@plr = player()


@hero = associative_array(
            'name': '§l§c3-D §aMa§an(DG)',
            'class': '3dmandelroygarrett',
            'sig': 'sYSUqD+F5toMdFwUGnnZ+o8jf+w/EHWQFfzRJB6zY1xSWh7gtJ8QdvIRqgMUZhaUfegqynmtWfcBGafQy0qdwBy3lwpMxz0k6ta+F3j7V4UaEv52x/zeqvITqCAemb1+rjev2wj/41lCP4NfmViCVSV37FyLFXkb7ZiiyPypm0V4e+qH5Gk/x7e6iSBWZ4osAz7PL45UVBR6C0sG1/kHU6IUWwJUG2699nJPdPAKgwFnY4qj1rFTGgIyupp8BUKb+IJKYDiHFxzhtedjI5W/2v98zAc/4OAyTBwF1tyEu68ILvdVuPvdz8Mx9k2RiZQsmqS6MUXXxXHyrMu29h1cnkHRnnrf3fHfZndSn5VqOs7z7HyPg+ye3aYhgh0YJXijzI2O+8Sl38AU/J9Ke2d9YvEUVSYuS5mj6v5CDKXcw/N7rjmBCxPSggcoJAkiUKZWLrbz2Rw1xByiwJhVN1JbRtZetFH82bK8bv7FoOEFMPaYkT9oqe+YMEy04NhB73+vb5BL0jegfL0AjfJo5BgWYF/89Rz4IgY9+mwA6cqpYq69NP+byqac7hS06uPr6ChYOJgv6MzEjwl5I4viU//AypWH5ikjX0kR+5ju54vcWtjhq67MBVdW6sMOzSYE/bE1D87CfAEPeiFHf+VqZkvje2MLZygXFPYiTizW9mSD1Vg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODEzMzY4NjI4NjQsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWY3YmViNGE1YjY4MWJjZmQ2OWM1YmJjOWM5NWJjZTViZGI5Nzk0ZDhlNGIxMzE1ZjNhYjU2N2RkMzJjNjIifX19',
            'trail': '',
            'op': 'false',
            'speech': "I will honour my predecessor's legacy",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/disguiseviewself"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 10 9999 1 true"
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"
            )
        )
