@plr = player()


@hero = associative_array(
            'name': '§l§c3-D §aMa§an(C&H)',
            'class': '3dmanchuckandhal',
            'sig': 'Xf6BFw6pPkHNfflBQkAwbGZnn49qXr+xbQ0zRO8PyLBPw01blCbMMD16N8hE2ZUzVPb+Ft/DqemvL7Md+Syv1rcH1ei+WetrXvFTDFwaUPmv31YG2cT/HI5V5Ers3n/A0xlk4N/rz3KzWYy9m0fGIa5oZFuBm3mtRFI0aCNLcU8/lujdVg2OBZy7xoMGLkfBR2xkrC0e6QNry5HmI14bq1B2euj2/5Hjh8EcpzT8bvfIYjbA1rp8RID9GgZ+pFARf0JZbJdTnyg8jT0UTf+QkTWjsHzsjMja6JJ2xkCGHXoFtbp1/6QghOXLhYzIHtCZWTg3KLPh9LO+2wZabStmWi1+WcFQTkmKIfKPB2QVmtsIllbfaIXzy2qVNZjnYK8GEZHbFczgBC87yLsXIy4HSM1+PjnWr+FoW7tXX5F7QuC6qPgIBLP1v60Mn7/PQHfZ3W5yRUPqhlB5DOffaoipu/4FkwZ1bgnXNrR064vHYE/8yJBr1zJcUrLa+KRTKnwu8VfqfO2gZDn30sQ0UglBIT7lFB36UtMpWWNp8hkT0q9RIWnsZtxYjdmz4ljmnuJ481UhlDS2qBvqy0KyW70kFk+InAw+0rEPPeIpCl0sP+BNsaf9a/UBuBk3FSL2Wi+V4NNLuV9vTbJN02nt58yVkMbYvDggl76kwW/gTB0KtIE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE4MTYzOTUwMjAsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjliOGM1MzY4NTJjNjk1ZDc0MDE2ZmM3YmIyNDA1NzZkZmVjZjg2MmQ0ZTkxZjNhMzljYzNlZTc1YjY3MWUifX19',
            'trail': '',
            'op': 'false',
            'speech': "Our abilities are 3 times an average man",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/disguiseviewself"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"             
            )
        )
