@plr = player()


@hero = associative_array(
            'name': '§l§c3-D §aMa§an(DG)',
            'class': '3dmandelroygarrett',
            'sig': 'fFdmGuQcW0TqMPmR/TE6CoVxeQtED6VGBonBpMZqRXDmraGZ2cYLMO81H3zh2xaniFbOGCEven/RR9vObP7vokvjIcHNLldEA6c6x13dN5OyHo1fXseas3tiaYCcDy9tak/0MG/2ZTwpENZT5Bd76MQ7ZMWThV8MFdNnhUjHQGN/yJ0fFTJPVpwNJrMJd+MBJyHZwiMeQjTj86p2+50X8+BGVtlKvxnKWjHk/9FQxUGVE54A5zmifV7hhtHCDv0MaTyLGmlhXpm1rys1zTH+Zi1BiQrCeQBaJbQP2fy1OzHcHvO+Vr7D0DDwh6hF766zZvo95NK3Mah4ANUOzH+NicwPuuR+wds5cWsKBEsiFg4PYzZten7FWCMBGt83hLSujJUU0RMtDxOfIm3KeffOkifNaL85EvtupyElKcFmlByhHq6hSJGrs7W4gmjhxHeXH3JEhAnyZBPit0m/R4viJrHs0zLxpUC/nCjQ3MqPmQOpNgMVsyKsiEX0YlF0uVwynFIZKH1A03GGlQXLDAlK/mgE+/m4UqCHy6SnHn68p5tJEMTLCyzwOxX8U/Zxp9JqmL1rZrom+6k5RkHOItjxD+3pqb6oOspA3+4RPLeyPYk08Q6BIjf4TTj3H7Dk7TNcTuzabA/qEAkZGdkMu5/fXuClFJjgZFkG2M5bhoaCScU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE4MTY1MzY2NDAsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjcyODVlNDNhNGYyOWMxY2Y5NjMzMDZkYThlYmZkOWRjMjJjMzNiZmRlOGE4YTJlYTIwZmFhZTIyZDM1OTRmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I will honour my predecessor's legacy",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/disguiseviewself"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 10 9999 1 true"
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"
            )
        )
