@plr = player()


@hero = associative_array(
            'name': '§l§c3-D §aMa§an(C&H)',
            'class': '3dmanchuckandhal',
            'sig': 'aTQDDeIoPzx7XHBd1bZfa7bN92m6ywbsXDrScXdy6uoz0j5n3ns27/ybpgBLotBUcvE1geqj8mT45gEGAiAHJIIOpJ9DRxOxcrhXLLNALfPI90TPQg8AXziqCSpWmip4nUAdOu1eShJMIT7CeGzQ13gqrlM6hEmduLvVJJ/E4V2W/fNyMfJnnl083g4tPq14RYiWOnHZTu4K+hTXt9LbC8U3KPqVhvncK+P+2kELcqPNGNCAdmDQP5/YgsEQcuFx213vXRoq5SV1ibBvgvG52u0FkRjQiYK5fKs0aw7F4ZAtceyh96FkHTuAkFCn4qgXBgCOdGq3TRe1VAEC2tx6Ga+J0hOpDZ+K1eb4wlHLNyDTFdm3RY48T2zcrULtsv8rKOl5Xm5172iyEdZbcjETITlaL0X3BpSPvYavGWbT1DYxCIyA3xJhPI3VwQsZD0420aB2nzC7Ilpo/+GxiFXkBM8v98DpXjc46tDxZEs3oJQnX9U0VL1KIkvn/rDC4ZGZ4ABIq5/h4CKkzvpzeVd8puNM0Of4xzJVzdTA4zwctoqQjTZeoNZ9MAEl0ZSQsyhdjPF8kl6icD+gZAPjcpcpIrvTlO6bMZbd84WAffZe+SbQvmDs/D4YChCj1v5ZPGyTNrSVncfwvycAtQO+tzG1PoL601EL9ql6gFCqR0gDQus=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAwMzE4MTYyNzksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJHb2RfRG9lc250X0V4aXN0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS85OTUzYjMwZDk0ZjU0NWU1MzZhMzY1MzlkYzMyYzFlNGFlY2U3NDc4OGM5MjkzOTUwODFhNTUwNjI3NTMifX19',
            'trail': '',
            'op': 'false',
            'speech': "Our abilities are 3 times an average man",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/disguiseviewself"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"             
            )
        )
