@plr = player()


@hero = associative_array(
            'name': '§l§c3-D §aMa§an §l(C&C)',
            'class': '3dmancc',
            'sig': 'Feh5qBfReZ/lLNJNETWpkNn7tHUd+mEnLYWqO5MLSKSvhAWUwUZ0blsog42WmR4hOjvKA2nzOpXuTj+MA0mVbkfLFX1fXwR0Iio0vUAGdihJsGPawP4GUONhIUsMqGly+Nd5fAYbXV3xElAEouKcJQcGvbm06KfakJO7+9+RxIff/7jaG4xOE2IsgyfHhll+tQSgP+pLqy83cP7b3Y60Dee4c2DBIvuBjCgKsCaSFPRYo1o7YmYcBTa8HQwNGzLuSIfCoU/XVkKkD9MZyjBIr3YsWEqUYJtD8StgA8Xwob/3g+GEd+uSLZd+VRJPEYLEQsbRohCpcmt9IhCJUG5Qot2JNk5hpXJx9cAzOQUzWeYAG9zIOWv9XGCSz/PmdrEu6U3fAfWseXtw4Fohktd2AoWY1QvLONc4Oy2SOk5Ib4XEj/PvQyriLBq5FuWFgamLdRbg7bu8L0SGgdWiaZDBW2JEj4k2Uh1d1fYAc9ngRQTV/7BV68qfQUWI4ODJKwOo621ZGeqCnYDR/k1q8leiQl+hmg/r+934ZU0ki+wRtVLSVikMoKCn0VJzoJlDJz6CFHdEoY0uCA0aCH/Ischg1tMRQZpMNdkJPxeFjZTrkBTaY0Oq8a0UH1Z95axD7yLRGMaiG+Fky7Un6pV/g+5PhnqgaiieuOIHMRnzgtAcHsw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODEzMzY4NjI4NjQsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWY3YmViNGE1YjY4MWJjZmQ2OWM1YmJjOWM5NWJjZTViZGI5Nzk0ZDhlNGIxMzE1ZjNhYjU2N2RkMzJjNjIifX19',
            'trail': '',
            'op': 'false',
            'speech': "Our abilities are 3 times an average man",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-4",
                "/haste 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/disguiseviewself",
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",               
            )
        )
