@plr = player() 
 
 
 
 
 @hero = associative_array( 
             'name': '§6Ab§eo§6min§ea§6tion', 
             'class': 'abomination', 
             'sig': 'kbmw84sQyNacNSPfEZ8gMlx9SikMcOP7DwEVQ0rVfhlF6SROulYAQ8bcWVBLg20cfWF7o2Y7sEncjLOuW7bUhvG1s4PzqXjgjUjoKhtdKtcULr0VuFoId3cFzldeDbbrjupxYKZOJt1TsB3VZE4Q2QVer9f0BNRSeV/GKJuh9ymTmk6N8I1n/RvEzQH6MIOot5Pczfg4Bvqo88d3my0C0ZHgJF/iReI+O55q8voSnr9YdTHnknESI1bxwazC3xRc6GofUf1S4GZMKnIQ8UcZ1ab4GM/6fDvQYZUHgHwdDoTO5w2OKkju2MJAZBviISQFuiXJ9f+G20GOBURxjAOmZs6wShVrfQ5AD/LdYxXeyCNMCBc6YjwNm5cKGkiU5MkiWi/1I04Qxpyz6I4wFRY9+zKjuiHR32YhIIDOBbfJc0VptPBY7+7Z2w5llsiY+cbJ9P76pUoVIcSaa4IQgOZ52LOYlzJxjI73Bt+DupsWXkJpPkm2gTl+CrGzZGq3e1rzO5/hfUYzs/aEkVFBsSD4Xotsej45WVGrgZNFryoiaRYYaiP+aI9+zIKw5oCTLjq50+bp3DIoWgBQ5VG6hpy9lVnmzpowrdgMd2C4xXFMlAO8anL0x9Ad9Amzivt5a4OKhfmfrSSeAkotZnpYTxI+1ziAcMGB7NlDrpt/1pc80Hg=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE0OTExNDM1NjQ0ODIsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWQ3MzgxNDZiYmQ3ODFmMWE1NzFlYWE4NTM2ZjkxZjhlYTY1MjIyNzQxMTgzOWU1MTliYjU5ZTE4YjA5MiJ9fX0=', 
             'trail': '', 
             'op': 'false', 
             'speech': "I am the Abomination!", 
             'powers': array( 
                 "/buff", 
                 "/jump 0-7",
                 "/carryplayer <player>", 
                 "/dismountplayer"
             ), 
             'buffs': array( 
                 "/effect ". @plr ." 5 9999 10 true",
                 "/effect ". @plr ." 21 9999 14 true"                
             ) 
         ) 
