@plr = player()




@hero = associative_array(
            'name': '§9Ab§7ra §dKa§5da§7bra',
            'class': 'abrakadabra',
            'sig': '"uRDCHoToo8GVK2F+S++TGqDfciSjL6urhG2wnGle1+04pEyxSqjOFBSQ+sILT7mEX0cOaipW7svEeRN5xzmDQ/tdzoKYFdmDTPsG/yAMPW0fyY8a0D0tRyh93SRtSrZlvbUADDRRcETxMD/j7U8ld+dk1/QVti4o3dYccN7By7F4Db3BgEYDrmCiCVF3VTrL1+Pesm/F7hTtglz/TBgrvAITlFSmdbBR4hSOHfBVfLtcQ0B5Y/3s7VTeY8UTmFOGd8OUsox0MTMIVhWY8Xl/wybBxLUkQQ21iYfXg0FtgfysfdNupO2tiprXxvMzNw8U2VTvQiEmsFiZLMvS6BEJ6w541lUkOrvMO7IhtKr8eHgYXNrJR7y/Ut3lH/annwLFcyzlPgmDyXz2bCJbAuKtpZOYoMINhY/JYzEGnnqv4EQsJjXOKtF0XFg4sMsllsAsthcGnjG2qKp//vvoHJWaxUYb0JqSU93NAJ+cwpbuywdR7aywcrL2YSjk+tPq6ejDIJW9ZrWuyp3/wStwz/vVsQXr2CjzCvu+3sQsglwAKAvDx6buFzUOMfCBgRWhAHeVQ/zNbPuzsfTN92VJD5CofC1ZBzvD5XPsP3iRBZSVE/Kuifprt8eE4ylHLP3FBTJT0JCaX+/u/he3uPhETHXo8YHW8cJMZyXAdoBNRhybsKQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTgyNzEyNTcxMDEsInByb2ZpbGVJZCI6IjkwYjJiYTZkNDNlNjRlNWM4Zjc3OTEyNmI2OTY5YTljIiwicHJvZmlsZU5hbWUiOiJXaW5nQXJtb3IiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E2OTM5M2UzZjZhZTI0M2JmMGNmYTI2OTk0YmRjOWQyODdiZjU5MWZjM2ZkMjZmYjkyMjliODUzYTJhNTg3In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Catch me if you can",
            'powers': array(
                "/buff",
                "/cast turnwater",
                "/cast abrawarp"
                
            ),
            'buffs': array(
            "/effect ". @plr ." 21 9999 9 true",
            "/give ". @plr ." minecraft:paper 1 name:&fMa&cgic &fCa&crds"
            )
)
