@plr = player()



@hero = associative_array(
            'name': '§4A§ec§cc§4e§el§ce§4r§ea§ct§4e§ed §cMan',
            'class': 'acceleratedman',
            'sig': 'mYrXTARg5n0hiNsR4tiyLe1qQtpsTPdrCpdDCpibkhj4TOiq4BPreLYKtJZuS796tKIA30eQrqegn99iLTHxWNdzYJV+SJvkTbnPy5ehFFkMPyLKjrqXgctS4DPoO/MHQrG6eXVmHoz7vRQwC4JM0t4RGQ7XGgC4z/tjIIjiv/+deUtmoGiC/ExqOPKynGSGKltZ+MDU79ssg5tX1uCokh9AofNDCeCxUGAHGqf+y1HhEqJth7Jck76wYU7aEYfVfN+8iT9KD5rphScug/I2tJLd/69m+u5QKC5uICpjYCyd0FfxJPdhmPFe9NKxCiM1qBM9U9NV2DK+kGfhcOQC9eWtkw7NgT2+uXKu4+IywW7flyr/3w86i0Aw6X3Hx3SBTcQl9RHN1x2YRPHWGh4rouvqYi+n200hQr7CWvKlSJBOaDB2bg7zm/OQlamDV2f+QDzXybnHSIeAyFhmRD7Kb6kJqUIzPUOymE4xQwKdOaiQvYBQjgwSUZ/5FmOSjx6YnOUgW+iSZ3OYTKHMmQwkiCnGCk+s9Q/5v2UI38zzQYJFzh4kl5c3L863TBmAj5KDU9Iramq4UFm2OPJnI3q231BBN37gXShpqY4XUUxBQJizxs8J2lJXV2CYQOBmH6wi2tvFGtLTPTggXSO9Kz9IAmHTfCU1zLMjh5VfCDk6R/8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTA1NjA3ODE2NjgsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJVbHRyYU93bERDIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS84MzhhN2I1NmNiNDliNjIyZjk1ZjE5MzJjZjNlN2MyMTE0YTg1Njc4YzU2YmI5ZjUyYmQ4OTYyYzVlZWM2YSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am Accelerated Man!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/haste 0-4",
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
