@plr = player()


@hero = associative_array(
            'name': '§4A§6d§ea§6m §4W§ba§er§6l§bo§ec§4k',
            'class': 'adamwarlock',
            'sig': 'KA9U/LeXhiZCMPaMQvW577sy7pyiqpHhvuS3i20/uDMlfqNyt2ehDyEOqEkdxrN/VkxwqY7fUDlGX9vmgKMRvZtzx8YHO0jC0415hU6lSUoph7rVpgBxxMQ8tJBF4Q21w+Ps+pQyyDws1r312V7KEece1DuYqbbIaZJMhU3vrWCYtZFfztOGEW05U2LQ4BB3tD0RG+TfuVitF3upcMjNKHhS4+xEvmrcKc7HuPVhLsoCL/A5i4gzDTK2BjYo5aN2rPkOkoQjuLYbpIE3SNOzaaGYPKNtKuOqF5Jbu4v7jhe00yOwjyt9eNAN9M2xVi7i8PsYmgqQZTX7JYOjMl7F9isWyklBbC8eACNf9x3KOvDBPYCMb1oBbXdVD7048RPliK4Z5NIdJRDTPMaHdQQw2B6J4LUrDQTCQKiWBavWoUUlTuq0t2kxYMUWGRJvxxvQ08QUL3KEBJijlB9wz0np4Y2UacOwThce5OvVZQevxOPedZkV8yN2tBJ+pD/lYX0VgnIvWDzikjaKd2tdcZShPig4tPwUzoeCVNEtpqVMfMxQ7uMWaZqS8hjEY/+ChFGNuhBJleraaJ72Yf3QMsy2WuJ55SbcEd+mWMdOhNNsDPH7hMI7BYRv/KJrjJWGd8C1uFHUAcrNZo9KvrUG6HNwevpwrJaIhUx4TZ5jAgMahww=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTY1MTQ2MDM1NzYsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJ4TXF0aHkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2IxZGM1ZmE2ZDU3NDRkOTRiYzk2ZmE1MWVmMjRiNThkMzUyMzljYmI0ZDAyNTY0OGJiZTAxMmM1N2YifX19',
            'trail': '',
            'op': 'false',
            'speech': "Don't force me to steal your soul!",
            'powers': array(
                "/buff",
                "/fly",
                "/intangible",
                "/tangible",
                "/cast forcefield",
                "/cast stonetouch",
                "/cast turnwater",
                "/cast forcepush"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/give ". @plr ." minecraft:golden_hoe 1 16:5 name:&4A&6d&ea&6m_&4W&ba&er&6l&bo&ec&4k's_&4S&et&6a&ef&4f",
                "/shot give ". @plr ." warlockblast",
                "/mgive ". @plr ." soulstone"
                
            )
)
