@plr = player()


@hero = associative_array(
            'name': '§6Orange_Lantern',
            'class': 'orangelanternagentorange',
            'sig': 'CWre6hMAP+X+P7y5UhmMcvaTJe1wROXYVjJMMgafsZRiQJwtv8L/On0ojgAV7TKDTrRHVadfcrflyUiPmceXaQ8jSdU6l+UwB5eVBXQ7SfiQHaZQktkL+1MwTO2ibTe0NrGopk6Gty3/2UdzWCNIM4dVZ78U93DKpJDQ0+UzqYjCFURELa0TFkLq6BWpDMWM6QG6/ZOYpgOeInB234PthZmEENj3CRseTVBSIH96/rVfMd4sD35aq1pxsuntWuXxJb6jWApyyx4x988m0ogm6PHSez1VDr3w7CbaaOG4gZ+PLQnfk5LDrBubUzP3MSZGN9vDqcIKw07zZJMpNpSdnrUn7lrRpjdyiAxy0jTMksUp7Iq2aDbKsmtXXs54DRDiSkW0oT1aAGItx2s05DKqVw/55gLgVq+99VzM1hdPFoIuDSa5H/hZBvgNuIG/YqWXlp319nWboi80fT11zD1QqMa72/Yl0veMnAQMPx3mkcBljNDps3NZ0jup5M5qNjVk3tPVkxt/Vv4VzAi2dT0KwlT6NeQ/LpLO0n6vxmBshbMCtuEkl2BPj5ToG0IFIMZPsvslnxupGIQ/GNfWzeSOL23LUPg+sBm0ev9tz0g/J/goxt6UEpbYTzFjIjNto8H8462apiD5XqiZKKu3gwObZ8Qn55tlKKPtL6PTZnWT79g=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzkwMTI3MDg1MTQsInByb2ZpbGVJZCI6IjEzZDRhMDk4Yzk4ZjQyMTNhMWNjMGU3MGFmYzMxMjRiIiwicHJvZmlsZU5hbWUiOiJEb2N0b3J3aG8xMV81Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jOTFhZWM4OTUyMjU3NWI3MDZmMTZkMzQ4Yzk2YjExYTNhMmEyODVmNGQ2ZmRiOTQxYWFjM2JjNmFlNjNlMzAifX19',
            'trail': '',
            'op': 'false',
            'speech': "I take what I want to take..",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-4",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." bluebeam",
                "/give ". @plr ." 95:11 64",
                "/give ". @plr ." minecraft:lapis_lazuli 1 20:2 16:155 name:&6Agent Orange's Ring"                
            )
        )
