@plr = player()


@hero = associative_array(
            'name': '§AAlexa §CBliss',
            'class': 'alexabliss',
            'sig': 'XimlhHXY80I0KB/5ovzv1Ed+VqcRsKSH5mSCi201uRbcAbqlZ4EzUEIdkupWQCJk7yxKOFm5/eRQvPVf8pZNjm7zIDnunmreMEq1cG/J+lhw9xG2KoXOP7W6oD0xtx41/pBfRZwVqKbHXdJAJjFrQKmsGxeZHB3nN8UYwpPKtHMi0XWAhLOOjo4JbTWG+swrJoqSK8tZ1B2qbdpZ6lZpj5AzkD0ST5k9gDq1FkjMP5vt8ebAenyWXXoiRWn5NktVmGYIuZ8NMoeW+fX2JXyf8LQXVaToju+MLSqtDcSUvEj4P9hiV0/lj0npy7BpETPfpx7m9tj5sL2F6Y8sjVOIxR2T5PFft6L8Pp4UzI5tz3XDNSqOlgkZ3fLmnThISMYoT1xHwwOHodt/6UgINsN56/Q3uONRNS8cFBksxDkNSJR3SRnonoexTb18+V7sZl0MhLjBN+3VEIBGkQjfxi7BFdyO9k7Uwv1snbTuY7DAXN6VaCX4qZvv7BEw+piYenGQAv/iczHkZruOIdJXq9jKBscSo2CBEiYMj6fBAOKWy8Q6o04RX0yc7ACRbS/OYMX7CARDwnnVMF5NoUcCcCW7iklXZwc/SBrNH5obkDvk51SGsF8PGi5UXTgz0LUXngjEcCljMZALNgL45Y46kCD6vVIxV2pllsN1hJ2vt2s345Y=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODc0NTgwMTUyODYsInByb2ZpbGVJZCI6ImRiYjQ3ODg3YmZiZDQwZTZiZmVjM2QxMDUzZWEzYWZmIiwicHJvZmlsZU5hbWUiOiJTX0hhcmxleVF1aW5uX1MiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jMTczM2E1MWEwOWU4NmNmYmZiNzNjYjBkNjg4NWU1MTU4MTYzYTYzZTJjYWQyNWUyYjJmNGRiNjIzZjY3OTJjIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Don't Bliss me off!",
            'powers': array(
                "/buff",
                "/jump 0-1",
                "/haste 0-1"
            ),
            'buffs': array()
)
