@plr = player()


@hero = associative_array(
            'name': '§bA§7l§8e§3x§9a§9n§bd§7e§8r §9T§3a§7y§8l§bo§9r',
            'class': 'alexandertaylor',
            'sig': 'hZW2H3t6NVRNzIdNMo6oSg0G2XsYI1V6o3+6gxK5/dVznypIwIC0iffOewaiN3kK2v+r3b2FNJusR08zmtauAc6mG+6DhAIf2I2THCnZbUub8ENwUgfp1VTT9Cs4Ti2xiOdABqyKlurtXMCchRzO1t1U7xDqdJPfvbJXIt5fTPvxWWa3VJK9Lzvqa5CcDRbg3wviCX8HviAjRsm3gDGOQpTvs0SVvzoH8AChaqgGqj/pCtbiVDRW6t/daLEug7mIwTD1IHWzbEXar0dydGwanDimsycSp9fnOWbr+1uIYadz442EHWol3UjkmUmw0bBN0av6mdSkHiy5+Mve4x0zRo/vMCbjHFhHJEGlqKKH92j02M3aQzfdiCOtpeq3vYE49lTzNPW8fW/fqf9L7mp6mijxdY1L6E5PJVg/JTZ2RNOmQUgJVGmT5brgjMCvqERoNgnLvmNxAHkj53gs2dOd5rShi16ZZz9d2d+mkGEyBtt9urYWp8QtgfR1W3BZkSHyaOcf7FVrVOBEZ0Jw9UDGrPMwwyGAdfqEZHkHOsYIAiiBPKYknm1/GYouibdsaEfgQxJvkmbIXXow3Gfug0/RsaEHb239rmnRA50Y2kBIaHIDGQjmM3Xs2DBXvzvTIACZn+vHQuAOSX9E/tB8jypvKO/Vb2ckXI1GR//GjN3295c=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcxNjUwNDY4MTUsInByb2ZpbGVJZCI6IjVkYTI2MDkyYzgwNzRjOWI4ZDA4OTUyM2Y3NGRkYzk3IiwicHJvZmlsZU5hbWUiOiJNYXN0VGhlV2lzZSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDg0ZDM1ZDU3MDg5YzI5ODY0ZDEzZDc3OGY3NjQ1YmI0ZDdjMTBjNjhhZTg4NmEwZDljMGU1YTQzY2Q4ZmQifX19',
            'trail': '',
            'op': 'false',
            'speech': "Let's all be fair here.",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-3",
                "/haste 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/disguise",
                "/create",
                "/lightningpunch <on/off>",
                "/invis",
                "/vis",
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"             
            )
)
