@plr = player()


@hero = associative_array(
            'name': '§3A§fl§bi§3c§fe,
            'class': 'alice',
            'sig': 'W0Pyd4oXnJ5bTLYLfW1mY3sxbaQqjgNW6pIuwkI00gBsOi3kxvZT90jihuY6dxdU84TsbvI+vgBD89z0k295HkIbTR2wYOWYMN6dqAWaP0S9q7gpL9KQG+7MGkZEVy66bP37TdUeYWZiAxsfXw+hSy45V1Ktebj35hXasHYZ7KWDJR6lG/iUMqKeX0tm+cRWzWYJ+ujqrNtyK2edj3ecoRfB8PGoi7nt9+TDTR/WnDlJYDilt4HRpyguYIuhHB3q1Uy68siF9y092/EuwI8KddVN4ovSiHcV3NEJrY9X5r0yAZbmA/4Yr/PNxWRXTCr2+cAE/UvNNjs08aSLcEe9jKucNrySYbY4eUUVCZ9UI2JP6hPx6UJa/GIxwJnX3l8A7bBcChsTOPMWg1PMGtCHdTxbuoUJNDY7SpV3hoNiVXZHXOW0/M5dWKfIHVl3qLwDG346VsSsi4XH8swClMQ/GEjCAhjXbnWwH4yxEO0Xg6uIMUzRx2rHszXVwj8QJow+A3yYpqaSZ+0PlGwmiBtU1ViAkgVojBNPsEY2VcE3ORwYKHtFnXlV19rkrwmYW/cbRMHr6uccc32QoeqcD+9+276y8qRRu/qRPiozPhexibM60oHeOmYMmBQZs6hwOau4Te4UxhAkCyXTOk6FhnzEt9JkTgrXybBQRFPF5SqcdUc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTMxNTAxMjk0MjQsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJMb3N0SW5HYWxheGVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2ZlOTEyZTRiYTg0ZjZiYjEwNGRkZGUzODU3NGYxYjQ4ZDI3ODEzYzI3NWY3MDc1Y2ZlZmYzMjVmZGFmMjEifX19',
            'trail': '',
            'op': 'false',
            'speech': "Curiouser & Curiouser...!",
            'powers': array(
            ),
            'buffs': array(              
            )
        )
