if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§3A§fl§ei§bc§fe',
            'class': 'alice',
            'sig': 'W0Pyd4oXnJ5bTLYLfW1mY3sxbaQqjgNW6pIuwkI00gBsOi3kxvZT90jihuY6dxdU84TsbvI+vgBD89z0k295HkIbTR2wYOWYMN6dqAWaP0S9q7gpL9KQG+7MGkZEVy66bP37TdUeYWZiAxsfXw+hSy45V1Ktebj35hXasHYZ7KWDJR6lG/iUMqKeX0tm+cRWzWYJ+ujqrNtyK2edj3ecoRfB8PGoi7nt9+TDTR/WnDlJYDilt4HRpyguYIuhHB3q1Uy68siF9y092/EuwI8KddVN4ovSiHcV3NEJrY9X5r0yAZbmA/4Yr/PNxWRXTCr2+cAE/UvNNjs08aSLcEe9jKucNrySYbY4eUUVCZ9UI2JP6hPx6UJa/GIxwJnX3l8A7bBcChsTOPMWg1PMGtCHdTxbuoUJNDY7SpV3hoNiVXZHXOW0/M5dWKfIHVl3qLwDG346VsSsi4XH8swClMQ/GEjCAhjXbnWwH4yxEO0Xg6uIMUzRx2rHszXVwj8QJow+A3yYpqaSZ+0PlGwmiBtU1ViAkgVojBNPsEY2VcE3ORwYKHtFnXlV19rkrwmYW/cbRMHr6uccc32QoeqcD+9+276y8qRRu/qRPiozPhexibM60oHeOmYMmBQZs6hwOau4Te4UxhAkCyXTOk6FhnzEt9JkTgrXybBQRFPF5SqcdUc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTMxNTAxMjk0MjQsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJMb3N0SW5HYWxheGVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2ZlOTEyZTRiYTg0ZjZiYjEwNGRkZGUzODU3NGYxYjQ4ZDI3ODEzYzI3NWY3MDc1Y2ZlZmYzMjVmZGFmMjEifX19',
            'altskins': array(
            array(
            'sig':'rIc2beKZTXq/v/k8xnq9b9UyPLCb7142t2o6YkdvugCqcOPT0uN6y8xOHAi1cku+hGpQNbzPEFVuOrLj8Ng/wGWCgO1ntzylTWxTX9AGSisL9Vo56eRkZBWuTmWtnVCw959eSTasaTK0/bhLMm5+xp5eQLUcf2C5krW7edDLszvdZ929bDNbLoKqTzy7GA2w0Qq0mmGZmch7GqAY+3BOFDhAp0YnmZXRT2mGZcpylBDBoDTgd2GxCrlg5opiihRBm/gVdxnuA8v/YWWuVZqBiweBcL04kcSD8wfHWYy88wWH0ujzE5/ux37dM1RGW9IL3YuUk7+ytrTFHjP8FpkqTZ+k/JZJOvqP7uc7dXTkVdfj4tljddY84kHTcz/XMu+d291BdPPkrKwiNMHFsaXWEsrnEouwrPlFvB51HTvFip6qzQnxZje3Nj75bddidKNwDg8IU1wb3cehGUDNyA9v41spcDITCYcXWR4fIep535P6C/xhxrl3A8PXJDUBniIthNZXKmgS0rG3NW3OZbnV05NW/uMcq4kxDpbC1ffQckBeRv8g+Mt6gQzHysJuGWcEHAE5uIVhZ5LaxWVGghxFwo0qpOzvLU6/GSL+a9bBIoO5dZZiznqp5xHbs+DjfY1eHbnsOMYV9URtgpHHnyxVgye1vxtY8hIH6+UD5y78C8M=',
            'val':'eyJ0aW1lc3RhbXAiOjE1MDQ3NDI0MDMyNTgsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJpaVNpbXFseVN0cXIiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS84ODU0NWE5MGRkYmQxZjc1NmVjNjMzNTRhNDFmZTMyMTRmYTdmZjJhMjg5ZGE3MWZmYWUzZDU3NThiMjg3NWMifX19'
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "Curiouser and curiouser!",
            'powers': array(
            "/buff"
            ),
            'buffs': array(
               "/give ". @plr ." minecraft:iron_sword 1 16:2 name:&3A&fl&0i&bc&fes_&3Sword",
               "/give ". @plr ." minecraft:iron_chestplate 1 name:&3A&fl&0i&bc&fes_'s_&3Chestplate",
               "/give ". @plr ." minecraft:iron_leggings 1 name:&3A&fl&0i&bc&fes_'s_&3Leggings",
               "/give ". @plr ." minecraft:iron_boots 1 name:&3A&fl&0i&bc&fes_'s_&3Boots"
            )
        )
