@plr = player()


@hero = associative_array(
            'name': '§0A§8li§7en §2X',
            'class': 'alienx',
            'sig': 'DXya/9OFlT+htm7qpzwoB7sfQwiXIIzp1Qvo1ADdKmqczzbhaN6nAxbHXntcT0uX5oZJmr/UK9O0MFmEzUwoKnM+nD52Z4eNa3HhwbbyibIFE+rm9Qr/j16jW6ON9SLfeBZ05zV9WirHfbzdBIwzhVkp/jccOfP8inYmdwBPDqOMNkvCXM57OPHRVBDv+jn6kLp3u+nFxTDHgdibYDl+EVSOar+/XS9IQhqAp8+L3WHt8KJcLI0x2ub+KMGmy2hVfHbNOpEnDWMMWKq0f1GFdRpdI+eaYZil768Z9OoyBuTogmJW+Q0/WN/i8XxiJ4wRFRhnnptBRfpPhJyk94ni2TXMWMXbZ83padQCO38cyFPwHsPPdJx9iSiZ+GIDiDo6Y0TPM1XEDQZweHSmaWy1YJ6UNDcQE7RheN5+s8m+YXZNBbCTo7LfoB6NCXB3nwcIyDY7Oh1hxU26Ja3ZG0Dy7jv6/1NcUK985u522OgUHwOkSXfm/PlK7TSkFAWxobtXxsXHxLNHTviTiNnlklC4TwZCNNNz5ju4kevJ7dt0h7btHq0i8CXBbL5rql8gC7ZNYE+Kqk5yWAP4m+CInSK6YnjPrbdgm6gi55nm5JpsbNekXgtG9KMwhnZSiz9acDf+aCeg1Z1oibK/rfGR3Rs0gLz1Jyxsc4eg+eLxFUjYaFk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcxNTk0MjQ0NjksInByb2ZpbGVJZCI6IjkwYjJiYTZkNDNlNjRlNWM4Zjc3OTEyNmI2OTY5YTljIiwicHJvZmlsZU5hbWUiOiJXaW5nQXJtb3IiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzEyYmVlNThlNDc0MzcwNjViNTllNzc4YjNmYjBkYWQ2OWY3NDFlMTllYWRiMzVjYTk3MDlhYmE2YThiYjlmZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Alien X",
            'powers': array(
                "/buff",
                "/cast freezetime",
                "/tp",
                "/depower",
                "/fly",
                "/destroyworld",
                "/mindcontrol <player>",
                "/stopmindcontrol"
                
            ),
            'buffs': array(
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 5 true"               
            )
)
