            'class': 'alsahhim',
            'name': §7Al-§8Sah-§7Him 
            'sig': 'KTf8HiVWoiUdCQ1QIHWXIWvgkcclh9CJDWlfofiL9/ujVGZFGClZZeuHdbf8+hpw+UBV62TZfXNCPu6dH+PMZD5nfmYiFpLRSXGitysqiugutamG/ddBPN8gzhIB/rtdF24OriLPdZl+aosz9RE1FtpQ4R26ToO5oVcxgXyXlGlj6kyP0+mQkSymoUBuCsT3ho6tZuSaQV0YGsMowAcxHkFB3Jic5BX4VEPgBKOQQNOEEfamNxowPtqevK4VnZ3NbwNQ3xdnpgWJNZINFXte2ZhSmuTEZZ2eHN8/THu//80MKM9vQw+xUDSzAeto+s8ixrU2Uze8wj48DHKlW+S4BPDr78jZCwQTIdolRsOoC++nSqJmA0tU0+5T+7Y/kPUIgaWAouNqK7Htoj04N8M5GUYrRfAyPHyj/HV41EB/r4FR2O9nKSlvl4YjTM0i5xbQAqqWYEeCuIUbKZIv9MXVcxA6Dj8aa2RrqBf3jnRpGbWeHVBrgVrdoWJj2J4B0GN1ZpOOYjUbD6GnkeLFj254coZ4taqgJKqefPipLVcw/K/iQTL6TWLUHJwFoNYzsMT8rtqBtEwgVpP2dgC9Amx9PUHsWR9bXN6DE9eiNn/VzsUdwuvdwNwSh5yTUUGGpOlZzEKCgbRmQv+3B/koAc104+YYnTTv9R32tRguxaLwBhw=' ,
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODU5NTI4MjgxMjAsInByb2ZpbGVJZCI6IjU1MGIwM2NkZDllOTRjODliNGVhNDRlYWQ0ODljZTBlIiwicHJvZmlsZU5hbWUiOiJBbmltZWxHaXJsIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82MmE3ZjhiZmJhN2Q1M2Y1NThmZmE2ZjFjNWRiYTEzY2FmYWUzYWViZmEwMjZmNjFkY2FjYzZlNGUzOTkyNCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Oliver Queen is gone, and will never return!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-4",
                "/haste 0-1",
            ),
            'buffs': array)
                "/effect ". @plr ." 21 9999 16 true",
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 1 9999 1 true",
                "/effect ". @plr ." 3 9999 3 true',
                "/effect ". @plr ." 8 9999 8 true",
                "/effect ". @plr ." 10 9999 10 true",
                "/give ". @plr ." minecraft:iron_sword 1",name: &7Al-&8Sah-&7Him_&7Swo&8rd
                "/give ". @plr ." minecraft: bow 1",name: &7Al-&8Sah-&7Him_&7Bo&8w
                
            )
        )
