if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§8A§7n§0a§7k§8i§7n §8S§7k§0y§8w§7a§bl§8k§0e§7r',
            'class': 'anakinskywalker',
            'sig': 'naRYUijxLf/XYpswBNC0xOOn5Vq8/hHdoYj1efm8uxuLWMZ4TDsgTMqG3DEUwj+4I/NJ7RWhlP3sv1YFIpHSq5Se3yJ7jpiCM+YcRkuNI7lyeBzAswhAhg9tt8g71LYEIpNM7lgZjGIOm+vdLHEHfcQGMIUF3wLTgsm6GeYRyI27PNIWmZnLZm3thZoOBiMdIl/uuLzaI719AEdWeGPrD/IROpgs9eOQAAZiN8yqB8IJDBM9SFR9N/L95Sdw3qImUjBlcxv9Y1UCQtzHjoJQzcs0P9YnKNwSCfjijdRefRuev8duch9kuIiC1BEftIbOb/5T1VotwKyV32W+HR8SJhdIpQKvmIyBcZ/Wu4EIuPuPTdF5xmtQ6fHwQMp/OGEpUFoXUbx9D3k6/EyezD7oOjNrTbe113kHhP+hvIAoIkZDJ3u7TTlQq4A3I73BvXRJXK4KIK683OG60whpJIZEzJU7J0jAxNd+OMW3VbuRTO4V8JK5xh0siBoPOXp/4oKhlIp2d3fNbPT9qNO54PrS1WJMbtHsU8QzIVTCBuJ2pokPHUHplVmJ97JzmW/Qjg5h7/X+NSvmEUpK8lCfXgtZMQsUtLpk3+MjLfSAZp1+MSHLWBB1sdz0GqPK4GH9SG0K9Q5Cmx8hwxW4jwmZKsOn84UnqxC9Tz2BJR9JcQECWrk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDczMzAwMTMyMTIsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJIZXlJdHpUb255Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iMTg3Y2RhYmZlZDVjMmIzODY1NGNjNThkZTFiYmYwZjU4ZWY1MjNlNTg0NzQyNDJkMjU3MmNmNDUxMWExYSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "May The Force Be With You.",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-1",
                "/forcepush <playername>",
                "/cast forcepull"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_sword 1 20:2 16:100 name:&8A&7n&0a&7k&8i&7n_&8S&7k&0y&8w&7a&bl&8k&0e&7r's_&aLightsaber"               
            )
        )
