@plr = player()


@hero = associative_array(
            'name': '§bA§6nn§ba§6beth Ch§ba§6s§be',
            'class': 'annabethchase',
            'sig': 'myCDFFE/uzaEDYi1k5e+Xeo1u2xTewTQbvzC7sKqd6TkuOXjTTO/tBFNs/hSm76VJHDromsr+kcCCmdDka7xWCiXLnyEdFhhHBX0GPgY52/2Dn8gHddo1gDvoY562eNzoEKyK1m/K6qYcAOKfIH6GTVUGvuWL45L1XiGlcK1WNgpz3bm9s3srdI5ZsG4nF+MY8jCSHtlvwwI2iERP6gW4/fRmXEY/zKbpCjHVRY7WzVivSlO0IQ8DUiBmUA/V1b2DsWsIjOWGBd9i9dFABPQCy3APVsoVFjzQG4eGyZqvdshN6N75KdD9mTVN584wLa8jXdrwLktckmL6h1he2wy2iy+NVNDFBVqQ/OoIv6IGx5xrLimKuh5OL+2p/amqmwTsRR5iZ4c6WvdWUoTRO3qaxXzw2v69R+cehdxP0EtW4J9K1D61YxDZLWrVgvKtZ9ErNJ2frUI6DCbE9BHbf/mhVtGC6hgOXDUU4/M/yS/7izz1Q8MHpik2BNfr7q21cxRIvZHq9bkwachRPo/A9RH9/tj10XhYYbM85L4yPs2c6XfQdtNT9vh09bkbYi8nddQ5iNIIROQ416kFZeLYuR51SujIuaQQJVvL/sCNODzG7MqXL0pcs9e+qsRXoiBe6gUtJRrk3fMyqMr3Pdbto8txV7/BoRGrZSmTpB7M+A/HtA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTI1MzI5NDU0MDEsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJMb3N0SW5HYWxheGVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQyNWI0MTkwY2YyNDIxMTVhYmRmZmI2ZDIwNGQ5ZmQyYWIxNmVkZDUzZDAzYTExOWQ5OWIwYjExY2U1YTExZSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am never, ever going to make things easy for you, Seaweed Brain. Get used to it.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 14 true",
                "/give ". @plr ." minecraft:iron_sword 1 19:2 name:&bA&6nn&ba&6eth_Ch&ba&6s&be's_&bKnife",
                "/give ". @plr ." minecraft:bow 1 19:2 name:&bA&6nn&ba&6eth_Ch&ba&6s&be's_&bBow",
                "/give ". @plr ." minecraft:iron_sword 1 19:2 name:&bA&6nn&ba&6eth_Ch&ba&6s&be's_&bSword"
            )
        )
