@plr = player()


@hero = associative_array(
            'name': '§bA§6nn§ba§6beth Ch§ba§6s§be',
            'class': 'annabethchase',
            'sig': 'myCDFFE/uzaEDYi1k5e+Xeo1u2xTewTQbvzC7sKqd6TkuOXjTTO/tBFNs/hSm76VJHDromsr+kcCCmdDka7xWCiXLnyEdFhhHBX0GPgY52/2Dn8gHddo1gDvoY562eNzoEKyK1m/K6qYcAOKfIH6GTVUGvuWL45L1XiGlcK1WNgpz3bm9s3srdI5ZsG4nF+MY8jCSHtlvwwI2iERP6gW4/fRmXEY/zKbpCjHVRY7WzVivSlO0IQ8DUiBmUA/V1b2DsWsIjOWGBd9i9dFABPQCy3APVsoVFjzQG4eGyZqvdshN6N75KdD9mTVN584wLa8jXdrwLktckmL6h1he2wy2iy+NVNDFBVqQ/OoIv6IGx5xrLimKuh5OL+2p/amqmwTsRR5iZ4c6WvdWUoTRO3qaxXzw2v69R+cehdxP0EtW4J9K1D61YxDZLWrVgvKtZ9ErNJ2frUI6DCbE9BHbf/mhVtGC6hgOXDUU4/M/yS/7izz1Q8MHpik2BNfr7q21cxRIvZHq9bkwachRPo/A9RH9/tj10XhYYbM85L4yPs2c6XfQdtNT9vh09bkbYi8nddQ5iNIIROQ416kFZeLYuR51SujIuaQQJVvL/sCNODzG7MqXL0pcs9e+qsRXoiBe6gUtJRrk3fMyqMr3Pdbto8txV7/BoRGrZSmTpB7M+A/HtA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTI1MzI5NDU0MDEsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJMb3N0SW5HYWxheGVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQyNWI0MTkwY2YyNDIxMTVhYmRmZmI2ZDIwNGQ5ZmQyYWIxNmVkZDUzZDAzYTExOWQ5OWIwYjExY2U1YTExZSJ9fX0=',
            'altskins': array(
            array(
            'sig':'wL0Syw9qekJAhSURflUnJkO0PTzRUN8tMk6LB1QZUZeMXt9+m+Ky8EpyREUriruTT45CB4dA3vUuhk8IFzDKGnAT9oYezcbN4YQoaGiDeZJbgIVJoiLMe04I9RtfZQWfp/OKbONItUcG6W/Pmaq29KUdhKt+YvMNdLMm0zhqyyGbT/+YorUtn9fvSCi9oQt/+DvfgsF2tduVy878PYhiZAnGWvy/C37dxmWrPu6TqMKfogFxm/lU60q3cDdUKA3FoG/U7Bv+Oli9NjVDa01Shnmqdj2z1R8aq3jBuGbJOF0f7rRGJ7evLd7Rre6pTlgJ/taJ06A1rTaaSUpjUuWJYWReAXF5ex/c/g3X4a9c+qXdiH5uYkG5RMOIe8z2oRz8jn6Bky3Sq/88CoqU/8d/JlPOlDtjfZrjLpoiEToAJptIDOnjV+/SDIsTUYfB6WVUNSIRBhEMbEjVQMYKDQ5adst3En0qcLik1c5HbNiD2e4LanU+dnQl30eWqhjDjYJrSm6b03/bHxrnPqbTd8D70ae+8PmJc9c7AK1HxVIJQbgtlp4mu12oCOmza+Mg4vZ0dQ8jp0hb2pHzHa4AdXq+MSzbrXu8z9esjh5lF4hIaimpr4MOsqvuuV4i6Z7z9yL2ipA7Y3+LwH6sjYg18ja2sKhI4GwOy9wKhps4b2CIKPE=',
            'val':'eyJ0aW1lc3RhbXAiOjE0OTU1NjY3MzExNzEsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJYX0Zvb2RNZWF0SGFya19YIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2I5NWY1MjBjMTMxOWRiYTliYmNiZjM5Yjk2YWZlN2U1OWE1NThkODlmNzZiNzY2YTg4OGRmNjQ0MzMyZiJ9fX0='
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "I am never, ever going to make things easy for you, Seaweed Brain. Get used to it.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/invis",
                "/vis"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 14 true",
                "/give ". @plr ." minecraft:iron_sword 1 19:2 name:&bA&6nn&ba&6beth_Ch&ba&6s&be's_&bKnife",
                "/give ". @plr ." minecraft:bow 1 19:2 51:1 name:&bA&6nn&ba&6beth_Ch&ba&6s&be's_&bBow",
                "/give ". @plr ." minecraft:iron_sword 1 19:2 name:&bA&6nn&ba&6beth_Ch&ba&6s&be's_&bSword"
                "/give ". @plr ." minecraft:arrow 1 0:0 name:&bA&6nn&ba&6beth_Ch&ba&6s&be's_&bArrow"
            )
        )
