@plr = player()


@hero = associative_array(
            'name': '§4A§0n§4t-M§0a§4n',
            'class': 'antman',
            'sig': 'iL3dsBePI026HHrTU1uYcdCcO0CB/nv5Z1zaSITdhcvrSx8r9nQGx4KXF5v7pDaTCeMvNPjvk1ABzWMNzy6zyhhtpE/rPtqKkmhBzpPyj1VqtG/afW6WEz+28o7jKbC559R/VFCy64IwIyEW68DZ43ZRIsEEce/L+B2e2mtchaVAULid3sq1Zw8q+oRXwm6vSUVgZSMl47yB1t37AW2j1YJjmW4znAw65VFuNxsS4m1qi5QeXLPB0CX2sArHFRHnsLDUJNAhp7Z5OgTBe1kFQRtNPm3gIFF+nbOcqhq6cgKBP32b6+yjK3RPWg348fMyo/TDVzBla0TKaF1f5BAxQVN5A4T3MF+gRV8Ch0X2f3l3orsfHxerT6E7toVK0drJNbTUwSaERz2RqIef353aOqPFGAScTmR5GLlMRRhoWXVDOCHIdS8+TTYuRaHPZh9TLqBuSXMGBMwaEVMDfWlTD1CPsfQ2MInbzY6yMGtuxm8vxvBxsnbhDlbd/ROYhXRQf4R9eMgamGCY/STCmzBKGGMNtZbXpR6X64wPXrBHth/rvo6h+U5iaxNjtQqIrkWlbDl6k17zvQG113Mpc0p5Tg1scZnH2HlOPDalir3ka0FrjJ2p1TJoMbsw+1f63T548DBF8GerXnUY0gC2CklGTLHck56Sj6y+F3uAYVEmIXw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTExNTQ2NDksInByb2ZpbGVJZCI6ImI4NThjMDk4YzI5YzRhNGM4NzY0NjJhNmQ5NDJjOTE2IiwicHJvZmlsZU5hbWUiOiJBbnRNYW4iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzliZGIzZjA1MjdhZjA4ZDhlOTQ2ZTQ5NzY4NTk0ODg2ZDNlYzJjZTJmZDJhOTg3MTliZTI0YTdiYTc0ZSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Tiny, but powerful!",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-2",
                "/carryplayer",
                "/dismountplayer",
                "/normalsize",
                "/grow"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/disguiseplayer ". @plr ." villager baby"                
            )
        )
