@plr = player()


@hero = associative_array(
            'name': '§dAphrodite',
            'class': 'aphrodite',
            'sig': 'W4lj/mZSI+D8zzIJCDv9MPgH0hHfj3/wLgEI5oSWo2DSbqK51P3SrjFvGSvwWSrNnBBRMeas1eMl2c/Y+AkKVndCH6np3+Qp3tnqISEDVDKQtx9UGQYcTk58n8wNfXuV6g+MlJw76E+xT5NOdxREWIrgJQwX16O/48BocG90OPS9/ToUh7wigslXeK2ksI7NuxPw0nqoDDwHdpKZmmee+0L812dCYBvvQhwReBI4Oj+Y2ZFqVs2YF+cZUSzagyVorJBNKWcK9OT/mTT7Z2r8g2UFyUUBvb2GShZagmfnl4mv3NfmMst1mpQNkeLtzN6GE0nKEFnRzXMzbqR/IPNjvpdWYwkhTa5yswapFQbi1+GkCKAlXTe/pwN4H2IP8J4yLzd46THlniVdhmwRNYcz/Fcn+iL56PiN30DdyPVY+V/FRFwy1aY7GhEG52w1N9rFuuHMJY/TMQjHvRdO073T+k77l2KOSNiAzwE+AQr6YLNuObMY78JBSE40z0RvN4Cx17vgoN7b2r1JXIxRnbPr5Ud4+Wo/6ilEF3pPYbZ4s7E4JfS2b/SC45u2xx8yIF9LlaSAacBn/g1XtRqvEquK/3Xn2KizKRLR87DN9/56hb63c5dOFKWUWKI5wiVmdg1/o8u4VuYRc9Lgp8g2vmmxPW0NYmuo6H0q8jFMD7v+VFQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjUyMzE5NDksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81NTMzNThhMTNmYmE3ZWU5MzQ2MGI5ZjUzZGMxZGIyZjY3OWIzNzdlZWFiYjg1YmJhMmJhNGUxYWE1N2E3NDNmIn19fQ==',
            'altskins':array(
            array(
            'sig':'hs7DmyHTUYvKGJ/msWtztvC3kh7B9nhjohHEKCmipai4rpkzMV29mGgTRGYdYM5/gIebZtoaXy/ZsXM2+kf94dPZRbRTLP8+y7rsz3bPgyDwcSaXh2Z/gE6uNREziPF6eWr3TEUMZYqhdEaZLhVZZemHJ10lSNyfYiEsFKUZ/f0qUAAcCJwCWmPensgpWt8xTIuwYKY3lU2u6Lz6VFkfyq/PCFJ5gx5Nngfcms9ubwf5gOos1vgCvpCx846+s+eKT2ge7UyRNDUQHWjas9dLPlunsa3XmovdUga+UAjf5FRUPI1nm9BAj8AcAiaY5TL0jMOIkOEQc2QGQR1CjfQA/GHAVLehvWGjToRghDSTrRA4suNmd/mZb8DUKrh8KpKndyLXC8L0bksWZ8GGhGfbxobqwFUAiFJ21udKd7jUq4VyQVMsgV6q8Ntw9utdsUWNpD89629yRBKtB9eesIQc/qqpLKH8zWELVEdKM5oyLNoaZ1Slc+09tFicNqncrEV58Z1Sr7/MmFAtuF8ENWQ2ExXYcbbbdvvsBdKrMEMf6dnyMV/eOuYz/iGeDWcgZmck/G5z9abtvbhA3Fsoj1s158ZaLhJ0a/Z3a+Tf7cXIEHlmS0RQYD5j4FCzo15ubxuSoI3sPCMtK+UcjqDjPrU2HEAG56tOvz4aQqUTtV4uQjQ=',
            'val':'eyJ0aW1lc3RhbXAiOjE0OTQxNzQwMjY0NzgsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJDYW11bGxsIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjUzYTk1M2RmZjNlOTIyNjc0MTZjNTRhMjdhMmMwZWE4NDc0MDM2Njc0ZTZjZDI3ZmJlYzQ5Yzk5ZDIwIn19fQ=='
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "I don't care if you're a boy or a girl, you're still cute ;)",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-3",
                "/fly",
                "/flyspeed <number>",
                "/carryplayer",
                "/dismountplayer",
                "/healing",
                "/healing <playername>",
                "/goldcarrot",
                "/seeds",
                "/wheat",
                "/carrot",
                "/meat",
                "/fish"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true"                
            )
        )
