@plr = player()


@hero = associative_array(
            'name': '§dAphrodite',
            'class': 'aphrodite',
            'sig': 'W4lj/mZSI+D8zzIJCDv9MPgH0hHfj3/wLgEI5oSWo2DSbqK51P3SrjFvGSvwWSrNnBBRMeas1eMl2c/Y+AkKVndCH6np3+Qp3tnqISEDVDKQtx9UGQYcTk58n8wNfXuV6g+MlJw76E+xT5NOdxREWIrgJQwX16O/48BocG90OPS9/ToUh7wigslXeK2ksI7NuxPw0nqoDDwHdpKZmmee+0L812dCYBvvQhwReBI4Oj+Y2ZFqVs2YF+cZUSzagyVorJBNKWcK9OT/mTT7Z2r8g2UFyUUBvb2GShZagmfnl4mv3NfmMst1mpQNkeLtzN6GE0nKEFnRzXMzbqR/IPNjvpdWYwkhTa5yswapFQbi1+GkCKAlXTe/pwN4H2IP8J4yLzd46THlniVdhmwRNYcz/Fcn+iL56PiN30DdyPVY+V/FRFwy1aY7GhEG52w1N9rFuuHMJY/TMQjHvRdO073T+k77l2KOSNiAzwE+AQr6YLNuObMY78JBSE40z0RvN4Cx17vgoN7b2r1JXIxRnbPr5Ud4+Wo/6ilEF3pPYbZ4s7E4JfS2b/SC45u2xx8yIF9LlaSAacBn/g1XtRqvEquK/3Xn2KizKRLR87DN9/56hb63c5dOFKWUWKI5wiVmdg1/o8u4VuYRc9Lgp8g2vmmxPW0NYmuo6H0q8jFMD7v+VFQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjUyMzE5NDksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81NTMzNThhMTNmYmE3ZWU5MzQ2MGI5ZjUzZGMxZGIyZjY3OWIzNzdlZWFiYjg1YmJhMmJhNGUxYWE1N2E3NDNmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I don't care if you're a boy or a girl, you're still cute ;)",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-3",
                "/fly",
                "/flyspeed <number>",
                "/carryplayer",
                "/dismountplayer",
                "/heal",
                "/goldcarrot",
                "/seeds",
                "/wheat",
                "/carrot",
                "/meat",
                "/fish"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true"                
            )
        )
