@plr = player()

@hero = associative_array(
            'name': '§3A§9p§3o§9ca§3lypse',
            'class': 'apocalypse',
            'sig': 'KE7H83A+MQQyqdtj28QsQqVv/m3Y/fgK2ln3bP6qEBeaTnv165gm3+HCc1j2W0FvkfCyKHNGFfQxV511z8MxdkWBFl814UsliZEmfgFbakxTj1SfWrYE3zxSp5b2dJp+2zP0g2s3aR2eXtukDcCYyiWqY5p46EA2+CVBRWZpABm90F4/GGGSOhAWQyi8loshCt0yS96GSn50q0tsjhX9Pv2dtRlK5bthplQyooEQRXiKw7bGtUM0iSGMquEqe7EDTp94pRNnsiZpo9NlbRNE1b9isNIf+vrPzQLglFqhL7kkP8nSkvwEqwwCWr4f45qUFen7BMzP9TR6JkpoxYhTq6LUTk5da3UOS8r0aagdYX22zqaJb0XHY2A7kdwQN9BA1bpiI+bfLgTv09eVGIH564d5NaWM8kx06qlLWfeseIFSF6MFvdY1k8O1NHH9vPl5q4s1GuVvjwG1AzgiukADj7Zc8EYPgwupFqmHQP2DpAlTUQweSneDtZCwDFn8r6zPIj6cX0BZg9orjv6A6YhRXkf5fDenGkquamG0FAIPnp2DY93+BL8CiX8tJ6W1/F2IFNTMLywDCU3f9xhHQATFX1e9T4eFcI4SAzQuYS49SQ8+1gyCqGnD6RPo5usIQ+IilLR4WnLCP1INTVAZRCQ17baLUvjJRz8kd6Gpydvudt8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzUwMzg1MTQ4MzQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzVjYWExYTFjMThiM2U3ZGU5NWFjNWIxMzA3Zjc4ZDhjMTg4MTA1YmYyMzg5MGEyNDY1NGRmMTNiYzdkZmM2In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I cannot be defeated, don't try.",
            'powers': array(
                "/buff",
                "/fly",
                "/flyspeed <number>",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/underworld (travels to the UNDERWORLD!)",
                "/disguise",
                "/undisguise",
                "/speak <playername>",
                "/confuse <player>",
                "/carryplayer",
                "/dismountplayer",
                "/tp <player>",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
