@plr = player()


@hero = associative_array(
            'name': '§eA§fp§eo§fll§eo',
            'class': 'apollo',
            'sig': 'P9X16sY7ypz1YpJ+5zdsG4nTKo1w79o7qFh2tHqR8CjPnQo7m482cvSOmHOpkRJEmm2OmrbqDsMe+A1vG1v0HNntQHfoHtYV5DATFi8WQ+oQv+PTatmHdWepRmX6wxobduMznY0A4ExAcFAy80kE42o6wiSUcgJm4E+gJ85Qs86dmU4N3lho+vzI1JIb9Cz7DACysQ+J+zF3+3jlhw05lDTcN5K1VXwj8Mypo0rMrVE74LPdNfMOjXlywi9YqTW8Q8c6GeiJqfR9IKk7maDjVCAEaw6qmkRVkD5ZJnaIosioD36DHSmpPEvEdrKsxp/oLD8O6CzLfBDpbeUkXZEDrPcHNqz6oC8kjSmhzJ22LYJFVMHjsP+AI8EzouiN27AQun5F5Slc2uB6bE4BPuLOTNH6gojFQzfAbDp/Zkltfq5SUQ7Y/3DTRv6y6u+aaswfBrYVMvn3K6fXR5nmCVLNPQZ1Cclkd+/vNpbPw2Rrxtc0Je4x0PJHNil/484zgcR12DUYW6xn2pEjlLCkv4kEBWzjiOxuOjcqqKCuoK+/DKwreEZfnT2uSN+vwcFxVXKZd0zWzVK7kj2gtHKZACc7B/9FqrqA2lvyILKEZ9qRItaCuM3JHf9cWf53aBwNM4udRLDJ4fRkACA19uakD59OaXBUFdSI1BFFKHq2E+ZfGbA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjQ5NzM5NzIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzc3NzUxOGJjOGY4YmM5NmUyMmQ1YWE0Yzk4NzZkZGQ0NTlmN2RjMmVkY2NkODNiNDUwNDZiYWNhNDZkMCJ9fX0=',
            'altskins':array(
            array(
            'sig':'c9LO3UkTn5U4GHZM4yoWDbkI2E3ciU6kYDGkSQZbwd7GqPseG1JFa2g4KPFdn/6pVePFjTN88/+OcblopOGBVjxatvH+b2kEzdtwWD7Ma3DdZYAhvslNIP2wQsnLGw2+N/ayAFu4LPf6vAYbsEXyojvRyl8UiyvCnfkc1OH8YdQNQyvf9hvrrocmenz2apvPTANZvpJnU9nMCh4/iOgEW0dg5jRSO2wmK1oyrgORCR3rXyfYjsqqXMGMX5HhZoyPGP99GjwHE2vRnC1HDWHEY2L0iCOPT/HyCL8LONAnbAHFQUnlUcP2jqsAD/YCQMOV4vOF+IJnpQL1qmV4FvjO/ifLzvDzEIRo9t5ApRpd/WS/ZpWdtjXn2ucKTUGE782mLmj9yTVMrDCnycHEypQSzrkDrlAw6pVkmvlUu6Zzi8fynq8kIlkvrbpJxA1rLyBF07osnk0fMD8bcseaR0vykFFcOxyWL4+TFkaH9Hv8eeVKLPNoEX2aY8P2jhyJRkFaFeHH+Nj3fmlZEzOcJ96jHh3MB61jmYO3RZFlW4RbvSnuNDYnEMAGZfUmshSF38XiceAiPnG3v+V9vr+c7sDGVsC0gCKClwx4jUS489SJWCuiKivLoXXdE77SsFKexoPAxflzXgEzn37by6f5qX5ibZIS1k0Ti2gMHdJ9ONe37Pg=',
            'val':'eyJ0aW1lc3RhbXAiOjE0OTQ2OTgyNDE4MjcsInByb2ZpbGVJZCI6IjAxMzAyOTlhNDQ4OTQyOWRiNGViNjg2NDNhNGM2YWM4IiwicHJvZmlsZU5hbWUiOiJ4RGNHYW1lcl9NQ1UiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzk5ODQ3YTNkNDEyYzQ1NjIxNzY0NWY2MmUyN2MxNjE3OTg0OTVmMmY3YWI2NjlmNDE0NzY1NzQwM2RkYzM1ZjEifX19'
            )
            ),
            
            'trail': '',
            'op': 'false',
            'speech': "I am the God of Light, Sun, Music, and Archery.",
            'powers': array(
                "/buff",
                "/jump 0-6",
                "/run 0-7",
                "/haste 0-6",
                "/arrow",
                "/carryplayer",
                "/dismountplayer",
                "/arrow regen",
                "/arrow regen long",
                "/arrow swiftness",
                "/arrow swiftness long",
                "/arrow fireresist",
                "/arrow healing",
                "/arrow nightvision",
                "/arrow strength",
                "/arrow strength long",
                "/arrow leaping",
                "/arrow leaping long",
                "/arrow invisibility",
                "/arrow poison",
                "/arrow poison long",
                "/arrow weakness",
                "/arrow slowness",
                "/arrow harming",
                "/arrow waterbreathing",
                "/arrow luck",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:bow 1 name:&eA&fp&eo&fll&eo's_Bow infinity:1"                
            )
        )
