@plr = player()


@hero = associative_array(
            'name': '§eA§fp§eo§fll§eo',
            'class': 'apollo',
            'sig': 'P9X16sY7ypz1YpJ+5zdsG4nTKo1w79o7qFh2tHqR8CjPnQo7m482cvSOmHOpkRJEmm2OmrbqDsMe+A1vG1v0HNntQHfoHtYV5DATFi8WQ+oQv+PTatmHdWepRmX6wxobduMznY0A4ExAcFAy80kE42o6wiSUcgJm4E+gJ85Qs86dmU4N3lho+vzI1JIb9Cz7DACysQ+J+zF3+3jlhw05lDTcN5K1VXwj8Mypo0rMrVE74LPdNfMOjXlywi9YqTW8Q8c6GeiJqfR9IKk7maDjVCAEaw6qmkRVkD5ZJnaIosioD36DHSmpPEvEdrKsxp/oLD8O6CzLfBDpbeUkXZEDrPcHNqz6oC8kjSmhzJ22LYJFVMHjsP+AI8EzouiN27AQun5F5Slc2uB6bE4BPuLOTNH6gojFQzfAbDp/Zkltfq5SUQ7Y/3DTRv6y6u+aaswfBrYVMvn3K6fXR5nmCVLNPQZ1Cclkd+/vNpbPw2Rrxtc0Je4x0PJHNil/484zgcR12DUYW6xn2pEjlLCkv4kEBWzjiOxuOjcqqKCuoK+/DKwreEZfnT2uSN+vwcFxVXKZd0zWzVK7kj2gtHKZACc7B/9FqrqA2lvyILKEZ9qRItaCuM3JHf9cWf53aBwNM4udRLDJ4fRkACA19uakD59OaXBUFdSI1BFFKHq2E+ZfGbA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjQ5NzM5NzIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzc3NzUxOGJjOGY4YmM5NmUyMmQ1YWE0Yzk4NzZkZGQ0NTlmN2RjMmVkY2NkODNiNDUwNDZiYWNhNDZkMCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am the God of Light, Sun, Music, and Archery.",
            'powers': array(
                "/buff",
                "/jump 0-6",
                "/run 0-7",
                "/haste 0-6",
                "/arrow",
                "/carryplayer",
                "/dismountplayer",
                "/arrow regen",
                "/arrow regen long",
                "/arrow swiftness",
                "/arrow swiftness long",
                "/arrow fireresist",
                "/arrow healing",
                "/arrow nightvision",
                "/arrow strength",
                "/arrow strength long",
                "/arrow leaping",
                "/arrow leaping long",
                "/arrow invisibility",
                "/arrow poison",
                "/arrow poison long",
                "/arrow weakness",
                "/arrow slowness",
                "/arrow harming",
                "/arrow waterbreathing",
                "/arrow luck",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:bow 1 name:&eA&fp&eo&fll&eo's_Bow infinity:1"                
            )
        )
