@plr = player()


@hero = associative_array(
            'name': '§9A§1q§4ual§1a§9d§8(K§8)',
            'class': 'aqualadkaldurahm',
            'sig': 'd11g2QZwP9SVplXIM+3neuuEL2m8bklVvmZBMIt1RmXBkjAjNF3fblJ6uDYfndms6UkZ6PaIZwD08R4iVxElJoGgHhoYua7+5DLF3TNnW0V866fuRsNMSD+JDy4rmF53HBVOcxN887tYUXlfb5pyl2vwYyJaR4LKh4PlgbSVemwwUSNQ6HPvdZ0YlJhzTVjnBUKW0h43kMZsPCXc4sDB+DvFXnJt7shLQyus5PDvfzr6jgmxSFZEagXPTsKNpGYFTwRwvofVVCVjvofWAW/homOye1i/BG0UTtjk0RHjdG5Ow7SxObjWpO0cEc1TlbkQ/kzaMO86EGXP0KvH9xM+Mb6YiYQLNhF+nseO15zJzTb8syxzENxWpYVy5ksCMHB+uoD5OBjgRIOZ9V8nMwUS7AmoyvfKHnHxO4HD7Q4zhwBkeQ869doy1ZXhKnq1dPoZDf2ZZf1lekez2H1D0Mn7kfY1X73v7vGenoLt3xwUx0OU6xzRhOZ/Jvyq0v4rlHFg8eP+n7Di7PepL0CxgYR4PKAhiSLgjM2ZEtUapX7nDoW7Sy4mn7twy0djyNhcU2HSsQyxQF7xYKSVAnbkmrhbw50QvEcHAJVp3WThKrvqbI/NT0dgL59ZQu78PGTXFXPoMZl1PPIXVtmkgSRrP4eNJjZKuaznY1/jDN9q6ORkmYI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQwOTgyNzM3MjMsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJUcmV5Q29kaW5nIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mZTcxN2ZiMjU4ZDlhZmI3YjFhM2I3M2NlYzI2OWNjMzA2NzI2NDQ1NGU5ODgzMTA0ZjI0YjMyNTBhYSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "My father shall no longer harm us.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-2",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 4 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." watershot",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&9A&1q&4ual&1a§9d's_&bWater_Bound_Sword",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&9A&1q&4ual&1a§9d's_&bWater_Bound_Sword"
            )
        )
