@plr = player()


@hero = associative_array(
            'name': '§eA§6qua§2man',
            'class': 'aquaman',
            'sig': 'PaTXS0+nmGzOohQTzRihnvTkiegnqwcWP/RL+Y9YbNUnshgFY/3riwpQZc0kPczrOQwBQPy5xnVUQXhLaD+jD76vUvrdSOsvChb76MNrFi8AxPX8iNFv9st9UkOMJ2bdRhYH3a3skorIv0oDIw6+jwATqnxmUe3BZk91vanHj1tGG5Y+eYpVpbhiRpUmnhPEf6zGvwgxID8OxKzRE+ZU9ou227b7ljRnV1iIoo8IVN7oLm5m+SDM5B6FAljN4EtYxkPAuD5pCFGpgqM81uZtNv2t9wu8NpfW7i4MxQr0RX2B5pqOlb8lOSPTpBOH/DLiTED2zlxcwym7nVdaj2qtW3ukLCwqz+6FrWpr0X8ODyfl6qXjYhuIaK8a6Zhi1PhVCWUxKR5P3JdMDBHqMZV1dbknoWxdX4c+Bk5pL/URagdDjQYNO0qBPGo1Dgxxz6etTDRpfye76mka5S4tUWrP5v251x37rpuavlrgCKB3Bc3BYdnn4GaNtyif3h5sGOHi7+e5MBa7jTg2Nx5sJEacsN9lbhgvYDGGmuWmVIW99ElKIdJkLJebJx5JfDJ0vRjF+WMD9zNLEB9WYkJGh6cLTNZlBu9G1idXtBO7x9p9mBjylTonQrBl8nI4Yq82ldZJYUMs718TZJeYKkD2AkbNME24N8m377vkorxuD3ENIlQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTMxODYwMjEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzkxYjUxNDE2YmU1NjY5MmMzNTM0ZjM0NDYxMTNhY2VhYzgzNTM2NzI3YjZlZjk1MjdmNjI4YTFjNWNlZTUwMzQifX19',
            'trail': '',
            'op': 'false',
            'speech': "You gain strength and can breathe underwater!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 6 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:fishing_rod 1 61:32767 62:5 name:&eA&6qua&2man's_Perfect_Fishing_Rod",
                "/give ". @plr ." minecraft:leather_helmet 1 5:50 6:1 8:3 name:&eA&6qua&2man's_Public_&9Water_Helmet"                
            )
        )
