@plr = player()


@hero = associative_array(
            'name': '§9A§1q§4ual§1a§9d §7(§Kaldur'ahm§7)',
            'class': 'aqualadkaldur'ahm',
            'sig': 'NvGny7uLZytg2lwV/EE7PHvG3tCXlW3c8WSsqFLwnHCqLUOvYW6Lm+1grijw6M22jbvHd2NTYiRr7CbTBIatIBYczzPbbg0cpjvb5GNWm58xRdietdPLe+WQou8u214uocMl8fb3DhaRhodk3c//4bnezrQC3EaPjZHFfQlgvFLbCb2KoVXr+3D5lCylci/xi8aUwhALv91Z3cJZr3lOOyuQXuEbiyAvSS6ttA5QUWJ0wOLrK7UxLQMB8D0w/IWqIR2WGjvJxC7JwHV3XIgeig1rdkBV0CPJiImjpdphAhKVXEx4BCBQ20kDYC8Fzna7Jgzfsg2yWAdo+xjq94an/tFT4jpfThMJqN5KKXtLbXvhKQtWNBp6/Ldfzv9bt4Qgee++vX/faDUwLF6/H0zcNrZje4WEcG9kYTvb645rGT5tU/eI1pa69qYP/eh8RlgZKn1l+yN3pAEOsNoLdy1NBg+vWxSXVsttP171grKM2zQ3Q7fotFHvrChtXSKNs0c+lTiV44Ksvjcr8PRYvgSO4w/YVEqmeU/JNMXdscOLPCKS5kxPYXHl+rRER6fPXHkPmvR8ngFyPCoT/xL6z1cfMlmgR+vzfkZZluF/LbqTVkMedJkobtfP5AsDr9y/6sj9LsJyhjtm3RB5/vjTqVKDXARmT/9ltEq0VPem3RtAYls=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQwMzM1NDIyNDcsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJUcmV5Q29kaW5nIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mZTcxN2ZiMjU4ZDlhZmI3YjFhM2I3M2NlYzI2OWNjMzA2NzI2NDQ1NGU5ODgzMTA0ZjI0YjMyNTBhYSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "You gain strength and can breathe underwater!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-2",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 4 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." watershot,
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:'&9&1q&4ual&1a§9d's &bWater Bound Sword",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:'&9&1q&4ual&1a§9d's &bWater Bound Sword"
            )
        )
