@plr = player()


@hero = associative_array(
            'name': '§1A§0r§7ch§1an§7ge§0l',
            'class': 'archangel',
            'sig': 'Bf6XMYaYNzNq1yDiFaoDK71QnWCWD1ScSdy1DHeh+e4o0TgjWTMZ3zbpIVjn1T7CaaMIRWDtJJAmcVUk+36N6Ocrn+G6GmI6+H1yJvbVmIFC5S5+OyBLxZ/tPFeJpTyRTo2pHtziKCmDBQ0rxQF4CT1PVRdhWAPYKJP4Lp8QoqekOjoBq7ti5TgKJD9G8clf3Xnqqv8kbtr8pOSt8SM6v4brD0L86t7RX3IqrY+udKJfPETExFMeE0jYk4/GFpgMshCcMPSJJ9orkKH8pIMbyC+vTB5JtzFHTLZE9GOKKP2tCn93aRlMQI/1TgpC45fQLdDOtB63aAOqxuHT7tO1uymSqrycKJjDGRd2SXi3EZkntBn0SWzcLuKYS6wY/MzQoGPal5bQFq54x3GodD2lliXB0ARGiQ36/OBc5fFu0YL4J/DPIBh2rIDH6EzJswpzWZKeCtm0TYT2MVvJJBtWE+dUL7ItIFqapjdlLq11zmUQBGOJnqW0krXInGwqlohDJjvKxEjyLPXWEYibioVz0L3YJ6lFWzNan/0UbT56T7fdtCv8vabZB5BmLz2fj1YU/+MyhriP8dY67gXDlmQ3uj3GfxQqJC1ofs8nvMob+zCFKE8oketF7NgHYiGhI5XCPojpyS+NH3kn7xIYvfMzruUz67C9TfxqgHpIzmpaRIY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTA0MjI4MzAzNzksInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWY1YjZkMTc5MzhmZjNlOTdkY2MxYjNkMWNmNGU1Nzg3MTU1Y2ZmMmY2NTlmNmZiZmNlMWRjZDQ2NWE3NSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am the Avenging Angel",
            'powers': array(
                "/buff",
                "/fly",
                "/cast feathershot"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 4 true"               
            )
)
