if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§1A§0r§7ch§1an§7ge§0l',
            'class': 'archangel',
            'sig': 'SyFwEph+w822dgLU2vDa/jIkkY+jmKVd4nrx2c9jP9TyAsXZYORjZC8EYxZJUNU76ThYqgP8nitGCSrGRACZIZS0ZtqAXHKxG5AecZcRJEbs1aV1HPgVaL2ixFyWHYLHbMb96uLmEn5TRczTQ5s8L2mxvS3s9kAjTOTj6ftBdbkvO1X6IN3XOIWWtHlRZSDzjbD6GBLjC575ChTMxrwgbNHB4O5pUf9lEygQ4qID9P4S/DK/7zlYPuHe5V0egiNXfVFDt62bIX9Zhr9jP5R4h72mtOdsOimkWX8JbZOkBjw0q37VG+K6BYkMaINkWWw52fmVo0iKpTamdSETd1J8zb8eSMWqfkwJaow6uK4OcU7noegDysoqHxw6ieiMQ6f+pVk6N9pxZmP8cBUbtyG5p1Ypa4zv0plppo0XNryXa4Uy1vwYd54z3p5Gu8MVp0WO8g+pbN/0uxGsMHs/ykfqoEm+08bE2BXp/oCK6/0Lq/7dN7hKgt8grIdLBiMdITtVvUkxhMvxn44zpJxpEw+waRPFj3wXpM+1mmbFfo+Th63v1G/Vp1QgZWUC+o4a7nhtOn5FueYEgAjrbAuUPawUtHcAn7eQ68BNK/+RSFZ6d0U6M/zCxkwacbxDE15n2QBNoY63irOaVPUCFnaBRABuwq1PoqVj9d8mNLn7DNozwKg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTE0NjU3MDQ5MzAsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJKaXJlbl9UaGVfR3JleSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmQ4NmY5ZTNjZTc3ZmRjMmQ5ZjI1ZWY2YmJkMzkzMjE3OGExYjNjMjZlODQ2OWQzZGEyY2QwZjdjMzFiNTMifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am the Avenging Angel",
            'powers': array(
                "/buff",
                "/cast feathershot",
                "/throwfeather"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." elytra 1",
                "/give ". @plr ." firework 10"
            )
)
