@plr = player()



@hero = associative_array(
            'name': '§4§lAr§0§le§4§ls',
            'class': 'ares',
            'sig': 'lLK1RWt4hqSaA4rjPZVurxuAldWTuz9jMsnwcaGXfV/XbqHqr2EFqwzGKobVNI14FT0r1vG2LORmXJhkZgIcWhgg3DepoJeJgKr7/oxGJe0El8F/n4rZUYPxNC9Fr5sfk2MTYey5wzOL6QN6vViVp0nJ7hcSOntB5oyLaE7o0YVxOy2z3aKoq/RYvCUX+QVLQrQfhILJxkAfnZF6WCuCbp0wknZ/gxYHPk5vyr+Kqep1LjMyM8JtoLRWaSEThtelJYhEC7QsjYLOuDMTWHW197EFf0+UTiJY7OTl3KDoN8dv0JnxvhSNCXU5DShG3YlVoooxUUENRlmGWw0+X4NZq67X2KM4LbMKcTmAgTgcUVGD9MZBMbx+6VZflaW1VN+V57jB3/JgrZf5lmEn00wTI3+3tIE1NADQqkoRsPqDDLH6pNjykZoAB/dayB4P0xdCVHxkugr7hmu3jMyA2l77YNrmZFYhEd/WQ90P4JRsJEo3U1X2/BbwStAwUO2vaizluiyEk+2w6Ax4E9Hh5WAunCUSdfTus2wHg36ovNslFpixJ2KLGwWxP7lT9UFMqUveCf+kAn/LiIqxMNJ4ksNj538DSDu+pq7mchkR2v0Sb8F/oL2Jnfv0OlRsKnX6pSC9JDO5ODqW1W2+6rX0pzZayrMQdQUpUHyZqwrmKVzN3sU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTcyMzI3MjcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzI1NmM5ODk2Y2UzZGRkNTlhODI0ZTNiMzZlZDhlOTUwZGM0OWE2NzJiM2QzZTY1MjAyZGUyNTc3YmY2MyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "War is necessary, but through it comes peace.",
            'powers': array(
                "/buff",
                "/jump 0-6",
                "/run 0-7",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-6",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." warbeam",
                "/give ". @plr ." minecraft:iron_axe 1 20:2 16:30 name:&4&lAr&0&le&4&ls's_&4War_Axe",
                "/give ". @plr ." minecraft:iron_axe 1 0 20:2 16:30 name:&4&lAr&0&le&4&ls's_&4War_Axe",
                "/give ". @plr ." minecraft:shield 1 basecolor:14188339 GRADIENT:15066419 GRADIENT_UP:10040115 TRIANGLE_TOP:15066419 CURLY_BORDER:1644825 TRIANGLE_TOP:1644825 MOJANG:1644825 CIRCLE_MIDDLE:1644825 BORDER:1644825 name:&4&lAr&0&le&4&ls's_&4Shield",
                "/give ". @plr ." minecraft:iron_helmet 1 0 0:10 1:10 3:10 4:10 7:10 name:&4&lAr&0&le&4&ls's_&4W&0a&4r_Helmet",
                "/give ". @plr ." minecraft:iron_chestplate 1 0 0:10 1:10 3:10 4:10 7:10 name:&4&lAr&0&le&4&ls's_&4W&0a&4r_Chestplate",
                "/give ". @plr ." minecraft:iron_leggings 1 0 0:10 1:10 3:10 4:10 7:10 name:&4&lAr&0&le&4&ls's_&4W&0a&4r_Leggings",
                "/give ". @plr ." minecraft:iron_boots 1 0 0:10 1:10 3:10 4:10 7:10 name:&4&lAr&0&le&4&ls's_&4W&0a&4r_Boots"                
            )
        )
