@plr = player()


@hero = associative_array(
            'name': '§4Ar§cse§4na§cl',
            'class': 'arsenal',
            'sig': 'KkGhuNs1XUjyOU+LrIL2BN/x8E8Ca+cVRO2WpEvfzFMCJ8uVkSt7IhLwmvzPgo8wuVs/3YNj0kpO7vDRe8mrlb9f/CLJMFlDJ/50gpjwHzOtiX+1tSiF+fjksYHQTYQfJA01bT/pHS1rBu4luQ8PBCwLR6igyHl6yPTdeTKA6BT82mlCS86y/F2mLyZZTY8vMW1tqQxx+QtssobmOjCX9+GswmFiOkrl+YoV5wEIsYr4Z230ddg7t74CfXt1ry7FqyahndJ7WHsb3MLF3ef1w6XhAf6COsomI4lT/eWx7qJ9Y9moLdwYi9Np3s6Xb7JXs4I+CP8xOSNqP7tf6nTVJ4waLd3pbpCXwSzr0lTP1a/0WTXjG9QyiqgD8TXvhpdt6WpwGe/xl8Pip+5XO696Sz6E/XRQv0Wut3F+QWBFS4GckceNXN1EQ1y70v1KejRSAjgzoQWlyApaAp3VY3uzUQPIVctkm2jefkQR+ncUmB9gioHcoqa63wBFZSaOpDJOtppoKOnpoYlhjCfPYt1e6wEaAjDR9fIroi0hRdaVg0OeANuowDYiWjHpP8b909825Dmhqt/eUr6C1lu1oH3UKdyc5c3/uwmR5cWtGhsZ7cSaTZDd9laaLTWGq3tIuyDPq59NseW7yaKhgYcOhB7Z+xO2/abzW937xj25zKse4GE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODYwNjE5MDY1NzYsInByb2ZpbGVJZCI6IjU1MGIwM2NkZDllOTRjODliNGVhNDRlYWQ0ODljZTBlIiwicHJvZmlsZU5hbWUiOiJBbmltZWxHaXJsIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xYTVlNWI5ZWM4NzhkNTNlYzQ4Y2Q2MzVlODYzYTM2ZTMyNzJjYzk2YWUzNDJmN2Q2OTdmYmM1ZWQzYTg1MSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "You have failed this city!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-3",
                "/arrow",
                "/arrow regen",
                "/arrow regen long",
                "/arrow swiftness",
                "/arrow swiftness long",
                "/arrow fireresist",
                "/arrow healing",
                "/arrow nightvision",
                "/arrow strength",
                "/arrow strength long",
                "/arrow leaping",
                "/arrow leaping long",
                "/arrow invisibility",
                "/arrow poison",
                "/arrow poison long",
                "/arrow weakness",
                "/arrow slowness",
                "/arrow harming",
                "/arrow waterbreathing",
                "/arrow luck"
             ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 17 true",
                "/effect ". @plr ." 5 9999 2 true",
                "/give ". @plr ." minecraft:bow 1 50:1 51:1 name: &4Ar&cse&4na&cl's_&4Bow",
                "/give ". @plr ." minecraft:ender_pearl 5 name: &4Ar&cse&4na&cl's's_&2Grappling_Arrow"
            )
        )
