@plr = player()


@hero = associative_array(
            'name': '§7A§6r§8t§ee§7r§6i§8a§em I§7g§6n§8i§es',
            'class': 'arteriam-i',
            'sig': '',
            'val': '',
            'trail': '',
            'op': 'false',
            'speech': "Im Fake!",
            'powers': array(
                "Epicness"
            ),
            'buffs': array(             
            )
        )
