@plr = player()


@hero = associative_array(
            'name': '§2Ar§fte§2mis§8(§2YJ§8)',
            'class': 'artemisyoungjustice',
            'sig': 'X9QYVQAi+tv5W+eas/Bwe02grnHGiCpZknW51MUkfmn9H8dhPq8dP5Sz6DsI0CvrTekqGeDWKjyil9C0p81fC07sP79roTuE8im/AqFZLK8Lqf3Cj9pV2+ZxcnTa2AWAIOFrHT/jdz5GPuUTqqKvxLfjBHZf3iNHBo8lkq6HcshmgGzsaaiuUGd+xwtjHCQy4a98DVXo55/d7KF+ILeUvb0bc0QaKHVU0L/7uCVfOHJLygtJrqgQYfZE2HPLtQHtf3/wz82C+X+tSAPJNp8xa+N6YAqLrmrUgEs2IChlopxgpzzvUQkItmSAlSWXyM2sUb56dK6JCt3ZByctOWoDjzDSG1lPCtj7IZ5+xDWk80gTX2nux6cqCtVs3FSYUb5Dw2DX0SDy2sDtijs+201nhGznJixwE0F1guPzILOED5yWsUHe2euLUeFvjQvWEoUKudQFofwqX1QVWtNMv0JmxbTk0WaAW4n8yHeQQeHbN6KS6B2yuhTvzSTTP2SUNtxbbAjaVDHPm+hujDN9YcMXcjS7Kb/aHxcQaWMgvAHAJ746qdi2m/GlXbFcMWcJ+6M+gd3L/X8GOEljt0SE53UVNM6g3VeFKZAcAuG951Xqh3uyGjKnmzTejOh6E6LPwIkWcTzaiNmf5LiXmDpd6AbH7+tGGh5bJP9AawUxEotfaFY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODUwMzM2Nzc4NDUsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2M4MWYzMmJkNjdiMGJjYTkzMGM1YzYyOWQ0OWY1ZTY0MjE2ZGQ5ZmI1Y2U1NDE2ZmFjYzhlMzgyODE4ZCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Hit the target!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-3",
                "/haste 0-1",
                "/arrow",
                "/arrow regen",
                "/arrow regen long",
                "/arrow swiftness",
                "/arrow swiftness long",
                "/arrow fireresist",
                "/arrow healing",
                "/arrow nightvision",
                "/arrow strength",
                "/arrow strength long",
                "/arrow leaping",
                "/arrow leaping long",
                "/arrow invisibility",
                "/arrow poison",
                "/arrow poison long",
                "/arrow weakness",
                "/arrow slowness",
                "/arrow harming",
                "/arrow waterbreathing",
                "/arrow luck"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:bow 1 50:1 51:1 name:&2Ar&fte&2mis'_&fBow",
                "/give ". @plr ." minecraft:ender_pearl 5 name:&2Ar&fte&2mis'_&fGrappling&2_Arrow",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true"                
            )
        )
