@plr = player()


@hero = associative_array(
            'name': '§9A§2r§9t§2e§9m§2i§9s',
            'class': 'artemis',
            'sig': 'jloZnDMrpB7vc9a81990/f1qBiYdcxxzWp9ojti1HZ0MeFUbCogAsImSrnQ+uoXjnVnJy16p1R7oAsROwIfXDYQLfQ9vmYYtU9I0Cm6EB0xg/IWcvkOC0oaAniJoVog3umVPA30qcvUsvXKP7sLQg/eEft69a/VO1aFGhy5DMF1JUY0KQhu9kUP8AN2bQ/jhagM1E4Xrv3aC2U6FEuz3dYY0b1OaG9wRu2CKB+9oqmporf8pAJF89IWTIOdWYOK4jtGcGPOSJfNHaVps4QhPJ1Qlio3pvHViwnVjrhvCdkqLd1esFqBKuHUFbXDdGbHdfsJz+uVHN+5/6/t4dXugkVrfr1Thpi1prPnxnB1AiRFp+maESo7traKHbRzmCJgtfUU0b+LSRViAeK8zyV0w7ZPfY8BIC2xdqS+1Y3hIAfA4l5z4ltSaq5gLpM77g1aGxTd6ORBckv+/Uv+dMNWtcI5PsQ+feGbcAy/M+KE5vA1VyYQNmmY93SIm7unHsQ6AdkI9zjOjeC76aI+yO8z8Hv/w+nu9BHUq3L68E1kBuqvNtbeiwEaUwa5OQKzn9+qY82CxCBtBssh4CB9ZUYj7RZcv8MXwF5683OOcAXgHnulf8afQadQsEhJxSE8HFA6vvXPrzRaMze7bFwCRLxWflpUoZrGsJBxgInCLma7RwT0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjUzOTcyODAsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yZTIyZmNkZGFjN2M5NjYyOTVhMjhhYzZmMGM4OTJjNmYxNDIyYzFmNmY4NDc2Mjg3N2I3MGZiYjY1In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Let the hunt begin!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-3",
                "/arrow",
                "/arrow regen",
                "/arrow regen long",
                "/arrow swiftness",
                "/arrow swiftness long",
                "/arrow fireresist",
                "/arrow healing",
                "/arrow nightvision",
                "/arrow strength",
                "/arrow strength long",
                "/arrow leaping",
                "/arrow leaping long",
                "/arrow invisibility",
                "/arrow poison",
                "/arrow poison long",
                "/arrow weakness",
                "/arrow slowness",
                "/arrow harming",
                "/arrow waterbreathing",
                "/arrow luck",
                "/flyspeed <number>",
                "/fly",
                "/feed"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:bow 1 0 51:1 name:&9A&2r&9t&2e&9m&2i&9s's_&9Bow",
                "/give ". @plr ." minecraft:iron_sword 1 0 20:2 16:10 name:&9A&2r&9t&2e&9m&2i&9s's_&9Sword"                
            )
        )
