@plr = player()



@hero = associative_array(
            'name': '§fA§es§bh §fP§er§bi§fm§ee',
            'class': 'ashprime',
            'sig': 'UwF/2MPI5YIUR7iZ2HNBv01KRcTl8s0FjYO/amxqLPToSRAtBUZsIFJCReogEqinCRqKyg+Ebo/2k52JgV4e/Hv77ERujNzRi9aBrxtojYP65f8jY4h/SPfyAHaH82DxE6pF8whOZM5M3rX79gdON97DCDkGKEzYlpkZcDogMayee0J/uMpqQTv3MesJSgWdll8J0bX9yUwhPdevzOEe6z3gw9vqFlCL5lEsVJD7E/7rwpusHfvaspKRy0ak+UK4x3Lg7MNi0NrDCfo5rMj9ue0jrRP7pC+JqXjPPhMmErGTsZ8Wb2pU2ONSNhZSgsHs/O5gOV1rQgyekdgryLTOwMsnjbafbX2gDSy8l6enxO8dT/5mGJY2RTab5urcrLXoTF+qyRgQI3x1TGw/DvF4wNBMrYTaW2Y+1Xz/lwSTiRjTUyVKywUkrtxBFtmP33kgx3ntgn4znuiZNdI3LIp1tabBBNYAc8xYxs4EN2G41g5ku5kqMHAqhTxNdLAzSFYAXPsNKFoihU263cN56NKshPRTWatx3Oeoh0xNnY7bvPhfHxMZTOFaXnLjU5Qz0ApcxPTxgqNS7GtpTnp7v2ghvrmmGMbv0ZDNcPr7oaQhssy8Af/iwNEHKzs0AFGl+6pSuX4o2DSF4YdZOF/OK0s+41gvOunhIVXwELevnyBkGg8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY5MTM5OTA4MjYsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJXaXR0bGVUaW1teSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmZhZTM5YjMyY2E0MmVlZWIxNzE3ODcwY2Q0ODdiMWZmOTg2Zjg0Mjk4MWQxZjY0MjQ3YWQ0NWU0YmU3NTMifX19',
            'trail': '',
            'op': 'false',
            'speech': "I'm not normal Ash, I am Ash Prime, shadow hunter of Warframe!",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-4",
                "/haste 0-4",
                "/invis",
                "/vis"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:bow 1 name:&fA&es&bh &fP&er&bi&fm&ee's_Bow",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&fA&es&bh &fP&er&bi&fm&ee's_Katana"                
            )
        )