@plr = player()


@hero = associative_array(
            'name': '§fA§9then§fa',
            'class': 'athena',
            'sig': 'H3qdVn/peycQJe9a6yGx+vrkv2n7Q2GDT8KHV65KEUWb2jt0ilL/qb28VYt50WnJdoR4HTkqD3RN51FPR+e+MXwD+cFdYiE61NbBOQO3K2ou0zShSW5QgZMGmIwDcQpU96fS7juzWAjRR4c0ST+UVQTFwhO1IVGd5L9CRAJA4LwLFGv8h75gQuGPGBkuY359cQL5yo4j/pVg5nmznxRomsAROBgEk7x0thRcqxUuHzjj23y2OqfIbiX1Mh9GxDyt0n2DKnheTNqTZHFBuzPj5cJOQ9Nd3sGMlKn/PSMPlmTRCqqTyLsdY6BC7tfgXZQS3x1jlXMLFBfDNhpBL2m5k4IZ7Ii7OngH/mX+JDFad/KtHY3hCqAxi/flYRzx19x+homZYhZ9dmt9zKwNWWhD6Sr8InUV27SuC3L+mjAWbEAww8fLwRpHndFg+1ONOIKpa2Vs/JO0G6SyEpGvOtkGJpg7O/tGE+1e5Ce0dGYQ8FEqEXCEx9m5q++wNKIt2yeI9xGyWOvYpxof/JPX7glgIm9UpF7CWS/n3kz6zaJIrZ+PnwRMSh6Wq0P8NN+XfvYUZ3D9vFq9iOQ1ENo63vW3PdXIkJa5+l+wHvG70DY2uPyszoGodKmKDqJmrNhfx+6eo+u9gy/t/eHWoRoq/TT01mDKUeXCcpQPOOYDEHrBKi4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3MzE1NzAzNzYsInByb2ZpbGVJZCI6Ijk5ZjQ5YzUyYzYxZTQyYWQ4MTFhMjBmZTU3ZGU5ODRlIiwicHJvZmlsZU5hbWUiOiJBdGhlbmEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hMGIzYTVmYzYwMjZlMGYzZTk5NGFhYzY1NWNmZTk2MWI1ZDk2YWI0ZTg3NDUxZDY4Y2E3MzQ3NTVkMzEzIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Wisdom is the key to battle",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-3",
                "/fly",
                "/flyspeed <number>",
                "/feed"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:iron_sword 1 20:2 16:10 name:&fA&9then&fa's_&9Sword",
                "/give ". @plr ." minecraft:iron_helmet 1 0:5 1:5 3:5 4:5 7:5 name:&fA&9then&fa's_&9Helmet",
                "/give ". @plr ." minecraft:iron_chestplate 1 0:5 1:5 3:5 4:5 7:5 name:&fA&9then&fa's_&9Chestplate",
                "/give ". @plr ." minecraft:iron_leggings 1 0:5 1:5 3:5 4:5 7:5 name:&fA&9then&fa's_&9Leggings",
                "/give ". @plr ." minecraft:iron_boots 1 0:5 1:5 3:5 4:5 7:5 name:&fA&9then&fa's_&9Boots"                
            )
        )
