@plr = player()


@hero = associative_array(
            'name': '§8At§1o§4m',
            'class': 'atom',
            'sig': 'Nqw/8KSpjDasvNXh/4igYzRqCBo17ILVIu1n4El+tYdRGly31tWJ7qM7UwV5vvQeKwxIG0A4OtOQoBwkhYRXPlZxQI2zHqVIRSlNquiZBOik6ED8W0eu64DdYjZttaH7yAlbWsjMN4+MhHD761vk6R+Co50AmKJDN2yyEFKNyQFOIAPmTXlyr95IeLD4RvVhZ9QB1CszybUa6aRd0OpVZNDXSAqkHiLZULNeqGjYCI+wetT88GWk2S7hCEHRAZInwPBEs03OfkVa3MD+HfWCSs8SKVX8KhuW2+mxV/vDw12H1O/GTr1GgT9j+p7msLxuPiAkP1PsJcobrdrfb2vVLYYAI2DdLdYrIn5zA88nAik65FWQ80H2Y381sxqTHxwjIVrJzRr4TlFUi0YmtY//SkM+a3ST/4sCTWzxFO8DKXFWfHc+VwkK5NCtA/0xv5AmQPgjBlo4NtuCP7TLaGL3H2ehj7s8bS0qJS48mlC48rRDzChbM+jUjVs/SzMwcXFnzYe8Pw+FqlAJjjXXi0DpBCUFAlgBspPltfVq1Gp2kX8plz/Cg4hWUzzNdRDarJgTGjT815Eovajjf1OcehgHM2UCg1YJUapeCBuohtOmsdCbpInR1ZefrUaSgg3JAr3xNpAHpjV9qx5M+FZMZ0OvErzKuIO0Dw8hBY0ddlNja3E=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk5Njg1NTE5MzYsInByb2ZpbGVJZCI6IjJkYjYyYTM1NjA2NTRjMmM5NjRkZWZjNWUwYWNlMThhIiwicHJvZmlsZU5hbWUiOiJBbmRyZWlNQ1UiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzU5ZjNhZWNlNzUxNWQ1YjVhNzk4ODM1ODkzMWI2OGIyNmJhMjVlOTVlZTdhOWE0NWVmYzMzNzUyYTFmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "WTF I'm little!!",
            'powers': array(
                "/buff",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-2",
                "/undisguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." plasmablast",
                "/disguise villager baby"                
            )
        )
