@plr = player()


@hero = associative_array(
            'name': '§4A§7t§8o§4m',
            'class': 'atom',
            'sig': 'DfoZzdQtG3Kmg03kSwJQsFemeJBcDBnXy1niKB+WHs1WlsmOWfzkIMvwv8OSjragAYxBCwQdyuosaAmAXDP4hec54aV2wZ9/SmexQOwO+wfQE0fmVK0Qimm16mjDdCZOckKncgzHIfsE242uvinKx7SgosoBFXR/NMxt/PuiZKka+O09a/IYGzdGgJlT7S5sAwuorfoCxfwLoGNDpMv/pOmdS6r0MFIS69A8ShQIhVG83GeLrgzvjHIhtKQ4iAntIvIi2mo+xDrSoQfX75mFVEyEb6p5abRW16k2wAmS5B+lVc86VFjmskZ2EjOp8M5hFpheFTusvXQwY4tD759GKDJsl8OLZ5vBzSaW/2nuvMBsgUwPOc32y64J4AHdVMbj4yuI7gqg+9275aavbOCLteZ4Hkoo72O1ir8eWiyS2Hofb8UBGTNiGDqcyZKQLfWMMhQU1MCAwGBpD+AMLBeAu8joNOKh3ZcZ7Ngq4vM8q1Tj08qvBq1Tj5N9ktejhsHtYc/HUVzt4q7gWXLWFdi4BEZ3DXjgBQxQWY4WrEupArrJfqL2rerGg7bzfHAhAqztZ0AoPQsMWXn0QskVxZOPRfZ85QdfXUqwmuLnZp0kUXS0GXwWcg7XngtL+1U7gc7sRDE7hq1BYS/nMQ0YWW0kd+A5nVw4ZSbNIaib/4GZt5c=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzI3ODAzMDkyMzUsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2NiZDczOTcxMTY2MTM2YjEyNmZmN2U1Y2VmYzIyNTgzODYxYTczZjU3NjFiMTBmNTg4OGUzZDg5ZGE1ZTllMCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "WTF I'm so small!",
            'powers': array(
                "/buff",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-2",
                "/undisguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." plasmablast",
                "/disguise villager baby"                
            )
        )
