@plr = player()


@hero = associative_array(
            'name': '§8A&7t§1o§4m',
            'class': 'atom',
            'sig': 'ARJyts6FP8J6PPVq4IgtnqSbwkhfWpUoupGJv5GuFcD54dXqpqiuGmtWz0BrY8n0680rm0x1q1g+8XA/Z4tCF+2TBtxgecJDPm6ZtKGydi1N9lzWdTjzvNT+eCSYyNi8gBS4t9NvTYUNK695E04o7T7IC6M23YrqaGZXlg9tK/ky5WtZiKQkN0a5kxO2HaJ70qGaXowYbI7dvGjGzcgpFMLM7zkT3O1X1gswRPfLdo19a+dDL/iKIDmM4GkVcUo7t6foNqc0/XNxaU7Mb8y1371UnMvj0PBgrdFq+zOoQLsQPx8gFlk0dsJZ09+0PEuCfAfA+g4VynO6Xoh+Zp7ItWU1fXCC51EvKu21TF2Vv5xamOA5dNsx88+sWysaMHiioD0q+EqLoIx5DtCZeAtp0c46PF4iQDUjRoYK8F0wFG1Z5mCmFZxTX2htN7ZqxNNT9ebptOg+qG7SI1UE13mqPNVN/CM8wX7TIW7syLuNXNkIbw5KyMAD49+UAnebWQaLQFeTX5uXPs3RAWxOAw89/p/bOj4sEB0yk3KePcaih1Pn8BJ0IUZ0JwEbdLPWMu5mC//EhqoSUpit6PWA4ZfXOPJskAOBpBn8q1z8IyDXmFVOpB0zY8diiG004YTwZ6UAmhgNTSKo7oYwaoz4R2jCf2/uIVEU0ExzU+XhMHlFdGk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAzODcyNDA0MTMsInByb2ZpbGVJZCI6IjJkYjYyYTM1NjA2NTRjMmM5NjRkZWZjNWUwYWNlMThhIiwicHJvZmlsZU5hbWUiOiJBbmRyZWlNQ1UiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzk0ZDlhNDM2YTc0ZWEyYzQ5OWI4OTA2YTNhOGY4NzM1NGRkNWNjYjVjNmEyNjhiZDdlNjk2NWMyMzNlYmQ4YmYifX19=',
            'altskins': array(
                array(
                    'sig': 'kTmqipriMV9kTWDmL48ZKTJXcodZFYWQP4Wby50lPu0dj4ti0MdlrfBjTg6ZX7zlmG0YAd3k59lX3EGOfZadQBTkrF9gArSMviynxPmHsDjahEEQo4SlVvYGjq7mKK+dVgzTKFbW03LdUah0iwLQ0PVLEUnOhZEygavz1Eb7zspDJmq2xSM8q/ZNKyKC+yRJW68odyHLwVoF13WcFT7AYN/Nbi5gSuIsGQMKVzGLXEApkEATnOAJA+Ey4mcg6kljo1agJ6mho2EUM0WJa6HiuBHiIZzGLPUt79G5Tm1v5JhbU1wJ3Mi9/uqZS1rkSw+wBZ3488LaN04t4CHbb2EIwcg6yE+EWnISzSApybFNdxWsh/yojtWozjSvFm+KV97S+PGWdXAlKVnVLs0iU9mIE0fG3t1Wc9z4tYDDuGjUFsdF4+PoWeoWQG7ll00n3eEzAFb6zvgLw5WXE6JmS2QxIyTVz4L+pbrI/PX8QYw+51LVtYj1MPc0okdWGYvDHIBHMRVHRPMO4aw5ZZqXRvKG8hsWty11VnnlDN2hpZkFBOe5bY+AuHA045v6SEJV/mbVz8AsiblvMwalLO0/H83mDNjUm+Oz+mHK+jq5rlS4i+1OHXl95Yh855eW9BuKKOwzV6MZqvYF6vuTDrSEx8QQ4+Ac3iKA5eUGWQbH4UhAyhI=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0OTAzODc0NzA1NjQsInByb2ZpbGVJZCI6IjJkYjYyYTM1NjA2NTRjMmM5NjRkZWZjNWUwYWNlMThhIiwicHJvZmlsZU5hbWUiOiJBbmRyZWlNQ1UiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2UyNjQ2N2QzMGI3MjZlMmM2OGMxNTMyYzkwMzA4ZTc2ZmIxYjU2NTk4NjkzY2NmZWRhZmE4ZjViNDk3ZjkifX19=',
                )
            ),            
            'trail': '',
            'op': 'false',
            'speech': "WTF I'm so small!",
            'powers': array(
                "/buff",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-2",
                "/undisguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." plasmablast",
                "/disguise villager baby"                
            )
        )
