if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§9A§6t§3t§9u§6m§3a',
            'class': 'attuma',
            'sig': 'YOgawnDamr8sD9CMXvI96iTBMtb3FMgL/EL4NSVkuZlUpikXCdzaZRcjpaaNjRRC/kTuWdgDfe44YUsX5LCKnyzqUZ9dvvdCbFy7caikwvEENI8FIRjJh3HWBfFvurB1OhWT8/poYSG8ibvqDRdzQnkWe86i+hRLEnrLzmRJ6SOVFKHBNCRNLPslaaP0pJ2FhFEpQl6zg25gU++w2Mpq5IvAPY6F3LIdd6QLsSbGAyVMdrJAaMRLjKIfhSQ8sKzrbsWJRKbl16yO2ABwnzmE5nifP9KiG/4lJ9c0PGbI5yEIOeVy3mOn+Xi6dRoI3YGngrP9mwz4/e3iCKVNnhC4A5ukgdmEhdLY0ESUst3r8vZxvWFKNQ4MXaE92djiLl1p7p2so7BCe4W6j6fnXAJzIEsdqdky7pIWH17YsNcqr6QIZVIZEVv7rxuA3xZrzs21zxt4YF0Q+96WJfXZEVw/PmP9IBhvkrvKq1NFG/6VzMU+RG6bqI/rXMmGL12cIA2UNhSSMReOzAmcIo2MOj8+yTcY5s6uoxMsoJti1HiE9mKKwymG+ek/+tKvSlC+rvTShL7ktg0qZ1WLYIYHIw29OMeyuWPcdNv5BiiubuX2DkvowA1VoI9c2Itkqu0Fii1PFxkO+qgvkaK4c7f1MojZYYLqQRFC5YMZ5ltOIpYJcho=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTA1MTAxODc1NjEsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjhkZTI0NDYyNTZlYTY0NTE2ZTdiM2EyOGMwYmYxOTFiOTdhNTViYTdkZDU4NGJhYmM3MWNmZmUxYmU2YjJiIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "The Atlanteans are superior to the surface dwellers!",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_hoe 1 16:10 name:&9At&3lant&9ean_&9Tr&3ide&9nt"                
            )
)
