@plr = player()


@hero = associative_array(
            'name': '§7Av§9a§7la§8nc§9h§7e',
            'class': 'avalanche',
            'sig': 'Ua2iSdxQRUyAL0pu5cKq69KQ89ng/JFPeB/JNTwWo1K7FiBGEnl4bYGA4dXBtsQlZI9IskCIYAb62hABzNQPLlj1G02M7K0n8XeUdl/F0wPrivtsFw57+I2cG2co2VZK46HIrxBdUIkLF5yqTld6BRAY7qix6EjlVz74hdtupMJ01jAr65nCAqUY+DMc2He0GXYuPuOFArRC8M9vhqWobSXMLW945kcUqt4tRJLU/tmFiXwDxYzlVOf7hbSOenvu2lAwZmrZ4C/iEetcLN5/y76z4Nmxv6vyc+hFSkyOMgkZUymYha0E/4k+XqoExVIAbqyv7oO/uC5TT1bGODLagADkewzNuAiny6MnC8IoVxvF6DNPSzHxbhTgM4AMj9V9iNl21IY6Vtk318fh4Mskda7G0L91PhCjpru0c7LbQsHbvMFG2o7AO1pGD536hP4gh2WWGJMQXijg+1/vHxvGjCPPln7+XnXpGV3iG4bAPYnIvhvG6vVMK8LcvajH8rL5mhtpgu2sB249ZPCvyb2HRx+Y3lR2Go91iwVE3YcpXJHY4i4YEZBSBTTMJjEQzCcmGSfn7vJpMDsJbfr206HmAJeUGuVyI4+2AUf36soH8xRWCpPFbt3QH8qieaEyRQkzHPcwi+0ZWhb/easx2DStYAuqCEWlO2lmIGbHhNxxw1c=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTE0NjY3Nzg5MTUsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTI0M2E5MjcxYTExYTU2MWIwNjA3NDkyM2VkMThhODYzNzBmNzU5MzllNzU5ZDI5NGZlNzA5ZDUyOTk1NmI0In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "May the earth shake at my hands!",
            'powers': array(
                "/buff",
                "/cast quake"
            ),
            'buffs': array(             
            )
)
