@plr = player()


@hero = associative_array(
            'name': '§6Bar&edock',
            'class': 'bardock',
            'sig': 'R5dSD72liS/6IvnB7i1dKsprQqFeSKEx7+BNEHqXk/xE50kDei6JRC1saPFM8NWY48FbF9x4xkBsMv1PSsCyLtl8QwsxHiZVoPd9tnejNUz2eqpLZESSnjcTi/kLvRDccWdKpqYwOWmiia1Lzpf1cLHhZy2Ez/hLe9+pZqH/iSc9Q1guAtVfaGsfuNX6S/oBIYgxLYWsNwbc/61JsKQjP6X7sY8htSAj/yzR5+OO+LQ2u69a49sobWbOaHCTntx38BDH+ozFsI5LmwMebiqjUZ/wSPK4kUDRPNMuh84UwzseApBnCg2AKwWSqaMg9ER49ULwDpS1383KT1/x5rOtU3ohlw6fqOaByjpaEOApQLlM8twX03qAXY38xu9+4evqxkSh6Eou3sDZlxWNwybWyoQjYavlnE0mQ9AX3x93pvoUrTP+OjyvOLXLTjv/m4sHYky/xKGIIfBaUWca6jPpi/LHYCVB+qnpOG0Sna3cKFqYm+MMo6PC/mtANAYyGTs10NDZk+K39Yyq7pcHBqGWo+TQbMHJIKl+LKJ/IXN/PSOLCNkteplPqGPe+H1yw8ZwS4AwxPejNASyb5367THKyiqXhr+PUSndJzon4nMVWV0tynZRF7hNgaBhhb/gGFlcn2xDowruJDkpuIFo1jkcB9l0IxKxh0nPj/Lzpi8CoeY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODUwMTEyMDU5MTMsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kZmQxNTFjNDNkNGNiYWMwMDNhOGE5Zjg5ZTVlNWEyNmQxNzQ4MzY0YmJhMzliZmNkMzU0Y2U2YTMxZjcifX19',
            'trail': '',
            'op': 'false',
            'speech': "I wanna be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-7",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/tp",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 18 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast
            )
        )
