@plr = player()


@hero = associative_array(
            'name': '§6Bar§edock',
            'class': 'bardock',
            'sig': 'uOdcbISlPkmMH63CLhnGD6U5ruZRprL41rOK/dVT6u9v0k/AYeEsaDwSr+0OD3ysVQwBTaodKBi5tRE9IHyDlZB6HybCgNhTEa7tGrWFY+o/W7v6D0qzVU5cjCtcuiGgPCI627ioK6NlEp25Cul5L6MC9U5lZYI0mBX7pEOdxPBtXas++ZkNu0q2CkCquuwS+3u5KpgIhldU6uWiLtLICSG+U+JFcQe9Gv36nL5+ahKe8lWT0GwyjURU/GCS21sxFAh/+8zY/rVf1ILHVd3QyFi/wL9kGWKgR3tm9FixG9kt2x3RwoH3AePErOnS70vO3VWJw5FHd4yia56Hs6bX9EJQSUVMKHqbRMSRXTbG6D6OVK+t0p/OftnKnlrMs4KiUIWFH3h9Ov0I9+p5eE1DsnZ0h4U/+WwHfz/6oX8PHNuUwBht13Vw9WD4+ieQSPM3EnWJLtAqNhP+EeCXu8RvTAhKHipMZ8Kh+HK2tz11bwcDPY9k2NQ9dCBO8k1hG/vmE/mKHn1UCsdgk3JoLAQAYrAhIeUsP1CsbJpwygO+Y7k4GnpG8fIhHM+SS73Chr1WhkRQzleF2zjuKckJcVbjZwtKAcvUblNd2Ct2LASrLK6c72qI0228n9vWctrfsXdLMlUPbHC5BVGaZZPoJbjzJrfnga7st8QOksrerV/QZeA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODU4Nzc4MjY3NjEsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lYTUyZmI3YmZkYjM2NGViOGVmM2VmZWM1Nzc3M2I1NmM0YTMzNjM1OTU1YjI1YzljZGEyYjE3NzNkNCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I wanna be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-4",
                "/fly",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 6 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true"
            )
        )
