
@plr = player() 
 
 
 
 
 @hero = associative_array( 
             'name': '§2B§0a§2r§0o§2n §0M§2o§0r§2d§0o', 
             'class': 'baronmordo', 
             'sig': 'J65fLdQux2BKCHTXZ54DSZQz5Xby3B6QZZtIpJ7hJBlgculLLGePJTCjgEnEEDFXgUV3H0KmgTRGi2oIgrHCB8oArBJTJGVLA68MNMgbhAKqAJvKiXQ4E4BF+SQtLJCVR0Ie27tAp0Dq8+aqAB3kn/M3H6Sxf/25/mTt5Ro1z9evX5sVQAIVhWJm54lppjHDVX3IpO7Yvm6dhS8zWcCAsbNXNHhZukq9fF+PSU2mheoRIdjy8+fbpW12XdsEEe/HDCYxF67F8hsSFBMPA/27lcjnqH6VpT4iFSFCGfOwB4L34cDGK/QkqrzYRj75IjeOaiubNT63H9id61Eg5lYXEKmq1OYVNo/3Z+8hN+L4ztcImwZYsim9Kdy7eop+NO+Pk4rXvJa3nRvyZ26BwkdDMkhFsIrFfnaSpwyyvK7C77GqdRYKGi0dXz1NWxJqWQX+OHUG6F2q6bWUKOZvFZG0RVTWH8sCDrPHlCMvnlQ/t5z3CgfNuPV/q0YrdFcKU54P00XsyzCz4TifoZVUlL9ZwP/TvP295NMpQ9XJ9EaJgVZYFqjhGgQ2rIRGgli52SvsFUlDTfyA+3NyGIXEQLT3mmPVmgOkr9MUJgTDuDN9dBhG1MzcktEvuRC8XXjW/MldePougiuMyIHJp2OPlBKkEXBV5XEhSlHbyEqoD0Gn1sY=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE0OTAwNTEzODQyMzQsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmU2YmMzZTdhNTA4NjQ2OGY1M2EwZTk4N2VkMzg1NTNmZGY0OTVjZDMyNjFlOTk0ZTFkMjEwOWE4NWZjYSJ9fX0=', 
             'trail': '', 
             'op': 'false', 
             'speech': "My Strength comes from the Dark Dimension!", 
             'powers': array( 
                 "/buff",
                 "/intangible",
                 "/tangible",
                 "/mindcontrol <playername>",
                 "/stopmindcontrol",
                 "/hover on",
                 "/hover off",
                 "/jump 0-4"
             ), 
             'buffs': array( 
                 "/shot give ". @plr ." darkmagic", 
                 "/effect ". @plr ." 21 9999 9 true"                
             ) 
         ) 



 
