@plr = player()




@hero = associative_array(
            'name': '§7B§ea§0t§7gi§8r§7l',
            'class': 'batgirl',
            'sig': 'VY19i44SkdKND7sGNyjSZ7q8k6co3Oh4UcGMkL6MC0pbssGsFQ914PbfmskDoUdpSs8rHKYSARIIua/oWPy6mMRtNVTqpM87oEMVqiubcjjaEiS/rIcWkaASc/9RcUhTIDcX19gpJoII0Q9XjmEnmTBwIxrsLcolxiPUDLqAUFP9Bbc3aghB2TWkNza08JwEMcyKGDwWt8dXtbFDP7UARwiA2JUUaBPzw5jnxg35YL5agtt3J6vOUgpraRnIXVNWpgVG2o5N0cPLDU7yll1KS2VaP34ewCSRCNosKY69wUIsz66VcDVqkwDZVMW5eee3VKcp8d72jqtMGbBscqGCAXUO9a0wkGzAQjmHxzxBjvj6pv2Zo5cMUiQKPaHxJUMg1mFxdmENoqySdAUYjx5rykwbTq1A6RPfSOC2fzaCuSuI+ws4Coz+6avKyn/JuJKLgK4a7sebHs650e3BIfwSFhGUs1Y4a26z2PTqJXbB6F7e29CARrYYbIejm0/qyaDKKzMx7urjvf2AeRMwiyhRu89M/G1GAzmLIW/91QdgeBX+F4ztZgC9GCJOOPHy0Bfe+ZY/CayKo/jqHyVSAtLVb6VeBb6Yi1t7/4WmgCQKo5HtBCgLEhzh8RmzSZXqd7hRYObxmztvi93IZUfoINFc1Sq7+kg8UECjPeo+iy5iADI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzU2OTY0MzY5OTIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS84OGRlNGYzMTgwMWExMzc2ZTNlMDllYmZhODNhYjNjMjMxNWZiMDc2YTkwNzNjNjk0NmE5ZWI2Y2UwNmRhMyJ9fX0=',
            'altskins': array(
            array(
            'sig':'ArKEPACzyxcgmxsEYARxDMR5dv4P8He5s4xYvrEuvO/6P9t/GAAe3GphmtH6xjgS3sk5feWhpibVlsd4ox45gRBuOGtiWaE1Q92gUR4wWSYucp7zNAEIYdAL5bFBqths9K8w+/AidGAS4h7N9vHUOcNIKm68gmTklPhcR1mYJa6AW7EXXeIGd1JdrQ5P5eJxsa18Uxs7Sp7ZqgX7B7uhABu7iOF0KbVtPe+1xRkhPl1D6Y9tjHqrzFfmOIOKaC4CGNDMRVYkUHa6zGVpl8A5LBAkxrpc2UpJp8YY+I+8XXqy33A6JIb6lfvS7t1+6bnhfxZPHiirBKFgaPq3M4bUYq05JXpQP/CFxSdZuz+4wcNYMamTfXugMXRqr2Z3VCtnPHP6SUIHEEo+WFxI0ACf5zKWl30AGuPXnwundSbzkIo94xuSkRysxCnx3t5lgS3GzvExycmM3YaFY4ekYITjDb8qBK+/MYU+YMXVByqut9OkJ/jrK4q2PTUgdXYTEZnoIimuqTR+z5fgcq9ehfdmXAwxszvpUX/swRAUMxNn/++FbuZ8jj0DIxd5gR/x+FCn9CTUkcEpBxJ9T+t+yXT+VdIvdhUUKaCRNE21BEn7U05uQ1ydeCZJeGuTmJQ732asnTXWU5juBA7g18A6lg+0K6Lz7diibLBm0w+gfyFYs/k=',
            'val':'eyJ0aW1lc3RhbXAiOjE0OTIwMTU0MDYyNzMsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJMb3N0SW5HYWxheGVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2RkZDVjODI0YTg4YTc2YWQyZWM4ZDhkYTQ0OTIxOWM2NWVjMWRiODFkYTIzNThjODU2ZWJkYTNlZjNlNDRiMSJ9fX0='
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "Trained by the best! My dad does not need to know though..",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&7B&ea&0t&7gi&8r&7l's_&8Glide_Wings",
                "/give ". @plr ." minecraft:ender_pearl 5 name:&7B&ea&0t&7gi&8r&7l's_&8Grappling_Hook"                
            )
        )
