@plr = player()



@hero = associative_array(
            'name': '§0B§8at§0m§8an §0(§4RD&0)',
            'class': 'batmanreddeath',
            'sig': 'V2wO9t+tPXufQvGaFy9JALlgaAxSWbucnc7DBcAXOeQYDHo1rW8yl/wjDRD+X5Ms4J4EJc28T6O8zCh4X7LIUQo4XMqXE1Asck7BB2hcz3dPDoSvLMgDiwjpxwu5lDw3PCMjx9PvNB+o9Wp6T/o7r6lQmMYZ/ru1NTVacw9lmQWbWGjTA+9Te9PmOPfyzqjM/cqTRHCmj2jvA+jHvKjnldvIVFsj3eXI1UpEjBrib1bU6lcoyptZSGhDPlr/bzOnsVgn8SrpkV4QV4hzWQEXVPlkmALQNcF6Xn9FDjAKRURI8Smku1Rab2vN9d+QL00ta1785h8bQr6fp9bbhrxk6pbys6jIXaYKve+HXv1/1Cs3p2Hsj+6zLGQD4k23LEYX+cEr3bHhVnz84VAMopgQBBZolJSiUMSWGubz6w03FHhyn3vTcXlyDuGIcB1U4fHgotObuigYqW6ZmjBVu5/q+yZ/yHhUCjGi5XckXSgjZUH883TEhl3KUDQLwhraaBEGgxuc8vwvGbOwWNWNOyfi8xRvwXCZOoY9ZS4DKncgjJ46wcOrBRtcq1ram0rvTmsaYNcdCOy6puYIsZ7nA2Bq+NDNFw5XSGzw3SHXbjKJK+wx4GO8dJfh5cJpsFE4p7SXl3ZxsGYZO0E9IXvv/RUKzE4zM+o0IR+En+rIu5W9ARQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDc5ODc0ODM1MDUsInByb2ZpbGVJZCI6ImQ3NzU3ZTAxY2YzZjQzMDU5NTkwYzY4ODIxNGJmZjc4IiwicHJvZmlsZU5hbWUiOiJtaW5lY3JhZnQ4ODIwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzY1ZDFlNzI4MmQ4ODNjMWEyN2RlNDZkYzI0YTBkZjRkM2EzMzZmMzZiMjRlOGI3ZTgwODkxNWZiN2M1YmRlMiJ9fX0=',
           'altskins': array( 
                array(
                'sig':'c3sfw4RH8UBngOenN1mhFH1kDuNid98mproMQFSV5tNWdb2gAVkfDdcAdd573fsERQGYkAz7s23/b9tBfe8mVsX520HaVfrcPiEj4kFQcGRs5ifB9nhT3OU8BQ5c4jgZyaUH50eNpnu4nwCIWTzJOPuOp68UaMyyQ5kGVE3+nvv4HZtX3iODSosdfpy1xQ8H5VDAFnvlAv1HJo67MWBWTsoMZeX0HglrQ4kfYiAeFv+uI3qwyhZsgGeUwSmZhUDM1bJLVbwFOSrLt03sseqIYslrxw4Q8gl0LRXH9XeZcs91185e3hqpVX79XHso0/uLTteqg2yelusFfdTrD8M26ChEyjJFwnn+vCjIcFOgbORstgdPA+fPnCxFh85cwP9GjGVRxkXdy/W+gHulVb/prChoBv6H6tWRjDZmiztoPsNGz+DwGj/h9BWKanUPLPFuiX3rJOIVY7/2850KUSS68M6tliKD489l7LaOSWhMYkSb6JY32UNgozzJHr7zflWBgNv6H09rVheCpnaUTyRvsSTdRKF7y9Wt/g/BRyya/jqYHUL0mL/AEiBRSXDwBaIvJk60JSsjamscNg7Y2dhk/epcujLapn8+Aj0tkFFkPpcqVXqdGtchVNNWv3YPFV23USX8Ft2Ax+MHnZxMoXfyBQnwtbZinmeaaoufw+YXp7s=',
                'val':'eyJ0aW1lc3RhbXAiOjE0ODk3OTMyNzYzNzksInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJTdGFyYmVhcnp6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kZWI3MmY5MDUyZmJiY2FiMjA1OGQxNzk1MWMwMzU3Njc4OTQ2NzY5YTU1ZWYwNjQzNzYxNDQ4ZjNkNWJmZTllIn19fQ=='
                )
                ),
           'trail': '',
            'op': 'true',
            'speech': "My name is Bruce Wayne. I am vengeance. I am justice. I am...BATMAN RED DEATH!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-9",
                "/haste 0-6",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/run 0-1 (In the speedforce)",
                "/wallrun <on/off>",
                "Look Up+Jump+Crouch to perform a wallrun.",
                "Anything you attack, dies"
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 5 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
)
