@plr = player()



@hero = associative_array(
            'name': '§0Batman §CBeyond',
            'class': 'batmanbeyond',
            'sig': 'AIZ7IL8bFS8NqY9CFn0IvF7EYojDfDtgsoWadinm1qcbQC0HEhxhR+RwuOvCenOWCMJID4cV9Q8+nLLcyw1KdUXFvqo6x+PjJ6A6hMIAL3tyZcG239PR9S6y/rb6njYzChMw8Ri4jCCFZH39NHSSo/3mNNTm95XMAFVGWqJJY6mSY7AYUX4FT3IfRXI2AePG3q5vF9Y1xMlCHKK2hg8BYLfkGZjIruMFwgZ1cGNYQJNyh6yhxffj5+nxjMmsNauta2wKXAAqG9PZnkv4jIPR6DswaT0L9fxTrPYm7FPyZAQ+scbxCCNARgXP+S6wXY2wIhSDBAv3JDIxNgYMGukkYF9g3Qu7PgAK88eB3JZs4MYBpTM2PApvz/SRHKN2Id03g0KvGyDPow/f/lqfnZKzY3j1SB9as08nhzMe+0vhWQP2lSIEnERHrJ6XL8G08wGw7gh0kpfXjSbJ2QIXATqfUhz7QBW6MprUw6a3h4ixHWkpZZt5ZCTwKHixVFL09ITCiCZ8jEPegbq8Kw74+YqbbKrK4fOt326JiqoMCfH8L/CFWW+/5fe3ukZ7yo4TVOr7bLvXIKewjCR/h2JykGrOVUeHUOVByXczqPO0HJPNnvhiD03SH08pbOeYjbiwNKTEEgbkU01AYtwPr13ZDQ1CR1zhrk2Q+KUvi1SUP7SyZ78=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDAwNTg5NTMxMDgsInByb2ZpbGVJZCI6IjQ2ZTY3YThhYzk4NzQ1MjZiMDRmYzRkYjA2ZGI1ODU1IiwicHJvZmlsZU5hbWUiOiJpaVN0cmVuZ3RoeiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmJmMTU5YWJjZGEwNzFkOWRiZGY0NDgxM2Q2ZjNjOGI1YmZkYTIyNDZkNjJhMWRhNGUyNDdkMTU5ODg2YSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Compare me to Superman now!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-4",
                "/haste 0-5",
                "/fly",
                "/flyspeed 0-10",
                "/invis",
                "/vis"
                
            ),
            'buffs': array(
                "/effect ". @plr ." 5  9999 10 true", 
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/give ". @plr ." minecraft:diamond_shovel 1 name:&aKr&2y&apt&2o&anite_&7Sp&8ea&7r"
            )
        )
