@plr = player()



@hero = associative_array(
            'name': '§0B§8at§0m§8an §0(§4RD&0)',
            'class': 'batmanreddeath',
            'sig': 'V2wO9t+tPXufQvGaFy9JALlgaAxSWbucnc7DBcAXOeQYDHo1rW8yl/wjDRD+X5Ms4J4EJc28T6O8zCh4X7LIUQo4XMqXE1Asck7BB2hcz3dPDoSvLMgDiwjpxwu5lDw3PCMjx9PvNB+o9Wp6T/o7r6lQmMYZ/ru1NTVacw9lmQWbWGjTA+9Te9PmOPfyzqjM/cqTRHCmj2jvA+jHvKjnldvIVFsj3eXI1UpEjBrib1bU6lcoyptZSGhDPlr/bzOnsVgn8SrpkV4QV4hzWQEXVPlkmALQNcF6Xn9FDjAKRURI8Smku1Rab2vN9d+QL00ta1785h8bQr6fp9bbhrxk6pbys6jIXaYKve+HXv1/1Cs3p2Hsj+6zLGQD4k23LEYX+cEr3bHhVnz84VAMopgQBBZolJSiUMSWGubz6w03FHhyn3vTcXlyDuGIcB1U4fHgotObuigYqW6ZmjBVu5/q+yZ/yHhUCjGi5XckXSgjZUH883TEhl3KUDQLwhraaBEGgxuc8vwvGbOwWNWNOyfi8xRvwXCZOoY9ZS4DKncgjJ46wcOrBRtcq1ram0rvTmsaYNcdCOy6puYIsZ7nA2Bq+NDNFw5XSGzw3SHXbjKJK+wx4GO8dJfh5cJpsFE4p7SXl3ZxsGYZO0E9IXvv/RUKzE4zM+o0IR+En+rIu5W9ARQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDc5ODc0ODM1MDUsInByb2ZpbGVJZCI6ImQ3NzU3ZTAxY2YzZjQzMDU5NTkwYzY4ODIxNGJmZjc4IiwicHJvZmlsZU5hbWUiOiJtaW5lY3JhZnQ4ODIwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzY1ZDFlNzI4MmQ4ODNjMWEyN2RlNDZkYzI0YTBkZjRkM2EzMzZmMzZiMjRlOGI3ZTgwODkxNWZiN2M1YmRlMiJ9fX0=',
            'trail': '',
            'op': 'true',
            'speech': "My name is Bruce Wayne. I am vengeance. I am justice. I am...BATMAN RED DEATH!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
            )
)
