@plr = player()


@hero = associative_array(
            'name': '§7B§ba§0t§8m§ba§7n §8G§bo§0d §8O§7f §8K§0n§bo§8w§7l§be§8d§0g§7e',
            'class': 'batmangodofknowledge',
            'sig': 'XCdQ1Dl5hhptu4CWeI8THGRfJaCwTHzD2Vu81B+d3LRW10bO9dzfmHHFd+ryTo4sdj/dYgBKB0f9id43Yyuvd4BX+imw/lBkRMSHCaDRapwzUia7DRMBhVWXLGVzkeKY1xhTmZGwEYMlxTB/soKG7H/VyH7iQLKWFSck6V8Zw4frI+/ZZqe3VMKcX8N1ADRmfTnQ6UwYhl67bDlDz5p6X3DZgTCYBprRgkjT5ig8yJRnlyCGBWOXreoXUAoJN/oGSn4xCB1TBCAOKL+W+QSIHfQaXIg1lkTMZ3wPPo5KW7y1bVtrMBkrphAjwJKzwUk48vXPAB0jHzbpeDyfEQ6C7zjeliUIkRDV1X3rA/CToDts4CLmeuFeMZ+I2xe6KEJSBNQvh3/qGzeRYgYJCS8iRIx9anyPM3p3eAzptSV04b73IhvUPTjY9r7EuGqMEJzZR1NUVw2m16UqrAZrYjrAWx3pYCqhtSzWRj5MG+/rXCtWI90YFR+r6IgT78TnSTxdeCBwH5jedxyGt0ZkbUIjAkG/79e0IkAxgeTZdXjSvZYZxlIZlu6TQ4wViA38EFaOJOY7PiugO4OvgdXm+iyYnsDXQ+nkcndK5tMCag9RIqQFfo/VDs+9AJ4YbImJTBoeomwq0633cgIDE4K5ybvM5BkrDjlfqbzivwPlSoyVe/s=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTg2NjIzMjAwMjYsInByb2ZpbGVJZCI6IjgzNTRlZDBkMDljYjQ2ODJiZjYyNWRmM2YwZTJiNDEyIiwicHJvZmlsZU5hbWUiOiJ4VmFsZW4iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQ5ZDAzNTcyMzllYmY2NGI1NzRhY2YzMzQ2NmE3OWYyZGE4ZDY5M2FmYWQ5NmY2YjA4YjNhODNhZGQwNDkifX19',
            'trail': '',
            'op': 'false',
            'speech': "The Mobius Chair is a miracle, Alfred... A gift. PING!",
            'powers': array(
                "/tppos <xyz>",
                "/tp <plr>",
                "/tphere <plr>",
                "/vis",
                "/invis",
                "/fly",
                "/flyspeed <0-10>,
                "/glow <on/off>",
                "You do not have hunger."
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 23 9999 1 true"
            )
        )
