@plr = player()


@hero = associative_array(
            'name': '§7B§ea§0t§7m§8a§7n(§8B§ba§8ts§7u§8it§7)',
            'class': 'batmanbatsuit',
            'sig': 'LVIH8K0Q9KpXLfl4RMH6eONPTGcs6Jiqe6WmBOTzwXQsxm3Ggh5R+7+BYx1VSLu3fiT7bSw1NCiRJIULobA3i87g2QSrvwzbtUTY8D9Th12RDhK9dpxzPPkUBupNCUnJ6bxPKCpD/24nkTTPZtC1/FYsHcEfLXPWGgg485eX62ry5i+INlnBduCuTZz+4+Z219uKzmZ4nDSalvBJgLDAPpHXfUGIcvWYWBCazFIyHF55vYDPUXGSodTb0TCIwYwL3v/cXOIkw920T4IB8r3mIZz3kA3hH6pLJyj/QZTCyDYSzkOz1EPhasV6ppShRjdMQE4ADp7TaHieZb8rK5jq7xeq1dd9pxsTHCnMjWorkwx5TYxueXAqxORQSlGGPadZtWLbrWO2Zo0zO1xAHtWqxJkslb49zdEtVshAVMdhoyYAtv0qJ7UZo8BouVZxp5675aW9BraL/iAFmRvCZHUCK/dB1Br4YzecI4/6yq37+G9ZL9YSEsqvUXj5sHeTlvdtnwgzSvEcWS8M999Rf6AwXOt4F11t8s+DEdrewVs9RYRWsbCfWb13pYhb5gy51dP+2M7EbHwrcJ+bmScJPgkd2w+mhbdP1LVI2mSuPP96weQElIKnVrn4O5aMN4RHps29B05agNoWjc2dZA4kTyr/2yRd8Op8peM/PHm1oCg2EJQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzMyODM2NjE1MTcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzg2ZjMzY2Y0NGVjZjM0MmRkYTg1ODE2YWJiODIxYzNkNTU5ZWJjN2U3YWVhM2YwMWI0ODg2MjVjZThiMWM3OCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "WHY DID YOU SAY MARTHA?!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-5"
            ),
            'buffs': array(
                "/effect ". @plr ." 2 9999 2 true",
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:diamond_shovel 1 name:&aKr&2y&apt&2o&anite_&7Sp&8ea&7r",
                "/give ". @plr ." minecraft:ender_pearl 5 name:&7B&ea&0t&7m&8a&7n's_&8Grappling_Hook"
            )
        )
