@plr = player()



@hero = associative_array(
            'name': '§1B§8a§et§0-§9M§7i§8t§0e',
            'class': 'batmite',
            'sig': 'g2Uvp20gGOhIBoCiOTtlGuyOKaP+x1BOwFtXWswvy5KxjyyFyWRzCDOiMkVuusGZ0ia4tJC2/FJzaMgpcSacAc445n1wNOGl5gTZMN1avdDqey5jgAWlo5zJyy2MwaLMadXvWPBnKBLTKAgrYyn/+bEhpiNAiWb0kxZDyGC272am5QRvXTQWYZ1/zgYUCYIM93gM7tM+XZmtR+h82bfoFyKBLyaARP++BLL+mzqOPOKaWr6Og+Nz71B2oD+4ziastBNBtBfa0tIvevgHXkePqKbah3TzHAEudMNN5jp1kHE3S/YC6RNF9TeMvr+W5lJvFDfNBLpdVpHbA3zgvJifgmDosKmKuD9CGqRZWQ8PXHDzT8mR7Ip4rqJeS4THP4t3MS/6SJ71Xr73KGAypGNZtmn0tL17t94vzId3BT3vmfeUp78tzXig+ZC8XQKAU7nX3uXi9bFoxgvFCyN/G/DbjsmLasCOeEmfBlOAMTnzQkn4HwxzYbO0XhK40TPfsz6JTI/1nA/6CVx2RFBkSOmo3P26VtvwpkmecoOeCrJsmrpEz0uSTiXPaxRq6w2NyHQtjd5C4uIG8nuSHhYfgxKU3HV4UAJeRVXMaR4q2mJLr8oWSC95RhRIQvqSHN7OnklAXCER48SaS484DoC96/ADgfwrKWnzqFvRdyNiFxoSfDU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTE1NzQ4MzQxNDMsInByb2ZpbGVJZCI6ImU2ZGU4Y2YwYWY0NTQ0ZTQ4ODJmZDk4NDQ2ZjRiMzFiIiwicHJvZmlsZU5hbWUiOiJScW5kb21QcXJzb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzcwZWM0YTUwYTRkZWRiNDY4NGM2NGUyZWFlODhjNTI4ZDNlZTY4ZTYyZTM4MjU5ZGI2Y2ExMTkxOTgzOWRiZGMifX19',
            'trail': '',
            'op': 'true',
            'speech': "Batman is the best superhero of all time!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2",
                "/fly",
                "/disguise",
                "/create <itemid> <qty>",
                "/undisguise",
                "/disguiseviewself",
                "/back",
                "/tppos <x> <y> <z>",
                "/tp <plr>",
                "/tp <plr> <plr> (Lets you teleport someone to someone else)",
                "Access to all warps"
           ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 21 9999 2 true"
            )
        )
