@plr = player()


@hero = associative_array(
            'name': '§eB§7a§8t §7W§eo§8m§ea§7n',
            'class': 'batwoman',
            'sig': 'YugJoUtL1nMD2WjbUHPxDFOt3TIYlznSovMfvnYRQCt5iibiFTZucM6EWzJBLz7fBkcNcztxlOuCsFNyBM2GtVY0GTg3TtcKdyBB1xTJYlqwNkadeg/JXXxwBQJD8fr1jd1EvDLx+C4LyrAlG46kIK012DaBZGGIQemO5ZiV61uj6dpegw/KQr+0Z8ZaYdAzHtAAbhl9AyHz8rGB3HCbGM/K9DTVpjuClJFn2MDY17rr31/sr5vwbEeQcYU6ZNJZOaPQXqGpmHQ9jLYcocTRMx6z+gHXWRHIGx8SJBXJLl0JjoyPDCV04z9KJn1O3XX93kQkgirZlFyrE5S4j8wrHOfZ3cjVoXo9lVKCpsEWuexoMsZzqEIOoqnWdtCYC4lwbTwDAAStk8l8bcSFtcXo1ePHq4tOz0+kRMmamQwSNt9u6UY/CEPzxMiO454sH1SomqWntu7l/+tDZJMyLAyeapwgOugwPCbA/T+8V0LI7u5LguyU86ntWZ5hHmRFXR+TmPNW3LdXmIvFTgfq58CDikqd3RmRL9l+HuABLCbciDOg4kwk/aKyUi62t6epw3SWKk1i6bU8tqkE+xxqmaF+YjuWg6VdHmZSoLax/NNcNY5SHJAa+9XWjF5g/ryWkRQF3f2T4FWKmDKszyZy0oCMHLPamIjPktOtHIKS1kEn7ww=
',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTY1Nzc1MjI4NzYsInByb2ZpbGVJZCI6ImIzNDE3MDhjN2Q4ZjQ5YmY5M2Y3OGQ3NjU1MGVkMDJiIiwicHJvZmlsZU5hbWUiOiJBY2NvdHRpeCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODhkZTRmMzE4MDFhMTM3NmUzZTA5ZWJmYTgzYWIzYzIzMTVmYjA3NmE5MDczYzY5NDZhOWViNmNlMDZkYTMifX19',
            'trail': '',
            'op': 'false',
            'speech': "Ready to fight crime!",
            'powers': array(
                "/buff",
                "/batarang",
                "/grapplinghook",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:ender_pearl 5 name:&7B&ea&0t&7m&8a&7n's_&8Grappling_Hook"                
            )
)
