@plr = player()




@hero = associative_array(
            'name': '§2B§8e§5a§8s§2t §aB§5o§ay',
            'class': 'beastboy',
            'sig': 'SoivnUgy40qHsZlXNgEmeIyNe5rkVr5m3Bt1Ye7gNoc8e+eFIKz6p3A1OldgBMaQMNk+fTUKvZHSfzYDBUTh/NL3UVVMcojc9mCKpaP3szmOYWJBA3EkAvEBkfY9UWlP5+LcVccUsK+nzBEg5lY6A/DveoYiv+cW2g7vVPvxPPQoHEZ1KpBmjG+r5edavW7uO1YHAcDz7n0oXJ8MirDYzX75Hf620yU3KXY8+cd55xNAJwfVeQuc/SF1i8rQzuG4zPR0ipqUQ36mJ6ZEIL/9sO+amriLITxGWMuwqY5JCDg+Cipk5Ezs6nXG/eCVNmO6luPQIric7fiTZqXXwdkDIoJoQQxMeuZ3Zl0nj6LhkQe8DVEImjFuZjj7+9XmzA2JvQVj8nFkBV/x96Yc1Qvz0hpnbF+AINBqNFA1kkdVYqaCFgvs3uVa6Wzx5yqy2/TlEVPCc1v98sjYMVRZI/e+QiUdDFku+FZBCScBNsIRL0ryiwUTpq62i+g4DEZVMYebSQfggRn9FB0cduPYtkhfUEo7bMn/aG6AZ6/7X3wRVYxeT3rNOazVgbMhqxvfD8P8kP7G0vreH3enOuMr7ru+nMnPNS8t6nociR/eadhoLbk3I//MqVnWBcxC2fyRFpwkr67Y1vS4Z34p+L/C+QmEWrIAlktmg928TayCICAvfFc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg4OTA2MzU2OTQsInByb2ZpbGVJZCI6IjRiZDYyYzJlNTZlMzRmZjQ4NDNmNGFmNTFlZGI4MzM5IiwicHJvZmlsZU5hbWUiOiJ0ZWFtR0JOaXNiZXRzIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hMGVkZmQxNGYzMWUzNjdjZmIzYWM5ZjI0M2IwNTU2NDMwOTg2ZTcxYjhlMGRlZTY4YjRkYjI4NDgwNzE0ZWIifX19',
            'trail': '',
            'op': 'false',
            'speech': "Beast Boy is here to save the day!",
            'powers': array(
                "/buff",
                "/jump 0-8",
                "/run 0-7",
                "/haste 0-6",
                "/fly",
                "/flyspeed <number>",
                "/disguise",
                "/disguiseviewself",
                "/undisguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"           
            )
        )
