@plr = player()



@hero = associative_array(
            'name': '§5B§6e§5e§9r§8u§9s',
            'class': 'beerus',
            'sig': 'dx44unemClcFenovKKNU07+xH4UHBYvJephEKKpm1URN+sNFILcYx6I5LX1ltv+l66f6UmIkdWje+nElKXzRl3v21NnY85Mwgsy1pocaTIoUiphDx5ug0VSoZVqoqWVbdHVlBO2ytBbnpjW644xWacMnthq8n101Q4fZdQ59SUo86DAMJ2nZzkR+Frs+ojl45hGlN8PtGJx+gNWPAdyiBkFazc/4DsPU7ap3WReWxp0kF2DYa58WPDXMXPpWsgsF7o3J2MJsOW/FsYcw16/nR82SVctamuoVAF0LZRueIjV1YjyxJDHqs/b9sDtG0YAsXOOI9o2vnMwkS1NH0dAsVBYdD4mCya62qnZauPWbLktiVgJg/xqqZCNCq0rcciXXpIX3NKgEZ6ELUZcDoHwVm4wIBGuibN+SWKjiqd7AkcbKkIDSw3d4M/Dx/t+OBCWiu1az/rMhNSEkglTEf6wuwuHGLUB5UaArh96FIcoeUqEX+RrMj+4Ef5QqCAjGfySTiCWcK16hsNiBQ5VAIq89tOvxw81lqxszCwBhZURsm+hjI22nabzWIa/yMbA2y+kC0GikLKwQvZ0X/E8hKNAgp8hSC2WX0XX6EKMX4yBeCJO3+rll96GF+n7w6QkQWWRHcJIMiJCu0whsNQh/2EEeQTXTvLsSJse53fqosec4GC8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzgzNjE5OTc3ODYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Y3OWY3YThiMWRmMjZkMzExODgxMzZmY2Y1ZDFlNWY5M2NiNmVhOTI0NWM1NDBlNzlmOGVjYTI2ZTJkMzg5MiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am the God of Destruction!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer <player>",
                "/dismountplayer",
                "/touchkill"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." kiblast"
            )
        )
