@plr = player()


@hero = associative_array(
            'name': '§2B§fe§8n §210',
            'class': 'ben10',
            'sig': 'rNcbbbzjz31M6qc40FMZhNf8ur22Mx+vPmkSkvuNF2FrDw50RavUNuBGWYZq8XF3vuMcNbnvS62xnf1w0B6bFUawqT7Nj57oNXHW1RapHrUU+OgUhZdqOlqsFNzJSOplGT1uNvyatf0PUDVouZtcnR/zpfc8RY5nLBA5XAmVVpc9UgNtV/stAnPcMyQiv3lE9zbv5/fHReQhtv2UrsdeT55JOCVlTVCitCjZadWAArVLByyPlA1KkQBhkntyMn6+pz5iv4+pCd70I0uh7pD6gY/uJOn5crc2HwlQlzwjf4QGiBikd9nJKW8hdSeX8vlV8+YP0Bcr+0RrLL4PXxqnxioM/X4WwecsiiaIFA+IWdp9Gahh3gXg4i34LrQiUyFEmwhMxDOfVNvCRc9Eb4EgQuvmnYoIdR51ikhPfXFmfDM1xikNKf/blmxsyc1vFuCkm77eC+iEi09WxfL272gZkCD/XkAqepBblT7z6p0s3u+ePktag/LbvPCPhb9z1jBd/jx/UCOKnGKjJNYfm0qpoSScP/VYh07F/Y4uKvDjM47gyzoPMMHFgJN6+f8Sw/Zf0W2R0n5cJk9qi1LAOMWq1efoInYY3ptXNzpw2hGc+OQrH5jCmbsR/SK5ZEqcNlTBbas9GOBSngQA5uZxAXn7r0G2mq/KdPMFLJH/wx5vE48=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcxNjU3Mjk2MzAsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzk4NmVlNGMwMTdiMDI2ZWIxYTFlN2NmNmE3Njg1ZjA4MWU4NDY4ZThhZWQ4YzljNGFjMThjMjVhOTllZTEifX19',
            'trail': '',
            'op': 'false',
            'speech': "Its hero time!",
            'powers': array(
                "/herotransform"
            ),
            'buffs': array(
            ),
            'alts': array(
                'heatblast',
                'bigchill',
                'alienx',
                'lodestar',
                'goop',
                'fourarms'
            )
        )
