@plr = player()




@hero = associative_array(
            'name': '§2B§fe§2n§010
            'class': 'ben10',
            'sig': 'XvKFuz3dsDs9yTnoqWguVXV9RDKv42cZVe+alaiepY7wFQqzBoNdMwi6OZkxwIXUOj08iVk0Cb6T/Nc4EMpCOB0D1s1vrSSyqt4qj2HT8G5vQzYNuOV00qMFXlghnfbWVPbeSWrbUyDh1oa4157iGyLwA0wCFo9ai+ODdwhTtf6447hKqsuTxDgdJGzw1N11bt8C15LjnKKghlIUc3io8MSlzagl9uUBaSRssXOv2N5Aq49sI7LyOerJ01V3oI4eYCXo615vSNUh/ls6urx1kwi4/hZgU9HcRcvkcmo2UEV51YVULJOQWt5j75Pgy0aQjZ/b10fOfJF9EpTn9ZyWEvP/9zJCGj2QK1BSNW4tD3KnSZGPMOmIU3cBX9uVJ/z+fj5kUGlvlLY8x/XewKf+lgmCSYop5xVykU60vRGMLaNxF3nUUUGgoTFO8n/9toaYwP8rMs4IDqeTEWeejcCjz1FihssteG9ty6noTPN4brrfe8uCoU4By/edNje1VXgt0r1KwJ4RDnXKAw3RpszP+K7MylRcPwNObGRG2Mk1c6CZ35yl9bikbMauXvSjlqYcZ3RGehrmk8sfSFvhL7HM1S0KInxbYH/H4Sywc/BeTzYwPDSn/cRZkQuxswfLiPR3GeZx41HKJd7YwqfmpFCmduaQu9J33GiOar1leepxDzk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODgxNTgyNTAzNDQsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJNaWxlc01vcmFsZXM4ODgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzYzOTE3MTM0NzQxNDZhNzBlNWVlMTFiZGZmMzhkZWE3ZDkzNTgwNDM5YWI1MTg2OGRiZWQwZjhlZWJkNWFlMCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Since when do I ever mess things up?!",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-3",
                "/disguise",
                "/disguiseviewself",
                "/undisguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 4 true"           
            )
        )
