@plr = player()




@hero = associative_array(
            'name': '§2B§fe§2n§010
            'class': 'ben10',
            'sig': 'XvKFuz3dsDs9yTnoqWguVXV9RDKv42cZVe+alaiepY7wFQqzBoNdMwi6OZkxwIXUOj08iVk0Cb6T/Nc4EMpCOB0D1s1vrSSyqt4qj2HT8G5vQzYNuOV00qMFXlghnfbWVPbeSWrbUyDh1oa4157iGyLwA0wCFo9ai+ODdwhTtf6447hKqsuTxDgdJGzw1N11bt8C15LjnKKghlIUc3io8MSlzagl9uUBaSRssXOv2N5Aq49sI7LyOerJ01V3oI4eYCXo615vSNUh/ls6urx1kwi4/hZgU9HcRcvkcmo2UEV51YVULJOQWt5j75Pgy0aQjZ/b10fOfJF9EpTn9ZyWEvP/9zJCGj2QK1BSNW4tD3KnSZGPMOmIU3cBX9uVJ/z+fj5kUGlvlLY8x/XewKf+lgmCSYop5xVykU60vRGMLaNxF3nUUUGgoTFO8n/9toaYwP8rMs4IDqeTEWeejcCjz1FihssteG9ty6noTPN4brrfe8uCoU4By/edNje1VXgt0r1KwJ4RDnXKAw3RpszP+K7MylRcPwNObGRG2Mk1c6CZ35yl9bikbMauXvSjlqYcZ3RGehrmk8sfSFvhL7HM1S0KInxbYH/H4Sywc/BeTzYwPDSn/cRZkQuxswfLiPR3GeZx41HKJd7YwqfmpFCmduaQu9J33GiOar1leepxDzk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODgxNTgyNTAzNDQsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJNaWxlc01vcmFsZXM4ODgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzYzOTE3MTM0NzQxNDZhNzBlNWVlMTFiZGZmMzhkZWE3ZDkzNTgwNDM5YWI1MTg2OGRiZWQwZjhlZWJkNWFlMCJ9fX0=',
            'altskins': array(
                array(  
                    'sig': 'G3O+diTPbErKe3PzQnIbVEMLEKWIyULVw08a2mNY1Gulu4T2fcxfu89cZA34i2S3mD4TYYzWzubtBy/8LjnTNx2MwZtvQsnohyYLRxeO/NCGqRO9Yt0McdrXCe3Ci8jJpQ/hGXne8wS2dsw6zojH1By9fYSyxgGTqgX9kqQJ2lS4Gfe01rHYZlWp9Qiz3Jly0edCLLOhO8WVWyzMITgfi8vyaBJ3WZ5q+zDiCDV9mIH4V4Ze5lNHko1SA8JE8BWDYyfdtZL2yX5Wg1CjFoO3ZNhhXSmqmsi+lpPuQVCu+sIGJoMxibZ2DHYccMj/nHBWrfcsGcMmxLE0cCrMCZ6AU8qRnWlzpxpr1Q1RylPs9YiwPMf0U6EASOn1fjrYYIj9h6xveHCEfZ03l5NQjBKsbvqIA402WIGXIPv2LcU8or7H3B+QYdhG2cLt6BayB0Fpvm82z2XWEfR3cC95Fcf3hoF3xY3a0dGVvG9Pd5TOxdBlR2SeNWn7cT1Bq8SkGnVnJ3Wnab6BwA0C/kZVC/RwzHmumbb8seRos8gEOzt0fXx8vNOPG0Zhvm94scFdhEEgdsOcZksJzoXXdB6unHrVagJs1ZLuD/YwcxqHVOZrFNtM32w6ich/xMltwAsBJzAY2eFAl00fQ5Gqv1Z4m8soOf9L8WnscXu0VaD9kBUgSyw=',                    
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODgxNTk2MTk3MzEsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJNaWxlc01vcmFsZXM4ODgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzI3OGQ4ZmQ5ZWY4ODgxZTZiMmQ4MTMxNTU5OTY2YWYyMDI5N2NhOGFkY2NhZjhlNWZmYTcwMzVjNmQ5MWU2YyJ9fX0='              
                )
            ),                            
            'trail': '',
            'op': 'false',
            'speech': "Since when do I ever mess things up?!",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-3",
                "/disguise",
                "/disguiseviewself",
                "/undisguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 4 true"           
            )
        )
