@plr = player()


@hero = associative_array(
            'name': '§8Bet§2ty §8Scha§2efer',
            'class': 'bettyschaefer',
            'sig': 'Y50dKeXcF49gslX1gqKps99eAkgLiTJhMOn0Xkfv/sLjiMtpyxemfVvsrND9kZjDwfGhkxhgxVsMUckmbsmbg4F75oV+OjLyJ+DOu6XLxxjKIU60NygVQYv/CcbDyFi0V2o++0WKq97X+9cj8YvpalvYhZfvMFDHiYK0EMnEEi0RUBW0QV+HWarw4GrQb4Bs00gXLMnsfRI04zu+F8M3GZRz77kj+AeATLqOO+NyCLBTZgWccsZvu7X0frpQupnuVBBqx6tKrvWxO5rs2Xe/AEo3cNl+sHChFWcYDKjaMMXibpBVfafWszjEhRBGjk/Ug8Dg4P9nlJKC4CwswZ++Oj+cePVyVTytBk8AYuoymBltNORXbIfU/vEGNp5QBDUrRFZ7OjG9iqw6SBRD0S9hHohGh81RJLkDRxOG/Ky07cphTdasER7VbUiVkP+8Z42IuGJJ92YjuddTbBJgdncVM1WJFXakGzy4dtxuAE+7tCbBPrp6+/t4+oAi85vRytbcSzP+k6jFARbBtSg5HBLsQyneqzDCHjWpRbT2sKaKMdM/gsjL46t1xx2atwduZmGKigDBd5gAxGn9PutvSSRAr6gA5FCkQYGbFhFAQsA0CGiTcFjxntIjvKvEB6DOYtPPC2zj6j70WaTxnr0etHVCdgkHBC9eEWjiG52cLiGcZCM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDAxNDA4MTUyNTIsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJCYXNpY2FsbHlIYXJrIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjljYzg4MTYzZWQ2MTNmZDUzYWVmNDMxNDFjNWY1M2YyZWFkOWRhNWZiZmY1NzcwNWFmYmE1OWVmZjYwZjkyZCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Oh, I'm sorry, Mr. Gillis, but I just didn't think it was any good. I found it flat and trite.",
            'powers': array(
                "/buff",
                "/run 0-1",
            ),
            'buffs': array(                
            )
        )
