@plr = player()



@hero = associative_array(
            'name': '§bB§0i§bg §0C§bh§0i§bl§0l',
            'class': 'bigchill',
            'sig': 'iIO4qURoinag+HRasHZh4AuwjQUYk0tn72gSeBrKJqGoDNcfGBcheLsq1IOv/5xWnaAqC3yMRDJNZfyFIgoV35H+Ol0Yus5abJHuD7raswjjLbROBZPvfbkt784QHsrStg3i4o1MrOGd+6lXlwqfiJWQQmbZ4KPHH5Gp8YjzlFTA/RliehkeEP+6UxAqLaSxHUmM+/JxA2mPk3JDnTiarg3DB2rjWmUxuHSIzV36z+q9krD9Ye3l603knwkqTd+sLAGR5jugXxRCae1Hdzlqg1Sd+hqUU0o+95gnSds6W5brEc4Wh6dIl4dwC2FerCvJ3SqewJekHmqeey7LNv6YiEIB34cDI1vR+tCrEIqdv/6yry4r8Ovy7BERDGawYw6AWf1cL2JOcW552M8BK0GWQWU0TXitDfPCVmTCtJM8Z2TIRwyT0GWY9A02MC4rReZG/O9d2gBWeBhQh2tuyVR8PYfcZaa5vLjE5pc4mhVg5r5zkv6kXN9vR7AsDPruMVPaFGY+Z5wWEaJv49iwqlXjBiMbblq9PzfBuSOxEE04dsmLMhzdnHkUo8POBiYFgrdAcR6Y4exF/516HkxjGuBVjrxIwbXUJercINCBMg6wvbL88XJ+E9SoSLG7/H6kleD3ur+wYz+1Cpx3NukiOGlzqr8OwASE6AX2mouZLIFt540=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTU4NzA1Mzc1MzgsInByb2ZpbGVJZCI6IjkwYjJiYTZkNDNlNjRlNWM4Zjc3OTEyNmI2OTY5YTljIiwicHJvZmlsZU5hbWUiOiJXaW5nQXJtb3IiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2VjMTRmOTY3MjQ5OTBjMzVkNGZiNmMyOWVjNDdiNzU3NDlmNmIzNjlkYzA0NjFhNTEzNTcwMTE2M2Q5YjQifX19',
            'trail': '',
            'op': 'false',
            'speech': "I suppose that's cold comfort",
            'powers': array(
                "/buff",
                "/intangible",
                "/tangible",
                "/jump <0-1>",
                "/run <0-2>",
                "/thru (phases through walls)",
                "/fly",
                "/cast freezeray",
                "/chill <player>",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." icespike",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&bWings"
            ),
            'alts': array(
                'ben10',
                'alienx',
                'heatblast',
                'lodestar'
            )
        )
