@plr = player()


@hero = associative_array(
            'name': '§cB§0i§clly §cNum§0er§cous',
            'class': 'billynumerous',
            'sig': 'U2XG2C3IbPEbrOGBlvJgdt/IYdXXxjie98l46T8GxHljjw+Jnl9rkab+ZEtYkSktj/9qu0Zi6wVzz/dXYxnsv+9CIn+6BZxrmVsjzCSP672uN8q0n+jQN8V7q+wtaSyQqnIRewu7IUKYNr2/wNsMPISbFbBtMbRb4iABelbxtBHHnZ7+GsOGVl24gHeK6Qm5kpJjUjpJD1ID8FQ5GKRp/Y/6UGBnnvWUlGUFFzRCeL7qGubm6DaQI1my12nohZumMOjixEOLF2kra78j4jPqMia4a0QndeOQvXzTOtsRiIxIT6SwWONVUM0pCDtg4GiA/9mwrwV2lPybek67R03r129JWl+QzoosJ06wNV+KnQeGc5k+e7Weo807e4g+ftJUE6JHr7OS1A6nYS1fMUUghwpOFXytbfqIIrPH6o9LC9J9HaQo8EUWnXsy7/pXwSJi5cUxbiqpyZ6F5HHQZx0sg72bxXEnhHugSV5krBk+FPbB2bh6icC9Y3N5Bd+w3rj+wK9tE7vpYQoqe+zoH1JuoISmLWDFQZm6O7Sl35sYq4ShbLjjLjC/EI0otzkycD1FcoW/4HU9TfNdGg6zckwf3Q/sO6sC0v9g6jZogqp9JdF9OZhIpIVqR3h3AY2+8HoMztSObKzLi9boWboCQyoccyQl3xIpdf6pGNBe4MG/hvM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTA2MTIzMTI3OTYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJKaXJlbl9UaGVfR3JleSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzFlZGM0N2ZiOWExNzNjMTJlZjc4ZTgyMjdjOTQxMmY0MmNkZjI5ZTVlNWNkMTEyNjc4ZTI5NjYyMjZlYTQyYiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I can duplicate myself!",
            'powers': array(
                "/buff",
                "/cloneself"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 8 true"
            )
        )
