@plr = player()


@hero = associative_array(
            'name': '§5B§7i§ez§5a§7r§1r§5o',
            'class': 'bizarro',
            'sig': 'CjOf5jLXooK/j21xB7QLUpZ2M2HmLep5NR6YO51o75Ms6kTVCxv7DT8higtZQozPfwuzBgpKnsCDQFekG8Alu+2VdxlljasJTBhQx5LJmbJF54k6m3iQJjVGxlobNGQB84TxTCt4SVtoR2SpZ8jJzbgUsOZj5H6/6psoUYmFMIeNTsyU7vCY8ueTgFhoLeqBRwlc79xPKIcQ2HmOZ/SUpxJ1rpnG5MFz3sfXk1F1hbfIVcQhgTicU+sRmm92W+J+jmYlWf/W269LoVeh2g7iL1+Nf4XMHq3Vn++8/AgQ/upkABRWAu2iMjWX/Y8doPsIQQH8HFkNWKbDamR4DEEz7x1easLn2QvULvSIvXcEAAHEszKhEdJLSlgwaYfnSxM8L2XgVDccrwrmC+M2csEnNfYZe95VORGx8Q2zbgOsR+Hd5udLOF5M+VP2XSHMQj4nm+yFDReixmlau2W2PAXsJ1svqQRO292CGRT3re4Tpryc+TVONDcWqhWPpFyAzJv5ZjCZ/U+xjIfGbBw8h8ZbIfPBy+52//7n/c3tK7/V6pHkz/Hs+uNQLD0puCA5jggph2twxZzCwMt4nMCA6XgIPaVqu1siiliw4zWO4fpm06s8M2jNi1ltcBslBUbmw8//eU7vMvDBq3F5+Gu0tFK5j6/onzDI58anh1c0F99pvwc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDY3MjQ0MDYzODgsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJpaVNpbXFseUhxcmsiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Q5NTE2YTNiMzBjZGYyMTU0Y2FjNzY4NjRhNWQzYWQ4MzY5MjgxNTRkZTMxYjZmNjdlM2Y1ZjhlOGJhZmU3ZCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "No! Am Bizarro!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/break (breaks 1 block of whatever you're looking at, including bedrock)"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
        )
