@plr = player()


@hero = associative_array(
            'name': '§8Bl§ba§8ck L§fi§8ghtn§ei§8ng',
            'class': 'blacklightning',
            'sig': 'i/3PLYB3Y5mxX3z2hjvgFjnQQsMEMxo+yt7pJCi5PLFrNtgBDK9w30KmOtvMRAsakpJBf3ErQxqg9Q82HZqeU1jwXbLMUp6z85GNaNf0N4PG+47JcCQ3Q0B2+YyWLJK/QK09TTEmpmgo4A9PkHmek8BEEWNw0ty4qKDukcHed2o07Xv/94FFoW1iAoJ2LwhLetTDO/6/244qdMrfhooIOGoCCDADERzhK2b2eZfnPEWQlKOitmn5OnVAgVhgFFs0uu7yDNDIcuz480mVxiybZRs2ezIuw9QOrbxncNqWdMsMatiWbKOcJqqswiO1IxUZhjsnn8KljuZm7+4+c5JCcJKUDgB2No+upINld7IOicOLSGl3/IboFgk9BYFHZdp0q19M1hwfuQlKrgGkZAzgYgun/RCkCFg7ZFoQDVdegIj3ZZ0KXkRCQsglX/39QY24R9PeVitCZP5fiDT197Z+Cw2i7da10U54800Ye305tjeEiye1F7j9B4jM0rp6d2TDFJQFzCyjeGk3SpbeCWJBI6aFJzmAf91LDNjFq+DG0/HTfHjYOCqf9W+ENNRcSQnaxMuvtiKFFWCaAWtHRLymqBHGrnjuHQdogIffRQTV9SaV5vJMv9Znqf16nDulm2kbMrmwT05Z9mE5tQoGHE011UsxhSCxS3suWu9kIpeeuH4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE0NzE3Mjk1MzcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJSb2JvQ29kZSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Q3YTU5ZDdkZWYwMTkxNGYzYWUyMmExNDNhZGQ5NDI3NWE4YmU1MWQ2YzJmOTc1NWFhY2JjMTE1Yzk0ZCJ9fX0=',
            'altskins': array(
                array(
                    'sig': 'nb3kLL8IoohFSyYrg5hUr9K0RmhBtac0MpHRpClrhaT5BzG6DIm7XzxTFD3ilbf6n4MGhRgG4YHpq3wm8RW1bf1ZBsXnxdtZ8plJDMmDiAokAvcGEVr5H3LPBa21cSYlDvmeTQgi0nZ4mbtsHfXWA3VAs2PHyAAKQQzwTQJ0lMRu1LhD5mh0QpDpdkokJNglSc8S98/rVFP262phcTE6PpvI0zG1iDz8OlHqWmTR6XHx9ryNdzY5HyIHRESJe3nK86ls74E6X2U5G7mGkF2lCn2EshR3jcGroI9dCgOH+n1d1QbV2uFb5aYH1IAQYUx3nodByVDVAe5/4c11OkrWhC7jJQX0RkqB6O+U5fJOdKcHh+zlHTdqS2Rq4odxE8YjKLEvd0nRmzWhZ59h/E0zqrOj3GdIYOeYqPI94/3tbyhPabW4mjyHcYnLh5DRm9kMSfbOTvNmwxOYEchPue/7/2+ZMdT9dutNYeLgchbsQnUdrmc9N/m12sElSkSxz2VMvjTT71X8tqZ4ZgiJ/ODUixthpSA0RUp9Q7CZ83GlkxgiOpEPzYYGVnKPxOolSDE3FK8D3oWCbWpUe3IwKJpLb1TvkQW0FiCyuEtx8O+LI2If7pkdrl9mma/Am+4hTumYtt1jy+p/18zp5ei/Blirp9GlLnjC/xXS6d6jhWqLwoc=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0OTU1ODc3MzM4ODgsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJUaGF0Q3JhZnRMaWZlIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jMWM3ZWM3MjhkMjQ0MzE0ZjQxODMwMWIzMzE2YjE4MmE2MmNhYzg2M2RhNmVlMmJhN2EzZDgyY2VkNTE0NSJ9fX0='
                ),

            'trail': '',
            'op': 'false',
            'speech': "I am Black Lightning!",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-6",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." whitelightning"                
            )
        )
