@plr = player()


@hero = associative_array(
            'name': '§0Bl§ba§7ck§8 §8La§7nt§0er§bn§8(§bS§0G§8)',
            'class': 'blacklanternsolomongrundy',
            'sig': 'ZMLjSfMIUCkLK8wqJXJLaayfBAgGnBE1yFERsqSry8W5ln2+2ArZD63SiBvfI8ZNOjYwtOLqny0OOAdIqdC8t77X7gUKEYAdyG6j9qW2iroiG7g9g6H+jc+bZb5zHG51cIrC2Lmq0XTa8V4GlVjxVi221YhLYiouMTJpPmlr2Tutwg7sh5eFuynwdsKxFRR/WT2dI9cWyT383uWWkBNtkBgbb9sTM/lgOcR6fLYBWMsDgGb9QuLoel3ocDp7zcFgFiDHUOEv/RfamienJbRRUdXc5JK3ku+Zvq9CqsrqvUb5eyUlc51jqBt3BDbZn/dPxZgv0iFuvAjmr7tSB/8/5zrncB8dyelQK3zt3U0f1FmX/UdbAKhMUfPfr/nxz7hr+nMZAqHudUjBSsefMFy4zbPOtNKLzMox++MASNSwLd0NDvFCrDFlk65o1kONQFr4/gOkUbryuTTK5oJb49vDnrYX7mqAJBD20mCyS3eDhRPLNc9dhc+sdiaDd+oLwDf8ODv/lCZ2VqcbT3dTbH66JDvqdUO3AAAOBXMUvZSckEsXjADcTPlqrnayXc/XZy6j1EB5R0rypg431FYZFFtUgtOrXcYXmfPT7J6yFBd724R84MK4imr7J6Xz1QNokxyWpWfqpJZPFgS0ceuOikSviBpRl3UqfVO+7lB4/c7O2Aw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIxMzE1MTMwMDYsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTJmNzc5OGM0YjczZmVjZmFmYzJjZDMwMWJiYzg3NjliODRmYzJjY2VlZDc2YzVlZTdjY2VkZDVlZmJlNzAifX19',
            'trail': '',
            'op': 'false',
            'speech': "Me Grundy and me Lantern!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-5",
                "/fly",
                "Protected by Nekron, mobs will fear you and wont attack you"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." blackenergybeam",
                "/give ". @plr ." 95:7 64",
                "/give ". @plr ." 263 1 20:2 16:155 name:&0B&8l&7a&fc&0k&8_&7L&fa&0nte&8r&7n's_&8Ri&fn&0g"
            )
)
