@plr = player()



@hero = associative_array(
            'name': '§8B§7l§8a§7c§8k §8F§7l§4a§8s§7h',
            'class': 'blackflash',
            'sig': 'e42VJxVNfRhyRzTLBx7MWe1elqvi8yqsOl7IHH/Xu2NMAsVGnvr0CbnP1tphd91flUUUJdc6aL3DdUOtveCMkezmIcnodwRQ6ZBxT0W6A9uJIjAbpRVqH9lq99FUifnS/7AAX7G5aZVUpEs3PTNsQiyVsXNN5X2G8KeDjjBLGMnKCis6asMHDVlBEGM0Q6fv7T/obn5tbDgUBPb+rhnOb6M9B6tz+g2a9VQnheIg42ulZY9k9OmTYwIztr1oT0u77LJmdnVetXydcUXCCndTjCANeGP7eer1nuGrCS+kGqic5cPVF5DW0UO565N80mG/azie/sRgndeKb+A/zgNsZ7IWW2r/yNg1iotbMPxiY65aMP55i1P1wDyJVxK0vRXZlnCY8qdbT2auonypKp1D01UbpGMrxKKLpgpOELwlfvjDq2iTl2qDrWMXe+VKeLAbvGThrb2EcnqFlitnRCvT50LXKjuZf2j3amSMlEdM00RqW/TEOiB6PHqTTyA6kFGdC81Tlw+jObcTlh1UFxu+mtofrTmDdM9DbLjxuYS7KH/wp8hstsFT5z2RMPmdy8nla9CvJ/SbGgII+1dgFq/GN585134/GalmCt1rMLVIt3n62czc/7odMs9qLNsLS12cnuuCAf5s6cmasPSTO38d7XpFLAzc2s+VSblBow5bCKI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzk4NDMxOTQ4NjYsInByb2ZpbGVJZCI6IjAyZGM3ZDcyMTk3NzQ5NTA4MWVjYTUxNTMyNTBkY2FkIiwicHJvZmlsZU5hbWUiOiJSaWNoaW5hdG9yMzI0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82OTVkNGY2YWQ3OWFlZDIwYzU2YjEwZjZjMzE2YTE0NjYwZGRiYjUyODExZDJkYzc0YWRjNTk1YjBmYWI0YzgifX19',
            'trail': '',
            'op': 'false',
            'speech': "The death of a speedster is near!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-9",
                "/haste 0-4",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/speedforceheal <playername>",
                "/speedforcewhirlwind",
                "/run 0-1 (In the speedforce)",
                "/thru (phases through walls)",
                "/touchkill"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
