@plr = player()



@hero = associative_array(
            'name': '§8B§7l§0a§8ck B§0o§7l§8t',
            'class': 'blackbolt',
            'sig': 'gJkaneYNd5DvbDYGINhXQdnsmtK2oyJjdBH+9PnGcQamUTmtxf3yF+j73zyk58004B5CoFOvR/AKJYQf4437h5UtX6CDtYz1TSOAEWxlFlBBhJiXvyEKVQjQcsv9LG5W3HkUDYqJKweyr6cluGXo6BrIAN2NWkIF+HfHUHHpZlPnSZnKV4KxbtmZxz/q/4wgJWWC7jCKaqaqbHl45yKRoTj1hRG6yEWa6y3j0C0TZp4mT/9JFiORx6qWvuAFnV2zjPnpEfqhRn/YlEmoKtlfAnrKOLD2kxO1Q5+/6syJDJPE1yP3OPTrABIfYot/YOAHFH7Dbcvlm60qzGvDkTqUxO+sSQ+ma++EbqTJ+UjGv9SebM9jlWUsU1QGA2bkF0eV8qfSqoOojsXeN75lrhtiOX36II5gZqxR7YWXrVAtLOFPP5Z2USp5opd8uJQWOrTXsXCy6tyvIhZAL+ay+J8ii1TgBF6pysuUP4Nr4mC06aSiGQVEZite7pLVKOnkiUedd5GKsDlsY/wCOy6XEYoPliZqnrSvYFrZo4hb7yuNAxMhhxYP9Ccaf7T7YX2Fkn31IR3LNG1hnGbKhtopbDYQIlJXdxlPn9vvQ+N0zBTqwpErv1gHLc342adLeh4BEPLYVuttHK/WD88EQeREi5Xxi2EnA8vYA3aOkn3vtBLtjqA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzIyNTQwMTEyMjQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2EwMzkxYzhmMjhkY2I5ZTdjMGJlZDY0MWYyMDVjY2RmNDU0ODAyYTkzYjAxNTZlZjdlNWNjNWNhMjNmYzA2NiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "...!",
            'powers': array(
                "/buff",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-8",
                "/jump 0-8",
                "/haste 0-8",
                "/yell"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true"                
            )
        )
