@plr = player()



@hero = associative_array(
            'name': '§8Black §6Racer(WW)',
            'class': 'blackracerwilliewalker',
            'sig': 'qndDgq/htoj1x28Hw7pUsA1Nw7/WF2uGMLlJb5tMQVpZbE+R8s8+ZZ2muK4SG/H9YhgE9Jpawjxny3r9ro+3drF5u9nTKluFPaazvpM9lsBRdvsaHGvlbcIFX5C19bLn+urq1czMMy2MF5FHudLiuYc6KOhP0ea4Ov2g/Otk7TShwPWB+OSNwoQIMKvKCLmvV6DKPN7GXiLA6XuZFqenofj4RdRG3o7JtxrySJVUWrNqEgtoyJ1HxyEtKrhk2UBkD8XAYXOW830qza9ieXH4W1gzz9H2nEcumi+4hqykp7PbpRQGrghkcRePT0kGBEuigRljroKq7i2h2zIzjO14ygWWJyFw5qLVPdCAnSEtAvxcRplrQ0n8M1Z4Bw+M2fKZps28ttd9BKAeB9eCxfaQt3YsDSWo6h53PxgybrtgaItH5o/kfAhw2alNzSV79HetG50jAQiY04LVFNaG/tN8NokKoxJFH0CrAjPkYOvaO+F4ENJBaLwRA1G5GmN0LjBCKKzbc7con5WuhIElmTCeDzzdWPwGp8vGiGNOvf3PFWV7gE6i20TPuFhc5iUBGOEQpnE1YbayjMQjnC4oNqf8nQOp7uKtDZdXC77EDrt4gbo7trR+eNJ4vPHnBBo0gbdyZbKsqRT5yjY8ObhXwEd8ZsdT7kwqZk2Zrbep2ODhges=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE1MTUxNTA3OTYsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGVjYjIzYzgzMzM3NmE4ZWQ2ZWY5MjQ3MjFiNTRlOGI4MTc2MmVjYzYxMWE2Y2RiNjQwZGRhOTU4MjM4OGFlIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': '',
            'speech': "I am the Grim Reaper of the Speedforce",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-9",
                "/haste 0-5",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/run 0-1 (In the speedforce)",
                "/touchkill",
                "/fly",
                "/fly speed <number>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 254 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:golden_hoe 1 16:255 34:255 name:&6R&8a&6c&8e&6r's_&8S&6c&8y&6t&8h&6e",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"  
            )
        )
