@plr = player()



@hero = associative_array(
            'name': '§0B§8l§0a§8ck §0F§8l§4a§0s§8h',
            'class': 'blackflash',
            'sig': 'e42VJxVNfRhyRzTLBx7MWe1elqvi8yqsOl7IHH/Xu2NMAsVGnvr0CbnP1tphd91flUUUJdc6aL3DdUOtveCMkezmIcnodwRQ6ZBxT0W6A9uJIjAbpRVqH9lq99FUifnS/7AAX7G5aZVUpEs3PTNsQiyVsXNN5X2G8KeDjjBLGMnKCis6asMHDVlBEGM0Q6fv7T/obn5tbDgUBPb+rhnOb6M9B6tz+g2a9VQnheIg42ulZY9k9OmTYwIztr1oT0u77LJmdnVetXydcUXCCndTjCANeGP7eer1nuGrCS+kGqic5cPVF5DW0UO565N80mG/azie/sRgndeKb+A/zgNsZ7IWW2r/yNg1iotbMPxiY65aMP55i1P1wDyJVxK0vRXZlnCY8qdbT2auonypKp1D01UbpGMrxKKLpgpOELwlfvjDq2iTl2qDrWMXe+VKeLAbvGThrb2EcnqFlitnRCvT50LXKjuZf2j3amSMlEdM00RqW/TEOiB6PHqTTyA6kFGdC81Tlw+jObcTlh1UFxu+mtofrTmDdM9DbLjxuYS7KH/wp8hstsFT5z2RMPmdy8nla9CvJ/SbGgII+1dgFq/GN585134/GalmCt1rMLVIt3n62czc/7odMs9qLNsLS12cnuuCAf5s6cmasPSTO38d7XpFLAzc2s+VSblBow5bCKI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzk4NDMxOTQ4NjYsInByb2ZpbGVJZCI6IjAyZGM3ZDcyMTk3NzQ5NTA4MWVjYTUxNTMyNTBkY2FkIiwicHJvZmlsZU5hbWUiOiJSaWNoaW5hdG9yMzI0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82OTVkNGY2YWQ3OWFlZDIwYzU2YjEwZjZjMzE2YTE0NjYwZGRiYjUyODExZDJkYzc0YWRjNTk1YjBmYWI0YzgifX19',
           'altskins': array( 
                array(
                'sig':'c3sfw4RH8UBngOenN1mhFH1kDuNid98mproMQFSV5tNWdb2gAVkfDdcAdd573fsERQGYkAz7s23/b9tBfe8mVsX520HaVfrcPiEj4kFQcGRs5ifB9nhT3OU8BQ5c4jgZyaUH50eNpnu4nwCIWTzJOPuOp68UaMyyQ5kGVE3+nvv4HZtX3iODSosdfpy1xQ8H5VDAFnvlAv1HJo67MWBWTsoMZeX0HglrQ4kfYiAeFv+uI3qwyhZsgGeUwSmZhUDM1bJLVbwFOSrLt03sseqIYslrxw4Q8gl0LRXH9XeZcs91185e3hqpVX79XHso0/uLTteqg2yelusFfdTrD8M26ChEyjJFwnn+vCjIcFOgbORstgdPA+fPnCxFh85cwP9GjGVRxkXdy/W+gHulVb/prChoBv6H6tWRjDZmiztoPsNGz+DwGj/h9BWKanUPLPFuiX3rJOIVY7/2850KUSS68M6tliKD489l7LaOSWhMYkSb6JY32UNgozzJHr7zflWBgNv6H09rVheCpnaUTyRvsSTdRKF7y9Wt/g/BRyya/jqYHUL0mL/AEiBRSXDwBaIvJk60JSsjamscNg7Y2dhk/epcujLapn8+Aj0tkFFkPpcqVXqdGtchVNNWv3YPFV23USX8Ft2Ax+MHnZxMoXfyBQnwtbZinmeaaoufw+YXp7s=',
                'val':'eyJ0aW1lc3RhbXAiOjE0ODk3OTMyNzYzNzksInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJTdGFyYmVhcnp6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kZWI3MmY5MDUyZmJiY2FiMjA1OGQxNzk1MWMwMzU3Njc4OTQ2NzY5YTU1ZWYwNjQzNzYxNDQ4ZjNkNWJmZTllIn19fQ=='
                )
                ),
           'trail': '',
            'op': 'false',
            'speech': "The death of a speedster is near!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-9",
                "/haste 0-4",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/run 0-1 (In the speedforce)",
                "/thru (phases through walls)",
                "/touchkill"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 255 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
