@plr = player()


@hero = associative_array(
            'name': '§0B§8l§7a§fc§0k §7L§fa§0nte§8r§7n§8(§fM§7M§8)',
            'class': 'blacklanternmartianmanhunter',
            'sig': 'lMli+xUvFgFAQBdXL/D+jHUUe/xLnfemN/YteT00TZt4zZ3C9MvXJ5RZ59r/O+6Rabh7/BKqjFkmjsaj01ogJqdUrVUAvV1EEZaFlWE6kmDgfMx0uE5ypuOZiCe8DW9lKB0aDFZyYKvKQ0qfNcyJv8dxUYhRNQJHLV+f6RBdevAtHJsW7rGwgkoux7alsLTNBErjRD89wMG91uB5GF4QemzeMBuwC3D58jVSebcEfFMhfefKFT+FgQJSVFHk6yHvnh5LYlsBOojNoFKtQfE1TPsgMcM/tm/qxarACxyWPVhbEplwXl3hRwNx278hFlCTZDDiG9bJ4odsVLTssIRF50I+a8lAxiin93hhLSXZh0MbIoGo2RKnPlmEVzKQbMri+1lUE2vaMLa4/9PATxmM7zquMWib5ND1d1/11pLQobgtwYtrtrc52dgyIX+0OYxg4z19vO/MTiPNt+l6N2QRaXjtxOdl/zJNHaTEljQ8qky/BxnKQZzrpaJ/6vLj7DEA364iONv5APtRWEfO61cfh/UpVNy/C2GepD1VuVAe0FN60NDAiif/fbrSCAqmWLCx7rXC3xI4AFWIJ4gckcOLYU7xJt8hLSLDOIbMRRhqTXlzg6vv6tSAwEL2kqVCyYi2F51m9gAlHGCPfjbL5XJ4b//sBoLKrRP/67xmwRDxyfA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIyMDA2OTAxMDgsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzg0ZWI2MDVlOGJiYWM5MzdjNjMyYWE3NzcxMmMwMzM5NzlkNmJhM2FmZTI0MzFkMTdlZjZiNjcxMWU0OWFkIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "The DEATH is worth it. The pain. The suffering. The future is DEATH.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-8",
                "/haste 0-7",
                "/flyspeed <number>",
                "/fly",
                "/intangible",
                "/tangible",
                "/disguise",
                "/speak <player> <message>",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/invis",
                "/vis",
                "/disguiseviewself",
                "/confuse <player>",
                "/undisguise",
                "You are protected by Nekron so mobs will fear you and wont attack you",
                "/mindlock <playername>",
                "/msg <playername>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." blackenergybeam",
                "/give ". @plr ." 95:7 64",
                "/give ". @plr ." 263 1 20:2 16:155 name:&0B&8l&7a&fc&0k&8_&7L&fa&0nte&8r&7n's_&8Ri&fn&0g"
                
            )
        )
