@plr = player()



@hero = associative_array(
            'name': '§1B§el§4a§1c§ek §1§oR§e§oa§4§oc§1§oe§e§or§9(§eW§9)',
            'class': 'blackracerwilliewalker',
            'sig': 'VLCbC0ELZMfnDfQAHlGPsexIw8pHxMoyyd5CXOh/X2ivzrjfY5DfLAVmVMyrf8/11sfH1lJcbrtC/GGs/b75VnG52H1oDRn2UGUlWerDTXsuHd6mtvV+xDFdS/Klg8hX0ZN2Ygd428j8GWhWmWVQS45xREsvqo8QZrwlZz2zsKAVtOiKQ4qMUK/ZgL5lvGwFGUzYYuF6riIUjKAbGo9LyS709Q8HJVnDYdM46Y+kd+QJEeodz/fjtIswiGeA1s0He5B+aP4C5/JxBsqeUcj658sgewIvnRLpU66xcsxnbZUi9okQ/PPXW2MkQFQaxtNEXrjBPE8f5Zv6urQ4Fj0/BBRkyKyDo0hZh/qq+Iy2GUhGUCUsBKJgF5ZIb/SpQJXIobS8R4kQOuQ+hbqG32oiPvX/R5A0HwwvsosFDZQVymPgcjbLZh54BMXY+Jev/kf9WcA96DOx+RvuoCfFu+i5/oDuDVWpB1+97UMmMDtYOig0xz0uMRX2tYxCvYGCaKIOt2ejCoIJmHU2k+206xnKTSuhHZ1YN7UycdOjEVa/dXDZeyV2pursT2yfzbtPRH+L4trRw2KttcN6kFaa22V1zZer63sMPB0/m8Oln/fn8z/tMZkuWoB1X3O1biT3hlNxswwasVRIW6XLXGbA9ap4KAmUXEcGNdAO3vwZr7kYEtw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTY1NzY0MjAzOTQsInByb2ZpbGVJZCI6IjgzNTRlZDBkMDljYjQ2ODJiZjYyNWRmM2YwZTJiNDEyIiwicHJvZmlsZU5hbWUiOiJ4VmFsZW4iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2QwNDk2ZmZmN2JkNDE2M2Y1OWZiNzI3MzRhNmNkMmQ5NDY1ZmQxOTI2NThjNTUzMzU4Yjk1YTNiNDJhMzk4NiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': '',
            'speech': "I am the Grim Reaper of the Speedforce",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-9",
                "/haste 0-5",
                "/back (In the speedforce)",
                "/tp <player> (In the speedforce)",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/run 0-1 (In the speedforce)",
                "Anything you attack, dies",
                "/fly",
                "/fly speed <number>"
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 5 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"  
            )
        )
