@plr = player()


@hero = associative_array(
            'name': '§8Bl§0a§8ck Sp§fi§8derm§0a§8n',
            'class': 'blackspiderman',
            'sig': 'nDRekBs5EBPpqV2AxX1LCW+hRQpnywDqyiS1Y4bloJn5OJEYTyMFolXdQdRRlMBfz/POuNCUP12J1ktrJliyaYv2Q5gvq7ySJ6MJng1SZu4PRDzgtsGI08MAmHFVPfQnCyi3QHNWGSpHM4PuBnFGHqu/ArKLYF8Vw0P8WKuWPGJTblbWMe4Pl1Gtvz28nAz+qKgCkfitsC4NKVA209UWsWe4N7sN60MzPBp7YqQPCM1akiAaN7zMkDmwe2L0mSR3ajESyS4VTX9Ujy1Shy0F7tb6NM9PAmrq3NFMCVcG2cGuh5O1nzd1py77R+Xn19xaItt8TJS0z/Xgll8ldKIQpszHTocrOq1VMWdkhR3zwTG9pdEFj962UTw5evjWwDgID8Ce7tEju2EqhLpsXQWWSyHUHr4A2km7gkfZDKZURObpuG1IQzh75gPBG+cTIBu7X6BEzNUnEatN1uKre3minlVY9QsEDPz9WSXFE9BAlTp3HQg+R/DY+etpz5rhwLXL9+jMUeUycqnvnnHPEFRU2wTwCNF3LQgrHenfUUa4AZ3GDHF4B7W3vsko16QUCjWoGJCtSPQSIKBWK2xDSPj5enD93EpWfglkL1EDzbppJ5SFQEJpiEd1h+n9aBIzrMGoemNS/PvjaKkyvJUg5q271eYI1nrYWd5hIuM2VdlS9Bo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjY1NjIyNzgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzczZWViMWI5N2E3ZTI0ZWY5ZjRiNGVmOTVmMjcxYTczZGZkY2Y0MjUzYWU1YzgyYjE4NTA4NTMxMzJhZjE1In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Oh fuck I'm black",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-5",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-4",
                "/web",
                "/websling"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:web 64",
                "/shot give ". @plr ." webshot"
            )
        )
