@plr = player()


@hero = associative_array(
            'name': '§0Bl§ba§7ck§8 §8La§7nt§0er§bn§8(§bD§0S§8R§bR§8)',
            'class': 'blacklanterndeathstormraymondrusch',
            'sig': 'a5C3KN5UTGw5jJ7mffQlObmIbSagaRC82WReoLZqef23Nudx8+zxAbCQpMwx3AXGkOtlwBfFTlCsU+AqrHB8KScGm6eguEqRLYDjX5GeiJwuxNYRmcDT6DwY3n+GSiqK47wvyx6Opp61PmbhIVT/1iHqGuxTwvW4Xn69O13CAZCpt1Fl6G91KaxjOKbekYmPPAQ+cgobmeDXVY5DzTqZNahkYo1tc4q/5LNPeRUg63wOERkB5bEGNMvyFEZR4BpKZccHYE+Otj9fWJ+XpSyOmCttpJgDB+XQrfgVDtxbk26f7bYIsCYoGT/BDLma0XRGuU8Drj9D5awDWN+kcKMv7+GoQ0fKtSXW+0NWKmsMOMpUEci93NN9EWuKkAMMM6dNba9s6rhGT7yCxzNdF8djqFR3f9Us8HoapufJEqdzKHrYHXK4pS+d4kcxb+05RqVtn1uHPyHRnoq4/Q7+Loy08O+bWXWUmxS0qcAtxth1foL3jlPDdqmNhFDSYezJ3/a/SyFW8g9Qx0doEhnlIcSCgJ7YfhS5Vvs5GDnsCXN3JM0dj2rf5gl6puR6N4sThQFb5BzqpSI0W2rBbQiTfcUP8kmdZfBFLNXrw+afzQfAaSAbcdIWjVLZRMXqE+Ygl6do9x0ipVvWx/4Er9CB9IG2vonGOMhH1bcyKfCbmI416uk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIwMDIxNTAxMzUsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2M2NmM2ZTI5YjZhZjQ4YjYxMmM3ZmM2OTg2OTM0MjhkMDI2ODE1YjE4YjM1ZTJiNmU2N2YxYjI4ODE4YWI1In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "We are Ronnie Raymond and Jason Rusch, together we're DEATHSTORM.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-5",
                "/flyspeed <number>",
                "/fly",
                "/transmute <blocktype>",
                "Protected by Nekron, mobs will fear you and wont attack you"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 16 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." blackenergybeam",
                "/give ". @plr ." 95:7 64",
                "/give ". @plr ." 263 1 20:2 16:155 name:&0B&8l&7a&fc&0k&8_&7L&fa&0nte&8r&7n's_&8Ri&fn&0g"
            )
)
