if(@plr == null){@plr = player()} 
 
 
 
 
 @hero = associative_array( 
             'name': '§0B§8l§4a§0c§8k§0h§8e§4a§8r§0t', 
             'class': 'blackheart', 
             'sig': 'EhcIYEkEnWj3cH7a1cDFs7o7EsjNCoeSPEjV3dDjphxkPv1xaJR85aYJViEaF1b1RSVPMPwGjWnVrueEBJeyjEt2adkX01+dkTm/A2rlx3kcaBJonC6MW+1nP/s+7veuB81uoYQ972w3CAMnJ8ctgvQ4GaMbKshByBjzDftSUbrW+C4jSeg3Jkj8m7F+Ef0QGP4S4VukZcqoulN5PLSUf54kkXGQo/ATjHlyCZc1lXB24dEZIdptTBg2o8dpO0jRPASDwOqifr0sf1u1niMFJBTFZ1YDpHf10bvGUxxgyRKF+5gccnCJ5Ph3uQJ9p97scMbnHG22F6cMScoSKi5ykHxXJpHZtKdJplTR9wXoNhN/GnsEOuYxas8EkcE7YKfXG6CMUBzLGONWM5QH94PgLVaPGhk34MkttN8umltu12XFQSIKPUrECqoz8mY77A/Tm4y4B7mK4pqedCEiK2sag193j7QJHNKC5xaAAPkWTa91dJaEghjSMc2iOXVbToVB6dkejqQy06XYscoOt0LxOywE8+4hzgdvmaqZIL17pfkwZq30GCf47y9RpPw37ZD78edFWar5o0N4OMbmIFemmpU+jphLFDOanu6GDL00ZRLCrtyDa1y+oll3MgmJkilZ8VJv/MrqxCweRk2oMNkpjmOB8PTICAJSekqGjsZNP7g=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE1MDk1NzIwMzc3MjUsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmQ4NWQ2ZTQ2NTdmYWMzYWE3MmFmZWI2MDg3OGFiZjU4YzhlMzkxNjU1ZDJhZGZlZDllZjIzOGIwYmFmMyJ9fX0=', 
             'trail': '', 
             'op': 'false', 
             'speech': "I am the son of Mephisto!", 
             'powers': array( 
                 "/buff",  
                 "/jump 0-3",
                 "/cast demonicblast",
                 "/cast darkpound",
                 "/cast soulshock"
             ), 
             'buffs': array( 
                 "/effect ". @plr ." 11 9999 2 true", 
                 "/effect ". @plr ." 21 9999 9 true", 
                 "/give ". @plr ." minecraft:iron_sword 1 20:1 16:5 name:&8Wr&7ist_&8Bl&7ades"                 
             ) 
) 
