@plr = player()



@hero = associative_array(
            'name': '§8Black §6Racer(BA)',
            'class': 'blackracerbarryallen',
            'sig': 'lNFUTVEiDREo/kZ20kGofjc0WylhmwwOvIMME9gREmjDgFz55745C/XGMGHAqAOK1bywRyQps6W+4GbuWDIOqEl/rC+VSsMWZYY69N4L0nmu02XwhInrUsgRQWvTF5EZeWh9g2XfWSOp1j3tWtXQ1DCn+0Bmu/eBBBl7lKdxHSjUSZ32dJdAX/w+X27lXVwVK4+OGmm1KDDxly/Tq+IEkHxKouaExcvXPCiyg0Z/QEf/+rS3C8Xh8NBpQ66YWtaEvO0nqtTprWKumskYIXxxnNXZCgNNGUoTk/hAM1GVQDlzasE+j5VaSLAyZtqHXFlB7Ch5AqhIJmugQhlxnrJLTyikNl1CA145AbsuD45Z8kdIyT4QYA+xLO3ZzWFrjq3F1ohCu5HJj8aGNb15St2w62WAHdxskXqdAIV41YEG/jVQX9zv6thOUbtFIs/mXqu9WdjuS8arsezAuAl+RPohZH0lTMuRwGuIx8wb40jTDGGm5P9qwiHWCdBHuOeLecdz/AtO9aO6P2hviFa45422TDPGUQWqa0sRu8A/DMiYNfMQW8aegr/pFo5GGXo/0buWKxpjVCwkIJZJJ/T/IjYESU+c2J4nLeef997G/k2HAtlfQy9SEMZ87FuPBD3ckRRZQFdlyoi22Xpi9EQbub08ZldHGmRR7xS95ebvX++8R7Q=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE2MzgyMTIwODgsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTUxYmI1YjI4ZTViMTc5MDY4NTIxY2M3Mzk1N2FhYmUzODUxNDVjN2VjODZkOWI4OTYyMWU4ZWYzIn19fQ==',
            'trail': '',
            'op': 'true',
            'speech': '',
            'speech': "We are Death and We will defeat the Anti-Monitor!",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-9",
                "/haste 0-5",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/whirlwind",
                "/run 0-1 (In the speedforce)",
                "/thru (phases through walls)",
                "/touchkill",
                "/vibrate",
                "/stopvibrating",
                "/speak <playername>",
                "/disguiseviewself",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/touchkill",
                "/back",
                "/confuse <player>",
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 254 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"  
            )
        )
