@plr = player()


@hero = associative_array(
            'name': '§8Bl§ba§8ck L§fi§8ghtn§ei§8ng',
            'class': 'blacklightning',
            'sig': 'i/3PLYB3Y5mxX3z2hjvgFjnQQsMEMxo+yt7pJCi5PLFrNtgBDK9w30KmOtvMRAsakpJBf3ErQxqg9Q82HZqeU1jwXbLMUp6z85GNaNf0N4PG+47JcCQ3Q0B2+YyWLJK/QK09TTEmpmgo4A9PkHmek8BEEWNw0ty4qKDukcHed2o07Xv/94FFoW1iAoJ2LwhLetTDO/6/244qdMrfhooIOGoCCDADERzhK2b2eZfnPEWQlKOitmn5OnVAgVhgFFs0uu7yDNDIcuz480mVxiybZRs2ezIuw9QOrbxncNqWdMsMatiWbKOcJqqswiO1IxUZhjsnn8KljuZm7+4+c5JCcJKUDgB2No+upINld7IOicOLSGl3/IboFgk9BYFHZdp0q19M1hwfuQlKrgGkZAzgYgun/RCkCFg7ZFoQDVdegIj3ZZ0KXkRCQsglX/39QY24R9PeVitCZP5fiDT197Z+Cw2i7da10U54800Ye305tjeEiye1F7j9B4jM0rp6d2TDFJQFzCyjeGk3SpbeCWJBI6aFJzmAf91LDNjFq+DG0/HTfHjYOCqf9W+ENNRcSQnaxMuvtiKFFWCaAWtHRLymqBHGrnjuHQdogIffRQTV9SaV5vJMv9Znqf16nDulm2kbMrmwT05Z9mE5tQoGHE011UsxhSCxS3suWu9kIpeeuH4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE0NzE3Mjk1MzcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJSb2JvQ29kZSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Q3YTU5ZDdkZWYwMTkxNGYzYWUyMmExNDNhZGQ5NDI3NWE4YmU1MWQ2YzJmOTc1NWFhY2JjMTE1Yzk0ZCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am Black Lightning!",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-6",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." whitelightning"                
            )
        )
