@plr = player()



@hero = associative_array(
            'name': '§5B§0lac§5k §5W§0ido§5w',
            'class': 'blackwidow',
            'sig': 'drM80Ih3JK2UVWtWf5FCGlwGbZRt8mvMLtEa6s5m458exJX1E0C/LNXNKoMIa2ni8+y+w3phRoME1U6MTO4BMl5PWIZ/YS0RD2hce0J5jB54B2ul2h7aVLQKOUGwO3dRQLie1GDtZ3VQI9878wBzxfjhe4DLLUj5OiF0OztGzQEnHqEUVJv40exR/pVrXx6hOMJn6pEBD3pd9LrOpSn66BetL6zTrjZH81K8LzIxTHpX5rNFw04Mb+SIslH64XN9d5MyjNdJDnasESsP1JGOEVcyV9uCg9DRLqY/rO5YTKtnRZ+9J0hlu/8Q/Ea9H0yvmzWgcoSy7IdorlkgZoCW+QCC8+D0YrYpaGd2ZvNqAzqVVM2HE6MMGckm18id2PFN1xh1hox060zJTrD2VSHoQ7FhHH32RNaOlpgbO2fRdHYS3vetyy4YJnqkKGDoKoZXPjZLm1rnb30Kw85kuUekpUI5mdL+KjWzkNnTSUgeCmnRjTDyQc+Gbolbv3lhSnTmNGuZ2tRP6caiM85jMwYqDxQYQ82g0LRH98KxB3G3OXATJv/cVOJyokaNd4XINC5TrijHL6idhg8xhklK+cIXGlzeorbQpyyYuS0NGGh6EfX1zSztD3TVDb13otXuvkfdaAGpLgYdW26AW58CIhyckNaTiZYOntB+ISd79ClO19g=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAwMzExMDM0ODYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJHb2RfRG9lc250X0V4aXN0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzIyZmU0YWM5MmVjMTgzYmNiZTNhMzk4NjI3ZGQ5MjA0ZTMzMGYxMWFiNjlhMjI0YjdhOTA5NTE4NDc3In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I've got red in my ledger, I'd like to wipe it out.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." pistol"                
            )
        )
