@plr = player()



@hero = associative_array(
            'name': '§5B§0lac§5k §5W§0ido§5w',
            'class': 'blackwidow',
            'sig': 'CXpxExmu7xw43m4/sp+8cT5VMl7X9vhta/Vyx0idL070pD26fsmXraSX6P08QcBtgtr5gG8FxveSxRTBuAnNQ0agGuyyUGmJBRtwzprdxDK07OVNsLyHJ+LpKTogAjxLhfIEywqgYHBE5VH+LLq2dZQZSwlRqFZfJZoXaa8WV2lCVDXGABVhpQju/5Fv4/cXdPdFU4yKRLxLaueOUt07g0PFtw0+OtwSfgm35ixvdIG75dhq9/tN0gR1bT/JYG5+M/uhzYEwSoCrSTMKgXr+UTjBukOW/w+lr0TXkhlGfDfgGjHhuvKlIPKv/BFU5zKoYtrmhAoLCwkqd7GBGZWDEv6w1gMBTpgZzryv2zbqISybz6YNY77l6DNK4/gsTGBhV1Y8dgC1JcRo/TSWSOBsZ6c0l5YJ1bgm8ebIhB3GfNhUurqjkRCHEU1Cwm45Q5DiFLBtDBKeZ/mw5nOEykYVHtGViyh5IYkj/ERBlGo4b+yVpygcOJzAt6EDm70dWBjM1K8vEpHb3lk+fL8rqpyM7T5rhGltl1Awej7wXIs7TF8/viJo5hGEADzv8DguriFGpTPiN8seqjk8crS2aMs9iy7W2/eINoBQ5Owv9ZPp9OhYjGcY6lAdlSaLFZQkP7RKJAqM57TVzoBGHNwElyskCCa3UawsVyHZuQcUKjU83wg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjAyMDA5MzQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iMzY3ZDM1ZmMzODdlNzE1MzFiM2M0NTY3M2M4MDQ5ZTZhZTU3Njc4ZWU3YjY0NTNkYmIyZWE1MzQ4MjExYzcifX19',
            'trail': '',
            'op': 'false',
            'speech': "I've got red in my ledger, I'd like to wipe it out.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." pistol"                
            )
        )