@plr = player()


@hero = associative_array(
            'name': '§0B§8l§7a§fc§0k §7L§fa§0nte§8r§7n§8-§fM§7M',
            'class': 'blacklanternmartianmanhunter',
            'sig': 'acew6DgUKta4gRdhltA5HLm0czKZjBijdXOeO8YZAcCPtbeuvPCWjp0KNKR/R1JbExxp6I8SjBGv5st0oQFsw4F1rBKjIvfsFIlwgF4DpQHTRgQrYpNnTGxeqWOavqgWu+m0IGE1mN0whQY1ebktnGN6mztQownXCjTXN9L1ZquvBeX5X1Pq2ICh7wzjkmjO4DLJf0DrNmfEdDkEtGtjF1njtjkQZO7nYn6b/8GCBTArFH+1sDEurlRZri+AftiRQsQDfIlI/Avt74nUseIXnkWlQ8x1JdJKvgoAmVo+Z6MV+YZ8fEmc6JbA1Ft0/qK0UC3Lx1N4HFUwpgcZucKgIV2Ke+H88XBEJo14VtNFycBICCB/yy+2I9h8+gHNA8/kodtPcdQ4x3MPMT5IAko9XLmOMZOqKnSDqFwQiQ0Q38gp55WB8jCr5lfZGFR811y7catWSVwUiTsZ/KN+vO0h59/YxPk0FnI88wDDqBgWNU4LcjrqdNEXUqTbwc0lGsrO0n2HMlSG6HwVG6T/8I5pbgdXsQaE3LUo/aQdieLkobDRl9h8sJNC6w2/e/hGBedIgv6fpgJ2b0M9zBGiGZyo25Ax5bf6z7BICbHA5UH72+bxJXeHECKVn0yMGW1hKpoeidenrpgKmTnWl2Ki2OsoRwpNf0JRiDYTSuQNFCDDMPE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIxNjg4MDg1MzMsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2U5YWUzMzQ3ODQzM2MzZWY0NmZhNjViMTA5MjlhODBjNWZkZGZiZDU5Mzg2MGIzMjFhZDQ4YTY3NzliNzU4NyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "The DEATH is worth it. The pain. The suffering. The future is DEATH.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-8",
                "/haste 0-7",
                "/flyspeed <number>",
                "/fly",
                "/thru (intangible)",
                "/disguise",
                "/speak <player> <message>",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/invis",
                "/vis",
                "/disguiseviewself",
                "/confuse <player>",
                "/undisguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." blackenergybeam",
                "/give ". @plr ." 95:7 64",
                "/give ". @plr ." 263 1 20:2 16:155 name:&0B&8l&7a&fc&0k&8_&7L&fa&0nte&8r&7n's_&8Ri&fn&0g"
                
            )
        )
