@plr = player()


@hero = associative_array(
            'name': '§0B§8l§7a§fc§0k §7L§fa§0nte§8r§7n§8(§0S§8M§8)',
            'class': 'blacklanternsuperman',
            'sig': 'CNw1fk3jt0bCp8L/nV+zuQ6wlDWYg57BiqOYmBGrBj08H24Uxt/DvZqVbQtYGTN/yV/9H/pgnN0SoJMHEsTRIo2MD6U1j0erlXVV9v4tZN6OS3EvvTVrE6kfxo3Dv+qfAv+RXEYp9+8qLv90l5g95hSu5BcpG/eTrORzqL0sc8RWu4PM0SC+6kCiFTbrkt+Yp3daa4kWrGif3Fjnf3fsZEEjwquM94ZdUdRn5ymHNc4FD+2zCHoUpHEEjc1XB64WwRClowz8tj7XVdRwykp8z5QqQZ5fsUvWQi5VQaUQA3DC9fy5Tgork5rUJEeYqTsPnSlWdEDfn/gU8rhzQRZ6ojSItrOCXBpYkzHs/8uFGcq0K7tw/4YpZGUtyv+OXEbWvQDygNoPOyw+ugm7jjjalrQHHvUu3u5pO1d8imwnPRXGSi6DZpDHIsv8+rea2bwgSE72DMHboqrEixkOAINQMYjdQ2ksyM0yuX96eT932Vof+zzJtcrfn6RMnDvEsMIqgdu/rag4+XeHpbJIbt1BLdo4mAB8Qf1I2jBYR+VHqI7JuYKxPfLXrGOMN3ogdLL0OaluL1gmIm8Zfyki14TpT/KrN4rz5YQYIZvZ2aGZa9ykakkju0XXN6F0Au5LfX27jOZ0c6iPMf7GA7Py30NCtX2KILKGRMeJ1zQcyi5E1Sw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIyNzAxNDQzMDcsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzViOTJlY2U5MmJiZGI5MjViMzNhN2Y1YjJhZGY1YmZjM2E4ZDNmODI3NjFkMmU1NGVkZTg5ZWIwMWFjZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Time to kill again!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "Protected by Nekron, mobs will fear you and wont attack you"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." 95:7 64",
                "/give ". @plr ." 263 1 20:2 16:155 name:&0B&8l&7a&fc&0k&8_&7L&fa&0nte&8r&7n's_&8Ri&fn&0g",
                "/shot give ". @plr ." blackenergybeam",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
