@plr = player()


@hero = associative_array(
            'name': '§0Black Canary',
            'class': 'blackcanary',
            'sig': 'vLX1PxYRVV+PmTjZNGvVl4tKO0MPuCO+FU/+V/4yd7GJewl43YaRskxCixh5oOLkgRZ0fMZ8uuFJUdfWtUJM6IHcFhA9aAigPjEkBiO+lcMSovVIK7L33k6Tab9af12YPY53iboKEmrMdd3Jz8h8GAedmqP+2G1kgr+0C11IbehtYlqztCPQ8UST2elEnmQWE/GxiPsxfeF0vk5XthUpsrKBHF36lKjeq3Pyj6Nh2I8OWK28pYBbo4j6x/pf4gOZ/c2Dkm2/RQ2xPahD7V3fPWcaZjKI0jU4CRs1anz7Ag25LsVN+JCwnlaTmlMU0qqmfTUE+zIQdcaeGHEiMP+EPOHZyr1WBhUuQ0g/J96UtDhrzFiRHf1OcdFsMGUOnriQrG0aL9MxS/BVYL79TFRPtCrIWLutvG74rEiQm9YW2U7cdx5G2e6Tl5dzoaqWz+3n0SsDnLNo+sDlLxkRyRAFB86XecccuvDKZY8tSIirzYC3KCNT0toMjmZJg4In3MPpIGL3xJyk3rIVw2GKPEDRMvvIbruCGKHzm87mTvEZ573x0E58FnA/EYebmFI3pIx5nZmb+Gxymg3L/9w3Q8B8ejnSB0nTWTX+F511Tes/uNZD359zOcT6pBiugjBArtSvp++ELInKKBFdNT30PihU2xdIHU4pwhutDo7aMWEy3f0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjE2NjQ5NDIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hYWExNjY4M2NjZGRiNTZhM2FmZDRjMTMxOWQ2NzY3MTc5ZTg3NGU1Zjk0YjE5ZDZmNmVkNzYyMzc3ZCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Dark as the night, my vengence is true",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-2",
                "/push"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:stick 1 19:3 16:3 name:&0Ca&0na&0ry_&0Ba&0to&0n"
            )
        )
