@plr = player()



@hero = associative_array(
            'name': '§0B§8l§7a§fc§0k§8-§7L§fa§0nte§8r§7n§8(§fE§8T§8)',
            'class': 'blacklanterneobardthawne',
            'sig': 'p98fKB78BmqWjnok1gNqx+udMSqZiX+b9hXhJ8ZyMZDVh0BpzgzX5UnYBE6VOd2Eemj/IFoI7vqluyo7zYWIGM6LPYSLLPslUFkU80kEv8Pl4QeIm4+pyblF1XZdDLx7XqQs0bsmwqwBGoksCPMJWmK0BLykHyIbJhlOX4jKW9Rpm6wM+SaG34TBUI09PkeAdVrLIXbbqXOwt1ZRPFP/FUNjbj3FDiQsRJSbKlSIksylKHcNJmqYzU5Ygl8A9TpzdcBQpNBSTZmPNEeTAdyv0C9gpvD62li4MV1bDV0eIdUZy9Yb2g236zham1yq6QX8qbAvpZO4qiLXS5gljAilwzYhdIbmGiIRxUGZe46b9YfhrAV6XHmWrPnFs1kiD2lYfAgvt1dHnpz03f1gOiWSxotRC067IOoKA9Tb6lTlxAahgnqpMeNRxhqrOALV4btttGP8IPdSdtFdma3FdCiptbH9frVeROyha5p2poi8ZRe84w0ojsVN7TgNlAo2UUVUpXZY/K+uhGw0Zauyl8d+72ZHS7lXRabTc5MvfmRageoEMPRytS7bhAaA1mQ4GGRlWyQe8DLPf9zjc/B/P640c8sMW2JkxETbcIUSaQafpU5AQo2R+lBDBfQVRbwSit63f8iEM59rNsx62vOvvSi6DuCYRtKLBN3JiTsubKi8xXo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE4NjE2OTU5ODksInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzJkMWJmZTkzYWFkY2U0NjFkNWQ4OGY5ZjI5YzRhZWU2MGY4MjM2MjcwZWQ1ZDNiMjJkMjI1NDg0NmQ2NzEifX19',
            'trail': '',
            'op': 'false',
            'speech': "We could say im the reverse... Yeah. Im the reverse of you Flash, now im even fucking dead and you're alive.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/haste 0-4",
                "/thru (phases through walls)",
                "/flyspeed <number>",
                "/fly",
                "You are protected by Nekron so mobs will fear you and wont attack you"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." blackenergybeam",
                "/give ". @plr ." 95:7 64",
                "/give ". @plr ." 263 1 20:2 16:155 name:&0B&8l&7a&fc&0k&8_&7L&fa&0nte&8r&7n's_&8Ri&fn&0g"
            )
        )
