@plr = player()


@hero = associative_array(
            'name': '§8Bl§ea§8ck §8Ad§ea§8m',
            'class': 'blackadam',
            'sig': 'Ichd3mbmOE1rOu9WH7c3HW7BiMQaPDIotJ3c6qyYsH5VaWUOnzIVXAX6kg1RhfklLw8ydpy5c2f/yDZyWw9EF5ByNvzCKxfjAX9HkmOWONb80T9m9Zq4LZ6KN1peS8pZsJVEI87Y971p4lXhe/4oEdTbu8z+BMZMlPbykW+dAW8K1em0xjfFRP5PXdkUk8Bv+KoqX61HZ4I0kaSJioFE6VQ2jFZjUZnOEHRIsDIDYQ/4ngtLwH0mcbPdIR/LWjfqK8cVPl46OFn4X6TpV1dYvlEkpxPJDjSRQGThoGvL6HTGujnhfoPRWVjNTEUIPLaN9mkxbr6hm+gKcbZIiyNAqCVe2B4nGMJpZ4Fl1g0cpdqGI7GdOQSstk4xodktjMKH2gGlMX9f0n1R7dzfiOqVivug1xGkEhgfkfHoVdlim12Dr/ObMH69/XL+/20cwu7wKdPl2Ym7uE19WObDnxmgL9b4hohoo2GqELcyjZNianPBEo96FvEmHkK0t4MnvapGPU/pqVq979OvRr/W8CpeGGMIWuHzPDcXibEafxagqfHAM9z6G/643TC3Iv0PCkCqtVwbx1NfawisjjxOc1vPSfGtmOn0NIWA2wzVBzDetZcTFmIuC9j7gXtDfDZ8j5+BkDIuMSYjdatZdc8Y749JXoJrc3DKM2294gv3ya9TzF0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjkwMzg1ODAyMjQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzViMTUwMzA1MzA5NTUzODdmZGFmYmQ5M2JiOTE3MjNhMDljODFiZTI4YzM5ZDk0NzExZTVjZGNiZmUxNyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Am I black?! SHIT!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." whitelightning"                
            )
        )
