if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§0Bl§8a§7ck §fB§0ee§7tl§8e',
            'class': 'blackbeetle',
            'sig': 'LSQyP29lK5lZMbi8+0PCPj5+FVbdh1SQLX9IOhtONKG7VTB2RMcjJqJ3PqU2rvOyTPiUJH7EqgXRkqbOVIjnUoG220WZIbGhSCJKvKcJm0N6m6lG0MV43AnxLCpav5aI6Yqqfyyc4XFh2F3Nj3YZYTpFusmm0bthJnHVu2gBp/UVNl1MhMNyo6PxwZ9tBAclpxTLwx1ECSN3wC83B0zE07Q9DZIk/0L/ahqp4otAia/iP7K4DCEoCv0jYwZT/nPST2dILuq6bqXaW+nGSDXC9Wkm0csmUtgQuBO06azlIAJEaYJUoBq5/bM31QC+3B2Cix+8h1mtwHCnbDO3YuKT53hg92n5gKpvNBUYldFIYx9jNYZwuR8M8OQTyW9aUuGDIO0XoDxBXXuYrt/w+u9aVEwRPfkZo8UAxVSKVBNKRU1ACmkr6+8PQzpujKyxDvlSXQdValIDPNjpwAqVtmRwkAfcSISIhfvJ4CoLl/p8NV0v/R0NkQiSBdFtL267PuhmnfU4xsZaGlze4f4VDD+26IZU8v9mq5yxyRZ1xiExvZSx+ppHYohG1q5MYzanELhk7P+4SQ0rHdI3eROKanumJRNO00FiGVpy7ywWHVTVOn0sj/2lHhmJbK7YfgPH8cghPvY2bcMm9sK/ml1TBbN6iczw+OzfTiTXLe0rbx2oIwI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTE0ODAwMDA1MDUsInByb2ZpbGVJZCI6ImU2ZGU4Y2YwYWY0NTQ0ZTQ4ODJmZDk4NDQ2ZjRiMzFiIiwicHJvZmlsZU5hbWUiOiJScW5kb21QcXJzb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzc1YmY2Y2ZmMzRhNzMyNzkyZjY2NzY4YTliNjZlZWExNTBkNTY3OWNhYWViYzU1MzY0ZTk3YjdjMjhjZjZiM2MifX19',
            'trail': '',
            'op': 'false',
            'speech': "I'm going to exterminate all of the flesh on this planet!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-5",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." blackenergybeam",
                "/give ". @plr ." minecraft:elytra",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&0Bl&8a&7ck_&fB&0ee&7tl&8e's_&fBl&0a&7d&8e"
            )
        )
