@plr = player()


@hero = associative_array(
            'name': '§8Bl§ba§8ck L§fi§8ghtn§ei§8ng',
            'class': 'blacklightning',
            'sig': 'Ee+hzbAHTpAUMqOBkD1Yu9KW2QMNK8GWEKpwUYCScdfDs/wSyYjn0WSRcBVycjhqpDbdv0injDFtv0vu5MPDaHL6kokLn9i1r6oZ2CClgsCbBU9DADHTO0w3905rzCm/8aMHcV0NoGJVQLFtVaOJy4zabhxy8f8idpskccqq4ibqM3A1zVR+pe6deEVCwL1qNa7/1SequyX7gSjEaQjbRqz2yWNXN8sDQmoNc3LZ1LhFYoXlPSSjSmwkvO8jre73Efd1naqo0xEWm496EjRadC7pFqxrLr8iCHqlT83kQyUXBANmUjnPWdi8RujgrjmL2229GRRRUkarz78cBCILQ486Nj+u2EEPQchCPamxmaeRRh+9lYzlwx/XbvByaviUlMkKP3JF26FqDneaYvEBW37nM0IKlbA9B4Zvyl9HfSEVSGkmqLkJXo9M/TOURJbvOahkWo3AkX+RtflrLR/YJLkj8YDfLF6mSkYOYGx1yGjoa+mLrHzRSFNfyHmf4MtolMdFn/I/2TebKR+9WNxF3cP59yronq1ouDx9WOMTXMSpmv5z5EzIIyTb/e8ergYZPGeCCkz78SkcfDSzlz5svqEkYEubGFP4InG30czTAM6d4DyPbcvlWnr+Q47ZBTycOnQmCe4LkTksnGG9e2urt6JQXOMrYMRPWbp7tw9C7Q8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzMxMTI4NjY2MDUsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzczZDNjOGIyZDFmMzMzNTQzNDNhOGMzYjEzODU2M2Q3M2M2MWRkZDViN2RiNzExMzcxMzQ4NTU4NTVhMmRjMyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am Black Lightning!",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-6",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." whitelightning"                
            )
        )
