@plr = player()




@hero = associative_array(
            'name': '§bBl§5a§bst',
            'class': 'blast',
            'sig': 'h4WlQkmo+zG2TsAMDvOLhZEusyf+Ku2bvUnMSipvgSomhEUZULauZcyXBjDDfCD7zN0EjnlRr+TQ5zE+zc1UnQ5f8g0nGseYRCITW/70DQ8sUKvHy6+5z/wMiSZQVmAK2f5pyuHB+5ETvxL7Vkm/WVkvcmXtgJMJmLt8g3CQsZ/lfs4DZpP+3DeiEBmBYEYgRVOLnM6XR7lisNfggtctY0eVZbZM5hhYmpsT0h8uwxn1WcxKap8ohomONKdO7f9IVn2nA2mCDNuYAbeLY6DRO4bXM+AN7aFb1zPiOrFVPpQhPN3K4JfjkFYk3rO9ILHgWXh4d620VPn+md/DY9vfVvaBwhARW2Ypyn24VVLwbWj5XE9fegjCLPBKPd1ObjyOnEQk0GgPIhvs0HEIMvt+XT4rbrYWAJNDAxJEPBurgcqW2Njc+VkC5t61LsRPcMIIUV7ll/h1nB8XCosyidEc8q/GM1kxfSn1vc3IiC7zZ8m8cj9gcazPnjHXM1cmv+jnaCsSlhzP3/Hk4i7kDNGB8D8Q1VSSplJ64FcRE2ryQjPmo7hEQkYtxeqvB+oWHy3dw0IvmLuO2kGfnF/OJz5EUqkYn5gFVkKwfEp6ZEPsQ6QFHg/r7WJsWI7d77YUVK0LtCo8jVL8v5Bh5Ug2h75uhk/tcmS03jgTxm6a2cwY8LE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzUxMTY5NDkwOTgsInByb2ZpbGVJZCI6IjFhZDQ4ODQ1NTllZjQ1Y2Q4MDlmNzk2ZmQzZDNkOWJlIiwicHJvZmlsZU5hbWUiOiJKb2huYXRoYW5YUCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmEyM2UzN2Q5NDE2NDc4OWVmNGEzNmQyYWQwNmFlMGIxODI4NzIwOWZlNjkyMjk0ZWE5ZTZjNTZlMTE3YTg2In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I never back down from a fight, after all I am rank 1 of the highest hero class!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-9"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
