@plr = player()



@hero = associative_array(
            'name': '§5B§0l§5i§0n§5k',
            'class': 'blink',
            'sig': 'UmHJSDsdVW5IgL9B9BnVK2tjW+jvXmRZ0qTyTgmA3lycy11Jg59zdSzHdg6niHWOjWkTVDD2MjEWJqL4aR7l4SRSIkPitEhCks2vn0sdDWb0Vu3J6ZylWhnfgSuJ4mIiVP1FUF0V18/a9+cfCDyYxBXFNvwIpMUzMmK6mraS+HIKr75mz+MJhuzPazwK49pz8VAFpXP1V+mQN/cFRrTQEtpskww4Z70R13viKpYv7dnEzOhLzOj34eZ3qvm37LTxeTJDfOGmL5tf0ka8j9DL0u0R8L4j/mLR85aPaglZ1W5h2HbDT0Fvg2AZwbRRS+/3nk9BeaHqMaIZPM8khrgB4rVZZBa+gEBn15HO+9y5H9bKfPsDwjNsgXLIWAcS0gVKLwd0cwGwRsZngBC8X258MX8BIhfoxzWpJv9ukOOX/BbMzIaRrGCv7LRcbsy/q0/sWVc0TLV0YPkypLJemxr3UsqZJgi8lEGP874nazyCuEQGfTbMBU5MWp3URWA3B2N5Fl2Ngx/ePudq2MkQoG/6wLIamJAobBOcmXAkMP7wLOuAKpdriUJR6bxTfpGxXprxG8uwJUtOPFBKhwYo2suebE7FsUQt2qYAWL2nxUrx29zOJSbUs3veqwZ4Fsvt/kL8UlWRchCMB3rpeCStFYK1CgIJj6G/FYQQKS0R8RJ13nM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDcwNzk0OTg5OTUsInByb2ZpbGVJZCI6ImE4ZTE1OWVhZGVlYjRmNzNhMjQ2NTkxYjU4OWFkY2Y0IiwicHJvZmlsZU5hbWUiOiJNckZsYW1lWVQiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80OTE5OTM5MWNhZTkwY2JmN2JhYjg5NTU5MmNhZmYxZWI2NDE3NmI0MDUwYzZkMDEyMzg5NWE5M2QxYmY0In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Blink and you'll miss me!",
            'powers': array(
                "/tppos <x> <y> <z>",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
            )
        )
