@plr = player()


@hero = associative_array(
            'name': '§1B§3l§bu§1e §3B§be§1e§3t§bl§1e',
            'class': 'bluebeetle',
            'sig': 'ai4tl4tKGarQ7Pvga3xtblXotJINeqlyI1QZELyRrNiM7XU1xVAL8haZ2q1m0nhVUf9vyGe+BV3i+rWVlELkRt6MzaYceQ7L2i8qdpOCXP0eOO3iK1cqLcs2fbryddXlKKV6srO9MoUxROtz+Ty2D67pkpebkJHLCJgGdfrTnOitu9Zv2M/weBu3Eeci9ZkhQLeZ69TSOgImHyO3HyMNxTpXpWg1tXJ/TcEdKuFFG1CvvT5K4Dpgir6xfcOL9RcF+frrm+FkbPPQnw2EM+oySX5f45B6yaFcYhWiRKCDczbUDb26rKHpN9eVB7DcEg7V9W58GA6zB0oOcwN/Oa6canF0gWAdX7n71hExeEJkkEs/p14mugf7XoJgPbVFjimHEqSqInIJFqccjBANQYXQVuaGFBimHGhlTWj+sOMkYVvQxsOvq3xj7PNmMvANAeNCnGmo78NuZGhYftpNL6c1HW8nHoAOy6tQjIZAj6zYLfoVNrr1o4/bDIAzDBTgQqsF1Ph3KESQxvSQcGxTMP0xYFWIRtr9PQIuzvc8kkWS3KwaaxtHRAIVC2YPN/TD8gz+ODBRO7uMr1yNTInKKMWYhFgEJpUixhoIziRQM+10GL3qUAE0iE5IHzesqoubL9y2R72vfJrqAExnUi16BjZPtJ7AEVI2Sulju8DfhCltd8Y=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODM3NjcyNDY5MDEsInByb2ZpbGVJZCI6IjJlN2QzZjk2YmNkNzRhYzRiNmE3ZmMyM2Y5NWQ0OWEwIiwicHJvZmlsZU5hbWUiOiJHb2xkZW5Gb3hNaW5lciIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2ZhNjc4OTg4NjM1YTc5NTkxNzhiMzU1MjUxOTU5NzE0OTYxODM2NTVjZjA0MjY3YjNiYTZjY2E5ZmM0ZWJlOSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "With my blue scarab i'll become the next Blue Beetle.",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-5,
                "/haste 0-5",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/effect ". @plr ." 11 9999 2 true,
                "/effect ". @plr ." 10 9999 2 true,
                "/effect ". @plr ." 12 9999 1 true,
                "/give ". @plr ." minecraft:diamond_sword 1 20:2 16:100 name:§3Blue_Beetles_§9Sword"
"            )
        )
