@plr = player()


@hero = associative_array(
            'name': '§fB§1l§9u§fe§8-§fL§1a§9nte§1r§fn§8(§9S§fW§8)',
            'class': 'bluelanternsaintwalker',
            'sig': 'Btb9SyV0gVkYn/3NVoAJ0nMmWnB+27NbkchwDiw35LKY9GrxQxjr7cxkiKlcfPXdUYsti/Z3SP+w2Vs/YRxl437IrG7O8tfINbnT2h55mZWe2urjk/bkSNgdVAuRDqYwaVtXqEzJ9IJ0eaEMimbKOJDp9SpZ4fZc6IJU4Agd+jo3EN8Q/0muhXt0uQLO1di7sWrk2HVR7osn9p/5+SnrAfDN1x+v8Vu2YUdOXJvnlmKploYt2ct2slf7rB9D1Vxdtcoex42JOkxlTOrCyxQGTB/pN8ysSFnwZ6LykAbEzfPg0JRjyovnz6j9UeEM0uabJdb6YygEWQ06nzEN3Faag02A3P9x3GFC3Fa61QKc1u5XMVxfFkBmVug62PZyraf8PjslycQsFTxuImB07XA8K7oH5LKDMies1xtipZCC9bsve+G8td2qLTb2p7hKJE0YMxGA8Dx+4Xv/bpFqazRQIT8e+si4IHSr3KTZR1UJV/gfJZCSeBVtojEZshQI4PqmL0Y1EWZHIJuIu8CWZh5IOiCRJTrFKxhpqVh44wMaEd2rh9/jTG9QWGgi8jsmpUWjNVI+wpXNykgsZ/xwHt3j/vvz8+nG0RTDlaef9f55cEHc8y8WMZztA0zc9WFd/0xxUipZyu/CPOT1QDXpHEfZ7e+VAyiBBlGm5mFJjA6FL4U=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg5MjIyNjYzMTUsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJXaXR0bGVUaW1teSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTViZmRiMzRjYmUwOGMyODliYWY1NDgyYWZiN2JmYzY0MGRiZmViNDQ3ZmJkOGIzNThhYWI4MjUyZDllOGE0MyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I bring Hope to this universe....",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-3",
                "/haste 0-4",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." blueenergybeam",
                "/give ". @plr ." 95:11 64",
                "/give ". @plr ." minecraft:dye:4 1 20:2 16:155 name:&fS&bai&9n&1t_&bWa&fl&9ke&1r's_Ring"                  
            )
        )
