@plr = player()



@hero = associative_array(
            'name': '§fB§1l§9u§fe§8-§fL§1a§9nte§1r§fn§8(§fB§bA§8)',
            'class': 'bluelanternbarryallen',
            'sig': 'ixSeaeGGpAOUGyV7QyoC+ZhH+mUvRXg2ZgcZ7i3xRnj4oDp1UvJth8GQf0vAHAt6T8p2IOxvXBSTPJBA983yiqnHERV916uBYpybZ0zjZQwcmxwPogSI+v2TjwL4p3cYMdZHCorvp/vWo/7VbE3IzrtUtLpeweuEZbF4Bolz3dE43AVYMn9FPlvPcRDrcOIU2tPVT8rbg2LJQLEOceLLsMnVz4vVmi+CiCZ5+85VhzpHp357WSfWD85YBY9j/ixkSQY1SdktSEQTk2G2xnMTfHI0ueF8ITWpekzITg1oT9avA4pVh1ZYCrTbI4AtmwLTxsNR+IWRe6rjgE/Pz6yYZUyTkLYRbW3qLqKZM5VIO59T2GBrw3sWCWMZBXrSH/yoIloe06SNk3vETe2EyD3wF2RIwBpyyi03vOBbNBgeqoQnQZFtC63THZZfytx9sx+eb4YP48TU9lBFy5SldXOi5epm+kFJ9jpkrivazdumfy3H+SEZMHpQcZVKNHk/+BhoEPkEXoCK6rdSSJSZhmBljUxAhuowCx+480N/lNzjdh/5h1ID6/xglFuH2EAI2GZUCVjkHLJc98nHcNjb3iQxH3LbxHwBmBSJ2x8CvTD9YDqCoFQn0PvC/+bsBdB4mpjDEQQU848fgx41XGA/F6H+ld2pvlkJlVO4dNslzu492Gk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODA4OTk4MTIyOTksInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzhmZmYxNDExNmFlMDZlZTdmNjZlNTc2MjJhYmUyM2E2Y2ZlM2M2Yzc4YTU1YjI5YjZjYjYzOTE4NmFhZDcifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am Barry Allen! And i will bring hope to our world!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/haste 0-4",
                "/thru (phases through walls)",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." blueenergybeam",
                "/give ". @plr ." 95:11 64",
                "/give ". @plr ." minecraft:dye:4 1 20:2 16:155 name:&fB&bl&9u&1e_&bLa&fnt&9er&1n's_Ring"
            )
        )
