@plr = player()



@hero = associative_array(
            'name': '§1B§9l§7u§8e §1R§9a§7n§8g§1e§9r',
            'class': 'blueranger',
            'sig': 'ASw5VNYcx6vIaWmcm5XafAMbXIpEtF+z3JhaTeSZYGRLo4RVc0AcLjdvC8GhgpKYB/ZxYRNFdCyIKO98IHJ6BH+PliWOLJ6qKG81jjuJzIQxjJKwgzuZPb1RNHOsrn4g/jbQN+fz478uDSVPJ1YdXFZYpRIbobu4j57ewL146HPIBBhUO2Oq4NckvLavRahIzIWxR13LDQLBB3buURLVUWTz90dBmxS19O2WzN+IXG5/PObQ0Sr7HFIAfMscYPYS02rA2yIwJmEXUOrXHZLvmkuCC8KTR1akPMoaKB2OQSbAvAwFCw/ct/wJPGSrZcyvhqzMPhKf/LDpFjBx/Y1tQQUZrT0rDAg4Gr/oCNUUdU0hXh4ybeSfN0ggDA8mCEkzU5CQCwZucsJb7cnQktVJRtIoZ/GHF86CJD+kp9Z31sxR3/T093JgEqBxPqF2RTEdEN0AO7i83m5+rai2RPV/3Mqenh01OXmD99bPyzE2fJPA34tBHuHRJeu5kIXTM7v1QCpqFZp153nVOXVOyu1ycfv9/FaUWuTQxyQ1J4njDlgkwmFUAAQQHQx8iSOPjsLGWZdjNkLEvWKV7GhLrtcPbgpT/+v+XNVSDujs0POh63GAlHmtWR/OroGZTtA62RI2UfMN+C2iGlyxPGuhzWY6gahT5JirK3C6HGzjt2KTDTc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTA2NzE0NzMzOTUsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJVbHRyYU93bERDIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lMGVjODA3YWY4NGQ0ODU3OWFmMmNjYTU1MzJkZDFmZWNiNjgxMDczZTEzNTZkNTNmZmE3MWFlYzA4ZSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Yippy Kai Yay Motherfucker!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-2",
                "/jump 0-4",
                "/haste 0-5",
                "/arrow",
                "/zord",
                "/unzord"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:diamond_sword 2 20:2 16:155 name:&1B&9l&7u&8e_&1R&9a&7n&8g&1e&9r's_&1Daggers",
                "/shot give ".@plr." hydrobow"
            )
        )
