@plr = player()



@hero = associative_array(
            'name': '§bB§1l§bu§1e §bB§1e§9e§1t§ble',
            'class': 'bluebeetle',
            'sig': 'Scu9XDAgrF0FETl38fIwbOmSiz8rC+RJUMQ9Id+3A+Q5+MuhvXsCEHn7GNpbTR9J9ZmHzAu7f/GObfnj88vKfhf6GTAJ291NUYbed9+dOEo2RS6hqoadxB40MIeLwZlBii6VIkwWaqkdreu7u1hvqO/2Uq94yixnh9N71LMFafkkttQr7dAFpH/gVo+h8ZxrJGRcwHc7rBt6v/UPYhp3/SbC05slNuGKNa+EQC9/RDrXJKFizqNYqpkSbUFmGICjOC07IJo+7gLhS0hG1TC7eVXN5VubY1PKh1qabx56gzOQ6F9+Nvf2wzE7R26gCpbdhGTj4Z9Glb4/HNRWCYiMK44y0bJc80zKIWisbv9cvn2ukmMmhhRMtHv6RxIuURt+HkTJewYVYUsMGxcZtOxYb8x6N98sIq0mnTpxiQVHRm4aXrGKcFH0AuN7Lqkh+rKhG1lcSXghZTha5gEVng11YLtbpzwBQ01phzeFKFOY2AP6xbRLnHDXnWxo4ZXmMrqhGynJfiZs+XHY3DKMNngecUYCwl9katIVI3pkD9hxQTpzBg9eS44cUXsmqZYd4UpoKrwztfoDHZzeMTzw8paSe4vBqVSTTVjnRHuH3DC0x7QAwCl4MFML7tLuYyT6sGQe+bVqPkoudmSS0fkexFTLsDAQU1Nwd4YA+4fDqdpXoh0=',            
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODg0MDgyNDE4MjAsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJNaWxlc01vcmFsZXM4ODgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E3ODk4ZmY4ODkzNDhmZDE5YTJlODkyYjkwMjFlM2MxNGY3N2ExMjZlZDYzMWI1OWE4MmUyZDE4YmEzMTMifX19',
            'trail': '',
            'op': 'false',
            'speech': "Another annoying monster battle, another interrupted date... another typical night in the life of Jaime Reyes",            
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-2",
                "/run 0-3",
                "/haste 0-5",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 6 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." blueenergybeam"            
             )
        )
