@plr = player()


@hero = associative_array(
            'name': '§2B§3o§2b§3a §8Fett',
            'class': 'bobafett',
            'sig': 'aOreqc/5e0tHk5G3kXwuaYdNQANRZ7xVdjXcsDYEVyII5PJdcIsV2oq73XlDNbumVCEtnm+MDGG6YSo4gnHOz0SBpc2Sn4HfW1Zp1tRUQsmZrMgnr/Lz7o9uUf0fnw9KNaqd7g5Fu0iftMi2AVOv0CMHEarRLvtSkpneTbBerRWgDFRTf0uy6USx1/LoTiG5xDqiKwNO6HWjaPuyNXPxlAGEGzF4CDGkiVn94s3ZfHrWmmGhKuTv9bCDrH4e9ve3pOaGpWvTpLFsPFhycVaNN5RfcUPQZWxihbbJ5vVZysGKdqrd7k9SgU1iVRYRPUB0Mihat1EUCpd6OTBi/M5R/vRvgXIXDjrGNNz/7UsHDJcsDerskEtDOFuHy12y4TXCQckD/xqzzLGNZK6BOTnNUkpcRHYWGHPdTnv++q7a87J90wYRptNvbythjPmkHZ9cOrOKKAVL6gxe1NhfejZqlX83uPLTHI4JAGtA7laKB9ZnUIq1zrCA+dZF54buE+38y+PrwXtwjXmPGWPsEQtmpNNKWPp7GEWxfP8bunDNkXc+StIq3auNhbW0A3RYFR3V3udCJU4kPkVenp86T5fqzDJ4uyUPkyalyhxqmn6s4I51ZuokNVcB9TuoWcSnK1e6x2mmV1/8mqyKf+qAmbvxtOa5F4Ru7xfttEwHkBCJQ3M=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ0OTEzMTQyNzYsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWM1ZmMwZGM4OWQ1ZGRlMDc1ZGQzMmQ0NTdiZDhkYzA4YzZhNzYxYTczM2M1NDg0NWIyYWJkMDlhNjk5MSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "This time we will get them all.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/fly",
                "Shoots rockets with bare hands"
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." homingmissile",
                "/shot give ". @plr ." blasterrifle",
                "/shot give ". @plr ." flamethrower"
            )
)
