@plr = player()


@hero = associative_array(
            'name': '§dB§9oro§ds',
            'class': 'boros',
            'sig': 'ws+wFA1+u/gvrbf3VlfnXeLFae+wRJCtQ6qkg4SJSw7drLfkAQq0LX5qNjlOQz1KguxDA5LkkSUKy9/4hlVG7WP45WOe5JkAZJptiIgx6/Bc4HYxVecKtaMtawFCtYJTaOFigc5zsUQzdF4JfIOnWfXpa+KfOTaHDmVREFgIfuJBQBhoilVEBN7WymTYPB9GvQS7I3N4FLPpV9Y7foHsPllyaJntzxZg12QJSYiSdCGqFgS7PJZJyxAmOdE3dT3XoS8LXrpREdxAdzJteuHTPCBHWy+5oDAcl0bGn0MsFdKGoqpavoWUgzl7b0X29z5Z90qjJfgNDOQX3rVtTx03kEsKZdNWmLe1e659wt/zRkh8kWaPBlhfTlwzBX+2LKbE0D/hqSId9idqNNvfmxpabvDRynZ4+lMzm1ftdi/toOG6CykexWfaiMCfkaVGj0FPhDI7BrJg0B7hxX300qYdunmUupkx/GpZsTwYlS6BULk/lRvtb3OUCDxt4rxtZIQ/jXLdL4upZB2vGhrWX4O+UJfQfrHeXCGlMq8xePY8kdvP613Nc5O9ywSqoSm8gkCW+qhemGdxXRKoNQ8cm/n2IS2KiddhPELfGwl91fd8Qfg48xf7fX+//NXl8ICaVR+uqUJMWtb5KmWmCqFOSn/YIoC8zqDj7x+wYvYing/UUBI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODEwNTc3MjA1MDYsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzI0ZGIxMzdlN2M2NzJmODEzZWFlOTM2OWQ4NThiMmExZjkzNjVjNDlmODcyMzQ3OGQ2NGQ1MjIyOGIyNjIwIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I am the STRONGEST!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true"                
            )
        )
