@plr = player()


@hero = associative_array(
            'name': '§dB§9oro§ds',
            'class': 'boros',
            'sig': 'n9LrlCx5Ydzr4uKLflHmcWCZ7pwmRxygmBRt0zf/Rx3CDi7k+Vm1Bq+EPMGCbp9MX2V7ZzgZtyO/It3jrVHNhRkVIJ6/78lHksit0BiTEYGxeSRE80MCsnEiVaSiRALtCiR9QU5dTR1/73PkcfQsj8m7n9ASlPRIie5/dNCmkI8TFfII3n0tlbbsLwp/8ElUFtN82O+Xhfc1XLzaSTJrsIVtg175Sk4JSt1VETpo3AQ6ySbFE34fwL1wzKp8bzDW7MB9ZGnGVUxCKU0jzPGVB7R/5hJRxaVWgZz7VRQPnva2XzSqd87wirWXAtY/JFNxsW8uMvUMEtHm805QWnQAt14OoO1s4OCRZ0T+5rqqEf1HP2eYc1Qx+WrUMk+ESuDwDQkgG3ru9o7thziwAWtLLmv7xZc6rYPJ/DgeKvz36VEanU9y/IUcaufZ3kElRFjoEE1ELJR7MbjSg/pdf5Vdqb4rHjiQ+IuDW8VKhHjs1eX4/XPFelN1Ui9EbWu9DLflo4SY4fBYdLeXyuqZqr+KjgJpwP1QNuwztFOKw6NCRGRQ/Alaqst/S40RupoPioTtIgW13K87t3q27h5asrve0g5Ke9qFqi7AsbnRAeG49NL5/OTkQCEGb19PpBMOWMWlvF0Ga3LBFRezGEUGRmJzh4Ojs0jbwS5IKaQ2aibuP+M=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjY2ODY0MzYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFiYmQzZTk1OGZlNzU4ODdiMWJkZGNjMDI1MzQzNjQwZmU5NTc0ZjNiNDgzODlmMjU0NWU5NzZiYTQyOWIifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am the STRONGEST!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/haste 0-9",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true"                
            )
        )
