@plr = player()




@hero = associative_array(
            'name': '§2B§5r§0a§2i§5n§0i§2a§5c',
            'class': 'brainiac',
            'sig': 'K3nO+eWsiLn6YEX0wqhhaJMygeIuXBDtL7JXgt7Lzjn6bocDmAwlkOSr18NCxipqBukJvcKhzAVQSNVyQyOKwuaaQ1L9O3h6OH127jpcESbJ4NL1jW+rii60+e4/K876xlwS5hlwWrnUX1ahtW6aIHmGRrt0MRIFkrsw9UTzFJgMkD2WMt+JiVU8jYTEMUSE0a6julFouBMh4fGu74shlOtWVSQZ1vPYnfuTUA/lt1RMS+07qq9zmcstUjYK3W7ZQBmvy0An0AHMhE88s5dEXJkce3KfxiJDqM0KiqHbfF6M41cubn/LeqO8n5Y4k4qo63OQbKNdBp4RAF/n5eE8t79c1432OFMUTGnyV2CzuWQElAXZc0wOxHB3SuvNvWqrnqn5gCroplYLggrtinpVF3StGnJIM62x0d0DcrtGU6U/c28GmOaLAUcwnXgj3/1833D5mElLGbVlPiOBSvLldAzbvzFLIgoKlYgsf9Tzdn1O3LHjSFCKMzg1QJoSmhFcTx2lpP+Ph6QiC9FDYLbpYREb/rQM06BGFGQhhp73e/A9D69hTNAP3VZciFVzbakIF+kkJI1TsJiQQ3txcVUmxi4n5QRK7EDcCGkUUqxLDc/hQBJEFoWylmnVP8s6lGpY7accIkhwoP9d6itdLwi47RYkoH8v3zRasqZ9VtD1Tl0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAwNTY2NDQ2NDAsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJVbHRyYU93bERDIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83YTc0OWMyMWQ4Mjc2MjM4NzA0OTQ2M2IyYWU5YjE5MzNhZDY2MzY4OGJlNmQyZGY5ODkyODE5ZDIwNmVkNyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am the smartest being earth has ever encountered!",
            'powers': array(
                "/buff",
                "/carryplayer <playername>",
                "/dismountplayer",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-5",
                "/fly",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/speak <playername>",
                "/confuse",
                "/unconfuse",
                "/mindlock"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 12 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 9 true"
            )
        )
