@plr = player()


@hero = associative_array(
            'name': '§4B§4u§4f§4f§4y',
            'class': 'buffy',
            'sig': 'jT0SqS/qLKOHXv7mIsZ75MmcLedwU0o61xHkbnUyKA4cs4LJRHuMqGw5tQT8ROCRWJ5HnMg2Dp2VYZkP5PDrOPnFjaPm1w5bFOCLo0XKdLT9a8KVwuiEaDVA5cDB0FEbdw/AToMlRr8x/313cwgaV02rkQLxhPpKynaiO6PyVU2AWHg46mgDhCJrRBjbS4JbfLGr+oxb2DnQrjdCQgA1qLkLhxaFFm1J3W3E81793703mgACKN/mG+Jj75kghLhjjzuJ4JLAR9qDseNsTqw9Fw927jgOqpBb37Va+HrjW5HfZzKBovDRK/qwIPzikmUPSAF9Rp6jq51S5+18PFBa3yVeSJOLZPvkoIBmWHgofthHTaK7AytodpfDh15+JBPVoPl33pw+DbcERHhUAiqpp7u7x5C3xZEDmpRDu++Lvp1WJCWiwjdIpMwtaOYrCNBpwkZAy6RHJmNkX8HAVEz2zrr4r/srN+mXoNtYUx68BOagaWnCfCWuB+6/1iKonQbPiIVR4ZzKvoEGl9SNAIdrPcxVfGnWUNkiRioYMaXI7g7v3Dt5q+Z6cf1fUdLmbc9MEhnjz5QH3hXFuw7/kQYEzJkNOqLxxnRRccAW/LOQxZuItmJW/1Yqv6rn2c7PtYMRSlH3ZZscasPeaVSIk1ykOZX/yoHe6Fua0V7USRjiJR8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTQ5OTUwNjU3NDMsInByb2ZpbGVJZCI6Ijc0OWNiNTc2MDIwYTQzNTA4NTJjOTllODE4NTg3NGY5IiwicHJvZmlsZU5hbWUiOiJkaWJzMTIwNSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzVmYzc0OTg2YTRlNGZiNDkzZTRmMjg1M2RlZmFlMmU3N2QxNDNkMGQ2OWM1ZDVlMDk0MjZhNzc4Y2FkOTI5In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Time to slay.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-6",
                "/run 0-5",
                "/haste 0-5",            
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 10 true",
                "/effect ". @plr ." 11 9999 5 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true", 
                "/give ". @plr ." minecraft:stick 16 8:30 4:30 name:&4B&4u&4f&4f&4y_&4Stick"                
            )
        )
