@plr = player()
@hero = associative_array(
            'name': '§eBumblebee(DC)',
            'class': 'bumblebee(dc)',
            'sig': 'M4dDzsUiO00oEeR8jZ5bdeuAg4+oIqdIfdW1dADu9pcbLzvN6JbDKFi+/HZWbAyn0BFfFZZZuKp2W96pxIpmgMarapx4fuK2ivvfD2E6BKZjWN6QLmdXRCBCGbmSiLQTzlGVl3J5R51JSbwSkd5ilYbgxtx/RmnU9dFcplGHgEZ19WmfKZWTqELwW8QDST0bL3Ip56YKbsEv6TyUCvhPWRsobHdHjvSl5vOW/0yVYgzjNreoeISiRe4zfwPUQ2JUcBnBAec2PE8Fe4Ca63Xset81s/qO9iAkoWjpxnRt2kbTb+ibvNJvRmucNiKXrx17u9xrzasND7dVbaTBxQApW6K5YJ5C/LitN+AysAdluh6QRGo2KrCl0ayiGDnvrZXRwubcGwQ6yY1tcGh21OexJ05BDNT9mwU4B4yvvC8Fzq4SN+enGKkTCxGBaDBUV186N9fQeBzizJI7T6OS9AkT4m5+RQ8mKACVoYeeIwHOt6Ofny7/44n/0mQojQ2zEmFH3TRv89CJ1l1Pd0I1NFKIbrb5frtz6tBl1bWg+lgC8jVdodR79F8bUflwOASBNEfhRZVSPww/1dulwSQad6qM5zMHQnjtQePe25lr/MXE3wttGTOseJ5kJoEwCjq8ld5bhqAjoO1v3ykqA+Qzqn7gOySouARUB5oqNfrZmvnGYCA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODc0OTg2Mjg2MDgsInByb2ZpbGVJZCI6IjU1MGIwM2NkZDllOTRjODliNGVhNDRlYWQ0ODljZTBlIiwicHJvZmlsZU5hbWUiOiJEX1N1cGVyR2lybF9DIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8wZGRmZDYzOWRhMTc0MTJiZDg4MTJlM2UxYmQ4ZWQ2YzIyZjZiYjk2NWFlYmExMjkxMWQwNThkZTI0YiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': There are no Decepticons in the area Optimus.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-5",
                "/haste 0-4",
                "/carryplayer <player>",
                "/dismountplayer",
                "/transform",
                "/untransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 7 true"
            )
        )
