@plr = player()


@hero = associative_array(
            'name': '§6B§0u§6m§0b§6l§0e§6b§0e§6e§0(YJ)',
            'class': 'bumblebeeyoungjustice',
            'sig': 'ZCA63kKcPOYoflMd6tZAXvsE8KJMbNrn1eSQzTUqTOP3urpAhYERrCxWiIa0/BFlnYYdffxfRwDYdVRJvGtMWp45JDLV4JRN8koaYZ2jcHCU0mB3Lm876b0KGtRNSe/l/Yyqwgbp1ju0hE50MOoNVUHM+QHR6vjdN9ljKWRZhY0SZYOM+Eaxm1T1usKJ0EbN4ia3ncCWw9xhuAn5iwuH2MxP2jaiYIBfRGR0XJTwsYlqPvk+eiAdl2sSf5mOAz5TLBBx7y9bbN0VVfcKeLvdo4800RxEe/oHaAHqYl/VgQwafFihAOFECOFtnblUvnAXHYJ7IWDvQKMlApY+jrewBsrk57Nvl7YeYWqHamlDgLDdJzg8THArEw3RECFtbjq1KhXjmf/DWz/f+Wt6WRX98lFHEKHt0aHw8t7NJXzZWesuYWxT/mwxLjoYvZyJKFiBKkW2JRGs1JWHSM0JFSmhFigllzZ4aT/Qr63BbDzYkCH2by3UFyAGuYyCBp3f8svKCcJQeVdOv2H/OkxJ/idK5fi9sxs/Ox9goRC3G4FO6NhjN/ruKDqFbc9Xbyey+LLvJId5vS2ME2g9ejuOIkyPaJ6Z6N6x2om0VrEWYtFrl2MgIzicWTexH/8ALNVDG6aFqHaUVOg0uHLWMAi/YdO+g5z1iPuTjb+AeN1fTNI3Qjo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTczMDg5Njg0ODQsInByb2ZpbGVJZCI6IjhjYTdmYzU2NjE0YjQ4MmE5MWRmYmY4NTgwYmEyNzNkIiwicHJvZmlsZU5hbWUiOiJUaGVMaWdodFNoYWRvd18iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzY0NmZmMDI0Yjc2MThkMTY0ZWZmYTY3MjliZDlkZTVjMmRiYjMwMTdiYWU0YTc3MDY5NDgyNmU2MjY3NDc4NCIsIm1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9fX19',
            'trail': '',
            'op': 'false',
            'speech': "I can shrink to the size of a bumblebee!",
            'powers': array(
                "/buff",
                "/shrink",
                "/normalsize",
                "/fly",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-3",
                "/haste 0-2",
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 4 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." yellowenergybeam"
            )
        )
