@plr = player()


@hero = associative_array(
            'name': '§9C§3a§9p§3t§9a§3i§9n §3C§9o§3l§9d',
            'class': 'captaincold',
            'sig': 'W+RUFJ32CbUEMEpRQSjA2CkxJXFw2NhqSaQPvyFsy8uUZnPD4ficVFREuQ4Iu8wJVKUjG9vlmws7uOcunWRA2/Jso/SAB1zr6hOuixqark69PhDQQL3PbXL4x9rfJY+p3ErMjlX79XQJoTeEMfLwFdKB3skI59SxQOV/FddNyPt94L+/y8J7I9GZXaeihPu9MdPvIk3Edx7JE6H+bABS4GQOvdRjUv+CU3w1iZBQJBoyBJHbdz8sYFWWsXo65tYubl+7bu2uYLU/ch/SENp1Y3ckWonO1LeH5YUkzmUPQ++HAxjg1OtsyiZ73HQp9UEWRBRwtBbpjDCqUWyMtzvMM412I3wwJslxkz2cvN1oOE8sKGHm8J1qZO0HVafGW1K57rsy10FR5yyz+9oLiVX9wJrqvTh5ej0h7bEbxFKVwjbQgI8Ve6OVZLXcswX3S/lsMcuAiKvoGdiwx+PVSPSAp5eKD4kEqW7a0vC2lLwzvtHpLHx+kMulndmdq9TrynCGGQa5McYx+6PwJbX2Hw2N5k5sXUE0kfAMYRaY+zgBh02cdH0+c7EbPgn/CUs6ZbXeI/DxLqLA0Yvbdw7BPcKkPqd4+fcm+mfZvkSAXS8bjT9jhNr97p6Qdd98n6l5DQ67px27sbQqaP/LKC4JR/GFFfu+vlaRCaDLTzqu8V73NG8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk5ODc5MjkxMTgsInByb2ZpbGVJZCI6IjhhNGFhNTg4ZmIxYjQ3YTdhMWNmN2Y4NjZkY2M0YmY4IiwicHJvZmlsZU5hbWUiOiJEb25hbGRfSlRydW1wIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xOWM1MThmM2E3NWNhMzlmNGQyOWE0MDJlZDVkN2NmNWJjMTNjNzE4NmU3YTUxNjM3NmY3YjM4ZDVhNTYxY2YifX19',
            'trail': '',
            'op': 'false',
            'speech': "It's a little chilly",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/shot give ". @plr ." freezeray"                
            )
        )
