@plr = player()


@hero = associative_array(
            'name': '§4C§9apt§fain §4A§9mer§4ica§8(§4S§9R§8)',
            'class': 'captainamericasteverogers',
            'sig': 'fW18bSRKrzC2x1X2D8M1Hzky/nD/XXFSGXK6Yn8NLaKcx3MRJ5LtCyich/ptgIJyJF6RqLqqMGPtxhzI+RLVtUBpNB+hJoRiUr1m3zcea590AI638G4PSL3bc2YLfLJJdAZhM5UK19kBTT9Eo6U0nCkCUqH7eQh7jTRWH6SMbt/cBKCWDYP9O104BcHNS/JqMpEJ1eVGRzRU1UGq90UKNEQ4yYdDIZJEVggjJoOUcmmi3gU6bZftJYQ3SZ+VhqC5E6nf9+SkVq3dLMmbMIpumAJbd9ALMtikKOtGShmwc3RNpkVfwoQbWnt8drYwE3Lt5f3ERyXSbEvWL3e5Y1i2GzMehpRTBM6iuT//RYZm4hps8Xls/AQUELpuiTvUECmJf1NcvoDSKp+0/OukCSXOKi1Ya/YvqVWeXcqxuti8TSA6vqRghydyhqtY9pELYV54BmV7tv+xSfzksQ8TIEl6Nfa3SZv6PWXR6jQduCYymnOiCtRLkyDjeGU+uDQJsgWNwPkJ1RwbJSKEwjeBbDAAsfdgSZmXJNVrHvOgLhZHBzvN+cTQSRpdEy60iwxtO7/5f9kuB/ZftgU775KHYCLeXC+h+1ClV3zI6GoNUSJD9RvZZAHrtOulDlH0zGRYy0iioW+H6o5ZtjZO+11Y4bHDA2pKZ5ZS9aY2FjfHTeM2XKU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTY0ODg0MzQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2UxMTBlZTczZDczNTM2MmVkMTYwNDBlNGM1Njk0MzEzYmFjZmNmNjM4NWZlNzFhMzRhOTYzNDcyMzU5MjNmNCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Protect And Serve",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-4",
                "/haste 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:shield 1 durability:3 mending:1 basecolor:14188339 HALF_HORIZONTAL:10040115 HALF_HORIZONTAL_MIRROR:10040115 CROSS:3361970 STRIPE_CENTER:3361970 STRIPE_MIDDLE:3361970 FLOWER:16777215 name:&4C&9apt&fain_&4A&9mer&4ica's_&9Shield"                
            )
        )
