@plr = player()



@hero = associative_array(
            'name': '§4C§1a§9p§ft§1a§f§1§fin §fUniverse-PP',
            'class': 'captainuniversepeterparker',
            'sig': 'xfeKOR3Y/0VN4nYXicnMdtX3BUZl8FYpxVT5WjKAMnVR8uI42itPLXDbUPjWkDTOXWYdlGdANP4wuJJFa8Hvxonl2AjOt9DePHVAxZdraOc7SEhckQ8y/mAK/2NlKehpJgEHT/L6vl+4+GmFys0S1/Xs/vqZjGspxAJBEmacN3JNVwyOZA1E0RO/Hbbloblza4l2afWozm+JDtCCi+1t9trCDArN9zTrjykIvXfJZgWhr3sdHTRDlepjt/IrnL8JC1jQn7sDXZlmkyxIXxQ5s118DCZnt1/YZBpRAfKTmqmCjCT1vyaDKitEUHTXIW9lzX/EiOS05rucy+e4eNsb1ACIIrczx3hAa4BdIVAEioJbQ1LKNCj2Qdd2JSWhBJdtETZ74L+q0LbPYl2EGpRJK94dw468ohvZy8QJM+PWP4Buds3M1nTKPfs11HanfnePSUy9SUZbl/BBOXsNRVDXRzMaZjYPIymNOqpMZuQMg+D+Ijq1P20Em9xjaz2MowvgR1M3wk6aST09geVPdD52sWyT9R2VVnV4Z3mHhulytkPjUr5QovtRn7gsAlH9W82B5JVRKUVfgGZdQJMkZ697iyOTOCcmtmeFdcADYEk05rKQQKTnygUcQMIpyyjcyrUiZoNq4qsHYqaL4uIowNy1tkfhcmm6sNHRQ2elLJsKxbc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY5MTQxODgxMjUsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJXaXR0bGVUaW1teSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTE2OWM5ZWJkNDEzYjBhMDVkNjEwNDI4ZjMyZjlhNmI4YjI1NDJjNGI0MTY4N2ZjMmM5ZmIyYWI1ZWExMSJ9fX0=',
            'trail': '',
            'op': 'true',
            'speech': "With this amount of power comes greater responsibility.",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/fly speed <number>",
                "/fly",
                "/carryplayer",
                "/dismountplayer",
                "/web",
                "/websling",
                "/gmc",
                "/gms",
                "/speak <playername>",
                "/disguiseviewself",
                "/mindcontrol <playername>",
                "/confuse <player>",
                "/stopmindcontrol"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." yellowlightning",
                "/shot give ". @plr ." webshot"
            )
        )
