@plr = player()





@hero = associative_array(
            'name': '§bC§4a§bptai§4n §bAt§4om',
            'class': 'captainatom',
            'sig': 'A0f4ZnlZ5iEXoUE8KLc/U2z7ad5F1XgpX/nnODfSWs/xDv3CNkvM8N5eg+B8/mzn/S7T79IGwWD3NEUqD0aXZe1wVDfTUXnXAw8OcakPZRcX7S3hgGM+noW2cqvDkwPWYr3BPcuJbQP2R/p3S7TtPPWW9NJsO+Y0qx82ZirgMtTmL+f6xNvAtTXAWKjzjCWMjN5zguwRCtjPKrWzl3S6rz0nZVrKKOHP4Mcmeacdyc2cNp8Sq3wEcor6wMLEXpzWKGIhVENgmgPdRMGuTXSaXKsSFvq6IzSzem2fr1AD+j9SUAQPTmcwOt+ax+Cn02z62O++5Aic2RHhb2Mp6wJ6JosImPEtoKiYR3fglh7xXJJQd4nqUmWfiAdWVBtc1FejyrWnO9OZ6CoI83gIrRIdlfCHGiIMErGFaF+qJSod5ZvqHSHEGB3LbXo8gc/KaZxI2HUvR+5KH9qeVjs7tGJKDBbAhWNkwgUkXSO0Dhc6omeJxzai1hEKKflL/7AsC75sTIiF8uvM21AOzF+6o8plR3GedG9kgFVZ6T1ViWUVkne1UlypXTOsbutsIBjDtUO4rJIfxYKOiJKx+Oa+Wk789BWNLvuo7S6wIAJoZB3Mp10QPc1x1HxEv4LkIdkUmQJTc6og2B97wHhZNsvokYMQN06YDdPoD9vS9EuTpDQJe7E=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODUwNjE0NDEzMzgsInByb2ZpbGVJZCI6IjI1N2E0NWQ2N2RiMDQ5MmQ5NDVjYTAzMGY0OTg1OTMyIiwicHJvZmlsZU5hbWUiOiJCb29mdXJkIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80MDZhYjZjMTM4NmU2MjVjZjNhZTM4NTdlOGI1MTZkMDJiNjhmY2NiNWQwMWNmNjU1OWNkZjljOGRlZGViIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I will protect everyone at all costs!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-3",
                "/run 0-3",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 9 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." energybeam"
            )
        )
