@plr = player()



@hero = associative_array(
            'name': '§4C§1a§9p§ft§1a§f§1§fin §fUniverse§8(PP§8)',
            'class': 'captainuniversepeterparker',
            'sig': 'bXVtfbWwGBWjGOM1gCvM6C8NMBCTcfFJyt7+CZ+auY2CzCEZhN/QhTnloMDZpfOOl2Cqg9iR9gB2unuXsLHUL9hW1cbQ/ymQvxuFhBjY7l2BaRgaHObCFf0ddxDvb4LpogE28fdqwLE5j6XIOoZJUkBhN/kic3L81LIwlvpJH+kBUd0ejQ/R8e5xfaH27ZaTWCVAbRX6ZMsRVLobI1dc3WW3StqtjlXTRQ2o1Hgh8rK+JtdP6gunAlTQZ2cXUmsWatusujKwtZXUxPos9GLLt26mqo8xuTbAdbDGDtKzhnE0a4MRPf7LFXVU5hAePssGHX2vFPh8FwEAvQsIWtBwrxd/wCGFTaxnlhqDshf3tdytAw57tpd0Gaty0mzHbj3zLi0xLcuoaoCJXF1ILvyJAHXbXlGjuuX6S4HRoUjRIgE7NODFfrCSJNvJ21CpA0W7OXNesef3lvka8EpcLzHNEzEJKftpXXPBFF+J3+8W0bP6rGpYacbhaPO6/xNL2hXuGQQl7YLnh9FVWaTp6WVvKQD7Tawcv7y4hZeI6+TOaH90m1JAYPG4LNKWBTk3louzrCDHA6fvqAUIAe80HNHcHhariLuz7h9Ma8oYjESLpJepUEQpSLKrkTU/6rvJfhmHB40vyfKv30EXXL14Sjw8cQkmzHFye7FsOrQhvIchj0c=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAwMzIwNjgwNjEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJHb2RfRG9lc250X0V4aXN0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mNmFkNzk0MTYwZmUyNTk4MjliMzMzODBmY2U0OWFkMTQyYTJhY2UzNzY4YjI5MzQzMzU0NGY0YmJjNmVkNWMifX19',
            'trail': '',
            'op': 'false',
            'speech': "With this amount of power comes greater responsibility.",
            'powers': array(),
            'buffs': array()
        )
