@plr = player()




@hero = associative_array(
            'name': '§4C§0a§4rn§0a§4ge',
            'class': 'carnage',
            'sig': 'eBcJoQtCn6JQdk9zE7BKTduw2+CGRJCaLvCMuQcki9eyvV4NbMMDAF1txIPLvmUvLehIAEdxK/XRnWHyRJZjPs0cMJQlyJKg0cTVX1CuRjpaAhW73hgvxnj2RYo/fDUqcRxffY33IG0/1Y2Qg+bWJRUNwFFh8i8uj063kxLv5UMyQcy5hEQxDaCIFgx6dc5l7v5kYlrTpoB2t9U4FfJzH0sUowZeugFEFYOeSfwaUpn2BBrQBiU6/0bbSf/dH99N0PPLr7ROiqgO9k1Mth6EzCxMoIAjhefZECXcex+z6qn51VLZ5nIi2+gEg9tMh6OnTByU9GCLj1mAh9iO8hPoyz+6V6OiiPafFZMSQW1FZrbVj66GHLwZPYlv3wZVHYEL7nx+VgGro4aSrVI5HoKjg3MErmFVY9RBoywr3jAqRb1B5fh7q5C0t+9sH+QayYAJ16SdRfLezvsdMXTXT2dq/d2QwakwaRHuqk7lbYs1bABn25e0vo4G7ymPqJBZehD9SBQ8cr0vY0PNZdxCoKiwoLhIgGSl4/xH0U0TqTFU3a0qbHBg7VDR9rOCuGtJ9XlSaMfxjL8KSkKqMP8FSQp0lNJaVz8CdFOdCNQ+do97Bnz+xDWQpvoWH6OhCexS5rI6fVGTHVH4Au5N7yIlN/xQ5vX1iBV8Qa5CO+RIhRz5pyI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzk4NjIyMzAxODMsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzNhYWRhNTM2YjAxZjZhNjUyMWM0YTk5Mzk3Y2ZmYmZkNjE4ZjAzNDk5M2NhYzVjYTM0ZWM0NTM3MzJkNzYwIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Again I am reborn in blood and agony! I am CARNAGE!",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-5",
                "/haste 0-4",
                "/web",
                "/websling"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 6 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:web 64", 
                "/shot give ". @plr ." webshot"
            )
        )
