@plr = player()




@hero = associative_array(
            'name': '§4C§0a§4rn§0a§4ge',
            'class': 'carnage',
            'sig': 'Uog5m9vDdimMkp0rVQgjcLaRJw1BzxXc64xRb+1LjmYrOms/5u2bdQYlxZx5A23zNBO4YQOmsMnPBR6DkNtbr9118VVhxiU3JdtC8pjSZo6wFYh8f5aZm4RnnWI3v4Skc451BZmVicSQVVlWaNGSj8rJaW7Gs90pw+ruUmmZ6zKvxsXX1HjDhpQD75tMbMYzIwoOG2CxD/C0u/NShYFWg1OwUoA89H5HSBpZehj6esGw3Gbodc3bsBMw/T2w79FYV2moEHLzJEHWPQN2cwONJaNx+d/g0DrBfbT3H8mDn1DXumcByKqygQMm/hPTh2ph0K1B4Zx3sPTmzRSR2J6LNfY0M9mCUkWIRVO4ENAW9u1fOI+Rm9HkIxEcXplvFUIR5EPAD8Xw6ogBEfq7gvQzZ/W+oEy4olOlxw6xQWcEQQG/U/aE69fGhuyocj7Paswh/2aHQFxiMsOjpvhr21X4eH6JnLuVOt8WA/tpoKOe3+7W1IMZRvzAdqhLrhU2SD1xT+D6hy7BPr0ObzyOMUTk+xMtQ61IJ94HOYYmadB04s1ZOxF4+DLiIkQ02hZ5rSuiKdbUs1UdQV7P2RkWWjwLLCUEKwMIAgQljExOPi//cEdUBwDoaUBYVtzBiEQl9cKwNKfdhGKWR/cFAXQEvbl40TGbOvTwiJbpcGIWtVRoBD8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY4NTE5MDU4NzIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzk1N2VmYWJjYTE0MmExY2M4MTJmNDRjZTRjYzhjMTI5M2M5YTFiODY1Y2ZlOTdjZTNiZWJhMWE0YTkzZDgyIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Again I am reborn in blood and agony! I am CARNAGE!",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-5",
                "/haste 0-4",
                "/web",
                "/websling"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 6 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:web 64", 
                "/shot give ". @plr ." webshot"
            )
        )
