@plr = player()




@hero = associative_array(
            'name': '§4C§0a§4rn§0a§4ge',
            'class': 'carnage',
            'sig': 'A/UwQfW5XxKqBpdDXYrzrwRmjgDnqOVTfKCYJfy8D2A6OWzSWZIx/iEWi67YBr2naaZZahxVohqxoy8VfMgJLmzbUVM+8HWt3z4RjZPQvqx8u4ce7x0OezdifPAVZjs8bv4vu9ZmkZjFbsdMTxHn6HSVrmGDr+ewl89Pu0QzoM1s2f17lRsMv5OFylQAIgEXkr+CikpzIkNx+ugvrlR4BfKtAkL2zscR20On4EdqHEGdkO1XW7vgeSkMdMnjQizzsyOHQiW9iPEWPV1hppdO172m+wHJqz1B/70OjXg2LCfdkPaEbYtNM+rHHnx10v+SBJ/9gBv/+0nB8l4C+MmCqMf6YvsTp8twxVDlsa8WnV8Cdrn6E8W63wCaY+kwNT/qqX19LpKoBv4VZT4zSEDtXzH4SHszfubTdi9pD8O7QCRdymozc14iwub7eV9YmJICiHhdzHS7Es0uj6WQB0bzDnvU6qnP8Ldn3BBLwRpO6tCALU7igIALX98kLSvRWFx+nk1b7TcFxYhSlZpYonh7WFOGTxE2/6OjOwmsn9Ad4OrCOKvrxqK1GGFreYl4LcjitYxsU4atPRlXDfZwO0u1S9uRE26U6lTXB+02VcaT3B9PfpXzbh2So3hgSjNR0pMG8YvrhUUMsQ+N7p0TNdq4WnJ3jiKe5FXQhDja03l+864=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzUyNjg5MDE3MzEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFlOTMxZmMwNzc3ZTMxZDI3MDM2MmRmMGNhNTlkMzNkNzliZGZhYWQ4MTJlMzFiYTJiNDllOWZlNjA4Yzc2In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Again I am reborn in blood and agony! I am CARNAGE!",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-5",
                "/haste 0-4",
                "/web",
                "/websling"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 6 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:web 64"                
            )
        )