@plr = player()


@hero = associative_array(
            'name': '§8C§0a§8twom§0a§8n',
            'class': 'catwoman',
            'sig': 'ZvcKsigfeSzI9F7yhkwethRciPTyYU7cATHinokOs8/pJK/JwuXLvUaNqqAJe0D4qT5PFnZUqmxh6OZaJPEwBl7z2afEAP1Fhuc2Rv5oBW6mued9B9QpgokNr9KZUxticst31Ge7e11MZorOUQRxyjuX8xUIODnnfb8mHYda67RomjZdmBqKlPgcYaiYTKN69fVpfJZquYahsoScSQriCGzLavQxWe5j+xRguLondp/CJxZ7m+EQmpf8KaVZgePSO/fAT2Hk3Jrl9XRyyi/A39fjwHQz1tA0t0oDlnsfNpcNy1ThJcUbCOz1wamPSH/zZQx0+KeJpshrjEmYT+R0iFdX9uY6E431lXiKXXdQuJ7a7ChxY6cj3xC78dNCBVqpIMT2iK+eS4u8FCF87zXtCiXaO3kbb17eV6yshYik6zfHbBKbsm4kkrxrRHxrDhqIoWZDyYXuuz1+F+y8rX1RKh8ZWFTYlh5xcT8+xrBhLMV/w5UsUgZMXhbfr93fq7/1zQltB0XXQ4xQsBNRir830/jVe0ezQhdKHoDLXPeMZ22qXuTeu4aWp5ojJpczKiMqIAK6pyB0JjP+fSH8WnHeAXLUfZxrYsC9wCEFKsZj07NHiPqJklEaA/ZjBSS9S7qBobL3aJiQ1CPGxT2RuD96SntOnWp9PY31KO/5wKoaXNc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzQxNTEyNzQ4OTAsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83NmIyOWJlMmMyMzBlOTgxMjVkOWZjYmY2Mjg0N2ZkN2ZhMDcyZmI4ZGFlNDBhMzQ5NzU2ZDNmN2U3YzAyNiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I'm a girl cat!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-1",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/give ". @plr ." minecraft:iron_bars 1 16:10 name:&8C&0a&8twom&0a&8n's_Claws",
                "/give ". @plr ." minecraft:ender_pearl 5 name:&8C&0a&8twom&0a&8n's_Grapple",
                "/shot give ". @plr ." catwomanwhip"
            )
        )
