@plr = player()


@hero = associative_array(
            'name': '§0B§8l§7a§fc§0k §7L§fa§0nte§8r§7n§8(§fM§7M§8)',
            'class': 'blacklanternmartianmanhunter',
            'sig': 'FOWp7ikohCaLOXZCIusLXDTvbBa5d2YMMKl3+oGq17XYxC/SNlgAsBWR6ITQHMvw7eVvDIJL/npwCnEhlNXKIRpI0ECmzf5WXFLch2l5N41rUi0hTlBdkonHXWD/et9QT+KFxoAfmOHywtRnzFx8ZwsrNFBCzU6NhJq59IRwpYWbwlIPpxYfRbG4seg+GkpBL1ByQTziLR+suKri9vy3Tr4b2LdKNhlPsOyERf8nQfZsCHu3xlve2SQgywb6l73Sb+Cwq6wsB39fn0SMcj9j3YpMi/ZCMbS9qHgpd+059BQiloYOdsRY2rRypf+Mr/APYKIfpsX7UP1kQ+Yi6XiXpAdFK1l1HlVmCZK23xHlmTqaeGWkfJ2ZfuQJRYVxa8qJ9CAktlK7S1mTSc/S1PGjTHxN6zXoTMqdC5masnvzSK209z4nl3YMe26GUHt9ViPSYTv2uMIrBCEGxEo2XzByZIqdi0N8hqVsgiZj0F1iZLtAgTXDR7VKUod5pZ3s/pJrT/QSVuq4D3GZhLxylG7M6+Tv/Cko+Kc3r2P0W1H7bV1v8M0BCdjayvtd/v5CzarTgTyF2WLiceWft+gP/ZLmXu4KBizR/oO+Wt6lCNBSqwvgaVBd62Ex5oFhvbpHukmHC8c0aSq12lVyW2DlFW2sC7rkS/oioqt0XXK0KSdI7l8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk3MTIyNDA3NTgsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJCcjBrZW5TMHVscyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E4NjY0OGNmZjNjNWUyNDc2N2ExZmU1ODE3OTJhOTU0ODExZjY0NjJkNThhOTE2NTk0YzYzMTIxYzcxYiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I, Cheetah, want nothing more than to rule Super Hero High with an iron paw." ,
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-4",
                "/run 0-9",
                "/disguise",
                "/disguiseviewself",
                "/undisguise",
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 16 9999 1 true",              
            )
        )          
