@plr = player()


@hero = associative_array(
            'name': '§eChe§6et§eah',
            'class': 'cheetah',
            'sig': 'dFGB/ZorEcut8kABFus/jt+okXfudG6x1GXTP1S/ADUJqn82UtfLJFbWW7qHKdhFtzyX0G9ql8eKoHqEQx+Nipd3dY79218zBXr7qBLrh1LICkQCPtS4omEZ+9jWG8EGHUSZm9q/s/YEZOwgbwXq2oE0jMTc2VAdmTGzni0lmnEsbu72CTk5v37glKQOKZsSoHyAjJJo37mIA56tbeihBSmFez2fWE51bKSVEUMnZhrNJJ8zLGqLAsyim3fLsiF51iHtv01TISogDdjc1S4IrQ+J2Wzvo9ZUPXAqIx5TTvPuE386MFocpKk+Gku4gemyFcuqtyxa2Zbf4wWNuq396rWvzsEnaV15g8xyu/MXm1ySMyAA47Of/pIUrTgXopz8sC/j1/Ba0eAhpGYy64yqmDNkmmysXjR5uYV/fiuQ+xaeOH/Los5mEc61fufud2w826b4MAM74ZInOL4jKeRv1ZoN2+Ai32opWKldsR5VHWgaTZiUrGXXF+7kZYGsUGKu4GojQSKU3x9Hv31jz78rjr1bwmJAF+ppnr/X8hW6n4tgXFW8XlMDIJRhx9Ekb8XRpp1vTEZDXquKRQ4fwvK1hdca6Uy8oVfDnHkAytdscN0bSbEiASOifX/F8afSsuEtB9bldbJzG2SfvSuh3LmyA4FrUXz9R8J1hL3DVOBX1no=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAwMzA4MDc5MjEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJHb2RfRG9lc250X0V4aXN0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjI4YjM0NGVlYzg5YWY2ZDU4ODZiMDgyYjlkODE1YjNkM2E0MWU0NDM3Y2ViZmZhOGNiZGNlZTY5NmVhNDQyNyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I, Cheetah, want nothing more than to rule Super Hero High with an iron paw!" ,
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 4 true",
                "/effect ". @plr ." 11 9999 1 true"             
            )
        )          
