@plr = player()



@hero = associative_array(
            'name': '§2Ch§8es§7hi§4re',
            'class': 'cheshire',
            'sig': 'YvzWKtNqoCarklD23OQS5TSXzyqnnubgqxdFtMr2PdMq85k7dhmEtaEimuaZvUsdvCDJMJEF/7m/0EEipdRdQhG+cZa/5bjOe4a9g6ANjWb8Hxz6YGaWATcq2/qyLgR4hsT8dFuHW1pn0XzS0loAatzgi9oVU/U7ndW8lwG8vqKbWNcM0WqZ+DwCO8C2E3dXX4lyijDrY3GDAaq1BNnVOjl9c8BN1c0LA0M4x7Kireodz2dckSaV/FN0w6+R3YM5/wmTlIxqw3LR0/J642kmeGFvw9WLM4DYSM7QZzy/UIsF+hvip5dlX8kiBxEIQWj3y3C3VLrTk8gcARCD14D2nEP/nRLfAdTVdtNvSFQCawcsD2aNdJ5GfMB1ajAXlmauEeNu0XxSdLVTdakiv/3GZLG2k+4rb7jVl/1A+0732SKecuSYT93v7VKSSjoJBJTkob532Xy04teu8zAPJbqNo8RktZjkB3nZevhj9xZi2lNwEAE6yPzsCJCApllmp8io5486Vxup7HtpzTLIedut3jJQU1K51cSNLp9ej30Ws7zysH9gz5IsbVLoSj1HLP5+5NrwoKbhoZRumP3zzehlwk6g31z7iu3FmMrmJboHrp3Hsbl86zGk73HyG8pmHZ4N+ijplec3qy3oiqcDttH6syDARYwyq3M+tsYeZQJWJTQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTA2NTg0NTU1MTQsInByb2ZpbGVJZCI6ImM4Yjg4MTMxNTJkNDRhZjA5NTkzZGRjZGIzZDU2MDU4IiwicHJvZmlsZU5hbWUiOiJfV29uZGVyQmF0XyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Q1MmI2ZjE0Mzg4YmExYmRlMWZjY2M4NTI1Y2ZjMGZiYWRjMzU2NWVkZmYwM2NiYWY2NzY5MmY1MjQyIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "My poison will take over you!",
            'powers': array(
                "/buff",
                "/run 0-3",
                "/jump 0-4",
                "/haste 0-2"
            ),  
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&2Ch&8es&7hi&4re's_&2S&8a&7i"
            )
        )
