@plr = player()


@hero = associative_array(
            'name': '§cCh§8i§7z§8u§cru Ka§8w§7a§cna§8m§7i',
            'class': 'chizurukawanami',
            'sig': 'P0reH02CKoUvFYYh8chVC4Jl+0ONnXfhH7txD3KGQb8y/uQsRLMgDek7pDOOLtN+xttUiw0wJeIV+1Zg0aP9yb05aMXSCEBG788drARgfuXDCEG+NUHyrma3ZUQFYHOgXtkOyw2jr1MM9pr6GP6qzPdZjAQ5PTUOzqQqZ/DHkyoRkZY7j8HGy8FWmDCQMfje3OFNzoy/0upFVHGTI4ow2WJVo6V8dSm0jzEQhplGpDHlALNIUTxM9Q/5zOvymSj14lURIEvprtdETjBNKcozULtJd2oybEnlG+gB+8W8hwZyCUNncAmKLx4n9P3+5uK3PneiTy4eHltnPk/pAqEojV7pUQsMgDiBWrdCWj5GW/muwmNJmlm0hFnhLEiVKeyaKMJgi9u6XI64hWkvvGXKr7P6p9TghdVRK4ngU7BxQ7GsTgWDQ7ib9palbq2Dh8FVhHbHRXnmermXgLrb9UFPn4A+a21H8x1pZWCq2hQmfl+hBvm47dn04mVn2BNEOFnf19ot0p4c//XbzRXANqB67yvUm44Sm58ha8A19Trsjz1CexWlBPobcxFd03Qfdsi2WvUkQ/xuAjXSea+fvzH1kcbwuy2SZef2EXmErQL1wxzyGoyFH2U+VgwoP5w03gViGptY7Bp2uKuc5LwqThOik4sY5EbMetrWwp/ERRUETXw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTM4MzkwNjkxNDYsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJMb3N0SW5HYWxheGVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzU0ZGVlMmI3MTRmNzllZGI1M2MyZDVjNmE5ODQ1ZTM1NmMyYjVlOTFhMmE3OTY2NjUzNWQxMmE4ZDNkZSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Bang!",
            'powers': array(
            ),    
            ) 
        )        
