@plr = player()


@hero = associative_array(
            'name': '§cCh§8i§7z§8u§cru Ka§8w§7a§cna§8m§7i',
            'class': 'chizurukawanami',
            'sig': 'P0reH02CKoUvFYYh8chVC4Jl+0ONnXfhH7txD3KGQb8y/uQsRLMgDek7pDOOLtN+xttUiw0wJeIV+1Zg0aP9yb05aMXSCEBG788drARgfuXDCEG+NUHyrma3ZUQFYHOgXtkOyw2jr1MM9pr6GP6qzPdZjAQ5PTUOzqQqZ/DHkyoRkZY7j8HGy8FWmDCQMfje3OFNzoy/0upFVHGTI4ow2WJVo6V8dSm0jzEQhplGpDHlALNIUTxM9Q/5zOvymSj14lURIEvprtdETjBNKcozULtJd2oybEnlG+gB+8W8hwZyCUNncAmKLx4n9P3+5uK3PneiTy4eHltnPk/pAqEojV7pUQsMgDiBWrdCWj5GW/muwmNJmlm0hFnhLEiVKeyaKMJgi9u6XI64hWkvvGXKr7P6p9TghdVRK4ngU7BxQ7GsTgWDQ7ib9palbq2Dh8FVhHbHRXnmermXgLrb9UFPn4A+a21H8x1pZWCq2hQmfl+hBvm47dn04mVn2BNEOFnf19ot0p4c//XbzRXANqB67yvUm44Sm58ha8A19Trsjz1CexWlBPobcxFd03Qfdsi2WvUkQ/xuAjXSea+fvzH1kcbwuy2SZef2EXmErQL1wxzyGoyFH2U+VgwoP5w03gViGptY7Bp2uKuc5LwqThOik4sY5EbMetrWwp/ERRUETXw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTM4MzkwNjkxNDYsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJMb3N0SW5HYWxheGVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzU0ZGVlMmI3MTRmNzllZGI1M2MyZDVjNmE5ODQ1ZTM1NmMyYjVlOTFhMmE3OTY2NjUzNWQxMmE4ZDNkZSJ9fX0=',
            'altskins': array(
                array(
                    'sig': 'JRyCi4Y/dZCaw4+ygRqqo4KHgK1xnjjOBlyIrRBgybva9uqIIsiF5H/R8RfSQCAoEbHW3mJ7I46HItq6i4XutqfYCahPh/VvYyId9e+gk+j6sv9fx27a2OQyqtOTXbAxwiRI5B7u9O4IGcdv/+8p2z6zkoAdJu6eSYOOSKK7ewYNba4pWuRHiXMXplElwqq3dSQVUgw1AWj4vIVuLGOHtSDL/Lj1YWA94ZfR8qSt5nJjjoVMD8OKXW7rK14eFT+zjbfO5AaC8x+Luh+rcqVmwOG0cDSslIvBMuGZbuFDak5pnLxzlShf9Yea2i42Y+MOJ+Mp+4cN+WXHoLHSxgKh5saL54TXliilYjFj3UP9kOHYY8VeCbihqDAO72Cano0pjp9uPAsRp70cEciP3PHw6WDCZHspRqxkxNelytmgmensKV7Bybsf8LG2TPSVxjwXGTB2WSXCCV4iVvoGsxUzf8JQgiiZ4SaWsRfdA/WlkXliCnuYAELc0oEFF81IamOxTD7gWlfzLmBJCqlsycG4n3BQm9DtDoUdHCyn4lOPh3w0A9wzAlUw93nx2/KFudFAKY5fqrCUjwB9cqkJHJeg6p9A2xdnyBpBDE68zK7QS/kvyJNn+VPWpLtcXAfLVOYG58i3RLNHDOreV8HYEDithl8lCWC4DTKmorcB27aCVfg=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0OTYzNTE3MDczODMsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJSYWlyYWt1dSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzVkMjRjZTg5Yjc1ZjMxNGVkNDlmODk1MGQwOWRjNjgzYjQ2MzcxZGQxZDRhOWUxNTFlN2Q3NTQ1NDY2ZiJ9fX0='
                ),
                array(
                    'sig': 'YedKwd0ttgte5lmc09t8DH8I3FkAhTwtKZCQB6M80ezWDqk7gAyYmkrwksO+D5H4EXRkV6Cjvrx9+ZS427+a16ZNLNfP63AMknB+QjTk3P9mR6cS/KakOHOoBTUfWjN4pXwgD1SoGxTNJMIdjz+/5Jhh0gv8x7k2p88xHwC8SGhgZSD6x3uHtYSL9E9fr73OW5NNTGgCwil8y5aRPsB2gVN+zTBJi9AeY5gyCXEMEzOq/zgOFeM4MtIeYo3QMBgflkMDlFbN1NDPT7ofJRhSEKEdqAC1LUCVtkHTQPAYtPcSqf9nW88KMGXpFEk5Qr8XbJdn8RXZgv2zfZd14LyTIqjzePMEYDbiCqJMdLKtcpybchYn1RCCigfgiyQYg4Qus/oLqcAAZodCu+s+S2vbYLut7b0QYf3+8kwELgadXIaQPTkmWrBJR7uHKqR8Ohx8zcSdBM8VqJlSHVVjgcolr/pOv0i7TUauSP96nYxTZBAjGPBaHmAq1VJwoRcKD7hOrS2R1TgvgqadEojf9BDly4NFGd/pje8pPQbtHghnyvn2Q/hawq24sajFPnmTfVXuWOfUX1A+2yR1tyH1RRjaJ2XJIVvfoOQX7DtceXEVKE0to9mf56VLq3Rsq8Zi8kdsyP0z5KLEA/ksWMWyoWTYH3XnQUi+ki4qMS5ZE4zaf+s=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0OTYzNTI2ODk3NzQsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJSYWlyYWt1dSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2MzMzdkYjk2YjQwZjU4YjZhYWM2NzQ3ZjJkOWE5MTNkNGExNWYxMWZmZGFmYTY1NmViMDdkYWQ5MjkzNjEzNiJ9fX0='
                ),
                array(
                    'sig': 'r0D6Xnz5F9xAcU7FRKJP7QUdPnqM1zijgHZ9OpBHvKGFnjrsJqosJZu8eo+4QbITVikW3lRv1e9KkObmtOaFVg+fZGFTD9gA5dUBrh3ZKpB8n5YmbvGzRBxqpBNXYey7x74qCAUU/+PLbD4nYZQsxP+flEmMtc17V6XZAMPRgZQmAOeLUuB0QRBeE3nC6DSMsYsr9BAzCBZYEUdwFZX0uvslj8zXnbAP1SpO3Ut5O3H/PciqJNNn2Lp+oXmkqIP9jnJ3afpehebF546ipxQLTX722SB3IC0lCfQ8dmoUQhK+BGBU+ZSFbFeaj95Ya4YuqMGEvXqVa3ig31kbsyJIqJM/0kDhcCY2VmNb7cawvdGufgZC09t7sB8uo0KcEomWzs1YldX4YgtQwt3S3g0R0AUexzuwZcr8L2ch/n8HPbwN4sEKn9BuMprUuUA0u0NHpRAcbYK8kMYIe8qyBgXndRnYVHerwnZw3sOmom4xWZ656b0FsjHfRzxACBh8LU3PdAdeymAovB32NOSjAV8AlGG1wuH7rsbukylKHqtIHR70xMrg7OeLgUJyqmfiIjfwv+hVRyCgcm8I59o6PhRwxSHqEdvK72rkZ/xTO/tHod5EbMokfZBS/ODOJOry/Vn08jM+vUzoVYovqBAZTn/gUvnIlp9hTlCfLm+nkRgmIgo=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0OTYzNTMyMDIwMzAsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJSYWlyYWt1dSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2MwZjc5ZWMwZWRlMjc4ZjFmMjZjZTI4NjhiMmQyMmViYjJlNzZiODNiN2NlMWQ3NGY4MjY3MWExMzM0NDMifX19'
                )
            ),
            'trail': '',
            'op': 'false',
            'speech': "Bang!",
            'powers': array(    
             ),
            'buffs': array(

            ) 
        )        
