@plr = player()



@hero = associative_array(
            'name': '§f§lChristianic God',
            'class': 'christianicgod',
            'sig': 'cv/DnXAIq9kCSz934YA7zPcgQFXvx9Ugh4JGzX1pQq68pnAOYrCZ6l+S3TNYbCz2uM6Kj0/q/X8T5ioZEyKMxgrdkeJfBKmU3msGlRdlqgJrEVWeWTOAuj6CeyCbohYyS3nVCivSnGk8XmPVk9w8saFLX7JbsYnwlV3lmY0mQeuhvZwciP8wNsa7mUj9OebhamSzt4XRvLdrINTq1ujTXRpWfV/XLppbDaEpeDMX3jWxwJYfcRALoBTVMS40uOp7DLjIK+E0BLumM5Nay+n+e8k9w1u8At8D6AZTWmFCDaDutIdO0i09SQxIOw5O+8tGTJ7jftfwJUCWWQl6lTLuVItVbyH9/5EIoeXLYFEuuUuBiR0WWTojpBd8mpqBXIxzqRMWPNXt065QfjZXGeqvR11JGfKxFGcR+TvBrSC/1COxqjSsZGfZ9qd98qVeC+XbjJhnpznxLoeAHwQ2MtqnL7HvDOcqAp8w1pCUH3hEygExAZuAMaVfL6bPW/J9g2FiGqtJDUAjhYnogTwHpzg9hioyJYkZPYXDL7PR5eS4fGdu+wowxZAlwMN8X+3hbg4qtK7VT6cTmCr0UZAa3T670eXG5TVwh3S3bFFQBfqq8drEZKnsX8qiy18wyGuFENpmeOC8ojLox7TGYVzfHGToQ42P/MdDtVUbE5DSgp3D0ag=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzcxNjg3MTEwNjksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQ3NTBlZjJiYjMxYTkwYzA2N2JiNDZhMDU2NzBlYjE1NzNmNGU1M2Y5YmViNTliNjYyYWU2MGYwYzRjZWU1YiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': '',
            'speech': "Fuck you, I am the way.",
            'powers': array(
                "/buff",
                "/watertowine"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&fWater_Walking_Boots"
            
        )
     )
