@plr = player()



@hero = associative_array(
            'name': '§cC§3i§ft§ci§3z§fe§cn §3S§ft§ce§3e§fl',
            'class': 'citizensteelarrow',
            'sig': 'FXDGaT5mnuq1t/btF2npKOIB+8lbbZYyjdslDsEc8DStQ0399U3imY/DFGnpbeX6mibnni1crlCfhOQmZTq0D+cAZkK+cBJ1M14vtvMdeAr1zjgIeAM1Zq2jugG4kT2e8S1N69sNEiRYdOrLuzzW90yCpYqhLyXNblfSRsLXZ1IqAbUa7aCFRA0QPLao+FvnFxc/HS1warVR+LdhJyuLZS5dH/vnqSFY9uBHapJpcis8NwTYL87hoZ9J83wiL9HlIz+vU1lNUryViBQL1cMPv2Yn1EMPB7yD0cexLlARzJO5CKJI9JfPJy5/7kIC+426uvYeoIoC5vNlB1x/hYm65tJOqHe96ay+zRXyS4hA++DCey86oJjeaNmpaKfQNlPRzeNX7tClhfEemWy4knSYqgFn+ZXS5TpxlImL5EweZl8PKokt9M23F3c0T58kOyh5D+5uqT1E6VboBrQaCLd3SBEVZibELdtEzrI1gcsduS0ZqXu8JN3cLawYDnlLL8FECFh0XsieUlxZK54K2g0jAqHHMwGZjrtF27cb+JIGLtY35hLuslK1W+qjNM9cY1Cek+BeempJe+kYkBP4bK2Bz15B+OJdIumjKi7rhkOseYgkyuO2GsApAoCx2HiC7rYP5dJfJBIcjh2EQxlf/dsu0AW9vLt+CbyuzQ/CDWw/r1Q=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE2MzcxMzgyNDQsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDQ4OWQ2NTY1Y2ExNDA2NDc0ZGRiN2M5ZjYxNDRkNmUzNDUyOTJkYzgzMTc1YzIzY2U4ZDM3NGI4MTUwMmQifX19',
            'trail': '',
            'op': 'false',
            'speech': "The name's Steel",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-5",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"
            )
        )
