@plr = player()




@hero = associative_array(
            'name': '§6Clayface',
            'class': 'clayface',
            'sig': 'kQpGVWwreRDDt5QhXIYiu6InsXCkI9O5aEbdBVl7gjdXgeQcWZrhxfZUlkhT7U3uNwM27of3Cy2aUQmrCiE5fAj8GjShn09h1c7VvjmijO/Hlolbg7tyl3KK/zNu2Dkhl0AxEhe9FGD+ldeoLQsyEndxOXJfHQ4stYUtauo4G65t+Etf88K6J09gWz4h1ZadPPBMz4oO9N6T+KohRsp0FI5UeP0b1SZqtrfRJLQ7U3fExZ9mQuBNe2E87INBMh8BJZvryHLQEclkvP2kA6Q2RxpgCqWPJyxDXBh0LertKyk+cCuSG0L//ZrLaEGvlbLd4PDorPGbou/cvbGwrVdRDh0BhxWW5WhUNqBbNLapKEt8yZcUQeGRfbfYhQIqKVRUhsD9ayb6+A86hdvsl3FoWhygynAj5nQRN9pppDif9KJ5K0BPmOx8Z6zaesxirznwqkMTrFVBH7ko+OtnoD2hdBr9Pt4ghcFcZMUj0Rcw2/NASh3/qKq69EIbZMtsXpMYb0ISggUcC/Jss9KSd/1e151RVwM5WDArs5nWyMxGaZJ7zfHPIGk9iUy+9/29ZyGh7PwVwItQyOnJYNWSMo6f69DFO51n0/esUrlm26y8VN9lmjNgFkWQTN9xxE41QV5AEo9QRIFOTbvREVQSCgWOyVDP43EqZgQdN9CSr8BtBBc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzU3MDg2NTQzMjksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2FmODkyOWMzOGVhMDE0ZTUyNTk5MTk2MWNmNGQxNzBhODQzMzMxNTMxNGQ1NDk4YjY4MTg2NzJhZGVjOTI0In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Glorb, Globba, Glooob, Gloob",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-3",
                "/haste 0-5",
                "/carryplayer",
                "/dismountplayer",
                "/disguise",
                "/disguiseviewself",
                "/undisguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 8 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/effect ". @plr ." 21 9999 9 true"                
            )
        )
