@plr = player()


@hero = associative_array(
            'name': '§cC§eo§9s§6mi§9c §4A§2r§9m§6o§4r S§9u§ep§9er§4man',
            'class': 'cosmicarmorsuperman',
            'sig': 'Aio1FChJVrbcojj4rqjXi6T2wCYGIV1g77LUBx5sfEOYOlQmeCh8isH4UZaFQPDotpQXqDe2TJL0V9SMo7pl+T1pxp5CDw9BmVaP2TSjVsLulNwvP1K6OvLbcZf1rNVfqDLOuXpLT7MZrHygXLDLtSb9PrOaU3R1CWy3bWrxfp84feJs2TOZxCjkt8yEIRGeGwEugh6VRDmWy6oNLjQ+jwpQY/ki5lAW7XVKdINHhPEZlsc1vNGaLAb+a7B8LcyrDsmH8S4mAVVMY5i2qZTKTuPV4FGFlPUxjCId+90iwIYvPw+v1zEL0CEf6oDfhz4/SUgolKUY/GqrjPJzx5zFbRVKBKz8KOCXcKWHpXN31hE0BwxqMRPwaYZl1ar+Bfol4sYYYvTbidUeywCtcNA/ksx3Npfd6qvSRmbHyhr6Yps8D4+UlMwq66OYia6BiHCRH08wLU5tHcFB6PhmtdzekYcLl9nNYs4FgDYTaXlqXzFHJntBHftot45uPNmF8HTyf02QZORah4lXwq3Ckgk2SCwGfwEZK2B21DOZbhOzdF1aZ/u93xL/ntPEmyJoiGKMAp4Q1/BZXfioVJd0ttzQrOj5LqLn3wB1nAEvcYRGtxqCVrnziGDOHRcnhSAej+cjh7okz29m29yNiGeY8XhC57rSZNyCm6OmN2lZ4fPSyMc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjgyNzkwODA1NDMsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2FhMzU4OTFlMThmZGUyNDA0MTUwODk3M2JkZDFmOTRiZGI2ZWY2ODY0YWVkZjIyMjMxMmEyODY4ZDlhMjM2MCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Do you have the power to contain me? I don't think so.",
            'powers': array(
                "/buff",
                "/fly",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-6",
                "/haste 0-9",
                "/grow",
                "/shrink"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 155 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 19 true"               
            )
        )
