@plr = player()


@hero = associative_array(
            'name': '§6C§er§6y§es§6t§ea§6l',
            'class': 'crystal',
            'sig': 't99/hFLh5dQgFrKCYYxsDSRZr7i5d/sVNI8BWzChsp/JQ1ozysm2o7IZ1Kx6hFdopZseoGQauuTz4F18sIoaWCHDkKRCLb4YOy8rfA6l+KuEqQ30svwnnCJnCi/eV5GJHWtrzFV8QSo7kwHUJ/PTgelco7iIIQ7h9l4aGYHqz+Gbf2AKCvd9pr5Y3m/Bl7CNh1ZL+DviQTEAwN/13XQeeS1SdZrzfREFmoO3P/fRJ9988P7Vqf/QPXDt5X32/0tXgC924RTMrbf/M9ZG4QJpU7O0Z8mrc1KCGpWbVFVUOKb0wiRHYvKPNeDpl//hJm43ETihHu8HOg+TcbHaRgF9+QJGZ4Oza2qZnr3jiw9j3BBRqbYBnCZkUJxpnkIQsFtyYlMkYw91wq/fAIDQnwaHGoHnRlrHg45WIdUFOXXIupXlRpc/7gWRTT0xHPb1RzS1NaiqSDqD83AUf3Z98xkRyrFxvCUtkprmX7PfTaEb76LPQGQ9Bx4LTOuSjf6SOz3IELO3g7Q/2qJMKyuNBiVf8yVhy2QeopgQ980boVm2bhbznyg7QzofqKEThPZv7P3ZFYHMDDzhsiiqU8chCWkYqqRFLKGxpdWnm7ha5zbZGwb7nMSD0V0iI1f9xELuLwA1/xqEu9bOIvePCUQPrW4I6aFhGz5E+71QwbjhzcZtPjY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDcxNzkyODAzMDAsInByb2ZpbGVJZCI6ImE4ZTE1OWVhZGVlYjRmNzNhMjQ2NTkxYjU4OWFkY2Y0IiwicHJvZmlsZU5hbWUiOiJNckZsYW1lWVQiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80YzY3YWQ5ZTExODA1ZWMwODIyMGY0NGEyYWEzYjIzYjNhMjA0MTZlODhkOTQ3M2IwN2E3Y2M4Mzk0ZDE1OTcifX19',
            'trail': '',
            'op': 'false',
            'speech': "Lockjaw, come here boy!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-3",
                "/wind <playername>",
                "/crystallightning",
                "/fireballpunch <on/off>",
                "You can throw a fireball with your bare hand"
            ),
            'buffs': array(
                "/shot give ". @plr ." icebeam"              
            )
        )
