@plr = player()


@hero = associative_array(
            'name': '§7C§by§8b§4o§7r§8g',
            'class': 'cyborg',
            'sig': 'PnkQsIiNFisp5RZj560gNnddjccb4zIZZijvl3iq1Rtr9mvvgRVaJbeKoazCbDmPmGHKbuP3U+QVQw75h56YYEf1mV1KOlkqB9+xILkQvJeaHe5D+4dSWoG0v6MpGjpmmLaC92Mvu1Wyu56Mark9JSY/JYHWqv4REAQ9jd4Zy0oYjAdc952mIQCe6k6vRwrradP9fe9zHrU/1zK/iIIsOtqPT6bBXzA5ALGZebJ6zK5WyIAxuF/m6ND7TYw/UvxTA/YvBGiLa5efvaohe2PPy6bHeyZB6nsr+RHOqr3gSSP2qC/W60tHf2XL9Jwz3T6JRckxg52AATg5yE58KNCMGZRu2ODKJP8sS7mbbhkqWb5tPeOke0m20cP1TuEXbcsax8I9z41BDBacVPfJAGKf0y41rbpdZWmZDkTQKmEtJqlkg7v2oa6oaVBbBPon+eloMU/nVvdnp/9ZePelrOBG4h2KXy4MbHAfRnjYLy+ZWIBLZpGlWj+PL4o5Xoqueu5FiGtu2OFOeh5sI8cLdRtuKf497m+eo4jEsk/fxj5IATqfgCojTnR0IpLH2ntzSIZL/6Lb/3xxU/YU/aiY/xq3aSZ4ke9vyLXv/e4SBe+FW2rK9ASfy63Ujx0GZVqgXkl5qOBP3Qe8sgI+Mkd5OgwNE8UOWfBCEfHS8THtmx12+r0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjQzNjExMTYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2VkZGRhOTk1OTRjYzJlM2Y0M2NhYjkyNTlkNjI3ZGM2Y2U4ZGU2OGI0YWU2N2ZlMzVlZjg5NjViZjdmMjMwIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "My body may have its limitations but when I put my mind to it, there's nothing I can't do.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-6",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-7",
                "/flyspeed <number>",
                "/fly",
                "/tp"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." cyborgbeam"                
            )
        )
