@plr = player()


@hero = associative_array(
            'name': '§9C§ey§9c§cl§eo§9ps',
            'class': 'Cyclops',
            'sig': '\275aa541189745c4badb79553f654519',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzk4NjI1Nzg1ODEsInByb2ZpbGVJZCI6IjI3NWFhNTQxMTg5NzQ1YzRiYWRiNzk1NTNmNjU0NTE5IiwicHJvZmlsZU5hbWUiOiJmbGFtaW5nd2FycmlvcjEwIiwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E0NDg1ZWM0ZWY5OWE4N2IyYTg5ODc0NGNhYjc2ZTljZWJjYzFmYjcyNzJlMjRjMzRkYmYxMWUzMGI1NjYyOCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Unstoppable? I don't think so.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                             
            )
