@plr = player()


@hero = associative_array(
            'name': '§9C§ey§9c§cl§eo§9ps',
            'class': 'cyclops',
            'sig': 'UlQCU4TBuhcXWLauPxSe6J0DeA2tlhBn/xa0fAO/8+stJIlXqpd+VEO73ANPJeuISl7Vx0Bghe4qkVwrbYC8oB6ixN7VLcYjCH2ovTVj0L5hs3x6Av8yo2ku09m3aeXEXC91bGsCxMcgUGDaBunrXZNheHZ0SdGPD74/ENPh5Qd4Tn4WugTryLqYmGPAp/meDWC84efkueXs5yDaNM7nGJoCsIeFXkhuRqZoUmK2b6f/ZsxZMtwK4dw069K7I09RSmwv+bofBCQlskBrSbD2UtV+I2VXmqsfA4gO9DS6HlQHfdEF5tkhD9aTTQG4YvtCvX70Z9XGsSW7zMPWFwoOY8Rmed40y3xPuU4kbQuFdzbSWY59WB1om4DcEwvFFitHBRsWhCOZTbOHd8M4tKuLEpWgBKx5E5gkx9ILebjSJeUcmjhGfZUgkY70qzqeWeFNTMHsXhRdLXv0y42/e7lWzEe1R3C7xwheV3JHFLVfM5p92GiTg5t4bclW1FtQax6ZMhBfXCRbKXhL/P0Jt6L7N/pAxplhu5SL48xjTKmzGGOAWiJPPO58BhIEl/CuxViYI0E438XScRZU36G6pfbic4JfrhjTu72KYRmUzjfkUm5uU6tcnlvMTR5N5Ekc5HoRGgJvbD+I/J9nO42pD6jJ9DqyCeP4S/i3RE25bTS50Q0=",
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzk4NjI1Nzg1ODEsInByb2ZpbGVJZCI6IjI3NWFhNTQxMTg5NzQ1YzRiYWRiNzk1NTNmNjU0NTE5IiwicHJvZmlsZU5hbWUiOiJmbGFtaW5nd2FycmlvcjEwIiwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E0NDg1ZWM0ZWY5OWE4N2IyYTg5ODc0NGNhYjc2ZTljZWJjYzFmYjcyNzJlMjRjMzRkYmYxMWUzMGI1NjYyOCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Unstoppable? I don't think so.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect " @plr " 21 9999 4 true",
             )                 
        )             
