@plr = player()


@hero = associative_array(
            'name': '§9D§f. §dV§fa',
            'class': 'd.va',
            'sig': 'daEPKuKB0o3XwXpx/nVvK5GUdN3QsHtz5oMe4nk8ZIH90CNuL5FW9DpiK27Gh2CvSEP9A87+/M6ggjRi0l0fGTg7BGX4x1e7HoXAd8I831BIbM6y5NIoh05GYefxOQq2VJO1OKqtSjH6/c28RSdCfSNAySxxn+577gKWknSqHA0UewQ5ZzmofuKjtrL9IzMoYg3+HWOuOLfmfTyd95yFvzf4reSkNS23nAMavK8gihHncOyOtAT1O40EcWX/2Jd5y+wrCwCEx8LpcJWOD9pivjbrtGW4hJmjVmslSZSJIoyXIonI3JBPWf1y9gNwgoAmfygiB0kxsDw1VDZfSL8GpHm00X/RrKTbBSoyPzGByMWi+ArUbYsxzy0d+0AfAAsG0MLlrE/iF4VoJfhKfKdUDyjbXnJvbSW5tAG6P3RSxlTXNl8kwmHKsS6rjEzWIiJPvLbeewwroP4SXRU6a/3to18grSx1ck6gjVPJOJHuhOP0JjkU5SjXIrKhbMZl4ekmZwurgmWbFKiDWVRYSCY0ojE9DXnPST/km093QJn0qhBo232dOVQt51cUqfkPkXaTmIm+CTr39VygKPSob0lWeYJ+sDBzbRn6zaaQYRCDSqyVjrxHQXm+9Lqsfsbh6pPShw3+YWHHqreDtAqUhkEdjikcwJjjstT+bG3pplRWKGM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTU1OTA2OTk0NDcsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJUaGVfUmVkX0NhbmFyeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzVjMTI5OTM1NzBhM2ZmYTU1OGE2MTdlYzdiYTI1NWE0ZDg5ODY2MmNkYTFiMTc4NmRjYjgzZjhkY2RiNGQ5MiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "D. Va 1! Bad Guy 0!",
            'powers': array(
                "/buff"
           ),
            'buffs': array(
                "/shot give ". @plr ." pistol"
            )
        )
