if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§8D§7a§8m§9i§8e§7n §8D§7a§8rh§7k',
            'class': 'damiendarhk',
            'sig': 'qT+suTRUv7hSIO89mAH37B7ArZi29bRDzac48vhHQy/0oyxW0QDVjkZShKsH8v1zEQJ4OHxd3oKE5O0s3XzC/+S5SBfMPUSAJABXuIQpuLR4OH9hPS5OaJWhRVubqOzRwrIz+oNT/vRjES0RID4bMsnSgJyFu3YsRV+hjBZdHSIPTvinkWEqgTxvB243Xxi73U7x2/Upy87Ly8zMsPKv1zCNzgZyy8vmaQv15cMZvGBqgUWKsdasSHh+IqhX4Du8sai+JsEgaZKHSG3TUqYCsd9QT6mRtevafTyWhOmrMS7NRCz2cKKCDH0N6PYnIJrOZm+eeBpzQ8tIFjveW8kn7tE1aHz35rcDYE2OtnPTdQL3bd0DnL4zGHDIOxa2je1OUGOnLintyFa1pQ24NZgLaYHC2hVSRVLsNysN0uJmWnGh6TUzxQLMXn4S9EAVttcJrgHBG7jvyKRjnMWKsX1QOF6q9J8iPA7OcpJB/etaiigDX6QkS0jxFAZi71UGhFOrDUKvHHvvptvik4ENG2mA1FICaAXtKaICbZ4J3hyqEklN7k+O3Fyn7B++14XcGg9/szT90zb479q9EgIQMIYacx0M/IIRphWaperxZdYGGitKe0xumkYxwdyq+tewx1V+0Ec0MUBr3R2uVlVe+9hoTL2qVciHndJxDGtBKPhku1s=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTEwMTU3NzM5NTYsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJ4VG9ueV9EQyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmY4MmNlYzU5OTRlNTk5ZDM4ODIyNzNhMWZkZDYzYmZjY2E4NDNlODRiNWY5NGJkNGJkZGE2NWQ0MGFhZTcifX19',
            'trail': '',
            'op': 'false',
            'speech': "I always keep my promises!",
            'powers': array(
                "/buff",
                "/push",
                "/touchkill"
            ),
            'buffs': array(
            )
        )
