@plr = player()



@hero = associative_array(
            'name': '§2D§aa§0n§fn§ay §0P§ah§2a§0n§at§fo§2m',
            'class': 'dannyphantom',
            'sig': 'UR7wmb1UJurAxsPJ2yslmFEXylXhWTNltPgDbITXtHleestk/yrv2bUNPLbQGsCWouaKbv0NvmYecb0SnOw+HjU9LQvaPa++XcfaquRl6rLslnsYneqWJepmE4AOC8QGTzcH0t0S0IDLft2eXJTyZHyZXwokuvGRzBIGNz6Q69gesT5EBV38ZX6C57NpN6JmPMgav0PGore1NN76lnEifg73rORmLX2OWgdAK1EgfE1ZI5riTuHadZpV32+kkXrZP9xpU5JCjpUhWqmbGACt5fe4/RpMeYJpbOdt15QlI7UdaI3V/JxobdlDKvFJIsRJCC6/VwWbUIqZvzZW1v3ZtTDB0R27qzx+tTiQBOc69Gdl1zXvXh2ZTzqupxKsv9p8GP7s45eUaqYl+tgGvULiLhZm5TaPjZ6x5xTDBhbJc8jl75CYA3wHLQxDhwnvqjYTnnrd8wNiApFHzdhb2j6I5wVA1+crZArRGCr2vu5E/K6yQ/B+E8ZPhiubtufhm3z3AyHg9dC3f/knlUGpm6GMZTZ0vOe/2vtsuE1yXpVVloZjsdqy+z8KQVcVnj2tDJISA/GvBvFGN+vRDytERXt33lRVJw8rbaElTpGSEeVUTLs8jvK8JyBjnS8bkyBaLFiJVQXvKSP/aI99T4GSBBtNdwv2w1hLcK/If4PfHLwErkY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODUwMjI1Nzc3NzEsInByb2ZpbGVJZCI6IjdmZTg4N2Q0MzMzODRmZjdiNWEyZTFiMzQ5OWIwOWU1IiwicHJvZmlsZU5hbWUiOiJGb3h5U2hhZG93cyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWJlN2YxZGE3NmQ5Y2U1NzZiYTkxMGM1MTVjOGUyZjczNjFkOWRhMjZmMThhODg2NDA4MzY3OGQ1ZjM5In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I'm going ghost!",
            'powers': array(
                "/buff",
                "/intangible",
                "/tangible",
                "/jump 0-1",
                "/run 0-2",
                "/thru (phases through walls)",
                "/fly",
                "/fly speed <number>",
                "/mindcontrol <playername>",
                "/stopmindcontrol"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 4 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true"
            )
        )
