@plr = player()



@hero = associative_array(
            'name': '§4D§care§4d§cevil',
            'class': 'daredevil',
            'sig': 'eq2UCkT3YooJ/YxZp9yoMyFUD/XVKGPy+BkmAPJ7i1t/5Td3k/wVb52VNJlGQm2qHoXYcpmubammjB7h+LjA2fLPS0i8DEpIYrzbjQoRIeSmkZ0F63pjoGjsQZjwruT0OOLba133ICpwMuNNwsXmiLYButvK9KpTHvkhCEWY//czYid5v81+2WvV7qJ0KYfJzbRfnwmtPDPCZ1pCHsy9IPBRJaO5mWTg4zuLTarEzt424jPwS1bHGIkuI4Da2Z6NerRsQtsgBv4wiHzY9MWhOuDH8/gP0dA+ZZ2CSDown8AtzJc6A0XdPA/1bP+DY+zzt9Oauzou2cbnZIuArk2MCNxdO/nJ4wlHnyUrq+sRTo13p6jd+VwA8M9r+29nF0eRcl4zN1taP96+VfIisewj0zHk/5kfyzn7Ux+j1k3uY8X4DW1YEXauzHKYlCb4OQpn5D7WD8QqwEwmpdc6P0GZJW/y9IVFVk/e0NFCrSbSpqxQT3qaFk0fhOgLWRN/ePUX5KOt9R+FKdgidV6TH/680os8HYmAuieTA1YJa1aJ5fnVkSWjjd4v42NoYrNnRjWQ3s+8Qu0ien/d/TH3bsKoUNPj096+R8qtKfUAh/TSL6IeVULOQnQbJ9CNFxce4xL3PXwQ7anc5/5q14C5HzF67Q73vwnBPitvC+KIkkfLKBY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Njg2MzQ5NjM5OTksInByb2ZpbGVJZCI6IjAxMzAyOTlhNDQ4OTQyOWRiNGViNjg2NDNhNGM2YWM4IiwicHJvZmlsZU5hbWUiOiJHT1RlYW1MZW9HTyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmQ2MDJhYTFiODQ2ODRlOTE4MzRlMTE4NTgxMTYyMDZlMmZlNWFlNjg0ODdhYzM0ZWU3YjdjMGEyOWM3NiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I can't see shit!",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 15 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:stick 1 name:&4D&care&4d&cevil's_&4Billy_Club",
                "/give ". @plr ." minecraft:stick 1 name:&4D&care&4d&cevil's_&4Billy_Club"                
            )
        )