@plr = player()


@hero = associative_array(
            'name': '§8Da§0r§8k Ar§7c§0h§8er(§0MM§8)',
            'class': 'darkarchermalcolmmerlyn',
            'sig': 'b7uDmL81XbITejyv6W5HYcTQNRHdzKFcF8o2q2nsSoJV23B6uWipxfUQi1jp6SayFeROAtv7gSJVGyFEjfVWU2FgcltHm4LKoGAnDlkZl0NsNYy0c+Rl6J3JZzD8RXg7J3dGmASUW7b68l0Vcc9NuwLGjZp3I9tJCt1iVOV3olXWviK+gbS/c3ArHSVnAWpdKoER9db81QvIEDq1XQWJRHvdevOFI+01fubuN/UENnpdFRz8w5r0TBfundiR3Zivm+gRRFRWrJZV/mM8F4d/nBZp3G2spft3NiRDj31mNx3Bb4MPz47ixmf1e9uiH/bxt1c5tiQiB6PLiuZA+CGHSTLtH9xRM2+tRu7hCPsLAmG9nffnNHfhAjiX0dDS9JY198NMI2r9rpr+3Th3fT6fw2zGZGibm5oEoUJXdShBe2j0zRDbR6XQgn+5mfqLIZWdqHTA81KKd2MyZnCQci6rbAqMxJzis2KoO8GOnFvDEzoM26XwTI1WtU2EKI3GiE7F73h8GC5q0DORqN8f+b3o5Umqqkgumdg3VJ+DH+6nzpjz3JgRMCRUC0F4dhhLUoqgtJ1C6//DgvaoGe1lGst3KESz0c+RoEwFVciPVem91fKAjoHEb/sp5olbiN0H/jOsCQBkjV3eOr3iukZKQGclItwur/azVrP6JKkyEfPM/tc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTI1OTcxMTUxOTYsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJUaGVfUmVkX0NhbmFyeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTgyODdiMzllOWMyOWQyNzM0OGYxYTZjNmVlYzdjNmVmODNkM2M0ODljMWE5MTQ5NGM1MjY4ZDRlZjRlYiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "You can't stop me!",
            'powers': array(
                "/buff",
                "/arrow"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:bow 1 50:1 51:1 name:&8Da&0r&8k_Ar&7c&0h&8er(&0MM&8)'s_&8B&7o&0w",
                "/effect ". @plr ." 21 9999 4 true"                
            )
        )
