@plr = player()


@hero = associative_array(
            'name': '§0D§7a§8r§0k S§8u§4p§7e§8rg§0irl',
            'class': 'darksupergirl',
            'sig': 'gKGy49U/EEMrzVLVd39+zreWqV5Wdt2KlbpEcpu84mIGBhDn6Qt6qEaSKz6Kf1UbjvoCMlX/F2qmep6dGQrdHlGVdn0uqegxxn6Qq062lUqo0vu5I55mHkmS/evByZBKiu8pmr0W1qbBqxMvjG7sIkePOx7jNKOKCGxhfXfC6fLu0SNkRkL0/wnKgbMs1pPRK0zrhEieal/u8yUJMCIk4TTzkq0MFjuFHJKKdAvhaX/FMfFa2Iim13Yf9eJ79kgeJKZY6o1YPrJAtPlN3lo1P7GhsapBBXJS44+Uwc95QmwJOAlnl0zzbQiFHHHWItZxLEN6EyYsbJtFZsaEJ1gh2+BCb8TUK6Al1Zp7pgxl2QvCYCCHfCYYRC8JsMhWy1lKWZazMAVkYHsMIIgDcnHxaCJy6WBbcse6CodAoEo3TtiimnleX1Ru8Hvbfoy+ChqMcNLdB/Co3Wo4nO0IM/TnkB4qu8YTm65DsbLgU0GqPqCzbmTykKvZVW/kAMVuxSFXOuHOWRI+qAqq6r55OWTLTPgmscFBh5KTvjInA3aYyxoKxsFq07lt7wi+pU8Ifx3/V5BVvcLEcX/yX7EHohRpJ3rvd4TwB2234CRAoppgvz+zTABJ8DivCCzYYtT/0TK7vxOmgpOID5+1FsTLbFznt3R7fyAwXL30JfiI1Thw5XE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDEyNTYyOTk0MzgsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJIZXlJdHpIYXJrIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTVkNjk0MjkxNTFiYzNjYmM1YTk2ODcwOTExYWVmOTQ4YjU3MWRlNGU5MWU4OGE4OWU1YzUxNDFjNmVjN2UifX19',
            'trail': '',
            'op': 'false',
            'speech': "Born from Darkseid with Black Kryptonite!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
        )
