@plr = player()



@hero = associative_array(
            'name': '§9D§8a§9rk§7s§1e§7id',
            'class': 'darkseid',
            'sig': 'TKym1C3uuoWg8gfKf/QkGldNSsR3iE6xTihWM+nUplIdLXNc726AOqNkrpwMMFeEan76FPzAcVyoREDpp3aqKfkNz5HfYb9s6qFb4DjsgLGImz4ja1kbblrvDQnMbcwyu2jQoB0qpsu7bTpL63TFUNyvX5V+MteYqYst7vDNISfM+b2Bfyuzpe6qazZRq1T6wPvY1gWfiMNt14YpjO8sANy77EGSck4tz6M9OuKC6B9YCHtbSwXkQHVN9VaWk9VYSFtZ664BE6NJwqLMwGN+h0fyzepUuUmg+3m6J1um6Jt49hIdrawRRIrUHxg767rQb4oPvw1Plpi3gIwU4aBTMshuzjjPdH8rDAJiYEco0nkWLLiTrJzK/ohmSzUYyLYu7l6l8f/1A5FaDVzoo7u1s3AUvaFXxrTy0t2kajOkZL9h0xwJcMGFWqQWGJ7y0WwuITrxNwbh5R1ZLrxT0mj47zBBszkRLh6C6UzcL4tVsztN4gVv7TEBt4xBZOGp/b97cC9SZrZQgAoYcUZAAraIPqXSBn1JlP6OGZJfkNHVxXdJJySy86voJn5eL70VBt6hUXv8wy1AfqnEyDLtz3+xaDpX+2fXKUK6O9J4ViwILTVGPUwWWQ/tLvAuhyV05rz6tT6kHK4HduNVJgAs6er9C5LOQSTSJ5gfbdeyEn0YJPw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzQ1MTM5NDgzNzgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzliZGM2Y2Q0MzcyNDE4ZTBhNWY0ZTMyYWM1MmE4OTZhODM0OWNhMmFhYzc5NGRhYTcxOWQyNmQwYmNlZjg1ZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am the Destroyer of Worlds!",
            'powers': array(
                "/buff",
                "/levitate",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/apokolips (travels to your homeworld of Apokolips)",
                "/tp",
                "/carryplayer",
                "/dismountplayer",
                "/empower <playername> (gives player strength 10)",
                "/speak <playername>",
                "/grow",
                "/shrink",
                "/jump 0-9",
                "/run 0-9",
                "/confuse <player>",
                "/haste 0-9"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." omegabeam",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
