@plr = player()


@hero = associative_array(
            'name': '§0D§fa§7r§0k S§8u§4p§8er§7gi§fr§0l',
            'class': 'darksupergirl',
            'sig': 'cLeJZI8OFL0OXMw/kiTxihtrgjAMEY4ft0B8FvscqgrqMacfGvufyjZEvfhAKQEt/Egnywtlcje9aYdFfPXDqJjKqkIJAzi42cqEBlPRHfsJEkE3izf6EZx6aDCIl757bMzTIUjBrkyqAqtdDkO2PNQ+5773il/mO1JYC57zdF6h8ZgZRU3VuFBhMUD6R+rLOI8+jMQ1Vj5WFM6VDsCC2cil7qSUR06lrpmgs6vtGjyp0Rf6bGr2/GSa8PkePG9iIJd7tSGd/euT+uyeQ3OE6OaUXBQ/LRVlQ7FudkLviqe/gxzefrGu5sgHNafqVR1wIK/uWi0mT0dSJ9kMCi89Sz5GeMPNFfB/z23jWKaOFChjVHvzXO0Kp1K+JuJUqLZmmKNQum9dLIHZYHD65S57KmZE6GYxSADFW0QYnsz5ParQYiyx8YxupP+kTau8sZmZXvAAnEPtkN3TzsKDeoJTE/sGUwwI749+12BLnvjNPf3b50qYcRy5AxQV2AJApqwSlY5kfr8PNUUPL7U7uKspyP2jgt7uxle6BrcCaVbaVjnSEYpko1KeVys13qhi+Vnsz5VKabt7OE4TP+8FC3erjEFdey23YL6gG2BL1yF5rDx0VT8I7BKIw5Ry0OWv9uy+dUshCJaSiSxlSacohzsu50j21ZoSTQUR4NAPhDGUuxI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDEzNDY1MDQ5NjQsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJIZXlJdHpIYXJrIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTVkNjk0MjkxNTFiYzNjYmM1YTk2ODcwOTExYWVmOTQ4YjU3MWRlNGU5MWU4OGE4OWU1YzUxNDFjNmVjN2UifX19',
            'trail': '',
            'op': 'false',
            'speech': "Made by Dark Kryptonite!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
        )
