@plr = player()


@hero = associative_array(
            'name': '§2Da§8w§2nbrea§8k§2er§8Batman',
            'class': 'dawnbreakerbatman',
            'sig': 'TbP6Dh+DKdlza1tO5HoQSW/iEr23XTkwowIqBfsNywjAZacr9Hn/rrOK/tmBg/Nk9Cgz3uTlL4jQY+RvZIv2ZFQTKtgxXGa/JJmrIi+z4y2Fxv/QSElDWjNqHCPaI01z2iR7iJqsBMzqt3hWt+R/LWqvhuBIi9weF226DmhjhskfbV4iK0Q4CtAr1NY2klZ7iLjbUQUQftwcQo+NtbRGBbpr49mCrRjKJJmsgJIECZPTs2cZAj95qVhCWf+T2TVq1Zj97wwf4yaHO5MEIj/tLuE0LvTSeQWOsouwG+l2khQ8gVJXe9jlSTZg0HlrY9T4p/6gufn2llEpI5vqM6DXAlbZrz/nBLFNDOQ5VUhjyu9MdRUmWfQIn/buER7YVSIRtjYVOCEU5Mj3q6rDzOEs2OhW87bg+qosOB6Knp16jjz3qUhzx9PoH9HneXfFy7IfI4afn9Tuo6pxlSjX79raQNmGZrCrQeqsVy1r6u9RHdR9Y9+P6Fyo2YgcSPFiHxmmHlw4uF73WASz0MtOMHKnVyyb5Y2kgCU8lMTkSbQ9+I0V6K2MDI7LMZQ/zCqEXIXjM9KI0mb9JtrTaRtbMP453GM+poqo1NHr+J0TtbDXSXIFYITfeBAGsNO56u28Yym/2muu8S3JHZ9TRJH6wn2i7EnQV9yi59wojDY/aVuxqsY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDc3MjI5NjY2MzgsInByb2ZpbGVJZCI6ImQ3NzU3ZTAxY2YzZjQzMDU5NTkwYzY4ODIxNGJmZjc4IiwicHJvZmlsZU5hbWUiOiJtaW5lY3JhZnQ4ODIwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzI5ZDdiMGI1ZjQzOTEzYjg0ZjJjZDI1MTFmYTk4ZmI1MjYwMzFlNzUwNDVjYTc1OTdiNDNjYWU2MTQxNmYzIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "With darkness black,  choke the light! No brightest day escapes my sight! I turn the dawn to midnight! Beware my power, DAWNBREAKER'S LIGHT!.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-4",
                "/run 0-5",
                "/haste 0-6",
                "/flyspeed <number>",
                "/fly",
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 18 true",
                "/effect ". @plr ." 11 9999 5 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 21 9999 13 true",
                "/shot give ". @plr ." greenenergybeam",
                "/give ". @plr ." 95:5 64",
                "/give ". @plr ." minecraft:emerald 1 20:2 16:155 name:&2Daw&8n&2Br_eak&8e&2r_Ring",                
            )
)
