@plr = player()


@hero = associative_array(
            'name': '§fD§ea§fzz§7l§fer',
            'class': 'dazzler',
            'sig': 'G/vUQNPDx66bXJMofO7AsWfhV5iNgwl2QqPJ3uNwk84eCkTiXfxyXoIubr2q2wmuFtPIAY0OgCZ6SWXOaC7bDu7JLOOV5hc73I0prufoRicNcR2VfrilmlXK41IsUskM+XS6Na5lkZ0j3/GIJ7ofJ7dpxdcsQGdTqx+6NSb8nNJiubypaTiwBC8AR/T55sLYx/ptZkWKDkOu8ETiWHg8AMfYTa9RmCfJPPLcrl1MAUd6G54ct2eo83D4f1WHJJxGnaQAZbiJmKMyZk9xTV6sYY+JFbWjY5zXz2/CDf3y7C/g/7SBbNKvqdwaVfwApHLPj6N1bzcHpz77QimbmCl7MwLlW08jNfMTkNu1OjHVwv5OA1PLWrOXWaY1ndx2BjzRNzvhvbUoEinBxBOYfAxO71mmDdx/V1Hi1OirTQEKVGexjqHoaXQzK8cUyrnBpHL2+AjrFdU1wn3GqWJT4K9tgeKAgJXtZ2X7wRZcTM8rOPcdHaJHMsOeRswVeXwNh9AOQcUmJ1jRhThGkV3moN/l1T5tiJwhtCAc6Xk0bvsAjbPW0qqdpIEyVwCo88D4VxByNSKAZAL7PI7fCDYaFxeVtKzRMChmB8sXUOIgmWdSggc4B/f5dW4j1LQ8HgR92h+w/ul2uu+fatuzVJQlge1FWxCaT1trBMVh7AP0k5DeHYo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ1MDY3NTMzMzYsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2JmNWJkNWE4YzQzYTJjZTNmMzQyNWZiOTBmNjJjYjBhZTUxNzYzMGQ0NzhjNmU4YmNlODVlNmE3YzJmNmUifX19',
            'trail': '',
            'op': 'false',
            'speech': "Lets light it up!",
            'powers': array(
                "/buff",
            ),
            'buffs': array(
                "/shot give ". @plr ." whiteenergybeam",
                "/shot give ". @plr ." lightbeam"
            )
        )
