@plr = player()


@hero = associative_array(
            'name': '§fD§ea§fzz§7l§ferr',
            'class': 'dazzler',
            'sig': 'GqTSHbiLr6qGQATQJRigFF2LF29sZQcG3wuLY+BDaW4D8/B6DbLp2wZkJfo/Mgjn6O6KBQUa42zprqQy5UWUPfUqbsbfHRQGsMLk38uUFzZUPa/O0O1mIXlZ6d5jChjTEPsI2R5TXiemk7W+sC8jVk29hWqj+WGFtoVjwGjyHCrEuI98/nVCu1cvz598yoY/76aORSTKgal60Dvxoj58sBiR7jHmiUUh4icj6UM1l7J9gxJXEMDarHxoe6J+sp+O6bONR1C3Zo634qYeQGkUh5r3iQCL3p+0korvOhGV2ZBPAZ7qryrRFVDxlNhgiOIXjdfOmKtsQJsgyA/py6S9TDjXm+OcIOAzujpaaO8upaqFZRflOpZ2ssub032wcuTl+Bd0wtzs6LVQ8KfVNFNrjzRFlZegeC7GIphqJcIfqIA93zLFjD4uOe/MoDfYQNqjZEhyN0AE7EYt68QbrY8XL7MQK4QxVxse7aGqRmeoxrixWg4DyRi4FegO2u7go1wM0P8+N9NhV6mMBFY6NmlDOda3BshsHUUNP2D4/7fK146o3pDy6vrFMxBjmUK5qpqKLWxx/zK9o0BI7y5sSp8vddI/Dc7vAF0TbYFPuDit/kd9qN/hpgoaUlJwAFKZT1kfomG5KpCmq9tWPsOj+u5hVOqdyZLsewOIdTbadDhzMDs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODM4MTQyMzM1OTQsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzk5YjRhZWM1ZGZkN2ExZjI4MWUzM2ViYWE5MjUyZWMwMjgyZWU3ZWM1NzNhMjNkNWNjOThiNDM0YzFhMzFjMWQifX19',
            'trail': '',
            'op': 'false',
            'speech': "Lets light it up!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-4",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/effect ". @plr ." 21 9999 9 true"             
            )
        )
