@plr = player()


@hero = associative_array(
            'name': '§4D§0ea§4dp§0oo§4l',
            'class': 'deadpool',
            'sig': 'Qe/Zu/vAw0+yEwTvANY2rnQtktRy+Rvxit/j8tfTAkr76WXcyrqD6c+UEhfxt4q/AFidowyYvhjpCJrhQsN1awT0IJU/IgLNtQnbe2pfWYkyRmuZLJheu/JSDl64x4YZ2XLfMwwYCq7ZfJ/rCGiy+OP3aFVXYOG6dKvDNPDy0GiZWOFqWz7EKMnzVVO625ivoZoyOIhp5Q69N7mwbiBgoSc9Cx+hXFOjrHghxlNOkSBkmkHX+ByDtsbk/KowC6pwTpYoGC4Kvl6uGuGMLabnExcIERCFalXKk/Np0+6o6k9QfY0IJ4tjex19wzQBl6p4hda9F5jPeocAgqzTrCpqnbGWQfakXPGZMbEYl5bQ5bNRBw/9DmStpZLwAMbVyjfZfS15RVdkwHaNO0qZckKFXg/UOcOOa7FtrYhK/WMRlUb882drsIqOLvLC3Rewu6mhQuulLEz7BXFtXB9nPsIlL2fKAXcNAusE4Dm9gWKVXtHD9E5oHda5qKL033pN84zcbcFgCQMJKqcwc12AIN7W0NZ0UHdj/AoQRNHAFeweUwgAIrajCvBHkAscrmCA4BvE7q4voOaEialT0zxx663kR/d0Pxq/Wh7UgudQ/jbi3KQEl8bqbbrD8RYYH523acJWBBc7RfPj8K6+njoRZQ+jqUFP2zrIdJiKzKy3cyHnKZY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NDkwMTk4ODEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdiYTcxODkyNGZiM2E4YmE5ZDk2NzA0OTY4OGNkYjE2NWM5NTY3Mzk0OWIzMzYzMDNjMjcxY2UyNjhiNDEifX19', 
            'altskins': array(
            array(
            'sig':'cSUki2pVeZlWgMbQbaQ9/YvguF3W2RubW3Kc0GzdofxyW0bggHa6pGw5823kDa6quFWqky4zs21NfQ65rRCDqiv2jSf8CpWEy+fdwjbSE32Nk/RGeuGok4oXEgNlj9OCol/jilBrvgpxS1zr4zL2s6t7vmwEua1nCmW9QasBlYO79ZtRBHjqEgrn2iL3yKOMF2ohWJ7tm0bT0FIrCmGPLrYreWf7J07CTdH/K1cl9/EQJbQ/GDw2GLjj7K1YJoWwBkQL7O85tqnzyBW2wMnkbt6ZNeWJ1KBu3copso4mC07L/yc0psaJDZYPF2N4ZOpLZJPG9d7xwC9neyQZhN5fdieIsEwqZE5c3MsFYkKuG/h+M2Oe33rU7Uds33Ddm2ptJJADHGlbCmwZfJf06nBvt+u9dREaE6eJw4HsOG/sf8slwPdJG91Ye9VFmTWYWOur6ZI+8qzlBqT1l2v8qPVsXc9+eKBNMvBufrh+WHfyHba3DPvhP4hYKOeTEaD839EWcJcjb4iGp6HTYeYgBB8nWwnuNV8N4DVYgtgx28dbJ/bmVfNFymkCJjxaG5uWnITVcmo1NJPjmqs+bWDhNEUPAykktoqQjywBgIBw40ZcHcM1sSbIogjJnmw8drJVyJDMEDg2F3mFTHe/GTZS5FMe/lybdjivjNJtekHjxt1tBME=',
            'val':'eyJ0aW1lc3RhbXAiOjE1MTgwNTk3MTY0NDgsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJNYXJpZWxpYSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTk5NTk5NTIxNGEzN2FiYjE3NDhjODFiNmE3Mzc3ZDEyMzUyNDhhODJhNTY4ZWY1N2IyNzUzNGFlZTkyZTdkMyIsIm1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9fX19'
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "Hey ".@plr.", thanks for typing /buff, and for choosing me! By the way, tell your mom I said \"Hello There\"! She'll know what it means.",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-3",
                "/haste 0-2",
                "/bodyslide",
                "/tpradius"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." pistol",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&4D&0ea&4dP&0oo&4l's_Katana",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&4D&0ea&4dP&0oo&4l's_Katana", 
                "/give ". @plr ." minecraft:bread 1 name:&6Chimichanga"
            )
        )
