@plr = player()


@hero = associative_array(
            'name': '§4D§0ea§4dp§0oo§4l',
            'class': 'deadpool',
            'sig': 'Qe/Zu/vAw0+yEwTvANY2rnQtktRy+Rvxit/j8tfTAkr76WXcyrqD6c+UEhfxt4q/AFidowyYvhjpCJrhQsN1awT0IJU/IgLNtQnbe2pfWYkyRmuZLJheu/JSDl64x4YZ2XLfMwwYCq7ZfJ/rCGiy+OP3aFVXYOG6dKvDNPDy0GiZWOFqWz7EKMnzVVO625ivoZoyOIhp5Q69N7mwbiBgoSc9Cx+hXFOjrHghxlNOkSBkmkHX+ByDtsbk/KowC6pwTpYoGC4Kvl6uGuGMLabnExcIERCFalXKk/Np0+6o6k9QfY0IJ4tjex19wzQBl6p4hda9F5jPeocAgqzTrCpqnbGWQfakXPGZMbEYl5bQ5bNRBw/9DmStpZLwAMbVyjfZfS15RVdkwHaNO0qZckKFXg/UOcOOa7FtrYhK/WMRlUb882drsIqOLvLC3Rewu6mhQuulLEz7BXFtXB9nPsIlL2fKAXcNAusE4Dm9gWKVXtHD9E5oHda5qKL033pN84zcbcFgCQMJKqcwc12AIN7W0NZ0UHdj/AoQRNHAFeweUwgAIrajCvBHkAscrmCA4BvE7q4voOaEialT0zxx663kR/d0Pxq/Wh7UgudQ/jbi3KQEl8bqbbrD8RYYH523acJWBBc7RfPj8K6+njoRZQ+jqUFP2zrIdJiKzKy3cyHnKZY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NDkwMTk4ODEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdiYTcxODkyNGZiM2E4YmE5ZDk2NzA0OTY4OGNkYjE2NWM5NTY3Mzk0OWIzMzYzMDNjMjcxY2UyNjhiNDEifX19',
            'altskins': array(
                array(  
                    'sig': 'uc6ajWnofBWExjF1axV5OXO9QUKYvCO0GtPAsYVFnK/APiEWJh/ub3cnLfx55YpkTr4VaBoTUJVpUmwveEDH1fS7Py6Jnf2o4Sh+3rCDKKkDWnZS3s2kns0+bIINgGEJ9lI9s8F3NnljoKhzG0F74xtMon6taJB6cmVrAzN77rbm5l/Sra3lxmvz2oanmVxiooNmFjVkviRXXsCP19+aj/jzvdhxJLc4srCua/vrDduk3gE/uk60A4qotiehSVNiG0hSZdAps+Zy5IStVU7ijlU75oYj40siPAadXA+AmN8V6k+iIDhDJQJAhgEmPH/08ascOcROLSAHF6wHzKmZdaty/xsgm+en6lsB9VVnWINWu0yyzfO3rLlH/GgbkA3m4tuBlvBSbQUVELmVZ7KbTFjxF8gJKhaNdUtWMNu9S2NKHNOyj233glq4bQEt4ihwl/ofLytmZr0NOhBab/onQck/dq30Kf+Ta11MTFF2+jv9CAZOFiDyTYjTpC6Tp08nYupMKH9IKr9pehrmNdsUHbb7K8m1dwhG3pY5JTLSAcDitOGHYNfdA51YeZoBclTf/twEIE0aOLe4crjnQa1Scys6qBkf2KZYjzFJFgWx5nPSFOrn2lBv1LR2XJdwbZl9brQ/HdOGj3s8hV4lJjOZGRsTHToTHQbyBHLIPl5UrK0=',                    
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODc5OTM1NTQ0NzYsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJNckNyYWZ0ODg4Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mMmIyNGUyYmUzMDQwYmFiOWNmY2M2ZmJkOTJhYzQ5ZDVjN2Y0YjY2NmQ4M2FlMmVlNmMyN2NlNzNjYTNjYyJ9fX0='
                )
            ),                        
            'trail': '',
            'op': 'false',
            'speech': "Hey ".@plr.", thanks for typing /buff, and for choosing me! By the way, tell your mom I said \"Hello There\"! She'll know what it means.",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-3",
                "/haste 0-2",
                "/jumpto"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." pistol",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&4D&0ea&4dP&0oo&4l's_Katana",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&4D&0ea&4dP&0oo&4l's_Katana"                
            )
        )
