@plr = player()




@hero = associative_array(
            'name': '§fDe§cad§8sh§co§8t',
            'class': 'deadshot',
            'sig': 'QW/k0yZSHe1y47vNiTnmyE4KNXZEBGAV7pTTM2TWi+cDwPk0lKhHVqPxTyrbFlPpA2EY6f+A5DPJm64OOCOXjn5FIOxI0Yf5+WdjHNR4wylNmpcQb0cEMdWNmpxUh7ndOSVdhkIzu/bSMvhKGy/9Xh1rlYFyAjtD2jPsNO2tmfeENQPVhwGIMCRuF693u19y9IFJnNfjuzJ9MF/G8crGepwUlJ3zlftRozi9OodUQdOJM3bE52Wv1ATC3N2LhpuxKCdHNTw5ewpwNh3MNjgXlG+Ws+JmyYboI/3BdvNPOWDNmD74td5Pxw9/7TQvWznQKmM8GUzInVRs6PfVIEyzlyTCYJW1W+9VYvKFeQMG/CpcgHTx5BPOnoL/0uMmHYYiIoaXld6pDcTTppSoae82mSOk9WBIGQep/xKjY+B92JjACzMYnF1lfOg2KnFZLyYQ3xMyhYQB5jK9PnIejHHdPxyDc1dYozS+hdwyXhOTAHtjsWNCgxmQ1Ps9iHvnxLft/6sSUbIzQ64gsnYiklo1+sqJarh3n9Eqg6+r7hotbfAgc8grZILUyxLGrhWo59c5lF9PIL1byb3CxsgX3AhoQD6B8JwD9HxwYFcaf2CXTICoFdKqY7u149VGAxpxW5m0kS7KoLSO1oCzYHy/2/9aXoiokfa0lSAO3Blph8Phgj4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NDI0NjEyMDEsInByb2ZpbGVJZCI6IjIyMmM3ZjliNmQ1ZjRlN2M5NzE1ZjE3ZGJhMjJhOGM3IiwicHJvZmlsZU5hbWUiOiJKZHJvcHBlcnQiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2YyYjgyODZmM2E2NzM3ZjVmYTRkOWFkNWRiYTc4YmVkNmE4MWFhN2Y1ZmZiNDIzOGNkNWQ1YmIwMzllN2QyIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Another day for Killing.",
            'powers': array(
                "/buff",
                "/run 0-1",
                "/jump 0-1",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." AK-47",
                "/shot give ". @plr ." Type95",
                "/shot give ". @plr ." Olympia",
                "/shot give ". @plr ." Python",
                "/shot give ". @plr ." Gauss",
                "/shot give ". @plr ." Grenade",
                "/shot give ". @plr ." Hunting"                
            )
        )