@plr = player()



@hero = associative_array(
            'name': '§8Death§6stroke',
            'class': 'deathstroke',
            'sig': 'p68TiR3MaEj7/q02WbOM85/DMdC84s1GpyvlqN1SH1MTDNo6B90vJzDuscthfFKSk5Cf+4bJ2Git9o2AODWTDRZR/BtnTqyeUyBmJduUNyy6ZYVvg2JJ+7U6EHYwqEIjznctKq+25ioB+sLp17SoksAt1P2lNrgygv7jacMtE41kMjFfpSl47ELdvug72d0WxeX10mkSzdo6NJ2x4m0ZnDUHcJ6MlwCRaENnMFqdvOrWIbZdiVAhSddm/r/Rf5bijAHQSlUPW1bqHYKjYRipJuDPddOdPkROy94adoxgupijn9WgkHrT9phXADO8/yc9/7YUktnzR++ym5tjx1hPJWRA+r5rM78ADDs8hspp6UejZKDz0K0lyqUFJiKuG4h4437AJY5dVUOl3zP3f4PSWXf2ZfjIPeV1qoq1k8pA+jNB5MyK8VpSVwi21ylL+5Iu2tfsTpKhjEZp2EcbFYtFzEkzrmG2xxLFOqdPRl95JZ1eDvYqVoT7DQhr76W5xCfKwZOXbcgVtlNt/6D7lPQvu4y4y1R6d4txev9+a18tMJssOcMXVfIVWr1yl6SHp7M58OJB43o7tVuHjIdqMO1uf9ZIfvfZJTzGFi0B54nlv8R7Xrf6TnKTnzAt3L13JE+mP04X4AdOfHbCub/qIjphSQZ3E/zFwvzyNRt4crDuiKY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzI0MjY0NTQ3MzksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzMyNjJkMzU5NDg2NmZiYTU4ZmZlZmE2OGY1YjNkZGIwYzU1YTRlNTRkMzc4YmNlOWU4MjExYTE4N2ZhMTMifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am DeathStroke!",
            'powers': array(
                "/buff",
                "/run 0-3",
                "/jump 0-4",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." AK-47",
                "/shot give ". @plr ." Type95",
                "/shot give ". @plr ." Olympia",
                "/shot give ". @plr ." Python",
                "/shot give ". @plr ." Gauss",
                "/shot give ". @plr ." Putty",
                "/shot give ". @plr ." Grenade",
                "/shot give ". @plr ." C4"                
            )
        )