@plr = player()



@hero = associative_array(
            'name': '§7D§8e§8a§0t§0h§-§cF§2G',
            'class': 'death',
            'sig': 'rAamSWwgY7EPhst/8wOKaqZBzxnVOVANkU9QwnWh/9fJCF1RTlySIzi80S7ymti0e74hD/yp63b5XnD8qmaWGdvw2QatGUG0zem+9Ms+jJq4tzNj2Y5kKbVX+ZiCPewYqFdTvOwFGYJteiTt9wLbfeZIPHv6BX/7AatSEk6L7Vw3iXGluyKG4w+RDYULflKM3ZS6wpRIC0vEesLeo+6QUb0m6qXLni+1QFOM5EHys+uRowe9jtTNGZvYW1M/3SdoUhNjer+agE587qzw+aeCSBOeZpyPrSjajrUhx4QPUoNaW4QfMOR6fT8iSrQedDs4LmGb/mlx9EnrAKrUqp9T/hbDvLGI6iCUmwaxi9W916ze801Z6CdcHFfnYHZcEzd8bn2sw87jH2kswzyfjLPQK7B16+P8krjMqcqFvaXyIuC3ZdgnIeSYxXL8tUdnAEFCsMsTKv4krCv6tb6036PCeC0vJngeu98DfQYDR5Ojtbo8MEig4oYy06VPfM3YoQCaEbBa2jYG/vlfFIN91RRFETQWa1+81us0/pKil6rfFRW56Fj142pN46oVp2UsRkFDapt5uYOzHZSqspZRpiJ6MWOCaYSKcnUHD2kvBHbWA/JrPglp/v1D+RriyTGZwCRc0S4j0OO+jHyP4KV3D0YPfN4Hmb77mYxJKBJTlsll1mM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE2NDQ3NjkxNjksInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJfVGtreTRFdmVyWVRfIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jMGQzMWZhOTYwYWE4NTRmODY5OGU1NGQ3Zjk3ZjY4NWM4NGVlOGQzYWUwODcxOWQ3Mzc2NjJkNWFhN2Y4YmEifX19',
            'trail': 'flame',
            'op': 'true',
            'speech': '',
            'speech': "Death comes to ALL!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/gmc",
                "/gms",
                "/intangible",
                "/wheat",
                "/carrot",
                "/potato",
                "/bonemeal",
                "/goldcarrot",
                "/seeds",
                "/meat",
                "/fish",
                "/bread",
                "/wine",
                "/tangible",
                "/invis",
                "/vis",
                "/disguise",
                "/disguiseviewself",
                "/tp",
                "/repair",
                "/skull",
                "/spawner",
                "/kill",
                "/flame",
                "/lightning",
                "/back",
                "/top",
                "/touchkill",
                "As Death himself, mobs won't attack you as they fear Death",
                "As Death, you can travel to the Speed Force, and your powers shall still be avaliable."
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 254 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true"
            )
        )
