@plr = player()


@hero = associative_array(
            'name': '§0D§8e§fa§0th§f-D§8C',
            'class': 'deathdc',
            'sig': 'gTr2MqHu8rGgkcePFcbl/+4rw0NnO5xVTlijdBKwaZ2I9TtyVetNTG7EGBEK+nH6SLqEii7vmQ/q5hE3H8wYDAwvard0NjeoYEh4jRSms0b1/9fDlks3Yo5TAOGf0szzU3ovzY50laUohuLEMEr0cN5sTqTHnswXEVB0Nd3Q8mBTz8PCnKFNB9tH2Dl8KWdFOYz90ulp97vNPqCps4oLJgPAY8mLkwFxCiigtHRcDV6AO8inMctGdVbUhS3cTyB6BU1n0LMhzlsXcwC3pAmEu2Vx7fGOUnm9lugLtYjvmbwN622gIBojcwbubtsewOXhNhlDmlqW3aOJW5rinRqM1d3lZFqOlFpHUnlBnVy4Vyp7QjxzLUCs1A1DlO7XBj5prCNxNhKXv4VdcCeJHHrAhVmgJJLtF3LzAxuERgIIRH8x+uIbfXAQ/n7MhvsNP3P8jUldhWLAooDPQm8+SsWr2f/YC0aiOfttOTjm4wx1XPNNGmGWlB6VUAP+6D7C4bSYMkxrKk+ckZNALxjg77bWAz0qxiVLSLOsMkyRVY4D5gfAGr3Mn65XbtXhqOX8SDVEk2aA/2K2C5G4cgA8Bn9YyTSAfjq4oIpwRsq2dZ7hflxIoITXbHZ+Ov9CeSewLGYOvHfZka41OeMGj0FxxqFA5osUyTBdUnFVdcOiy51xms0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODEyOTI0MTAzMzcsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hNDdhZDhhOThkMjllMWI3YzhlMTYxYzhkOWExYTQzZGMzNDU2Njk0MWI3Y2JkYTdlZWI2NTM5MzU1MzcyODMifX19',
            'trail': '',
            'op': 'true',
            'speech': "Your time has come little piece of life.",
            'powers': array(
                "/buff",
                "/disguiseviewself",
                "/tp",
                "/touchkill"
            ),
            'buffs': array(
                "/effect ". @plr ." 4 9999 254 true"              
                "/effect ". @plr ." 10 9999 4 true"              
            )
        )
