@plr = player()



@hero = associative_array(
            'name': '§3D§fe§ck§7u',
            'class': 'deku',
            'sig': 'Rr7/xfIegrK1i3MbSLJN+C++70Gf2sKL5vsMIzlTSX/ujOYXKUZIdRcGXA3tq61Rj30tGiaYLUoBWdX/iIdAFQHvSUf4FVPyXI8Gen3Phfo8d64LhT+nRKxdb1/+WnC+jqJrtnwf8RudbnfUZ1FJ37nluNK9+2IYyBqn6+FJRT3ALF4QlXWVzIGwO9X+ds9d6p/XSXFik0RWgalQw3kqTLEtXAD9LBpcYBO/erm39dnYkY1mQb7PMQfGaYq2W6gCNiugc3OVYVk+/DGCe8PqP4cZi5CWZf1ya5HhKKjMmHqT4r1gtxx863XpJBMMtmBMBQ/ZFrQScRfsz892Rc5JBRFR+GKXzZUnn4NuggdMJbaHphok6KvGwvFCR4KhHnr39eqY/GxbBIrrfTHxTCgRq6NmqiIuFbsETlfRk6dmV7Et8wcN9WOTKoOHh0l9xsZZoWn1cW1JebYsYGjoa/fb2iVJXI8pgUUi4G1yzL5wouwTM4oeZ3atNaU9I2YdiDxMQ/hzSDj4J+fq0W8sw0jL0qK3mOpWoeKuH9zia+GJinxPmpj67Sc9WDjbXbXymYx8ASIf6GbKxyfT8VM5OcSXIvDVHjgpKWOsmYa0uRNGjiJQXRW7gx+cJulwodihNLEoUUHo12KX6qZ3UzWYVvbqHeTGkzwI0d5l3Ihr4DKPMpE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTUwOTEzOTQzMTksInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2IzOWI5ZDhmM2ZiMzIyMzQyYWVlNWI2NGViZGUzMjFhMWZjNDQ2NmM4NTViYTQxYjVjMThhYzM2ZjE4MmZkIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "My deku means you can do it ",
            'powers': array(
               "/buff",
               "/jump 0-6"
           ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 6 true",
                "/effect ". @plr ." 11 9999 2 true"
            )
        )

