@plr = player()


@hero = associative_array(
            'name': '§4D§0e§4l§cs§0i§cn §8R§7o§8w§7e',
            'class': 'delsinrowe',
            'sig': 'hkNLaHgWG+9LtiKOYN6WI0NjMWOLT1Fcu77dEQMiR3lObkWyPaDRJSkqzDbLHZmkEAL19vXYn4LnHUTP4VGJi5TcJ7mz0q2mI1NLGGEa5Xno6rs9izx2p11sw9wGW973ipzctDqdVKxHZg681RzxyhQ+4EOvdSLVzvP6dX5yVsDIHC6jPO/fd/iXsem+NskumrZmrOxmqJsPHlD4JDOcqSPBZI2SZP668vGvVKrlG25zNsDJHMawIdwk9/QX2uf0XujFhkDzWZoBbzoU2JaP9Mt4AlNij1cQc2UDN3JPG67P227ggRHjDryT4JCao2zmaL4M3GVJA8vwenCSq5ymAoRa2XdBDLXET8UkT9KEjcb9fsHTbKHgKs7qXwogStH4w1yfrT2WpNZD3mEPaOOYr7/7ZfXbfCV3/w7NYqkQvcoXEjVoIvLE8QZq8vTznOWh9jIDXQmNQUkHNDmWAEr/+C7NcKdFWQWOdDtM8swPnK4isIZY9FPXUO9+Dd8Fn/JOhLBTVbkkGHK+hcAtwYbAxUzTiR8anvaO2yd2jOXoGIHole0gaLhEiFlFNMdho+aYTZxH4jgqHc1Q7ssGwgcBABC0P7U22p4gj8rhiD5Cq/EKSIm7/qNOSs87XZI88P2cuYSTKgpL9/FoLI7qDDS48FRP+lDPJahF9uKvb8U0bqg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODczMDA5OTg2OTQsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJVbHRyYU93bERDIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mYjZkYmFiZTk4YWQ2M2QzNTkyMDViNDQ2NmJhZjczY2ViMjZiMWI4ZGU5ODI0YjM4Y2FkMTQxNGQzNDcwIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Just because something isn't normal doesn't mean it needs to be fixed.",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-3",
                "/haste 0-5",
                "/thru"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." solarenergybeam"   
            )
        )
