@plr = player()


@hero = associative_array(
            'name': '§aD§2e§am§2e§at§2e§ar',
            'class': 'demeter',
            'sig': 'c+O4z2CSonwhDyR+tLaDIRVKufJepLWk3p6lxPEoOJQ+PCR7CD15WDeSqD2uJT2NX+upV3uwSsDgAxNXAMOrH6uYo5Kxs6cY1I3J7YegOR/sXV0qdpmv014ULZD6Ug9u7kem1DJiNqgp43vxYwG09NY8TeQIMmyM3YPw398zJZWB4pr08z4qWLZjk5fldHbfBU5/jxtm9nUDjHXft1l/hGL19CVqZF0/f/0/AwCMEoyWQ/2+EXLjE7mWJZMAw8r33cwUlbU7+6lcOJR9uT+lyZ66RiJbpiIA7GAFiJm0WRowYBB7+Y41EMId44sxoMNsMyCY6ZLXaWZD792OH0bVrcJp+C72H1mlLCVQx9JW5ZI5ljkF5RiXaE7EfLijVBviO8HNWIBIW/DJvOT0fkDyN9YI+nZpVglJ0PwaZr9QAjTPA/byj/+qaKAvB2hFiE/Mh7yYs8allONRCEcDV9lZKHo6jITLuoj+RPhFT791HegAYJSjXuCqM6Y/8d1/V5VYsQHsqj6mp7M/5F5MC7aKgZTMTjlniVvwr0owk3UKWJGkDyfdLy/SfbkztFJpwrgeXbTVjouOFitEs9Z6piSww7evdDJgRe2UbnzcSpLg/zwQMpbf3WgQBPmKS5h+6qobwHjU4+C3hTVISIjHkJHCCFcFH9z3jJXPLH/5b7Z0AKQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjU1NjcwODQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS84MGQ5NWQ1MWRiZDM4NzJkMTE2MmE0NjE0ZDZlNDk2ZTgxMmU2YzViZGQ2ZWZmZDQyYmE0MTQwYmQxYTQ1MiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Goddess of the harvest.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-3",
                "/wheat",
                "/carrot",
                "/potato",
                "/bonemeal",
                "/carryplayer",
                "/dismountplayer",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true"                
            )
        )
