@plr = player()




@hero = associative_array(
            'name': '§5D§4e§5sp§5e§4ro',
            'class': 'despero',
            'sig': 'BXUROZxOXua0fQJgL9ZbEcJc4lmV3ys6kAv22OElfbUwdvMghx8yc0JU8l/U8Ukaxyl7SAXSvxZVR4C+jPR+GzKGCwKd896tGKFyS4sQH0wwcdpveb8RHcIxx7wOM6V3Kuxwxbpb0essV5yGZKYA4PJmqz7khzEiiIlj8AFGW37VicMOpgFw0rVQG7wXOv5VYpVESQQsm1Xenbxl1jHqrcT2+FAXnsA72C5Du8cStTzRMDtA2i1xvoF/lBWm4bbvvEMQKS0SbDdEVHLr9cZumgBdS3OpLXYZedaMEdwHF7f+e7tsvpgGKUmKM8GX08kDK6ab0Agb27C+aQOPmCnurazZlPHfqGiLy08phcz9ZdYwpLeU/qYE+EDpKZVIsFNYNmIiD+LQIK7BJekO2mk5ILoUPDW0Q1FxZckpGYCcOaSMonPz+2ZN7zi+z/+pP2t0EVX6LKZmMrMfFxBAzSnpBIZN6Fc+QoWe0zKAMjDWylaB2WzbHedN8igQfbhNOpMRZHP0ZKbYcC3Olbs3oRyUPwiGXqYVLricKL+fj+pamtVAy2Bm+ZGNGcfw5lujDLlU3O77+QZ+Ds2Uex9/zSSyP6f8ox+8MlEnSZpBGV+4cvlVx8gP3kwsd1LtA+pBLC/TDLLii/CIrjYuUPyZ+OAIJRFx0aH0ZzWwECx2dJIgs2s=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODUxNDI2NzM2ODksInByb2ZpbGVJZCI6IjI1N2E0NWQ2N2RiMDQ5MmQ5NDVjYTAzMGY0OTg1OTMyIiwicHJvZmlsZU5hbWUiOiJCb29mdXJkIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81ZjMyNzhjMjNhZDJmNTZjOGI1YjRjNDIyYjE5NzRlNjgzZTA3NjY0ODU1ZmRhMTJiODQ4ODZlY2E2Yzk0MTEyIn19fQ==',
            'altskins': array(
                array(
                    'sig': 'OpPKaZRX0N5e0exKDl7eBQWrW+nXf6zMvpLm6gl45Ryot9MpfwBDKv6T2LsepS9Aq0vaJDN9Jt+nExCXnWXC4v8c5PrfrbP8NBJte/kmUWq3D2H9GbGoslf3Vh8fowZFPBYpFFgEfb+4bd4muVrfHRpiZBRHee502fCkkFpSsplaIw0dZklWbwGsX2G6PwxKh3YsJ2M2suq7E8jbkIlg15Z3sKPgkQUKEoAJ/uvJGVcYhtkLlT+eTyb+cKNAwptlK7y7kSWzW9mnBi+dHwqNWm+ipCASzr+ZtdLpJWPJJaEinyLmlHzO+vhOg1rA7Abjp4BnQe5A+nq/u4IUHTb7xB8Ac2k4sopzC2Tfspk/Rm3Ml3LuK7snAbvq8fyZcK3ECkgVeq7vT2WfBVOznUR8exy42U1yWagjYdzMYkkIvnXIHxVK4D9G0dtUANy0OaXoh41CuSm1ImkertWP5KUG99+kcGRG5Xn0oZeBQsDSdEfdwp77HB08mCMNBwkD3MYKGuymVoxICEYPlHuMLX5VTAkJnVD/FyHqISGNiX5yEcfJVDOdUbqBrUWYcTKha1oRaOaDWg2c62SN8KpTk5lv7jv9yc0CkPzNQNk0r6wKGuWqAjd5/HkWe4GAIsCWzgA5Bd1o42wJmp1z0ed6zjQJBvYTqyvLskqS3y2lt23dnm8=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODUxNDkyMTkzMzIsInByb2ZpbGVJZCI6IjI1N2E0NWQ2N2RiMDQ5MmQ5NDVjYTAzMGY0OTg1OTMyIiwicHJvZmlsZU5hbWUiOiJCb29mdXJkIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82MjIwNzI5NmE3M2U0MDUwYjNiZTgyZjNhYTc2NDRhMjBjYTk1NTU4ODQ3YTRhMjNjYTI3ZTQ1NjJkNDE2NSJ9fX0='
                )
            ),
            'trail': '',
            'op': 'false',
            'speech': "I will destroy the Justice League for what they have done to me!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-4",
                "/run 0-4",
                "/haste 0-4",
                "/flyspeed <number>",
                "/fly",
                "/speak <player> <message>",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/confuse <player>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 24 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 24 true",
                "/shot give ". @plr ." energybeam"                
            )
        )
