@plr = player()


@hero = associative_array(
            'name': '§8D§6e§es§7t§8r§6o§7y§8e§7r',
            'class': 'destroyer',
            'sig': 'IUTREc9CwxYiHCU7gzkhvaqdQaDebsn8zqP0QSgeFYl5V9Njd8OhcCSzKU04PSdis4axa1cfaB6psESn66cOyU1hx970L4Ma/dBZvdRVdpgIPCHEwoMRxlRo3ia3VuxIQZct/2MLXy35vlAdlxYFablZKUldOnVuFK2hiaS4cLfCg1XFpnYoeTRYhR3M/7BSB05uFN5m1Q/OJgchaX8+eYfDvW7aEBtDrVp4EX8v/s9Pw8slyHW6V8zaXpMWVWEoWWQIpE9A3WWqOqyr78QOQtz2UdCikectNEbrI79ZFpOhZTuQ56TrIycDKj6Y9aoWfcleNCHHjmhVr2wNli34nnZYkn6HgXxexkg1af2Y7pe/Uzz83qaAIf90t/apih2zyJpkia15c3H0JUtTG9SQjPJqCuOAa+Op5iJpZvhZMeyX72Hsw4DdDzA8ahkTbNQ6kEQQ4106ajLBuA7d/oxLkP013n+KHbAAeCTll5Cen1GB4TDfjZSIqI8uOYP0qZK8mU1kgVGgUdAy5pq549Ly8IuYFHeLSYRtr/lnTVimAXCY/sIFY9CLi6SUd3xhxwX67Wnn9/Ssl+KuGrJO9shzUyx1kOc5ZlqVHSUq8d/8UtVjKhmQia9PKuYdig4iy3naeS6PDzFl7FVzVwObxrgHMOVZ39dJTWixICPOpSWk8xI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTYwNTE5MzgzMDgsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJ4TXF0aHkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzhlZWI5NmEwZTU3MzYyZDBiMjgwY2ZiNTk5ZDQwMTFkZmU0OTkyNWM5ZTI5YmViODgyODU5MmI4NDQ5NSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I do more than live! I do what I was created for! I DESTROY!!",
            'powers': array(
                "/buff",
                "/carryplayer <player>",
                "/dismountplayer <player>",
                "/cast crystalshield",
                "/cast crystaltrap",
                "/cast moltenbolt",
                "/cast solidify",
                "/cast liftmetal",
                "/cast telekinisis",
                "/cast destroyerblast"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 14 true" 
            )
)
