@plr = player()




@hero = associative_array(
'name': '§8De§ftect§8ive §8W§0e§fst',
            'class': 'detectivewest',
            'sig': 'TYSRAaPeCdbf1124gpu/Wh8R0b99baU6gqMlzdWjEmz+kXh9aWTHjl/jye+iduCwqnugql4EFESwY6+4l64ZPedIyIA8zEZhIcM25/XcUCEwxw4UTCkh7ERQrC8jgLw+Kt6Xm4CRZ1VD1/vlygOLet4YgMZEUwVRaGDk75i7pMXoyOqmApvnySbbJ1MqL+8NANGoX9qCXRs3f8wduW6NJq3YjKMugPnC2g5a5fODtdqIvcB0RU1o2HGhan0ofaztog6O+QAB33BN9tfoqMqWSpTkRA8i6jYxTdUc8G5D46Cjca5Q3vYLj2ohR1n9kyPl1gNU56L0VQWidACTnpj0C9GNAp+xL3Av3GwSgzZEZ79oEvc7/PnhtXNPYSuRQ4HMQH934KbAP6aMCeBZQ/Ur7DMXVNHi++SmRyEd32UacnwZQOG3EOhPmxBq8JBUEZBjetU6+e7zT6oQEkSeiQ+Lq0xPXfAatrrJOa7Qb5VGcTqxnw1KvPoz54C/8ufscVoTbkSeMMdIpBPJfmqaqSSaDSz3iCCXWcgsHfhICBYLbGcl2uC2YV9hanu3uidfdXusGXg6zh3G8c9vG3+asSFYtW6Gm//xeFJ/K4m+cgZ4FDI6JmlpbHw0LEyd+yix3ZD/nNyXSIyO3xm39z2qzkH9zM3sMV6Xo9UanvdY4fkjn7Y=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDc4MTA3OTIxMTcsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJIZXlJdHpUb255Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS84OTZiNDc5MjZkY2NjNGFhZGE3YzRkZTY2NWI1OWQ4Nzg2ZGI2MzU4YTU5YTkwZmM3NTFjMTkwOTllZTc5N2MifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am Detective West.",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/shot give ". @plr ." pistol"               
            )
        )
