@plr = player()


@hero = associative_array(
            'name': '§bDi§fam§8on§bdh§fe§8a§2d',
            'class': 'diamondhead',
            'sig': 'g7VoaCJXgjp3t6r4f6y8FNyZOMDRFZ+QEQKd/euKqJTdqG1kbcDgre9QxENAnhcGI8etlxwd32NAOEEi4y/IWZY2y3FLRSlHAQfq9YVXG+0wh8UX1Q+WIBbaeymYVUQORw3CCVfNDTe0sloeKGLgK+9dH9hhdgs4T+ZhWqiNe5L1+ozNTmwUKpJvWA+1uRFwJtPns91Bvo6xY/Gpy+OyPpB8QEAur/LDLv/G9rLyeuGvTHEz9+K79J2puUWDcucjFqm+p7I4fHUcQyLhsM8qcWn5UpVaBPI4MGxnN/qtIABBmyrCl4e7E71Ha7LLj/F4YgNeIBCmqbXO/DHydMSBhYOu3pasbqHuuk7yg6WXUGmEms3Utqg+6mw+e1lxC4ynLSQFegGr767wfALEJmn1le9cji1qvpjnnF/lu7VN0RldItvFX/N/U7qhMQYsK8JlqsdR+OCKCjVCQeqEBpTpLyH099qQXL2VqLOyU0LTywh6Y5yVU4Vzjh3Ps+e+UBQAAYrfo5KR3pBd8wv6y1SCSSzf+qxTS/r0qwkyRgbdj3iQgEiOVImUUCwNXXUaWCMbUHXWcZbxoT+/Wl0tXo0kXfiz94Wrvvdpif2jTZRvNc7ZeSkruucfxkBxXW4UtLg+j/EJ1ZppgXvqdil+HkjnFwc/XyQ3YdIyrRpZEkUrlPg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTc3Nzg3Njk0NjgsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzMyZDNhZTE1M2RmNjIzNzU3NmQ4MWU2OWU0NjQ0YTYxYmEzOWE0ODM2ODU4NDkzY2M5NTJiMDc0MTBmNmNjIn19fQ=="',
            'trail': '',
            'op': 'false',
            'speech': "",
            'powers': array(
                "/buff",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/give ". @plr ." minecraft:diamond_sword 1 16:20 name:&bC&3r&by&3s&bt&3a&bl_&3S&bw&3o&br&3d",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/shot give ". @plr ." crystalshards",
            ),
            'alts': array(
                'ben10',
                'heatblast',
                'goop',
                'alienx',
                'fourarms',
                'lodestar',
                'xlr8',
                'bigchill'
            )
        )
