@plr = player()


@hero = associative_array(
            'name': '§bDi§fam§8on§bdh§fe§8a§2d',
            'class': 'diamondhead',
            'sig': 'Tw9PIX9WjeQIpKlon38bt+Ocl4dXBZ5qrW7Wvv8q7k8G/ankyfNqGHYF22+0pROtdStUOiP1Ea3aIAlUGTZD53A0ODQarGOoLjGqR1xXdmx7uhGdhrLGpLc/R28QaIKe2jQCE9GmQXes1dzKDZyXzVsTHPTQyFSjtKQ8g49zhpTgH+pHWMKd/LViAWGSAODCDfsxc/wsQIyyrIvWXtMV7l1716PnJcwgVJVYpgaFu6InZWk93YwGZ+3FVxVCPvTJNHFWXkD/mxboWIU6z5xPIKc3QFZZcG9siI+GXwSqjq7tmR9ig2htDZUKTlvz4wha/TEqpX2tBFjqCBXp/1244OPthcKAa2ehBbpYaephnIEvMMbcnS/WnAo4cSlsXM5L8My/PMyIeba+vws9p419fe2u+D/K6PZMhob/5K7uR+yRuCWF+uAagH1xVvnLGv7DeHinCVvkjiqUgixoSNEULY+j1/FzMZgAKqyz6bJygyld4qucufx3N0Yr3/uiy5KKnYu6AliSXtWqs0rvJ8urDRYYQ8Y4myNZRWd0t++APRyHMPlc3IWHvRx1Y0zEzj4AS0gGgdXXfMolhAee3mr9+jH8yNshl8sYsSXOZethzHMoldYYmw3plL026ALNIHxUKuYhKrtlqWe9JFdTfrYSvQScPthI3YHS+zcfQnZuKHA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTc3ODI0ODcxMTAsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzMyZDNhZTE1M2RmNjIzNzU3NmQ4MWU2OWU0NjQ0YTYxYmEzOWE0ODM2ODU4NDkzY2M5NTJiMDc0MTBmNmNjIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Cool! This rocks!",
            'powers': array(
                "/buff",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/give ". @plr ." minecraft:diamond_sword 1 16:20 name:&bC&3r&by&3s&bt&3a&bl_&3S&bw&3o&br&3d",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/shot give ". @plr ." crystalshards",
            ),
            'alts': array(
                'ben10',
                'heatblast',
                'goop',
                'alienx',
                'fourarms',
                'lodestar',
                'xlr8',
                'bigchill'
            )
        )
