@plr = player()


@hero = associative_array(
            'name': '§aDi§2on§ay§2sus',
            'class': 'dionysus',
            'sig': 'cHaif1orTLpnAbFjlzcLYhl4SPVyx48fLf8y0qXpj5ly3K5Z1Jdf/PWzW1T1Qr2D7+GB1XL52GSZAWVAZuCDtwRXy62YYksfl6NxX9V1clltyyNErV2WRL8QyZbZgP1euiNnkCRjVR6c9fdD2Yl59qWymLoVzwC/TV1fcz1kdpeLF6+yKHjOOsWJxB96AsB0MVPL5uMiiAFXyDkG0p0OgXwF/tGQTUAviXyDBtt/zzNyOSl/WFvytx9XgxtPhx3GsZmYDVgb38uZI5d3tO9mUFSEtAa5jaXin3fUAlCHdG0F3WTq5LVGwfYbRsjKOW+UDGDyU7CXEL8xf0acy1Dpa15Se4/MQ7ed4/dvyHtQ1FYCszxWop1X0Cr7zfUINJbMNxZA25ULUtU/zpXhRIL4wUOPm6Q0qoVPvx/NSNUDnKhLYaf4tLPa27v/MUJWqY9jWgJ2/Sa8MqldawEWOYvwF7kAeP/v4dvTa0FhsjTbDgS4JLVOruRdux4S+moGCzsJ3AVELBZ2vgubIyQ5WDRSmzOFtacS2GDEiY0hGNAs7uKCrZOGDv86+FdQRZmDL9Io/P3jZioT9Eg4FT71CSCNaojOWAZnx/c8RRCz82gGicSBNmKvAIfc3PT5QmkL9XqU/bQFJvcJvt3v+/2UMcbDFrlLzsdXeSyi89V5ko9S8xI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjU2ODg4NzksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzM0ZDE3Y2Y2OWEzZjRhNGEyNzVkYzI3MjI3YjgxZDNlNGUzOWI3ZWVhMWUxZDBiZTYwMzIzMjkwNTdlZDRhIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Goddess of wine, fertility, theatre, and religious ecstasy.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/bread",
                "/wine",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true"                
            )
        )
