@plr = player() 
 
 
 
 
 @hero = associative_array( 
             'name': '§2Do§6ct§2or §2O§6c§7t§4o§7p§6u§2s', 
             'class': 'doctoroctopus', 
             'sig': 'vpwXv1PQohXtoMRQSHD7sfODVQPaZhsTdZ2Kaq9Vn+RSOV+JNuLlvjQz8EjdGqsFBus485d+ONc3mbPFLeX9vHAwH6HXx/A1wTcmEXczwKiW21t/EpZ8FvgvkHUxIOQzmNFrid/9VPjJjPOHSFmTO1NS5DqQ1nZFkAVEPoXl5nbbHhNfc0tO1VXgeJMZ5Fn7eqVTuJ0BCrL+jPPmuw+866PZ7ioqplLtTPLzSl+YkYc4bMYvuzWl5mM0aTCJGZfFMV3ZqPC33SvmMSnTN8lonqbgQGFHyMZZNtsU29fEi06QUebS06uCm0HeXiz7+fjQvqrKf2nvsgfAmoRI12+S3+TLpaYUSmjNxFpC2coXPBR+bbafsUnVtOGyGTGX1U/r8MBdevWwe+pYwgV2A7Uj9dfYdverS7YnuvdtZQ7nYRkZIhqEgRCgds65yEYKwmDyuzjvctxK95zGpWlecMFeGBBC0TgM2G4MJxO98d5ZyE6WsYy+vZu4XxvSiRZxs0UkDHW56ivI5HnJsWZMiFBBRLAfg9r15q5lFHLaxluKQikXHUspE0ttZSvi7YAyVFkWvmUnJln3dtuPXhYAsjB+7PO6/HkwNhaAIpB/P+3YAOdgvcek8hYfcW4w7VA1a0JWP6T8AIbMcaFNSzYl/V8RRlhN5BSQiYBOiSw14ONc98k=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE0OTg3NjExOTYwMjYsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGNlNDM5OWVmYmFjZmNmOGYwOTc4ZTYwNDI5NTJhMzhlOGMxODNlMjdlY2Q1NGUwOThmYjM3ZTRjZGZmIn19fQ==', 
             'trail': '', 
             'op': 'false', 
             'speech': "With my superior intellect I will finally destroy Spider man!", 
             'powers': array( 
                 "/buff"
             ), 
             'buffs': array(  
                 "/effect ". @plr ." 21 9999 4 true",
                 "/give ". @plr ." minecraft:fishing_rod 1 16:50 name:&7D&4o&7c_&7O&4c&7k's_&7Ten&8tac&7le", 
                 "/give ". @plr ." minecraft:fishing_rod 1 16:50 name:&7D&4o&7c_&7O&4c&7k's_&7Ten&8tac&7le"                 
             ) 
         ) 
