@plr = player()


@hero = associative_array(
            'name': '§6D§9o§6ct§9o§6r F§9a§6te-KN',
            'class': 'doctorfatekentnelson',
            'sig': 'yCAcklh6rB5De57WWOEb4RXb1dvH+k5qzoAeJtc6vAQzQ6kYo9yMQCSaDpSdNjMEqEOCVm5BiMSZWDr0Ylgx0e1xwzePS0PRpqxjvCfbJYC1Aa61f2KiXqR3FxMFe/0MAafwN4mQWkrEEhzuYkUmA+F9Xk2ZYddOMBhvP3DQ/1/ptR4QtbC0Ru1VF/mQR9RM7imred9GnqO/3kN9HkXfNiVRdh1T8BMxo/9W9s+RM+wFQVOstaGuYYhT4B7sn6DB2IKaLH5pFELg0x+LvZTP/Hmj7KC8dFKZHzjMUNSDs6hQe4DnQmGYbErjYAmvSiOiH+cwQxe5DRdRA9YYFS7ois4TDDtjx0rlMnkHeuQrwyhZk+BRrHBKQMThgwHLCXHYwVTI8dQnAKCaSlA5pBWboOwrrxzROAmBBLcBD+/Y3sMIsUByrQnY4f4kEiyqYZd+uz4zK5euB5klh5kMy60OHhiTC21xzfkrGynaBgesKrhSRi68M5O1aP7Ko4GNzho67FF/zOJWhD0O0Q0LoDTpJDdMinyOjhNE5SqnBTmP7S0eKgATc+Sw7DjuPTI4BBiEJrMS9RzMqOIj31N2axXrFiCd+/3qGbLyP26NrHTYuiFgGmhb4MxFpZ8t3gkxH9sG7JuosnlTm5tJ2ADepWQl99aiRifCtGPk13FU7pBCxXg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzE3MzA1NDU3MDksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzY0MmRmZjc3MTgyNWI0OWZlNjNlZDYzNjUxYmM0Zjc1YjY4ZWUzNWI2YjlhNDUxODAxN2FlZTU3NzZlODgifX19',
            'trail': '',
            'op': 'true',
            'speech': "I am Kent Nelson, a.k.a. Doctor Fate.",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-7",
                "/haste 0-7",
                "/carryplayer",
                "/dismountplayer",
                "/gmc",
                "/gms",
                "/fly",
                "/fly speed <number>",
                "/speak <playername>",
                "/intangible",
                "/tangible",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/invis",
                "/vis",
                "/disguise",
                "/undisguise",
                "/disguiseviewself",
                "/tp",
                "/heal",
                "/repair",
                "/skull",
                "/time",
                "/spawner",
                "/lightning",
                "/weather",
                "/back",
                "/confuse <player>",
                "/top"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
