@plr = player()


@hero = associative_array(
            'name': '§bD§3o§bct§3o§br §bM§3a§bnhatt§3a§bn',
            'class': 'doctormanhattan',
            'sig': 'jvRQbVMc9Cgziqz7KywUxL0TeTV7/op88ZgfbywriuP56RscgaxCR6j1/Ewv2I5maP8rCEcA6UBEUjbeNpzbUdDmVZsN2fNDnVZ6YPdlbAwNT3Cco1X37rzBvC4n1RbYBDTyiRq6N3/J9hPDHFqBZslf2rWhypOgzQCQEo026HNivyntRHwqqkpkOcUv2sQgTOHPpeamKru+8F2i6OdndHiHS4qqJ1CVY3LsowmY7eDyCOXVRbkhtjzvmQ/7YiMKthVriKpLVk9pswAKi8yfRgd9ov+7UZQWP99lY23JDmkGsJkvwINdNOJxatgBoakOaMwUQ86AJMSeViIOFm0cQ2zDPy1eesDEHkPfiJtp5XVUfhvH9L+Bga3MJznSbe0QspT39J0hZ1VrfGALBf8rff7GXFY69Ge9KRFsptowc0OkMqeHh1IdEIjSP0RJXTlckGeIdIkF0GRw8VHM6mvn4jlcg06BLHnhc79Jx1saVQPQWapP8O27YIZVG2ZCgQIgw3gzfbdWqfqJPGuob7nWUhW1djVOFkP/kFp1t9MrG/phClEwNmybQwrpk0VpX61Ms8cUEw0L/owwqePuzB0Hkh+v6sTgMCAk8FaElYZ9e4IVbeCMqKesNMO6voI001N/dtX691FtByLnTMAqLKZsBAfn3k0gDIor5zVlNzS1q+I=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjI5NzkxNjEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzViZDJiZmZiZTdmZGMxYmFhM2Y2YWY2MTM4MTc4NzZhOTdkNmE2OWE1MmM0MzMwMzZkZTEwOTI1MTI4YzFmZSJ9fX0=',
            'trail': '',
            'op': 'true',
            'speech': "The existence of life is a highly overrated phenonenon.",
            'powers': array(
                "/buff",
                "/kill",
                "/gmc",
                "/gms",
                "/tp",
                "/fly",
                "/skull <player>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 11 9999 4 true"
            )
        ) 
