@plr = player()


@hero = associative_array(
            'name': '§6D§9o§6ct§9o§6r F§9a§6te§8(KN§8)',
            'class': 'doctorfatekentnelson',
            'sig': 'yCAcklh6rB5De57WWOEb4RXb1dvH+k5qzoAeJtc6vAQzQ6kYo9yMQCSaDpSdNjMEqEOCVm5BiMSZWDr0Ylgx0e1xwzePS0PRpqxjvCfbJYC1Aa61f2KiXqR3FxMFe/0MAafwN4mQWkrEEhzuYkUmA+F9Xk2ZYddOMBhvP3DQ/1/ptR4QtbC0Ru1VF/mQR9RM7imred9GnqO/3kN9HkXfNiVRdh1T8BMxo/9W9s+RM+wFQVOstaGuYYhT4B7sn6DB2IKaLH5pFELg0x+LvZTP/Hmj7KC8dFKZHzjMUNSDs6hQe4DnQmGYbErjYAmvSiOiH+cwQxe5DRdRA9YYFS7ois4TDDtjx0rlMnkHeuQrwyhZk+BRrHBKQMThgwHLCXHYwVTI8dQnAKCaSlA5pBWboOwrrxzROAmBBLcBD+/Y3sMIsUByrQnY4f4kEiyqYZd+uz4zK5euB5klh5kMy60OHhiTC21xzfkrGynaBgesKrhSRi68M5O1aP7Ko4GNzho67FF/zOJWhD0O0Q0LoDTpJDdMinyOjhNE5SqnBTmP7S0eKgATc+Sw7DjuPTI4BBiEJrMS9RzMqOIj31N2axXrFiCd+/3qGbLyP26NrHTYuiFgGmhb4MxFpZ8t3gkxH9sG7JuosnlTm5tJ2ADepWQl99aiRifCtGPk13FU7pBCxXg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzE3MzA1NDU3MDksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzY0MmRmZjc3MTgyNWI0OWZlNjNlZDYzNjUxYmM0Zjc1YjY4ZWUzNWI2YjlhNDUxODAxN2FlZTU3NzZlODgifX19',
            'trail': '',
            'op': 'true',
            'speech': "I am Kent Nelson, a.k.a. Doctor Fate.",
            'powers': array(
                "/buff",
                "/fly"
            ),    
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/shot give ". @plr ." orderbeam",
                "/effect ". @plr ." 21 9999 4 true"
            ) 
        )        
