@plr = player()


@hero = associative_array(
            'name': '§cD§9octo§cr §9S§ctrang§9e',
            'class': 'doctorstrange',
            'sig': 'sKLXddFVzgq1IhsWXfuDllDcJAVcWkDaDIrTV4aEQTXRnM52SpAezE5uI7fzLxU0RLSF81HCkzAhQUhsd521HEv+YAdmh7xcATT9JTLWB8VNx1tjwcPatmiSmVzhZ3JZ0GxkZOXYkhnc/6nGN9JdKlLrD7w4wgxOZofEZ9I/KDgyIq39bP15MBcTcLtzw844ukGBkdadgNFtkZnlwqSfjcOUN0Csremu45qDc7lsvAa4ArQeNi5+zSjV+/k6uGuN2MWDZBsTeQvf/RIQGxJdmBcPWgTpPX3RYaC9EKQc8OOetW0PUrOoCKlTv3iI7FZfyvGpBeLzC4l5W7RlFbAhM8SSGHTW85p1zUMhLd/RsrNbY5Eh8wKCS0nyeoVxVr44pMa0Tj2T2LqNVR8RT4snaMXl6ZsxL6hKJw4Cv4FDbK3lFB0iVzCb9oXniq9585vabKqZcHeKzE6RbT41uGk/1y9e6k8WsqJ4prqwMCTKbvMF7tcaGMg4A/tK/jluaho103uRiiOOPbQCk19gCNSxXISC33I3N9MO3v8DODoclAmwttEUgIlW10t+aMtmWr3r9GLN0TlnhE2iuSrExtTeXN3W3bBKjZUDpWkrqYO9TvkbAfz0uzK/SjJ/3OhxyX8VS4Hz1sXqp+8M1O84iNKrLGJaRyQ+lDCM/yCRxWY8op4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjY0ODA5NTY0ODgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2I0OWFjNmU1YzgxNTNkODRiNDhmYjYyOWJmM2U3M2JjY2JlZDhjNmQ0ZGJjOTViNjk0MTRjNmY5ZmI3YWRkIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Let's get strange!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-1",
                "/haste 0-1",
                "/hover on",
                "/hover off"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." magicblast"                
            )
        )
