@plr = player()


@hero = associative_array(
            'name': '§7D§foo§7msd§4a§7y',
            'class': 'doomsday',
            'sig': 'aCqllc80vvswwdl2uu+z1bod3zBcXyexOKuSomPcmvJbFqFIzknnW8S7PCDdIdjgOvP1wZuEcxO5NYpbNfOCXNIkqCZzSFeTdqsTW+PRLLp2GKiRtEC7e9QqJt8zJW53L45EeThebPnEuX88wJ61Kcneh1JryP7ddpkcqr0MBFKTRoN3NOyAKHo0YdH3QiJ6bqqsaea3bPE9JjMeRdhkg618jxTyPjEJk4EgfvOqYuvHEEjoHNzi7n0Cq/cfauO7SH12nsoKucLMIFTKiaGPh5NGQjxc3xUQVtLg8gATL6OKovp4E8nC0L2g7MjU2QbGeXbvfnhKVwMDUcDGrhJDrEN1qoFWxO39lQw25xAFMzEknA7Zhc9UOpLZue6stoAFFieeggJ94raOBD6cfKnNyXdPjYxAc8ljz08QkIAgK6QCItE09+w9lhnKKXNCo8m5qC7RFeOpTZ0hn1M/Dy1Gh+RuzLP8UqHsPe03JrAxUD6qJdFKlN7jsfDsQPpgBu4oNPYJg7R6OYHwAHu2WD7r4x2HqyWnWrh/sB5Lqeo3yOGczWSAbHNDuh5q4XqVzZFDMfEbVMEpH/OAoqGso7qOTO4lGMjHIKg2Wzug1yr6MrOmmPqqjRIxYPIXGGUplDngFf5iq2NcpFXECetaK8+cEQucOaNoMyCeR9s5jfdwQVw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Njg4MDczMzQxMzgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2I4ZjE0ZjcyNzRlZDViMTY3NmFkZDNhMDZhYzYyMzMyMDVlODEzOWI5YTRlNWZkZWM4NzNjY2U2OGQzZDU0NiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "ARGLE BLARGLE FLARG!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-1",
                "/haste 0-9"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&7D&foo&7msd&4a&7y's_Glide_Wings"                
            )
        )
