@plr = player()  
   
  
   
   
  @hero = associative_array(  
              'name': '§eD§6o§cr§4m§7a§8m§8m§0u',  
              'class': 'dormammu',  
              'sig': 'HNGtsJgzRRbIEyQIQ63CrH/dObVAtD+6PH7sWcTmMRDgqcJvTcHeUONesgIyfIpEwcKugISjtuZ/zIYgOh2ADlOv4e2yzhz+K2xSUCFqL6vhD4jnK0xD0Ti48C/JFWitRXpXbkD2b9mEQOj9OPMQJiF210byB3pK2S+3xebFmzx14DCicH7jLXLPiffzJmhvu2MSA4H3pP+n/CJRHr3wg1WPlgRUnuMuF6XL+sESa1pxvceoo3b5VEmv06oedASoz97HKSRogmPXlbMtvJwVYdbBr7gNGxDVBfXuKTazt/E4/fpP70hevf4Opio2Bszlo9L5Kyy2HBQjnFIdMoxLBsP0ifJQFB4+8hb4uZUrVRSjWvSpgtUrcnJWkHJL/IdtNBmTpmW0BRU1J97xEyKRAl1jHVluwRzX+jl+rPkGe/jKcIz64nCF8i+h8jvZUI6j6wmxvTQ1g6qmAL9fHSWNaBXduXGHBqApMGPms5uQG6LdfpllvOD5DtSNTIPOtvSUevPvB+6FIsOaZE/zHy3bk9mAPKPbH/BNt+Y+SlK2XvPHOPyBt5GQ3D84tuFeHpnKUSSy3b5gQ4CHAlB2EivtdQ75JOsKVPDEbBWJTUbh5dPV1l2Ig3wSRfoYxaPi0QTumX9ybCYGqvtGOYNS2gPk2ske0UjhpvgidNKbxxy3jDQ=',
              'val': 'eyJ0aW1lc3RhbXAiOjE0OTA0Nzk1MzkxMDYsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWI0MjMzNWUzNjA1NTUyYTJhZTdjZmJlZGY4NzliZGIwMjFkOTk3OGRiYWEzYTgyYTZiOTA5OWZjMjI2OGEifX19',  
              'trail': '',  
              'op': 'false',  
              'speech': "The Dark Dimension is my own Domain!",  
              'powers': array(  
                  "/buff", 
                  "/intangible",
                  "/tangible",
                  "/disguise",
                  "/tppos <x> <y> <z>",
                  "/fly",
                  "/run 0-3"
              ),  
              'buffs': array(  
                  "/shot give ". @plr ." elementalblast",  
                  "/effect ". @plr ." 5 9999 4 true",
                  "/shot give ". @plr ." cosmicenergyblast",
                  "/give minecraft:spawn_egg_zombie",
                  "/effect ". @plr ." 11 9999 2 true",
                  "/effect ". @plr ." 21 9999 9 true"
              )  
          )  
  
