@plr = player()




@hero = associative_array(
            'name': '§fDovahkiin',
            'class': 'dovahkiin',
            'sig': 'nJWfeVPkRpxrveev3ZXt186Yigmgq9M3aswbGW2VK23BQHDaszGsplVC9nKUGKOsGh9AcVjFguP56P6ABhxyN/vVBj3U4ImEnqy8/FJ9AeLHAvcrUaXrJXpq21AQ6+aOtgFGOLpARG81V7B9ZHZVGiJrF3R+8zQKf30WmBg0n4naxSs6H1DmvTbS1hyj6T9EwGmvB014dyUj0pBqnbarBR3BeaXqvXgFU+zc0xQyDLC7jblSXYG0QTu7OR1JEYDvyTlojUOOz9UEFpG8/wUZNIon13X2SMcwkoCZG75w43P6G/bjOzxwC87N6SZH9FETJa6wu+S9uzcB33r5obvSymo4dU/br9lrWLiZ7GZA2xgGvGLBSXEXChaODq9WHXpt485quKDXFhoo7EAcJ/dza1r2dR3zzFIcMejAcA5RCYeZiY0u3dqam4RHc0Df6T1MP4KamPiB0/EOL6KSu5LFuBxon6EjkgdW1jtBKsChOAO+eKUrQ6ltSl693Z+swhLgtJCNjDrdJDw5dO2hb899HYoaoptIAFGF08RR8asLDHTKBjk5DCzx561ZA4r6r35ZyPrkEKsbDa//OCohN+VKGPrUxz+ciiYlCK088kP0Q0PHtEPZDG9p/fVTiNar6kHGTl3mprIsKAY3oZTUEwHxuqJMegXJabGXdB3yHRefTnI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NDE0NDQ4NzUsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2U3ZDQzNGQyNjA1ZjFkNzc2ZDhlMjM1NGM4Y2U2NzQ5Mzk0YzEyZjBjZDVkMWE4ZDdhNTdiMjE1NTAxNThlYWUifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am the Dragonborn!",
            'powers': array(
                "/buff",
                "/run 0-1",
                "/jump 0-1",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true"                
            )
        )