@plr = player()   
     
     
     
     
   @hero = associative_array(   
               'name': '§5Dum§dbl§5edo§dre',   
               'class': 'dumbledore',   
               'sig': 'OIsAaCy4bm5fcreEjrwBYnY6Mq4qbv25C2ybOQfagE7FpNwh++JoU+TgZKvFOSZFqmQMhlJSVcYgEbv74ocaOll28Afe7YSAH4GULWYe42IjiZ3W3yJDhXAbZK3CF1a/UdZg/5HeVLhgegNhYPs02E9VfwppF/hVN3W5YMTWlpfXx2KIV2RgXDx/+RCAf2x3zeSUJijN86uOahBr5kfIj4Q7PHcZxMukxDOkzXEi1EJziT47apSPvvPSfl6WZywkr9No9iHkd+1PZ7qnLs71rfOYjlfKjiZ+PomlHg9en8W4Lym7JqhaN9Iv26xJDTkh1gxKgU3mbiKu0unzgb7dHKoyeO8rnJoYktImkZzvUhPTNDpDYepEG/JBMksZq6sRbmWY1xU3afMBZhE5MzFm+dTzaYaV8k4pQrqkNcwxv5o5XfXZreTB4ZGVfbPSFYQPr7Zk+7smIaOjbdBFwkNQeUgLfJ3YZY8eciuYfT++RXwt5ItlBsAzvDyTiPkNpFAhKPrPOW3i0Z3RcjkGl9UBgAnAp4dppWwqx/UkA9KsIfJo+Jb8sqOpltiQlEzh5BU/1XPD8RGtKIPW3GLnoPonScri3Ppe4C+JUGxKSPtYJeu6yaWeEk9x/oF1QimMLJz8gFgicqtgui3wldiF8oihRUxBv0GE2Fyzy580RHd4MxY=',   
               'val': 'eyJ0aW1lc3RhbXAiOjE0OTIyMTA2MTY5NzcsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODBmZjhhNDAyZjFjMzNhYTZlNTJmNGQ3NzI2OGRlZjJjMzZkN2MzYjU1ZTAyYTE0OGU4OGFiZmVhODFhN2Q3In19fQ==',   
               'trail': '',   
               'op': 'false',   
               'speech': "Welcome to Hogwarts!",   
               'powers': array(   
                   "/buff"      
               ),   
               'buffs': array(   
                   "/mgive ". @plr ." elderwand"             
               )   
           )   
