@plr = player()


@hero = associative_array(
            'name': '§bE§1l§be§1c§bt§1r§bo(§1JF§b)',
            'class': 'electrojamiefoxx',
            'sig': 'RMkkA/M9MXhy+Z7i5LoU8rpA8jgNjsOhy5gEBC8pnE2rvrZ7Jk5UxpcULyjuv9G/LX5ceObknJBKi8S2l2fa+lMu+wf5SYWUMCcV9rWQAfc4iMo7Dyoa5LtXO3CQ0EuGh67/OfASkUhytVebnWn13/2zjTaLUTJxsptVnAyZb1VoKf4WhhHU0wd/AdW/xhDW0k9tEEBw4Ftu7DR/9dECoWHpy5alhEhgqImlPYu0eIF1eO/3r3/H8NCKj5sDLhhcy0bE9wVmd+o2NzP/XXyRzsObetJ81glASwkRK4ASnNgYBNwUYPT/uW5JFNzAtkZXDD+vjxJbMNuKLntoONsZr24qFNs1a5QvyjkIWsnZMj637k09gnyDYnzLGyQ5Hx1UgrJwmvN2WsnKvDrnp7JQbDAwvnQo9EbnhQxrpfw4skL0OYTGeewH41uvWjGD4qLBwe/YRSi4uy5lcPrUnPgE5xtcbdy1iM3JpWWAsnvyLEsfVdqL0d9Y6iB1kKquUVwnE9PY16csUafwRygurTEpVCD3egi0pgeAXVKy8Z9d8e1HVPvNm/70V2ZUYRqmeAdzzCA7inKeXLHmt2rZiRIa50jhL84YzS3yp+mywDykSaXGLAucQB0yhc/Q7Lp+VBxCHvnHr2v+k3tmk1V7/+HfqQo07jsfCSFXsn9eFpLhfjE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQwMDIwODQ1OTMsInByb2ZpbGVJZCI6ImQzOTMzYzNlNWNhOTRhNGJiMjFkZGQ0ODFlNjkyY2JkIiwicHJvZmlsZU5hbWUiOiJZb3VyVXNlcm5hbWUiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2VkNDBkMDcxNDljMmQ4MDc5NzYxN2VlM2RiNThhYTEzZWQxMjk2OGIxNmFiMDYzZjFkMTljNTI4MGU3ZTcifX19',
            'trail': '',
            'op': 'false',
            'speech': "I'll dance on your grave!",
            'powers': array(
                "/buff",
                "/lightning",
                "/run 0-3",
                "/jump 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 12 true"
            )
        )
