@plr = player() 
 
 
 
 
 @hero = associative_array( 
             'name': '§2Ele§bc§etro', 
             'class': 'electro', 
             'sig': 'IqHbFSQRHs2qm5+hpN5DsTysEb/WZIGvPu5gK+viTfygsCPF2rJ0F96JppLgw5yvGmGwz0eK5WppwR7AFq+YBpmNkxPvJ4Kh+HyMVrLuiFeRJ2bNuWocQDqFMS+rB2sqtq5ecJafUet4xIuP1i+LRwOxYp+6OuSGtCeJ4SUG9kxinc0t5k7gB6uLlQLHagr2Qh12JIyqEreT6n6UYE0kzHRsCd4DM58+1+rIQVum3PHLmNcxhJdN8PRm0KTQYI7memABqUkSv1eSJh8QWjL0S/YUXFcZ3rx7mrGg3FO86BP9QF+WF95n1tsXnSlCzqXOdObEb8xoISuErJt0lK+WbG1mSJUsdBbLwNQvAQDXPjXIqnfJAzd9I6pop4FYS9C9TKYO/Q52dzIiAPYRa/UgBzD8qu6Seo0BNgiyVHCbjT/HAKCSgnZWtlYDOh8mGbCTfTVrJETRmZsZ+uNPJxKM3FEi4klcDeNWxT9BRC7Y8pd93u+5nXB16HqsykUIfFj3PzYeH8Vm30TuUwoVibLPPIJr5jbMcqT5s1ZpNt1xNSGRrJE3O+aTbPVwAQj3LskcD9GzPkH/c8u5g3aDEWckvokup1Q2+aK8rDpbI1vAspZmT2s5fCco4KeKiC1AymvyY05wMGS7cpvtKQnjdg4VBeLkuanh+B283iLlTzQqGc0=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE0OTYzNTU5NTExMjEsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTIyZWVkYTc0M2JkNjdhZWIyYjQzYWM3ZTk0ZGI2ZjUxYjFhOWM4ZjU3MmRjZmMwZjM2OTg2NThjNGUzZWMwIn19fQ==', 
             'trail': '', 
             'op': 'false', 
             'speech': "I might seem shocking too you.", 
             'powers': array( 
                 "/buff", 
                 "/fly",
                 "/run 0-2",
                 "/cast electrictp"
             ), 
             'buffs': array( 
                 "/effect ". @plr ." 21 9999 9 true",  
                 "/shot give ". @plr ." electrocute"                 
             ) 
         ) 
