@plr = player()


@hero = associative_array(
            'name': '§4E§0l§4e§0k§4t§0r§4a',
            'class': 'elektra',
            'sig': 'aBvru4fDHX28Rhz71eX8aaMZLZxD4yDg3piRZ8JObDFVaCo6rlsmEVKUNCpwxE6v7OIYXlSGwCWXRP6hbXVtZJdsg/HZ1gyLA4M+KNru2oA8n+2zRWdCgrum7mcdoy3lw8P74KfnQtIqNXkGxz1t7k73tSltRe1/I5UGDrzCAWY7L6iM/IHLu4PZa8XZVZV9hwDm6Xcs13nFKM0s4Mj8ZFNO/8dvPmaC2YCa4qGEgX0JzFTLXz9KNTeZ7XUWEFbCCd+9QyEfv0IGl3KSDt5n4O1TFG+oYSxaaPQyU14dpQtf+7SrYpQq4UoToya4XbgdTwMRejZTpkvTAl9ThEOfnwI5DfzhdFR4LkUfEenBdRFzghw6fDxtw0Aq9f8iqO+iI2RSRu8HIxwvgKkLM/3KZ1WKWRUMRmmsI8SC+v+4b8p3iHpSC75T9l6pr9twgNBvH3/EiC0RKCXaHiedE05D4bl25Ik26x/OdAG3S84HB322l08wRm7JdiWap9njbMFhdUvdeoILP5927UbyyfKJYOOuLp2lSqSyw5XQ/S1/rx8nqbiImmmJZpQsWHVbyAB1Yu8dJwPmSa6NVG/ZUK4WkYfrUYhC999LkizEmWsq5fRHjNMgmOz9/EVvqNiiSZ2KXcU29CqpbPktQb8T73X+3Dvz3ir2FLYfs63by4oxz94=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODgwNTQ1NzkxODAsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzMzMTQ0MzVjYjY3M2JkNjFlZWNlZGVhODM2ZTNlNzYyYmM2YTZmZDU0NTc2NmJiYTY5NGU1MmI2ZDJiMmIzNDUifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am Elektra Natchios. Not even the stars are safe in the sky.",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_sword 2 name:&4E&0l&4e&0k&4t&0r&4a&0's_&4Sais"                
            )
        )
