@plr = player()


@hero = associative_array(
            'name': '§4El§0o§fn§4ga§8t§fe§4d §4M§fa§8n',
            'class': 'elongatedman',
            'sig': 'akjBsYbx2uBQiDW71qZL7xQ6fcyajs/zfZpGQN+5wE62z/iXC7guWzIePJ6MWrxrrUuaPmHO+wSsnkVIbCsKbX3tHYh563yCa072sbZ8n6nXtoFco8AqTQ4yfCNax8SIQ+9aX3roHM6T+Mv3lTAQXdsysCY6BoOWf8kNoPKSWMIbdXcT+A3B8q7UwO2WQmRlbwBwIDeZeFV3zpMUDwkO7BPAWp9FTYLJ4KzM3oy0EC3h2d33tpyiOB20Y7nxxnK3CGLjrTvJuE3LS44YiMzSU9hSu99MVZtxmm7Set0j3rQDarO26eA5UhFJwKR587cWjPHxxolMIy8EhT9nFL89JT5TLdojOCHmZa4jA2ZZK5Lm4TrGSsvxyw4erocg3f5KrzsufEKln5u6DxwnUJUIZVLkbc9qEnEW93Xjuv4iMLOmb4DUGS0LLDojHYjgaBI/G57TQbqyK1Ib7+GL2CrGhq3+FKfuFbK5dVJpU3pXDheoPt3WF3zk41jacgrodc6YtCZsyr8d0mgdJ7sZigNnYtnH8gsOfs0RUFwiHRwDpAQlCU0uEi6f+waEwURjObv/zF4VbiZANNJPjSroPjJh6QrCUktvdXRn/7aYTSDso6Zv7NkKmdBa8uzvmqKK1sEO31tZyZ3GlI1LXOAlK0H83JTMtBg1Y0ngKopR0P1qD6c=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTgzNjU3OTE5NTcsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJUb255Qm9uZ29zIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kYmUyNDMzNTc4ZDA5OGEyMmY2ODgzYzJhZTNmYmMyYTY1ZDJmMDM4ZmU2NGFiMzM5YTNmM2U5YWMwOGMzMiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am invincible!",
            'powers': array(
                "/buff",
                "/disguise player",
                "/undisguise"
            ),
            'buffs': array(
            )
        )
