@plr = player()


@hero = associative_array(
            'name': '§fE§7m§fm§7a §fF§7r§fo§7s§ft',
            'class': 'emmafrost',
            'sig': 'Pv5h1z315B1YpptQDELei3AyuStnI8P8iAcyFCk1fVrQb18k3RvkWrThIIhVFAN9yOnljXFpxgqo4r19tUBrPpXfcnOi6Sbjc9O/t2iXki2Vf/EopI1TJyz9v24c0OjSys26v1DjPeS4Wu173k08SkEKxkUCNCx8s72UAjN2t4X7RJwvUvs4X1GEs6vryeyTO3XzqYWXKZVmhHO5k15fZj1ZN8yB3VuBdkfO3xMGxSNZwoRtnKYu7umh/GOBGPb0t2Oe6ohfgOqG+x/ebGTXxd+KB4CKauHxhV4N9iBZnb9yHT1x7hhJgPMZg0tK8Mwa6xGDrcheysJm+/fFp6NAkuTVKt264EJ4zyunlSdamx+Gw0ukU9ypXDu+eqaSd0ywEqjOoCOQBBNMVnT05dVU2wAgDqL1PJz7+t9NW93sjoiJVvUpQWeYAEgJCpwiRnJ0Mm02ntjw8tgVL3Jx5Ed8eJ9lz33wD4Qym/Z7Yz3/EZ+lYHJHjntstVHaDZEZUfV38s+ClKHeNMKTxXytQTfeBD32uQ5TeRDWkhEJnhQRWUpqFhIVHNx98kJkEjs+4K7QPao6SAGjJuGxOue1QpziZdATCXFFDoyapDgXgPcPAJXkq+O8l8lhh+qoAT8e7aGuDMEEzW+geLQ/4tl+9YuCFByjouh9KKqF7K/z06iDicU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAwNjY3NDMwODcsInByb2ZpbGVJZCI6IjhhNGFhNTg4ZmIxYjQ3YTdhMWNmN2Y4NjZkY2M0YmY4IiwicHJvZmlsZU5hbWUiOiJEb25hbGRfSlRydW1wIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kOTk0OTcxYmQ2MjYyYmY3NWI0NTZmYmE5Y2EyYzk0NWUzZGU4ZTkzZTlmNzQ3MjE4ZTlmMmZlZDM2NTY2NmI0In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Despite the name, I'm not that cold",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2",
                "/speak <player> <message>",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/confuse <player>",
                "/mindlock <playername>",
                "/msg <playername>"
            ),
            'buffs': array()
        )
