@plr = player()


@hero = associative_array(
            'name': '§fE§7m§fm§7a §fF§7r§fo§7s§ft',
            'class': 'emmafrost',
            'sig': 'N51Wno0u2mq8Qc/lYSOxBHxkFtuWYGYZvebE0qi/OsZ0V2cX9ctw3I0oeF9n4LMYMjtvfPkqP+6CcqdiUpe5M/F9zmVPIb6x2rF0lNlFoVcsg7EKDFmScPAOnAjFX7nOWZgDjQshh7hc2fSXbKDgiSQjangTSdCi5iDDwqNbgFNbkTP40yPQgTBB591ajqZYWU+tBm9b6eycy6QrbA3dX0cfDsiFmCBdpoHTZ7Dd03DunR5lxIJPz2lci/73IGVKwDl315HHAKjYpz2r206nSrsViHNuUMPFGY0Nmi2Dmz6li4T5pY8KA2F3K5m7yb05KkMmOPVzv9iHP30e201oxqFh/NvxSFa8hUtofM+VUrBxsoKKBAjFbWl590iHjP7J8ldg5MQmodthK4rq7qiotJ8Ty1CR7wBJqwi+7dZGzQYdgXH4+J+byepKZ/WgWaYJYVzF80mWJXrYSr+Eep2RnDdrzsrFgIMVSjxucIsnetM62HmlAQhshrkBLc+22sfMce5k8bvy94znFmrw6vGqeqgYFbT7TVXGb9YIBAktwNm+tAj7fd2gvrXCf8vKTTGZAnoz6xQz9P0COXVsNP5cRALx3m2OQAywYxT6ON7S/D2QEcFEx5zF+tbGeSSFXLIWI57kx0QZo76hYqCJPNFWaqPP7nFaVzqkuLLWoMIoPr4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAyNDQwMTEyNjAsInByb2ZpbGVJZCI6IjhhNGFhNTg4ZmIxYjQ3YTdhMWNmN2Y4NjZkY2M0YmY4IiwicHJvZmlsZU5hbWUiOiJEb25hbGRfSlRydW1wIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDk5NDk3MWJkNjI2MmJmNzViNDU2ZmJhOWNhMmM5NDVlM2RlOGU5M2U5Zjc0NzIxOGU5ZjJmZWQzNjU2NjZiNCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Despite the name, I'm not that cold",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2",
                "/speak <player> <message>",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/confuse <player>",
                "/mindlock <playername>",
                "/msg <playername>"
            ),
            'buffs': array()
        )
