@plr = player()


@hero = associative_array(
            'name': '§0End§de§0rman',
            'class': 'enderman',
            'sig': 'KNcBbCsoV94gKcV5AD3iPahMOz0T4yITJph81FRP3DXtxuriRNSWdrP96Phkam5JLCP61nwRXVJDxfDEXSfcC6kW1kOFtXiqpacaPmYHengY/xcZP5l+ilmKvUln2D3+ZJSWQ4aNx4SRtWhYGXYlfsdFR82fcD4BJpMXVoi3WHoxUyV9tqe7cmqTHN2LbltfN1oRu6J+LKQXbCcc91rk9h22TF4b3NC9e9jrJkqCTJZKhE3GCoYspH9C0MS4pQa8psBFsfSk1XAk/OgI6UFlgHQa8x/J5Sx8Z3813kM2r3IWKtFp5nhtfSDs6oEN+yoRttiD1exE4Lep8nT3ofrspWZH/CZLIMUpu6IoFQ56YR8zk4/wGqmqDSPKN6TFyY2I994vOAiTv/mRGU7vLs9Q6EcH0mOa06BwRKC3azAwuIJXeUTeUNjLrsiHDBxkYXXQkSQ8ToHKyjp2so27UiRwLzEmAIjC7GUaJeOb5H7Dozq81HfwUAmtFtDRsGBMGdjfm60vH2DvddUiH5n9jnu1IkW8V6uQfdPREi9509e1gx9QiSf37vTHASby4KVsNyrYMvcVl/rWTpLkOa/AL+JMJK9nfd/vgfYai8N5frc2lTVHhTnGPoSFMZUV3fJn5AozG6E8UCoG1aF/4+9VGwvg7NdBoqT9EDKKwgwEOkH9euw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODc4ODM5NDMwNDIsInByb2ZpbGVJZCI6ImJkNmY2MjIyMGI3NTQ2OTg4YzgzZmExY2EyYWZiMmU5IiwicHJvZmlsZU5hbWUiOiJDaDFja2VuIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yYzk2Njg0Nzc3ZmJkNDc4MTE0YWFlYTQ0MzhhNzI3NmJkYjhmZmFmOGNlNThhMjljNzQyYzExNzdiYWYifX19',
            'trail': '',
            'op': 'false',
            'speech': "*Borp*",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/pt jumpto",
                "/jumpto"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 6 true",
                "/give ". @plr ." minecraft:endstone 1 name:&0End_&fStone"
            )
)
