@plr = player()


@hero = associative_array(
            'name': '§0End§de§0rman',
            'class': 'enderman',
            'sig': 'enderman',
            'val': '',
            'trail': '',
            'op': 'false',
            'speech': "*Borp*",
            'powers': array(
                "/buff",
                "/pt jumpto",
                "/jumpto"
            ),
            'buffs': array(
                "/effect ". @plr ." 2 9999 3 true"
            )
)
