@plr = player()


@hero = associative_array(
            'name': '§0End§de§0rman',
            'class': 'enderman',
            'sig': 'cqB/gyqvoCep6UwDWdXE88o1/2PKEHmcxqRVm8zDNd2ySdESGoqxLERMKQbuityPVLNSjqfeU/kNLwN2X++AOUR925KqrUnjQl8ErQyaYCDkVswGqVWJ1kMzUtdF9+Tv3ol6n+IkkT9AVfdruPSB5BWhQphksNrT0FDbz+nyxRRtfTrr4aFjRPs2XlY/JiVXgqDRLYt9F3Uv8NjQeEpf+sFXI4wE4NHPdiKAPtuqss2w4877X5z9BFy4bGu28yj1xdRBByJUWk5B+O7z6Inzh3Px/xQyC+YcKt20sG+MoeSlsjCm5tZtomVo2VJaH3f7tXRrllS9P/Xuy3D9kqLDcEHgDQIFBirTCqpy+qEwDkpVxWD6T0evxiikJUWlCviIe4fyCVhVBmSSFEGf0/+W7UigETlKS9WwOBCQAm91YzPdl9EhH9F1NeIiQSVYdI/b+JTXl8fK1utStmgZTXyfNpeq33X/qWjKgPLiA7qcdVQXGH9LowQAzTXLVOH13vNik21CyxiwPkotJKcLeds7Oqut1qRVGDeM2+K6lw61pefyZxwvMKln379dOpxpcacBMaFc5ohug4Czk/AfY7QdkApJ3clXDynVPWYPn3yaFAEzQFWLyWDf0abqnrokZR7ZLPtSMcka2sK807gSAyyO2iczbReVspoxnFYRtjl1Ujc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODc4OTY4NjYwMzAsInByb2ZpbGVJZCI6ImJkNmY2MjIyMGI3NTQ2OTg4YzgzZmExY2EyYWZiMmU5IiwicHJvZmlsZU5hbWUiOiJDaDFja2VuIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS85NWM2NTQ1NzRhOGI4MTllOTQ3ZDU0NmI3N2U4ZDRhNDQ4MGIxZjMxODQ2YzNiNDdhYjYwYjU5YTU3In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "*Borp*",
            'powers': array(
                "/buff",
                "/pt jumpto",
                "/jumpto"
            ),
            'buffs': array(
                "/effect ". @plr ." 2 9999 3 true",
                "/give ". @plr ." minecraft:endstone 1 name:&0End_&fStone"
            )
)
