@plr = player()



@hero = associative_array(
            'name': '§2Er§7en §2Ja§7eg§2er',
            'class': 'erenjaeger',
            'sig': 'xxKafCbcLw3gg9uEQBL+k8wbsAzgFVNYGpVptBN4VIvIlo0a9kIOhHjogc5FuM77ui3sIGC9/qcY4ozaO+itY/xBhyQ3t6sCDxn3rT9sYmPwnscsVPMAPhhIxzJ1BLgGuP5OKL2aZI00/nuKoHnZ4jdLLlHaaThEVd+u3Sten7AxXZnDRc2N31ClcBNqrvxtDvn9HifvS/VjlICNSXxViwEaDa66EvQeXxQ4lP9ZroLMoDdaRpbFO5Kiz/x4NKU0/4rpTpe81EaYnLRkcu5zoSVDRDi/Vmg3C2Z6RoOtq93dwVAOHd/nYyVT6dsLcPwODgwcmBCpwhEbno4dr9wc/ziZqm/nk6Cx83ThJtOST3TGRMvZ0c6JCGpE6BWTP/S4N+cq1YhE9O4kqdmHkVaNHtmHOkYH50NSrHH69OZhIl4uhRlJw3BhmXqhAd1Op2f4jQe0UpvGIIvKIRaXnLUOD12z/RNySsIR6+jslQ26bgyzOiPWIUeLMVz58YV7GZBam5W0lvZM2Mv4mTWlckku93Y2jo8stZ4bLH/M0UaqTJjXHBW9d52dJRvIww+4LH6FRlhpGitq7bBLeerr1qNIf8YUXJhvTdF8EMbOQE+m2puwndend9hp53+Hb0J2gMIuIEF45hVLyrz1kJKQJrNKmvydOtas303dkwReUCL/KNc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTQ4MzM3MjE1MTgsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYV9SZWFwZXIiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFhMjhiZDk1ODc1YjcwNzk3MWI5YzhmODhlOGFmZTVjNWE3NDVjYTgzOTUwYjc0ZTRlZDI0ZWJkMWE2ZGRhNWIifX19'
                )
            ),
            'trail': '',
            'op': 'false',
            'speech': "What is the point if those with the means and power do not fight?",
            'powers': array(
               "/buff",
               "/grow",
               "/shrink",
                "With an empty hand, right click the air and you will use your 3D maneuver gear. You can use it to swing around the city!"
           ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:§73D_maneuver_blade",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:§73D_maneuver_blade"
            )
        )
