@plr = player()


@hero = associative_array(
            'name': '§8E§4r§cm§aa§8c',
            'class': 'ermac',
            'sig': 'eZ/+EgH1hAL7DvHmZmTtwh1vJD45PDjiK0tma1vCU8EvoU06UL7fuvtK7ZbT+n04/EAPi8wG/UwBCFPr/DtFIyLjVLDrsDZHmWfh/BeJV8xLCPHN9Em0e+Na12pSmH+dv4uftWOUHIEKU218bDmaQOsX1wEpjUx2JkrdXgtxtWv+yrOPkXUnF7MVfi5Mrq3LykjbWKJUUgIoVJAt2bTR9CPUEJIUj7ZX5EDJPS/CF6r08AE/ZS9z+2VatgaJQ6OxG5J6aCtGqksQXrRLb0RfaJCcd6Z8qUHKgixB4wTnjVT50xtgYWI90XGTwxZqJZG6VeytTHoi64tCkOsX9cQwEVXXtMRtBYqg7EPBb7VXwc3SQYmLFDfFnFbE7o3KEbDa8TKATjv1trjfLI+AcMUtKe9yJ6hVpAWDSbxzzC4SsgHjbdpzxC9wZwxk/8gHPXM9fyqZs1dhYnQzXHP8nuFyQEXX0HypsZraZJSqn4fq1SgMLk0NN5wJkTsH1mhz51xd0E2t/JKvylV30+XDUNuKw6aL1J7G4BZ/IIPptMuxpBiHynqXOWZ9/4Y7Ic1cjlM60yaauo90X8hInpJdp7OU/W7baaka0PRYdPOR8ZC7uPvImGY2xQzqlFmXiK7eIIXyngvKeNL/OfSdcNqNcNCD0vgEGWVMYYFQw2JHRw923uw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDU0Mjc4NzY1MDAsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGRlNWVmYzUyZTRjYWZhNGY3NjcxZmM3OTEzOGU5ZTUxM2E5ZWRiNTRiYzVkNzUwYmY0MGM2NzdmODkifX19',
            'trail': '',
            'op': 'false',
            'speech': "We are Ermac!",
            'powers': array(
                "/buff",
                "/tppos",
                "/cast soulpush",
                "/cast soulgrip",
                "/cast energytrap",
                "/float <up/down/pause/unpause/stop>"
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." soulball"              
            )
        )
