@plr = player()


@hero = associative_array(
            'name': '§1E§9v§ei§9e',
            'class': 'evie',
            'sig': 'Kts/P4CDK7/tn1Iec0vDRIvyKb1Hjn8zucroe5r6/Wj0J5PU6AywakrgZXwGHsCz/gaDUknaOYChhiUczcFJAtiNbZIJ1pqFR5iF/pIisNhHEwwS/RZQa+ANi7QnK9Q9J5OUibu2Fyo2oW6rFx1TRAdciu++HubVnq08OnyrSk2I/g3tClpxGSmZJA7Ok8xMpuBLnx+m/vzKkKQyDeJXCIcmSdoZfHV7B+C+Bo73TgT2eIg6z6yHHvLdjKLoXG5bt7nn5pRlJE1Ci8KK9apmrLiClvdJN4oEMHSQXmy1aFWvUBThZAS2ITjPqMwqEkBmIzCfGRklcUevBQDV5kmeq1me3RsZpA4m78E9oOB8in4Hei2ANshlMmCzIw/yNAVUwB89ruGXS/XUx7y6XBGRB90alVyM84+y6E7Xoeh0WzBgQTDn2Akkwe5eqiKM80GZfTo2hLTo8RGkrLUBYViO8GZhzFoE2psw/Vca2yCbvcRiHYgwDvVYfgGTlzD86mmcW4oxnjZ1jdmLJgoC5pLll8z3GuD4Hj+sV9iprAZkxdMa/li4qR06addNR2kZqmHeGoeiW0dRxPi0ViN5SO8FC5VOp04Av+S7l3wp3xK+fzwbs0ZjH61TSFpX9QLTImt/7CsJBTWwb07A20AAje5Tn6zYUtmrwoOyQDzjuEwB2fs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTM4Njk1ODMzMjYsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJUaGVfUmVkX0NhbmFyeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzI2MmJjNjU2M2Y2OTllZTU4Y2ExZTMxNzEzOTA2ODcwYjliNzMxNDBjYjhlZTIwNzE0M2I2NzRkZWRmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Mirror Mirror in my hand, who's the biggest jerk in the land?!",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:glass 1 name:&1E&9v&ei&9e's_&1M&9i&er&1r&9o&1r"
            )
        )
