@plr = player()


@hero = associative_array(
            'name': '§8F§7a§8n§7g',
            'class': 'fang',
            'sig': 'KpRbyylZrS3R5G949NX8YFkiz2mX3ehaeF0ikk7jczrp0e2MTj4bXq6bZLrI5OpAR9BbdrWK4UL3Js96OMQjHj/x66ccSdWD9XzfXR+d4sd1flXdKEM3pWZEwq5tHLusKqtfWtofL/AumD8AI7+fM9f11sJ/7gMVY0Q6ek70WYKWthmif6qWq/ywfWp7ZivD6u6+8pwnoyUH8ZFCnZ4Tk/yGS9Bn1DLxsHLnlsbK4jOHF5TmmcrKyZq51GDCGtDypC4V8wn5Z4W5rY2s4LZCprKahDCVRT9BQ+IY3FfJblc+yRNY1GCxcTANOAz8Vp9btIxVtYdIt86xHbayPkPKGqeFUxfnJ/0TmNSLFLMDSNt+G8LM5d6gyzL1+e5sKFTwXvspGIOBMmqKg/51cp1Z+Wua1M/n3Iv3+P26ThI/lL8xpvDcyv+fEdN8bd5YW+PMR0vhCYdafJcbmVNt+HlfCrKPy4slCwA8+A6v326DEvSyXNEB2u6w8jVtjWdF3u8iIhPyA8kyPq9VOined04UYjHdKMw/UASUJn0KYPvf0X7bR1WhAPDP/8VYb4IUkBjZg0KMq4mtRikU7Cv+Hvei/I/nxUc/g4J9mkaI50W3SBgHosaFMz3wEZ2i3SKbHNI1SBAwnLA9LlxttzCqoLryJ9R/UNbEaNcZqI8DBnoBHzs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzAyNTg0NDc5MTAsInByb2ZpbGVJZCI6Ijg3NmVjODhjOGJmMzQ5YjRiM2Q1YWQ4YTM3MWQxMWI0IiwicHJvZmlsZU5hbWUiOiJBbW91eF9GYW5nIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kZTUyMWNmNjg5ZWZmODQ4NjVmMWZlNTA3OGY3Mjk1ZDY4ZTQyMjJmNDFkNTI5NjQ4ZTIzYThhOGEyZWU4NSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "You just can't kill people like you used to.",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-2",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-2",
                "/flyspeed <number>",
                "/fly",
                "/invis (automatically de-cloak if you move)",
                "/vis"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&8F&7a&8n&7g's_Glide_Wings",
                "/give ". @plr ." minecraft:compass 1 0 name:&8F&7a&8n&7g's_Compass"                
            )
        )
