@plr = player()




@hero = associative_array(
            'name': '§fFinn §9The §1Human',
            'class': 'finnthehuman',
            'sig': 'A871OV9KU/VU1YteOLnU6zoxyNT21c38OO/DAx0w4xyzUYkEioypiud70PGnHplDsR7xA662Hi687bsutSiiZyHUSVemQSWIOxLv5rf5jLu7OdcEz+OV9lxDXs4cUMRmKMLW6gvPxS0BoaWjnS81LYBUWsK4KA9OhuZVFI7JhtOrlEgb/rb9tZxyzR47RXnhUb9hdV/R1mHHohDzAWcOsZq/BTfUmUdyuaUE/3+GQN6Yib++dHVM9t7BfNbvXuldv4cVX56O93H3TTU2Y33emI+W+BttzuhTLl2xBkj1b05zogOjo5ya8ldoE+1UgObh9tVVn9xnQm8MiGMq8+tgN8QhtvwgjgfwNV86A+loNpjlR6AtXjtycN2JhjDxL2IZu78pWg2IjQAG3eNq8YbIAX2CNABOdy/4az8q5VZQXrNQyq4uVCnUinJq/Ls5Z/12aDaKTncwCACyDwsQTPBqCDNGcl2OG6H+vRobcqCo6YC5fwBm5hCz2m3o49CF5TGietk+pKP9o3yrf++O6Ou0HlxXGcAHkQnYdE3bVqSif4gh3gbX5mRB9YSTJZHY+JOmmFcTxNQcZJv4G3LuFTFPkKtKHc9i/HAwUj/dQU7ZoP/oiLou8lNX+gNvcglVvaowkd5+z3wiI9E/h1hSHwiEAapfPvw2dhJ/P521mgkGPkk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NDkyMjgxMzIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kMGY2NGFhYzU0NzAzMDM4Njk5NDZlYmFjNDQ0N2E4ODQ1YjY1OWI4NjljOGRlOWM5NTg0ZmM0ZGMxOWJiMDIyIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "IT'S ADVENTURE TIME!",
            'powers': array(
                "/buff",
                "/jump 0-1",
                "/run 0-1",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_sword 1"                
            )
        )