@plr = player()


@hero = associative_array(
            'name': '§cFire§estorm(§cJ§eS)',
            'class': 'firestormjacksonstein',
            'sig': 'N3jhhummS57OBufYMMBMVNfVosnlA3I9ufWqyD5rXhFO8RXydertytnD3aU640xZqI2fZvb0J3EXvt06bVSFIbtqw+XmuXRXSpKZWmhR5tfUJo896Rp+W5D5sadSdiKq+Lj7Z7MsD3gB/Ixjr10Mbqrngjqxje6JlRYwQuTZgKYUP1ZRaHSsqb6dShyHq5uw1uyVJgQ3ba8LfWcnLHNl3l9oURhlrYxDgwyKWzvx3xZPhjEwlbsw6z45FzrYHIGlLLLSHvvRJ3uocomQU/klzI29wef12LRt8kqZhu4hVwp9U0Rc7Lv2sVG/jfy4VqYNq+oZtcqx6Rdszvh3TO9xqwZxrXC5nanD3Mm4QT+a/OhRgmGAGSmXkBIHKEOxSDqPBTXGLun3ca8c7/4CnlezKGnE8r9StQtabpAL+UrPdkGohUScWcu/ZhaDxxO0c0ot1du5WJocPVjgwM6XX0xoFnVjGiIdqrUtYl+lYfUNacFLiTevZjZEujrfEa3bX/rireNjh9HY0b9qiIxrX0draTN0cL/ev4VOY/mKKbj5ruqZchGcQ6ez/dGXRLDEwvcgEi4vhh+R3Q5WFebAubCyeY2bvAOQOVg1rPEu5pjw/yMonzJLd8sAmjOQjmWpZXi94UFG8KC6Yn4OFQ3KfPnoRHOxaKW1a6N/X9xREf0dHyU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDAyMjY3NzE1NjcsInByb2ZpbGVJZCI6IjU5NzU0YTRkMjVmNTRlZjNhZjk0ZDNmMGU1OGFmYjhjIiwicHJvZmlsZU5hbWUiOiJpaVdlYWtuZXNzIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lMDVlY2U2MTg2NGFkOGY0NjJmY2YxYjk0YjE0OGU3YWQxNTMwNTllYzc1NTE4MWRkZDA3NzQ2ZGQyNGYwODEifX19',
            'trail': '',
            'op': 'false',
            'speech': "We are Jax Jackson and Martin Stein, together we're FIRESTORM.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-5",
                "/haste 0-6",
                "/flyspeed <number>",
                "/fly",
                "/transmute <number>",
                "/thru (phases through objects)",
                "Shoots nuclear blasts with bare hand"
            ),
            'buffs': array(
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 5 9999 12 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 10 9999 4 true"              
            )
)
