@plr = player()


@hero = associative_array(
            'name': '§cFi§ere&cst§eor§cm§6-§cR§eS',
            'class': 'firestormraymondstein',
            'sig': 'yU1SxqcZRAHwbMHZfNlD2AOn3RGj9ML/Hr0DcncPXCsKTVsItGLJloktfyr0+OXqSjqkBduA3wsthb7rANkAiiLi10e5Du8YBL9w/SF4lYqMCfsZ8GkQ9vKsb8WbUR4gfWWoHpFGqJcMGOzpBI9peLNppSjKvMWr8tgRK4Oq6NLRcKbHWFFHfB6bKnxULdDnCo/RSDulOO2M4t+Fom4me8KeGiARICgoZb0ZDptWgFuzpUslcn6B1vgh0R6hxdiund1vMjKpbPtvWsPV7x2Bl+aEYWYkTBDuI0SvPtaL2KaJ4cDfUZQmJg9sQQccGr0MQ0ISWQRY+AG7hj2K7RNuHqkNMXsYhiD01cusoWC7zSzebFMYBwAzK4ltdvr9qNi1YwKurnh+k2Sgp382yndEo/hshL4g2jpyQRkEMgZ5oY2rXDfft6psd6DdAroUfcqNwPYQd64iaHDyQmyFaeU8keW+ZUaZVYMTx32bC7mwcJA5ZHkkxC1jfFfgsvmw5KHgw6gPlNtlbyL0FjpnFObSVWG5qlNJbJ+7CeY0f3gdB46oJt+qIOYdFRHHJ/rgAZtXTObvn6HM06mPbCpRe7Am7CecIwClDQYw4wsMVc9P2Fy6BCB6Gn5mUYyOCbSYtzn0N0BozjtW/5Dfhx42tTwvSxKc/t/d8o9eTwrnteMoBJg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjQ4MDAxMTEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mOTM2Y2NjM2I3ZDQ2ZDE4YTg2MGY1N2Y2ZmYxZmIzNjFmMzQxMzUyN2Y3YjcxODQ4NTIwNGQ2MWI5ZSJ9fX0=',
            'altskins': array(
                array(
                    'sig': 'E88ui1ZPDkw6NrB4eKFuUsTNg0fVLJmncuoX7Txw15Mk62H1yRc+nu5aSjFA4XSUgvG+fdFiunjrgY1xSgNVdEt0cM0G2U36ySDq80dLIl7p8QydT0k6jyXluBZseKhlJecfz6prHyn9vbyVdf/NfzPqt1sdVC1Jd3CJYxAh98ukciRKKocEjnYx17cxpINeKgep43E6+mboH2sXQsbUgttow2hNeTGlpY3GHrGdyz63b59X1e6Pw9xG2rCs/DboW7KZWqoY6Q5pRvMYu3Ye3i5xlmZc9DpYfYvwJffz7PCfTn+rqSYYW5fqlJNwmdDezBEW62MRohf10igvBUUoWOLhGCgyroe1AKN8kyRVqIdn6hmK5+V53wCE78Exaq8fc1J9crkvbcvuBeSTAMCZ7wt3TrireitxeEV3ZyXkMpLacFqAR0+5p5ssO1k2H4mqVa+wY5tXjfSimfMnsIUoKFlYB1aLQCXiebfZznbjgtf36ha8EQjzpnNukBfWQl0tJ14eov93ouVe8TVnoNTFSNdA5UwzKH5eeUYAZda5P67y8+Q07TRJE4l1jMHlbH1sY0k5G+x9Ly/Esf10iGerpBwiZqzo0IV+4KnKYAmrvaYVwl8wGCk3l+2ZMAlNburgDlI3iMM4EpFiinUobuxqfWpGogmUouEnGjwojD8BUZI=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODE5ODgxODU0OTgsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzcwY2ZkM2E3NWMzNGVjZGVjNjY3YTJiYTA0N2I3MWE5YTI1ZjFmYjNkYTI4NjRlYzIzYTg4OTczOTkwZGZlIn19fQ=='
                )
            ),
            'trail': '',
            'op': 'false',
            'speech': "We are Ronnie Raymond and Martin Stein, together we're FIRESTORM.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-5",
                "/haste 0-6",
                "/fly speed <number>",
                "/fly",
                "/thru (phases through objects)",
                "Shoots nuclear blasts with bare hand"
            ),
            'buffs': array(
                "/effect ". @plr ." 12 9999 5 true",
                "/effect ". @plr ." 5 9999 12 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/shot give ". @plr ." flame"                
            )
)
