@plr = player()


@hero = associative_array(
            'name': '§cFi§ere§cst§eor§cm§8(§cR§eS§8)',
            'class': 'firestormraymondstein',
            'sig': 'k6TjYXSCVU0BW+9nroksvd+TxflH0FabUfcNWkrBTiepaRW0pHxqhjke15887UF3zR5/LnFOgDp2TS1x50sH2xdGO1VIlUgnECUuVRSV78VWw7/3NyGqAgi25VTpxlSI4a+JcK6BeOZsVPZTwPkiU8yClXxHC7N6YzCPqZDGDMZ7qzz/VS3dTzc68jz7TKGX9tX1CeTQbQ1vp590Vbwer6NnyzgKcKf6mkj4M4iO9r7yAlbGorKlKhdQ8/pQUrWHWDNpMx9GeXs0vaNJC36qtUhND3chjER6yn+8Xw4IR2pyKaXf6p5yHb6OPd2Rg9arPyvP2RoEk2hMuTcCO/0GhjyGBIgw54Xk10t+XPnJBe06DBriO9L3v99wo8+3lCTctEKb2ncd2old0mPhEmGInEhp8InkWW+X3JNxT7nlPLU15T6OTLfK2ePPLALfTUFAk/bIDRSH5mYp0SJ9UutiVdNBEqkSLH5Y5/D/wwNd8v5bvxs91whlz4wYy4A77rI390r5mgiyGimVzlwpSLnUjd+oGDNkWoFQyeKCuEzqO7l5Uienpq2UMl92dLYkOD3dCkM8v2dMRAXR1VyYbjiQeGw0NwL/995kn90w3iaGPcrovEDDPLVn8QTMkXbeRuQL5cy6OIL/3w287QVA0wrt4zMQV3brMf+OVMpLTui/kwo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE5OTA5NDEwNzQsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzcwY2ZkM2E3NWMzNGVjZGVjNjY3YTJiYTA0N2I3MWE5YTI1ZjFmYjNkYTI4NjRlYzIzYTg4OTczOTkwZGZlIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "We are Ronnie Raymond and Martin Stein, together we're FIRESTORM.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-5",
                "/haste 0-6",
                "/flyspeed <number>",
                "/fly",
                "/transmute <number>",
                "/thru (phases through objects)",
                "Shoots nuclear blasts with bare hand"
            ),
            'buffs': array(
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 5 9999 12 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 10 9999 4 true"              
            )
)
