@plr = player()


@hero = associative_array(
            'name': '§cFi§ere§cst§eor§cm§8(§cR§eS§8)',
            'class': 'firestormraymondstein',
            'sig': 'k6TjYXSCVU0BW+9nroksvd+TxflH0FabUfcNWkrBTiepaRW0pHxqhjke15887UF3zR5/LnFOgDp2TS1x50sH2xdGO1VIlUgnECUuVRSV78VWw7/3NyGqAgi25VTpxlSI4a+JcK6BeOZsVPZTwPkiU8yClXxHC7N6YzCPqZDGDMZ7qzz/VS3dTzc68jz7TKGX9tX1CeTQbQ1vp590Vbwer6NnyzgKcKf6mkj4M4iO9r7yAlbGorKlKhdQ8/pQUrWHWDNpMx9GeXs0vaNJC36qtUhND3chjER6yn+8Xw4IR2pyKaXf6p5yHb6OPd2Rg9arPyvP2RoEk2hMuTcCO/0GhjyGBIgw54Xk10t+XPnJBe06DBriO9L3v99wo8+3lCTctEKb2ncd2old0mPhEmGInEhp8InkWW+X3JNxT7nlPLU15T6OTLfK2ePPLALfTUFAk/bIDRSH5mYp0SJ9UutiVdNBEqkSLH5Y5/D/wwNd8v5bvxs91whlz4wYy4A77rI390r5mgiyGimVzlwpSLnUjd+oGDNkWoFQyeKCuEzqO7l5Uienpq2UMl92dLYkOD3dCkM8v2dMRAXR1VyYbjiQeGw0NwL/995kn90w3iaGPcrovEDDPLVn8QTMkXbeRuQL5cy6OIL/3w287QVA0wrt4zMQV3brMf+OVMpLTui/kwo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE5OTA5NDEwNzQsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzcwY2ZkM2E3NWMzNGVjZGVjNjY3YTJiYTA0N2I3MWE5YTI1ZjFmYjNkYTI4NjRlYzIzYTg4OTczOTkwZGZlIn19fQ==',
            'altskins': array(
                array(
                    'sig': 'koI9BTC7a9gqZPVUEklF5pr/VLJLcFeq/CH6Q0ZCSd8sxzay+cez0slDagjjNf+8k2FGz9CBPtl/r0csUV6b9u/oT/d84/ULbKvTzgLDxulNn1OS8lwp2dB3NV/tiLn18HmPvQTnOOGPcKMwsrl8h+O6G3OYXVwsSlJjYSm71KAWThXMYeD0Va2ekfJSxu9UORKoc46RBxoEauoSsAnkoOWiavw8VOcBvjVutc2I+yCn7lnD1AQMxg/ITRCYz/83jrOMvzmDDfO4b++AYdGqkdNYqUQzU9YnrQaLM2W4XFyiwSYEdWqGv9XFHBEx1W00njV5cQtRBoHC8tlPsSttUMDmOXmv20n+Bf7I2b/uNRvkWwo5CKdu8Ph1S4dE7fbuWw+NMUhXvK8zrRMtaB4epJFkZnpnZ1pOLZ4vrOzMcKhp92rSegJt9fOHwEJlwWg1JWPwMge8Nc8D2n55iq8dHfqJiwxVAsrqqyC3Fsw3JWbfHCtPePqjA8xYHiWjSJCPXG2OKnfUy7yVcjL3sbAa7iDaAnS/S0Cg5iMCUOYOUISvZ1YxyUSQHm4hHCHTRJ97YO8Esbb33UdeKoLLKt9VmFDvb8cgh1BLw3IFw0taXdaTItCl+fKgLqXcVR4KmC65V+RK5anGVxWPeF7RPvBmHFUaR2k134S8Ha+CFJLxpq0=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0OTUzODcxMjE0ODUsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJUaGF0Q3JhZnRMaWZlIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80NTE1NjRhZGNkZGQ0MGMwNmVhYjRkODI1NDE4YmZiZDljZGU2NDUyMzZkNjU4N2ZjYmY2YWE3NDhkMzI4OTAifX19"'
                ),
            'trail': '',
            'op': 'false',
            'speech': "We are Ronnie Raymond and Martin Stein, together we're FIRESTORM.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-5",
                "/haste 0-6",
                "/flyspeed <number>",
                "/fly",
                "/transmute <number>",
                "/thru (phases through objects)",
                "Shoots nuclear blasts with bare hand"
            ),
            'buffs': array(
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 5 9999 12 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." flamethrower",
                "/effect ". @plr ." 10 9999 4 true"              
            )
)
