@plr = player()


@hero = associative_array(
            'name': '§1F§bi§fv§9e§9s',
            'class': 'fives',
            'sig': 'bG+3zqJWEC5Z4JVmSHmyB9we6vUsDhTwgFFZUGRfaKTyl/J1zH+N5U0PbY05bbqoxiWFc2o5qvMZZxM8PFerAqdFWXpnXYiTJSOpHGkYyUBQSPT9dLqp5dN5B1sqEUqKfgY4/FVQT4prcshO5UIFPfuEqqcrYHs22wFocMQDzRdppdrOHPNjtPsRwkAASSbCTDoxiIOyWrcTNx5RUwtz4b3USyr4SZ8OUTzJ0GJWoAaiKEeIKcNm0ziYquVhi1gg7xU3qbokVPFUZob9uOUwkkMqJv6LDCQAMYI/BRjcJ3FMv1KS8xunORY8ADvQTjt0EHX4/Vr8X57v08JTLMn/GxbHsboRi9EMBuJ7wUGaGXfIDs/zaKnn2uGgKGLZ4kkVL2u2YS6SopM84TbeUxgIo9gEzL7b1Nau8X4p1KE+arpSKY1nRSJMhp4eJGiOhQr0kpsc6Ezpgg+7CEcaNvFkJzbyvIOOuUYC1zWO5c+VN/0Y+oEHt04JqZU+uIUfDHGxSJTD8uJh/mefrJllyqlN/c7y3U5m96mRcFjQ2mc5D7hqQ7Z5XLmBEQViLrP9SpAxxTZpR4oewfRLIr//SejPiu1gsw8HFEBxLznmKeaNnCwP6lhPFoorWgHlvH2E5a/vA5whjwn79+Im94BM2kJ6Vjglru+wdDEXX+VCz2Y2KC8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODUwMjQxNDcyODQsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJVbHRyYU93bERDIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yNTE1YTRkYzY4N2EzMjBkNmIwZDk2Y2VlM2YxNThiYzEyOWZjOTNmNWU5ZjE1MTZhYmYwZTA0Yjg5NjEyMSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': ".",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-2",
                "/jump 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." blasterrifle"
            )
)
