@plr = player()

    

    
@hero = associative_array(
            'name': '§4Fl§ea§4sh§8(WallyW§8)',
            'class': 'flashwallywest',
            'sig': 'VAdJJWGxmnXCqfLMszZa8l5fSKwhAjb5MUoBdCS7cgMKPaPYQjk7M0liP44o7XbZD0bKITW3zxuzywjDdhhKI3RNmcoKdDjsv20EnJaYQI3eWm51UJNuVns6SAIDxDNW4pSYnnr8rOABRw7whgcEHZMAFp7WGMhp5tdF8dRk9N7Kc4UsFixUzFfezGBs+ia+dJ2UoH3cfqaZxD/u7sJHZIYDT8Ksuz0v+r/4MhsdEutH6AOJuxcQhn9QF3TmXGZ+56BNZCqLfuNGJu0xjhjcuphZj+j68S6tmKQ52oWBS6g5pe3i3D0E9Rd6LmNBmQio8EVJ7SU1v5It0emOn7Mlbe/4JkuJYI5TQAacetSBnJbTnVr+N7dJrwDle9GhgquZ58w/f6/j4x6daMlIZR6MvhkuN8AAdUylIdeAOHy+u10H7BTqGSe2i0/gdtg6T0Hgl7DOJFTiSthhfavB84I0/b85b48YMWmXcR9jO3/Um++L/9vOOnPq4vLCdOQilLlzSIqhjmq5fHWlFJi8lVWBTkQV7ilHE9mwNTQeq6wXAwpCaGIvl2qIdz9h968mLot8yxvFEWseolFs1sEb/tkz/8KkRBkCEJtL9k86RAcEnS6xENDx21LiUW4+wV0SuugGOTXguamQ5Ne67eeWfVJ81/N3Kb+z8AkiLF8JGfydwLQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Njk5OTQwMjM4MzQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2YzYjk4MTZiZGU1MmRkYjNmOWQ5NzgxYTMyYzg3MzNmZDMzMmQ0YTZhN2FlYjU4YjA3ODE2MjNkNzY0NWVkZiJ9fX0=',
            'altskins': array(
                array(
                    'sig': '"cKxFsVwcY5ZSo2UouRMM8eXvOh3im4AwM1qMyaQ31xBMmQ9Ysxjw3YF3s98guTg6Ka+qdsdchzmQZrj3HyCjWvuYd0g+e1HS+S4oVK2G5E5OgDKZb6f+HbdktKPDAZ0zpQdQdjDKxC9FD6S7qtFpveEG6KBmZbKbvHL2qkuTffYFwOCtMd9m+Ihat539BCtud/QJHG2Y9RW5GBgFU04keu6fVUks7150CDTnMyh/4vT1lbh5cmV2RWYJDAIVZ7SxtlNcSmUBK3rOOlA9YQSvVF+nHVb1HS82mXIAUmHM7OB9ib5Pm00erAbPu7a7sHKGCFDGj34cGV1ZqoHjmDoOE/eCvNnxC1zv+S0OuDTGOgxXriBA9TInfB7X/o6a4FXlcMXqvV/1CieeQ9v+wuS6HOyzu0IKzTIYcfyPE2Al1OD8JNWPJlCGfkr1ZCjgh+wf7+2cm0uLSyJ51XFdzCRdET7onbfr/6Jq7EaGnjypcXzm4ESnbgz9U3I7btByw6rVNR3mm6oHQWUs2Wdb8EIRnbXbWKKaZRXVMDPaK3sfpLIcN/uSx9whhL+IuWPGz+86t3Ezf9TCID6Jgy2FvuYCKklAGrdKHT7EWDTVGnwstATLo7gmhPdzup7U4a+r4VN20FdIgZNlyOz3NKANnGuyPpyO0NWSxoHkBhc4HRDaQJs=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODY1MjEyMDg0NTAsInByb2ZpbGVJZCI6IjdmZTg4N2Q0MzMzODRmZjdiNWEyZTFiMzQ5OWIwOWU1IiwicHJvZmlsZU5hbWUiOiJGb3h5U2hhZG93cyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzg3ZTQ1ZGQyZDYxNjMzMDkxMjY2YmYxYmZlNTQxZWFjZTM4NDU3OGNiZmQ4ZWU4ODFjYzNlYTIxYjdkNzdiIn19fQ=='
                )
            ),
            'trail': '',
            'op': 'false',
            'speech': "I am Wally West, unleash the speedforce inside of me!",
            'powers': array(
                "/buff",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/jump 0-3",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/speedforceheal <playername>",
                "/whirlwind",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-7",
                "/tppos <x y z world>",
                "/thru (phases through walls)",
                "/thrudestabilize",
                "/modifyspeed <playername> <number>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give " . @plr . " 95:4 5",
                #"/give ". @plr ." minecraft:leather_boots 1 0 {AttributeModifiers:[{Operation:0,UUIDLeast:1,UUIDMost:1,Amount:123456789123456894321654.0,AttributeName:generic.movementSpeed,Name:speed}],display:{Name:Boots of Wally West}}",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
