@plr = player()



@hero = associative_array(
            'name': '§4Fl§ea§4sh-BarryA',
            'class': 'flashbarryallen',
            'sig': 'cujvw/4jiRBXzm+Tz7Lziq6fjyMiqbAFUeVJlMcBI2Ku6DDySGzuXP3h11iwWU1TyxksPON7BTyr7rqjWon0QuhoVsXrY8IrF9bRryHSszU1j/8gixLknNKxKb5VZF0g6f1mggKt1J5pLdwOXwr0U7xCmckKuCOKSIsSBNzDLVt+NrjEC/p5KiGo0MpSkW4X73X9zHyFH+qWNiBuAYC7ZrjRYtR86le7QvtPAuYluJvLyjBlcbiupaNJnDElqwCeV7gzDzcyNQcxJmFiDXiURXNO/iyBhEawLC3I33VqaEKbugUgbK/fBik8ZbEtA/Ng+SNz8UkC1KefqFxCWHJr73whSmWyqjGZp2u8xCb+8+H8zm+n6tdKB61sq4k2i56ifPZivtBGlFxiYC767lYe+A7cjBGdjBmpHzibz+UfwTl+t7gyabEaTFJz5tMKs+wd7ZRXK71r67TmJ6R3/8ypmzLLv67tRbnIp0YrVtRgVmI2gdP2Fagi7o3za0O3lfWw+F/5azwzqjKo01JIbTra9IN6+jnuCy4qG/XdCSXQqPqUNVFvdfsyqafqAdyWtg1WvU0DMoQzVupaV3wKObUFkVjnnfJL7U7gQwsQbYzViboUbyhuIWN62tGVWBpvdV3OFPbE9GyKyPkQOfZ5rhV2w9uZpop6Y594smZmidE715s=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTI3MjEyNTcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2RhNjg3ZmJmYWI0YTBmOTk0OTU1NjRiNzNhN2Q1YmE3ZjE5MTQ3ODRmM2ZiZGMyNzgxMjcwZWUzMzcwYTUifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am Barry Allen!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/back (In the speedforce),
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/speedforceheal <playername>",
                "/whirlwind",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/haste 0-4",
                "/thru (phases through walls)"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
