@plr = player()



@hero = associative_array(
            'name': '§4Fl§ea§4sh§8(BartA§8)',
            'class': 'flashbartallen',
            'sig': 'ngiD8CykMgFQndTGkdRSkyMU747TzO4eABeUFD9e3yCQbMvTBZ4GpMZxNW13rE7KZCz39bvr9SUPyulAsHi7iFXG/D6N1AE44Smy4bFo55kbZRqfjapkqsVgoHqoQxsuC40VmFUn+W4b1oR4/PtOUMzVd3R3rITL2D+h6fo3hiPGX2961iQTDHV2bqi6fq0qloUvBNaiRh/PFf8lzM7Kja6vI32MMAfQzBa0inWhsfUdOwcrv3KVJr1Dr9rfmTTTvRw7sy7/p/ECi95boNNsC5ZfdDgFIqd4BiKmLDTHUcurBLlkOsEiy+d/ket83ODHDNQk/sC/l8xKOBLlEQb75jBRBVMBuNQW8N/p0+fJ0w7SKNJWp3rlQApODx369sny3LzGNJS92dWhWmqK5AeaT4gFkPgM96L41pRVybRK6kI+J+B7VyG1qP6R27hBZ75hKQP15B6VJugIPH2QjXhbSD3H3OyaMZ84ZwSGezv6SXD/OyrfTcEjTBEHMI0ZnhGjjqgX5FGhW2ivG0dBIFgOfZaKqCkJ9Uj5F3YuJJASqhiM9GFSwo7ZK4oLCewL9DlaYDAKMWPAiLKDkfjLdhVHIzkUzJhAk2hEIG0B31s4aOrnuKYj7AEG1/oReZV3xXducOzo0QncxCRbNi2SGeUrXnTDu3nUZjOPRg5B8ppUbgw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzE4MDQwMTEzODcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdmOTIzMWU5Mzk5MGU0NDM5ZTFiYWQyMjcyODg0NmQ0OTdkOGQyODc1NjQ0NjQ4NjE5YzlhNTc4OGIzNyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am Bart Allen!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/whirlwind",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/haste 0-4",
                "/thru (phases through walls)",
                "/vibrate",
                "/stopvibrating"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
