@plr = player()



@hero = associative_array(
            'name': '§4Fl§ea§4sh§8(JG§8)',
            'class': 'flashjaygarrick',
            'sig': 'WZEqdPCgTnNSFJV+Jfajt37qxMMr/Dpic09q7L3LhG612GewD6EdWwuKh1W548Bj5aECOZ1u3Eul+qBDWsCRcyi7lRbIjUEniSPA301vTJidqbJHk8eXpKqHcby2RfjSoBIw+Iezbuju9jS1msinPuxbvABtG6d9tX9ECii+OhaRW8qVqTABYkUfEqySgD2Ww9opC5My6iYiQbT7OL4TdiKqzrAz+wJnc5+OoNL4/7wjcn5Zkzj4rU4KvFgmxGDIe1RpJbQImKY8pQr47qmyEBkyyIu+A4s61oymD+2ZbfGTyOtViE98u5fpGa7OCjxPXNQFi95+WmewHfyal4+4lxXun9wI60G3MKRpKXfow4TVrrGyxZcVusmnCtrxGqYsx2TAmvBZ9sgYYHWReS+q+0u7T2SblA+NcmJnH1a+NXK/2PCTguDUo8xNVhDhAsUjRr5hl0zLWXSoZIai2FA/T7veki/AKnrXuv77dW+n92UMkfciXAwVNFOBh39Jp/ePhoJ0CkYUHH1HoGf2mt3PCL63DEsXmtLbIhX448/qkVelkUmDa7IwcEhcrNecS90+UaUaXP6A7VAxBZ49Rlzx1EMVkyNuHB23QA8Di1zEOHFY/wizB+D1mq3ZDzQol+B0uAE6xEfG02rbv/zfdn6oBgLTHtvIT2ejWQZGmXD0uFM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODM4MDQ4MDQyNzAsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWQ2M2MwYmM5ZmRhMTA4MDk2ODg4Y2NhYjlhMzJmYWExYzMwYjlhYzk0YzhkODMwZDgyNjVmYzkzMjRiNjAifX19',
            'trail': '',
            'op': 'false',
            'speech': "I'll do it in a Flash!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforcebuffs",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/haste 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
