@plr = player()

    

    
@hero = associative_array(
            'name': '§4Fl§fa§4sh§f§8(§4WalterW§8)',
            'class': 'flashwalterwest',
            'sig': 'ARMqRBhlxYAab0fvuGVSdLVbV2ci3712Gl2gSxoCX5YqMZ0lzVn8jLEHn9Tkji4mcb9P3iOgfcXyS4LM7ceCO9RC0eYWtdL3VERjTnfASHoYat/02knFww1DSqsmuVDgQ30nkCNvaiNa/5gLusB7HMJ2Oki1l+GlYSPaXkof8KKhycYaJIZBNMZcX0g1KyWdU6rAdvSpgl1293Iwmji+uDYIZaWfnRwjfJKWqZvg2OjrD4pm61oKO2w0wL6SkcrvTzGg5MPqh+SRJCGCF4FokP99TP8oyazK1osBg/2xqUGclVgShQ62iQTC+iTsDTiYuSDC4ueFZoxDMunN9RXesw5RmSVD9HQY2uhPu2XzpwwEg85kvron8AtA5ytVXcUKnl9Ty5XFpQYd60w0VYdDYHBZQOyR1dE4YQfQw9P0GyapH+E7iASOcb5JZqYW1E0rFb2x2Hmf7oS3Wm+YLmW1QY5zAU4ROpirbrmdikhg/9Mlu7+17T8ZZFnJx7bFKmmVLWR+NoiqcSHkDIPo2VfyRR2d3CJbNkcwsZxj1Deo2oFi2O1lfkeTuHtKdlceYhftdVrygQOW27o6/0cY4gaEtJoj2MgbFq8IESLVXZuyE4Q08Hq6HhfydF7qE8ttNl/LFjy3GzCyKrKun8dLAoZTh7imZxkdNwsI4+sAAUuHpPs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzk5MTU0MDQyMjIsInByb2ZpbGVJZCI6IjAyZGM3ZDcyMTk3NzQ5NTA4MWVjYTUxNTMyNTBkY2FkIiwicHJvZmlsZU5hbWUiOiJSaWNoaW5hdG9yMzI0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83ZTNiYTkyOTI1MmYxMzgwZWY3YThlNmJkNGMwZjAxOTNmNjJkZmRmODU0YTQ1MTg1NGUzMTc3ZDMzMTdlM2EifX19',
            'trail': '',
            'op': 'false',
            'speech': "The fast lane just got faster!",
            'powers': array(
                "/buff",
                "/run 0-9",
                "/jump 0-3",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/speedforcewhirlwind",
                "/carryplayer <playername>",
                "/dismountplayer",
                "/haste 0-7",
                "/run 0-1 (In the speedforce)",
                "/thru (phases through walls)"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
