@plr = player()



@hero = associative_array(
            'name': '§4Fl§ea§4sh§8(BarryA§8)',
            'class': 'flashbarryallen',
            'sig': 'cujvw/4jiRBXzm+Tz7Lziq6fjyMiqbAFUeVJlMcBI2Ku6DDySGzuXP3h11iwWU1TyxksPON7BTyr7rqjWon0QuhoVsXrY8IrF9bRryHSszU1j/8gixLknNKxKb5VZF0g6f1mggKt1J5pLdwOXwr0U7xCmckKuCOKSIsSBNzDLVt+NrjEC/p5KiGo0MpSkW4X73X9zHyFH+qWNiBuAYC7ZrjRYtR86le7QvtPAuYluJvLyjBlcbiupaNJnDElqwCeV7gzDzcyNQcxJmFiDXiURXNO/iyBhEawLC3I33VqaEKbugUgbK/fBik8ZbEtA/Ng+SNz8UkC1KefqFxCWHJr73whSmWyqjGZp2u8xCb+8+H8zm+n6tdKB61sq4k2i56ifPZivtBGlFxiYC767lYe+A7cjBGdjBmpHzibz+UfwTl+t7gyabEaTFJz5tMKs+wd7ZRXK71r67TmJ6R3/8ypmzLLv67tRbnIp0YrVtRgVmI2gdP2Fagi7o3za0O3lfWw+F/5azwzqjKo01JIbTra9IN6+jnuCy4qG/XdCSXQqPqUNVFvdfsyqafqAdyWtg1WvU0DMoQzVupaV3wKObUFkVjnnfJL7U7gQwsQbYzViboUbyhuIWN62tGVWBpvdV3OFPbE9GyKyPkQOfZ5rhV2w9uZpop6Y594smZmidE715s=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTI3MjEyNTcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2RhNjg3ZmJmYWI0YTBmOTk0OTU1NjRiNzNhN2Q1YmE3ZjE5MTQ3ODRmM2ZiZGMyNzgxMjcwZWUzMzcwYTUifX19',
             'altskins': array(
              array(
              'sig':'ox038VGMXB2aiOPUTqlZLWwk5G/7KgRdjLomeDd+4X3Pxqvqj1+TBj+AsoKaBraenAmrPSUQ66CbAlc7J3chiVojexAK7lH2431jpwHzc1LF0E/ezmrIF73X75F0A4J1udfVZMuz/w22IxqyR6PVkwSs/znNOkEvuM+IytHhJkK1aefyOBvNjkL6z7890l++zf9mCzocBcBJgdG/LphzcMglXTCOA9Ix1m0PpdJKNlppjeuzPHEGxgKN256098W6gFpyCMzf4Z3gAvYULJu02nOHwYQOXK0vo1XUIL5HkzX54IzDNVG3oeOCvedCS9HeizxR8TAo8F/2IZ9it9cZ9j5NdKuqiIWgJkZSDCipdYQusAFBl8y80vKEQ7rB5EvryzQ4rjtemW4ovkywBdeV1uxN1823T6xuuELgFyHR4s4qcMkYQwxvQcvCmjKrSRnHFDgwiDaLwTu6keCWR5c/28tvTqncfjorL8urDjMZyE9fcyLBpVOAnyNr2XU5hVEUKjjOcGf/dhia7vDrpv+Pizht1n2dLjJYMnbf8RPp5Q1PxD1dLKGeL2sXePu5nCMHFxixWHAhwW6kOMOidB13NMyhWDJXHwN3i12r/Tz0XANEm9gSDczD6uXVDTFVTgkM323NLYfU+/eDXlFJcADlgEU0eqaz1LrpLQ03sM5Cykw=',
              'val':'eyJ0aW1lc3RhbXAiOjE0OTAyMjAzNDI2NjMsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJTdGFyYmVhcnp6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lYTg0ZTg5ZTQ5ZWU1YTczMjIyMDM3OTJlYjgzMTE0OThmMzljYjI4ZGYxYTQ4YmQ4Y2QwMjVkNTU2NTQifX19'
               ),
              array(
              'sig':'KgSxnhzhNTMkuipELPexw11FPpnqagEE9SZzZd/OJCGQ0QNzR6pYyZcwyZbYBp9GqHRDTe8mV4j1rYv3un5gNAZgjJaTInkYXaWXuxalNH2sVxc6Xg88ReQ/DBzvshylxadfqOXCR7NPA41X9PJggIXL66+j4/LbWMwHlOiA56OqVLdheNvnFK9Xt68arbl4TvKOoOl/9Qym8NQ7OE1o0IU4W1iB0W0r5a5qaSOC89/7q2bgwNwutGB3HikmWt4650cMjV1S/Avry+hFUYlGAAbMi2Axj7WOVoVPdzQMnoNEJMak9W6LXcuUSxOYAmeXZzVgmlrDb9YuGKFk2b+f/bfRNViHhkeXIsg5Dqm0iIgtwIYUqiYnhLZSdvclJz25+yugUjYSd67xTXfRVMk+pfHkzwho6hYutVWg9qIoBWVKK0IWRnZp2tHyQz9J2gq9MgYeYQgF5lsT4mPGpq1Box9wcuTFVsm8M4pE5bHrspjvJ6Xg070G8ZAVqGrIv0qw+ey8dI+TJ/6un4ZlXdgEpSpCPLGEln8P8ItXGopxN+Jz/sB/tLnF2DikIbDjrdN6nmJHbcnwVyRZbRL3gpSbd0hyWRPJ39QJDA+0jN6A4Q+uQ0kKWpCQueHZFpkrpeztHFO824esU0MeMh/4Wl+X8V0OBpJY0lCuBMBFeW3djIE=',
              'val':'eyJ0aW1lc3RhbXAiOjE1MDg2MTY3NTg4NzAsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E0NjQ1MzYzZGE4YzI3NDZlNmFkZDViY2I0M2RjODkxODVlNTg1ZWUyNTYwMjc5NDlkYjM1NGFhMTRjOTkxMiJ9fX0='
               ) 
               ),
            'trail': '',
            'op': 'false',
            'speech': "I am Barry Allen!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/back (In the speedforce)",
                "/tp <player> (In the speedforce)",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/whirlwind",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/haste 0-4",
                "/wallrun <on/off>",
                "Look Up+Jump+Crouch to perform a wallrun.",
                "Throw lightning with an empty hand.",
                "/thru",
                "/cast infinitemasspunch"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
        )
