@plr = player()


@hero = associative_array(
            'name': '§4F§fo§8u§fr §4A§fr§8m§4s',
            'class': 'fourarms',
            'sig': 'aAeIXQRozw8h0uvdaEr+/5Z5ZLmdWqTnk6Uu46xPSV1rFDYN6knWgKh8AKqsx6JKYveIS3+3qmoa1QN10dRn49hA8cN6QhAUSeiYj2A67oUPIiUo+DdI/Kru2/zCXjuYyylgCjWM1nD9YZxvgV5gejC8bqIwomlBRM6MFsU0l0nA+rrYGzuDngWrZ9W/nAyMbwK7q5aJWbMEcGZC6mh5fBxRT8p/DdZvrBc4gVxVS3a42TfxgHDqEkCdsSEglUVA+V1qLejQJG6sb6fgAeQf5s6nbNjE6+BPgpMiRCNUdCbiaBiZ7iAezbfu66kI5syVBqNBPjhQsaFUMFxeaEgp4nCItbcDp7wnLALyMAKajPVbJY7ahIPyPykC+0pKzlHPua3fFiLCvBNoqYE2QF4Eq2zWEPTvJfiBXIbmETQrcli+7m5hl7SceJLTZ+kZnxm+35QJmLFnOox5LkO25+Prigau73gBB+6sYMiOUoRZFI/bI05rMWvRUPrtmY28gSo6GJDZQgQI+HLoXPbhDBcYBycJw3a3AD0lKMGe6/zbGugBy3px5wtZHOoWASQgGHQ9kxIo0C5A8MCmRNhL3zVlaLmuguAxT+HELemxPchwKNoqqu496QxUe2rTTD3JiqUl4QHJCyqmS/bGpZ3V3mXXrbL/nACveGfcbcV/QO3tqLY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcxNzUwMDE4MzAsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzI3OGQ4ZmQ5ZWY4ODgxZTZiMmQ4MTMxNTU5OTY2YWYyMDI5N2NhOGFkY2NhZjhlNWZmYTcwMzVjNmQ5MWU2YyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Let's wrestle",
            'powers': array(
                "/buff",
                "/jump 0-6",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",               
            )
        )
