if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§4F§8r§4e§8d§4d§8y §4K§cr§8u§7e§6g§7e§6r',
            'class': 'freddykrueger',
            'sig': 'ahN+jQjnUY3DAXhDVqtlLumZx/OahPsRK2sfyH6EWseG2B1A1nPuimWon/G2F9axnMsaT4oUxs+DiXDjfC+V6snv3XUiWI4dYS6M58iUnkGJVaZlxqrwtIytqfHh5XPDJfJf6UoLsaZzFE+XfkFMANJl3EmOi+Zh8mathRP0jWalrgmqiVFpAN9gzIti44nVWfF+DLye0Rntt3ilBprq471dZ8gWbxt8t8XPpp0Q6Ewu1l0sSYyyFbSQSszPf2hH0ViZIq1AWZBCn3V86pBZmDvamNGwJMlBbThneeG8VsmjjC7fwAUEngo6D3kU4kDOlyswpeyHzQ7iS5Hv7XaDafPRLcNJ3Qj9j1eRMZiAAT1QWrg1UTnIQZPlM7H4UwUk4PUHbMTvX3bgtL7orjpcLiFc4KUv1LEWjZk2gY9wFb+EnQXVKNzo7elkOm8JjtskoFqV/P3XZRQqBzex8NrGIB+IgssfAOBjCHSMTamGW+bXG0Re/dqr4PUoCcHp4BJ6ti3IIX/Es0QgU5OOT0qxpoiGDXE6vy7b9pecPDH0zEqd/Kh68pcZqkDB/ZhApvnGdFpi74bc/Os7EvqyAErl9Fs6s4m6GRhwMC+cQ6A+wrKkssyXf6oKS78nqE6i9Njgkx3aCNJVKLOiDjH/Pd7P4UfptGrYpFnDxXbgrHnYzmo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDczMDUxMDUxMDEsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTdhNjE4MzVmODJjOTkyZjJjNmQyNWZkYzVmYWNhZjUzNDYzMWJjMzU3OGRkOWUzZGI2MTI2MjMzMDVlOTUifX19',
            'trail': '',
            'op': 'false',
            'speech': "1 2 Freddy's coming for you 3 4 you better lock your door 5 6 better get the crucifix 7 8 gonna stay up late 9 10 never gonna sleep again!",
            'powers': array(
                "/buff",
                "/tppos"
                
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/give ". @plr ." minecraft:iron_bars 1 16:10 name:&6Kr&8ueg&6er's_&8Fing&6er_&8Bl&6a&8des"                
            )
        )
