@plr = player()


@hero = associative_array(
            'name': '§5G§9a§0l§5a§9c§0t§5u§9s',
            'class': 'galactus',
            'sig': 'rxUFJqdFKw1Vbx/s/TQcm9tqB37Y80PtpPA8kIRS54hQ+WIwp3ZGTgDcIbXaGViUEh+bWWtmYgghuZnLzDybproRnc4LhtsnH5Ik8ka9EqLr3YGOVK7pKUcMk9lI78XJV1zGcW4pMKsQBctkyacKuMgJoo8pPfETWfxlDs7PJOh07TSazd9iJn72yg2MyfiMDYzNCm7F/eo+1zxSXP7ek80yM9VrG67YfbZVftdgaKQ/OtM5psKo0YdIsFp8/jo7CwHahcWDyXL039EMuKgPcVrZMOknS2NRKU5+6/etNZ9sZ/eygBIKbWgBdJ8ZVZSfE2fY6Zr7qpVRaaog3CePX4OFSaJR6T2b5Heo17myTzoiGtlYZSFCoLn1XPPtSwQvwREVddxgcoNORCRBzdpuI4At/qL0dcQ+rh/yAeSqOnnuKuJCRehEGQO/mx+MCAYVN1Kjg/td9cpCjM5vvB2AGytsvmSKH8QoYtMVZxNejSp61c0zOUiba/KINoYiHcliQy/eEEqsIoomh/nKxal50xC9qBpO+MSWDR5Ka8Tzow/Ftap/WbIdKdbDXr6iey05KwBptc6q+UGmN7CWpIXJYBCsrNjJGWRx9HeB8/lkWDiIZEcaLxjcBdss2jEpIxIpGJFSpNrcDAMn2EhSqhlUa7Bo9gT1t8pHDEQo+lc3v+Q=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Njk4MjEyMzQyODYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzY5OTZlMmE1MmY5NjY2M2RmZTFjYjMzZTY3ZjY3Njc1NGY5YWY3OGMyNTBjMjVlZGM5NzBlNjM5NDljMyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I will begin consumption of this world immediately",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 150 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/disguise giant",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
