@plr = player()


@hero = associative_array(
            'name': '§0G§1a§am§1o§0r§aa',
            'class': 'gamora',
            'sig': 'ZF2ncStDhXfdQw63gWoDQEz0eVAWoyNwOFO4bHXk71DB4A3CPaNFeD7fWv9kqjdLo8M3EJRdlAMorGaLuKuGw5nmcV0KJ1Vz16hre5P3BB+0c0zXPU422/VE1T3xI6fhFrdMvS5mAkjM0ENp6LWSaSo0u/jEcaOf78YzEGTOT+qTTzJi5VsHH0ESSMud+J1c5hRrOKSIN/2TVJCIItpVYGmo0mLKZPuMlWs3FlDQ0YVR6ekOKPfZrkvFQUk3t+rsykV8yoLveNYfuL7nRplPfnCwpJB+9HD1gTE5m4TzD3X+p1Vy0jiFQ4kBtwb7WQNRS39Wu9WI+KBzlNh6I7OI5b7HshV/+v57iqfLJdVcwHb5e8Uf+rXtz77nTelkl68XHPiqX8Y8/R5YFFUtbsIsEblUo00xScXQ/kN+t5sY5tIXdMr3FyNHKCS6hYyiDp4yff1cPwfuJQb02XN6pIl35nmfftV7kxJfVtvV2LmoqBwNZKv7jYZLnlkAO6aiDcipjVn4Tc9OX/f0M8IjTFN30yVkHInoGFtw7g67GEydqL9/oUe+VwubToPPuE4dyY5OVXIyGyskI3MymTezvOM93isYVPjHX9TCL5LjqvIf//e871p0huh/GF57KvFZ3i/9d2vbSMm3WoTnduUe2A4axUqR/eKlEMSC2vPqRzucNtg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTI3MTM4ODcxMTEsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJMb3N0SW5HYWxheGVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzhiMjRiNGRjYTc2Mjc4NzFiOWVkNjkxYjJjZGJlZTc0NzI0Y2RlYWNiYmFkMzRlMzQxNmY4ZTNjMDJmMjRjOSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I have spent most of my life surrounded by my enemies. I will be grateful to die among my friends.",
            'powers': array(
                "/buff",
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 5 true",                
                /give ". @plr ." minecraft:iron_sword 1 19:5 16:5 name:&0G&1a&am&1o&0r&aa's_Sword"
            )
        )
