@plr = player()


@hero = associative_array(
            'name': '§8Gen§7e§8ral Z§7o§8d',
            'class': 'generalzod',
            'sig': 'pi0vnfI6JcdHBoYnOeu+uHqKEjuFPemDdvDOgU4iqEagTtCriJco596OeTvezWTT54QmsJjPso/qLRKZsuSgCfSwpEmYjGDxr3FsYSYgtzzbq1MNynN3kvuZ854lAD4oRhvXrWWzKDZxDmdu2w03OhAHk/io8K//hj2zXKlu1ClGy6qkmfBmU+ZqTbOXqscgPuVbTcIfVpaVV8wVlyAl8wdr5UnHcR2fJ9CsgZ+5TrPPXdLkNfvulM9pOk3IYm1W1miRnnrtROjYlcusbtdeAglbuDd6Mhph3UAhododtk0MZ54iG22NUkiS1aSaeyQeqjZzibq62Dcctjsc2oT/yjegDXZ3VOtQGZnPKR5lMig+4dO+LG8VlHM0FD6mhafuqTWLhc4z4Rs46hluoodyowfxKGvhpAOkOuxz59HGjaXL1kntk83se1ukkPf3zByDHnOvFCMh6n+/8BZfvPlAH+mvxI+sky4i/TA36UPLBFXqppuBTHXBLlNwnvosffro8dvp9UjE89Yfp+ffopBiWiqb56IO7BW8zxvnTL/MxZSzxAGUZONogO91SqCRc+U3mrkz+c4hS6klnGKBGEGy/Srfd9aHbSrZojlQcOhMOLLAmrfUMLL99K0iwLHlcmgDiFhl48Yet4ormJUVE0WF2gJqYW9CzHcWn4GTVp6TfK0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzEyOTEzNTg1ODcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Q1ZDhlNTdjZmNkOTY4NjIxOThmZmVhMGQzOTdiNDM0OWUyYmY3M2ZiYWMyN2VlZDMzYmU1Y2Y4ODcyNzJhMiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am evil superman or some shit idk!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/jump 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
