@plr = player()



@hero = associative_array(
            'name': '§8G§6e§7n§eo§8s',
            'class': 'genos',
            'sig': 'n1OrAg229aMesd+xd/BXBwjKQniq6Dj/2spJYDBHHhfgFAMk11gwbNKWkgw9EyE91Ms99OI6/kDQoqULDl4cWp4t4yBB6cOJDTSDYxnv+kHZYxevYJvt0DV+utONRnwQx3ONpyYn0SDCAUSoMpAWxbKiMHmBsYFtsnHagTXbhju4ut/FaoJT66DK0487CXjUIKE0HCQ72a7C4AvVcnMXZoP/Hn6zhh/UlMLCl7IxCYW9Mzxlgp67s6SqMF6LMnWQfc2XfjrVyjC7EvllfCP7SugOeCMafhh4v6YxbLNtCC1qrOnzQI1wznLSelN+A8mlRYVsHOehPw8mXI+aKHRIu9CzVfW2d0aeF9lahOb28EFFlItOdPbcrFDSYSItyVsU+KxcIjZ6+1/gWGGaDokLTD/ZKJRglZl/a0SqtVJa5GMZ5MC9cjf5rkh6nTY2b00id/tIcbXnehc5ZiOGztotpeQRLyQc2AsXrgdLCBA9mVRPuBgau9no+n2Le7midaxHRvzR/Dg9jaO988M5J6BnQU2grK0tPrTPjNq08IczmvW0hTTMgpn8xeEk3omPGRaLPxm0IEv0R3hFyCy6h8UDKIHmxWm9L9ymZm8EK0hGLdKuK+5PFU1iyeNiAEru9lHHqFIpVCay84v3wODmLM4m60b7Lpzky8ALujuxdtLkWSw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzUxOTEzNTA0OTAsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E5ZGJmZDY5Y2FjOTZiYTMxMmM5NjY0YmRhNDNiZGUxNGIyZmZjNmZkMjNjZjllNjZkMTNhZmY5YjdmMTk4In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Master Saitama would be proud.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-9"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 12 true)"                
            )
        )
