@plr = player()



@hero = associative_array(
            'name': '§7G§8h§7o§8s§7t§8f§7r§8e§7a§8k',
            'class': 'ghostfreak',
            'sig': 'pBiTmHHcMkPLMWIBQ1eCBLn7YwDQNOyrnpXlapxQHriZTLqcKNf4ZBz9J8/yiBYwPX/11SSoTUlu4/lnaEMy27LI2nCNH2fY2t93BPdBs19myOKzq1B6r6tQ5733JkfCt7jlvZC9LXJg74crqyEAmUnPQ/y55rWbadGtp0U67pKOIJpASazyExZuj47uwTCbC0dDyNkyIDooR1NGOqTVHtxMfYjiwjSq8P4bUu471VmGu0ymZV8aFMA/So3DWRdu1TbsmwIo/Gofba8kPnCJmsRwCd+Nno/pPzjAlCQ3ZL6NtyltXkFeTga2Greoj13EosDfYLxoFOeV7UZiDlF7EqNDtbKEkAkdWqHvYBru9KnBhq7OVwzHGQZ3Y7w2nz11gzA5B+4yF7j81np5szzHL56qOlmI3d8a7bcOYQWuBfBkZBCAzcxw5uLpPOziMh2HoVBq8pB14AZsnavqluypHE6gwQ0pbvO7HZ3NDBZyZd4qTr/PRRjrC3I6rQ0rOfobaAgdkKNokWc9SgSxKB/fqJG2RMGupf5SiEizfZWM3QOgvPDy5hc0ywB6GCfLwC3s6dKRz2selClOpp7FKLuJWdbPXYofsVrWHR0N0fLEaFmGmMBym1/Zt7vJV2SCZTvuLwcijaNoNvrnZPa7N3XOg6fvw/xkzDlU0LHfBqJnsIw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTc3OTU5ODUzMDcsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzk0MjExNDNhY2UxM2NiZWFmNDcxY2MxMDgxOGI4M2I4ZmJiNzEyMGZiZTgyMDU1ZTc0ZWYyNjQ1OTgwNjkifX19',
            'trail': '',
            'op': 'false',
            'speech': "You look like you've seen a ghost...freak! Hahahahaha",
            'powers': array(
                "/buff",
                "/intangible",
                "/tangible",
                "/thru (phases through walls)",
                "/fly",
                "/mindcontrol <playername>",
                "/stopmindcontrol"
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_bars 1 16:6 name:&7Ghostfreak's_&8Claws"
            ),
            'alts': array(
                'heatblast',
                'bigchill',
                'alienx',
                'lodestar',
                'goop',
                'fourarms',
                'xlr8',
                'diamondhead',
                'ben10'
            )
        )
