if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§6Gi§egan§8ta',
            'class': 'giganta',
            'sig': 'OoFL5KPOOynWopxHY7BfD6w87AQgYdcm4Nfxa/Y0Ok2F+6piF4RIUzkXnrWYeyaXpZvdEFESZq/Phh1L70Z6RGPVUVcbfV9q4nxJ2YvC2j4ZbE0NCN7Vh0imrudPB7qrhHsrNu6FSmjP/HcwVLKwtuqkolSgaUa7U2u3IA7sO1Q+3YljWxx7U8mgvxYZenYyZa/bNTs9YeT/aO012gYhdOL3v86CBId4Pk0HU3SQTzksRumWjLSNufAJ87W+ylxEMrnXnQN14zp1QeHU/Ml4DttadBpoXkxFF+M8TbKHtBbhJ2ivQMaScI7EyDzxc52K2zmKhzn3viyWM1vOLfWVDeK5Q10J1Tm9o1znWtCweeoCO8AHBExkgLRn6KPe1OVaoYMjHlhwHSIjZ5+FYTwR2cwDharu4zxHgyzxuzwCuhxagTZbjyeF4ImDLefLOTu2AKxBkfV4Q5xGJ6BTjOpxsYhzZdHd3Y5Ln8r5ao1hBsUYnIyYhH5hd0ygzalSlkbLkWZObuWGLn0HzKtDxC6N/VT4Z7kvoPXyBBEZLQ+df97Ujm4hVebkqv8sq47bKGGwWLU5h2ZCZtWXs7WDmPTwn1qhRkt79MrJXvamMAYVx7KD6Xc5+5vvg8rC3CScYDLKFq/cGTYzUkb1slymh9wUVeiDwKF1oEbfeU1xm0crbP8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTE0NjU4NDM1NTgsInByb2ZpbGVJZCI6ImU2ZGU4Y2YwYWY0NTQ0ZTQ4ODJmZDk4NDQ2ZjRiMzFiIiwicHJvZmlsZU5hbWUiOiJScW5kb21QcXJzb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iN2FhNjU5Y2YyMWJjNzgyOTIzZTQ3Y2NlYWE4Mzg3ODlmYjhlZjZhNGQ0N2RiNmZkODIyZjE5Yjc3NGFhZSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "The earth is just a world filled with ants!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-4",
                "/haste 0-4",
                "/gigantayell",
                "/carryplayer",
                "/dismountplayer",
                "/normalform",
                "/grow"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 4 true"
            )
        )
