@plr = player()




@hero = associative_array(
            'name': '§4Go§7d§4f§7all §cS§8u§cper§8m§ca§8n',
            'class': 'godfallsuperman',
            'sig': 'oQdv4swuIAOYhsQnK0HzmhPd2mnoarG6vHZHEbVZSQRK2ev2D8dBp8JqdDXkoeIJbNozDvOPIfhl8XdGJK0OtHvEtfbpT1No5E9dmbjxO/oRQjllw2YYlLhUC+YUt3QQEi9nk3ZbZIj1sLUO7imAG4tW1uLPy/9grsIzrpCRaV8ugqsFS06AykmZZ5aJOlv9RJnCQy51zPf3wR4TGdY47rtNPL/1gfgozkcOH8ejTX4RljcB37r+ecGDPrKCQ/xSYdSIOn5aFi8Zqh2KuMsbpbVOerMKelJYUiuO9YbSC6o64kctTvjt6V0iTwnqIf2Ve5WRfJ6fUM+3SCH75Ph8y2/quiD211XzFHCZmPO9giluh2uFki19tVSt2SNJPmv6DUGzJ8O16a1AkWPv+oHSeOArGzEEu2rMj585f+AgFpnDBHeNTxg0QKAde812AFF+OaQkXiYy41WmP3UW5lb3aWAV4JDlCvOKDZccaWkvvIK8POUM7U8hoQTtmGsW30ZyAS4ImaILzp2F/2CN3qibH1kgMZz8tNmxruit+EyB9oSdu/YlgvAvRKD3BoxWOUTZohd4k5npzHt4abTYZRbHJ0P9ZOb70UtcnRMI9JIHcKpvBHHh5nEHC4srOCqhKg0VQRYp1QA4RIYMgVkPDkLWp6rXIQ2JD3leDAtBFNEyiak=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzczNzc5NDA0MzMsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdkMjVkZGU0ZjFkNDg5OTY4OWNhZmVjYWU3MDg4N2ExNzVjODRhOTE4OGRhYzEwNjZjODg1YWMxMGY0NTg1YiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "The power of Kandor protects me!",
            'powers': array(
                "/buff",
                "/run 0-6",
                "/jump 0-6",
                "/haste 0-6",
                "/fly speed <number>",
                "/fly",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
