@plr = player()




@hero = associative_array(
            'name': '§4Go§7d§4f§7all §cS§8u§cper§8m§ca§8n',
            'class': 'godfallsuperman',
            'sig': 'GuD1IGa3RE+gdIieMSrd3wSJzNXqwYvUk7+6IQUgus10zCPsU98sfbEfNIfBWocREdXTB0nrJXlEq2p24c0mZW10WuvcxthTk8pa1/DOwivrrF6MngwBaz4gakROgGhQZg6v2kSj+zEPxjDSqvs8vdLKC5C+Dx/vSp7GK8gSHnnSQFTU81PjJz+ZaLPshgeCv/eQ6fEmhQklLR3wJFLRM6CU/fgHn4iSqWyqfrIkBYrWLQ0Yg7/vbc1maaoYHhxf+RRruhIFOA+YLC+pR8IFPgFANI00TtTSt0tpVvnj6aNujFFEppIgJPFuvKPP7l/H3Q8iXRnDCS9BZSvfWJc6IW6Flxi52qAZmFTx+m38ydmALoJF4r0uS8wL2basR6LF89O4j7AHNk8eNrek8raoWAqN9c9Y1XA1qfdXsrSaLF9hzmrgxxaR8HsKfX0GlNOxoFySp/hQotDkk4qGGSwd7c/KdCrpF99qH7IomzRZFZNinpfzEmgVRyLOyJZ+rubcrduygu9j2N1nqvEY8KvQmxVVs7Y/ZP/f5VUhCc/ZFNBZyGdzC88AXjSFpyZdkv4s1s0oYc1EMc4Wvd/1WNfY7Eb74YGqxNLMEmSqNXDRZpskcBb8PtGBheEko8fqXBumuIc53bhAOZv7zdkp6ttNa5BL6XS/4LHL8OCuXQlwBlk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE0NzIwMTIwMzQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJSb2JvQ29kZSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjk0MWYzZDg5MTY3NjdiMWE2ZjYxZThjMmYwOWMzMDFlMjRlM2IzMjJhZmE2YzQ3M2I0MTQ5ZWJkMWQifX19',
            'trail': '',
            'op': 'false',
            'speech': "The power of Kandor protects me!",
            'powers': array(
                "/buff",
                "/run 0-6",
                "/jump 0-6",
                "/haste 0-6",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
