@plr = player()



@hero = associative_array(
            'name': '§eG§fo§ed§fsp§eee§fd',
            'class': 'godspeed',
            'sig': 'QC2T0PYmyl75S6Vwb/I57UbEfMgJLR7dx7j0V0rdhA7fspqQdjb8RR8nwHEQ7lnozCbMUyL3rnQz12523P7qtT5SxAif03WY9Mcjz6Wy6FdjekKjLuXAmto6et3gYn8Pi8zdPMoY0c9P2GVlMBTwV/LlPeggljX9Ayw/4xcOU7GcAgNfbUc/XbxbPk2S6Fg/3NQeKQRtCzXxbrSZdDBJelZvYrQJy39DAHHrXyKNGQHUli9+uO2fW+TI5uHq81PIY7BdOCEcVx7xcl/ug9iEl8zePdJfAVUgkpGyLGI7F1XULVI/bbsHpkDZKbhC1M7naxMWI2aA9np3PHZNVtqU3HnsT+nwoSKY9qNOKPO17wM6D6zg/vcNn603SF677wQnJQdct0CJ/gVIfSg2CUaXJYWljDgsWe2Dfam96WtDrI9rWCS0nd26lQErX2liaCx/1kiXPVbVK0/LPwXBhvhXA+6axqSXe6slTzIGZDsRZfxsihpwWwYoWKiGGqJvgjE8kU7b7f2Yy8ugfRGIg0BGiYGaEptCgKFFNkFTq7XeXEMn/LJXfTL7qSWlN2M1GMWBFOMFDEKp81H3l7Dw9kjc8eX6gi2M1BAM4wUVNRz6Zycf1BfunLAEpjHe3LXL7mQDwLTrrc5cIE0oy+xDPVHyzwaJGSh+364KuX8GtxnDp7Q=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODU3NjM1MTQ0NDAsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81MDg1ZDZiMDhjNWRhNTY3MWMxNDVlZGE4YWUzMzhiMzY5MTk5MDQ1Y2JiN2ZmMTMyYTI5NmM3MjEzOWQxMTdiIn19fQ==',
            'trail': '',
            'op': '',
            'speech': "I am Godspeed!",
            'powers': array(
                "/buff",
                "/carryplayer <Player>",
                "/back (in the speedforce)",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/run 0-9",
                "/haste 0-6",
                "/jump 0-3",
                "/thru (phases through walls)",
                "/tppos <X, Y, Z Coordinates>",
                "Access to all warps in the speedforce"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
)
