@plr = player()



@hero = associative_array(
            'name': '§eG§fo§ed§fsp§eee§fd',
            'class': 'godspeed',
            'sig': 'qBRphKC5A4n04Gx7Grrqph5NXYim+CZ2qPlUJG/AGTmJpNKsfFfsNyNiIjWJc6EL8TqsQJHVF7bPZm2kXNZz8veLl0HkzkNewkQolz42Bq/oYYTkDN7GfU6ZoPEN092ur1ic4QrwuUn/ZpErFz5as+EReyHBnxg/goK7YOPLoCbLvjnWB74dOQYq0PNOsf9FhyB+jW6I3kaiNmGQv/vkJpjBFgcz9P7Zw6SyrKAPCCKYhxi4pojxiZ5vDnXpOKn8W0ng+qFVllRSd1k8iDzWuuU7TnBn4tkaEa2q3Bsu7AOmv1fkEXygxUDuqB/bL8lTk/HT2OahHCREcHbW5UOzAEaGv3kJPpwgEWJdH1rgKuybnBPpjBBEN4Nfaxuwz1w9AGjOzxeh59/9g92LxYbj9wn3kawtycLzmKy4lhe7Oxcwfl3hksGrGELRTMndsr6up79P9/oKpgsgEwJ1JQByqeg2hxa8MEf+7eQUpjlFYirK05RugnriUhW1paWGlziPrtuisDOJhHfF6/bsQ9WJngMe3+hQmQRWzLvM64yCPKTkU1LqhsAm5MBkMzs47jdDZ34OWArvRyg6pFa6ErJpkGnpXYCVSe1v9+qvj3hezhxdGSYGb2ug+fOfBidpOwDri2HxFnc1XanqEg5T3ifcD0LY982RgyoEaObJP4zMC9E=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODU3NTc0NzE4NTAsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83ZDFhMjBiZDRlZGU0YjE2OTY5ODE1Y2IxN2RjOGMzNTVkZDA2Y2E5YWQ4OTRiZTE1MWFmMTJiODQ1OTYyODY4In19fQ==',
            'altskins': array(
                array(
                    'sig': 'DpjBUfjCcrswlwa5tDt0wj76QmcbaJzeaPbPnk/tkAELJ8qF0myT39Cwo+N8oEjK0UHz/6K3+a3FTU+7Z+iAoOvih76iq9wiORUxPoijWV1jsBgn2Ivf44wTulPeuumGpmtaRc/wRzLwg9BTwmSBbf9ocOkvo+BiB5seTIa3/0Ebm8DL8gjEWPtDwnsdVllkzNgNG+665ABXNC3Z+49RWEzyd6eMKVNJSQmiojp4x18kMe13Ados+K4rlerzEWUspoMx6nkKDEO/uEbaTSd5h7sLWquI7nraBtuoe5Yv7IzYVIlRKU/5gWND/2xt+/FlYqrr8QCqIMQ2PbmSoWe8tFirSIoNKXvi7jlOugAiYh3YPkZj+hON7ai+2h991k6onjzkkY5tU3rEU1rWM+LPQGA4canIsuVbHmk/YDuyfqig0iW+4TX39FOE/lsG+30J8OA0/UhtDyu9MEE7d4lXIOBQ6hC/HihU4yRS8AvxRk3KI/JwdIakMVDj3QbJYjlt+mJf1jgla7rGOCgRSDoaSBlBif2vsEFy1B2T9emazF9qs71+g3Nj6zEBeO7xukPBCliV8qiVLkynZSBT81xtMhXIRZM1+ga47nYnM9xzyVlETizP214I4t+JK9DhJ+XcOEEy+wfVnjiH4PqzcKuXcXtimjDjfjs7vj/9a3spmr0=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODU3NjI3NDYwMDcsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81MDg1ZDZiMDhjNWRhNTY3MWMxNDVlZGE4YWUzMzhiMzY5MTk5MDQ1Y2JiN2ZmMTMyYTI5NmM3MjEzOWQxMTdiIn19fQ=='
                )
),
            'trail': '',
            'op': '',
            'speech': "I am Godspeed!",
            'powers': array(
                "/buff",
                "/carryplayer <Player>",
                "/back (in the speedforce)",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/run 0-9",
                "/haste 0-6",
                "/jump 0-3",
                "/thru (phases through walls)",
                "/tppos <X, Y, Z Coordinates>",
                "Access to all warps in the speedforce"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
)
