@plr = player()



@hero = associative_array(
            'name': '§eG§1o§6han',
            'class': 'gohan',
            'sig': 'CoDrltfa7zDhXsKVkwdVOTkNMTAglNk/wGK7Hzd+RTZk9E6DiwIPb4C0sNpJmobCC6zmiNgm6m5XsxZSjVtSwztYqg3NXl3dFUTIfEoOueX+sope8NgmTJhHWDYNVMwTGhNGmqqsFJy6jgGQaSJBJeEf/Y7ROr/y3Kq3kh1aLnm/87cdNNOLn1Hikvt7LeT+M/oYXZAIpJss6PWFoWJY5dsdy1iFgBwWzTKtKcEE6UH5MID6U9Hj9QMjKLamMDzF8vod0CWN+Am9ww3CvjRAqsXslyNTMcg89285hLLhxta+EDwaGG2MygwASJ133F6u6rose6kIgLRuNWI56bAc/Z592s6ibIWsyIKgP8smR4DjGhJ0GPODXuaFvn+OVrHPRNE0GtIhyaQbucqs/Jw2Q5t/JrGbIOC/MiRzTyJTebJ3IOwkF/RClwo+cUx+L4EMTZtJW598Zz5UCtJ6bADmR0Dk2m67Syo03WiG7ELDXVaUeXuJ25qImpdxqRau8g/cXTpAHOPkAxS8SEXCCiTgdeLxP1omKSEp53I9gHyUaNuclTiGGh08cmKHdcWCxOy172X8evB92dqm7eOM9Wry/bdvQbNuC+IyhwkTqtcV+wAEmSWhp4i/hwg/Nt7pydjdaTt7EYEI3jA1Pm+r9PFyCWavWlGaJn+otdg3i6OU59M=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzQ3Nzk0ODY1NDEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2YyMThjYTQ1MjE0OTg4NzQ3MTYyM2YzNTM4MzIzNDBmOTc1NzhlMGY5YTE3OGZlNjY2MTVmOWJlOWIzNmY2In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I'm Gohan!!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 18 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast"
            )
        )
