@plr = player()


@hero = associative_array(
            'name': '§eG§1o§6ku§8(§eSS2§8)',
            'class': 'gokusupersaiyan2',
            'sig': 'CH3UoiXD5pyxntrbw1oVXrqx0ENqloiE6nhlOQvTP4n7OkALxXPoFL80FAIQjzpl3yHpSUUsxz/uNy7wm226ahbjvtAArEHVT7kc6PYGiimWUEtOKAnFSPMkV1BZXwWrgzoXrXzwrnDqBq6Crasbm4NDb+c9G+HClmvi9Jf0N7owkkq3Zq/C2jNNWmWA+MPI0MuulEzCUTSXVIg7IeAZM9wpwa6xdcXAjdGTbAaNCwFUNQfADUPNQmOo5DgFZI3GTtKiqC7PxZjMWZleBqYeI2d48pkOhys09mVjpJYanxne/cyUTia5dcptg4mYtNaAU36FWZhXTmLSY+l5UI77sPtyBzmgMoi1TQ0oX1bD1GH9SzwWNrbx/PDA5RtgDRQSV+UU8vqJ2R60PJBLB5sgke1DK7oAmTQRAEoMI2epoemUciiQh5a7lqCe15yvHr5UthmrrN/pw8iAx+IGXB1UWN5ds8W11dE3S6vy6iuzrUkKf3Y0SkHbbRBCRDrZqybpUWXvkXrJARpYyk01NhorD/7fc3JN0iqreRzFth24uCDzFjzJZZCBnjMqWXnnbOhw3xmZuRTX0cIg4PbTpFXlJOeUAiUL7sbEQwopqwMqdbjqWT+NZ1ENYXKQMrm8CymaPHEPYUujwFxFGjQTsf2WpQphWq6sebTCgxL+s3ETWx8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcwOTg4ODgwOTgsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdhOTk2MDg4NDI0MzM0Yjc5MTIzZGFjZWE2MzMzNTUzZjYzZjU2MzJlMjk0NmE0NjdiZTY5MzBkZjliODIifX19',
            'trail': '',
            'op': 'false',
            'speech': "I will be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/flyspeed <number>",
                "/fly",
                "/tp",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 18 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'goku',
                'gokukaioken',
                'gokusupersaiyanblue',
                'gokusupersaiyan'
            )
        )
