@plr = player()


@hero = associative_array(
            'name': '§eG§1o§6ku§8(§eSS3§8)',
            'class': 'gokusupersaiyan3',
            'sig': 'cOzrlFFo5TkJv7+IxPvn1phG020IHxUx2davIH3l+UWlF3hbaVeuoxG/Zsq3vztRNSYr6nQdc0TlJ4h/m7Qxry9xTNqPxSdgS7wzs+k4duNdlRm/jGhZ/YBfJN+yzv8c13d+jJ5YE5GI6jhkfNjuF316SVLTN7D8b767xzHfze4p4Cz5LC0gUuZ+NQKDAXVS8YO7tWD0c6EDGwt6Q6mMLNksXoJyak1MKsz4dgf4yXyjV11FqFZvzVJt6eJmp7OWS5NMBoOjU0ZFKxheDXaj1ZgC5Afk6t/Sy9w0FpxTlkzu8g4Dcu2AzSsa1MD9GtlFo0AyhxgWulSVa8qh8OcuaCaG3Ll/dlNBt5s0MzBqiCbNETS7KD1hKzjv8a/VlF1HH8W2iyfDXMMN4E5aNlHK/10BboJluZvOFuy33uv5DwEdTPnGNpbSXXRVQ7bHNWJcW89XEUHWtjrd1hihPLiuxLGmEKTV7OZrTf9fBTJ+r7Zw7kuTmfj0mLni0VG9OZ1+p7ajF81Z4D945CHd14xwUT2hTa3DNNWpfqfOLG1QGXb3vJOr7GQ2e0VCYvJ8fUsohX+E+HgwLtHmJ0FZSEroAxcaIf8giy9/lnl1hjpVMmcqnHpZDeoHLQjGRuS09xg5U2hHr9t1N8mmaie8vAYivscM1hAK1Zpq/+Dw3goGstQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcwOTc0OTc3MDksInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzNiZWVkOGU4NWIyMjJiMmZhOGZhNGJlZmZiOTg4YTc2NWJkNGNkMzNiYjI1YjYwZmQxNTk1NjZhZmRlOTZhIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I will be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/flyspeed <number>",
                "/fly",
                "/tp",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'goku',
                'gokukaioken',
                'gokusupersaiyanblue'
                'gokusupersaiyan'
                'gokusupersaiyan2'
            )
        )
