@plr = player()


@hero = associative_array(
            'name': '§eG§1o§6ku§8(§eSS2§8)',
            'class': 'gokusupersaiyan2',
            'sig': 'MapFEG2KQ+oCV263sayCROtWFIiEpXMjx3jpFHbtuvAcdm762HWFO52JvmDyagWX4kruint4oY8hr6gi3Z/rff+x+HWLo6z8HcohX9tnehOAzpDYD6+K3gMVusC2rINqguWgaknexHFIabNN84i3OdJVY6JSTz/MgLSbTJwkYGhAAHAXve1N6CWaGMdL40hJx/tfRpElKALuR+SImowYXDs1QpQWal7b9MKvZgOP3PnyU4p+Zxpk/aISYn5q9tvJw7LDCi53YbTlGQuSflYLg1nir6DP/qyfPyFO5ItZ7YePfA838ekytzLgwLcC6N4HvuOX/emtSkoef4/4rZosGuUR4qmLTI4mEAOJnBERiIlb8vKFjQx5DRF6bk3JV1SPb25bgbQBETmYNegCMTWDtocTwatsdjSck9lZvy0WeDDmpXQXYT8Mco0GOH8HqdnD/n6lCtfm7bE0K3tbPzAE3jVh/WUiz7nKF9GE/+9zVIrCdZlgqC3WKJBvhG8cX7SvULTYpZ/FEQTBGXy8M3KEMB2YTrIDOlIhtjxNGUC2KNaHaSwFi1KeWpGlESuTWlJjar+OHTWxGUaGHECRwfKLiiD0kD41eW+j3PSV8VUY14XHK6MWINTTZEaNO5O+SILbdk8i0xnTiLFMs6D05xcsgem+f4CUytPrr1F5OV1CmuE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcxNTcxMzY0MTQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJKaXJlbl9UaGVfR3JleSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjI5NmY2YmViOTkzYmQ1ZDRjZGYyNjg0MmI2ZmM0ZGQ3ZTQ0OGVjY2FlOTViNTMyOTFhZmIxNmQ0MjI5ODYifX19',
            'trail': '',
            'op': 'false',
            'speech': "I will be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/flyspeed <number>",
                "/fly",
                "/tp <player>",
                "/grouptp <player>",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 18 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'goku',
                'gokukaioken',
                'gokusupersaiyan',
                'gokusupersaiyan3',
                'gokusupersaiyanblue'
            )
        )
