@plr = player()


@hero = associative_array(
            'name': '§cG§1o§6ku§8(§cK§8)',
            'class': 'gokukaioken',
            'sig': 'mynn2scEwCJjQyop6hUoQHxR4HrS4+plJljYhJKLa7hgxaS7cppNf1LUlsdD6XCtYOwizzA9JrvXDbVISSYoFf61FlMew61tIBLR733moo6Wxob5lxZbFernBQXZbg+GDvYMehSBzVgGd8a+ACuM1uUSaio6nZErrnYhjX3hsGVr4stdye5caWh5ZCYS7eyX46o37prEeLoZq4CQ+rEP4amPJpCs0HmSzCvX0e4W7Kqua4O2ohEKv8KFJQtlk0ZAjfDi6X/0qYaz+SyQ/K9PEPAB5SRYAt5EtmbuVkuvgjuDHbeKTqj0ZdkSn7YgmpgXn3MtzrhwD4OLCOtVKTeE4cyg6/5cmZVyk3fpdQmNfKjyAWHMpIK4kg0clJhZlv2BWLSb2VTBE2M364WeGw3ySnXzsyQ2WCr6WlQr1tMSOQjofRSl1NaETUL7iO/JER1+eh2+EJDHvyCcV5dlP8uhIrr3RtOlQCCQSyzF0gaw5PRD6WlSGSjUSA/ucqrl0oVylpqR0gDpwKDyEgcNBmX7xKMMk5jEnBWZ6X/xbGj9lH9tEnRgzcRAvGgnRbXH8+vtUJR4+ZTyxc2yRa3JMKBYptjGNtBMWTXWRjA3MfUBERJ1wXVd7kvLmziBWDJ0F3geXAf5QmbJxgTpgkU4ULFfaeTE/T7cwor7DyUvXwt32VM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTY0ODgzNjIxMDMsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzIzOGY0NGE2YTgxMDhjZDgzNTk4OTE5Mzg5MzBlMzdkNGNkNTA4ZmRlNGYzNWQ2NGRlYzhjN2Q0YTgzNzNkIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I will be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-7",
                "/haste 0-7",
                "/flyspeed <number>",
                "/fly",
                "/tp <player>",
                "/grouptp <player>",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'goku',
                'gokukaioken',
                'gokusupersaiyan',
                'gokusupersaiyan2',
                'gokusupersaiyan3',
                'gokusupersaiyanblue',
                'gokusupersaiyanbluekaioken'
            )
        )
