@plr = player()


@hero = associative_array(
            'name': '§eG§1o§6ku§8(§eSS1§8)',
            'class': 'gokuss1',
            'sig': 'a2fwD912omBceS92Slyg/On5Tp/yGr5UNb3FhlfmVFzF7EgmipluBA7TL8qHKRlvCLAgqe6RnVmeTYHMHPivepMimEE8nVrnpyZMnIXJ2ZpVk4MuwAAJiFgRHo/klC9QZEkBFY7Ou0oL7bOJT3cuLeQivm7gzH6vucZ/45dYZJ7pQucrTYaNBBzgfXKCADiRw0k9QBZ2YZ0ycDPV3R/MTLRyaqq8ICbk0GKIIAB6c7P5U3crloAsW/niMPeYRFM9iCT6KqppxiRWM7JsWsnWQsb0xqtZzIrlLtxkWVHYISxdGzsytmjvqADkZPRgltZftmDOL3rpnuj1ESuYUiwjxFMfUc2I8vFIQeljIIAQ08GF3KWLn/203V4z7Aqhnc6askijZtjyIYi3geA6CNKgXTixcf9ezWY4jTH6E0ApK1ri4ROn0jNcTufyW/BUGA+qkjqfeJS9XekMgZuJgjWPMvDqz+D6IxulNT2AGV7DbOpBBeS2PHYC4BJpwQdtRQKFkmQbeX9QnpYuwHGH9TbSSw36tImhqra/kqryPswN7BRma9bz1Tj5LkAl9o/DpCq/hIqFdb5Pb7hWZXxXAGFBQqJH2/4fbJzVvp8T9hsfU1aXdiS2dZSBTaHsyWIxSVnRvQ8XKRMEv5Xg+nNR4MxwzYHT2cgmwm0GYyGezglAMng=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcwMTU2MjI3NzYsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdhOTk2MDg4NDI0MzM0Yjc5MTIzZGFjZWE2MzMzNTUzZjYzZjU2MzJlMjk0NmE0NjdiZTY5MzBkZjliODIifX19',
            'trail': '',
            'op': 'false',
            'speech': "I will be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-7",
                "/haste 0-7",
                "/flyspeed <number>",
                "/fly",
                "/tp",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 16 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'goku',
                'gokussb',
                'gokukaioken'
            )
        )
