@plr = player()


@hero = associative_array(
            'name': '§8G§co§6ku§8(§cSS4§8)',
            'class': 'gokusupersaiyan4',
            'sig': 'NAfc3mmsDFpCtgPXGKGjLhfbEwYQ+i0BnmAk/LVH5vALnAK9TR9qk5rhh07Cpa/oAMgD64wXvOgaV/2wXPQBNQauOVt7SHQOwqgcUkajSkcueTLBVbuPTdQEWl0dYZOKDhkKvH/W8nXG8K9L7JlkRi46fllrCFGesUWnWZlGCgPGvxN+jTBkFB9E0p3r24zzI8OsUpz2JPvzwD+IaN+nvroDWq+SN9hazgB9LZWOP/oV6yZac8IHtDJvhS0AbaRyYu+sGhJMMR6GDWaYbT1olltdWzcv2Hx1pl0ZIUTnmb68b4AZwjOsF7ga0xOyujvdPpo2a53kbzvtPoG04xZ9JOanllGRVwquJG5ddnagmp/zA+vcXNMi/3cN1ZJi3ZA6bB5vNayzDwhQkuimm7ApxarCforMOcJN5dSJkhN91vBePb/x+l/iXhb2V4sUlfQSy4ipsl3B/gqol0gLOqKQ+X9yyABVDfg5BG+wwM+ij2f2BW3bYIslxoSx9TX5bf1rYVwvNVjAk20c6i/51SE/bWegJo4NjYzQ12JRShsGk/JHIxk7MNG3QmW/I0emcF0gJAIadg7P+8fxNeka4PjynJPPObOlepIFJ8IbIs0vDJTZhdQ4QuyDiPVjKDSuniex8/Z/+ayGG5+rNKvFXw5QnPqZ+O8kjnM0U4HYwjeVw5g=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTg4Mjk2NDU1OTEsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2VjNjYxNTZkOGMyYzVkYWI3MGMzYTJjMmRjYjU0YTlhZTVhZjk0NjMyZmIxOGZmMzRlZWRkODY5MWRjZDQ4MjUifX19',
            'trail': '',
            'op': 'false',
            'speech': "I will be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/tp <player>",
                "/grouptp <player>",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'goku',
                'gokukaioken',
                'gokusupersaiyan',
                'gokusupersaiyan2',
                'gokusupersaiyan3',
                'gokusupersaiyanblue',
                'gokusupersaiyanbluekaioken',
                'gokusupersaiyangod'
            )
        )
