@plr = player()


@hero = associative_array(
            'name': '§eG§1o§6ku§8(§eSS3§8)',
            'class': 'gokusupersaiyan3',
            'sig': 'e9XbsaWxXJdcVm2i9EUD1v3ofgmGuEQz/J/eWON42zI/hEChRX851quvmv1DSIypiTYfUv1mIkfgnVESXPzqCnSpvrhsmtqLz8DuCbhF5/w3XKXd2kdnM/yfkxUKvZmjeoMkiWjKLEyDKVUv9oWrveCtcNTKBk12ojn7sVb6whsbYeD9MfqQ/uOP8m3bStcNJSL1mE9Bi73f+AWpiuKfo4kQYSIxxLf2/Y39PvDeuG14cSIXT/HC+98NiXQTnugBS21v9nputcG8kKH4u7ov6Q01O1BpvNBjJxic7sCbE+QQ9g9UXK4o1w7D0rv4B5MgKj1zIyuuvUXYLxiQU/dzpoBh+LqFY+GTSXQ6QVoKzUx/t60pY14GaboE6yApCkDYdxJK+qfeLtwsOUPYHb6uPHBANUgs9bzvoplSxR18b3PJePd1TaanXaibP7DKETxrlZiKVsM0Z8kmPX3Rka615GnNG9rhoXN2VBjD+iWQWHmOyvl4XK/Ef11aGMFZOR2g8SuADF8vE2r6xcf4jcUAn7xxQwYcuCJ3b/b8e6wzezfT1kMPuv9FC1FMg4XKhKwu686gITRR83N6XGPseAQ4hB7IDH2Bww+oYgl4Fyob5W0BNqIyuE5uMJ0IHj5VNHL7u5ORwxRvmVO160JfN2rWvb2GgKJ/Glez1l7NoEMGBJI',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcxNTU2MjAyNjcsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2FhNjY3YmEzMjQ4N2MwNmFmMzJiZDZjNWEyODEzNjAzMjVjYzllOWNmMTZhMjkyMmNkM2NhNzk3ODgyNmM0MyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I will be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/flyspeed <number>",
                "/fly",
                "/tp <player>",
                "/grouptp <player>",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'goku',
                'gokukaioken',
                'gokusupersaiyan',
                'gokusupersaiyan2',
                'gokusupersaiyanblue',
                'gokusupersaiyanbluekaioken'
            )
        )
