@plr = player()


@hero = associative_array(
            'name': '§dG§5o§8ku§8(§dSSR§8)',
            'class': 'gokusupersaiyanrose',
            'sig': 'yJBsFBeAts1bOQkdpdhxGUhBtMNtq9nlgor4gDOwLY5glPSi53alS92G1Y+JWaoOv4Ke7PCFwSQ15oP9gj2f5WuzGt26WAUL9+7d+rYrxDri1NvaJxogqiul/+/V7bxo9fIBPLqrvWceeuwZeCdJZKneF6p0EQiLeAGMm4VdRYa7r3YwPNBGgaHMzWpxH9Kd2xm9kFRodeyGQigzlTNYKymF5qY0K2kbHmhSOmP+bn/1/seZtG0Le3c/rDaOJDYv//LpmBmF1s0TxVbj0SnpRR8XFGgdnhi1B6U0r+y/xDmxszAWnyC8miVpOmtAbw3zQpYoAxxfUVkt4yDUQaD2VtZj+3RnUAQKkfPgAQJLIeOhuhSGAg7RGCenaoPCMdqEbKAOly6jI4Q+mcRAOAQtZ66LsLD7pCRRM7ooHpBsKDH9p3+9ojgzOLBQSBQUTdsjNmGXeDaM0PK//oXulAM5Ty+VqHdX2uG2juxip5J0zeqo58youW/pw+envnh6g2+hWiIyZxKBTzfXnCpB/+5IDfmNS6h0RzSjQxqAhKQj8tJBLVm3o9gvp24jhp3dTt3N/vJj6J7HDOqgppsl3qMZ8iHqCnRdkW45hunDaTOaZZLOVbAihFNPUJIPwtvVHxXL3wQl8Bxwu3MoWx37ZZ/8WEBpwtXA5ar79KLUjHTJVao=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTgyMzY3MjEzNzksInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2I2MWU5NTI3ZWQ0YjcxNTM4N2M0Mzc4NjNjMWMwOTZmNjU2OGVkMWUzNjlhYWU4YmYxMTA2MGFkOGE5MDU1In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I will be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/tp <player>",
                "/grouptp <player>",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 24 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." superblackkamehameha",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'goku',
                'gokukaioken',
                'gokusupersaiyan',
                'gokusupersaiyan2',
                'gokusupersaiyan3',
                'gokusupersaiyanblue',
                'gokusupersaiyanbluekaioken'
            )
        )
