@plr = player()


@hero = associative_array(
            'name': '§eG§1o§6ku§8(§eSS3§8)',
            'class': 'gokusupersaiyan3',
            'sig': 'CI6Bbi+ScJRXAbCi8T8dOvOZId8vHbTXopmCU2AOdrRx67NSdi5BydYINhKEjoVvMhK9DrYD/IenRqBfrQq9Z/tL+tWwT2ik1+bdj10dE9vG/5+dd8OltzPTRi5JD40U/+GloUsJWT97lMqsDcn2FPdmO94b8eDKjf02K7hyX2fhCcum8WqBU+qi/OLCmVz8yZMcasGpKkcqcRFHYtR9Xw77rQkju3NxNaWVnqFC6ofOzR3poASyCL/+qnkOp6nYF9D36QEkB/1fcLwq+a+7X0NtverSDF3p9mFYvr51cTqA42zaMHtz4uyYWQjKglPEU+QVP50CFl2gYw2hZzlPeaAAEucJ+gXDAsTydKan2LP04mPLTZhquw2QesWzM0BQc8W/iJmP3J4oSkwlTbbGONaYFuM1PA6AVIDAixyVLXsk3ZEsNahua33ZB/RdM+Gohf52xkwUeAdxF68xZ7iEyH0k+jOS+bx6gtnGGji2I5CAPkVcLApCME0x59gVLK3h+Pm9ZTYRfz8QARWc7VPwmALxF0hARcLubnG7XDKOv/q2JM4R8+uRn6ThUhnhiAh1uGC5qt2JPb+v6IAJ7zDawiFm/fepg0yVN3YmyMMd2Je9o0CKtcz7NWVvH4WSQlxS2mv3KUzeZVi15bO2tqDD0ODJqvOpAG1IlVEcbcZXag8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcwOTk4OTk2NDIsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E2OWUxYTcyMjE3MmYwM2QyYjdhMTY2ZTM0Mjk2MjhhMjEwMWE3Mjg2MzUyMGI3YmFiNzE4NDYxNDk5MzUzZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I will be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/flyspeed <number>",
                "/fly",
                "/tp",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'goku',
                'gokukaioken',
                'gokusupersaiyanblue'
                'gokusupersaiyan'
                'gokusupersaiyan2'
            )
        )
