@plr = player()


@hero = associative_array(
            'name': '§bG§1o§6ku',
            'class': 'goku',
            'sig': 'OkxWl4LWbPhZcKlLlob59vZ4+cPVtcjMEC8z40Tu/evDxNlv7AkHGtWrxajr0dbei2gHR/+EyFvXletcDJIp72YDC3GEeHasOLEeg7joKXCdOwsyFalLRn92zMuLCqUEDxi2nmh0aoYdeZBBKet2cn+ih604IMyrD9e7FOiLp/ucmS5vtrsGTlrwpA8bvZwauKWKOxsPG54GcQe+gp2e0EAHnPNIwPNMl0upX7pfYEviToPPDzo/+ubZyiCefIxBVLultecyOOC/8Ox+UBjpDrtRaMT0vM1OMovc7uzneq5zcyGIEduGAq6DrKB9Iyc9DxGCIg1sQYIxsvQCOAFXhhBOjjPka0PFZH0Xsh7pxxzqcO2BaLvi2gPRVml6UsFEz9kZGwC9XNBYGbqtkLXzi72WA2Vbn7TZefsLKXmpBZ6GamB25/qFRdevJUNKIONUGo22P0y6QS9GoQWjymOVVbh+aipQQjuY+X647uNeQEuidUNJ8LV+WapglSNJFUdS4GBap5arDCSQ1bqXjcLZiUtlPS7/Nvig23PeLNn+mMqki7sG2DyF3nxj0i2PVKuugaG1yIGvvXLNDopdmFtgslDb/GWN02yZxLDOKnZ9aeWjBluRzH5FP3li+X5T0M6Dr0zGw1iQmHAcGhKlQ6yiAMWa9z6977kXnWTNtbEh3ZQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTM5MTIyMzQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Y5MzI2NjFhMTFkN2ExZTJhYjMzMzJkNmFhODVjNDQzZWY4MzQ3MjU1ZDZmZjNjMWI5MTQwODE3OWJkNTcxZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I will be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/tp",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast"
            )
        )
