@plr = player()


@hero = associative_array(
            'name': '§0G§7o§0k§7u §0B§8l&7a§0c§7k',
            'class': 'gokublack',
            'sig': 'olo90VVXvRHwnm3q6f+7bjnzAJl+PFyOKxc1bi75uYsbb9QoFbXskbWG591YDFtOPN7xAP6/Qn8/afvIyktiiNrcSrCTdY8NVTAdaWsgMZi3ShwkgyFkkWNONCWTr4WZqOORyP9RY0/yDfqY1uNuxElgkBxu8TDI6uxoXwuejR847XLhw0kSAqSMVJsmwaOWhXxFDOkLRi0T1Ry/wQkWq6YHARBXZKL8psGoA6OcQ8B1ucd6KtUygOoyydkrhaGgtSE5Bknff9SV25Cbv+xr9IMJrmRLNYEeFdp6QuQHeB2viJ5fFefrJ+I8ccFSuf3VeDoyD8EbFG4XnprHZPgYWPX2Ylkyw/ius8c92E4OaUObCn0hgetEzHKEAzieddrozi5wgf/n7uEnhv45I8cQJ1BPUGLvMfi9qtG/2rj1fj6aLMAzM1cuaivEOQjhFzu3wCCxNM/1O32RisJ/NYSDk7UMqdpa8zLbPWSOFYNtwy8zOX+R7DrFBSncjPXUyToNQOEztYUkEJ5GaHm9kM5cA/tdHos/9pyaYNgT3OwEzYULO4X9q9Qf+rnNhBHfcPGbqF4b+KecEV5z/JbGVeIlX3dpE7rOVwFxQcGeXKj2O+JPiCw+KHC3yRzWAHhL+jotgTmqJ/sKSWq5DDVFTPSWddz2i6SivYCEkaK49X8jfYY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTgyNDAyMjY2NDEsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzlmZTI5N2Y0ZjI5NGEyZWM4ODIxNDAyZjVjNTg2ZjFiNDc4M2JkNTU5ZTdhZDkwZmQxNDcxYjBlZGY5YTllZSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am looking at things from a much higher perspective than you",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/tp <player>",
                "/grouptp <player>",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." superblackkamehameha",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'gokublacksupersaiyanrose'
            )
        )
