@plr = player()


@hero = associative_array(
            'name': '§bG§1o§6ku§8(§bSSB§f+§cK§8)',
            'class': 'gokusupersaiyanbluekaioken',
            'sig': 'Q8ptOhp3udiTjJ4IHsMf/9S/Q2mrMxZxYd1tOURt6ILyI9I+4SYREXpcwLaQ4cWjXUsyuR9L6peFczF4vq4gyYrQm4+xWHHYFFNx3RFNJK35mh3Q/r+Ng3Gp8GhC4djZihIoxnORhihIOFBpU4k7Jq0LRIL5IX1RqqRMn5Q68wqPgVXHwmJy3SH1cjrPVKCgUcq5Q7+VaFdCkd860R5d0MBiPYcXWwJSM+q/XTUyRD8rVDu4G2BBkzZgOuiZN54UiAnEuCyTI2WU0wmj3OMI2iLSY6WGLnzmv/W0Ig5InIufP3hwRuWuumDU1aWqa4+S/wcBo2RgAdUXa/SrGvfsRmxm4XjtjZS+SrDbCfo8HnNHw/nG3XkgvpklBkCMW0axEBNWJOjYvkJjqkmWLiJ/D7UxXNkQRFJoNB4PzrRTw7j4LksbSxlLZhGfmAehhR1PI2C7oZFekRJZPW6MoPEM19vu+uSfwPQG4Srusgod4GDpaL/04hWueRMwS/rbzQgnQqegEflkXgmkZGxjHjH4AG3SWguJexU5QiC1CM9p5a30GFfTiSZVs0U4qlU70fKEU2yFwfUuL4YUHDf8lc1cswr/b5kFfK/snMVbioXl3wigy9D9MofrE34ieGc5lyaEhXGKGZvl/yD1M93aCpTv9HzOvjFfY7mvMmF6HqMX8bE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTgyMjk3MTEzMjIsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2ZiOGRjM2Q0Mjk0YjEyMTk2MTRlYTU4YWVkYTRhYWI3Y2JhYTZhMTE0ZDYxMWUzNTEwNWY5MDgxNzVjZDhlIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I will be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/tp <player>",
                "/grouptp <player>",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 23 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'goku',
                'gokukaioken',
                'gokusupersaiyan',
                'gokusupersaiyan2',
                'gokusupersaiyan3',
                'gokusupersaiyanblue'
            )
        )
