@plr = player()


@hero = associative_array(
            'name': '§8G§1o§6ku',
            'class': 'goku',
            'sig': 'XahxajxmvDG77xyGkQLHMICR77+09TI7VyHPmb6Y124g6XR4Lasb1a5WTiUgc9ULDSxXDRNXINHlk08KwpGlhxzz7nNE4tKAD3NkxiYNYQPSvEm6EiTZRfz9sctkT5EIFz4bQv4Qx0afCrl8UZ38f+D/Gu78oH0GSswCMbxM378pYwm2rG6iI2fyEFSTKFDafrMSVmCAtW6l61w1j62lGnp9GqmsL84xsnjbLx3iPkFmB8MYpyNhw0yAGRbxsjE/QjRJjHJbq6mDp2IQOQLdK6WMiGyRUFghxxSeemtr5e546kMG+rayc49MzOLkiDofsrnHJf9ElycTVWMfkGcZV/e8psv4m6yxoIDq43R5bAKoglOoMEpE3zAr//snIrthVlAViNb2GVWSd0UjO9XpVeMWCVjd7dd5ASCCeXitOk5ou39+831X3U0IF4AJLsx6HGMla97nRaWBM1W5kUNNg8A/9Lg5HwbmocbFM26l5UXuIQJh/PPvbF9MJEBYWNNzIPiZbBcZ0HR97hXnIAyeG+J+9tI0xqTZBqYP5H6mz9icQCkSAYhsjBgP4fB9FvmdRO9usdt/09m7qK2z9emH9z72Qxy8S1EwK4Da4d5eAFDknjs/oRtEUC60qItdac/ATEaZy7FM1t7oIL6YcKpJ0cw7a0/bYD8GGgffKjow/Tg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTYxNDI3Mzc0MjMsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzMyNWFiNzBlNGExOGFjNGZhM2FlMzhmODdkMDg3YTliNjQ3NzY2YzNhNDZjYmQ1NDQ2MmUzMWJiZDgxM2FkYyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I will be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-5",
                "/haste 0-5",
                "/flyspeed <number>",
                "/fly",
                "/tp",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'gokukaioken',
                'gokussb'
            )
        )
