@plr = player()


@hero = associative_array(
            'name': '§cG§1o§6ku§8(§cSSG§8)',
            'class': 'gokusupersaiyangod',
            'sig': 'GZbJGcDstRaxMsiL+F1RfCnTi+OvDIrDWTW/MYpMs4OMj4ZfgtV19VkMRRyMRQRoCtrM0qJUCeosl9PxoADKEyc+g0Ute8qNKSZIUhrzy/Lw4CFe0857se+zja5hOnzuXihzx/KfB1EMrzlhdW+acBfFWeVha6fQZbGvBQwk2ifghH1kQmsBLO6qc6OIV8RPCn/Vv2ZsselxP791e4LN2SjS+kRnQt87GSLvyEtm6K+EK4CpG89r3NfHKOKlpqHay69ApgyyKBVI6PJWBJKgUMwozjeyAi3TBskQC/Zf5Xx5ripAoWjM30fz5AG3DHB6sVBAjFPaJnbCua6ZXYBk3mYY4qQaabIAiFJ+vkAM10iAWL7UPu/Ey3A7HK9Dn6P3ErpZqszUa3yx/u0WTkbdF5jfKOIB10xsd3J93bo+kxsUk1kd9bgN4VHtDFfJsYbB8TzxAWsf3xfjHXiprL8G8/R+p1B4m37ihneZgOPdtGAuShBovdSFqxGvkPAMBMgTDT0CPHLv8LSdaQ9zNbenNpfcEDBlZHlHyvfWA6KvTuRzSEPhnmd7QhuHNVhqHginn8aIf0tggm0K2l5Kxs40p4rLHrK7Nymb/taFYSd89R3e+S+QnFAlIz0Fy6ZdZ+7QszuDdVFrGtZ7tbAG4GLVaO5HaXG5b0Ohh+i2mqRyNWI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTg4MzQwMDUxODYsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFmYzI2ZjY4OTMxNTYwYWI1MWRmNjA3OTRhNTlmMzMzNjc1ODRmODkxN2M2N2MxNDcxM2NlMTU0NDZjMWZiZCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I will be the strongest in the UNIVERSE!!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/tp <player>",
                "/grouptp <player>",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." kamehameha",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'goku',
                'gokukaioken',
                'gokusupersaiyan',
                'gokusupersaiyan2',
                'gokusupersaiyan3',
                'gokusupersaiyan4',
                'gokusupersaiyanblue',
                'gokusupersaiyanbluekaioken',
                'gokuultrainstinct'
            )
        )
