@plr = player()


@hero = associative_array(
            'name': '§6Golden §eNinja',
            'class': 'goldenninja',
            'sig': 'Ass9GteaEPvmvxkxkrBH94KAW85JgdXXVSj3kvZQNMIkAxMthAagP4YYlQ3higBPKvdxVALxZAZo+eeIij2vVn3SGFdOna4Dieu7Ejl8Bphjke2FMK0a1xxNZJHCrfTYmSlAQysltSNgzCfn5RBhITeecLe+Uq9Bsnnr/SjCOm6NluzsYLBwG8VAq2uta058JXH93VqRZjJrbYdYU8PTwypAidutEaqElD8NkNCQ03xDfiXjmHZCipkO9l9wmeHqUI+LRFOihwTo7NaYUCVIw3Y3Yf3d9+Dwi0wlwzFqMlox9SGfAj9m9gcMax9h34PW4ZlBAUgRAkBCt8Bxkg7gSJ+n2z7xOzifB5rhXcbNvlX//Sz/kV9HAMSbl8kwNBASWwwvh2S7JXeO5W4HaeaUF8r34A6U9gbAhEGKVMBOrj1FahX9TkICaJ5uKiJ/z3GRqXXffGf2E23y9TXoFGSR1Y+lnGDzsoPJ23VGj2/o2ZM/B/+hqrDveQmdMMkp66q5xakKJ88gz3ThJE/geCF3oTcGLYb7IV7876cLkeSaREY72fuWdQXctPpSYqQ5EwTYqSViwCJpXUkR0Rmz2fRsNg689Ae7hVxCq1356LxlWKLZ7senO4rtiVYGlShPWSrYZQzWlhzd8j+7FjhuBsePp9a9qyZNXQBjKab+aeq2UlQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODU0NDk4MDg1ODMsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xODFjZDYxZGQyNWE1NmJiNTQ4ODE2MTI4OTVhMjc4ZGIwNzRkODRiZTczNDU4NTNhZDcxM2M4NzQ1ZDNkZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am the master of spinjitsu!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/haste 0-8",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-5",
                "/spinjutsu (gives strength 5 for 10 seconds)"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:golden_sword 1 20:2 name:&6Golden_Katana"
            )
        )

