@plr = player()



@hero = associative_array(
            'name': '§2Go§aop',
            'class': 'goop',
            'sig': 'qvJGM394IuyeU6D9DmzS+wtDtZcD+YXi6weHJsTcYZGJ3TA2tW3yEpfjUkVWlXzEL7Vfz6TpaQf7sthrBz8pVzsxHoWYW89b9PBknVavAvIi9K1lOuWGBKxYnyMeh7mU3HEpafPGjMqtgJSqNYdPiFOzmfWeKLUDcAP7xqv5sItVIy48JvAZueMJXNGttc2oHUpzy7ptUr/0Bb5SXoSxgRXN0/LXMVQRmI3VEwhujJfY+GpirRVQmNGi5k/75+wPDyV+aTHFBeIPKufhrSs8NV8Ng3AL+787OzBb+w8iUXRPZG9PtTaizixqhOKWkt37O8rAJQEOqnMvv/3+Owt3TImH6/nCOzWkk3rBgvpgqImQfi+/DR1NY7OTE4iM+7KXGQHGralCP2yDPl+tt9wJjfr0uescQgJtlLdTEJhi5pCBluvto28Y6eBXDxl0leUR9rcj/Yl1ha+qjoovWtXEbA17M8hSIunla+U0V4nRLIdaf+8NE64aiyFT4O18+/g9pl9q+hsfkBF2y63ZZQg4Ya6gD7F3O9s4E8ju8aP16UeKgXr+QL6Ze1PbA4dJjzMXHeP8yNNhtm5b7AxBe6ISd/fra0gP9HyNjQ2HAymWkM9r+PAZ/M0VqiK1bDsmasuY0FfFv+RMkLV1cwTxzVOeUHfpKLg0T30zht3Z81p+kOw=',
            'val': '"eyJ0aW1lc3RhbXAiOjE1MTcyNTgxMzIzMTYsInByb2ZpbGVJZCI6IjkwYjJiYTZkNDNlNjRlNWM4Zjc3OTEyNmI2OTY5YTljIiwicHJvZmlsZU5hbWUiOiJXaW5nQXJtb3IiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2ZjZjgyMmE2YmZmZDExZDllNTlkZjMxOTRlMWNmNjI0OGJhYmQ5YTQzMzdhNzAzZTQzZTgxZTFjMjlmY2JiIn19fQ==',
            'trail': 'slime',
            'op': 'false',
            'speech': "Goop",
            'powers': array(
                "/buff",
                "/herotransform",
                "/fly"
            ),
            'buffs': array( 
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 11 9999 5 true",
                "/give ". @plr ." minecraft:slime_ball 1 19:10 name:&2Slime_&aFist"
            ),
            'alts': array(
                'ben10',
                'bigchill',
                'alienx',
                'lodestar',
                'heatblast'
            )
        )
