@plr = player()



@hero = associative_array(
            'name': '§2Go§aop',
            'class': 'goop',
            'sig': 'mvaIRtYNMZO2oZOirh6muhtabIte56WhK+r5RkjSlTD6+BS4PjSQX33U81Cv1KdO1e3z23XL53Jv0yp6zgwTvSKfvArqF3Q8xVYlfCPfH6ufMFEm608+8h3qkiyzUBHh8mNm5fRzNMN+XNj2MVeg1/343qBmqYW0ew1f+pYPmSI9aZOdwfJMATkgaZsZBmMdBeSwRN7oNzjC1VTDZMasBNpEMCbeybTSNwTGLRhvBBaLh3to7KE+U7Jr0NATjWOEFXRMeE0cc0GAhqTbXKgFZqvh6ghR1V3CMV+yVvDPlzFUv+QyTdcLX8a7HLUlQqG7D+k/zjAFkGN8cOj3mM7P54XGdHqFl4FZFFx74SmeVgBsZUiba2y2Hp+7vPWUXKFMbkTujYMO3cJjkRmK0PWi3pisdxU9gBy5gfb5Jzf3CaR+5tRVWzLEjmNWxfB1B201lfq8l+JTUMWBI/IvpyVhYHAfjTmN8Nl84Suo8wxsoxom0ioB3xt0n3YZ39F3dzRICQY7WHBkEKch2o5MCLbfmikDb8WaSOjn2gMg/XSqK+4hTfAX652gr5desrnmptZC9+QYeWAMeb7birWSUQ2ogEBFRIdVXGDNB5NcTRj32WC2QKTT5tW00YwI73McWgtOrrkc4c2goiH8AbxWAFFahh2QRLfiMioCMlFWpU8BDJ8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTczNDA1ODAyODQsInByb2ZpbGVJZCI6IjkwYjJiYTZkNDNlNjRlNWM4Zjc3OTEyNmI2OTY5YTljIiwicHJvZmlsZU5hbWUiOiJXaW5nQXJtb3IiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2ZjZjgyMmE2YmZmZDExZDllNTlkZjMxOTRlMWNmNjI0OGJhYmQ5YTQzMzdhNzAzZTQzZTgxZTFjMjlmY2JiIn19fQ==',
            'trail': 'slime',
            'op': 'false',
            'speech': "Goop",
            'powers': array(
                "/buff",
                "/herotransform",
                "/fly"
            ),
            'buffs': array( 
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 11 9999 5 true",
                "/give ". @plr ." minecraft:slime_ball 1 19:10 name:&2Slime_&aFist"
            ),
            'alts': array(
                'ben10',
                'bigchill',
                'alienx',
                'lodestar',
                'heatblast',
                'fourarms'
            )
        )
