@plr = player()




@hero = associative_array(
            'name': '§8G§7o§8rilla Gr§7o§8dd',
            'class': 'gorillagrodd',
            'sig': 'ENW4KUuebKuSEJJhRGL+EoP45cJ49eqEDkwYKJ0j4fWnV8xwKAL5XhJ0Pdg+18qjf/J721wg0kUS7mvirQl3SfM2YKy2WNtFTovJtPNuV3T6v52qpIvDYJK0rOQ6MV27mCwS+R4zRBKGZQY3mZB+fJndsUD6sChQ5FxoMEx3l42w2npdGyzkUg/VKOP2DnJjijIHZgz6rklU9R2AF/Kcmd6c4YAoWOutyJWPDf7t6Vb2dTuJ96Zs83JufvtuhsrCMbZOyzDmNidzHPcdMrTbs0dkeN9aSES4NRjTtpdM4oLlHb+oDhZoPxhZV1kKIgjdyRjIxjvJoW90P+nOoCT5ihAp8/zS66Dua4JwlFbmeUTx3x0dGVoDwyLJqHwN2YfS0t32RXqa1pYqZMQQi4KVlw8jThwv1Tq0oT+ouynzmhUwBc+STkRHf+Qhyv1nnXbfKEd/wY1qlRoDAX9/3aoHDQuo9aFsnaO/Z3dP027699YxoBDB5U3iTGkUIKcxU49LniByeiYScC6hq1izs3t0AphLDqy+P+UtWzSRv1fOtmf4xl5nofPob5KZRI3/pNoXFlGp2z3O9vCaw+203fyCkMBgrzbdnEm45H2nqnqejXlyK/qhEZ8/spP6gBlZOhRLr5nGuL7ZGb8WoAAj15thqGZQwizrUfAI4pdrAV6Tsx0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzUxOTE2MzU2NTcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2U4ODQ4MDI5MjA1OGZiYTdjMGRhNTMwNDU5OGI0ZDY3NGUxYTg2OWM4ZGU2YTdhNWE4MzQ2YmNjNDRiYmZkIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I am a telepathic gorilla!",
            'powers': array(
                "/buff",
                "/carryplayer <playername>",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-9",
                "/haste 0-6",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/speedforcewhirlwind",
                "/speak <playername>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 12 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true"                
            )
        )
