@plr = player()


@hero = associative_array(
            'name': '§bG§8o§bt§8h§ba§8m§bM§8a§bn',
            'class': 'gothamman',
            'sig': 'NNJXcuhTH+YOJ+JAtbv/dYBt2fLY/N7TZXnJKaGTsLhK0WPDnzRcRbEcws8TXUyE14+9UmQhP51kRt3Oq8QVyV3nfsoDK1UCag8TytsH7BAD+PhT2T1nutsb7JDwhwkBsfjRhr7JtaHColj0vJ9AxagxUTm0LF1J6UNe3oCaeHq+gKy3b9AgugOb3q0u9IXM3MNa4D3o7A86HyULEelnChY/XvL2bRc0A5U1X2/9YSbRVXbEFuhcvMljeVqLoyk02BSvVfafHBJN3AT85/7wLJO2kucCWRikSyT0p+aT5Rshkn8zdByU637/7Kf64AcyXSa3+F3SmwwhbV97IObjOudQOf14+5uQ6rW3qaJCwKyLlxEQTS1STJI3Z9EkTogpTa2T+Lc4Bun17xtHd6zRuB+eCwNSQq8r+aY25zldeJi8JFB+O69m6c9kXSJDxInLh1GEogW1pQ1qqzW6a3jLTC5DiAZoFCBms1Jr9iCh7IdfVlvVI189Yt+cB6F+hxHSLWqHVt7XhjRGslPemg/5LzxC0jXyxNta+bchhGdEWaYAYc3QQzLJBRRp/JlGBQHBhRMeqd5YcZTU5Mxu4/uYllErcll1G1P5rl7QAzDT8K4xVrmCs9mLZtezbRGp7Evc2Q6CQ5sxqV+MLbzsXUNg2n5De85qRPTQ2GjbV7JR7dw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODExODA0Nzc4NzAsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTg3ZDNiNWZkNjRlZGMyNjM2MTVkOWQ3YTY2OWJiYjM3ODYzODdjMzdmN2IzMDlmNDE0YTgyZTNhY2FmMCJ9fX0=',
            'trail': '',
            'op': 'true',
            'speech': "My powers may drain my lifeforce, but it's a small price to pay to defend Gotham",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
