@plr = player()


@hero = associative_array(
            'name': '§bG§8o§bt§8h§ba§8m §bM§8a§bn',
            'class': 'gothamman',
            'sig': 'SDrvLan7MDvSXsrtTdLmn/mU9EVEpG6IiVch0j7IRoNWrbpho61x6UbnA1IUaPV5XA3EXi8p+tTT1fexGQfjEV/ld1wLDAveWe6J0zaspwXSWbb0TF7LtxTiSfzRXQTYh3QKCReQlZzX53On5Y2kTONeq5UPBNDKMBTFIraE3hKV9hpmWEA1VEMx3wRRQqH4GOw8Qmx2PTeQ7pxYIamx/xnboVLXWw5Pb3V5qc1WTelcOoj48DGHRzIrUa6L2zeI7sR64v+ofosMUwiSk++jmku9ajnwLh+i5l0AuCqA+U/aLStdepqaQp+02LsmzB2tv3XBVIvscIgN7bZWgxGeNjM0Cc6U5TOE4f2seDyvq9neMT0LGtq/2y5M+CKLipXRfZJ6NnpfaBVp9g/Ib6p0NJFZr+dPUfC9p2ZNmwgl+IQlYFZdhmNYeRfCQvmlo8Kjd5ef10pi4jfVba86Q8nxHXaLw19460kpAoh9KAk2esm8yxpIO9rbCH5ex2ff58XCRYAfRNryx9jImnacgtEpcrFztswC+rTVHNpE98aJFx77uuZW9RTVJMi6c3P+XO3fpF0480rOvxCR9jZIl4IW8jJhmXftAzT1P4L6ygbTNrZi2YlQu6Ow/vYZeR4Fe5+oLiPNalTS9n+cOocUeqwNIVY2QSfnYlIzzfsIgjOY7iU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE0NzIyNDIwMTksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJSb2JvQ29kZSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTMxYTVkN2IxYmZlODM0NzY2MGU1OGYxYTgxNDVkMzE3MmQwZGUyMTMyNGZmNjg1NjU3ZDA1ZDQwZGZjYyJ9fX0=',
            'trail': '',
            'op': 'true',
            'speech': "My powers may drain my lifeforce, but it's a small price to pay to defend Gotham",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
