@plr = player()


@hero = associative_array(
            'name': '§bG§8o§bt§8h§ba§8m §bM§8a§bn',
            'class': 'gothamman',
            'sig': 'kR/z4B88NWwA2w0CekEkHZ5h7Jd/qkk7sqRJ4Yx51W8JltLJpZoItqqp+Vx3cz+u/lsqYnZgRWH+XDboUo5ksV+OZsmAOTSWOpPaAG3q5qKvqQEYgENjMlaO2MdMyye86mpQhMc726XV4zpfJvbQ/WSR4fkY0KBpHEiFtFPc2DbL3TkfccHMhjcupYikYWIIJfZduDKL2W3/AJX0LCpeOF3Js0xYUKyN3UCuc6MNN9Fbx4tk93JAgR/3eC375/DhQ6BLa14XOegr/0tRcLszupQm/6nu2GKUfC19m5pTIWCZwkByrDgYkLc3fkIhy4JxyCYbaUdQlGYOuThJJf0vnXJOnNSf5au1RNa82Zg+lEQBiQTuKaNBipsCJQ/d+tWlKf5HlFj1zwDVp3o6A+t7LEKmu2+UfQBPFIpHBlM3eDOf0z+lZnjuBqkc4f5UcoJ4AQC041bJtEY/HlZTyvbfWvecoJirHaDhz4pxdXbf6NwGqzG79q/wjg4ZymECra8T10aOF429/o+ppnKIYQyc9OspXEtUeQX34yZA9kd2hiP3+8gFmSZByTOFj16DtGKa4SZWHwR1uUVwhf34WuRDd1NReshum8n27Y9hQZd8KgYFLIPshkjw4NgavJ+7pWUvfW4VIF8++NjVbYMoVqFSUW2CZJB4hqGeEb6u8LOu2+g=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk4MDA2MjA5NjEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJHb2RfRG9lc250X0V4aXN0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hZTk4MGZiYzM5MTFiZmZhMTY3NWI3OTE1ODcyOTU5NTVjOTVkOTNkYWY3NzZmMjNjOWYxYjYzNjUyZjg5MyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "My powers may drain my lifeforce, but it's a small price to pay to defend Gotham",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
