@plr = player()


@hero = associative_array(
            'name': '§2Gre§0e§2n A§0r§2row',
            'class': 'greenarrow',
            'sig': 'Kwulj9SxXQE4RI26IWFHrj5DZ2GTMbgWb74TCLvZ8ICIOW+34ycJWVl70L/BJ8M09GVKkIQAcNe9+wwz9G0ijLXozYTvSm5I6pn4Wt081Att7+yzm7wZjGGqJOdjSPKpcb7hM1Zj/++N051qaHTWNwMdVBfBojHtF3jskntycUdVXEV+ZjuXa4lcrfmlG4JbEzRPjc44b/GL86mW29JiKKPMPstw1AClea8H8GalpmXCFVj4yrYP5UteiME9758uFjhQPhZrhaAeXZ259ZrpVN1/oyGlmaD/QfDxgDEBSmc+DuqusO6Ak3mxOV6uxfjzFLwFDC+tBdjTms8X+qfqI/JyFrnSm7FCc9ueOIinYIF+ydMmg1tDJP53dwQWpWiVxI/zcwzblbdFmFv7v5JASYoI80G0SI1Wn5gLTUWMaBgOYXDVrMWbPqXKmHfHe6JvqWDpzoIEQV82QVWq33nhqeQ6kyL1ZDiQvLICN+Gz50dsp0bGTp9yNlf5JoMWmvDmImbzwf5Gb0mJ1yY9Vo+J/rh+Oj36HVuJ3pW4IAxcryvo6vXedlju2Jt5jsJIR9TydBigVXXJkm5Qq0w3mc6heu6R1RYZj9C/OW83j7ldGxB20sItk+KiqBjhJsIxMdsK9NEQvtlkW2qG38UpGCbhxqBaCJcxvPv+gsvXhu1V1Eo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTQ3Mjk0MTQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQ1YzI1MjI0NTNhNDk4OThhMzY3MmY4ZDNlOTg5M2JhMjU5NjdlZTM5MTJjNzY5MWE5MTJmNzk3NGNiOTY5MCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Robin Hood, eat your heart out!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-3",
                "/haste 0-1",
                "/arrow",
                "/arrow regen",
                "/arrow regen long",
                "/arrow swiftness",
                "/arrow swiftness long",
                "/arrow fireresist",
                "/arrow healing",
                "/arrow nightvision",
                "/arrow strength",
                "/arrow strength long",
                "/arrow leaping",
                "/arrow leaping long",
                "/arrow invisibility",
                "/arrow poison",
                "/arrow poison long",
                "/arrow weakness",
                "/arrow slowness",
                "/arrow harming",
                "/arrow waterbreathing",
                "/arrow luck"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:bow 1 50:1 51:1 name:&2Gre&0e&2n_A&0r&2row's_&8Bow",
                "/give ". @plr ." minecraft:ender_pearl 5 name:&2Gre&0e&2n_A&0r&2row's_&2Grappling_Arrow",
                "/effect ". @plr ." 5 9999 1 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true"                
            )
        )