@plr = player()


@hero = associative_array(
            'name': '§2Gr§8e§2en Lant§8e§2rn§8(§cS§8)',
            'class': 'greenlanternsuperman',
            'sig': 'j6poijHDRNxoqhPKnPsBjfazdqyxWErjigiCK2AC4EgyQlLzfbLIffIBr9s9Zv2D4AxGK4EazEg8N6dcyJfiMfhdt4rx9fpw6k2/OE4iT64KW3kK8r353ECZX3+p6QbBeZ4T6NtAZPpneoRV9upL32ONGc/pUXTjoLUcxnBRq+B2WqK9jyU2Ib7yQ8kxDNWqRNUPmGxJxX/nODqOMr/xR7Ib4+TXmCAgUTHMi8aTpZy41NOkew6FdGo3CVIRlh71ZrSLe/QqGJ9mJvgzefvAMuQn8wkSB1OH5zLWJQKGRD5zdvJAsuiCcp0JAM7+kN2SgjUiyv6ZfRVWXzxm9g22ftelWa1rWJCTF/OkaPpTZAJJNYR00kOyntry/60o8UdRoJm/H5X7lYFqPT/nOdN4D/udDX2CuK0pzPFCcTb6AtoR5dXD0mgn3GsOLBE9pshS/X1jipXFwTbewxYowaIgl/G09jkaR5zYM9zngF5AsYdSxnRy65Ridh5BZhoDlnNfHQnHN1MDqeOPH0fU+JyiqBEYoBhwPDIirJ3sRE8HGSZx5pbpzyVZGOKnioIiPamt1QBpnPXDHE7bX5CYs4CAZvdsO2KrIkVMnaK1mOKV0MaU9yCQ3JbgWNGR1Lh2hageVT3ibtSKfTgAqzf/ruZGn0GdPLkKruprErMTuHJM0p8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDE5MTA2NzY5MjIsInByb2ZpbGVJZCI6ImU2ZGU4Y2YwYWY0NTQ0ZTQ4ODJmZDk4NDQ2ZjRiMzFiIiwicHJvZmlsZU5hbWUiOiJScW5kb21QcXJzb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2FhYTNkZGE0MTlkNTIyNTNjNTU4NjlkMzljMTlmMTBlYTRjZDA4NzIxYWU3YjI1NjgzZTFkYTc2NWRlZGRiIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Kryptonite isnt the only green powerful rock",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/break (breaks 1 block of whatever you're looking at, including bedrock)"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." greenenergybeam",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
                "/give ". @plr ." minecraft:emerald 1 20:2 16:155 name:&2Gr&8e&2en_Lant&8e&2rn_Ring"                
                "/give ". @plr ." 95:5 64",
           )   
        )
            
           
         
