@plr = player()



@hero = associative_array(
            'name': '§2Gr§8e§2en Lant§8e§2rn§8(AS)',
            'class': 'greenlanternalanscott',
            'sig': 'SGoHUu1pusA+yaQ/QLAuLClXpsSOU+Impv/gJKwuM7XWvAvylEmyw7OE+M8gKvAYF8HBZ2QerJeLYT08jo0D2Aw6JZy51xpTSbCSf/YX5Jz631TJrPVSgWhnzkqKRuFqXrOFSW9ovXamc0UTki2KjPjM+ZY8ct8i2qHOEVvDEIWxU1EOppKCQFxGlvt2c61VQD6FVHATKa+NqE5VMLOeJDOwoBowyrWGqyPyLs/BIjXAsUmrD1nZbdCvxvjRUHlHoMieYl9IVRJcr//W99gePJqe0P04gEeeOYvpyVfh+nYLcxIwsC8/AX0lV5tfD2DTSgjt+Goha7CbOs+H7pQpKqpSEgP+6nGbngfT3LhGx+nm5c8YJptkJZ70Utqh26c43naDIvZVQupJqcb4SwW+YnRXXtSBH396uvyj6QflD+jO3ABYLhwwhAVuim0PQ4puQi3npp31NBu5iqC7cR2ec/a0e7pgUeelwbD2nX/4QC1Ubpv451SekGiO4A9wq3y8MF44qIKo0+jw8fmASSk86SI3QWrps8DBRosBSy6hHzaFZV1IeW5irWUeXDqQUJAo+7sZDl3TPBMZCLedbDf7zYtTqw1srjb8Q0wnLbIbKTRNDOISKPzfB9OEA7+wST51ADFllv9Jw3FUEgq5S+vwAXqXpjVdPL6BdAPvOP/OvA4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzE2MzQzMzYwNTYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzc5MjBlMDhlMTkzOGMyNWExYTUzMmI4ZmIwOWQ2YmNiM2M2OGRkYTg0OWU0ZTY5MTM1MmFmZDhmNzBjNTJlMjIifX19',
            'trail': '',
            'op': 'false',
            'speech': "In the brightest day, in the blackest night, no evil shall escape my sight.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-4",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." greenenergybeam",
                "/give ". @plr ." 95:5 64",
                "/give ". @plr ." minecraft:emerald 1 20:2 16:155 name:&2Gr&8e&2en_Lant&8e&2rn_Ring"                
            )
        )
