@plr = player()


@hero = associative_array(
            'name': '§2Gr§8e§2en Lant§8e§2rn§8(HJ)',
            'class': 'greenlanternhaljordan',
            'sig': 'Uu/s2BKatMUGgvb2nZnEdsNL5glQpOaoYcuripH59JAG2eJ21NRHl4gkR2BKUyZ7yfWk3tdfQH1S2cDqXCD7UIBPdQ7byzeREBuzDiKhbaZwN0xuqOrl7FXCpHIOTUDfuKsleDokXaXdDcKLVnWbvHC+ulFjegTjgR21IgoqJRylI/qB2dGwnqxmyjS9cnzQ4sby7u02nqD/fOZ/Mf5fw6JHdQjbWsdtEbBau4ztyANw45DOsYvc5H0Ns8v+qwldXaLwaAnR+LKqQTBxNuqNKd1XbWpOv/Q0VH/4vxBYb8yMrSchYbqoVmiCDDN2BOHuGevrnVPsbvQMZErZSLz3QrltuAOyZKeYLb/Ay2pFmbVIhijN3Ptwx0YIc8hG0l1J/wiw9k+63UZSIYfXrs0JWMRe3g6ppbLfwgNDwSq4LI1SGyYYA84sO6HlafD3ZqXXHvlvL4qvjNVbpf8KXsMIQlAvIBudkRZ//FX080IVxkEeNS+ZAdfBR21ZnVDZ3ONJOzwLpmkqjDxaTGALsigC0zl3TNCAAyGVK1dMkIaPDY8illj7Z4yawWHm9sbKtWoPr7ItkiwCyxSf34lO327nT4MkeAzmllGSHTPlmdTv5VDnwxb13lwQfKkjJr3TZw3J6s4w+doP6jJb66JVZJ9inNc6sQ6AYCOyTOF7SOqRrXQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjIzODEwNDIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2IzZmU1MzQ5ZTJhMjQ0YzVmYTJkZjI5ZWQ1Y2Y1OGQ3M2FkOTI4M2M0M2JmYWIxNTgxMmQyOTQ5MmVhNzQ2OCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "In the brightest day, in the blackest night, no evil shall escape my sight.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-4",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." greenenergybeam",
                "/give ". @plr ." 95:5 64",
                "/give ". @plr ." minecraft:emerald 1 20:2 16:155 name:&2Gr&8e&2en_Lant&8e&2rn_Ring"                
            )
        )
