 @plr = player()
 
 
 @hero = associative_array(
             'name': '§2G§8re§aen §8B§7ee§2tle§8(§7BO§8)',
             'class': 'greenbeetlebarzzooomm',
             'sig': 'nqxRbbWWZPgIEFeRbZI/BRoCnhkCMilkkaH2838qTUTZS2BJu5K39v7EFoQWPncmyAnPyEw7ZMfuSbBZiIJ0yEOkrs+zbYbvm2GK0nkitrP4n7CmZCtOSDjyjsEiqdQ3w5qD6plcGvNqv9OGQkAJHgQKxjqRlrYE4pd0GrmLk/LL6UVmP4ykzZAeimeGT1xbCP+lf+QZWuVWf2MZsd/UFC0BhnOwDUKyiusyzGj5heuPnlZvGXvMwGC3Q5DflO5rrkPlO2WT68QgZatUM1DnD9c2L/8E2T9daGVoN+djdlJv6AD0umyYJFHwMHGH3B0qqivkATuftTrcORI6BinlZ2MIqbvNHAJFE9pjVNy3Zgs7NNYpa5CSyCr3v3y/bEZ+ZTHFOkhNlvyhU7FVI6RaAbKFDGOlThM9IA/Cmja/XIeb/hjscSEaALOBK5bkgxLcbKNW44iwlgqL77s4XiPFic8zz98LP/ZULOKOmFdEnLeWP/wimQX6cxQ3WmSES4KfavVxosnwKRuIu+j4PUqNIfTJl+dc1BHjOh6OYBF7JMuz4DIFvh0GM8+OWvU7cgXUlERBiDf3vPM32Cd5rECOK7xFo1UcuHTsD9wv4qIe1nDxTpGXrha1VDx3kVoyVaCkr606uhCvs+wNThGG4QUAYZiqKn+LO5DttWn2hGIjiSY=',
             'val': 'eyJ0aW1lc3RhbXAiOjE1MTE1NDYwNzg1ODcsInByb2ZpbGVJZCI6ImU2ZGU4Y2YwYWY0NTQ0ZTQ4ODJmZDk4NDQ2ZjRiMzFiIiwicHJvZmlsZU5hbWUiOiJScW5kb21QcXJzb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzI2NzI3OWM1M2JkZTY4ZTljODk0YjIzMjhhZWJmODA4Y2IyZDNkMjgzNTVjOGFkODdmMWYyNGFlNGEwNmMifX19',
             'trail': '',
             'op': 'false',
             'speech': "I'm a beetle!",
             'powers': array(
                 "/buff",
                 "/carryplayer",
                 "/dismountplayer",
                 "/jump 0-2",
                 "/run 0-2",
                 "/haste 0-7",
                 "/fly",
                 "/intangible",
                 "/tangible",
                 "/speak <player> <message>",
                 "/mindcontrol <playername>",
                 "/stopmindcontrol",
                 "/invis",
                 "/vis",
                 "/disguiseviewself",
                 "/disguise",
                 "/undis",
                 "/confuse <player>",
                 "/mindlock <playername>",
                 "/msg <playername>"
             ),
             'buffs': array(
                 "/effect ". @plr ." 5 9999 15 true",
                 "/effect ". @plr ." 11 9999 3 true",
                 "/effect ". @plr ." 21 9999 19 true",
                 "/shot give ". @plr ." greenenergybeam",
                 "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&2G&8re&aen_&8B&7ee&2tle's_&8Bl&2a&7d&ae"
             )
         )
