@plr = player()


@hero = associative_array(
            'name': '§8G§7r§9e§8y §8G§9a§7r§8g§9o§7y§8le',
            'class': 'greygargoyle',
            'sig': 'pU8YDtVxJ/f2wbUgyxosVx9vs+YxSzoMIhRBOTvzX80DZaXhEY7+aKUSMc+klXx5LVsqoXrX+pjJy5In2cVSan0g0G34zXemiTV/iFkGLnB/aNGcNAf4htnMhLKK3I9dxdHx/+DPYkHFFo2gKWIlJ6D+Gb9ksBjQSFNZ71h6pYnr5xEsqDuDp3cI/9nEv8HfqmKpPEmzSA8Sly28pc98z8KIqr1y1UGXadZ0FXr2KeYdTdUN68fX0+NIGvhUWMtekdEsMsl+zPZPCqNHY1uzQZIlw5apuaaXeauFxLBeFI+IBwiSVQEz3kvrDdGeayGHV5bGXno6xe7hpp3qB0ySmY9itw2VbS9Wd1H9lRMtE5T+VQtdzWNS3Sygj122AubxhN6M54PhvC39CxYgu7/PcEeQ8jB7xWXExobasiTRb8Ns1RKwV9THTsZk8GT9Z7HGfH5LVmMpYm8zQaQEwQ94t302FVsBKo4nGq6xu9NlB755AI0pogkBVL3EvuKw58gLrxM1QXR6wv+VlWFX0FKTkcXf950F56nXCLbZjDQhweznP+PUtNwqKQq9FX4i48oZElLTZA1eTrFrpXt9sH7nY4Bsk69xjC7DGxYjjwgJThkRJTVLLhveZqTs1Mx9O/uvsNNHN0fUiVVbsLkxjMGIRsyRS0SPo+ezF2pGn79bgik=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTEwMzEwMDMxODksInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjg2YWY1NDEyZTc4YWNhYWNhMTc5ODdhMjQ1ZDE4NjY3ZTZhN2UwODQxZGZkZjg4YjgwZTMyZjAzMTFhOTUifX19',
            'trail': '',
            'op': 'false',
            'speech': "With one touch I can turn you to stone!",
            'powers': array(
                "/buff",
                "/cast groundpound",
                "/cast stonetouch"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true"               
            )
)
