@plr = player()



@hero = associative_array(
            'name': '§fG§8rim §fR§8eaper',
            'class': 'grimreaper',
            'sig': 'RounD/kMQCe2K0bKXcccYqFbNbVU7HI1sOwm/HvwrttITp6HOoDOe8NVJOxW2voDWDFn+ZQol8YFDESRiwt+VF+x/C64nKjJFuniRWT+/3/9LyOO0Xnwdyo/aIXqwFmgcKKTz5aCc6JiAHPSyMJ7S/eeC5lV0QcC7yiwqK3tLVRw9zGIn4jToehFKN/c4FUZ61b0eDLOlNbQsMm7vL7Sx159cIyhNc3UXVsiKniXYy8MMg2AKdV1UW5q2qi1A6O4G7gc0APLBsh/8oFR0N3P0qanlVQCGHXyd+j6cW7xwX2dGkVakP37H2RXFmEVY4pP8ukYPPy4tbYAs+LdZ5jo8ioYcG+es41wWp8hoYCO6VqI2n09z6+TLArxT7g7hOmte/trN3hvz4XYaKYTTiPITtyiZYkVTKpv07GvhVqiiUICnKZ9ZJQpdJYPF7yaLLEaBQQpez8ODVKIm0ObNPSXhKFm9SRAFYTfMzK+c+zKuoLvzLRNcZLEBTqIYwtjAn6YzT5+oU28wDxnfboKI1VEViIcntoZfDmiNJoIyxalsqG6UhzX1itBa//B4m5OIjQCPQH3FVyoMKdgT2LeGNwJ+SedsNNSsjm38cSflFHQnasqE6L473upp3HQJGIb+8ePzYQ7zily6Rav4pTG2yVUJXDow3ccpkf2JJ15/uoN8Yw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAxNTE5NzUzMDAsInByb2ZpbGVJZCI6IjVkY2Y0NTcyNmNiYTQ3N2U5MjgxN2JkZGQ3ZWM1Njc2IiwicHJvZmlsZU5hbWUiOiJXeW5kZmFsbF8iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81NWFjNTc5YzZkMjUxMzM3Nzg5NzFlYWM1ZGI3ZDhlYjdkZmUxMjUzMzM4Y2E1MzdlZTM0MjViNTcxMTEzYTAifSwiQ0FQRSI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzVjM2NhN2VlMmE0OThmMWI1ZDI1OGQ1ZmE5MjdlNjNlNDMzMTQzYWRkNTUzOGNmNjNiNmE5Yjc4YWU3MzUifX19',
            'trail': '',
            'op': 'false',
            'speech': '',
            'speech': "I have been and always will be death itself",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-4",
                "/haste 0-5",
                "/touchkill",
                "/fly",
                "/fly speed <number>",
                "/tp <player>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 254 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:golden_hoe 1 16:255 34:255 name:&0Re&8ap&7er&f's &0S&8c&7y&fthe"  
            )
        )
