@plr = player()


@hero = associative_array(
            'name': '§2G§ar§6o§ao§2t',
            'class': 'groot',
            'sig': 'odbNLFNNFpYxoSJJu2hpAwj2d3gdeHgI/SJn4SpF0CPR5l3z/SVonAt4JiNRHbsPvkGU3LQNHGTXvpcC3HFd98sToi74zhMRiGtgQh/n14IqrW+1uMjm11DHzfzNbuA6xTTnHd7juBprr6lmyG6y5CFQuSttFelOkMUX4O3AO7pkfRq9b74zgye4kPF1Q9XfRePaZKhHfGoz9QzJnLirOL/iWZ40NhmgoGMDieeirFBYmSgQZBjhUlO9Ts9rG+3DwBJz+UbpszMk0wW0A3jnlw03RvrweomjJpnrnAI4ka1xHN89sMptEhwq1gCn/YKdBnoEFAnPAZKJIerTEeY6MFDdTq6xG4TcWwUHbnjLOCD65dqPFuEYEOmsUSIy1NcF+8FZ8nHPpm2moMtmN/cDEByUx5cqO8OMa1Jbocp+EWiAGJgg6eY+HwYPNHwPw0PaC+UiP4eS1aNNs4GeHIuwDBMRelYQcZ7anyqvpdItJqIEecvyO2hbIY9582HQuSzShWlwcYlu//6mD6dv0hET1aW9tPV3U8Fy+gRQulXnrDxLVecgwFY9pelbM9Z8PZx/1JPCkFgukZ6BIwqvyGFL1E/8iSfO8GwBCLQ8X9qCZ6yMuar+cqJMXfLVVmxYknwqL2nEkeZW5U9TkIZ4pY9runlF0wAwzwx/OFNI2YuRAWc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg3MTk3MjAxMDQsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJXaXR0bGVUaW1teSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmJkMTU5MWI5M2I5ZDMzNzdjOGY4YzJiZGM0OGIzNDIxYTNiODhjOTUxN2Q0NWRiZWVmYTFhN2Q0ODFhNWI5In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I am GROOT!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 7 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:stick 1 16:10 name:&2G&ar&6o&ao&2t's_Damage_Attack",
                "/give ". @plr ." minecraft:stick 1 19:10 name:&2G&ar&6o&ao&2t's_Knockback_Attack",
                "/give ". @plr ." minecraft:stick 1 19:5 16:5 name:&2G&ar&6o&ao&2t's_Damage_&_Knockback__Attack"
            )
        )
