@plr = player()


@hero = associative_array(
            'name': '§7G§0u§1a§0r§7d§1i§0a§7n',
            'class': 'guardian',
            'sig': 'HLnkoGMh6YFQTmOQ1PH+yuNzZnmnsrJ58YS6ZEU0KihedhHA20Q5fwWSx60VJ2shawXLXgujyjP1XIfT+NY5oaDexCoA3Zb0AaJZc00s/K2rvWP16Wb9bjDLQRhNuc9PBdIbOFluhUPoYMo/6lu6vb1pPVJQosv9Qms3K5o9Ir49L2kBRGEkrr5AKGGqErsVV72kaIf/JqMNRtNsyqMiamEBSt3dl55mrg0BTacET7j0ofTyZrCepSwnlDc7axGIMkj+1Iakt/D+9txs3YY8tTnN/emFmeudCwOGbHoXrHXIcsm3qgMn9dvWLLMDZVWVNaFAC/DG7PMJuIkPLk1hLElt6bOk1RKUkcpZ2qBe2dlHZrOfYyNieaINtWO4EpOLy85If/PUGtyJrlgPaQHBdFnTdh8Bk2gYcMOeITsN11WAIIj3oegVDpRYzVF2ZdYfyen+T96dFPPrYZzXJ27phnCZOmK1skpNAxKQo1OuHksrLBpU3OwEVCwk8y2zomLRXdf/2C8FI5Qm2mGochnXHo2MR1im4oeuWDGijyMmrkUHUUjmOEUvJPYObgSDrY0tQAF4H51eU21ZtPzIxXJ8/qjqP7u78J15eMKqMCbyLth97BUHBHpKYESfkrDZlusraM7TdnV+MC26n1ff9bTlGv8CGpY27q3tvS2m6wGQ1+A=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDc1MTE2NTk1NTMsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJIZXlJdHpUb255Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzFiNDY1NDM0NGM2NzMxNjY4ZWY4NTBjNGM1ZDMxMzg1MWU2NGUwNWNiMzMwNzI5NGNiMjVkMzc4NzUyNyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am Guardian.",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 21 9999 4 true"
            )
        )
