@plr = player()


@hero = associative_array(
            'name': '§dG§fw§de§fn§dP§fo§do§fl',
            'class': 'gwenpool',
            'sig': 'PyoeTKB2mL+Tm3TzfLiBQ+MNC6e4hMfii//XdTdlO1hWFEwcEdTCFU+NsmOVUTDhbEdspTTLDJdvQ1xRky3dUsDki4HG4OQNesgkt3A+tihw056kdJXkUuImBFPh4Clb7GwL0JXJHQZ7Dg+Xz/e+VTMtptO3DdUPITyBHAUZ+lzAUR8JoL0Mn38DQrbgvOb7yLBFwF+cFSVP08+juLmAsLHfr+A3CVvy0vVWsU0XEN2n2rZHw1lAvnsdxBw7EHr8Zn+0kCUIAk7VrL/jCA4l1ihCVVq+njfxFXeevrCFscgrAvP6yqiM/3e3bRKem/+oMon7CT1aFGmi8slvSTO2FBhEYLVTG6pQxr+hoRDiaq01dumwzAt3ukj7RdIye/eRw4a6nuy93MDE4+t5k+KSpnsFxudp1I9JRXNZji+Oqn/4uD+GYsowTwrZfch3FkXKP48uhQQEycX1uy6F2aoabmkGeb/wLYDgR2DY84Ep/75bKJxAOcVh+IeKu5NJ8tDlp8yQQ3ocS/Gbl3HCnOTJIlJHOha6d5MWtb66tHrZTjgBGZxNQbqArbm7b2b0nntg2Dhgj24N+K/ngsD4lSOYBD8/tNR0CqaAZBfRKOkmpNRHkP5KzT0g3vR/04Urt88/Rwl1Yj1NETW3rrlcOy/BJtPyAeMlJkv+dzbcVYzH4Hw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDY5MDk4NDMwNzYsInByb2ZpbGVJZCI6ImE4ZTE1OWVhZGVlYjRmNzNhMjQ2NTkxYjU4OWFkY2Y0IiwicHJvZmlsZU5hbWUiOiJNckZsYW1lWVQiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mY2VhMzdiYzFkNTliYWRiZDczYjhiZTUwZDNjMzVjMmVkNzU2YTQ0YmU1OTllM2Q1ZGQ4MzUzN2NhNiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Hey ".@plr.", thanks for choosing your friendly neighborhood GWENPOOL!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 1 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." pistol",
                "/give ". @plr ." minecraft:iron_sword 1 16:10",
                "/give ". @plr ." minecraft:iron_sword 1 16:10"
            )
        )
