@plr = player()



@hero = associative_array(
            'name': '§0G§4y§8p§cs§4y',
            'class': 'gypsy',
            'sig': 'XB9f/LXDYUV1Ua8uVKaYZ2M4eqfEDV/9tG8IAnm/befZhGWmEfjIknpKbq5uIyvaJPVLSobRHPqCCt/5zDZunSiXZyTu4+d6k4HYCch9uM+NuzDZSvUcOa+o4HGx9B1g+9te17+S1fUmK3/YFzCtVlf/HtH87N0FjzQaNX/77/GQ/Kblcmqt0xcfrCNL0PNnGTxxMrbdRMVXi+Yl2ke4l2TYme0ALFPVlv6RmcMmPAbTcrirzqYAd64H/CCgeMIBGhLj0m/bonb+yQqT1AbEvojG4B2TO4LVOcyP0ctgHrm5dQElnZd4Y+PsI99EDj7gcWvx8a33Vl2uDR5ojDB77HuHPUalAQ8Qk9b0dlb8A7jtFmobao1IAt4IaUcq06FZj0N+2DKfNmovvAsbXoakTcTAk/y6kmfwUSDWeSa6mDMqWnBheVn3XenDn/Y+JL3nrYYXwr5SJJJKy8jUzLKpzvYHRXlpaqVa2E7AnekKPWT0WftoqUtuZbdAfPXbWIygeLZmx5widfJWdt+71jO2GvAXGnG76Wqej73TahZ2edNP2+vL+MduW+e3dM8hmSqps1CNxsx+ZGRgyHImonuXa7veP8x3w7ERia1dsS+y7F7vsIkZIekVThNHRD1yEEUlM+lJQM+BioxP7Fnr522yZTnbIP5pQ4GbUSrrHsY6q+0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTM1MjI0NDU4ODksInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJUaGVfUmVkX0NhbmFyeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2QxMTQ4ZjJmYTcyZmQ3N2JhZmMwMzZiYWQwMWY1ZDNjNDZhYTRjYTQ1OTM5ZDVkZGY0Y2ZmYTBlM2RmY2YifX19',
            'trail': '',
            'op': 'false',
            'speech': "You will serve Justice!",
            'powers': array(
                "/buff",
                "/tppos <x y z world>"
            ),
            'buffs': array(
        )
     )
