@plr = player()


@hero = associative_array(
            'name': '§4Hades',
            'class': 'hades',
            'sig': 'FsZNvFSOLUftm2x1ULYBi67MxVC8pTqgep4WQypoV1mvfC47oKin0ihZCOMg7peDslXSZ/fmAKXyni2UAIb3YRccBtQvjrWkt19n8gSPfuzTcwRxyZWHolve4l5snO3jBv2bwYYmQt8qiwcuukuK4jXEfYOrMTcco65Zt2OTvfNGF/GZj6fnvmcMxRoJAu2R8WAhwWtHCdXtWgRR0pvcBrABuBJ3ew5nDB0j7we1GD9dYHqKL8XhIVK+yzNsRraYukMcSHsNbW/73zNEFi1oEV884Ywzcvav9go3kCYUX164+cgZdNK/MEEpe1RhK+fgtV26Lp5uEWX4T+Oyzz4Fv4CDmkml3Vzr8bKnYrwi4P6wJvDLGQIxMGED1KD0roMFCAVtSBHumK/BI+K+ve9WGHfsKxPBrMpd8fNlexDpdVfXUOyA7drG/cW5hzxFSoAubH0Qah4OrSI73ZF+StVIz6CE6g190JtUDYtwXjnir1vq09GnfzXqdCCGa+Oa2OCJrSOO2cZkl6bEZufY5tG7kUHHBV9DCYePl6hlRIIXl0HzF7vVT5IeAaMTDHTobbGk8ehehjT38DNcatFqQ5+AvaBveIotZbRDhiFaVZkMxQfJ3zq/PqZ37sDWGLjIJisUeSWuKsMFP10xN0VjLNG4FQPCTLN22aI5dZ5/RHIuTXE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjU3OTExMTgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzliODE0MzdiNDVhZjI0NjU5YzIzOTMyYzMyOWUyMjRjYWQ3YTFlMGEzOWVhZTE2M2UzYTk5ODVkYWUxMTIifX19',
            'trail': '',
            'op': 'false',
            'speech': "God of the Underworld!",            
            'powers': array(
                "/buff",
                "/haste 0-5",
                "/run 0-6",
                "/jump 0-4",
                "/carryplayer",
                "/dismountplayer",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 12 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." blackenergybeam"
           
             )
          )
