@plr = player()


@hero = associative_array(
            'name': '§4H§fa§0r§4l§fe§0y §4Q§fu§0i§4n§fn',
            'class': 'harleyquinn',
            'sig': 'oH6W0Bqm+1ULpnqhdCNz01wmTtVNG+SboLlKDLB/wSCmVmg9rWOqpUoEuM8PWSeF5YyafPb4QxJzfkw8y6d7x9M2B/taIquH89BgiyaSscJt8evfx+0xud7FEwSfnP93YkoPecoByjma5rJBh/doEpvOFOFz2jCsnY8pqBVENF3YqOl0uG9NS1Wt8/NGnboYf9XdZgG+apmT8slxwkMpEyCPIGkQu05liLrtszV7+O6l1/WlLiMnvp/I1vQlZ4qm4DMZaSyXsrqoX/aLubiBSylBccKtwgoRFlAzKWpTuN44udomDXN0L6x/2BJh2G6D/Klbd4/gn510PdBU40KuRAJkqEwiZTB5ZkKg1rjrXZ4GW/moNzU8OE8zJeB3Q+BBrMHQ/gGLaLWmx9w7FFLQlgo7KBwVOtqcJgpUeXMXIugTTweWqeOxdgWETm7KwWiE12o51ge8MQCFv4ZPqE/SWUi9kYeDAUVbfHboHQMNe+6vzZYyBFuj/mvOqn8SfZ+Mha9qXb0M6iou/NnXdf0r6K5RX0CEehgx2TWnRUQVComx65VHgOylfs0lXx/bpZ9izdR9szj67wqLt7KfTDFr1aPXiqmdy4dC3kddE0aTm1dNZnBfwKhuP4HxnGq+To7VwoeuoyDL8y3fpBK7bHYnIL2iApP+YAEL0eLTu4NuEQU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NTM5MzI4OTksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xOGMxOTI1ZTg3MzA5ZGJhMTIzNjczMTQ2YmY4NTU2Y2U1YjE1MTdmYTdjMTEzODA5OGE4NTNmMmYzOTUifX19',
            'altskins': array(
                array(
                    'sig': 'E88ui1ZPDkw6NrB4eKFuUsTNg0fVLJmncuoX7Txw15Mk62H1yRc+nu5aSjFA4XSUgvG+fdFiunjrgY1xSgNVdEt0cM0G2U36ySDq80dLIl7p8QydT0k6jyXluBZseKhlJecfz6prHyn9vbyVdf/NfzPqt1sdVC1Jd3CJYxAh98ukciRKKocEjnYx17cxpINeKgep43E6+mboH2sXQsbUgttow2hNeTGlpY3GHrGdyz63b59X1e6Pw9xG2rCs/DboW7KZWqoY6Q5pRvMYu3Ye3i5xlmZc9DpYfYvwJffz7PCfTn+rqSYYW5fqlJNwmdDezBEW62MRohf10igvBUUoWOLhGCgyroe1AKN8kyRVqIdn6hmK5+V53wCE78Exaq8fc1J9crkvbcvuBeSTAMCZ7wt3TrireitxeEV3ZyXkMpLacFqAR0+5p5ssO1k2H4mqVa+wY5tXjfSimfMnsIUoKFlYB1aLQCXiebfZznbjgtf36ha8EQjzpnNukBfWQl0tJ14eov93ouVe8TVnoNTFSNdA5UwzKH5eeUYAZda5P67y8+Q07TRJE4l1jMHlbH1sY0k5G+x9Ly/Esf10iGerpBwiZqzo0IV+4KnKYAmrvaYVwl8wGCk3l+2ZMAlNburgDlI3iMM4EpFiinUobuxqfWpGogmUouEnGjwojD8BUZI=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODE0NzI0ODMwMjIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJSb2JvQ29kZSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2QzOWEzODE1NjMyMjYyZDQzNmQ0ZDlmZmI0NjdiZGZjMGQ0OGFiODQyN2M3MzQyMDUwZjc0MDZhY2QzNjZhIn19fQ=='
                ),array(
                    'sig': '',
                    'val': '',
                )
            ),
            'trail': '',
            'op': 'false',
            'speech': '',
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:iron_axe 1 20:2 16:10 name:&4H&fa&0r&4l&fe&0y_&4Q&fu&0i&4n&fn's_Hammer",
                "/give ". @plr ." minecraft:stick 1 16:2 name:&6Baseball_Bat",
                "/give ". @plr ." minecraft:stick 1 16:2 name:&7Crow_Bar",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." cakebomb"
            )
        )
