@plr = player()


@hero = associative_array(
            'name': '§4H§fa§0r§4l§fe§0y §4Q§fu§0i§4n§fn',
            'class': 'harleyquinn',
            'sig': 'oH6W0Bqm+1ULpnqhdCNz01wmTtVNG+SboLlKDLB/wSCmVmg9rWOqpUoEuM8PWSeF5YyafPb4QxJzfkw8y6d7x9M2B/taIquH89BgiyaSscJt8evfx+0xud7FEwSfnP93YkoPecoByjma5rJBh/doEpvOFOFz2jCsnY8pqBVENF3YqOl0uG9NS1Wt8/NGnboYf9XdZgG+apmT8slxwkMpEyCPIGkQu05liLrtszV7+O6l1/WlLiMnvp/I1vQlZ4qm4DMZaSyXsrqoX/aLubiBSylBccKtwgoRFlAzKWpTuN44udomDXN0L6x/2BJh2G6D/Klbd4/gn510PdBU40KuRAJkqEwiZTB5ZkKg1rjrXZ4GW/moNzU8OE8zJeB3Q+BBrMHQ/gGLaLWmx9w7FFLQlgo7KBwVOtqcJgpUeXMXIugTTweWqeOxdgWETm7KwWiE12o51ge8MQCFv4ZPqE/SWUi9kYeDAUVbfHboHQMNe+6vzZYyBFuj/mvOqn8SfZ+Mha9qXb0M6iou/NnXdf0r6K5RX0CEehgx2TWnRUQVComx65VHgOylfs0lXx/bpZ9izdR9szj67wqLt7KfTDFr1aPXiqmdy4dC3kddE0aTm1dNZnBfwKhuP4HxnGq+To7VwoeuoyDL8y3fpBK7bHYnIL2iApP+YAEL0eLTu4NuEQU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NTM5MzI4OTksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xOGMxOTI1ZTg3MzA5ZGJhMTIzNjczMTQ2YmY4NTU2Y2U1YjE1MTdmYTdjMTEzODA5OGE4NTNmMmYzOTUifX19',
            'altskins': array(
                array(
                    'sig': 'UBJKPLHq5/MYIuiU7fj3Fn/oDprTbY+juLCg8mqXEqeCSQZtpNL0P2MYJFD5G+Eg3jYYQ4678auQhdlE/NyjdQ5u2x8Zwpq2jHh6LDu4VDNeUKAJf3gSgkqX9lFisx+cus5dKOOOei7yl7Iuir8jvv7w4vU/qLsz4T4hEgqVfWVaTKuQYrTgzJrpeqqVZ0FMT4rev1nrr/cRHJ7WuPtzb9rV0Z6Kd4C2czDuiQVjsbmGuOc91OIFLBowm2bzNt2rxY3ywlqcQJEgXocrXtw3dQa/6GFJAN4k4zh/mcEA2KlkqgYcM/MB+lvo1aEjjrwUuYtiieGWofj22uJpxeRI5t55D2NOfIlatMHe6sdl1R6Hi7kqrIDmtPfbtOSykLoG7f2VEfpGtYsRkVNSWIpCsrUa0kWRsANUWaw5aC4ZDBo4G04xrulLgmxLDgd/kGEFn140EIsHpUam0a9NagIUQF8yAZi0xm83X2/XRW/BnEsSI5+vr+BNl5d4UZd4Cj8XJHuHUhaZhEtCcKp7h2+ARO02NrmEGiqqfYbx3XQEEXlBc8UcmRqNg+sGkcSzZ1bH5tuxMVRMbc00i59T3BJIcqRmAIl/S1e/TFl6lNxetT4UmXs6H+qnyCwmIoxzJiJxYBi8D9ME3p+imyF9+uZr4SERsVbRY/k4SPby+fcHRLs=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODY1MjEyMDg0NTAsInByb2ZpbGVJZCI6IjdmZTg4N2Q0MzMzODRmZjdiNWEyZTFiMzQ5OWIwOWU1IiwicHJvZmlsZU5hbWUiOiJGb3h5U2hhZG93cyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzg3ZTQ1ZGQyZDYxNjMzMDkxMjY2YmYxYmZlNTQxZWFjZTM4NDU3OGNiZmQ4ZWU4ODFjYzNlYTIxYjdkNzdiIn19fQ=='
                ),
                array(
                    'sig': 'O2p8BxZHAyYKekMwN70G9alpp9jRarM8wEwnINl5VMz+PypjWdyvOal1iRLVEYKzVwLdAYMXCHed3SMlpZGmEQN8C+zc6fb75P304DAj7Lb/Z82hCw5M42J10m/zyFz56jo9aLBxedgXb6FQ1dVhTBIYNrB9yCC3tnPPELVaV8YAefSN4jxYci+77ePAoPdfUlluZGSxZHpvO9SKrr8Bl49CvPLnuYcMvXbVtiBUB8BXIan95L8aVTSkuyDREhvAGyUuy5EYR1JkKsxktlwU1Rm8qS+xtnAiFQjT3T5BpYUYst1c7d4IL+Xg6Of1uN9IwQ8MXxW/EdAC5/KP8HwgCanZ6vX7R7F1BYaYsGujS9XCvjHDJQzWiKs2eFROGVKFUQBPjmGPoVry8N9vKHfwSl7sI+yL7vIq87G82fJ+Uk2BciVDHy4MOaKsTTRBTNgP8qZfuPSSsAKqO2Y3xd4iC578VzCjb3Xla7Zb77G/XS+PYyqyDKDy0Ae2mH/jKR3FlF9o9RlIpuTKpHagqYDPGgLHvKxTuu7eKzOcsumlgOTTYLUJRKixsV3a7KlLMgp6uznueFbgqb1tZLgO9Nqrj5FwgcuOpDUHB0zZRmTKGKnbo+OLw9ij9FxwO0FOys5hjO89V/7WQyvt+mBsFR4JB67OColp4WUVI+fCEM5V+tk=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODY1MjE1NjAzNjQsInByb2ZpbGVJZCI6IjdmZTg4N2Q0MzMzODRmZjdiNWEyZTFiMzQ5OWIwOWU1IiwicHJvZmlsZU5hbWUiOiJGb3h5U2hhZG93cyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzI4YzliMTcyMzYyMjg5YmIzNzFjODdhMDM4ZDQxZmU5YjZiOGVkNzc4MTJkNjVlMWY2YTAyOGJiNjIyYmUifX19'
                 ),
                 array(
                    'sig':'HZioJ18IFK/6iSi2+VceyqU5cQBEh11yAh8RgGf3PKaVLS90fb/wgWaB3INs1hrrzuPaTLnzXAtVQ4qoLU9MfRiIyYNLEIxgkRgTkUPF3fHkTQc0Ny4iozUqLdOMjrrWJKggcBPNyjTYdDqazjOMEFqrJsA1UP6bvuHYcz+qIl3OP6/30fe1Ny5QG9cqUusIhT+yJoDeiBYacFC+o5seXn9lZADRpAgEKwq0edqtvKtTaEsojxJ2dNuNS5B3gyAger5wyOi2KFu4lLh+kueeo3ST7czEcgrQdyYk34amqi+CmFvXzrvlUEA5w/G7XD01m2Uj3HdUF2bzqw409L7knmYMyjyvBwW6QsvgyjeWKsmRZxtSCa8g3USGRnJ36ZnW1q0mtBVoqW68H0QYFqF0hpvmaPlgY9Gep/0lJcmHTlBbn8g31W/OWfgwmcmTQNeESX7H1ladKN/wuXSbzLkZloLPY+kcRMyYDPloMp3/mHMYVyXrtTPVwYC7Q/kJNRvowyf1G+iBDGI2C9yl9I357/Ve+1P6pvxu+tSFRGWN/MCKLnMokwb1ePb1rSDMaw0PGqfIVCLyJ0MTFVX9P321qo16ZAI71tYOdW1LUc4lv97TUUPFuNAbz0lxkipPWl1n3B63yX9iuuyH9gQgwyh9c8ZkCegYrOzt9fkewwc47/Y=',
                    'val':'eyJ0aW1lc3RhbXAiOjE0OTAyMjE2MzMyNTEsInByb2ZpbGVJZCI6ImRiYjQ3ODg3YmZiZDQwZTZiZmVjM2QxMDUzZWEzYWZmIiwicHJvZmlsZU5hbWUiOiJEX1RlcnJhX0MiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xMmU0YWE2Y2NjZWFlMzY4NzYwODY3M2U1Yjg5ZDUxOTdhOTQ1ZWJiMDZlMjBkNWM0NTgxNjYxZWQzMTYzIn19fQ=='
                 )
              ),
            'trail': '',
            'op': 'false',
            'speech': "Oh that's cute...",
            'powers': array(
                "/buff",
                "/hyenas",
                "/run 0-1",
                "/jump 0-1"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:iron_axe 1 20:2 16:10 name:&4H&fa&0r&4l&fe&0y_&4Q&fu&0i&4n&fn's_Hammer",
                "/give ". @plr ." minecraft:stick 1 16:2 name:&6Baseball_Bat",
                "/give ". @plr ." minecraft:stick 1 16:2 name:&7Crow_Bar",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." cakebomb"
            )
        )
