@plr = player()


@hero = associative_array(
            'name': '§4H§fa§0r§4l§fe§0y §4Q§fu§0i§4n§fn',
            'class': 'harleyquinn',
            'sig': 'oH6W0Bqm+1ULpnqhdCNz01wmTtVNG+SboLlKDLB/wSCmVmg9rWOqpUoEuM8PWSeF5YyafPb4QxJzfkw8y6d7x9M2B/taIquH89BgiyaSscJt8evfx+0xud7FEwSfnP93YkoPecoByjma5rJBh/doEpvOFOFz2jCsnY8pqBVENF3YqOl0uG9NS1Wt8/NGnboYf9XdZgG+apmT8slxwkMpEyCPIGkQu05liLrtszV7+O6l1/WlLiMnvp/I1vQlZ4qm4DMZaSyXsrqoX/aLubiBSylBccKtwgoRFlAzKWpTuN44udomDXN0L6x/2BJh2G6D/Klbd4/gn510PdBU40KuRAJkqEwiZTB5ZkKg1rjrXZ4GW/moNzU8OE8zJeB3Q+BBrMHQ/gGLaLWmx9w7FFLQlgo7KBwVOtqcJgpUeXMXIugTTweWqeOxdgWETm7KwWiE12o51ge8MQCFv4ZPqE/SWUi9kYeDAUVbfHboHQMNe+6vzZYyBFuj/mvOqn8SfZ+Mha9qXb0M6iou/NnXdf0r6K5RX0CEehgx2TWnRUQVComx65VHgOylfs0lXx/bpZ9izdR9szj67wqLt7KfTDFr1aPXiqmdy4dC3kddE0aTm1dNZnBfwKhuP4HxnGq+To7VwoeuoyDL8y3fpBK7bHYnIL2iApP+YAEL0eLTu4NuEQU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NTM5MzI4OTksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xOGMxOTI1ZTg3MzA5ZGJhMTIzNjczMTQ2YmY4NTU2Y2U1YjE1MTdmYTdjMTEzODA5OGE4NTNmMmYzOTUifX19',
            'trail': '',
            'op': 'false',
            'speech': '',
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:stick 1 19:5 16:2 name:&4H&fa&0r&4l&fe&0y_&4Q&fu&0i&4n&fn's_Baseball_Bat",
                "/give ". @plr ." minecraft:iron_axe 1 20:2 16:10 name:&4H&fa&0r&4l&fe&0y_&4Q&fu&0i&4n&fn's_Hammer",
                "/shot give ". @plr ." pistol"
            )
        )
