@plr = player()  
   
   
   
   
  @hero = associative_array(  
              'name': '§4Har§6ry §4Pot§6ter',  
              'class': 'harrypotter',  
              'sig': 'aEn3ricY6IQOz1fQZj1K0pFUwehU+SKxcYbRBM33fiJp2hJbsbJ7vfjg+5j/KGkG7BhAkGKYCpdaYvLDt+09dSigyXE7SZSfLQ4H1copeT9SkvRA37sL7gPqeSI+bSWB/fFQq4yXbkjURgXld8iMp01KYCYUoyBFYwxlF4z6fiRjP1C/9b84dYmRBi2RXOBRaH9V+bRE/10FEHmqfSnqA+92c/sRqHtwMxP6jvgrJaPAG8Z77dhC5n7FIEQuQmJ3N1GU3bgk91cwkgdhogMgokgq4FeMOeLb957dOhTwQMOpNxaENv/zhypnk++lecRN6LgMfXPXhjT64kE+jtnunppyCthc0BVomg9KVJNnjgkPB/DQ7jMwTxD9qHvgLjXzs8xZcAo7io6/enZDPQLOHmA71+5pKVeyaYpWyDktyt7lggGIiajb5uwCIftbaWtDsDS4SnxXFgk7ohtigRhNqV4jKXi9ifpJ+nmHmvovayTH8P7A9nlmq26ktjFOGnWvrcGahGWOo4nuHHgFb2m00fqCFGC3njgw7CdPRscIv5VHAEAf9eSaxhNsG/GN//4qZ4epKeZSg21CZZOxNaE/sub5UBEMlHyQjHm9Ffq1PHGJQcCj5VwgEz8YfR30VJTyCpxKL/Vxw8fJ+DXLSjViEaGhVd3MSEzrDQOUiGZ0pgA=',  
              'val': 'eyJ0aW1lc3RhbXAiOjE0OTEzNDMyMTA2NTQsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmVjZWE5NzI4NzRkZThkYzEyOGIzMTY2NTg3YTgyOTNiNWNhZGQ3OGVjZjY2MzE3MDVjODI4ODI0OGFkMWJjIn19fQ==',  
              'trail': '',  
              'op': 'false',  
              'speech': "I am the boy who lived!",  
              'powers': array(  
                  "/buff", 
                  "/invis",
                  "/vis"
              ),  
              'buffs': array(  
                  "/mgive ". @plr ." wand",  
                  "/effect ". @plr ." 21 9999 4 true"                 
              )  
          )  
