@plr = player()



@hero = associative_array(

            'name': '§cHa§4wk§egi§6rl',
            'class': 'hawkgirl',
            'sig': 'Igj90wt2Kwyi1ezGduSI8szNIlciA6MmFaOuNG9pU814SvXtSe/soW+xK72mw4Tv8jIWUi5LNTkNmIKsVgwvP2kkVTkwXT1P01zaZ88C4RLG5J5UnIM1r4O8r9N4rRnsFUvLO42gCQe13H4ygZW2ffR7MUbEcCOTR39oo4XF8dQUVkHWf0OR5tOAOT72hRhaAb74cmu6CJfnsYDxtH9QDfE2GR1q5hfbXyyMje8ICIZdpUUfzHdRYDNLyeG7HfJ5kjm6iDLjkRv8EcrcX0T14nqbqvc/EpcnosqYRX+88A8Oq2FJoebyGwkPdB0m0l6kfZFayLtTb8/a+mZvfBCeBm2+MqOJyQUyzvZvoj2OHO7jztKjmj/btVGPI9UXGKaztaS/ACQQTPs9wjc1lzu08+gBhuQ4E+OQSFe/bvTwfX5Ga6qvZXwH3W5K1xfDoYwilYc+Gz3xc/94HTB5mvRcecQ3L8KoKTPEZvGucGBpv01rGn3hQ1sLSOwsfa+P+WxDnMTF+0pcDqRtPXya4t9LRIEgyN3lxBkemVH4y0Bf5DxUWqvs+L++vYUG29kjszlzdlNqWDKcMtLKTLpZsFQSaWyWcoNIQEVYulBzB2IMLtmRzCTweQnUkia9WIYpbdH2ShEIJ2Lg1IGABPMEyYJBPlq1RBR5QrE0Ofet6nbKZPE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTA2NjIzNTE2MTYsInByb2ZpbGVJZCI6ImQzOWRkYzUyNWZkYjQ4NGU4ZTBjZjUzOGU3OTgyYmVlIiwicHJvZmlsZU5hbWUiOiJFeWVtYWtpZCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGQ5NjUxYjhmNTEyOTQxOGFlNTg1NWFiM2UyN2ZiZGU5MDNjZjJmZjk3ZjhlZmQ0OGU1NDZlMDYxMmE1YWZjIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "We carry justice on our wings!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/fly",
                "/carryplayer <playername>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/give ". @plr ." minecraft:iron_shovel 1 16:5 name:&cHa&4wk&egi&6rl's_&8Mace",
                "/give ". @plr ." minecraft:fireworks 64 name:&cHa&4wk&egi&6rl's_&7Propelled_Flight",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:5 name:&cHa&4wk&egi&6rl's_&6Glide_Wings"                
            )
        )
