@plr = player()


@hero = associative_array(
            'name': '§8H§0a§8w§0k§8e§0y§8e',
            'class': 'hawkeye',
            'sig': 'BKlhnzJ0O+k+HS3BOWIySva6kOD8lbaMnSUZ5Q4iNKikZ7+pHSmGjDxjqlprxM5zcyy4JX/CzOXD+oRaTPMa2p654zgLgIwQVbXwmQRJNF3ZDu2iwKKQQXMyJ0y03P/iUkgdBMGp3HkLTB9ToGDS6YEZrij+CWf+FDhY9uaEr7uOeoQCgGTT1U31HOBAXlCn+wiO4db+3uMNqgTXfGUjGcBDjX0z2zFGO4bbzN1SinTcOlZOHFzTNDAGNAUcM0sKQzFLeI34Qr8rT4xK9u6HoH/aaopBxPOcxSZkky7FQcZpkjqKc+tTSNOUombbEwkofk5+PA3ILamZxYXBzHB8icQgN8hfj2WQSD4dEwOx7cxiWaodnLciYRAvZwfsDv1XsJpD+OQ55hM9xSw9n8SzA/PXPxYAQNx3qmqzLQzardvtjtMpgdDCeHhS+SlP3558VTRZx0VR9BNJmsrMpgegREhC/1Xg5RY14/DN//KpkJlTJnbyfcKDPVd4NFJfTPIns1WIDP08QnfTN/MEXbACiJ6g8/0zCCekFs5yaDyBffRxhrqK8VN87vJEim2jqNtzTLpIuvHqArNQ9qVSBgrR6i690PwnDur77MQM4ubp2OFX+2aQcDoqgPfA3+C5bb+6ifjhLJoahi440e0uFPvuDFYORawNbRKbvxwp6Zpfpos=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3MzE0NzE2NDQsInByb2ZpbGVJZCI6ImZiZTYxZDI1ZGViMDRhODFhNTdmNTFiNjc4NTQyZWJkIiwicHJvZmlsZU5hbWUiOiJIYXdrZXllIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yYTE3NGE0NmMzYWRhMzdhNGUwYmRkN2Y3NzQ1OTg4MTE0ODcyOWY5NTRhODRlNmFjYzc1YTk4YzU1NmNlNyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "How many bow & arrow shooter guys can there be?!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-3",
                "/haste 0-2",
                "/arrow",
                "/arrow regen",
                "/arrow regen long",
                "/arrow swiftness",
                "/arrow swiftness long",
                "/arrow fireresist",
                "/arrow healing",
                "/arrow nightvision",
                "/arrow strength",
                "/arrow strength long",
                "/arrow leaping",
                "/arrow leaping long",
                "/arrow invisibility",
                "/arrow poison",
                "/arrow poison long",
                "/arrow weakness",
                "/arrow slowness",
                "/arrow harming",
                "/arrow waterbreathing",
                "/arrow luck"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:bow 1 51:1 name:&8H&0a&8w&0k&8e&0y&8e's_&8Bow",
                "/effect ". @plr ." 5 9999 1 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true"                
            )
        )