@plr = player()



@hero = associative_array(

            'name': '§cHa§4wk§egi§6rl',
            'class': 'hawkgirl',
            'sig': 'BwvRzRqiy4gKzCR3drPSU8nFJScG09gggUvhhH1KdZBWbcYUyFVlYW3QabUT0xsAGcSBluYznoHDRPQKkRHMV9wnN0YOEh6BZY3YWS6fvRFECxL9IPQOWeRbfhMZzYIm2zWy7gJwxVsvmii0v375EA2/0xRQvLq6J0f2xNVyYENqOcNQEcUcu4tiUV7SdJVnRw2wI5ZFRCMLVPKxI3PnaGR1IjkmBqC1z0/tqsjRrjHqlBcvHaitekFeq0RDl7tnNKlj8jKBw2y7Obpkf4DnGNG0DZpKe0NqzhWPCta5X2HQ6ESjJj2UF2wwF8DBUZj6dgtgp6B+k+AiJs/eeqNRkoA3yezTRA5R2xL074ul5PQCxI4sLDlzZhqt7hpKHTquCrYl3daB4/6N6ywGy1jEpJxYP++wdOq7EfUouk89zwCd83djm6KUjf6aVs6bc8vF1XyWFuFQ4P/ZTEKPQ/SnraFByOaOWK8tQssxiBTrEWCRaBr4e+N3Y5aIusbKrvCSn554AADY0amPZvs+bfJ5LzULi1Ctclt6SrE4Wa2+EPMzY1VT+WY33aCAh1yDApX52Xh/Ao0a1963fyJPrFabv1lt2iVMphD+v9ovlnmKmjIcPn7LpgfN+HlXj+sgUMXb/JYd/GAazq4S7uCfn2WFyY83uw0Xx/E9/ZeJiKcfvLE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTA2NTI3ODI5NDksInByb2ZpbGVJZCI6ImQzOWRkYzUyNWZkYjQ4NGU4ZTBjZjUzOGU3OTgyYmVlIiwicHJvZmlsZU5hbWUiOiJFeWVtYWtpZCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzU3OTZlM2QxZDVhZWE0MTk5OGI4OWMxZDVhMmIzYTFkYzNlYzUzM2U4MjJiZTlmYzRiNjVlYjI1YzkyYTc5NCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "We carry justice on our wings!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&4H&ea&cwk&6gi&er&7l's_&6Glide_Wings"                
            )
        )
