if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§8H§7a§4y§cl§7e§8y',
            'class': 'hayley',
            'sig': 'vvQgUhYX/ljYUOWrD3tPQAevgwPIR/eioUFxg8FMT7beUsApeMZ04gQSJE75V4hZSdevHvBMK2arKhbtxsAB3hd3WTkFKKFcIB6iKqyNH33dePCjpOMsLJghBNUMuTJqUSpwPvTBmeIqFUGlInkpo8x4oJ0rfXKGR/Cemk+XJ9SuipkFeGyFxwkzNjLcZjijsKXdcVs5gTT1goep4XiGL8TbXW5RocUFdV4CID+gqkTXPo/jaSYjuY4xI9yKTJw6r0lQhCaJ0+P7UxtaULgpWcbC4jopxmboexWGtTT/6a6xSA/kmBf8PcrFfP2XSV1BLq/o/bYahAp/x9oTOGYKZcpPoc3xEOMDOwseT3C5JOfh7T06T2aK0/q0fDMotyJAJKzaT9kMPeNhYFoPEoNnx0U5kKwFdNaa+BmLQpuUoewd+cQtrybGgBed6u21KAkhRL0obNEQUcL9l5v8mjWJLFWZ2pZ2ny0y1FH3IpAH4r6c9eX4NR3dsnhhfdzv1PCotCDhdnqq+EmXxB26eDIxFnc3pPYD6dS8bL1avS3Wea4b+LIHTbeaKXZ8zlMuBv5T4rtU7xijulXVWo0TQzSMUz+lcyeD8yJ7gMZIsCuGDJJ/SUAPM4B2VNKHJUKMl1pvx9LjwCTRkCBA8mMGCf3Bc92iQpI/nnNAoeJG90xqQMc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDYyMjIyMDAxOTQsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFiNDk1YzMxMjdiZWNmZmUyMzE2ZTUwNWQ0NzYwZjI5M2ZjZDk5YjU3N2ZhMTgzZWU1YzI2YmNkMjk0MCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "How about a Hybrid Bite you Psychotic Bitch!",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-6",
                "/disguise wolf",
                "/normalform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 8 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/give ". @plr ." minecraft:ghast_tear 1 16:10 name:&4F&ca&4n&cg"                
            )
        )
