@plr = player()



@hero = associative_array(
            'name': '§eHe§6at§cbl§4ast',
            'class': 'heatblast',
            'sig': 'vqNYRtWtMtxy/5cNZtIRDAIAnUB0FP9No+qOPg1HO1JHL1WSwTd44DwMDr3FBUl572YZTD3ZBLSG+7ffIkTOPeW2COLnNVyjBAuodImROg+snLafZbDblYFOKX3re2uyvrnrGeWxjbGpLX+MHMJwar6vFiPcyaZ3W9ElAEKgiWhk2zD2Eq6f5mdCvaaSg+UiqGyuvD48D0HhQn1zSYRhhOx09ni7xPXJEENKthaO1VFO6sAePaOxc/tNkGVQqjOIh0Pufk715+WwmJtHXxIKXuYCUJV7hJJYFhceiDNou96PpecKBRNWOgsSoaxcuF2peRvuopiarP6JMyBrGNkpzjdXaEvzty6XAVx7tMg4cYBRbb1/Eo0EOthKPpkmv3a+Iv1SuZVMhAyTPOXWexooLMjEjI1WcIJWZCqXYjqfVl4+Lgcp2v+dHwMHHTh7S/O5K9+KSJKbOJLtKsO83x5NJ6zSgMdsO/LDBtbwQl6zJN5ah6yFDzwD2Mnqj6IOV4wCiAmStmQBMEz+5fbrrkOdz79Gm6AIX2+G/5741Zss7WAIPTosEJ9/vYWrTcjmBTPUOu2is9spsYHFcCyjmuoIZbqVrwAWNp+lhUgsUukXvKc3JhDsy1pHqvv8gMjyCms9Dil4+jq3BBxnhITEfrcchppiUI8gwIr5pDUwmhXAVEA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcxNjE1NjY5MTYsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdmZTdhNzdlNzNjMTFhNTI1MWE2YmYyMGMyMzViNDJhODNkN2M4ZmE3NzFhNGJjMzc1MDIyZjVmNDM4MjNkYSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Shooting flames I can definitely do!",
            'powers': array(
                "/buff",
                "Can throw fireballs by punching with an empty hand",
                "/fireballpunch <on/off>",
                "/flame <playername>",
                "/herotransform"
            ),
            'buffs': array(  
                "/shot give ". @plr ." flamethrower",
                "/effect ". @plr ." 21 9999 4 true"
            ),
            'alts': array(
                'ben10',
                'bigchill',
                'alienx',
                'lodestar',
                'goop'
            )
        )
