@plr = player()


@hero = associative_array(
            'name': '§2H§8e§0l§aa',
            'class': 'hela',
            'sig': 'ppYbOXNSL4bl8LI9mmda+G/M1HJ42jPgaV6M/IcdUEWxM2RsSfy/I3gyGFOG2lrAS6NHczSo0uua9oIKLY309IeP5wI3bW86pShSZZsqCdIV4oLi3JJo/w1zfHlaYGMJbH6qd6EvUPiMlsionOY8fZ4KqXnEDbPxxtaTd/DJ7K6Ke0CGGFLHn2NocsPt7fHP9CtXLG90FSZfoiqnRXuAAfGv+E8y4AaRKIKTZ8LwKf0s2I6ol98HmiYpVDuT/wBvHOKbOa1P03d9HezXabaCs/S5Jy3ZsKaOHDvpOD8KV81uPv3eJfQ3JYx63gli/pS1Rhqv0Ets1nJCGLEgn49d0XsLe2HEcEm+7TkyaoD39W7RdTELAIxGanB9vRtuDLQY7mvPIAojzfPS5WxWBHKlVNbjCVbEYrolAbJP+yrJe+fK/yMhHtcQI+1r++ZxRrYZdGVVgxmjpn6EJtNYZIq26/5nK24ZDAmm6cxjo+slXiRyaZhp+F4qJ9uBVDpVNvT6qLictvkWNCkYqRj9sPHRPBcWhT4UGLgjlTSHCTgVqut/6umP26qIZRT2jwbOaBsQyyOTD8sp9ibwDpILuEjl7wuk+UqKbkX9MfXo+mjyifJWE8TE6gHELca9sqwGQeYvaV3l5GeGnXJXVe90GwmcieqwiDiwjcYUOUtlSCOxaEM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTU5ODkwMjgyMzQsInByb2ZpbGVJZCI6ImU2ZGU4Y2YwYWY0NTQ0ZTQ4ODJmZDk4NDQ2ZjRiMzFiIiwicHJvZmlsZU5hbWUiOiJ4VGhxc2V5Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWY0OGI4ODRiZWZhNTZlZWU5ZDljZmQ0ZmU3OWIyYzY1ZWM1OGNmOTAyODY3YzkzZWE2Mzg1Zjc1NjU3MGRmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I'm not a queen or a monster. I'm the Goddess of Death!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-1",
                "/run 0-1",
                "/haste 0-5",
                "/fly",
                "/helatp <player>",
                "/speak",
                "/cast glasstouch",
                "/cast blind",
                "/cast forcefield",
                "/cast increaseage",
                "/cast helaheal",
                "/cast conjuresword",
                "/cast helabolt",
                "/cast turnghost"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." yellowenergybeam"            
            )
        )
