@plr = player()


@hero = associative_array(
            'name': '§4H§0e§cph§0a§4est§cus',
            'class': 'hephaestus',
            'sig': 'D/HjWP2y52oRI3F3kM+9ERT6ycc2Kc32ryJxQNLBXl7yeqhIqxydxQ+xQNx2jvC54KLC//UbT9Q0XwsaUPHipNu9xN9zBaJCUK56gCh6G6FpqG4iO/cRB4r7aFYTNrlhWm9zBncfrol5Ia1HBHUA3LV/keJmO0xCOBI+f3n1msHRUfn7JRx4Tg+eD8CRjHG9xYhLw/RXUkkKC+3yJEg5liGBGPR7hgHrlvVJ5dc4Ct0KYzAz8R2Y1jYU+wvhO5S9LUFE8w6lHxKVxKUuAIhzJaLYVXylpzwgoE/LzJUjfROYrIGaG770q5eN+pLrgRJYCXNBlGo+JdUp98E9i8gL1ZuNC31m5PAGYuUkga1OIe+5s/YBvEhEIdLyv4deE1sG80gGkJphQUmsLD+NhMQ445DmfpRskJIN8I4Wa6vThGDfpBdtRaFAFtgHeGSUptdmOJwMd6E7HyI2Qmn40jBLjFpupg9ZSqZln7tfL0YEPDaYxivhf2ubuUkBznLsCsiZ0mD0GFiVl1iSjPm4wNwaVRp+rsEmPn/PLBjTAgCAB+RxfIpP/UMsW4utstDxTYWBGhFOF+bGRhwqJAl2ze/uEIav85zyguXTtaeh+2TqQZIUdwucQRSvbmbAJg5mh6xdtLatwGA9KiGmCbX2jP489raKTwkwZSdOm9xwBVuagts=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjU5MTgwNjQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzM4NjIyOTE0MzQxYjQ2YWUxN2Y2ZWY0ZGIxYWJhMmZmNDc4ZjBmNDVkMzcyMTE4MTRhYTI4NzJkYzk5NjMzYSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I can repair anything!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-7",
                "/flame <playername>",
                "/flyspeed <number>",
                "/fly",
                "/enchant",
                "/repair",
                "/workbench",
                "/flintsteel"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:iron_axe 1 20:2 16:30 name:&4H&0e&cph&0a&4est&cus's_&6Hammer",
                "/give ". @plr ." minecraft:iron_sword 1 20:2 16:10 name:&4H&0e&cph&0a&4est&cus's_&6Sword"                
            )
        )
