@plr = player()


@hero = associative_array(
            'name': '§bH§3er§ba',
            'class': 'hera',
            'sig': 'lnH4aba7t7O33lmBAV35z3GOdLoKBJf1cyQpyZqFxG0fJ1+mhTa91d/fccDfFJqjCNpHdSsd2iBQywrnu4YA10MX/Pg4GN+2U1LOZuoxfFVMTd0yLaFOjRrLKmwNWp7tauXAcI7s0/K3eGWOkxWd4jvc/3W1N/f7NNigm1cY5OYC0YzjvXybaaAvFxIY2nGesmSI+u2+0WehdG/kButf43Hbm0mVOru6zKvayC4ATA8zXnyqMVi7NPAXu9q+PZqW801rRZVPURUgJgfdebojGi2clj05y2bqhgoGP8iB9/NI+MrZbNYNikJFwoylicUaIQoGZonoP3mEbBXP2IUYaLJ+4Mm4TdVTIK8MT0qHlPz0C2bPExm/B75QAaLM0QiIpQfx/lq9OLYx/mY4oabuffWTk0V3+Go++0I9GXSazUk7uUeop0GEd+lBFtohQcv9OKIbTt+9JSK+yIDRfIpOSVr3XdqGhkyHfts4SHB9z95jKoOIyjeX0do/8cMHdP5J5byn8er9u6kGAxvGbDMynrDYChFxhhskHhZ2XkirGAUOGZdFVMGoG6IglfvVYhYJ4E/wFxMAclV15x4fEog8NjusMzN64p/l/6ApbLOHb2gAe6+jAEFOOYKr0aH0J9x6zbo09e/Nd7pIUU0tytGorz/jU/RMxzI5Z8GMwJJxGcg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjYwMjA3MzQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83M2EwZjk2M2UzYmY5YTU1MTVlZGFiZjk4YjRmYjZkZmM5ZGEwNTg4ZTU2Yzk3MzkzMzVlZmE1M2VmYmMifX19',
            'trail': '',
            'op': 'false',
            'speech': "Marriage is a wonderful thing",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-3",
                "/flyspeed <number>",
                "/fly",
                "/pig",
                "/cow",
                "/chicken"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true"                
            )
        )
