@plr = player()


@hero = associative_array(
            'name': '§6Herc§9ules',
            'class': 'hercules',
            'sig': 'HeIxGeYHkAc3nuq7GRbMf6bdZIRZ/YztpI+lKKKDnIXyqYF+sGxAWUdVE9u3QujXbD5eYJ489Z/BYHJ33GrYZGdkkxdaXLOCgGYjh/PxVhD6RochhEfXVta8mkJlh4oSAS5Y5dELEMAxOhXZbVbOSP+6+asqM+pM6lve7Vod4ZzORL/iK10hvSjWQQWfu6uWaYXIKGGZt857xD/oNh7am4+z+5ffL+NZwfOvCHHx4Eccy0eHvqYnVjYt8+hPWixak9JB+G+b0R3+7KmYIJbTTjZUf2TCejlAz7RqLM1wJIFohv65QBVBvq3O9wXbWvujlDatoydjy7uF3gz1QDYuKWfFHiU/xi6unuFEJtvd2JzCiaeA+xFqWGRwQRAsDctJdP+Cd1AB8O7N1Fx01RP+vOp32RNmgmMXpIgCkVAB7xXBeHN58hcqghckSOWTH80hmVFDftoju9Kk1n31AxHLZ8zQ02YidhLyjaWF5Ksjusw3YwCN+K/sj+x2o8UO1nZ1PLPDTdzsMlXF4OAmhRmfg0dz5RcSo/Q+xrf2C3g45uEV0BbEqxdktSYLO1mw99YF4OrT9lfl14hefIszOaVT2coWbQNTau/PPbisccIpX61rkCC/IgzaTHexM7JEXC4DXkND9fAktAij7HkzBl/NuJeobe1McoBxtAcdiMR4hrQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTIxNzk4MDMsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzJmZTExNjlmZjQ3MDVmYjc1ZDQ4OTYxNTVlODg2YjNhOGFmMmRiZjcxZWYyZDVkMmI2NjA3MzQ3MzJkYiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I shall defeat you like my father before me!",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-2",
                "/haste 0-8"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 14 true"                
            )
        )