@plr = player()


@hero = associative_array(
            'name': '§eH§6e§er§6m§ee§6s',
            'class': 'hermes',
            'sig': 'Jf2OgsEDIaSZZOeFm/ztdqTyPNSGaxa2BMfGq1dFDSbSVb876w6BsP06TaEgPL6YMBnWcXE9H48ZoJSPVg9Oy1KkDlkN7RTFziyJJbeBZEhnmXC2Lhvw8AaK5iQDlcva31pHFWwWSZTZ+zqiYCgtnzKId0iWxgN50cHQ7i1Z6C05ahdtZum8kg62WKlAcWtGoDoIfVVjcXyOi6JhXMu9svem7jfBAhzvqnXG3z2BdBc3qge4e/2o7mdgppH6q+KefXjdkd8mqxoTH2QNXjMvyYZlmR0WzXLtj5faLZwhwTKBopCwwsBVIaedCnxfWZh4c5GbQvCNDQL9frgOBMDToQkGq/fIelqqscCi5cjqX7MM22VgtL3Ya4OGCszCsJuvA9kL7cja6G7rsfZrmE7t5ZyRhJWImCfw4BI+56Emei/UpZ5QbYk8Bvf2mqy85hFlQS2nwmyMuTRfTNFPrncB5VR2GrCKbYUrXQ19jOHGNT/YATLEvbH5B3mWjYnijXM4CW5MeyW1ejx6UDV6B3MJsm4xfp3tKi4zwF5alfCO3PFXZxNzfVED84TaxWHHN86Di0eqfOq18BGB2v3Yxp/FbrdeK54NdF6tSKfQNXJo0h/g9I4MKdYNgifLUhuFKdq5O7q5zUjBOLiPWJ4IAO4om+9gj/UkhICZ83GuZXg3GiE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjYwODU4ODgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzVmYWQ4NzhhZTlkMTY2NTRhNjNmMWUzYTIyNjE0ZGEwYjY2NzcyZDU5NmQ5NjEwNGJlY2NhMzNkODE0NzAifX19',
            'trail': '',
            'op': 'false',
            'speech': "Tonight im gonna have myselfff- wait im not Freddy Mercury!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-4",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true"                
            )
        )
