@plr = player()


@hero = associative_array(
            'name': '§6Hes§4tia',
            'class': 'hestia',
            'sig': 'sBH7M295z7q12ZfleEf3LT2D6u8zuEGLDTfaewlX+BEucn140gWpsEVUnAVKYqUaKTgzV/BmKhadEB2pAkX9njNJKK65AnUyyaA/H9AcfUX/Ae+YCEeodGUpJWaWZtarI5izyv9+Fz7iCY1JDUIM7aS420fYMnt/UmxjG6Mfs1bgwipxE8gmxvU/p8V9dQTarD6F8jX6P8QU5O9N671ygH87XARd8M2HHR09qZsKRRXJGr2sbWdiXvVGTBVY/DEyuuB/Kj5cG4/MxR+Tn9Qc1XyQpTm4tyg65KXyVl8fodzeBO4WL7D5bEQsy8cxbB6FhKQOA41EO75kqqYy/15w+7a0qb03+rzHuJLtJWHpoj5QHOcO5gSAw4hbgkTJOhw6UrasT/hR4eFXORxqOIM2+1Acc0p0zxCOlm0p+mwgrVn4Cp8Eae+c9TsSu1aajr0i73m+bBmdMlT4ugoZziC3m+shG3CruIbV/hNr5DS9MUkZZVGt8RP88OphX3XZyQw1o1fi+VTyGXcPQNtnFYt+GlEMEnOL0n/jWCVszF1LbheVlH9A3KF6pyeHtPbWx4CxfP9SDQSVGxzw+mnFNT/vkPYWrogwfdkHnhzGLiGGuFPTsQKHqckjHIMY7al8J05goy82/Abh8PiJsG1xBZmkT+9U5jdbVk01JHj7e8O1bZE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjYyNTE3MzIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kMGJiMDQ1YjFlZjE2ODI2OGE4YWU4ZjE4YWI5NzgxZDc3YmRlMjM1NmY3M2M5OTkzYjRhZGFmMjNhYTYyIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I an the Goddess of hearth, architecture, and the right ordering of domesticity, the family, and the state.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-3",
                "/flyspeed <number>",
                "/fly",
                "/pork",
                "/eggs",
                "/sugar",
                "/milk",
                "/wheat",
                "/cocoabeans"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true"                
            )
        )
