@plr = player()



@hero = associative_array(
            'name': '§6hi§4pp§fol§6ita',
            'class': 'hippolyta',
            'sig': 'Zm2pCkU/sg/qO2YpUR8FiSki3hLPkbkFqp2TLPbW1n88xHd23rYiZmSYANZ+BfufDfVw6J6m7Xj6lFLOFbjIISLYaz/c5eR08CgwBo6ys7yhqlN3AvKybUf2Z9pYbgVp6RvKdBAOrc9t7v0lfPp+VGlbBz2bVa2R6qWYYBOAd9yktbtdn1sQhkl5XCkd41MEwqO+TXZ180t1nSh1F/9xaKXNIHfSCV8RiPcc0OdvmzSBReHDAr0QcRh/SVki/Hgwb/jB3iOOuTyjcmsFglqGHDykEA61FwYi7cwf1NrlfzxUcDStlkHcScrve50f9o1dlv4M3AHzoRHui3QRu9OqJnC975na/M9I/opDNR7Agk7zZ7LjsRiyHk5uO15QZ/vaMtnPxizl0oqmtLmi+mZk4vHCBSfumiO63uV8WeMNhgQIu+BGazPW24GpJEE5KxxrZ+bfVF/V/AK33E+7yGMhTVl6r4qIu2GrBOLLYbd01o4FkDGePskV81V9LKe2AF1xy9ps+Ur/ndlNpkRaDkUK2mXZYmQTM4w6FZibA0XEOI4B4H/7Kqjuwwb6VJxlKeYlOkSTc5Z6c79ZTMbQjqFhb3xsRThObEV72/Kz4c4MjmWU4HKbKZRYUJwAHMJfOrn9rwkAhnUZKAMV/5ngc1zIRpJY2wZbKnbgWNNGJzRrZ/o=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTE1OTU0MTgyNDAsInByb2ZpbGVJZCI6ImM4Yjg4MTMxNTJkNDRhZjA5NTkzZGRjZGIzZDU2MDU4IiwicHJvZmlsZU5hbWUiOiJfV29uZGVyQmF0XyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjBkYTI2ODk1NGVhNjI2NDc1ZGIxZWU4MmVjZjg1ZDEyZWM2NTZlOWYxNGQxNmM5ZDhlYTE1ZDEzMmUxZSJ9fX0=',
            'trail': ','
            'op': 'false',
            'speech': "the world of men is a horrible place to be in.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-4",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-4",
                
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:iron_axe 1 20:2 16:30 name:&6hi&4pp&fol&6ita's_&4War_Axe",
                "/give ". @plr ." minecraft:iron_axe 1 0 20:2 16:30 name:&6hi&4pp&fol&6ita's_&4War_Axe",
                "/give ". @plr ." minecraft:shield 1 name:_&4Shield",
                "/give ". @plr ." minecraft:iron_helmet 1 0 0:10 1:10 3:10 4:10 7:10 name:&6hi&4pp&fol&6ita's_&4W&0a&4r_Helmet",
                "/give ". @plr ." minecraft:iron_chestplate 1 0 0:10 1:10 3:10 4:10 7:10 name:&6hi&4pp&fol&6ita's_&4W&0a&4r_Chestplate",
                "/give ". @plr ." minecraft:iron_leggings 1 0 0:10 1:10 3:10 4:10 7:10 name:&6hi&4pp&fol&6ita's&4_&4W&0a&4r_Leggings",
                "/give ". @plr ." minecraft:iron_boots 1 0 0:10 1:10 3:10 4:10 7:10 name:&6hi&4pp&fol&6ita's&_&4W&0a&4r_Boots"                
                "/give ". @plr ." minecraft:bow 1 50:1 51:1 name:&6ama&fzon&6ian_&fBow",         
         )
      )
            
        
