@plr = player()


@hero = associative_array(
            'name': '§6H§9o§6b§9Gob§6lin',
            'class': 'hobgoblin',
            'sig': 'H/RclsLaRxC+5LOfeQiQvla/XkWdobMviyx878965TPoiJWuL7GEm0TUg7/qe3DdAEcmFeWi7D7SrkRzv3YR2kJmnFLOOuczkP7Y7F6/Fp6eHYWD0tTh1CaFrmY9zDKyJCQbB6g/v81aT6INRaGdvon8t6eYiDWWD3lQQLubVgcDkga3CvzdGOViHibzOcOwHGjNM3doCdMC8P4l1uVCO/ZfTWvlRQ5dAsBFaZ1YZiC/Qj7ZJjlKqGNwq/z2hQu00S9fmmM07+m3tqQ3YKxWscdsjomIvBOrcVGi0yQiy6norySpy4QWG9xPSaI+iEyNap6YNwincrONiKGWVZN3xQdk2u/HUa06HjIrFJLAO9Cssgvn6H5maHW0+HtlWdMCbUGVRyyebDvs1efklzPZNQHQM3lN4mmk9qPo65MxI6eiGHkJj1lzF9w8ebIIYdQxWwZ4jcj3Bd/pQ2SLPkAyJxy2E3jjocWvSpSZ5//+BGvZ46Cq9jHl084EyWoB3m3+vsL7uZtRCcXyTlPpDMZUGgXXNg6NTFYtItLskn3qCYgtnmAK+fSF6qrvWevBKXnluoXnDI0Xdk75JrpOa+H2HVhTJn+fXHg3NlkMNPyoxO5y/ebeLD8LCVtuiQky4xaP0ufhGYIDa1Nrz7AGYVZ1KoBNM2g1lqdyblvG5Z9DyOA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTk3MDU5OTQxOTQsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzNkZmM4MTEzY2Y2YzE4YjY0NjQyY2Q5Yjk3Mzg2NGFjYTM4NDI3M2ZkMmUyOTU3MTcxNWJjOWY2NjVkMzFlIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I'd love to stay and play! But I have places to destroy HAHAHAHA!",
            'powers': array(
                "/buff",
                "/flyspeed <number>",
                "/fly (simulates his hoverboard, he can't really fly)"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." pumpkinbomb"                
            )
        )
