@plr = player()


@hero = associative_array(
            'name': '§eHoward §6the §fDuck',
            'class': 'howardtheduck',
            'sig': 'HmlUGgGGZQHLcZBLL2F6HeMzAXfjQyK0F8KQyhTOS6jpsvGWb3OuxY9wjkZDzEHXwBFRzLU7L0XJeVCB+UzvOxtm+01EsEMnm0Kdz6PRPSw9m/fDFwYKMphivWg0nQBi3Euu3kb4nanH25Ef9Pa55LrINPTYY9PQb+lsbAj8Ept8DixqIDudtfhv1BB+w9Wz3Js3VIj7rq56IkfX3lFDSdM0FkuXI5FyGBXN3s11iUvaA/socncmz+aoAOMrtzMDdqi1qXSPfD10kTQStRkFx43iQUAtq8PcGKFlwlDZj+L/I04OdftbOoUv1I37LYbe9dFr5RnEdSRnA6cC35v8gepHilaGHheYQlIjWEjfSM9wGAf6R+/MQjkB7ofjY+R7o02Y1bbDeL25bg5nxLLG9yf0TjQ5MSBwBANuRtM4OrpV5ou7Rdmp7m+HDXsA1PTy0wPmr3rochHmFucjARqfNUgk8yd6INaEWiAQUSa9r47M70fv4LpRtUNCAFPDnFhecF+WLP8rtpe0CwJ9DylVxE9ww2LWmmiGy1WSprGnJQc71ZQpsDY4y1sS1X2MSLTAeXKxyZVe2gRNDUlvnc98AffbzDlsFS+oDhDLebyLWyz7KgTVFpHKeKoXaLHIwuHioV3NbB6lvO1nCWMIcgAeKiz79SuQmybQq0UHeWdevyc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjgyODExMTA0ODUsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQwYmMzMjYyODliNzkzOTEyMzllZGVjMTQ2MTIxMWEwMWU5MTM2Njk1MTgwN2FiN2JiYzdjZTg3NjJlNGE3NmIifX19',
            'trail': '',
            'op': 'false',
            'speech': "I'm a duck! Quack!",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 1 true",
                "/shot give ". @plr ." howardtheduckbfg"                
            )
        )