@plr = player()


@hero = associative_array(
            'name': '§2§lH§a§lU§2§lLK',
            'class': 'hulk',
            'sig': 'XNLbC32ml/WEDICCgE1dT9vHmvsLSZxvi4aVYgBVHVdbeLkodpwXjKsA4xzoA7D7ro4poAFeHzlpV8BxSjYra4DcIOR8+pfBzlE1ux/XThfimXCEJOLEEf7YHud2nflYXJx7stdmDu1YK1uThvVZ3Z19gRHM5oIAnaeyCeZlY8yiJ0E/ZL6dfG7zd86Umtskv59JbOonHS03kohapZiO26NcbTRD0b7Synsa1JBbsIN+rS7kKdLOMey0hnFeBx4XnEffv0V2GRWntPlKn3xPKq3vy87LNNSihSrx/bdGRRbqx2SI0VJYQBqmEoLvzyZTKSQ+tOwTkuFuB19aLenNksP/aX13gP7LfH6hUVIbPqs4mMPJP+BuuMygrdmIHUQyoMCifniX1a77TpKiJiv33zQ5uMpyVU/jH/nMIJmkKQ+Ku6fNjJGSNS3ENCIUhD/mUyAU1j77PKUHhIxcsvyD1pyU1l255e+uKJgO3QqMZXgKJkdHC5iVk6i1qKdsSDp2JL4exXRFh67mYzl9TTlHKWJJHkUCF5s6b6TSYJcV7ltVRU0grtEAy9iYPaGr0PIYKiVVv9WFt937T+LW+gD/Zkvv5xlDrBiftb8uTW/7XnU1GChfvR7bRuklnrjfUbJ93WJL+md5AMFXC7mpZVYzPKT0NIp13tf4fxRgVZQ71xM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTAxMDE1ODYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2FmZDYzZDY2YzZmMzYxNDc3MzRkMTk0OGE1NzNkNWJhZjY3ZWM1ZDM4YjNkNWYzZDY2YWYyM2ExMTc4ZmM5OCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "HULK SMASH!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-1",
                "/haste 0-9",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&a&lH&2&lULK's_&aGlide_Wings"                
            )
        )
