@plr = player()


@hero = associative_array(
            'id': '152',
            'name': '',
            'class': 'hulkling',
            'sig': 'bkj7f2Olm+v46cNfGE4CWBeFwwLTO/LK5JUt4dS+Oq/LAv3CEIgdAszjhSb84D65Y2BMGUtgcS9gU5YcZB7XrIABJ9VYO8Svgku5CgYQBeF740IkSRAVCNVc8yxV7Buur1LPAE0UJfCbqgDKWK2heSeTR2nDUSH6slFxKUPZrcDdFXOq/UK1FYy6FSJ9sbdWYysvkNnGNAjUQ8wsIrLNlhw+GNlUkT8EQ3Vce7onZo9ovf+km6KZjgzsRUWm4aoGU6qlNC10Lm/boh69dnBZcGYLgrE7ktQEqkdCZvqjJueFH6Od948CxPASMVohBL9PQSFyi1mZICOJgIF+LYZ6uA2kknQedenjGHxlMKt079IF43o7QamT66HlQ0XHLHPDaOeKAvp8y94vOhOO7fjqwxdrvnhX5dxVBiv1BbtqWuYyncM1hPd9fVyh51ELM+0O+uf3TTkIYW62vdpfIn6mFgP/u/g1+fn8qKZdZuaLww/WlcOMUtyI9W4YV0K4/jVAcvt5FVKGlSNCUDlEA2CjLDGa7k6NN/QO52vPBbC0P352NQX9f5giyKtjBlQt/glB00BdbXx24xItYVVnmDjWsiXO1ATuiOng8DNeuzl0wtoUiaOK5t3cdMYeYndTPlK1IsTDp1bg4Owj7QopgYIZXZMQccQ7qlsqYYS2W5QJNfU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg2NDAxMDA2MjAsInByb2ZpbGVJZCI6IjRiZDYyYzJlNTZlMzRmZjQ4NDNmNGFmNTFlZGI4MzM5IiwicHJvZmlsZU5hbWUiOiJ0ZWFtR0JOaXNiZXRzIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hZGQ0YTRlNGJiNTBkYmUxOTE0OWU5YmEyNWMyM2Y5ZDliMmM0NmIzODE4MDMwYmVjZDY2N2I2MmJjNzRiZjAifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am Hulkling!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-1",
                "/haste 0-9"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true"
            )
        )
