@plr = player()



@hero = associative_array(
            'name': '§4H§cy§4b§cri§4d',
            'class': 'hybrid',
            'sig': 'Uog5m9vDdimMkp0rVQgjcLaRJw1BzxXc64xRb+1LjmYrOms/5u2bdQYlxZx5A23zNBO4YQOmsMnPBR6DkNtbr9118VVhxiU3JdtC8pjSZo6wFYh8f5aZm4RnnWI3v4Skc451BZmVicSQVVlWaNGSj8rJaW7Gs90pw+ruUmmZ6zKvxsXX1HjDhpQD75tMbMYzIwoOG2CxD/C0u/NShYFWg1OwUoA89H5HSBpZehj6esGw3Gbodc3bsBMw/T2w79FYV2moEHLzJEHWPQN2cwONJaNx+d/g0DrBfbT3H8mDn1DXumcByKqygQMm/hPTh2ph0K1B4Zx3sPTmzRSR2J6LNfY0M9mCUkWIRVO4ENAW9u1fOI+Rm9HkIxEcXplvFUIR5EPAD8Xw6ogBEfq7gvQzZ/W+oEy4olOlxw6xQWcEQQG/U/aE69fGhuyocj7Paswh/2aHQFxiMsOjpvhr21X4eH6JnLuVOt8WA/tpoKOe3+7W1IMZRvzAdqhLrhU2SD1xT+D6hy7BPr0ObzyOMUTk+xMtQ61IJ94HOYYmadB04s1ZOxF4+DLiIkQ02hZ5rSuiKdbUs1UdQV7P2RkWWjwLLCUEKwMIAgQljExOPi//cEdUBwDoaUBYVtzBiEQl9cKwNKfdhGKWR/cFAXQEvbl40TGbOvTwiJbpcGIWtVRoBD8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY4NTE5MDU4NzIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzk1N2VmYWJjYTE0MmExY2M4MTJmNDRjZTRjYzhjMTI5M2M5YTFiODY1Y2ZlOTdjZTNiZWJhMWE0YTkzZDgyIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "With these four symbiotes I'll be UNSTOPPABLE!",
            'powers': array(
                "/buff",
                "/vis",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-6",
                "/haste 0-5",
                "/websling",
                "/web"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:web 64",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&cHy&4br&cid's_&4Glide_Wings",
                "/shot give ". @plr ." webshot"
            )
        )
