if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§bH§9y§3d§br§3o§9m§3a§bn',
            'class': 'hydroman',
            'sig': 'ed93XXXK0XiyBIbuP+J7D/9GywG8ujxUHxyTulK20OFlIIBrwoljiYLgJ29pY5D7fl0wmrD0P2m6GaY4D7+1ZTbqHb855jkIPbTE8RxFl9GH7Ut/AT665+vy4n7ERgYeKDx8qxT9XhntugDzsvKLdu0wLte80KkaHorO1Ed3rcr3ASgVAJXZ/lGhjJEkVuI7wZDy6/3OaPXUFTWOYftr2+hSISyEHO7hLv127/1ov8HF7Rn2u6/SowiE//0Me56fKgYTtWn2P53u42hrZjdUHIMZbobpYQawSCpGxtZX4EwLGm2MMr3ig6gE0l/KmIgmXUySoiPbSvKoqJ/NrqlRYqqwwXdE/jejw78l3yR028Z4W2eZhA787KL/zkcR/oi4776ThzvtKFPtbrm9B0/nTHByEyn6cMD/Vh6ANS1qxLMIkFzdZDepzsTvDuBpHcUGs8wva9kkgVE8jIRcH9AQlk2f0hBcqs1nifuG+fgNzKKsnOZ0+WXdSqTELRdSV26suB0a5AaPzLROWvGBsIuq+968jv6+p+z5HRwiF1lGtZj4O0NwM6BjTxj/DKn00osEi+K6InN7fTu6P4OwkAJ+vsbxKDPwFj4CIdUn6v6g2sEYvz1cMVYvMmdSUgbkS8eSzmmicIxRcAzg1MgLK4EAIy5I0oJp8+Cu3TJBCm79/f4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDk0MDA1NzU2MjEsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODFhZDVhNDY0OGU0NTcyMmFhZTc1ODZkZTQ0ZTI3MDEyZTJlMzczY2QxZjI0ZjRiYTdhYzJlZmNhNGQ0NTE1In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Itsy bitsy spider went up the water spout down came the rain and washed the spider out!",
            'powers': array(
                "/buff",
                "/cast tsunami"
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/shot give ". @plr ." watershot"                     
            )
)
