@plr = player()


@hero = associative_array(
            'name': '§6Ichi§0go §fKuro§0saki',
            'class': 'ichigokurosaki',
            'sig': 'ckxM1Ts7gjMy1eqSPgpwncEi7u01NLEFZqJCLIRe6BNkYR0xYoHNX/EN7lOzEViBNboGhfcVp2TCHPQxxwZV+b39mBxuDXJN6UiDJAt+V16YSc8lipdmAjfqXN2V7jZde9YZKL1we7dFY1CHk7bbxpK5X6ZmbkzPp6COeJtMDE1gL2J0NM556crOwG+/MWpLf74IA7SYkR1kFBWkORm1ZABHsuUSMs7vw5LqEMEMj2KOyPSK8AUoAe+vpE/pE+i20k4FysaLV8Y9pLaLSTSqYacUkaetk2V8CZeHuKREeyN1hJUcAAxRgHPlRftDmEs8mlG5r2EpHoBRTd/vEtlst3nU78OdIsSsK1YvHXdFQAdZSyrtdEHAT3cDhnxT211cAvAO5cI31N+qbE7IK0AZaVT32eU0NEgSS0jIVcTg3JKTrsbqKW5Sfobl40YOsk3/u+Md4d/njjzw3QniJy6rbx6vABeHVbMZ8F0dlwjIONgIbpuQnk+gvdQ16PQe/lUIFLjyRRv8qgP0iPi7vFXVlsyBLgdbqiHISxD5lLHM1Wuo+ufLA5GVrxNh0neHvoP1Gx0w5qx2agQuLR7XtJ94UKaCpILYwaSHzJrlyhJot0vpr3a2HUzEO55h7kvjppkCSijBBJOFlMRCgmB4BUD0JCWNW973XfE9q/l+TIrd1io=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTU4NzQ1NTQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzIxNmU5NjNjNGY5OWEyNWI2ZTlkNGI2ZTM2MDE5YzUzOGY3YTM5OGExNDlmZjIxZmM2NGU5NzkyN2M5MDllIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I may only be a substitue soul reaper, but it's still enough to beat you!",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-5",
                "/hover on",
                "/hover off"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 8 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:iron_sword 1 16:100 17:5 18:5 19:2 20:2 name:&5Z&8an&5get&8su"                
            )
        )