@plr = player()


@hero = associative_array(
            'name': '§8I §8Hate §8Life',
            'class': 'ihatelife',
            'sig': 'eHIEDaIDwXAQYFBVwRexlSMfiP2nbUXi3zXJIgvGpe/6lHw87iiigbXd9aNpkGi8KWjoNpN6Hsl1AtBKGnTGG484LMBV8JoI1s3tB90O1Jajw+dapEKgiNu9XYE8syhwazc5fhKyRMWpI8TL0FBWtMQr3K6bD38ntCTKDYffnvN1/I67uf85/SPOIPlkZr7/hbxo9Wgj0Mi11/k7n1U3AMYh/5XAY3+/hAVf2GvYo/zA4hyFNlrbOOiKJ7K1y3dcdRR1M9ykv84LmuqUVgLchxs/B/l5oLs2W+26in6tUW9/K00E/R2VbTFsw3JZ2t64jYAMNas7t2XELEP/W0dWkJJmOZGWxJ5KjXPKf6q6xDR6wzr0GoQnKcNxuJaNoJjQ5/pp4tHi4lIyXSDltK2L+1Sc6xkY3bU2vVasjnLF7Rch0Gjf40+KSBc0vZIrVGzP0FFnSRs28KLdVl+WEGRnLp/3DNtU+MnXfzzAxF+VVYrUCGYvwpCNF9aqTV6qPUslaoilxHXOSmhn9NJ+jJH2syaBNjfpRQfgc9W3HSfIlCpYAPMbfFjku96DTIpvgisZ81C4Bjg2dUiWtWsWn83x9GKBOpT6rzHFEZsTvWQasimXRtPa09QiFt3U326KJO4bI4zCN246cf8Nprz2xifVwofPpMXEY07kwYNpfDkmI28=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTMyNDYyMjUyODUsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJhZGFtYmFzaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmQxNzEyOWQ4NDViMTRkMjEzNzNjYTdhOGM1MTNjODg1M2EyNjcxNTRmYzc4ZTg5YzRlZjNhNDVhZGIwNTgifX19',
            'trail': '',
            'op': 'false',
            'speech': "I hate life",
            'powers': array(
                "/intangible",
                "/tangible"
            ),
            'buffs': array(
                "/effect ". @plr ." 14 9999 1 true",
        )
