@plr = player()



@hero = associative_array(
            'name':'§aI§dm§2p§5o§as§ds§2i§5b§al§de §5Man ',
            'class': 'impossibleman',
            'sig': 'SpiSXtoxtFydvx2pWRYROhVQHJCMAaSjS7RmqleiyMAZ4TlsB0cblGGAdf1RFMscEmnfdjIo6tCdGy6I98pLnG5pe4A7cYPi20rgd4ONqXyyvEHRwrYwoZE8wYhu3qBd1pKUR1FhQ62qzcNpTX0lmos15L37T7Jph3CLtMuqBGzuUvGHIjEnfiuW4Bd01r91uQ2g0XSrj8/oIf2rrKRd9mJAzT2e3gWdu+R9IY4mVJlmKvagjakDOXlx/DFRKiI0vZDhhO4en4DUA3Xw/CnxbtOaJmpTMzZvGnb8Cpw6cYNrcdpuQatvrG2ELFfnvxLsgOoF1Rl9tBHHgIybEHZRaB79xYsD/ZVHTa1Z2kxyAUZEowh3h3OfC5scCbA19IS9btHuSVLbl7m6+VjiDEluz8TfTd0JqNkA3EYvznUggHO8RHzwDEEcJS8KMhmcvqMh9w/l6d/fQaXmVmn7pbwP+boWBAKYOLRuD0nDVQA7tdWaqKRfdOTXOWWPfe5luUq6OPQ3PDuOaBIYLfa0kYv5lmSrYTH9BMPPkz0cEr68GG+y0YhUGimMYCWqCa/P2McxjqiFxDJmZW14O0v0VO9vTkt7uaaNJcsOWfTlQUJVmfF6xN4hcT722KNGl+NHSrJKyKlyBzywaUTFuGxVokCiwXtadcj0vf8jWfqug7MS40Y=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODcyMDA0MTEwMTgsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJVbHRyYU93bERDIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iYTM2ZWZiZTU3YWI5OGRmNWJjNjk4MDc2Mzk2N2E4ZGQ3MzUzMmY2YmRkYWZmZjEzOGVhYmViZjg1NGIifX19',
            'trail': '',
            'op': 'true',
            'speech': "They call me impossible for a reason.",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-9",
                "/fly",      
                "/disguise",
                "/gmc",
                "/gms",
                "/undisguise",
                "/disguiseviewself",
                "/back",
                "/tppos <x> <y> <z>",
                "/tp"
           ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 13 9999 1 true"
            )
        )
