@plr = player()


@hero = associative_array(
            'name': '§fImp§4ulse§6§8(§fB§4A§8)',
            'class': 'impulsebartallen',
            'sig': 'ChNZkAMRBC2AzWlYvTdlpB148zS3CUz0Tf2603L4reehjBFkbPhYoZ4xyHwAHK4tRvFY1u6KsZ09GGO9DgKslB/J9mSbxLm0g27o9Xc6Q7LDdzdohMTit58TVH7XtWiaXFIPKfS1uojTk0JoB1B+tkMgj2i/hHc7h+/PeO9fQzH2KkGTCe5WKfrDSUrmE10PcLx3ImqxKiOVxDfQSZnrWI8cqx/99edtGVCnNjGFfHJ6ut8guXgefnrZIZbDyj/q1GX4YjuduiY4aVFAOKqankNqL8QebKYRpRUsjrSLrL1ZNphyDJtc0sj75fxhy2tPpAiEFkJr/2KJiDb8yiB+/KrBWmS0hQBxN4nwddLhPbXjfIXd2bYA9K/qQAJjkIlC672cA6M/ZxvNU6GXzGo+QpAOq6xUZBqkR9Gs8HDNGFlc3GmMFblD/Ie9LYJmc6DA6HXsrSXG7G0wroQWKscSceYSZgh2Vjl6CRCQbQUwxLtA/iWFU7FdHFw4LOKY967Ym2C+TR81gvNEASVtE1K5Sez/MVOcqqeIm44HV1Tr1ba/xIqmEnPgnbQjXsG7Mg/pwNNpbutF5x+PDsjpwsndzgqMdLuavK3NXKaAjvRB3snmHha3boAXr5hSy7lnndzDEduY9SezXiGoPu/O9lZQZ8jUXmAca/uABHWnw0BVxBU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODAzNzg3MTMxNDEsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQzYjdkYzQxYzgyYTI5ZWY5NmY2Yzk1ODY5NTcxZDMxNDcwNmU1NmVkNGQ2MTMxODM5OGJmMDg5ZDJjNTNlIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Dude! That is so crash!",
            'powers': array(
                "/buff",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/carryplayer <playername>",
                "/dismountplayer",
                "/run 0-9",
                 "/run 0-1 (In speedforce)",
                "/haste 0-4",
                "/tppos <x y z world>"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
