@plr = player()


@hero = associative_array(
            'name': '§fImp§4ulse',
            'class': 'impulse',
            'sig': 'opQxiA2MbEEpNRf3Jj3Iqht4NlLCsw+XOgVO+wJ2WH/SOK0gZK7E5ZvytjqlwY8EsZ/6q7faCaTwtz1alUbciRum7s0pY5IjnUoMFVtYDFH8J6n55Z1/fTJhkWj+f/WPIpwh4XrkO/xoLSgytlgqULbFCxd58jvH5Uz3/SyMVNknaoxZKiUsQ0Wsl3roPrNFWqEtHwIvRWHwazlVqbKFrZUwr73NI1R/EE7oOucUz9FSWkeEwqq+KPsed/81+UayybvA1kc/ABu+Hrt31ITyGhWOu8rJ/I+5GgYpFXiHmEv2ITJmSW3/TWEyXKnhuxMNMYo2lXoI8XaC7s/6HxTVlaB8qGqjkL91X3G9Lfd7cW5+3hLXKhBy4ya1tpZ4ILbTqlFIxcDFbQBRIed4fMHg6nbT00ZbQ4Y3Bf3FMd/VE6e+FQKaiZyBzTsp64FGQeQZ67ffetCyqfFNF5iHYEJx2qAQmCiE5TBQF50kV2v0Cd/4cYmlKArWoupgC7wssCECIqbkCiiyq9cB1d6a1xLcPiqzjh8QHRfQjGBog6uImoxL0ETtKookatPqxp4+2pycxmwB+CPrjQjSNLjnRACdj/e/TtM/AO8D7Q0Z0QZaPV1lpI4RT43Os6GGN78aUgSEHb/YH2zExeeOa7aNO1EON2yw3cwuZ4GSzK5SrGtZ9qU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODAwMjg3NTc3ODAsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJWaWNlVE9QIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS85ZTE3NjNiZjY0ODY1YzNmZGYxOTU0ODRjZWNkM2MzNWUzZDQ5OTE5YzFlMjdhZGY3NzY4ODMyZGM5YjVjMjEwIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Dude! That is so crash!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/speedforceheal <playername>",
                "/whirlwind",
                "/carryplayer <playername>",
                "/dismountplayer",
                "/run 0-9",
                 "/run 0-1 (In speed force)",
                "/haste 0-4",
                "/thru (phases through walls)"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
