@plr = player()


@hero = associative_array(
            'name': '§fI§0n§f-§0B§fe§0t§fw§0e§fe§0n§fe§0r',
            'class': 'in-betweener',
            'sig': 'aUONvgp+OBZHMDS3dVBSJJTn61bSxt5KctbLsmJIJVQiATbDnt731NlHWlSiWxUyu2nBPjMMlAdpWWpBoVdsAerU/P4w0byFUoXTSdJ+/0SbBe4bYBB5j1SmsawGovRgAbn9HadzOvTgASh0iVatWEgZh3RgFkLcVCpFupaStiGjq5+K1kkBkw2GeYkru9JGe56ECpTWDG3DplePIR9At5+UK4NgN0ediULDgxXpHtCHuNf4Prpo1K4Yr5lkW+nSVIF9+YLCQu2DDIoc9F35mj3NCg7Qo0ArkhnleYcXO+aSdyKA4w/yNnV2q03sczaRKwnNNHnSl5EP1tx0Q6tWbBqkPoq5OplB435UVieyoeugcTjpvQ7a1f0e+NK0YBs3zZZEokz36x/gaPjIOKDtOzg4bRUrBHb3ldDJFeVcFBETJqkP5OjnHT4Qa33Z0khL5+pFCAiZhlzKsj+y1UO+I+OUBL9Vj5v3BOVyoX1Ud0QAMUeGBF5VORzHEchjyXuiqka3vqXb3NtHXOuC7Ppe5EvLrK6ctC9eTYy2fz6zjAjuce7gvxG8Vpop+777seW/bC319KFbLeW9aPxzJtX+XFegEvUVsQfY/kKzt5eBdJNcrBmtCRoQUjJywk5pa6kDVcanFTYy1Hx/1TA24ODkd/YW+cvqZXZxZ+8cQvasZ/4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTY1NDk2MTM0MDUsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJ4TXF0aHkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdmMTkzNThiODQ4YzkwZjIxNGExNjVhYmEyZmU4Y2VkYmIwYWI0MTE5N2I1ZDgxYzhiNjhlMGQxNTQ0ZmMifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am he who walks between all concepts such as life and death, reality and illusion, good and evil, logic and emotion, god and man!",
            'powers': array(
                "/buff",
                "/fly",
                "/grow",
                "/normalform",
                "/cast cosmicbolt"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true", 
                "/effect ". @plr ." 11 9999 4 true"
            )
)
