@plr = player()


@hero = associative_array(
            'name': '§5I§dnd§5ig§do§7_§5On§de',
            'class': 'indigoone',
            'sig': 'mPrMiLLb+w6oDMwf9L7oaSfwWOpfisyEj0pcGPHI3NBzgouaPMTgQmgkIuOv28+oG0tS7J6mGbGUWcC0LXkJ2I8ogZEbODuFz7+wAuN5GTO2U/fUWw+k9WPMI+xNP7n1uDmEQ4WAB7VilenKGzLvV5IkvkkEFoZrTLZ72ec8JIaPVPMyT3Ib1EdYtxWroZqcCZj8jJONKhVbDy58H1aP//55io4w0kYzlK6tmDheEsaYpxEsbYcw2Rf83zNWDiqsnfMYjRk/lPvnnirIv/tHGa95PYkf0pRxgrtpi2eWPb8Q7iUw+5cmEQdN1LHguGlqDqQLyR1MLECWkdXmrxGkCDij+qLJ6yRj2sJ4cly2osw1oKj1mthABA8SMXxSYKjjhKzy4Ha/Bsba8glwVwXZhTSaZ1pOiXIYUrGxUvTTZD5hsRmBG5YM0U/8HByq5pjJPhhlv51GZ0El8yo4/MzzDc/NUw5XmGHdFRN6xCO+oFCqY7g4rIlx0sb6tXevktxeHxxV4Ir+kr30DBoZ4QMih8mH6OzBD398JQ3eOn0zWQcvxtp8UzC33+mWQ3DQ7T+GLCaKAFxStcpbyEvh2xYX7YMskfO3UE72m8wSjfa3zXUS26j4DjTwwXKz6xZ2rbZnecGE3r4wYbq/wSP7MPIHU6EwI7bWwUlpZ3HQkjPXxZI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIwMjM5NDQyODYsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80MzcwODFiMjRhZTM0NDNmNzIyY2ZmN2VlYzgyOWI3ZjUxZjgyZTlkYzQ4MGRiNzg2NmJiMzk2YmI0Y2NmZmE1In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Nok.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5,
                "/run 0-4,
                "/haste 0-5,
                "/fly speed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." purplebeam,
                "/give ". @plr ." 95:1 64",
                "/give ". @plr ." minecraft:dye:4 20:2 16:155 name:&5I&dnd&5ig&do&7_&5Tr&dibe&7_&5Rin&dg"                
            )
        )
