@plr = player()


@hero = associative_array(
            'name': '§5I§dnd§5ig§do§7 §5T§dr§5i§dbe-§5I§d1',
            'class': 'indigotribeindigo1',
            'sig': 'jG2e/CT48r8q/LnPNRUSXxZzoc+Guqh/hhJn/eanBdRoKzrEMYw1+fKtI/AZUcTAU022FPm0Y8CFaiqB+S/9S9rKec6UL6pf5b00THCzI/npy+xfzUHNDAbS3aRu+Qqhvx3fywoAC/D8Eny2zx9EWdpLKtasA+9rtbli8PP72YX/wugLeuL+Jv9JwwewsLxCyBShwdfQQhy2TFJzOMHwNdiOFFFyBorGorfr7VfjoNutowg7hrnbi8m0t9/G43KC7qLwX3WSRBNyLIAq9ejg1SubvwpS/u+1fDm36JL3A600vHpfVc/0ewGiBzwwbeLmdoUArCjKTKPFBcdQJaxDjuYrolp/Qy/eg+mxnrLF7G1VtyzLcj0j3GO0IV6zb5cU8Vw1DByOkxOEySSfxCeF0806WEqNUm8EOZYHYGcGXlz/RBaWYbQTk1iBv8qNPToPwaCuZix7ckW/ArMGmvHxrS9OnpFMxsCCIObTTbc3LV51F9YdqQkUbNb0nm51tHxKjrt7mLBBrIzNWM9iMZqnvOeD6emiNDL8B2tH0c4BjWTFod8Ss2mThlC+iXmaS/64zxJvi7mxKqf6Yx+ZtARkO+xJvZrLVH/GrSopHZ/zwrxW2kMwsWh2ghEVMAQuObaOGCCLaR6SO5QWza9JtUOlzraEDWqPzMxCsfSb9cF8Kd4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk4MDMxMjI5MTAsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJHb2RfRG9lc250X0V4aXN0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjk0MzUxMTNlNzIxZGUxMWIxMjk2MTJmMTVmYzhlZWIzMjU3ZDgxMWI4NTY2YjdjYjNmMzUxNDQ5ZjcyZSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Nok.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-4",
                "/haste 0-5",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." indigoenergybeam",
                "/give ". @plr ." 95:10 64",
                "/give ". @plr ." minecraft:dye:4 20:2 16:155 name:&5I&dnd&5ig&do&7_&5Tr&dibe&7_&5Rin&dg"                
            )    
        )
