@plr = player()


@hero = associative_array(
            'name': '§0In§ae§2r§at§0ia§8(TTII§8)',
            'class': 'inertiathaddeusthawneii',
            'sig': 'MvvvyvIKbuCKON8n/84CQPDSgaa513QaBrbJkHyXOv9NFri4fXDxxt0VYfS02aHqr9axTIg9ue/yUeuDiwLBv9LIUCHQeEJs80rL5yXaiGRpQHrKJW6DEophjxzdub7cWQ+T0VQdKdCcAPX5QihOa2avdAF8hmsd/D2yOlVCUS0hJ5mJ1gqERQaXWSjYnn6owVJnPTlTdLlAVhy0ku0IataTC9+AI2asTJKrL3FcCanRzdaOrrurDxFJ15NTz4iYJ9ShHoL63rFOjXmaccv/OwRj/yvgs+t7v1e+M0pRJQDZVgE5PCtQz0PIijTak52y9t4n3Lwib/8IqI+VqimcASRJcVbJ7dq4D/OUt3Gc1MRFnPzHa8e4aGupdis9JKs4rOAr0xWsfFD6vnCxIx20+JWZoS7dWEZE4kiferpojaOUBdC1BS7BXmdwDVlwCDWfMEOGrsX5IboygpBQq/+fjjIhfW///T6PHaY5yZ5kVtkiGJ2QJEM6pCrOsNtMywf/o+u9ObRNuc+531fD6F6ygqLc5TNjKSmLQArp5QEV7PdjEiWJ9fZ5d5avwlrBLjiObtRGx88BfxntW3kqhK3e3PnyVno4FGlF6g4dCnqpYPWK6wmdt+0RE3pqXsDZDkYPgNCcT1P3fBk2gCAvnwFNqZH1OiOIzKC0dcWYQUwdf5Q=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTA0NTkwMzE5MzYsInByb2ZpbGVJZCI6IjY5YTk4MDJmM2NjZjRhOTFiMmI3MmZjOGI5Y2Y4NmJhIiwicHJvZmlsZU5hbWUiOiJqb3NoYWZ0ZWwiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzcwN2NiODkyMjM4NDdlMTdkZGRiNjBhOTVkMjA1MWJjOTI0OWEyMmI4NzYyODg4ZWYxY2VmMzg3ZmFlZWQ1YyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Name's Tad Thawne, but you can call me Inertia",
            'powers': array(
                "/buff",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/carryplayer <playername>",
                "/dismountplayer",
                "/run 0-9",
                 "/run 0-1 (In speedforce)",
                "/haste 0-4",
                "/tppos <x y z world>"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"
            )
        )

