@plr = player()


@hero = associative_array(
            'name': '§0In§ae§2r§at§0ia§8(TTII§8)',
            'class': 'inertiathaddeusthawneii',
            'sig': 'k/v3bo6bjz302Vxegn1HvIXvbGro3F+rZTpuGRcm5z3nhnlcOMy+6fbdHnsrXwV0mJmELWNPRDm+7LcQdcyVJ1z1GZjr8/bQ7g6vnCm85jLZs9lYeTVCRyG3ZIa1IPnCUSNV2Fax7eMryN9wLr8TH9Nkj+YmA/RqJyIrjfLSFXQ8Fba8woGXBCJMu+e6U38bqvlWgF8GwkaCh/twgs7quTBCAUMXAW0HbUQ+8t5VrRWkj4Ar3Sp0u9FI5SgFoOI5iMvW6G5lO0Q3Brmw/WVx9PYDQnLngS1Pr1r0aZLDh4AuRg2Dvei0NQsgNKcFT23Kj+RJIf7IhkFxJDpWCosQwvcU/kxo8ZwfhcgQlc5rRu2hV6YW0KFLvJHBlFojJzlcMPkxQ+LW9r6grhuTXLd39kal4n4BNbhD47zho5WzsgCDXbvSYfv0mt2W1qgy9qIhhcuDXKKcPBfVEJP+032G+eUNg886ypa+IfP5K9mnPAHIqt+tXezCTxTeoDBQAmmag5/bxsjBT0r/yPZuCGk+5/IMq+GxhtVvnLirdd7VTNVmYteTu8GrzHTh+9uLQnS8ZSNyh+9UlA3Id0jlHvf+PqeQl4ktKEqLsPqyy2tHcOu4KWNBHVucZJ4f3rYOegRJ4SloAA2LBPORY2axYMlI8wmmYagxmdfHliyvqwnknaY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTA0MDU4NzY5NzYsInByb2ZpbGVJZCI6IjY5YTk4MDJmM2NjZjRhOTFiMmI3MmZjOGI5Y2Y4NmJhIiwicHJvZmlsZU5hbWUiOiJqb3NoYWZ0ZWwiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzc3YWU1MmQxMTk2MjUyZDg5OTdhY2Y2M2U1NDQ1NTFlZTVmYzg5MmRhN2M4ZDZjNmI2ZGI1MTg1YzE2OTYifX19',
            'trail': '',
            'op': 'false',
            'speech': "Name's Tad Thawne, but you can call me Inertia",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/whirlwind",
                "/carryplayer <playername>",
                "/dismountplayer",
                "/run 0-9",
                 "/run 0-1 (In speedforce)",
                "/haste 0-4",
                "/thru (phases through walls)",
                "/tppos <x y z world>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
