@plr = player()


@hero = associative_array(
            'name': '§0In§ae§2r§at§0ia§8(TTII§8)',
            'class': 'inertiathaddeusthawneii',
            'sig': 'c8LPjLI6gEtgZmQ9uiew8/l9bhTcREry0KjpJyeTfB1tZ/Q5jp8DvzjkUVFfU4Yf4C4VkBw+ytx5RA4qm5CTq4ya0l1KVa2ZFjYRlhnsF4dAvBiTKhWoBxrfHSR3mACpC792tzRwho9s8vH0tSxg3V6fJGpqZkXOUtDe58IEKJu+IR7pizQpwqqAYxYDP5mM0x829EUW1Pgg29N1DYolYuBSs4UNaToBhZTZ/Nohm+pdmzigMQHoIhejJCpDLqVqkiPAzQ2UcjZ1PFNdnWkn668HT3yY3giNwLyQbrSG4hE+wyf4uVZpogCQz7wRbvRZsAlFkoyX+BdfLY0SUZlpcfcy4cvRWRcW6rTo+X5bsAXsk8kUgqziDa2MiI8cUTbBuQ+oWP12y92RxuEsQVYZ7O5jT5t4R9p6er9zR11Kbm1Y5Av4V5ZotoK9/GCuFrTxlnXp91zPUGUxzw9SIIECLtf5np73HUg9Z/xF9JZg2qRZBrKYxb6SwEAuQHh/Pz8WFWZFVZZkYkKwKgsaCFgnQ0r7Wd3pBZPL5Jtv4E5MaSc8vbw2EYgefiMGj1UgJ+gheJ1DhetxRHEnLz4I3l3SMudhVeIwA3p0X+z6ePZNgH7P8qhRemU10Q9X1Yp72a4EC1Mwj0DM6tS5UQOAo7EQ4warcS3Js26xU1l9GjKfU5U=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTA0NDk5NjQ3MzUsInByb2ZpbGVJZCI6IjY5YTk4MDJmM2NjZjRhOTFiMmI3MmZjOGI5Y2Y4NmJhIiwicHJvZmlsZU5hbWUiOiJqb3NoYWZ0ZWwiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzc3YWU1MmQxMTk2MjUyZDg5OTdhY2Y2M2U1NDQ1NTFlZTVmYzg5MmRhN2M4ZDZjNmI2ZGI1MTg1YzE2OTYifX19',
            'trail': '',
            'op': 'false',
            'speech': "Name's Tad Thawne, but you can call me Inertia",
            'powers': array(
                "/buff",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/carryplayer <playername>",
                "/dismountplayer",
                "/run 0-9",
                 "/run 0-1 (In speedforce)",
                "/haste 0-4",
                "/tppos <x y z world>"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"
            )
        )

