@plr = player()


@hero = associative_array(
            'name': '§5I§4n§af§ei§9n§6i§5t§4y §5T§9h§ea§8n§9o§6s',
            'class': 'infinitythanos',
            'sig': 'AMfLYJSrvizkdhtOuNNjQcamMwoy198YSUlqlDRxySKCRNZvPJ0o3tMH//PH/I5Jxm9oLX0bgJxzZMKtsRDb5sL6PDz9pcMKgSle1xeQl4Vlfz840/jkdH1xTx3Xq5KTltrDnBPEXYeQXuXnbJZlei4BZbgc7hafIwx98/frue7TPbkmnoY9LW59Zc3GDmxkNZYObRriiGs9PXsQaicBVWW6efxc1xyl22JK/wCcScY107VtFNLa6OzMNPwr+00uaG1NAb07OrArrchTbfYUIv2fEaOGnFL9Hku43eYofX32LN7CO8Zlxs3HVsmuSoJNpIGTtvUEH8ez78+u9Lo4GiFjpYq4HyNBv/rLvI9EzhRfDwfNbiTv919aIYgEh86nWoujg0OqQNX5TUv1+XYxi5rNVUqquHdzt63s+AEojLHI5h+OrN0aYjPQaA83AEJi1imZROAs9zHeHl3162m/LyFldWJKBry6H4VX92juSG8TXV8S1FP1dCyk/o9l5I5TIWpFRubI74SFnMSHArk0HrqvAYSCjx6hMXPvP7uTdoe1tpolxCEZ/Jpn27yp4aTKtsfJcWYsxbrJl+7HzWNtyK6IWKTOLQFS+E0nVwvHUqeS6C6JF+yiN7p3ilE9MoszUy3S11qaLqlxDaqQHfZR3XeYIZgQ0hP0ZvprQGI097o=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzk5Mzc3NDg4MzIsInByb2ZpbGVJZCI6IjgzNTRlZDBkMDljYjQ2ODJiZjYyNWRmM2YwZTJiNDEyIiwicHJvZmlsZU5hbWUiOiJMZWdlbmRfT2ZfSGVsaXgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2I1Y2M1ZTA4ZWQwNmFhZGMwMTY0ZTYxZWI1NDdkN2NiYmRmNzI1ZGM4NmU0YmRkNmE2ZjZhNWVjMDg3NjEifX19',
            'trail': '',
            'op': 'true',
            'speech': "I wield the power of the Infinity Gauntlet!.",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/gmc",
                "/gms",
                "/fly",
                "/speak <playername>",
	              "/mindcontrol <playername>",
	              "/confuse <playername>",
                "/intangible",
                "/tangible",
                "/invis",
                "/vis",
                "/disguise",
                "/disguiseviewself",
                "/tp",
                "/yell",
                "/heal",
                "/repair",
                "/skull",
                "/time",
                "/spawner",
                "/kill",
                "/lightning",
                "/thunder",
                "/weather",
                "/back",
                "/top"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 255 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/effect ". @plr ." 23 9999 1 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
