@plr = player()


@hero = associative_array(
            'name': '§5I§4n§af§ei§9n§6i§5t§4y §7Si§fl§7ver §7Su§fr§7fer',
            'class': 'infinitysilversurfer',
            'sig': 'NQLMxTZwPIAGDioeLQ6IRWg5iOyLCPf7pXBDGgp823MlljnzoOBt2YcZ+z2SpY88cKHuRep+XGbtO181PVsWi574m32gqNLTYSvEEbqLu49V+3bImGs2Np44P/DrnFumcKNWU2eT1bdgHb4lzlQtiqlrcFa6qTV99j0LxG5fGm0u5+zDXkwkFQonz97/43VsyzplVahZicclR6zKEY6mWo00fU38biatRi0Q+BR86qE0j7/4qxtdfYlfJZa1w7JYiLRDWoSkYeSA2k8jI6IFT2bCD7EITQ2Pr8LDXJAC5/r/HQVpc0IiT740+fGJkb8y/Cdym5ryEBb8SNlxJOyRRbHmtQsF9pNcqI86GNaWTIoUYuCyEchucYVvT+WL0wn/lfrUMoVD362rf10MKCMRtvUlunS9qrYM7ii+Ffv94WSkvQNzZNLKVh9QWSjyB58neCbrhoBaJF/lpVkHhXOQXJqpamFRsKfpcUbP30ITgUY4MnqXGL2i7IsXiPeLVvobYbZNERAcdStX2XcUmWTvyXhU1g775dkaErivBN9RSIPy6AAHDbWFseoKz2PVGA/9wMB0x8paaZiK0QgvxTWKTToXeDAJiYHXlVez3CWUIJgbI3d7AdjkbuCB9nZ5hdB0SSF2QSIGTzoy5bSaE/cliseQIW7k3t67FFFJXs3DYMU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTA3NjkwNTI2NTYsInByb2ZpbGVJZCI6ImVmZTkxNmZmY2FlNTQwYjE4ODc4M2U1NWQ3NzZjMmRjIiwicHJvZmlsZU5hbWUiOiJTaGFtQnVsbEdhbWluZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWJkNjVmYmIyMTNhYjk5ZTZmZjlmZDU0MWNhOGQ4NDgyYmY4ZGVkMzY4MzY1MDc4ZmYzYWJkZmUyNzI3NiJ9fX0=',
            'trail': '',
            'op': 'true',
            'speech': "Surf's up, dude!",
            'powers': array(
                "/buff"
           ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true"
            )
        )
