@plr = player()




@hero = associative_array(
            'name': '§9Inv§bi§9s§1ible §9W§bo§9m§0a§9n',
            'class': 'invisiblewoman',
            'sig': 'VNd25ZQRar34rVbc2HWjqUkkjx6qLLXl6L5QGN5zekeezkxkeUmlTKy+q5xvF/49gK4SonEaTDHkOrLELLnkO4889xdm0rIvf11JdR1syjvq9XNsRceVFpYQYRLSxR+V8IeZkI+4md9to8HtUtf73WgC24d9LnaBElJPWtqXsL/HvrFTYLYIkVpxzYR+ZA6sKT9H+3YfMFRl4mxUg7z5QOhNYbtfHCt1+xfbHApBCxVPjp2IxcSkYXh0jLpnDIqT525vXsrjXF55zULATFFS6+0yWkcEkQDZfmO5wfX3UXnu5Keup/br68nSyrkRDZMV6hiB6lSokrQa67ZgfurSvlUeHfNcYJ2irgrR3O7pnG7rrSxTQiZDJbg3jklcFYdNdxVmzfBeZnX+kwlYfl3R0JtZitT4oDNhT8uR2cqP3/MCn11+oTr4NU7HsjZpW+9URfsDIQdujVwXl73xHYai3iazges2cj8SsC2CXovtLHwYqCYppgpsemtsFGT2GN1pLv38juNCyXqdbGSuxrpQVYnTNneNoIuyzOwJJyKtLKFncUwkHwm/ypBdvp6mcO7q4BaIQEyLFW9EJooNQxx8pJK37+9kEZ6UXGOZe2fbdpdP9R3CsM90A5iK5X6JEqbnLx4RfwzM9/alpQOW0WjMrUZHcpb6sjw5HbKx+uwFVIk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzUyNTA1MTI2MTAsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mOGRmZDM5NDE4ZGI3MjgwZmU5OTk3YWI5OTdhMThmN2Q4ZmE0Y2M1NGE1ZjIxMzE3YWJhODY4YjhhMmRlIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Invisibility is one thing, being naked and invisible is another.",
            'powers': array(
                "/buff",
                "/fly (she can't really fly, but she has control over psionic forcefields that she can use to fly)",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2",
                "/invis",
                "/vis"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 4 true"                
            )
        )
