@plr = player()



@hero = associative_array(
            'name': '§6I§4r§bo§4n M§6an §4MK §6X§4L§6V§4I',
            'class': 'ironmanmkxlvi',
            'sig': 'yUlZMABue0OGG/2njmbF+MnJZokd9jFItwUVOgbhhPEzavsyanVc60X9ZIqrfTQx44GrtsPqgaf5Etv4YC52Sw6LQ3ZoL00WgSexOxtXXTJ67Cq90/pvzxhcdiPQcKzwiTWP8zjYr3PhnMfhv4tuKrXtsOXsYkyq1/wceGoiy+/yjhSNwK7xxHwrSg5BRWOQrFbi72UIHEmjF2wzegmpImEg2HTaSY47tttll4u1x/jd/hCN3716lG2Do2breTusBL0HhAqabCXd/afiwbxdIaamQPgYp+zfm+tV+3fc+EmNJAqHLF2sHcmY+s2Mr2+mFWrtFVpUSMgU7O+/dxvEjj5m4d+9Sqlutqsi7Ip+x/Vfy52U/Z6zl6mLDsYggtAiYGc/nxZVShLGzigqOW9BVoVFQh5acO+0ZcvlkVqm8oYzMmQ88+7kPf4mkEsf6dCbdy2qZt4YPw1phKrmC1WmOeXEp/bNZE5eBOXaa+7bG0vR3q6L7vg1qadOLIbdNvLNL8s3X1jNHcO8doWdyaVlznfPLkDZK/CuzkE/RgLeLHcScsWG76PyZr54/SVatfGOfFAmNoeJskE0lEEV76KZsMIDL3YUsFelEP/9wvfeoeE9HtWOfxIBjjVNHcsQrkynMkpgw7xxWPgJ6IDWDicKfjjkzk0j0fbwPphJV1p0A9k=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg3MzY4NTQyOTIsInByb2ZpbGVJZCI6IjRiZDYyYzJlNTZlMzRmZjQ4NDNmNGFmNTFlZGI4MzM5IiwicHJvZmlsZU5hbWUiOiJ0ZWFtR0JOaXNiZXRzIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83NDU4ZTJmNmU5ZmM1NTNkYTM0MGEwODgzMDJmZjZmZjYxYmE5Nzk1NzE2Y2JhZDU0NmMxNDhiZmVkMWY0MiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "It's Hulk Bustin' Time!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-6"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." ironmansmachinegun",
                "/shot give ". @plr ." ironmanshomingmissile",
                "/shot give ". @plr ." quantumlaser"
            )
        )
