@plr = player()



@hero = associative_array(
            'name': '§6I§4r§bo§4n M§6an §4MK §6X§4L§6III',
            'class': 'ironmanmkxliii',
            'sig': 'RJ6VYTqYh1oJMwnOwPkFUsqC9IWVd4bXl4HbVuXG+D97I3XVZE9ldVgZp2iUlEuNoO2Oq3hkR9Ue7p87OWUw8C4w859/EzkLmNdb1rns+kU2UU92NaeqhpGyeLE7TDsNDhIxZRMwqWNinw6LWz+2XT7/WbyYcPUzKgORUkCtf6jxf96A208IrU8yLTXsWizDcHQ24qnLlHkvzwIqOgNzTtozBUSU2kyY9xE7YW3Kzxh5qK/dnZok7Gf+blD7NY050pua6UkCyTjD0OeZh1JSOW1HN40QSQjAIe0G/hqAbNjUGyICNOQUbYUDQn7pOziQ8Z8RFTOswaJsXA2cqlYOYSDLQAnup2xMqwuizvfkTpk5fdqqAyjImVpQHjPE+kWqkSPCgI0yKoO/gk/oJ3AeS3OllVIB0pJzjE9FAPklxUcx18lrHbc1fwIpOHOQ+9L7RSxW+ft0EiGSfe56vXQ5ae1AjWCwXlXcbgOMBKxTmsVcU7wQWIfknlI2vcRVrJGyQA1TnnhF4PqIMkL2UdEW7Mr1nZhOvRRpU2lrvEyY0vyfpa6ZMmSvcJK9SwoNePwrTk6nMTdamKvuL4hGVzTeqlKEoe3SMiCHjZLYqD/POPPkTudeVQg9l1RQXy+Bhsd+0SNpP+qYflecRyo2b0PwD6xDp5IL8nGhsel8/yno5Ew=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjY0ODY0NDk5MTIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2VmNzVlMWUzNzkyNTYyMTNlY2JkY2I5OGQ1ZDcyYmE4NDU4OTRjZmUxYzhlYzY4N2NlOWJiNzUzZDQ0MjcifX19',
            'trail': '',
            'op': 'false',
            'speech': "It's time to suit up again!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-2",
                "/run 0-3",
                "/haste 0-5",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/shot give ". @plr ." ironmansmachinegun",
                "/shot give ". @plr ." ironmanscannon",
                "/effect ". @plr ." 5 9999 6 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",                
                "/shot give ". @plr ." ironmansmachinegun",
                "/shot give ". @plr ." ironmanshomingmissile",
                "/shot give ". @plr ." quantumlaser"
            )
        )
