@plr = player()



@hero = associative_array(
            'name': '§6I§4r§bo§4n M§6an §4MK §6X§4V',
            'class': 'ironmanmkxv',
            'sig': 'P8MwvKVZ85EcMNdAS6FvBW7AFqY/bf0pQuF0UMISuNYcDgu0o4Lhc66yi/W3T8XlOWwnjKvTKOR+h4zkRV+sTaHUH4zo4WdVkp4apB0BmoKqmxnEIy+x13OR27tDhiCz4SqozkL3q9Wr1UAzL6CLAIPPsbwlhJ6F8dKrEdmohY7JK6vv4WCmLddQpaR4c4zp7ZvPh5d0nD8OYUyxyTwTMS61B9edXJ5L6E4MLStsRS4VwvfTHyLd7HPQBTakwj58fdBSNibyxkRKy8t87wzNhBhkAHylMPQy5il+WIv1i+jd1WnjmvEra3cN4fBFS5MINQSemk5icN3UBvX6VRalatOwrZVwevSA8Rm3wKS90MzeGOIsHNM5BjyzMfT5LZMTq3K64wPtvjzwgdzGWzSRgwX8QyJpvvpU+jIcjrpeGwErSdM7SfnX+8ebnw/OKOljsqOrvGjXiU95DckcHx7BRTbkiNndhEcVbbR4wpjZn5Feg37MPfICGxh/of1uYlGfFOKV1+t0w4ur0xQjNQ0UtW+ar/jbggio7A5a/4Mb4AGtTOfecxDPcXZzZPoH81prmQg56ahjqWzAefNzsC8oIb4PBn5Jxb30rcWrBncjgRoW+60s9J0C2OIohmbDPrOpD/ojSqFhWIQT+/YqHl6Vby3T6oGVr2NPxeeAdBkHL9w=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg3MjA0MTg5NTcsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJXaXR0bGVUaW1teSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmIyMmZjYTUyM2NhNTA1Zjk3MjM0ODcyNTdkYWM5MzVmN2M4NGY1ODMzMjlmZjRlMmE5MDQwZTU3MGVmNDJiIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "It's time to suit up again, this time in STEALTH!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-6",
                "/haste 0-6",
                "/fly",
                "/vis",
                "/invis"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 6 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",                
                "/shot give ". @plr ." ironmansmachinegun",
                "/shot give ". @plr ." ironmanshomingmissile",
                "/shot give ". @plr ." quantumlaser"
            )
        )
