@plr = player()



@hero = associative_array(
            'name': '§eI§fro§en §fFi§es§ft',
            'class': 'ironfist',
            'sig': 'QqjryVhdCcqYgGIwv47zkb7DWpTWi1R/Dg3fTzA+YCkBrtc/ej4F/tY72THmdXbksBx2KEgPRAiv2k58zm/5toRJCltQnYnhoqsD7Xaz1hSKT8pygCU2yaJDUwnXFkVDi3tzKHHQQz3AOib/MnJKoB3WiWbEEHK4Df8HXWHP4NRROLOBOxltS8MgdbZgub/ldhBhT0tpUPoH/pZCKQPEosf+q3OYFFuZy++ry7ZdYb2l0+hXHGFcsIwUkcLnx0sWh6bBzT+58rvP77FVMfqQdxdTIKHRuwFCZIamN3ebGvjVi7WCOdXPj/anIa7hQujBMGsNY/ZqeU0grBXiD5944V5vJMcv6x+K434Kk63qXgm31m1Sqidcg2QkM2yhkF9DDOHl7m1WKLqXOPR13QqI3IuG7MkOHea/FmdioaZWEJ8mPR9MeIW0NOo+AVw8NxJcvxt/ezMdaxBH18ISnBlYg2An7K7omM9QDAa1Uy7T3SOu+f0B3NdezAH471VfpW/kYWZw/fZsfEBqz+AqIgLg6HSyIbcHLhYTSrxNqDeBA9QuIXHte7bvGpRICd/RppAUl6kFsoXWqdqKEk3vOUh4XM7aQ28Qjc1QTIwhYHvXRTnin+jHCTTm40dB65IDLAiZYLN4KRGSR5kjwCrv9WKl6ehjhGR89LVRQnXwHwkXC+0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzczNTA1NTg4NzgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2RmYTI5OTY4MWEwNjZmZGU1YTUxOGU3YTIyNTkxY2YwOTdlZGI1ODk5NmQwY2M4YzgwMzVkYWY3OTU4NCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "You cannot shake hands with a clenched fist.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-5",
                "/heal",
                "/heal <playername>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 15 true"                
            )
        )
