@plr = player() 
 
 
 
 
 
 
 @hero = associative_array( 
             'name': '§4I§er§4o§en §4Sp§bi§eder', 
             'class': 'ironspider', 
             'sig': 'K/rEiwgyOIBAMbryBnPRAedmOm8fsLZM+Js9eZT66hqk2l7bX2y40qOcDGb5VWKD2haii8ZtksS83qmRjHKm4y5GFwpYmvPq2nTpOY6FRC0tPV8fj6nghwGjgLSfHeQ0I25120GI9A+TNi8rX71w4SfaSMiotA97DHKNjVV1C0m6ML+9sYf5Ot7DH3uWfNMZen1M5DvTYDosP2julWwkpaO2leHO7PAPiLiSiakHR47yRjlj956EfoAP9zbpzD22zgAktU1Rb/Tii/JpbuIG6+e8xlT4cajgOTxipHoAUjMKiNC8z92ld95iRjaLKDeAGkRchEKNfdcA6VobOmtcZOf25tPlt/ZsroCPo+8iPK7EvrFKaYFBjaTIU39wx4cMLpqKNGvyXbPDtqp0BA95qlAioII5y99SKNISelyXa22rGC6EfAmsizVSclWHjoigV6bisepI1PgR1uP1sDK8EW3qDOM7IJoUhEsGLQLUZAUfuSxzPQssJfmuzflkcV2Ac6nXaAkK9D9MzibT4C0Q2/6/QU2N5bjBwwY67tO8n4O/XZUrzvIKuSpVCaveAVil8pz9kVHtpV4KTgy0Nwd1yTWh8oNvKG3WUKksv4sxS+awYMeNXSkLpOhC0bYEQiubLrRWKiiFkqX7aybbNIp4rxyBQ0ngkzq7HDvI8bk8jIw=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE0OTQxNzc5NjkyMTcsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjMzN2MwZGExZGIyYmJkYWI5ODk5NDk1NTU0MDIzNjNiODhkMzY5Y2VmOTJmN2ZlYjdhMzBhMzE5Nzg3NjFiIn19fQ==',  
             'altskins': array(
                array(
                    'sig': 'hwLF7YoSqKkXPSvJuPLZ8O70JJJX3/GZDEpMh7wj9x78l4T3oeb8/Faj5MJuK3QI5yMmvw9PhV2GxZPORoqeH3nl8ebczBm1O8OrcWyUSA4kfP9+qt/r6dN6NubJVhbBSvOC7DJwMKgdDe4GwFf4XEDF4XrP4iCcVg+SydntzV3PMe8yWUx+Ok8aSGrCiAkLy+BCvSN7RTeXv3nShtqZft/WFYDxe9/fKBPUMjWfi7rHsmNQvVJhQ1+Hg3W3BFC4r/73PHKJzpfE2ez1wDHuUxe5JMDMHWmWcBHeEOWbtDQEQvXYxoPh62CohVdi0UIKb4mqDZd/SolqNX9yGpt8nSrRcEuKyv/l8YYBiONc8femgGJrU/1TCV3vp7sH07P3VzNS0P8mfizApY764TELcswsaQLptJaJaOcqI52BEJRDR9MJDsjpKXs1kHwFdlgtQczq/VdKsVewzZ+Ajeiq/ky6LUwncuJlv1UGxRWLgPdwnCO59WyC0uLbuq2/caRheSfRhyZddNqTpbwmbHuzGFpCEBxPxc6YDbv8ZpIlRqmCn7vIJ0FBQ2HQ9B9o3Kjh+MTIZTSRu3Q8BeraPpef7APB28x49TysGXUMMAr0Ti8yoWWRTrxCL0/9sh7E9L590R/Fip52ZVW8v/1E/1UO3k53zTHOUyYR0Ys3OkcyLJ0=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE1MTM5MTYzMjYwODQsInByb2ZpbGVJZCI6ImE4ZTE1OWVhZGVlYjRmNzNhMjQ2NTkxYjU4OWFkY2Y0IiwicHJvZmlsZU5hbWUiOiJNckZsYW1lWVQiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2MyYTVkOWMwYjM1MjdmNTFjMWU3NzU2YWRkMjM4ZjZjODk2OTk5MjhiZmM0YjNhMTI0MmNjODg5MjY3MjQifX19'
                )
            ),
             'trail': '', 
             'op': 'false', 
             'speech': "With great power comes great... ooo look at this cool suit!", 
             'powers': array( 
                 "/carryplayer", 
                 "/dismountplayer",
                 "/websling",
                 "/web"
             ), 
             'buffs': array( 
                 "/shot give ". @plr ." webshot",
                 "/shot give ". @plr ." quantumlaser",
                 "/shot give ". @plr ." ironmanshomingmissile"
             ) 
         ) 
