@plr = player()



@hero = associative_array(
            'name': '§8I§ct§7a§8c§4h§8i §8U§cc§7h§4i§8h§4a',
            'class': 'itachiuchiha',
            'sig': 'E5Ab5NN+lnT/aJpSDLCnUp+0QoiwZPdboO9IhJNP4sw3MmHHB+5R+fMefoNWn8WoHt18vuUOQ1vcCuhYF48pOwnv/kqvyh8OR6Deos20jf4J10FCHcrj34TO/Iv9FJWFs86H+mqBnhMQH2Tt8+pSTeRKJ4qTcel4DlbuOvQDs346eF8oxkUi/lpxDL4e3PfkAEVK4eQ4iKq4baXSHIbHx4CW3wqd0pORF/tnjeLKL4aLnmR39rKqMXzPWlXrjHdvgsT2Ll9/ho76lK86Qow/vnnqh86rSdnZam+zkoRaATwILB5lUIwpnuapd1vnHh1E60cyWepX0JnymIZoQeaW9WJKOLrqql5c2nPTt5CVxSu1ERYyAJs4y0iYt9ZTfH1297x/dbV/e1ViHzbCnJDxlzarCeViXBUh3qn519lT7Z3Lo6fLyLE2qOE36DM7ARG5jOpE8D2aWkQI9VB4dIBaEjV15xzTEmy0O2VWz5mx8XO6nK7ZuyHkLOKb1+S0wBW6sEBcFGog4kj+to9BmYgTJGJTlBY70brt7vyd1P/V2eIDIBuIs2YWiUvYziqy9/Fcv2GbKwW414ZN7c+UGUYaZkKu8KH9LFXZEUFoaZGBT4IR+U8loYTExgMD41GbaRx2jWs6PL5lF20t8OXnV56sd3lElWNAj1nLSMk7ARDPDUA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTY2Mjg0MjIxOTgsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJUb255Qm9uZ29zIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kNTY3Y2Q2Zjk1ODM2ZDhiNGI3MDk0YTYyMDAxYmNjZDFkODJmYTU0NzM0ZjRiNjZlZmEyZGFmN2M2NTNhYWMifX19',
            'trail': '',
            'op': 'false',
            'speech': "It's all right if you never forgive me, but no matter what you become, I will always love you.",
            'powers': array(
                "/buff",
                "/d bat",
                "/undisguise"
            ),
            'buffs': array(
                "/shot give ". @plr ." throwingstar"                
            )
        )
