@plr = player()


@hero = associative_array(
            'name': '§3Iz§7u§3k§7u §3M§4i§3d§7o§3r§ci§3ya',
            'class': 'izukumidoriya',
            'sig': 'W9Qmthw8+gzeeY+24w3jd7vo91fExJhu9BnTuSi1B+O1A6Jgy6cZzkz0DYCcmXznI1E7t3tD4Sb8CFYIGV/CR7mJOW97P7ktXXvIlPzbfY+P0A84dIHsm0XKDHiYfoDbExQxiQ3pWnpcSr7LbaO0lybKdkx74Gp47rkuZUN1Qcy5fFP3JpoHVm+rbYVBiLSC4qU0s4dnLtW9RWckX+0QAkpFe9ZewbMcfhNjyWYtEs0NlSZCBeVEtYCaMxunz0QUyJyQWNDMM/VHX18/cnDIrphKZQn/gWTwGm5UF00XX9cYaxIKC9VJwONCHYqO7GiSE40CJt2en7bBzz/YWaTbR5U194FO86rWQoU/7YJedagtStvNYVAB8P4EveDdMqXwsleTbcmidIxLysxkq51mzaqmFIH0jG0sFZEbNQv3isEouiKUXt/T54r9NC8gIep56AMvu9kO/rI7JEV8s/0LayxoHkAuZMJcNdpZ6MCR6dm4xymtpjh7vNyaqt5igpEbGrR4AaZtuTLNqx3ziVbqqX1Hjf53+ZljKDZCY+Nsc+Pwo8yJBRwxovheRgN5q3OguxlllzsNm5vaxq15icVv01XsZBoQhgEzVtLZqO4cpXq/s7zFRh68qxjOWTFLaaezv8Tcv7+mwLwa/q4D4T1z5jwwBkMGX/saZalhz4vlpbA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTY0Njc2NTA2MjgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJKaXJlbl9UaGVfR3JleSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzBlOTgzZGIxZGJiZmMxMTM4NGY3MTNmZmIxNzE4ZjYyN2VjMzljNmYyMWJiMTZlOWVjZDNkYjE5ZTdiOWUifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am a Izuku!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"
            )
        )
