@plr = player() 
 
 
 
 
 @hero = associative_array( 
             'name': '§6Jack §8Joyce', 
             'class': 'jackjoyce', 
             'sig': 'ozFif9nnrDyMk3a//AGJk0pTBnF60Vh8wNmrtIxkzIzr58YA1L7Gg0Ksg+juooQcRHmHfsrRxGK/T0mZLoWYU8MRKircLnGz9gc0HnRwb2+72SNe72deB3xxraKIrng7P+dbP7Mt0BucWEzzxOMWlLBYKEvgq/kUwuRImhKtBUxdy2xOoprvVSGscS0SvBjJZJ0QKLYlgVFdV607iQL+jN4+m49YUepSTCCoejj4oQVveZq2qf/63Ef8EPFSW9XXM3yYSloRl4Akotdq7k0T+IgoWG6fScj0SLFoESsEV0fk9T2IfIaOGbSV0AsJBOVn8kx6suvf1/eyHNSZPt7lNDMul+sX0KCG88idlwCM2FMIxz2k0N5Zgawy4pu0J7rXwM2s5eRl07+/btpOPOUc7bPC0gvqhgaXQCVgVmPTdnTeOiRenqN522tOIkyIiSdGvBQhRmmlOUTPjfsnFcccuqBvc2XlZmVnWN42zi3vUovxPcBoEFOICqfbS9GAAiviQwGgUX2FduO6kjLnggWg4prnO03IYUOs2HDoO8c/GjP711vpPqVC5YAb0wViOObtOa8m8f0EM7SZ6CmXfK+9NI6XiFhmdp3rZYdRj042mU8G6KdWuvrbX/FDMO51w50LNiaS5p8mpf/FGKlQNjNrPLPaA4lROFAwow63cdGCIjo=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE0OTEwODM1MDMzNDQsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmZlNDFlODEyMGE5N2JkOTYwM2NhZGU4YjZiZTA4YjdmNmY4MWJhZjg1ZjQ2MmZlNzQzNWQ2Y2VhNzUyNzAifX19', 
             'trail': '', 
             'op': 'false', 
             'speech': "Why the fuck is there an egg in this story?", 
             'powers': array( 
                 "/buff", 
                 "/stoptime" 
             ), 
             'buffs': array(  
                 "/shot give ". @plr ." pistol"                 
             ) 
         ) 
