@plr = player()


@hero = associative_array(
            'name': '§9J§1a§9ck §fF§9r§bo§9st',
            'class': 'jackfrost',
            'sig': 'qvx6n40UMjcPOpMDwvrSVOo3QmWEU6rXtNU8+yxxkVnIaQxio+iRJLK4pauLnnqRzJ9Uba05bWE/WEpwVkHe0iak342cdzWAr+VZwk6Wvz1ky2M8tHH72vuQff4g3ybB8eYD6OOJsw4XBFXW7aRS2nb9P/pILITfwbarWo0TmOZ8vQid0kIdzeAx6+1QYRmKYOaxLQ2zD3eqzJCfY49f3HvoNZOXHv7etVP183jMCpQgQockWn9a2tqZF8ivGoSR5S1pNXZnyPI1EFJucC8NwxA6A5I9WyFtfZleZhAG3L+yvaSfwKUB20vIV3NTjGSJATh97N4EFrOdzuMBrIFXKAgZ0bttxlCF5+XTFzgZL3pXAa5z9wPXlYqc7c+hqfZFk5arNPCP8x5VWev5pJpu4aZlHhHj3/hVkpKuTr55wjqR/qXWYryYQSi49CWLhP7ZrqqqhOYDL4AmAM7C8ipIead6Ys3K4fTjGWdlHUk2Kz4Kiz3/cau4LrGWusxoHUCLgKAWSbCQDHn1tDqnYAuBAmmxUFGu3HMOzC7e4dfqHjS51ombx27Hx3wx1BYg0YwDl0ps7BR49Uk5sNX84CfeTSqTyKYxE1BQ8mgabn+FueWjSadRB/FY8DNRphIRKA+JNWsDWTav9ZzRMmYntoaKya1byZyE+2LJgNEuouubgy8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTM0NTk5NzU1MjEsInByb2ZpbGVJZCI6IjM5MTc2MmViMjRmNjRkOTU4NGQ2YmZhYzY4MmQ1NzVhIiwicHJvZmlsZU5hbWUiOiJNeXRoc0Fkdmlzb3IiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2FjNWM3NmE0YWMyMjc5YzcyNjJkY2UxZDRkOGRlZWYzM2ZkZTI4NDZhMWJhOGYyN2RhMzhlNTZkMjNjYzJmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "So cold!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/cast iceshield",
                "/cast frost",
                "/freezewater"
                
            ),
            'buffs': array(
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/shot give ". @plr ." icebeam",
                "/give ". @plr ." minecraft:ice 5 16:10 17:10 name:&9I&1c&9e&9F&1i&9s&1t",       
                "/give ". @plr ." minecraft:iron_boots 1 9:3 name:&9F&1r&9o&8s&ft_&9B&3o&8ot&fs"
            )
        )
