@plr = player()


@hero = associative_array(
            'name': '§1J§9a§3ck §fF§1r§bo§9st§8(§1R§9O§3T§fG§8)',
            'class': 'jackfrostriseoftheguardians',
            'sig': 'CnjMBYOScbc3Hfkn+r1eTacBGUjs5E0dNPoiKrrdBwg0lTZ+lfbX2w0YeEOSaBp+g1xv4Kx1HePIqH5JP2zBvBwrajV/BSXtg2w7m5nweLMZDWphcvnEY5ZW+U9KTKZMJp5lJP7rqNERDngrE9f7Dq58Ffmx81SIlFDQxabgcU1QvnoMS3rFoD48LKuednBN/M1ewaAyRWrRdgvhcZNINJ5DmYWL1b3hTYfrzXgNcNL/jA03iOg6DVb2RkptxvTJolp6B9HOAwTB9+w2vdJx3lsmUNvZm80vLbMt5ROYoPmLj4tOyfxwZE0CfxKGgQveAVgEmohkpbDmRZJq1ff+GnokaoxSYdTXpkCw60Vxskzbt41kEKhppjDCg1SQgjFdGJa7LeIlw/8+Q2hR/MHVrwXicwpvpu/IMptOXTZk0relcb1Mmjsuoizy/eHP40F1L6NYDh02sHESBK7dx9IdaEdJ+miJXPPQGdi20ldJnG6nk27J/Jxdx8b84916/2rD9ILkeXJ25Q0Pabn4toLg4PrMz+UJMido2Ij0amluvwc22ozPeJrGQ9mE7zQk0H9xqBGmWz9xMQZHVu6paulOV0hT0yfJ/b1amzOtIav5tEWC4B2+SEbuti+XCX4IVLBx4IFts83jPZYQs8TWhc+OsvSsZ1KOvwbWrrMKmSDulpE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTM3MjE5MDU5MTUsInByb2ZpbGVJZCI6IjhjYjc5Y2QzMWU0ODQwODc5MTM3YTM3ZTE2NGYxNDk0IiwicHJvZmlsZU5hbWUiOiJCbHVlUmF2ZW5fIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82ZjRmNTEzOGY1M2U2NjE4ZDhkMTQyYjVmMzk0MzA5YzVjMzcxY2IyNjc2YTg2ZDNlYTI2MDZkNTFhNSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Its Jack Time!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",     
                "/cast frost",
                "/fly"      
            ),
            'buffs': array(
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/shot give ". @plr ." icebeam",
                "/give ". @plr ." minecraft:stick 5 16:10 17:10 name:&9J&1a&9c&9k&1s_&fF&1r&bo&9st's&8(&1R&9O&3T&fG&8)_&9S&1t&da&9f&7f",       
                "/give ". @plr ." minecraft:iron_boots 1 9:3 name:&9J&1a&9c&9k&1s_&fF&1r&bo&9st's&8(&1R&9O&3T&fG&8)_&9W&3a&8lk&fe&1r"
            )
        )
