@plr = player()



@hero = associative_array(
            'name': '§6J§eake §6T§ehe §6D§eog',
            'class': 'jakethedog',
            'sig': 'EHXMYPqFHimhPHEL7Yl2aXcHBANXt+QPFMKXJSHDjabny3P0YEKDfiPH1IjfJPXj45gTIjUhOD7cX4Uy+KCWOc2ZUSFbcQBisuZkr/i4NcN9PCc4Bn5PfFZtih6YZOWVgTg8fonV77lalnn7a0kClkViiiiI3cMXSsN7k5/27S0n24D6RLFQjHpISfWovUQE9WUPTxmmNy0W9TAka2Rp4WUhauinpiOSp6XuTDnujL8ELWVbHhY93Zo5+qKTURqTs8enrrsZSC3kQ0yDJodAyjI0WoANMipZ9arvfdRamKtJmYJRlgJYKZLf4xuFjsTk05FOIQxftrVobT24h4yVZwBadqtN/4eySXi3B4GPCUp/FvZm1e4w7YPitZw/9epMGeKFzw987RkAsyaLspgoZ4snY59V1CojGatdYH3eOfIotrQlks1+gNzsbBrDNCCUIodDVUTKzvace6Bb8BJGJ3lxtKmjrlfL8dO3p1/P9dQpBD6MGdIZ/y/UkGKE9suHr6D8WTzxGFI660cu8IyuBohlAatq6/1BLAig+reH7urVm7zRUhGwOpEyN1rswWdJ4kB6ctHuOom973i4prCMbWy8+hngAWZWkG31jJ+0G2M38UiP/aqI391nWaTBBJlWIzqtcaShANKic6Z4uIFw9Pck7kF1Fi43sqXLDFzZqBs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAzOTIzNTU3NzQsInByb2ZpbGVJZCI6IjVkY2Y0NTcyNmNiYTQ3N2U5MjgxN2JkZGQ3ZWM1Njc2IiwicHJvZmlsZU5hbWUiOiJXeW5kZmFsbF8iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zOGQ0ZjdjNTE3ZjBkNThjYmZhYzYwZGVkZDNmNmIyNTdlMTRhNGE5YjFhMjNhNTI2ODFhY2ZkNTQ0YjBiOWM1In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Ive always got room for ice cream.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-4",
                "/jump 0-6",
                "/haste 0-5",
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 8 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 8 true"                
            )
        )
