@plr = player() 
 
 
 
 
 @hero = associative_array( 
             'name': '§5Jas§7on §7Gr§eac§5e', 
             'class': 'jasongrace', 
             'sig': 'BYTDSmDunfIgpxgMlJVYjG9MQ8E4GAZ2Ab9wejMADCtt/IDAai1rOl2OTBqGpF4lV/nkqF3IUxMlOYaLHcbNLZ5IN3Id8vNrQrlp0IcCk1Jz/9EmERvHKxgNVO/nLHBHudL51thQ9x4M3Zx7FMgXT0CXZDUgDiTCaQ78s3BFy2MTeApVDKLqH088lEZpypzVzaY3X4hqCi1bbjDBlLMj2eweBh6P97wZvpSpi/HSipgwRVGusjM+SxfVEO2KeziMxJyRzM/PBeyGD9RvVbeOo/oxsr1Krnbh5cPHKJ91NDa+v5A0KUbjD8ywUoj8oNb7J8iyPKrP8FIMJSzKLRfPI2jHP5TE/mVatrpa66q534lrC+623o/zedT1+nnmhW7EK6NI4mH4MK+YeVYf6QHHC+NT7kkzVBgJZpUhvA1fC5L4KiU45+0xRcDx2c6sX1f+9AZwUn02XlLWqtTPG3unFXTaHNcu3WdFbUpVxmlCw2U86tA/M3ilo+Ee3DlPEfwWhZn9zVXcOaOkY6YjJsMtWyCJ9Le7/D5XQCnLiDnebPz+cw3SYDbJtV27r0JXe5PIbEc9/60lZCUVmI9NwrnWyfDtzdzJpCDEUI7BOv33Fl/7G866gwNjOFz6+JUG1Q9S6moqOH1AJQbkmUiFQcCj1FdGPKDUNPsNoevJG64bhS4=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE0OTUzNzU3MjU2NzYsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2I4MThkYjczMTE1ZGY2YzVhNjRhMTc5ZTU1YTUxYTgxMmI1YzIzOTJlZGNhYWYxM2Q1ZGU4NDFkY2YifX19', 
             'trail': '', 
             'op': 'false', 
             'speech': "I am the son of Zeus!", 
             'powers': array( 
                 "/buff", 
                 "/lightning", 
                 "/fly", 
                 "/run 0-4", 
                 "/jump 0-4" 
             ), 
             'buffs': array( 
                 "/effect ". @plr ." 5 9999 10 true", 
                 "/shot give ". @plr ." lightninglaser", 
                 "/give ". @plr ." minecraft:golden_sword 1 16:155 20:1 name:&7Jason's_&eSword" 
             ) 
         ) 
