

 
 @plr = player()  
   
   
   
   
  @hero = associative_array(  
              'name': '§eJe§1an §eGr§de§1y',  
              'class': 'jeangreay',  
              'sig': 'BxxYvh9N4x35a0aVSnTY6ODDS2pPiamMVW4q5QYRjWr82w1RIhCwo5vfV0ygMsMcOqgntg46eYNeiDSFiSVSuM03MkGbhm93nTmDrGkVvW9H2AuF2Who7yIH+k3jXYsrf+JGPa3wZUuUFOh1ov52kaI7WsVre86EZ48Xv3Thn3mgt+vJrPJwUQDrhDffsnxRSvs2f8l7j1JU4F7rHW00wkPEKK345g+7zeNSPm/Y0reYV4ZZxjB8Fq95V4TFZ3r5bRzPWtap71x3dm6r3VdmKNwqaDp8ncr5NoIi8OEGBUZmbOuoC4+vFc9ja8n+8x0G0VgaJaXs8x8LUnWrmCxM1i4UeILwlvPJmCFLCImOgqAzkko9vJi1xSUtEShLeIX9cK5n+uHOkZUm7DAO0tgEVmWEkUgqnwBbTYoGd4xKcFZOSyEBttJdE97baa8J6Q4LqJctFEU5WsBDq2dGXhgChNlZwNQLFLyepi1/4v+uwqxsVI2zHjf/IU6iHxhcHEgNx/Sj38MGDXe0fkOaTxaDl58PaaPla/lXSHBO1WU1Uv8EYpWeMeJE8S6Mg2OYD1PbGoVZsKMxD6w8Q7dAgTWXoEgHZMqJ31li04fU/8xJNujdh2wMYlFxOv+LMpB7/pL/d/Rk36Z+jilFF12LxAedJ/uUbxbh2HfDdSSGi4P2nYU=',  
              'val': 'eyJ0aW1lc3RhbXAiOjE0OTQwNDAwNTc5MDUsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjcyMjM0YzYxNTY4YmI3YmJkZDY3ZTM3MzlmMTllMjg3N2Q0YjRjNzNkNDNjNDlmZGY0ODQ2NzZmNWY1MWYifX19',  
              'trail': '',  
              'op': 'false',  
              'speech': "I must not overuse my powers!",  
              'powers': array(  
                  "/buff",
                  "/cast forcefield",
                  "/cast telekinisis",
                  "/hover on",
                  "/hover off,
                  "/msg <playername>"                 
              ),  
              'buffs': array(  
                  "/shot give ". @plr ." psychicblast"                 
              )  
          )  
 
 
 
 
 


 
