if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§eJ§5e§fr§5i§fc§5h§fo',
            'class': 'jericho',
            'sig': 'PGcTFnoOX23Yi8Oun4hjMKYn/3l2KNfVRDh6D4z9bE7Tj1pPak7KPfmWmR0jyLCy+EjYtTOqNL8rGJdjM4hc6yeUZIdX7dEXTArc32nDXSrDMGDiq9NObBbvlITBp//BNPxMfqGMiWCN0/pr28Av98uR2DDD5gi35Ixsr7SZSRSEywAZ5qIYI4u/szWO80EmT/Juz7f1gACJSWZPgxTyJeHUtCGeqdYvkziuUvr51Y5kVAzJO2QGt/TJAniYuBukwXfVjfHbOam8fcp5XiGQ0ZRbsPs1uDt0h9GPWVCq+VKhsvDXLEJPlvRcrzrmyrtDvCZadiyl0i+g22BnlSv5rVQAMFyjpy+mSE2UBStAVebnMjc4jAig4v3vQ4JAzluiX1QO0hAL3T/Nygb3eFtKB65WTnq9+K/J+HqrcRKfn8+2bpruHgquI6/GDqe9Fa72T1wqHU+xAm/dN2CZRxN4SU5lvyNIYFd0EMD+xqNCEoA0yV//KSl6EH/Uty+Fuitxnn5LhtA/XpU8ZttfmSMGVqWw53odHXFF+9l9+FChae57uU/A2ulMqsV5v9hnWFPze/YazcGOz+xGUTQMlD9dSGWPhih62xuQpDwyrZ2736FHK8koP4L2cfHOrIiNkzUlST5YfQVMDESNk9QaZeKzTQcp+rk5xiSFWyCf8UviPX8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDQ5ODI2MjA5NjUsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJKaXJlbl9UaGVfR3JleSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODdkN2Y3NjZhNGEwMmNjOGZmODUyYTZlOWFjZTgyNjg1ODJhZTFjNzViY2Q5Nzc3NzlmOWQzOTE1ODg5Zjk3In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "...",
            'powers': array(
                "/buff",
                "/mindcontrolnear <playername> - Mind controls people in 20 blocks of you. Can jump from person to person once mindcontrolling.",
                "/stopmindcontrol"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:stick 1 name:Jericho's_Guitar"
            )
        )
