
@plr = player()





@hero = associative_array(

            'name': '§§8J§0e§8r§8r§0i§8c§0h§8o,

            'class': 'Jerricho',

            'sig': 'J6BAQWi9u1C0f3t/Idk2QePp6oNghCy7UVeQigJtzsy0WUchY3Dg11+CDnUn/Z2MhM+bK06trbQ30nbyFS4xVCDML1V5mI/7H07Jij7f1MBti2N60klEC4hrMb19zpsjGatgRc548GEo4weCOycc9NjIi8iLyrHFu7Gw904MofM3jKNejt5rFnnUR52Z8RQSmmHg4mz9+aIQqv8i1sQURjdCNZfEhDZ/g1Vyi1QW9fR/UdGhlFXrvBZygVeQ3VMk2CZx+X+bKlzm7tjL4Qq3tpY6uO/qB70vwB7sVSjXmtenfFNCswMPnoJ11FA+ToH0qgkg4YhdPBuEAwU+JqPlxISDswCMG26VrNFE3pg6HDgtkYnXb+4n17ZWoiUfX4Rup3rhpf1OmhlmZdY37irT5WgXd8zT38DVaY5zhHKetXKv9EayjqsKk1SgSli9Q8odgoiZZQMne0nwuroixDjZH7eWSECZ87FcQzOrwxyBJiYk+OV1S5rUWilv7N0zmPz0IE5dUaXlJGl/VaLEuEPsmXh2GyBHBB7K2cbwTZmEztqXXfHXbT5Nerl/zXxQRLiAS03eoZnys3WvSpD7TWgFgaP0AqBt7g+APIw+dCEwfW6aNmtafOhyRRHTsjUiSHgnb8W8vGK7XuLdKScNy9clv5497K2VgWOvKACL1wXM1MY= ',
            'val': 'yJ0aW1lc3RhbXAiOjE1MDQwMDkyMTczNTUsInByb2ZpbGVJZCI6IjYzNzBmNTE5MDdjZTQ0NDg5NjY2OGUzYmE2NGU4NWUxIiwicHJvZmlsZU5hbWUiOiJRdWlja3NpbHZlcl9sb3ZlIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS84N2Q3Zjc2NmE0YTAyY2M4ZmY4NTJhNmU5YWNlODI2ODU4MmFlMWM3NWJjZDk3Nzc3OWY5ZDM5MTU4ODlmOTcifX19 ',
            'trail': '',

            'op': 'false',

            'speech': "Im In Here.",

            'powers': array(

                "/buff",

                "/jump 0-3",

                "/run 0-5",

                "/haste 0-7",

                "/speak <player> <message>",

                "/mindcontrol <playername>",

                "/stopmindcontrol",

                "/confuse <player>",

                "/mindlock <playername>",

                "/msg <playername>"

            ),

            'buffs': array(

                "/effect ". @plr ." 5 9999 20 true",

                "/effect ". @plr ." 10 9999 1 true",

                "/effect ". @plr ." 11 9999 3 true",

                "/effect ". @plr ." 13 9999 1 true",

                "/effect ". @plr ." 16 9999 1 true",

                "/effect ". @plr ." 21 9999 19 true",

                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"               

            )

        
