@plr = player()



@hero = associative_array(
            'name': '§4Je§ess§4e Qu§ei§4ck',
            'class': 'jessequick',
            'sig': 'R88gG+mbpGKFDECdzTtihKW97trkjqX751uqvjji4WbDYQfqyJY7ZyrjCSUFXoq41YQI3sYhySKwq7dXymARZnUk+mJ6Ia1EhftF7FC+mm3Iq/W7IEV356GfepCnFWlSpfwICYxNPsHQKR2YGKHJai0JFwOQErsFgxRD1qvnV5jkLdN5wEeQXQk5NgsvcuyKhNMZFy/EGId+aPTttlHJnSzOH90Ggr1bhZcPzQH2IRsXGbLETv7NPZyrjbmKg82ooi4lQV2Yd3HtdAcjcqTccdSy1CAPeO2XuIk31UPCz2LRI5/vDzj5XUElhoNWp1+45OABgH/7WfR2/2sVfCRGfaQa8eibyUCvnkKCGd06q3EWpL7efjGYO3o7JnK51Hn1JvT9+DYHw3DSc2JmPUKxiQ/z3ZZhTcYJWX7Wq1yEUXpIh6lOLcUGi9aZjs2JvgPPydHq0sJ/qeTLMIC6DE245Dg+1LS1JBykyXL6Lkngqo+IhrXtFFWGZLXLCNlp0jf7rtO5RBldIMewgOZw75yLk94rNEXJPnSfPWKuNAzAGTJbemCWlBkWy441arngxOugolLCiQHr/Eyj087Z0pWq2pq6R/YEk077BUDahcaDsK+Bj5H0Rk6Cr6FVJQbqOmieiEN9ma+taLVy66XXFpgzl0ugYII9ZJCukNMomCyD+bg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODAwMzI2MTM5NTksInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJfVGtreTRFdmVyWVRfIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iODEyMTgxNDRmMDM5ZmI4NDM5MzdlNWM2ODBjZTdjNmU1ZTkyZTY2YTliYjAwYzY5NjVhNjQ1NjdiIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I am Jesse Quick, the fastest WOMAN alive!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/speedforceheal <playername>",
                "/whirlwind",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/haste 0-4",
                "/thru (phases through walls)"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 3 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
