@plr = player()


@hero = associative_array(
            'name': '§eJ§0e§4ss§ee §4Q§eu§0i§ec§4k',
            'class': 'jessequick',
            'sig': 'jsR0nV+HMefvyhXbEpPwgQymJZYwy8WUGDAdo2HcHXVZkva/Abyiyum7LHjuHksQ3jlZFJH/rLtVM5a+q1DT2O29XnE95h07IfPoycPeodyIS0ZjlWo0jxQuHv3bUaUL7nfUCe1/yCf8hdtAKyoY+c6Zudu4N46joMtbIX4Rp1es0/csoT5X0ruQYEYz8NondEt1EgSCHJ8DFSmpO2Gn2H3uEnBKxGpLGdU1JBkcSyAKZN3vyjt74qZvvTJ53TKqjhJ4wLXQPFNBYr2ygwuX70DC9uQhoBt5DGCOQE9V/gEJAGCFmkGLugbi1HkNw9F5DXvgSaXWcXh9NOE6rF2I96ra6zO/4i287w7qVwofn1gE8x2V5w5OP+54uN43DppyOSOtcatjcoJCtlxrOOfyR1cEwmEg8TOBQWrjO0TQ7awcEyDXT7HNCW02GfmK4GVnFpXHW0SiVJwiNE+qnoUXkoZkbygq1CxHgzzO5/U3GadiIaPsyIYxxRtuMoUrhdLcz8eV0fkfekbzkNnzcbVonQnrharBEruNymUS1KiMB+RyAvzkg4dKxBGaxZTNgxFJIEGn5peM7c/mtbfAE9gJVUGUymfnmMlovEUC3l40NrkBVRam+PGmp/jcnFDQU9EMxT4W7i6NpaSVAZsSosvc67w4kB8qfoAKq+YCI9DSHKs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODA4MTMyNzExOTYsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81YmU1MTE2NmU1NzE2ODQyNDQ5MzM0MWExZGRjZDAxMTdmNzYwMmM0N2E1OWE3NjcyMmE5YmE3ODgyOGY3YiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "My name is Jesse Quick... and im the fastest woman alive!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/whirlwind",
                "/carryplayer <player name>",
                "/dismountplayer",
                "/run 0-8",
                "/run 0-1 (In the speedforce)",
                "/haste 0-4",
                "/thru (phases through walls)",
                "/vibrate",
                "/fly",
                "/stopvibrating"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
