@plr = player()


@hero = associative_array(
            'name': '§9Je§8ss§7ic§fa J§7on§8es',
            'class': 'jessicajones',
            'sig': 'Mo2wF97iLyp92t9yfxZaKoS8JDaZgr8aSGj5TRJPaMFE2EgllTR2urQHiz0qPpRDXR9N4Ye4o1E2WWIFY44pbnH9vqkWwqpP4BHrBgGwhglG1IcwvuhH0qKBTrZR1k/lhwBVusbwmjQAzPnD9Qoshiw/XndEIMnkoknzH2RiquTGS0kvDPSlLHAWkCI8RyElWPYhvd4vmbs1ksYgqsQgJKZz+8XcG9Es367GD2IykJ/unBw5I3OjTCemJffgkBu01oAppbaTKJPzqJlf0h2n3/9p6CN0J/Ej7IMyejTAx9W7N3nRLhEN66RCgf9eVqoU9cojCM13agIgFZrFRWXAGICdeVeqfJxh8j/6RcnwbWArHwPbMpjSkzDMxZkhEGgls8VAvHrhcyPpg0NdfCmEiH4My5WrVW6DmUp+Vf8cDRWFZJZ8qXy/4pCXvvprUbrxQsDojH6gWlQHtnDEJBXOeJoSQccASvu5gEq0cx0zommQbUWM0GdWTv5lYyt5aXjwIH5fR+4s4LirS8xgEo6ffWxGiQH2TX41hoYU/TxbDLwpBJv7Y7ELSp8z25crWPwyGFnOuN3f6b4NDR1cqvxYfN3YJxjImBoCqgZLKw7biL9v1tj5u9I+xEGJJo76QumZApgd0UkmvYxj9ibZcAolTZGEOu8gPe0RRBk1eDhaXGk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTUzNzkxNDExNTYsInByb2ZpbGVJZCI6IjllOTQwMWE2MjA2ZTRjMmNiNDkxNDMwYzRkNGY0YWM0IiwicHJvZmlsZU5hbWUiOiJLaXRzaGlpaSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzEzZTk4YjI3YjVkODczYTk3Njc0ZjNlNGEyOTM2MTAyYTVkNTcyN2NkODk1OWY4NTZiZWQzOWM2NGI5Yjg4In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Help me or get out of my way.",
            'powers': array(
                "/buff",
                "/fly",
                "/flyspeed 0-10",
                "/jump 0-5",
                "/run 0-4",
                "/haste 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:potion 1 0 {Potion:"minecraft:nausea"} name:&9Je&8ss&7ic&fa_J&7on&8es_&6Wh&eisk&fey",
            )
        )
