@plr = player()


@hero = associative_array(
            'name': '§dJ§8i§5n§0x',
            'class': 'jinx',
            'sig': 'HP/MHDi/MPqrjEKzROpblCP3Uhz0Xbk+IOm4/k0knvfJTVXxcl4RBdcup7+knEeqbACF9bBRNW11YjBVOThs1DP0JoKJ8un+xSgLdZdg3igm3K6S+5S3ZktX7b1xPuIWQH9op3IZ8p1M+sSuCdjJAjbCmIo+V4mJHHJjocNhIzXML56Jwfi3y9tlxzDXVyE8eiOKs1i5pxJmEyabJZtkkkkLNhYBgpbrzoCbn12WE+seAiI3dde4S3V20ei7fhJukX7SEZBQM1AabY2VwCVglpDZpJ5M9E4GCeFNwWXJGgqrVUgMy5seQQYGt36RKuCQ8XXrWiwP/2RNbp9sIOs7Du1z4qkJECE/Vg09EFsdoqgrRfyAs6NzZL3U0EWJBbAvSTScDyFDWwSWWmI2ESU6MzS/vpndl+zu2mkgOH5z047r8ZJdQJa/oaAkY9UVnoIRCzW3On3QZ4tQ+6jPzgV7OW1BYw4NbmoYBwa3rdg5wqGYFZoYd/JngzsMTyeJTZNz8LVcFUURXWiZWjZWttn3WcrfbV/OQ9auH2xRJCrlvnFylqWS2ZzlsV8/3nXrLvACqx5PMx5bOcfiuob1Kq4flCZwI2h8oMV4/EJHduKiQduVRZEuNLf/DCPchRwUxs8GeDH2kxEwPrUW0f2x5B6Xfz4rXfu7zMTxXqx7pGZVhp0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODA4NTc5MTQ1MjQsInByb2ZpbGVJZCI6IjI3NWFhNTQxMTg5NzQ1YzRiYWRiNzk1NTNmNjU0NTE5IiwicHJvZmlsZU5hbWUiOiJmbGFtaW5nd2FycmlvcjEwIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWQ5OWMwNWQ4ODU4YmYwODA1YTg5ZTMzZmMxMjA5NmVhOGZlYWQxZDkwN2RiN2I0NzYzMDQyYjZjZjNmNTYifX19',
            'trail': '',
            'op': 'false',
            'speech': "Im bad luck... I never really got to choose.",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-3",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." starbolt"                
            )
        )
