@plr = player()


@hero = associative_array(
            'name': '§4J§ci§4r§ce§4n §8T§fh§7e Gr§0e§fy',
            'class': 'jirenthegrey',
            'sig': 'A00mfrTCxaPwvn2vYTygUExw2fLW4FocozDdSSbOsNv7qTYMyz7svDjn2vmudYNlFW5AkVVb/LI3sCngwlR4LDO+ibkRgl0Sp9DScPAQM2aHrdaPzKBh85PUF+yiQsgvJN0Y3PlBiTWG9weBg7Gn9x3Dt3NmHLz8Nu7+C7N/ukt5u6+qW9OCw6SMF2L6xn3otHuhxDsKCBklZZu6R6cONSvTTuZraWIfeCnLlXTSIs20KL5H3EIt/GCcTvb3fjiTLa70rnu6TeeEPutB4xYbOCRnHbH3z1PRs5n3kUQu7oPX7VZFWisKqEC97hpKqgBZldPjvXtiyzLwbykbOzuWYyULY9tYosYVDs0jR9ETJfg+l+132k+ixnKMsCqcphANxgCIxBdjvyIm+MFTi3XPCaEn2HxF/iuLZXQGHIQYemwzJnGI8d5dWxG4T+9ooOanu6VyrtmEfFwec6WxTI2J/l041+KQezvUZNXaYAuSu8T2Cz771rm+NKwt+w8v4epMXMFpv6+anKdsgZo2lFBo6BNi4veoekB1W03ly0Nm5F5tGOkXBkoIVthDFoATApYNkSogwycQGt9Tkf5k1asYykzsAX91aIYzjleivItE0erRnkFl15u21sDaW8yTJZBv9wkOiYDjig4W1HTIypkYlI843MnSZy7oBQWIGY13/3E=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDE5NTQ4Mzc0OTksInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJIZXlJdHpIYXJrIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80OWQ2YjY5NjhlMzk5YWY4NGU2NWUwMWZmODVhZGUzNWI2OWJlMmEyM2ZmYjhhNDZkMmRmOTI1ZmVlNTcifX19',
            'trail': '',
            'op': 'false',
            'speech': "I'll take this.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/fly",
                "/flyspeed <number>",
                "Shoots fireballs with bare hand"
            ),    
            'buffs': array(
                "/effect ". @plr ." 5 9999 254 true",
                "/effect ". @plr ." 11 9999 5 true",
            ) 
        )       
