@plr = player()


@hero = associative_array(
            'name': '§fJohn Cena',
            'class': 'johncena',
            'sig': 'iPV77JY8R+xHYNdBDqLhDHRZ4aZjroPykErQ/ndNSS92YajtqVSAsgzKDK5sEarawcmgxj+clBf6GQ4LhS0Q3fu0ZvSd5FUMcNgCTPrnkqfBXdtfasls+r0DB+H5Dc+qEcPAYl9Q1T6JcJBMefn2D0DaUWQNDHrdRIROIBUQkPa4sn1WAHxEnhD2N5wf/wQlVzjkpocpp1szUW9zxFikCn2ALoMzPF6CNEWUljOzIYR+t1OHkHu1Hk179hsheTWifddGcZo0an94GDdphGSGm7RnvQYMOmEysPfIq1TGDLekPXhCUL7f+3xv3ja9eJg6B6NuscnJ4oMTnZ4HcdY3RMfOQPTW6I/G9coSc3BaDtH23fGfZMvmhNcX4GqTapEDqj9gEV3W2dwBbJSFZXAX0m3fRiZQBWdZU2tt4i5npNVjm9e7OahEsbu0MdH2Ord+lwMhYERvUjjbhjMCJZ4ktIqQQLCPLilDU9c0JCwwnJtoLQXfdLwktvXKGt0odnbbFyKcQIDDDUj+CaVZhRtcNMo69wpijvUSZIlKM1oXJ3ZD1VH2rB6Xjpkbp94WVGtklc3mPEZWWTsc9cudphx7MPs3PYwjv6U83Cqv80ni0iKPZuMnrsXMugQFhhPrx2ru+KwBuwzf8pjCc+DmNauIVerdTB1qofxrWZImb/0LcIo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzQ1Nzc5MTAyMjIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzczYzc1ZTlkYzM0YWUzZmVjNTg4NzY4NDdlODMwNWYxYzIyOGI3M2IwN2NhNGI0NWNkMDc5NTU3MGU5NWRhIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "You can't see me!",
            'powers': array(
                "/buff",
                "/jump 0-1",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." potion 1 effect:invisibility power:1 duration:5 name:&fJohn_Cena's_Invisibility_Potion"                
            )
        )
