@plr = player()


@hero = associative_array(
            'name': '§fJ§0o§4h§fn §4D§fo§4e',
            'class': 'johndoe',
            'sig': 'iBzm8UW91YILjiEzgKKgALRirHz6V3hsTY9Tm0m+VoOto/duMzBfSNK8swpTz31dDNtLuPf1trdgwS4golxdqB3jyOZS5pnDrSJGw4gWe2iXUl8CAFO1QWBtsp89gSi3VBZUvZlSw4f+yTdgBVyCVDNhoR43R0SiJkIxIWQ5S//cYRziSZVwD3b/YMMww+6sdOUH1lTtnCXMx5uf9WHbNozTq/tUPSOez/VGa7M4mLVEmSnnKfIwh1kHn62KDuUdlKSfjk2zLVdpNmSM7uWelwgz0LWQNHzlEBZXSZJKFJYccL42KoulRjCGQTj9CBEGpkt1/ce4pOJrlSp1QAuBDRUSxt1Vytl3Dl9/W3AnjNafnS918EqCw5jLVJ1OfCXAwnn/jyoRLbUnOVrpS8rRqoGtlNTHbmZW6lOVB4/0w4BVmZnJqEw1YPEBMZZthWzHdqlgmJWZJ+J+Kj/kYu7DwMpGkoinbxkwRPg7Sfaj4mMgpAoKjmtN9zV6aNqRE3H/Im2niyhuYA62vmcOcCg/+ubyWi63cTGw2KibGNzZT2VdD+IBuGj8wfkZKYqevxxN4eHoNQNQTreEBVVeaw+FLC+SKadgfeEnCyOKgl1KK7KGrBMSAJYm8FUHSNIyTc4oiQD8h5N0hgJRTlE6Ahzun4xNEXcJBRUsmkfN+YXe9qw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzQ1MDQwODgzMDEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2I4ZjQ5ZDQwMmRkMDcyNjNlZDQxN2JkOTQ5OGQ0MWJmNWQ0NjNkNTdjMjdhY2Q4OWQ3M2ZiNTMwMzg5M2I2In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': '',
            'powers': array(
                "/buff",
                "/cat"
            ),
            'buffs': array(
                "/summon Ozelot"
            )
        )