@plr = player()

@hero = associative_array(
            'name': '§fJo§2k§5er',
            'class': 'joker',
            'sig': 'AwQXimwxx8rTzOYRYqOVy03JYdNhKcjcc9TpQj+CybBC1Nf/mKV5kPk5AMpxPxA+DPvf+bxt4vdC5tUn+mQ8hvRymcidxr8ST4Ztdy6EYsmo3seAzONko3tSq4v5ccoSwVTbnj/6Hp5XYJMkBEik7Szm7rnz55dvl/MHTnc6TQ2dto9siCUu1GX35AqsiQHBBQ6XlKPAdegEWL8783aSs542Inad0uvq2b3nG3cnP1PXES6qCLxPKciKf+lwasIIqFyU+3qXIDxw8CsXpISGhvj/JQv+Snn5sjvWK/vSlxm3W1FRAZJSYdHAK0HkF7gOnHuoKYQ7eEe6LVmelQ71h6t3PpvGBXaV6wnetnCN9zv86SbOhiotOT+7FW0KVext6uY7XfLYPQj+ggLsIhKzFPw6RiCH7Xj2J8b3Gwo9spUGcFvfzLUMIv37Nob1b1QQ2jU2MZFVvCJSh7TOrzdKFrge1rG49CULt8wtwPI6PfOEVi+iXOpGVQinu+ANBDuMbR9dI5bkuFQ42vn01e0bIgbPJb12GjBjiWRmaZEODlzt31/EgOJHzcaRi5dLaUz9TmLn4XeVkczqy1SVwNCAfn8G8b5HlPreGGCDEL2NaRE1BfHzQ1fbvhJ/NI41yuimbfOxidw4cnQuqmq42Vjxqry46lQK9b7/Nsx21k7MtYY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzQ4MjU4NjQ2NjcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2RlZjZhOGYwNjU4MDQwZTk0NmI4NjViYmU1ODdjYzVkZjYwMzVkM2MwOWQ1NDNmYjI5MzZiZjI3YWJkMzE4In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I'm the Joker!",
            'powers': array(
                "/buff",
                "/jump 0-1",
                "/run 0-2",
                "/haste 0-1"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:stick 1 16:2 name:&6Baseball_Bat",
                "/give ". @plr ." minecraft:stick 1 16:2 name:&7Crow_Bar",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." cakebomb" 
            )
        )
