@plr = player()


@hero = associative_array(
            'name': '§eJ§eu§2n§6k§8ra§et',
            'class': 'junkrat',
            'sig': 'jI1S6Rv9wZ+vDYxF/TjDkS8G+VFcrcqlc1U/U/mJen1CMK+TiOSZE/ptSJmehe9jjudmtv1SYXCj4/GajiL8Vz63zxP88FSwAYIqdr5JbNrE5yFHDJYL1dFsvypgQ3N/zaYGTs4R/XzK9mRqefBuaTdl9/mLmjDfu9Pg1d0gyG3P+UUYZPOUOFfPgGQpEYMhtHG04jeJt8lh+/Tl72gCKS+t0QfTjg4KfejIPJYtE5VugsoY047EYgfg5mK8DljD/mzMtj6bFXlsm04iWwSHOXgvsxToMlPXR30LGNCud9rjmVjquV+m2OTFg/mZTmy3an1mXqXoBewELVixyqOMZ7Obr1OWlopRm/no4yBbHPb6Kf4MRVHV6J4M28c6p7sm75TUvfty/RObASYXA5pmgU+gsnMHRp/g0A4+D5UrXVEf0E8x6kHE2ud63LlSKnOAdSV/JHdAoPu4EUfgVsZ8g/Q6PBpMkxhaQNggEiBcZVOLDXWdR4tiAvXCoqMYd+SY9B3VUhHfKBhBOjNYwWMDhx0dRc+iD4z1i7WAjFJxJxsPbhSvc19PBGZ/qzj22AKIyL7zrRkfexV7rD4IbczSFyD+BtAoL/Pe4UJcx3/M6fXa96LOfwLGMtRnvY9xtM0zsXBfZp/kiGqgCJJp+3M+4x5mCY1P/xjM1Yvd6gp0Q5M=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcwMTkwNjMzNDIsInByb2ZpbGVJZCI6IjhjYjc5Y2QzMWU0ODQwODc5MTM3YTM3ZTE2NGYxNDk0IiwicHJvZmlsZU5hbWUiOiJNcXliZUl0ekJsdWVfIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lNmYxMjkxNTU1ZjNjOTI0N2I3Nzc4Y2FlM2NiNzQzOWIxY2EzNzgzNGFkZWQzNjIyZTE0ODI1NGE3M2EyZDkifX19',
            'trail': '',
            'op': 'false',
            'speech': "This bomb's for you!",
            'powers': array(
                "/buff",
                  ),
            'buffs': array(
            )
        )
