@plr = player()


@hero = associative_array(
            'name': '§4K§fa§8n§fe§4k§fi',
            'class': 'kaneki',
            'sig': 'QgdmChmFY2lfcAjzIzrSJdZB6ime4UAJ9DTWFq9yQKycU6rN5Hrq1CpjhbzUtCGq0duTW/Aa6jaIXqDI8PNh+8V/HxxpZwNvRAXg91+JYlwAyXntVJzP42s8Pc33mTmMpYygoOIQ3xkeUOA3+MjY1DJM1M7IqgpdNrSZbwOcCUKjhgQNMtmNGvVROh2AkAevP0HpASmu9PzfqKW3VEo23svc25jmxgrFkj5bd7b+KNY/lDNKcMTHBN2KwPdMlYn4+2pMNCc9VLdbOco0Iqjg+VoT97SxN4v8+etW1n8Pu11rGeh5BCofZwgbWvysYDlKs1zWCocSezIHlpZueCGlZGGSAuIdEGE6/8W/FxGR32907I6gcNlTfnpoz0t+xtc6QsZxYwEaeX0QcT8X4WsAQZkpGfL0YEkb2vvAnAfFYDks+3ZYlP3LT5T389y5fx0P6PNUygQpWxf9cYs0e6xW6prOwNVXj1Lt8E+NweLJ+0E1XOGsrPIyGWA0X6xOTLPBGVAEvPs+NJvfWF5buMKcaEiS67FkqUWvcKVakFC7j6HMRsU4V9anRqTF8kjKxt3odAI0dT772QHOAe4qioQnUnYgCu8tzn5d+1dbXw+g0zlGR/XN9rygqr+828BiUbxbIWCjLS+nVA0sC73ZPJL2eDAndoNRlD67xpC+yAwSx2Y=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTYwOTAxMDU0MTUsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2IxY2M0NzZlMzI4YzVmYjY2MmI5YWZiNDY2MTIyZGJlYmVmMzkyNDU0NzA3NDc4MmE1M2ExNDY1ZGQ1NjUifX19',
            'trail': '',
            'op': 'false',
            'speech': "It's not the world that's messed up; it's those of us in it",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-5",
                "/haste 0-2",
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." kaguneattack",
            )
        )
