@plr = player()


@hero = associative_array(
            'name': '§7K§8e§7n §8K§0a§8n§7e§8k§7i',
            'class': 'kenkaneki',
            'sig': 'JHMll0yCKi8kj8c1NPejq6UoUDCPQlhCL1WzOyS0w/2OZIX4nKBkwcTh9v9vHiYQDSgo9zCxgGCwgb35PVrBIODO7PLfgexwcVp8PySf8YnPMTXvFKaOGCb29+fLpmIjmXOYthvqu/+H95ab/IWj4x5qMbJhMfrlci1A5oA7gvVaRkV0BW+Y/40pdaSRSe0YwY/j6SfbJQjeBzmKLs2xK10WDBfpbnvArx/uj7HGq94qNBrumO1UoQs4sCAUndXj0YBeQa8Np4wGh8Cr9KrRvgjockmx2+welbniTSWrWQTOZn2ZOWDYcW+jaVnZjwFuu4nHHTgKJL+CI7O6qI13EIwMH33sy1yH/OL3EQtFzzvS9rQh1Wx7FW4s5LSaG0DbSauIQYgNoqfK7Hi0f+LaEmao6wUOrR9KE7HTBGMDfBZskjZ08byFXLiELu2IxDUb4R3E410GOB1mlm8AWVSKWqCaRedYWroR2zQOINXldRK2IIQRMBmLChAC84g5GXi8QkCqLEWNEwA1yvW7XFZ0UF17OF+xietyJzer96fMlLZQU+B2I/0fTn5F68z5XLcwb9f467mys5/D/MaS1+/r4YY7hiJSvdPfTvP+tPc/9OYQVVPdiNzTWqlvmpB1Yg+BEtApwIf0xoL74kWQLVLiDI7dsOClmp/vf92ynp3oHHw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQwODM3OTQ2NTEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJSb2JvQ29kZSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjhjM2MwOGY5YWNhMWU4ZjFjZmExN2MzZGZmYTQ3Yzg2MDcyNjdhOWIwMmQ3NWIxMWZhMjE3ZmExOTMwZDAifX19',
            'trail': '',
            'op': 'false',
            'speech': '',
            'powers': array(
                "/buff",
                "/run 0-6",
                "/jump 0-4",
                "/haste 0-5"
            ),
            'buffs': array(
                "/effect ".@plr." 5 9999 10 true"
                "/effect ".@plr." 11 9999 3 true",
                "/effect ".@plr." 21 9999 14 true"
            )
        )
