@plr = player()


@hero = associative_array(
            'name': '§eK§4i§ed §4F§el§4a§es§4h§e§8(§4W§eW§8)',
            'class': 'kidflashwallywest',
            'sig': 'lELtZMJ+SSeppXs+2Fk6aEaBT237vpJK+6nJ0qiYv2lFNvy+r+IDpr1G6jl7rxfL3xPrSs3EH+efZBStRg+3BT7z52v+qKzBJUAiWisz2d7YDDsYKITCvIlJWN02MAiTLl0qn9Ax6pkt5gne8Q5KY30YCyuL8o9W7pGX2gQuzKm8FS5NfWgT+JiT2pSYc6iDLUdn+eKF/eRd8y5+Q7LcCKhMA/L56NkIn2YpE4KwW+3y16PZwDh2k4ez4CN5OTBDe8A8eUO7DqkvebpUyyYpYIkqendRqNlm2C7iVCU1ZbUeJzAEwYLUNBWwL45ash51RppmLG7eofABD4YfTDPiiP0gR/7qdO8yIOWFm7DeNEzDOnoV76zSPLkK3mjWYX/XzSS+q6QU0e6USCA8ow1xCH8BfwOOawnt0Bbh3NpHaTgj9L7tAZ1MfhQuF3083acA7DwA5I4iQWqTZvBck82HQVBM/6hBEfTB/UyJKaDRJ6EbSQzadw4wiQJN1eOal2QPPUnfEs7PdANJRYlqSv3HdvakgCtbvqMnp/8pAFUPXEwANaEZNjk46vXWtJUDq3z21w4RlhbQlmz5a2jxwFbNbpZdVRjYhGjwVpkEZGzeh31SqRKXQ0EW6jDeYRNSYXkWQnoChrtRqJ1g5VtNovbzZ+yY6862xFjipeXr4uqP3i0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjgyNzU2MDE1ODEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzcyMTVhMWUyZDYxM2Q1MThlYTM1Y2Y5MjZkMjg2ZWRiNTQyZDk1YzczNTVhYTVlNzQ3MDNiNWZiZmU2YTc1NyJ9fX0=',
            'altskins': array(            
 +                 array(  
 +                     'sig': 'vLm5HtbiO4tLQAcW2DIiKd22lnE8B9KePfqe/kvoFJU7eRyBrczhMdbd+S+e3VfM/ffXYcyM6HuBd/IYVqqXwfGtmGq88O6lQMs/I2B/C0bDZEzs3nFMH9W47oBt4N9B0RfOJ6UgIfle9OQvK06Twg/OGOSKnZ7aei9WPE2/rxXvZ5d68dQ2j3kDQoGEHLbnPuynYo7UKLfx/z8OOi0zKwGEFv8ZJQoZcXgqZNIWeCHXZXADQ5fiF/qXAv5zElduiUkMHckqjGSrM1fHr8XHh6HKvXX9mjD4hpxf6gFMiQdW9b4Z1S67xSYGCtzFFvs4gJk/KeOLkskRBCC2kPTKtyB+jLVSn7/cng968KOzC2AySLukFfasFNi4udZIHC85Naygf6/kSfkuWUYxn6Mj91K5DP0QPpoayYj2GeroleyKW77laJwN4uEUU9m6z0zY3VLyl0UzQLwYWBIyAGFZE75y5qTJeVzNI6fWP/cx0Pl44Bcb5PNm0yF8naFwwJhYoClNCqJYjrTjkGVuO1wTG3yaOYnYV7/0JfFWNdiu8vWJAbObssW3fgZq+k6pF8Pz29NYdpP9TW3WEQ3O1cvnfU98LvYIop/hGZxN3+mSySWbLTU/EBBJe365cw9CuoA8juDzZiKbSuth7rIR0bQkkeB9TvYOsxQpS5l8WzkQ4Y0=',                    
 +                     'val': 'eyJ0aW1lc3RhbXAiOjE0ODg0MDEyOTUzNDMsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJNaWxlc01vcmFsZXM4ODgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzg0NTQ0YThhM2E5MzFiZjliMzZjY2ZjYzRmNGRhYmNjMTdkNmExZGU0MzQ3YWU3NTg1ZGRmZDZhNTUzYTUxZSJ9fX0='              
 +                )
 +            ),            
            'trail': '',
            'op': 'false',
            'speech': "Im the fastest KID alive!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/whirlwind",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-8",
                "/run 0-1 (In the speedforce)",
                "/haste 0-4",
                "/thru (phases through walls)",
                "/vibrate",
                "/stopvibrating"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
