@plr = player()


@hero = associative_array(
            'name': '§eK§4i§ed §4F§el§4a§es§4h§e§8(§4W§eW§8)',
            'class': 'kidflashwallywest',
            'sig': 'lELtZMJ+SSeppXs+2Fk6aEaBT237vpJK+6nJ0qiYv2lFNvy+r+IDpr1G6jl7rxfL3xPrSs3EH+efZBStRg+3BT7z52v+qKzBJUAiWisz2d7YDDsYKITCvIlJWN02MAiTLl0qn9Ax6pkt5gne8Q5KY30YCyuL8o9W7pGX2gQuzKm8FS5NfWgT+JiT2pSYc6iDLUdn+eKF/eRd8y5+Q7LcCKhMA/L56NkIn2YpE4KwW+3y16PZwDh2k4ez4CN5OTBDe8A8eUO7DqkvebpUyyYpYIkqendRqNlm2C7iVCU1ZbUeJzAEwYLUNBWwL45ash51RppmLG7eofABD4YfTDPiiP0gR/7qdO8yIOWFm7DeNEzDOnoV76zSPLkK3mjWYX/XzSS+q6QU0e6USCA8ow1xCH8BfwOOawnt0Bbh3NpHaTgj9L7tAZ1MfhQuF3083acA7DwA5I4iQWqTZvBck82HQVBM/6hBEfTB/UyJKaDRJ6EbSQzadw4wiQJN1eOal2QPPUnfEs7PdANJRYlqSv3HdvakgCtbvqMnp/8pAFUPXEwANaEZNjk46vXWtJUDq3z21w4RlhbQlmz5a2jxwFbNbpZdVRjYhGjwVpkEZGzeh31SqRKXQ0EW6jDeYRNSYXkWQnoChrtRqJ1g5VtNovbzZ+yY6862xFjipeXr4uqP3i0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjgyNzU2MDE1ODEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzcyMTVhMWUyZDYxM2Q1MThlYTM1Y2Y5MjZkMjg2ZWRiNTQyZDk1YzczNTVhYTVlNzQ3MDNiNWZiZmU2YTc1NyJ9fX0=',
            'altskins': array(
            array(
            'sig':'KLbSWPfOT8K/lj65KVXz6MiCA8PJ7cA+Fb9gUVrtBE1laumclZ7dFAaZcIDm2r0q5kDi4x7SfZ95z2+JPN6hJnHdsana7qxnxYOT13ljiSZOJ0TFH8ma4UfXlNsEeOBCbV0ACEbRoJBRsf/sqbNbZj3XKXrp448BvetGkRMtDySyBFnYHSY6qNNr/zWOHNQO8m3V/18KWJbE7UhfXexvxxk2AMZQtOQwfM2OFvT9iO5UhuGVvwo+ms6Yl3UuaHxehTMOWNc5q8/HuDb66h34bSNxC17o8L/NIDaRe2hO+pUcC5bMAv5kJj9kjnaqqB+7P+lKKLArcXvtn3BK8jR4uMFC12q3OG0hQEg7hgwWQMqCYKV5QSb4MNjdcUyUYQuXejUwrH/2y8XgC/7PHoOMDQxuatOkNNAo8qt7pWuiNrx8r8R+rSFgyyinBRZUxQXvbnOlMv/IiEq1Nw0/VqwJuYU2N+l3T/l7QR089Ji2r+JN4ogGAenRATWE2c+dasWWZ3hekYM9e8iO/av9tIE66udaiUrGd1pycMa4RmfOyFyqiQ3PW1eCldnYXHTsq36YWRuVG3sMT1VWkBIG2txx8427z4ZM/QL6A8BIm9eXsuFJb6F0s6jbK+Yh4Btlx19op/D5ltHQDH8ALi1zERUo81LtttfPBS8qtXJ6NDGjkeo=',
            'val':'eyJ0aW1lc3RhbXAiOjE0ODk4NjczNzM0NDcsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJTdGFyYmVhcnp6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iMDg4ZWM0NDY5NjZlZjNjMjU0YmZmZWY0OWQ0MzMxZTM2MjE0ZWRiYTZlZDNjNjE3YTU4M2ZkZGNhNWIxNTkxIn19fQ=='
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "Im the fastest KID alive!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/whirlwind",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/haste 0-4",
                "/thru (phases through walls)",
                "/vibrate",
                "/stopvibrating"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
