@plr = player()




@hero = associative_array(
            'name': '§2Killer §aCroc',
            'class': 'killercroc',
            'sig': 'dycNwt9Rwyk6MGVdEc8KtnOSSRq03APoenNbJyCidhN4AOTZOvM3jKf/15K7/Q6Q7NLg3PQmYMLCB6TiaeYRAO0cUXtabsouTh6OPyG0gkJyTr7tTliPoxu6UKS6XSMQ3kimsLB7E12n4N7mcZR6rkKtLt9QXyxlhYKmp4CmD08ZgtFFR3KBvAaY3Tt8R/GRsLihbOphx28vfQLLbXt7G1OsqL7IE0+2Dol2msG6FAE85H5XKS2dZft/O3fZuXdA2s40Ezk0nXEqdrBhHM0jbFOy4tEN/v5RYTg05FDZknZSW/3QulajOdRo15EGL7iepawwC1Y9xWh5kS2iv3DFE5yJz//qRo1kGFB7Ty9gWcx8NcjmodK4SaC00qlibxCxeuEl9rBB+aUM5n/RtwAxcniKbNIQcJTzbc/R2HZzjshrV2eYFO8SwUDYp9uXkX5+cb3RsPXkyG9T9wFulabU6f0jDEbXK068+1kpLD4BXYe2K24cD6KGnnhhrbe7FtkkP1rAm//UX8KUjnbToAp4GIX6Obf0ERNS25lbvO/y+hW6GvGFt9zD4uZ/qYjWuPuun5pwQF+bnZVk8puwY5ef88FOA/u+NNemt9Yf8p2quKs1QQw3wIurnT8Nu1v2EVUvAnpE+3qUNlqNoMyfKOhnWx2QopAv8dazPgOfTsqt5Bk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ5ODk5NTM0ODcsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80YWVhZmY2NjBjYzc0ZjRiMWY0N2M0MDdiZTcxNGE1NWU4ZmQ0MzY4MjVhZWEzN2Y2ZmVmMzk3MTIxN2RiMyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Lets get through the sewers!",
            'powers': array(
                "/buff",
                "/carryplayer <playername>",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-6",
                "/haste 0-5"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 12 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ".@plr  ." 13 9999 1 true"
            )
)
