@plr = player()


@hero = associative_array(
            'name': '§9K§1i§9l§8ler §9F§1r§9o§8st§8(§bCS§8)',
            'class': 'killerfrostcaitlinsnow',
            'sig': 'FyMJC0gfquheDsOvj/oaAG2j743Ef1kB6knwSeyrZ1hg2F1DNdPQe/w80sdw2+Fl3LvOmc3UbnHMUDb7IA7Yj68ZCuArxkXJRK4phbmR1gFmob5q/mPa6kUYWEkU3Mc49/Zpv9PvbcWcurGPjijd9hxlpde+krCU/KQEH1fCsHZtlS9CT3IQw+kVG6qA4FqGTAs44UJUxBbHB4IYhSrh7PgGoiXYTOreehLz1xFN8KHiuVbMZ3ukbqbXiFeSgFpeH402Ckqqjfmurh4crz+XiO6uXdCCrjCpV4I43W87dCTRj+0GLfbv3U3fbLfG7FqMyoEfssbKfAprcHnKMx0EnWgPebShKGTJjBGV03lf7bV0iseOAxZKeuIp89Gjxx1lO8/uk4UjStQ4HMSZ7hn265vCfAIOldq1P00ZCPWogZLhYSn7zJ+cFAFIq4nUsrB9yOpu0H74ROK548qUxjHqv625iDWlPI5c6vWD2QfQgelrTa/NzQPvDupTshfR4Fk11PIeeyQx30CI6JWe3KB8Yk0ZhYqXvQ6ZBjzeAU4VaO7leoBdeovvdkOTUcsFMCiRsKcJNRbfChKD6Laj46OdPWt1E3P8TnJT0eC+qlTzZiKBQymMVZljtTHEWgDI7zJSLLuFZZEQuWmC91waXnuTBgufjZzh1OqntUfG7o2qPbA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQzNjM0MzUxMDEsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJhZGFtYmFzaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjRkM2FjZTg5YzcyMDdmZWVjODRlZDc0ZGZhOTExM2ZiYTE4N2RhMGRkN2MxMjZjZmQxMTQxNzA1NTZkZTYifX19',
            'trail': '',
            'op': 'false',
            'speech': "Feel The Breeze!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer"
            ),
            'buffs': array(
                "/shot give ". @plr ." icebeam",
                "/give ". @plr ." minecraft:ice 5 16:10 17:10 name:&9I&1c&9e&9F&1i&9s&1t"                
            )
        )
