@plr = player()


@hero = associative_array(
            'name': '§fKi§5n§fgp§5i§fn',
            'class': 'kingpin',
            'sig': 'ybQJGhbSkqxnq97CyGSU4dEAI4uL59T04Eim0dwiWmSIB6FlL/pQXb4UfqAGxotiBJjLFnl4E8RwcMmnhuTjEC/GKSsY2QDnz1wGxCo6Bok5j31WlgjF9VWLhjrz8lUrC/XOIo/aBCysFxFlDYrLjIgOwhO4JhMGQL6iOM4gF/2nMGy376l1eKDcGgOjM7+lpFDS/O54fUMSbtjVj4a1om8X42SEebZxd1QGkoIPnLp7Yv8wJ+dKHF1pbPL4GKSwLnuvQRgQIUVp0jkrkKcyEFigbqfQcBACFux+GpcgDgKmyfdlA3Ng2dvUfCA3zP6Hu9wgPLVYwd+3JjWsTmbdmZnbjvFqv+ktMHxrZKG6xvpxP8XRDx3HNsKmguFhoJIWx4bu7rP6F7/mbz7c8Z/O3pnlm2c75Dh+4XuXJ9yxi4H8lTcAL/HuNC49dbtTKhNABhhdjKwChFTebRNYi7f4zj9ryIU1/SC8p1t5dgW6YEFAO3aWAwCZNlnde6lnxbMKtPmBp8WKaPaJEiPAzZ1vNHMAfhaWcq6M3yf1VhJ4ZH6jXcGmqmmBweDQxiEM5gtA81R3jQ5rAjpe5qP3PabzT+LhxXzCV/At56CDtqhIKlKshS0xlOlKijTLKCyLJmyvQw5REnYB5PmW0QJxcFKZh6JOyGaLrAn5inwJ/3NuVyg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzgxMTI1NTQyODksInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJXaXR0bGVUaW1teSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTllNWYwODM3YjdjM2I0ZmFkNDNkZjI3YjY3YjU4N2UzZWVkYTQ4MzNmYzUxZmIzZmY0OTkwMjg5ZGQ3NGUifX19',
            'trail': '',
            'op': 'false',
            'speech': "Wilson Fisk is my name.. On the streets the call me the KING-PIN!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-1",
                "/run 0-1",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true"
            )
        )
