@plr = player()




@hero = associative_array(
            'name': '§fK§4i§6r§7a',
            'class': 'kira',
            'sig': 'HrI3IoxlBKDTQ6QVBVATpfefMBddZhqeFo3RcjKG2VzcLrrDX3yESQeWwO07XNulZSr9LFpSgNv4x+DsAOIAmLa1DRzaiTLgOx3sKUU2Cj3jMHiyDOgWgjpQ+Y7luW465m2lMYEC2Q2i0eq5NmkvHM4seKFSwfPCweVdW2G3zhmMazYuGHvfV4bVAGk5r5/KaT7a22Jqg1dG6MSZT94cJzmic86WzkdBmj+ovehNpidAVnxVRNlmb3xURa2Q953o2oxKWfFCbAtM1LeDMhZRplJYbYOMOna9iNYTTPkHuSt1ppgwa9IxNFoiiGeakfOMMB3UmKFzs4ATbNFXa+UeNlusXvKmm+mLS67c8sk5eCA5ODXkl2tf0YEDgNY3+P3vQ4rRq9sDYoTkfdBwW3kJ99C253CK38duV6HPF4Uw00KT/HIKKfpLy/+DVso04RGQ0Hfk2bxlvJ4TERkRN52tRiSV3GNQ2OQIXRi4yWOXZyIwYEdX2KZ5e0uF5mlk0XGocgRw7cDEzbwnvsdAyOmEJkKkGSuNQRN6yTKjrHqQVj156sAAXWgJQSbtGD7zYuIoMRzCr3URFIewg29ECzcsgePSZUtaKfEPDpK+yPlxDRLS5vODDKdagdKrrQ6oiSBjH8nofJUt3ElkY8Na7Z48y2+3gVg1o++Bgey4OiWQidE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NDk2ODk4NzIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2NiNTc4M2I4ZGYyMTI2ODZlOTIzY2JhNDZmMmExMmE4OWFjYzVlNjlmNWE4OGI1OWM4MjY1MWZiMDRkNDFkIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I was once being bullied... but with my Deathnote it will never happen again",
            'powers': array(
                "/deathnote <player> <deathmessage>",
                "(example: /deathnote Bob123 having a heart attack)"
            ),
            'buffs': array()
        )
