@plr = player()


@hero = associative_array(
            'name': '§0K§8i§7r§0i§8t§7o',
            'class': 'kirito',
            'sig': 'hM6c9d34W+9jqJpNlub5rn27PD1Eh0EE6GnV40aW7fF0ylxUitLNIRynsDJ6I19XonN/sltdQKyN36qLkkZIlTmHKKM4kMforeUJ67Ea3w2kvgLhFVvvdevHE3TN7FNmGoE9zTFp04erGZAlTiwUcu9sFVHl4DBLdgmBHF5sypBXveW9xE94lqC9YJT54176gd1fux5Jo/4e3c70e2ixfKuPWqEcZQZIxuwWi0B4GTtVF2tCVBqrZefHl9sAIzVUJIdeMn8/699rSA7GAgnIS12EhfIiLQ+vxIUDlljFCk/QX5hVuvoXfig0BjR9PFs+8FtCX9Wv+GTn7X4VxeNhnzsyEjkAJ8gfWyYHbNEKNOAUnejh4tVDIN7tcC1IJuDLTB8mnJsZj4QsJkgJoJhr1Wfrq5N9tFbK05xrYcsPvhrtudXmKFZf+9SDy7h1Q5NzXVcOR4/oIRn9mz7UlVxzTvvOPbnfU2xVXtgoLlzM1OSHWsoaYAOedLomoqRlbnHNRFg7xxCuaHVR4UYiuKMF4ShWIJTP6S2HRtpevWri0I51JA5QXBsM7385jwHx7RVEkUg8oDQuLnnMO6lE1Ge6OYRhO4PgRsylx7CkOv6bzS7N5SM1fXYp+L4aeZkJlDTTlfno+ayxGZPz5EMyPU0BW9tqblpzcKucCFqfs6kqm4A=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTIzMjM3NjQ2NDMsInByb2ZpbGVJZCI6ImE4ZjhjZTVmNjRlZTQ2OWQ5YjNmN2Q3MDY5ODk4Njk0IiwicHJvZmlsZU5hbWUiOiJLYXp1dG9LaXJpZ2lhIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80ZDQzMTI5ZGM2NjQwZWE5NjY2OGUxYTY0ZDgzZDMyN2U3N2EwNTI4M2ZiMjE3ZjcwMWY3OTQxNWMyZWQzZDYifX19',
            'trail': '',
            'op': 'false',
            'speech': "Link Start!!!",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-7",
                "/haste 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:iron_sword 1 16:20 name:&0E&8l&7u&0c&8i&7d&0a&8t&7o&0r",
                "/give ". @plr ." minecraft:diamond_sword 1 16:20 name:&bD&3a&br&3k_&bR&3e&bp&3u&bl&3s&be&3r",
                "/give ". @plr ." minecraft:gold_sword 1 16:20 name:&6E&ex&6c&ea&6l&ei&6b&eu&6r"
            )
        )
