@plr = player()


@hero = associative_array(
            'name': '§9K§bi§1ta§9na',
            'class': 'kitana',
            'sig': 'EEYjnaKWK9N/tN6n2gY21qUXfXBK+DFMYqgwl6+yWDDyHDHyMCRXKAc7A93Fo49NEukkVTI+cZX+XMoDTO42myOb1VaJOL4NXP0fVsRELy9iE9Q4z0evYsh8KD3q1343AxNNV1Ov+VSJjF3TwSReYo9OD9ekEVr4WPKkWv6yFsGfi8+DJjnQeMMpbR93bIyBztorcqSbGuNS5xeHLCBlTxO8yB+teuTlVjFCbUZ9D3+cw5F/pcFKImn5PM4JLCBAWWx4ZuoNLezqV93eLmfhMLR9jqg1NENwWwmlcPYti/A7Wwb/UgSZUsNUN6KP5JnjlFKlDhS3o2pL2TVFdoaWp+ZtJ4B3yJZWIo4rrG6UI6Ywb6J/DTVBk7GIHXELUJr9Zr8LBQEr4DyKO8tQv3UQQRAW1ZJA9bXYYzzmwLVgdFd7tnKKwZ5lgzi/HiNiMNbZVTRPsBLhaeAKaq4T617oSDgOB7a3s4xMa61QduyYizUr8J9FXc6YY1GhKuyM9uHElDTOhqDd5F2oRWJVuFFJ2rby7kszqR9onvrjCvh3vwzhVNO9joHz1ERKxPI3pdqTUcs/XvdRqyB2XTUJRWiXprFeQJ12z1ap5afXPxx/NIbzZ0EwGBq8E3JR0j/ttVdvi5F7izniGZYV1D+xSnUbMACgUuIRoAlXb01YWpoxp9E=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTQwODM5NTEyOTQsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJMb3N0SW5HYWxheGVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2U3M2YxMjNjZjI4YmExMWUxMmE0OWU0NTdmZTk5OTQ1OTNkZTRiNzBjNzhkOWUxYjIzZTg1OWYxOTg5MjUwMjQifX19',
            'trail': '',
            'op': 'false',
            'speech': "You will learn respect!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:carpet 2 9 16:10 name:&9K&bi&1ta&9na&b's_&bBla&1ded_Fa&9ns"                
            )
)
