@plr = player()


@hero = associative_array(
            'name': '§4K§0y§4l§0o §0R§4e§0n',
            'class': 'kyloren',
            'sig': 'pOYCwx2uHUJl2f+HRs8P1leCxeaXYgnwzVR4AZ2OLMMhb3cAMnX5PFDp9Fn0Utd+Lm1Q1rqYoL6wsJ6hhKLFLwR2b2n9OlYV9y5GJurUYQAc98DBemdfF600LClWMzQWrODh/dqB18SkC0QMzzOTZjcYakEvFoewnh7s9euPP0/v0NjGVe/jZxpdHNGikyLBdnk7fsbW+7oRpXDpvjEJsFcOeujdZ55nhN4IOsV3ZAyoMCGgdLXo86RX6V1YGFb3vzsbdd+RxeJ8yKs3umf5ru9veICdtZLNRGd4aEKYLtujbXM6g60ksnitXSr2jBopknPX28nESyGoPS+DjK+UpcfSe/YEZ/VKngWhrnPbG8IO7wMOG0q6nN/+UFcoTR4ole7BM6fhqTlvdfQ+Os+yKvCiH3Xo4AM+qrudGJBvQPoWegAOUEyuuBvg4vIhjuzyROPNhZmI88DpWO1SMDWh4u/L3jsJHXQOVUVsN+0VR+0xotVTxvYKqlmtMZPdxd/kK5XCrxkBXkVhSi/wLUcmliKaQb7+YmnIx6EAJ7zd23fbREdwXYz7AEdjqQhXQJpog+OjU2+ym6CWB807XkXYptDGyNrugKB4Vr3U13vI5e7MeefO0/pg58fUiA1UcIkMyA3BfIUBluPOHE8DaFyipJxwljNNAn7IKwfRTGyrdVg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTQ2NTY4OTc4ODAsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJUaGVfUmVkX0NhbmFyeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzhmNmMyZTlmMjI5ZmRiMjg1YjFkMTJmODg5NDExZDc2YjIzNmE1OTEzYTY0YWFjNGFmMmU4NWI1NTJmYTYifX19',
            'trail': '',
            'op': 'false',
            'speech': "I CAN SHOW YOU THE WAY OF THE FORCE!",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_sword 1 20:2 16:100 name:&4K&0y&4l&0o_&0R&4e&0n's_&8L&0i&4g&0h&8t&0s&4a&8b&0e&4r"                
            )
        )
