@plr = player()



@hero = associative_array(
            'name': '§5La§2rr§6yB§7o§6y',
            'class': 'larryboy',
            'sig': 'NOG2yKhNH0InKl+qSRJr5QI6sHTPuBrU+lGuTyW9abbd6DrniKxmBnzSDDBvym49L+WkYnJDDOh2412uoP5dhtxihvdZOcuOuElSb81gS/hjZ4AH6juwzFO9s3S2tvQIckEX9BPWMBoIku+QB+XvbwsK8vBTptTq8iqn2WlzKGv61culZWeocJ7yGbEclIZkSJHeclkhcJNYsE2nbhgMwT1VgKOdzRMSOqgvru1pDRXGhmF5B1LAAHUw7X3d5NIgzmeRuuIdp0qxfPhjA7PFG6KdWNl8yAKQuOn6GxWGMCQc6Bb5GeanKeVfsNP6L+ekNe5Ub/1RqcbIONCv56XrtS0lmvcVC8G0KYrkiBAww7Bx0A2yR3MHefdq3pX+u2BVHFM/BIyP8z/kioAza7KioBwKuZduzDJiMlZd9j4dJEBR1dkArx6Gn4DUJagTDErnntvPMmt1UmlP+9Zq9CCYiOrW+E1qO4BJO8MfgqC7Hhns7EF1t9OM86YxFdNgwkrgXl2OEiPHJJJYTDLQG68uuAkEZFpujeqOA7vRQcWrjlFj0+2J2OmXeS0vLdqXbO0juGtuz1JGjYI/RxawzDb0vvnX8iT/jG82vlsBOEmwdsDHimY+U7AfebMNJaUzo9iD/Woch+ZkSaCT+dqyS+qoZyi05oDb4TuCpNN6tM8Q8Hk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTgxNzc2MjY5OTUsInByb2ZpbGVJZCI6ImM2Y2I0YjgxZjFlNzQ0NmRiOTY2ZTRlZDdiNDU5MDlkIiwicHJvZmlsZU5hbWUiOiJMb3JkT2ZHYWxsaWZyZXkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2EzZjJlNDg1MmViNjMyYTFiODNmY2NmYjMxNDJlMTJhNzQ5MWU0NDc0NzliZjEzNmFjNGFkZjM5OTYyNTFmMiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am that hero!",
            'powers': array(
                "/buff",
                "With an empty hand, right click the air and you will shoot a plunger ear. You can use it to swing around the city! Note: technically, you're sitting on an invisible chicken (lol), so if you wonder why you can't move it's because you have to press crouch button to get off the chicken first xD"
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 5 9999 1 true",
                "/effect ". @plr ." 1 9999 1 true"
            )
        )
