@plr = player()




@hero = associative_array(
            'name': '§4Le§fbr§con §cJa§fm§4es§8(§4M§fH§8)',
            'class': 'lebronjamesmiamiheat',
            'sig': 'sYNdDRgAdZDMXedWBimDsCg92HKRmPcVXAw6a4sdrFO+HvgWMlSrNYmYiJATnhHgrk5MuDu69M1vNq2W390rj70jQaO2MDV3CxnqUtid82oIyf9vg1IjcMrnB1jZQ50XfyLwK5h2gaaaruxD6Ae5tScRKnwSZJ10bZ0UZN0NPIAs1/Z9jHtMWg7NY6Zb2BphqHlh8jR/VcCf87AEXU+rNzyDxSSJkJ/SxYzvVLBb6Cni2R+VG3ldsJQezGxtw4hB6kKgWqc62PNTAzNNaLJz1A15FQs+mmg585mzzEp2++b4AHTeD52K/ridQoxF46umORe0bZ+zn8SIPK0oos6/af4B1WfA6vOJ1b6cT1cXEN3QHUK+x65w8NuZSBdW1Gwq5lXWHHvIqD5Y3IgbUtM0Z2xC9k3piKNfs39Sa7bHsAEVUuTaxC1vQqAnhHfFSSVeiL9tWf5jVLKkAwuSRilc7I2fRjeA0M6m+jZeVh/LRKgiwJNQY2btkuoni8zWdddsb45zj1WBIzO3PgZPV+4DEGB8oF2t5wYQgfGEJMOCrz/RcZawbEeEk/ZahT0TiRIVg8X9saZ6iAufR5jIQ7qta5eoI6m7/t7VCs7fMXggvc+8mZ7rjRjwH9okVxoeJhiE2i5H91pFc2Has1iSdsQPWiLP739HdH69FCB4o908+Xs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIyNjM3OTc1MDcsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJUcmV5Q29kaW5nIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS85MGZiNWVlNTE5NTE1YzVlZWNmZDdmNDIwMjg2MGNiNDRlZDQ4YWQ1NjFjN2Q3ZTM4ZGY1NjM3YmQ5NTcyN2EifX1',
            'trail': '',
            'op': 'false',
            'speech': "I am the KING!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-1",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 4 true"                
            )
        )
