@plr = player()


@hero = associative_array(
            'name': '§2L§9e§2x Luth§9o§2r',
            'class': 'lexluthor',
            'sig': 'B2CnORq8pQz8ooyfLjkDKGro7+BkUWz8Yf+kKUvg05vR0a/vttMflWkTbPlUlOPxuA0Ni2jsXn24+VXXdAj3Qdc+J7jOk+RJqNEiC+RsMKiDbpdpfjFs21kikNpNEMO1NkWMbXDsjvikuRlQXEQt+9oIYOBk03c3gAW2+XsZVescwXFaii/c3OesiDL+jnCGUf81O2dddqWpE3fiR+w/GSrfOopoFIeQo5aDOapT9ERF17OHoveP3fJY1VholAMFzjQHHOfPEqPE0+3neSXbU8sDdmOjGNEHV5ic2MU1CBajTMTdr0glSqmLkfF6ZJBG6pDv3WLWSR4aZDOo7rryXNH+vbNDuiPNUSetjnH6Fg0Z6hhVxVigsysG6h3o03hbKRbnJMJTV34HHmvDurbSmeLFLtDGQvYHscnhOE6NH16SOXC90IwVggpA1pb5dp/AUx2VQNMNDGaTT+tFFAD8PRlOvtV2BEF3Yo9Xbg9WpoKM/q4OOWjZGBH/5BO0xNuF6nkPX1BYpjh5BSm8Qb2f1qtNrGXGhj18NUod59Qn8JrLvmmGZIl0GhF6Ejb4YE6XD7nLHvolC/D8Yj/rw7jg0vQjPhtiS3j8h4AsryZMfsShTvrVZ57vw1AXCF8V6+8PyU5jMyaYvr6Xm0quofQcoiNlwsjypLeXKNSagARB17I=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjM5ODkwODksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzJiMmIwMzA3YWY4MWJhNGViZDFkMDVjNmFiNzViNTkyMWZiYzQwNDgxNTM2OTM4MTkxMWY2NmVhNDA4YiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "For I am, the smartest man in the world.",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/shot give ". @plr ." magicgun",
                "/shot give ". @plr ." exawattlaser",
                "/shot give ". @plr ." powercannon"                
            )
        )