@plr = player()


@hero = associative_array(
            'name': '§2Li§7n§2k',
            'class': 'link',
            'sig': 'hrfUDis61osl3YouE3aBfHZ5JkzcsUHAyAE236YMzWKb6SxIPHOXR//P6qEgVNAkX7myEbKbjYb7e5h+ncWEeNEj4fq2TBoAM3l8gWuQrh9BjpAga91msdqu6VElxfJq7CbDBQhczRuT4DqwdC0CSrU4hIonMCqRhO48DU7q2iVN39PmPJv48tcgekLs0vU4bvKuiTuiRnhNgDsks1PXpjKOPADzSz1aSurKDcfhJXKqTAXeaL86uzgM/Hs2K0tKlchqbFU2EkQKcJzFsLpBs37eKP4TGVBegNpWqzFzggq9TkV8brAqzocpWO4zLvP1Lo33m6e/YY3sN0KlnCyoUvHEhqRDbNbFreYXHas+SAXYvef7dBQ0HuEWu0EsTyXoJ0a3QW1ilONDuh7BZhBD0fWv3C9ZVIt1M4njd5SEOeSQO7/XX5+i62AZPqGW37zvc9kAC/nsvhK4o1qounSEcWtDST1q55gFhLlXOHtmkViBT0SDnmELa85LCfhoNTW6TbRnjFyLcuS/dssUHEjlQtHFRa7wMwuW6NxyQnlBvCCj2e1hGua8QPBDBGTDMW6A0fyaLi2nWbaDUybDGMOcICy5BirsO/+kVddAKu7mG5uxNZ5yN6ddlJgCoJw8iai2LRlOvNXKOStTdvrrFPztAj7zZOm9o2UYizm7N0QiWpQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDk3NDg1OTc1NDksInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJ4VG9ueV9EQyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2JkN2MyZTg3OWQ2MDgxZjkzNTYzZWY2YzVjY2QzY2U0MjYzYmUwOTMxZmVkNzM2NzE1ZDVjNThhNmMxOWYyNDkifX19',
            'trail': '',
            'op': 'false',
            'speech': "HYAAAA",
            'powers': array(
                "/buff",
                "/d wolf"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_sword 1 16:2 name:&2Li&7n&2k's_Sw&7or&2d"               
            )
        )
