@plr = player()


@hero = associative_array(
            'name': '§3Li§fn§3k',
            'class': 'link',
            'sig': '"CaXO3R64F6hGmOugJ7a5qEgE5P+nCOiA31390g302N2l3A/3hbLUW717CSysMshX+yc5zLECP/2XUScb4UKGzsFyRPMM0UGS7ovILHmaLL5qWR9qy5zrmC69ej/0ZHKOgnpGO+DOW//q1Mq008bMnXLgvqAXH9oK0zgjvKUt63FaOd749n3CsdnjN3a94iq+ojcqL91o9S/MOpndFBtY3LwjG0ox8TkE962+09JWXVTlkokh8GYZg8dCX7m/+YusUJjky90UPnyv9jMqBcWf2aPxS487c6WatTNNYN8IdD1cqwAVVckREjRVaTqPocTKnjBqf/sONO0bGrygRbr3zziFf+hLweQYe8Wb9DViFdNR6KJqqaLnqV+JdAYFH4iQN3wWaUr0Z9NeTDTcz068dJZExhVEa0krnnVSlZoXSkUorXP0kf6St8KfnH34tnQQhHR8edx4wrPpiZQrRwsb0wXfJ81zrxzKXs+q9x2pzZz1UYi4Wcq7AXdm3RFLoEjI97mvluoQ61i2af/i4QkkUVNFt5fxjtwJV4mrjjHndGaNOpAJG7yko2/HEppoANtJO90+9WSRi32DMUoZ3lZa5pHfcyFmKm8P5SJSCsfCOOyZq2mK9bCEEwm9brTZwcxSsJsQ24fbkz+H5+CD+QTSwGgYxFhSYHWYLNZHaqvsRYU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTYyMTI4NDI3NzQsInByb2ZpbGVJZCI6IjkwYjJiYTZkNDNlNjRlNWM4Zjc3OTEyNmI2OTY5YTljIiwicHJvZmlsZU5hbWUiOiJXaW5nQXJtb3IiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Q0OWFjNzkwOTU3MWY5NTk3NGNhYWMzNjM3MTJhZTk3ODZjNDIyYTE1NTk4ZDJlYWM3NjdlZWY5MDk3M2QyNyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "...",
            'powers': array(
                "/buff",
                "/wallclimb <on/off>",
                "Sneaking in the air will make you fall more slowly",
                "/arrow weakness"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_sword 1 16:2 name:"&1Master&7Sword",   
                "/give ". @plr ." minecraft:bow 1 50:1 51:1 name:&bGurdian'sBow"
            )
        )
