@plr = player()


@hero = associative_array(
            'name': '§2Li§7n§2k',
            'class': 'link',
            'sig': 'hrfUDis61osl3YouE3aBfHZ5JkzcsUHAyAE236YMzWKb6SxIPHOXR//P6qEgVNAkX7myEbKbjYb7e5h+ncWEeNEj4fq2TBoAM3l8gWuQrh9BjpAga91msdqu6VElxfJq7CbDBQhczRuT4DqwdC0CSrU4hIonMCqRhO48DU7q2iVN39PmPJv48tcgekLs0vU4bvKuiTuiRnhNgDsks1PXpjKOPADzSz1aSurKDcfhJXKqTAXeaL86uzgM/Hs2K0tKlchqbFU2EkQKcJzFsLpBs37eKP4TGVBegNpWqzFzggq9TkV8brAqzocpWO4zLvP1Lo33m6e/YY3sN0KlnCyoUvHEhqRDbNbFreYXHas+SAXYvef7dBQ0HuEWu0EsTyXoJ0a3QW1ilONDuh7BZhBD0fWv3C9ZVIt1M4njd5SEOeSQO7/XX5+i62AZPqGW37zvc9kAC/nsvhK4o1qounSEcWtDST1q55gFhLlXOHtmkViBT0SDnmELa85LCfhoNTW6TbRnjFyLcuS/dssUHEjlQtHFRa7wMwuW6NxyQnlBvCCj2e1hGua8QPBDBGTDMW6A0fyaLi2nWbaDUybDGMOcICy5BirsO/+kVddAKu7mG5uxNZ5yN6ddlJgCoJw8iai2LRlOvNXKOStTdvrrFPztAj7zZOm9o2UYizm7N0QiWpQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDk3NDg1OTc1NDksInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJ4VG9ueV9EQyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2JkN2MyZTg3OWQ2MDgxZjkzNTYzZWY2YzVjY2QzY2U0MjYzYmUwOTMxZmVkNzM2NzE1ZDVjNThhNmMxOWYyNDkifX19',
            'altskins': array(
                array(
                    'sig': 'CaXO3R64F6hGmOugJ7a5qEgE5P+nCOiA31390g302N2l3A/3hbLUW717CSysMshX+yc5zLECP/2XUScb4UKGzsFyRPMM0UGS7ovILHmaLL5qWR9qy5zrmC69ej/0ZHKOgnpGO+DOW//q1Mq008bMnXLgvqAXH9oK0zgjvKUt63FaOd749n3CsdnjN3a94iq+ojcqL91o9S/MOpndFBtY3LwjG0ox8TkE962+09JWXVTlkokh8GYZg8dCX7m/+YusUJjky90UPnyv9jMqBcWf2aPxS487c6WatTNNYN8IdD1cqwAVVckREjRVaTqPocTKnjBqf/sONO0bGrygRbr3zziFf+hLweQYe8Wb9DViFdNR6KJqqaLnqV+JdAYFH4iQN3wWaUr0Z9NeTDTcz068dJZExhVEa0krnnVSlZoXSkUorXP0kf6St8KfnH34tnQQhHR8edx4wrPpiZQrRwsb0wXfJ81zrxzKXs+q9x2pzZz1UYi4Wcq7AXdm3RFLoEjI97mvluoQ61i2af/i4QkkUVNFt5fxjtwJV4mrjjHndGaNOpAJG7yko2/HEppoANtJO90+9WSRi32DMUoZ3lZa5pHfcyFmKm8P5SJSCsfCOOyZq2mK9bCEEwm9brTZwcxSsJsQ24fbkz+H5+CD+QTSwGgYxFhSYHWYLNZHaqvsRYU=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODk4MDA4ODIwMjEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJHb2RfRG9lc250X0V4aXN0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOThlMWM5MmMzYjJmYmViZGNjZTVhZTQyYzM3NTc5ZTI4N2E5NjhkNzc4ZWQ4MzExMjFmM2Q5MWJjOWIzZDQifX19'
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "HYAAAA",
            'powers': array(
                "/buff",
                "/d wolf",
                "/wallclimb <on/off>",
                "/arrow bomb"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_sword 1 16:2 name:&5T&7h&8e_&5M&8a&7s&8t&7e&8r_&5S&7w&8o&7rd",
                "/give ". @plr ." minecraft:bow 1 50:1 51:1 name:&bGuardian's_Bow"
            )
        )
