@plr = player()


@hero = associative_array(
            'name': '§2L§ai§2t§at§2l§ae §2M§aa§2c',
            'class': 'littlemac',
            'sig': 'TY+oT6RvXbvT95y9eSoRgB3mB9DmbcROAEUwZdUcdiDcl6fEGe4FRBG93cnz+7tfeznOcI/V3U1PLDQj8t/I5WCsWPKXiyC0XHbeu5G8daU5bNL/XSmjR7O4K+/fXfzb3pQ9gjKjKfuv2qKmHVORH0zj3F1aIU9XNlTx0t/mPe+tv60r62UILzTCwVP/INVwcfFX+xVjsbqmbHQXAskoOFM9GhAPDDESTshm3+JRyFo6w4Pq8szw8wXUmDKCgPmgZFe8ZmtHFRhMKUpkNBQRs2WyNvsZu2/6rGLmmvfGh+mzpZnGLInSLdNTeNecYrqqDgnqjP4tS1bh8Ydn5MOpKQlWrY7+u1mcpH7SzpdqYa46oBohxqnUXOJfdi14UaSuR2SavIHistnFYNrk6XTIAPJei4a2K0JVza7awuSsGWq6B+pIXnOC7TWiDCRdCP7NhZ7BJ4GpQ2L7ToglEsIDecp5uMhOOIHy+a2n0HladMFz3mU6s6BH5D4yPKnHj2Ycmko9BBumwLTCQjQXMXWtpip+hvKPScxpLmkJGeNyOSS+W/PyJ+C2vy5Vu7zau0OA6RPL3v8jQkDEfdFB59FXnjW455jfQE09I3ZQ5XfyR+VHypBmT3IdXG1KpiRzmPfgUVVk7KOmIKHbiHQXq4d0CCQMnwxW/0d7DixB4BkhUWw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDE4ODUzMzk0NjIsInByb2ZpbGVJZCI6IjVhMjFkNGE3YmE4NzRkYmJhM2E4YzU2NjI5YjYwOWNiIiwicHJvZmlsZU5hbWUiOiJMZW9uYXJkb19nYW1lcyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjNjMWQzNTc5NjQ4NDg1MGI5YWRhZDgyMjMzYTkxNDFjMjcyMjZjN2Q2MzVmZTdhYzI4OTQxMTRhNjZkIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "We have a new champion.",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-5",
                "/haste 0-9"
                
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:stone_sword 1 16:10 name:&6S&et&6a&er_&6P&eu&6n&ec&eh"                
            )
        )
