@plr = player()


@hero = associative_array(
            'name': '§2L§fiz§0a§fr§5d',
            'class': 'lizard',
            'sig': 'ZCZ8btzcm9ax3X6LlKpPMaqhAOdQgy6t7eeCAtBPRWUakJXAYyEnDw/QcvGf1K+oZqpnDBkRfskbfVNHVHisOCZ3oUHYaEnQOg4E7ZSWSZ+yol3y+W1TiCaxZ7GsOuROHz3ukOshTEEmfrPeadtVJQ8L8psvVdDATxfgLFN+NgHi0W/1cjlWeDqoLnPXdYGIPhuqVt5PBq4o9smw+SuXeWvGOSVcbePGjsRolwcYOwb+ajJUr31sLrcgrVVkC7mGeukmDrnv4F1Vm3DcuwoQQmoPsk3N/5RSUR24nx+WgSIMld4QevcdtK6VLQThxzSp9n8XCaIN3e0+llp470zeVCNuuuiJkySUrPv77xVBccqZikI2xadPJW7AHeuWHeENPBDq9m8oNwp8lUGjEv59Gbcj/9bZuTO2iMyKb17jqqUQw78lErapHqor5VWIh8AsJ5AtZ9NMqKMvurQolQxV1yL1r8bUITUdpV7o/EY+B7akkrnGGXB71bt3Je6uhOsstZ1cLX3mjrsH/eU1HmVl+8cBhN3tPXQFxPt91Pg07eP1rxPFbM2x/42EZiKBTMscRfgR7TT+v1ZHkUJY/bJb4tIJ7ZyTNhX5G0V3mT10Ea6Od6ITj+yy3eg54Cto1KrWT7SfNAre4gR/s8oAU1TwrOdTWrxgFXLqX02hJS4qfx0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDA5OTUyMDE2NzYsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTk4ZjMwMjllNWEyZTAyYTgwNzhlZTM0NTA0YzQ2OTNkY2YyMmQ2NzE4ZTJmYmNkM2UyOWQzYmZhNDJhYjgifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am the lizard! Hisssss",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 21 9999 9 true"               
            )
        )
