@plr = player()

@hero = associative_array(
            'name': '§6Lo§ede§7st§8a§0r',
            'class': 'lodestar',
            'sig': 'mlmboZGd4fyYmrexASWw4Gp8a02m//LQUMMz+W6qiAHQKpsKgyX9fxSzWMJCASOs+kWkRvDsO55GqRecQdrVlJ43Sagj2qSf5ozGHEWX9LWLsHACvMZW08RzJ8kiSDcl4fLqvyULPkfgsESow34bvVK8Q0mm/pOdFgbV26kp2ic3dEH4bWt70Ch5nfhTeiIZHzbPmMF6ybt/S/z7R/fG/c8d32mk9VhaIotu6GWTVATYU62t1NqhIm6tarq5bWii5reQm7iUGZIL4q2HK+zQTQJD1fo8go/Hv6+AoFCrOQ+9O8MHOo9NGSxXQbsyrowRGnaM8rDzh5tks4RF0q6KnqaMv2L7SlZeyo7q6p8afa0Ve7Lpbl/Hrhdyj2yZZv4ExMZ6YPxulNQgji4JK3gzw1EG8qBj5K1wLRJug9RCOP6WM4ptLHN47NODTF48EI05a8YPD5o2NT29lFqmieHT/PC7AyQYGo7T9Pp/aHD6hX39oqQt4JwGNyGeXcVBd40dIuDJa+uh+XA7i6kZuF3sS2AKaXfKFDHiZKv3CYIzdGD3Dz6Kc8eM8lbFkTsCy9hsQFB1PrJZeAkRtcbKcmF6c9MTVyjgspcKhcFPVbhsslapNQirhjZarY3LP/acOKqviwUDHJvZo5IMGr7bb4XTjKSgftFu2uYJ5IPUs6qNdfA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcxNzQxODQ4NzAsInByb2ZpbGVJZCI6IjkwYjJiYTZkNDNlNjRlNWM4Zjc3OTEyNmI2OTY5YTljIiwicHJvZmlsZU5hbWUiOiJXaW5nQXJtb3IiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzY4ODQ2NWY4ZjJiNDI4N2RiZTdlOTAzMjRiOTM3ZmNkOWRjODhkZWMzNDFjYzk1NmUwODM0ZTg2MThkYjgifX19',
            'trail': '',
            'op': 'false',
            'speech': "Not the right time to shape a new guy",
            'powers': array(
                "/buff",
                "/jump <0-1>",
                "/run <0-1>",
                "/haste <0-1>",
                "/stealiron",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 4 true",   
                "/effect ". @plr ." 11 9999 4 true"   
            ),
            'alts': array(
                'ben10',
                'bigchill',
                'alienx',
                'heatblast',
                'goop'
            )
        )       

