@plr = player()

@hero = associative_array(
            'name': '§6Lo§ede§7st§8a§0r',
            'class': 'lodestar',
            'sig': 'O3+9nG2Fb7LaUUtdPZ/AfBc8MU0jQ/MyYuXbtPpiVJbiTWChV25lvq1g3i62RYAwHgTKdJAaEgKRj0IiNRgW66RKARjEHz1vI7dfk/F4N6Ucgw9aiLqCG5m8ziEWgP4iQKcH+NpLrZR8JZShZRzlToEjvS6xwOe2laed38kx8O0sSaD2CVc3DAMSGY8bBc/XAT8PLUc4YYdTT3Y/h6FcNdpl6tB+Fc3gT3zlTbXsC8jLjmMcy/cgUb06i9Djr/Eeq1N4C84DJ4sksrRLribyMt0fczlqt5RJGvwTan7UTWfLX67sJTuK9Pth1T69Ynreq12pRIdXH6L5yI1ZZ1ee3ft+MCXeZuZ4oDqOr10Wd0vgs5jqCpqeauHgCvQsTwgVw2Soe5fY9IJc40kc9uzEAXANPW8n6uOMrUtJ6d5AdzhTkgdvTspm4b6YRwg0OrPzlflJ8I7iJkPA9malx1eh5EwE1eYMPH6pNUQdhK9VULcd6QgeeUQ0KCue6JQU2OIJQut5LYRJYU0CJBQakLsmundRkyuqoBGCtp3R3oZpKqf0Qxso5aW1akjxhfM/JUCSvV56KFd3g/igMGJT4twTdQ1HmHBDWvv0t9OmDsNb+9x0jNp/XkvRf3T2KS2wkdx6ks03bFevIrNg5ULAzQ0rICfjDaYLIbINpiRFFgKQSY8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTcxNjcyNTk5MDUsInByb2ZpbGVJZCI6IjkwYjJiYTZkNDNlNjRlNWM4Zjc3OTEyNmI2OTY5YTljIiwicHJvZmlsZU5hbWUiOiJXaW5nQXJtb3IiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2NmYzhhNTY4ZGFjMTcxMzA4N2NhODMwZjFkNWI5NDRhNjQzOTEzM2RjMjJkMGQwODg2NTUyZjFkMjY0MjBhMSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Not the right time to shape a new guy",
            'powers': array(
                "/buff",
                "/jump <0-1>",
                "/run <0-1>",
                "/haste <0-1>",
                "/stealiron",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 4 true",   
                "/effect ". @plr ." 11 9999 4 true"   
            ),
            'alts': array(
                'ben10',
                'bigchill',
                'alienx',
                'heatblast'
            )
        )       

