 @plr = player()  
   
   
   
   
  @hero = associative_array(  
              'name': '§6L§2o§8k§bi',  
              'class': 'loki',  
              'sig': 'hzsEQDW0Cn86WJ0XRxGWQxsMmKxelDlkRCK+2MffNTtthtMWySBbZMz/AfPqMZe7sHQ2WaPvMDhgb/jpEO/DrobmopJzIEn4S7+UBY2u+FLGOs6S7kOH8PZX1l1Hwt3CGqaINF3d62H3A+VfUjRl1idBIsKYxtNyeCfJM1x9aZ2KKjtLNJSAN/iTwtCNEpnhY/LOknDz9UGTb/k08Nvv8haQWkXms7Pbij6X+OzeB2nwppVOtIaNIYz3Zei6XpkpYYooZEkE//6e4tXkIUZvLtp7oeHDnjqtNQ2gUmb4hMYoAeLV94+7SfRTwSvd8qMIGjV0+3H0rXuwRdlF/oyuC11mXlOAqAaWUXrUEDL3spkL3u7aHXRcqJp1Qgpx3T5exC8EDnF3AHQEt+Y/HifXWSWNmag6BPTocFx0DNH8PSw9AJWs0HCumWKplFaOdl0tXkH97Ulxn0P2FxoEeD7zXVqkzzoEng1CRM/seJcEN9eeHBnEjKV55Hd2f40v/81U/WE/43EkR+u3GENEt61cPqucgA1zrpEaYhZ9WrfHqcFcHOE9YvkJLPsZcJKhlYqPgGvYcfpDe3Y9HDIGYbi70p/3EUrCGUXTNvJYeX5DFtBws9ghPLvwAlnHJ6HUh7GcmVljamFWAOsPDuuE8LFXbmJUU2reV0wKsvXUO6m70BM=',  
              'val': 'eyJ0aW1lc3RhbXAiOjE0OTExMDAwMzU3MDcsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2VhYTYzYjk1MWQ1NmRhN2RlZDU1OWRlOGVlMGZhOWM1OTUwMThkOGZkM2MzZGU3YzA1YzcxNTc5ZWNhY2RkMiJ9fX0=',  
              'trail': '',  
              'op': 'false',  
              'speech': "Bow down to the God of Mischief!",  
              'powers': array(  
                  "/buff",  
                  "/mindcontrol <playername>", 
                  "/stopmindcontrol", 
                  "/run 0-2",   
                  "/disguise",
                  "/tppos <x> <y> <z>"
              ),  
              'buffs': array(    
                  "/effect ". @plr ." 21 9999 9 true",  
                  "/give ". @plr ." minecraft:golden_hoe 1 16:40 name:&6Loki's_&bScepter",  
                  "/shot give ". @plr ." frostbreath",
                  "/minecraft:give ".@plr." spawn_egg 1 0 {EntityTag:{id:\"Zombie\",CustomName:\"§6L§2o§8k§bi's §aCopies\"}}"
              )  
          )  
