@plr = player()


@hero = associative_array(
            'name': '§8L§fo§7r§8d §8V§ao§7l§8d§7e§fm§ao§8r§7t',
            'class': 'lordvoldemort',
            'sig': 'p7LbFKrA7OAZ/KSkp3/MZSbY6N+Pl3WMYkIDRkTFn1vVjRXx8CnAa5sAIUx7MqCfacVe6nyou59lcmxSJWFO4M4PY7+wTLP7IMZH9mCMUc+3j0p75XGtXuwZGdZWPEKEDxYRzRYro8Q+T0otnvj4kOvWTS3PG3jjJ128epDdHDyo7N1cV0x9OfUZymfkOrqDMqPH7Fq8embfurAuzc8AnQzrh0SjErV0Ka5P20qJBXGXURI5fZ6HIBcFcvAmhIfmrwPxM2xhwBmhcAI6nbwyYgA7GWoILmpQ/zxV1KjH4+sD8YuwnJupjddR5RSZ686WBR1BcnngwzRTiSTtZmW+PDZk8o8D8F+IQQvpVxKlH73w13HxTMEh6VStnzxl14XXblR4H0VGHDZzGVxeqfbtxsqHB7u7P5ko54OGUQT5h7fGJVbLMhohONEIURmhc7f9Zb2hKZArWMIvOvPVgoTjE8imgBvRmNVr6Ih/hPhD8vugPa6CCIwlkxWuSrO6HPuRdEpRldsbNM3uKyAY3xmRylIrtyWYZySDNBXcq6C8PszCzQHjrsNdHV4flbzLCEs2NwLphhAi3Pod7i4upcPoygKJjG0oIJIXQugksE70m8+ron3JdN7pm7suqC8aQFtyWXgBYwZKgSikluk8EfCy2GIjh/EZWY/HizbjcDuBtPw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDcwNzk0NTE5NDYsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTMyODE1OTVlODU3Mzk5N2FlZDdmMzZkNTI2ZDcxYTQ2Yjc5OTJkM2E3OWQ1N2JjZjY1ODlkZDk3ZDlhMSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I will destroy you harry potter!",
            'powers': array(
                "/buff",
                "/fly"
            ),
            'buffs': array(
                "/mgive ". @plr ." voldemortswand"               
            )
        )
