@plr = player()


@hero = associative_array(
            'name': '§fL§du§fc§dy',
            'class': 'lucy',
            'sig': 'nI319R63HVWAYWY1zlgUF7TuKbiUStFzpW8LJFx/emN3opcMhbUTBn65SXdta9GGTDg7nKy1kyy9T5a2Qzao2CnQIqegisREahdASVTYurN43E9gGOhFufYzWoKclXgnPdNZLAEH7AwFeWqzAUWMO8Pr5wRBvJfxDvbfPiMdk29pbmbDaW4Ooo1GQEaVRvjvWvRlIVA2sDCV4Y4iZyOnOXyRpddg516vcUIHYO2JvNbFsa8FBTKM5Yrbq7W+28VgZY+ZKITLpec9CjsEmKAc3Mz7h1P+utaQ7OapoGzmXmHIvnuMLFfz8sFGwXVHU6jtTPQGs+PIPAnkt0fc/M/P31RiCnbtFoZVwodY+ORI4gZUvQJIiWL3oAox4FZ/qIoEBTTT3I2VjeopF65XMbq05CnnKgvZglm4GDwOvRTgLWRD6z6wbEh/skN++8W0uGQ3N6A8zGILzFWmU7VXVkJ9Wom2ldGif4qcW+CP2e+ebe6w1vHIE3UD4PHFnOsfzYfHgyeiROVLUzcFG5n9z8VNP67UqVz2l1Qnw9UxRXBY2bw9DwCWpCaVO6odOTzgoIPbxCsU5EOc1mh/PpkDHVazwZ2S64z65Rid84pEmTef8LnE7jlfKIP1Xr+sNDBuwNqqSFb+uAeJIuVrXLW182sj8F7yRozi1VUICDbTQ1CHRqg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODc0NzAyMzk1NjEsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJVbHRyYU93bERDIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zOGY2ZjE4ZTk1NzVmZWVkMTU5M2Q5YmRlYzkxZmZmMjEzZmRmZmNhZjdlM2FjYjVlODM0MDRmMjQyMTE0ZDgifX19',
            'trail': '',
            'op': 'true',
            'speech': "The existence of life is a highly overrated phenonenon.",
            'powers': array(
                "/buff",
                "/kill",
                "/vibrate",
                "/stopvibrating"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 2 true"
                "/effect ". @plr ." 21 9999 9 true"
                "/shot give ". @plr ." omegabeam
            )
        ) 
