@plr = player()


@hero = associative_array(
            'name': '§fL§du§fc§dy',
            'class': 'lucy',
            'sig': 'wCHlvP31mjr/YKZ2c6w9M4w0HBaQNGhhQEqLm2R1O7CRCT0lB4L6KJALLFLrlvesgfdBIQVbWs00FFyQCElVWEMo2CrkimwCSe7p1EQXTgV0v4P1Txhl1cov8qyTc7FliXWz5FubW395J4mKsccnzZBcqt32y5k24uoqZlo64IKkAOUlietwfUffkoKlkNYfIGgnTm2cTMqONvuwRJ3vZED/v0KmA1QPR9fCzM1VXMtTle1AkrZ0gcnfMaP9aIB6PeGF1lfspfV1tiJEJAol1nTetSwTfRkHDcN6KPlljhab+wgympSRnDByLo8ODNdOtaY3R1D4+cT1RsopWsBBFrtKwJUFnykWvrserjCbTtcUqu+5pdmKnRD+7ihs4mnUag8FQM9ZBHDJxaVpZLQMyXexRtDUTROmctLAIkQcvI003XHk05q16Hh5A94a0OzTHYnyj01xqxP8hnZhCRtFIWlME/liFUi4us40UeNdXiDHAXUe1N9M3pN0raKSiQB/Xhy0aDC+aqZEqxQYnbl6kp/+4NKakh64fVwOix1Tcvd9Yc3AsWvR/CvQkT4hC9IbCpJRr8XhsrQ59BVRw2VsMdb17Vkz48XIYFuoxoXYZ7HJw4NEE8vJ3aORM13hQ7OkWPxlcbRajxeEDr5dvMKDLNmUnT5m7IEmyQZMz6kmVxg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk4NjEyMDc1NTgsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJCcjBrZW5TMHVscyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2RlNzg3ZDY0N2E4YTcyYjc5NTU4YmE4OTRkN2VhN2QwZWRjZGM2Zjg0NjNjNjIzOWZmNjkyNTIyOWVkOGI2In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "You know who isn't human? You know who isn't human?... PEOPLE LIKE YOU!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/touchkill"
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 3 true"                
            )
        )
