@plr = player()


@hero = associative_array(
            'name': '§8L§0u§8ke §0S§8ky§0w§8a§al§8ker',
            'class': 'lukeskywalker',
            'sig': 'S0hKr0cHT6pMNXx5dsmHh1L1wQ1eZvbIMiF7r3x9pcGSDersZ7Iuk+85vMsVJO4DmPcoCvbgYp6sCM26jiZqFR6WY4xPg8HJVkN8xHDl4DmFqL/CnslV/cSJF7lb8e1gsrameNoUoyi8G44e7zJFRq6K6iOEPs5KyBMdZC8PM+2jcoPp1IUygxSWl4ZvTEgH/LPtYVLa11yuCTjrJwBRYk27w19sMU08Cv/VqTd7Jl3MVbcUtrFO1aGB5UjT6jTZcs26WCBDf7qWhb7SJ5kb7YDI6b1iyj4hXqoJoJLlgZQd5eQY3ajO9HyF+2X2zxVCLorWuSOQHZoXUc5Kfw5YBdJ2uDGbK6oBd1eUQy7WjhuBxV9zfgyB2MZb8zZtt7ChdJcoB9vLgbanSCcEooCQnHtdKHxML7kba2Er//jzFkr6woFHAAm1msWAWUYrlpWZ3pqwPAC8UpVonEmbDhHKEp3miQydFQ0hxDTX0M7m3x4ev/aOdVhdSioF1x8ccTwLkloqHXQtyCLkm93H4cvFIVV1mc9sINiDVaHSJDA9y3c1ahY1DSkRXNVfZQY02r+rKBhwu5zHR3CSGFOs9aD9WsjWLpaLePYGMYe+fwCMgH1Uc9mF2+kXyADPXybJpjE1i2hUxrxK9wGhLOJL3rPI68LUhx89G4hIziBTdVx9orA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE0Njk3MTM0ODgsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmU3YWFiOTZiOTM0ZGU3N2M3OGEyMTIxZmVmMWIxNjFlNmU0ZjM2YjI5NGJlZTc4NmU1YTdjOTIyNWE1OGIifX19',
            'trail': '',
            'op': 'false',
            'speech': "Come to the dark side.",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-1",
                "/forcepush <playername>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_sword 1 20:2 16:100 name:&8L&0u&8ke_&0S&8ky&0w&8a&al&8ker's_&aLightsaber",
                "/shot give ". @plr ." forcelightning"                
            )
        )
