@plr = player()



@hero = associative_array(
            'name': '§eL§7u§eke §9C§7a§9ge',
            'class': 'lukecage',
            'sig': 'Noym/xJXWmf0rT5fE+QwDQd2E5tX7LNYXYTbo6aLTZnZL5Wj9/ayiZZ9luSlviz9iiyHddbDy9PZOE8bNJ94xEHpXmbkll3SxW7jbO90w1Ua5zeQ1vv5DoqigcGCQ8bCdY+bD0/sqa6ayZybyNUP728a3STvjNOXyoU8ZdgakwgCZjW+Fe1PdhigtunEcMYAs7FnjST3Pl+PJzpPmKgg4JR5uWJoOMo6xKBLwN0SlMm40sE9EFrfV8xN8hsLRB8/a7N+8BUFaUR2lvFg9bfegGpClRfQRIfaBUhanyi9nbDODqiSjqUGs+1h/bMLBQToIqyjkiRq5CrS0kqYU17nZXK1PFICHKEw1s6Q+lHvFe+bBIM8758Os6Sfc7WIiYTLzIMyWJBh7X+zOPJjXi+vQuqtjC97oF41eNINcHUggBNG+PRgJ4yPcoSMWK8+BmZw+IHDaLRfcRNyEK8tYfZR5yoRPlRyCShJCGzFe6jgmgYQobISx/jxekD3uGYfkwbHuDsYPUmEFSYVJ9w+YZarWCKFms9p+BxcpAOl/C79ztCS9Fu98KQfBu1qRrOdkNpNhbbfbHCZXLLPkGCgpJ3M4zmfSO8XUmq5h0q6WeSauQz3uqiSxn9dia0pxBd7BJzoH68WpV01yeuVf39LaJYuFZe6S+m/FsziiyZ6o5giAE4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg2NDY0NTI3MjQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdjOWUyZWEyMWUxNTQ0MTNkNTQ4NmM2MWNlMGQ3NDdjMjU3NDdkNjUxZGI0NGUzNGFkMDEyNjdiYTdlMDcyIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Headin' out, boss.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-9"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 14 true"
            )
        )
