@plr = player()



@hero = associative_array(
            'name': '§eL§7u§eke §9C§7a§9ge',
            'class': 'lukecage',
            'sig': 'VEFQP6vn9gQ3+Jaz72bUQJ3DaZFJDANwBapvpwMxDYpaZ5mk5AuxeuVZ9jyCr80NheONbTdW1+sBrWSA0M1hCXDFZcMv6FbhTAbORhyywrl5syUfAq8GE4IkOyP1b+gFIeoR/K5k3U2C8JbClNCqf17Xpv24UkYMYRdVkq5pOoMGx6hQgHhqCd/9eu4q8X06VlyDAdZbrPBeU0XSClPOk4pKkmlz6QKEbdRf99+K3T5TUOefN3X1TEPc84vQ2hqY4rosAKOOHO1knwjx3WNBlkOiFwRHM0nV0nEXvx97MLMMRyAiPfn/bbxkRdZb5fZidW45rQ9h+4rz3tmzSsSBp9YYkMJZDx30wQNcmrWvx/BjL+WDP+hzIQ38SGdkD6L4wTaXtj8cai39zf8+zvkYs8jwMDc8odm2i1WXLPI5uXDmRT7DTRFyj4+RjuZ0LqrmBtFqtwbswBs6SPGtiIPZ4Qfdd319wIeKbcJH3WruXbv9Mab25HgaNY6h+gbhy1d0EQuiPSjxIASweW/GhsOJbqLM1x1ZJDm19FcscLk/ayqjHNjAb/TefE3LeSLxX+4d717gcGwoScjO0DaZWx6FNOpt5FeH5UOrK9ZhpLznloZy2h/ujHFgjZ2rlPBilOd8ybUmnZ1phBWqHJWjqKjAHGsq0DNsGzeUl4e7bz/6qek=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODAyOTYwODU4OTEsInByb2ZpbGVJZCI6IjI3NWFhNTQxMTg5NzQ1YzRiYWRiNzk1NTNmNjU0NTE5IiwicHJvZmlsZU5hbWUiOiJmbGFtaW5nd2FycmlvcjEwIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hOWY4NDFiNmFmMTY1NmI4YTUyNGQzNDZiNjgzNjZjZDdmYTZiOTJhODZkMTNmYzk1MmM0MTRiNDcyYWY2NTYifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am Luke Cage!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-7",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"
            )
        )
