@plr = player()


@hero = associative_array(
            'name': '§8L§0u§8ke §0S§8ky§0w§8a§al§8ker',
            'class': 'lukeskywalker',
            'sig': 'urA9AMhMyjX7u7+yDlTUYoOKxcevE9I6eDJmxImCfeADFSpLVBgEFAIWKANZZyDCQlLqFDmu3iNOFSGlLj/hyCvVyCl+c2cvxv2hRpFaymn+8Htw/5POUnnc4j8470+obXKwjAoKo0BEl25HzK1JNQGpdWN0orLGk0t6jHgIxlZ8hKv8sl5RRgcF0EbyaUyFo2Q3JgnI7it2/Ni+aYW0vu2GXB4DpIRbgnRHnso05GqIZKpS7HexUiOk5eoHZBDgYTtxJCg7ybYv/gFrHCKDIskHpJxhjaCtOrYp0a2YFh5iteM0EHTeXPwHjdvoDbgAScDpIa6qejNZI+1EasujrrHQmNL826CDz399cqHKlHyKpkAbxj1bfiSZHpfY4afCzAmj43tiR26r72pbRKdSPnFKHWvz92AZS4ULgezgPn6AkDWa+fZqu2vsvkp3CkWPiW0MZXhdW5XIyiOcIcdR2uWCvzxVtemEYHizNT4AeXOxvmpr0PI8zSVC5gHpFOffZet3ZXHg9yhTnaWCF1Owb67TYx8dRXUhpFEHTDt12SwhOUDMyO40AMbzUj+oLZWzpCM3LshXlru7PW9GunW6oytMnK3zuJ8Inw8juGTyKfwAKNYWbUpVqtLs8uXYqV2EGQ1ly1glbhDqXCCpzv8fjWtTAEwWd9v3vxDXx5WQ/RU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE0MDQyMTE1OTEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJSb2JvQ29kZSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmU3YWFiOTZiOTM0ZGU3N2M3OGEyMTIxZmVmMWIxNjFlNmU0ZjM2YjI5NGJlZTc4NmU1YTdjOTIyNWE1OGIifX19',
            'trail': '',
            'op': 'false',
            'speech': "Im a new hope.",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-1",
                "/forcepush <playername>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_sword 1 20:2 16:100 name:&8L&0u&8ke_&0S&8ky&0w&8a&al&8ker's_&aLightsaber"               
            )
        )
