@plr = player()



@hero = associative_array(
            'name': '§eI§fro§en §fFi§es§ft',
            'class': 'lukecage',
            'sig': 'XEu3Gst1IT1B/Or9x/6OG2BapMiwFE4yelDi0W8iIQQRG8uWr814TdpIvSWenpFBKHBC1zKrX3MB73RVL00QgTUWlF1H/H0rTpAxZ1x65d9Wcs1alzd454pprFxNd6GR8vlwUXm64M+Us5M4xZVbnfwj6yLtLs329mOzjbmYbzmplYUto2tQduSHd633uach/p2naBvkSA5aOToomOgSkQGFVL9MNCJLIs2kLPNehRN25cNsnWEPiZAsSg52HiqAxFG0zIdVzy2DMJ7UsNw1UEoj2pIJKd4lDGi3h0hSWcMi8RVdFrG2L8aI6HC/cRNkoq/38oatQg8Dag5yaoI6EB6lOo7AAPoOorMmpiYxK8C3dQPlKzXdp8Lg1ASpn0k7jrspKFsSY2ZAelfqAUsrTQyoPAK5NhbJhuckiVzqep063oGqVbPnauN5a/bIgXoiPlcQzGdZhG4rIo+ENkxRuPxbbbKC3tDtyaZ2hx2O8vrT/4A0hI9e/p0BSDi7QN4GedILn43UOii94UOpDy0ncId3c6qZxkOyZquZVRuoCEljspkJdhi8NjKscl98Lh9BegJyqBR5O/hMH60JN3dEAcBxbLqZ0khX+pYC12EETc7ucexqCPeViC0ZkitN9I2uc/SWV6XZWOh46sfKgPf/7oE029w5Xv724LjJEt+Ga6A=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg2NjM3NDYxMTYsInByb2ZpbGVJZCI6ImM0NmQ3YjQ2NjhjMDQ1Zjg4ZmE2YjNkZWY0NjgyNzAzIiwicHJvZmlsZU5hbWUiOiJMZW80UmVhbCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTBmYjljNGE2NzRjYjJjNzI0NjZhYWQ0YWU0MWFjNzdmMjg5MGY5ZTg3NGExNjcwMjdmNWI2M2ZkZGJkNjAifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am the LukeCage!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-7"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"
            )
        )
