if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§5M§0a§5c§7e §7W§5i§0n§7d§5u',
            'class': 'macewindu',
            'sig': 'cYOa8jhPpNkdFdNV0q81PWOETyJvjzEHueV5U5n8Ckz7mo2wzGbkQutBr3rlvDaLkHAdcbvSZxwWupQQVkmyeuNKCdZd9E2Z7MXkPqdVO2BC2drS3LednXJJvwwkSV1SK1VQpNKvchn6qxwKv7z+sLZEFfJk2hEJayUNQ5F8p38zNhSQHNhUqQkr4Sbm/KzeISxAttD1/NcqtMylj5u6akiuJMNIrpym7vqwAmgFjjv4ydGQzoBZHHMa/jHHX+CVSvp2LmHkKTM1p/g2mA14uDSG4Hle+Xb7L5lUSYNFLrDAVglUm4P72lnFLrHw1+IP8w9i8/lqzHZIH0ZB8mC7ejkAI4QDekPx4xDagPA4Kw2JFWj1Rhc4QLflBhhO2Nd6sgNhSp5Q8pyAbTu6hwgRRurslQR+XZEICa/65O2zjs8HtUQSm3sK/mdx829Dfjok5EcpsVItVchNVLu/8n0/Xdu2chDhjFxjH5GxRb5q2hm0Y27sqY5S9oVkjlhF2ROb0C6Pw1sqL3qWAKlA36QYNSh6nq+dyRK/c4pfLEfsdI+imqNS9rNFeicABC5jViNOnk8jIYrFwK8KJs5yXCqyQgGIV/BL/5UNt85ia8tV7rXsL14PRoNptDishmyO7KGiZBORoDeM5GzEWseXXXVm2rs8dJiizeXthPre1XBwrM4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDc0NzEzMDg5NjgsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJIZXlJdHpUb255Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kOTZmZWQyMjQ3ZGE0MjQyMjhmZmEwZDUzNTgxOWY1N2IyNTZhYzk4NGQ2YWQxYTVkNmVhMWVjZDMxZGM1In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "May the force be with you.",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_sword 1 20:2 16:100 name:&5M&0a&5c&7e_&7W&5i&0n&7d&5u&7's_&5Lightsaber"               
            )
        )
