@plr = player()
 
 
 @hero = associative_array(
             'name': '§1M§4a§1d§4a§1r§1a',
             'class': 'madara',
             'sig': 'iyvp/hyULqeFcQRFr2KM1ndyUP8jwz6RthfNinlJPjoDsA7NcRm+X71z4GxNHGjvKiDu5fNPOA9prhRy8W7PXjBtYn71RsOaDqoTlNJRlxVcYem8tHOxg60OMszVcCOXLCCw2XB+N7D73vBPpysJMDukT5uTIVrZabwxhLz8L5zp1BIHaHJb84Ux412DIbelHeRL5ol7GJmi1w0tZweMGG/D9xIRchO6R9YzmpRI9nGJ6u89NDBQnrfC2EZAzz6P192h7b8jXwlcfOEnAU30zteaxb/zV/+MP8BMTippRW1PMTu2GeDAu/Lp3mdtpeAMew1ohxWR6M5rgOC5iRpu6gvnDPdaBF2FUOCGjagF15VSf5sS0cKqMr0jQpBc1apRSeXqB9WzhCHO91wkWOz/xXHHosa9YO2ni8jTAqyzROAEnVmdyyj+KVk7ajVHGJ8mPG6cY1ThNDA0R4HrnL/rQEqlvOwvVuC8e3Kj8sLv1eCLx2jh24VwOuUIV2+6GMhL0VVKwkb2VwwChPe3Cn8csPbXQhvVjMLtA7RYiAOcNGQ595PRQIB9gpOEUp31Ob1Fhtp85kkoG0kHhl6zHxJ9Id/pi38g0/rRAC48g+UD+7/18GMeVX7jW2YMw8umq27FPsTpXTNAkL5mkVPV/tAAuDyJs+v9Qhlp25VcXMMbCHU=',
             'val': 'eyJ0aW1lc3RhbXAiOjE1MDkzMjI1NDE3NzQsInByb2ZpbGVJZCI6IjRiZDIyNTQyZmM0MDQyZGViOTRjMjAzOWI0MjYyNTliIiwicHJvZmlsZU5hbWUiOiJzdGFybG9yZDIwMTYiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdjZWY0MWUxNWE0ZmMzOWRjYThjOWY1YTgwZWI5ZmIyNjNhNWFmNTlmZWU1NGJjNGViZDVkNjYxMzI1OWUzMCJ9fX0=',
             'trail': '',
             'op': 'false',
             'speech':"I will make a new world of only peace.",
             'powers': array(
                 "/buff",
                 "/jump 0-6",
                 "/run 0-8", 
                 "/haste 0-7",
                 "/mindcontrol <playername>",
                 "/stopmindcontrol"
                 
              ),
              'buffs': array(
                  "/effect ". @plr ." 5 9999 18 true", 
                  "/give ". @plr ." minecraft:diamond_sword 1 19:18 16:129 name:&1M&4a&1d&4a&1r&1a&4'&1s_&1S&4u&1s&4a&1n&4o&1o_&4S&1w&4o&1r&4d",
                  "/give " @plr ." minecraft:diamond_helmet 1 34:3 5:3 0:4 4:4 1:4 3:4 name:&1M&4a&1d&4a&1r&1a&4'&1s_&1S&4u&1s&4a&1n&4o&1o_&4H&1e&4a&1d"
                  "/give " @plr ." minecraft:diamond_chestplate 1 34:3 0:4 4:4 1:4 3:4 name:&1M&4a&1d&4a&1r&1a&4'&1s_&1S&4u&1s&4a&1n&4o&1o_&4C&1h&4e&4s&1t"
                  "/give " @plr ." minecraft:diamond_leggings 1 34:3 0:4 4:4 1:4 3:4 name:&1M&4a&1d&4a&1r&1a&4'&1s_&1S&4u&1s&4a&1n&4o&1o_&4L&1e&4g&1s"                  
                  "/give " @plr ." minecraft:diamond_boots 1 34:3 0:4 4:4 1:4 3:4 2:4 9:2 &1M&4a&1d&4a&1r&1a&4'&1s_&1S&4u&1s&4a&1n&4o&1o_&4F&1e&4e&1t"
                  "/effect ". @plr ." 10 9999 4 true",
                  "/effect ". @plr ." 21 9999 9 true"
              )
         )
