@plr = player()
 
 
 @hero = associative_array(
             'name': '§1M§4a§1d§4a§1r§1a',
             'class': 'madara',
             'sig': 'iyvp/hyULqeFcQRFr2KM1ndyUP8jwz6RthfNinlJPjoDsA7NcRm+X71z4GxNHGjvKiDu5fNPOA9prhRy8W7PXjBtYn71RsOaDqoTlNJRlxVcYem8tHOxg60OMszVcCOXLCCw2XB+N7D73vBPpysJMDukT5uTIVrZabwxhLz8L5zp1BIHaHJb84Ux412DIbelHeRL5ol7GJmi1w0tZweMGG/D9xIRchO6R9YzmpRI9nGJ6u89NDBQnrfC2EZAzz6P192h7b8jXwlcfOEnAU30zteaxb/zV/+MP8BMTippRW1PMTu2GeDAu/Lp3mdtpeAMew1ohxWR6M5rgOC5iRpu6gvnDPdaBF2FUOCGjagF15VSf5sS0cKqMr0jQpBc1apRSeXqB9WzhCHO91wkWOz/xXHHosa9YO2ni8jTAqyzROAEnVmdyyj+KVk7ajVHGJ8mPG6cY1ThNDA0R4HrnL/rQEqlvOwvVuC8e3Kj8sLv1eCLx2jh24VwOuUIV2+6GMhL0VVKwkb2VwwChPe3Cn8csPbXQhvVjMLtA7RYiAOcNGQ595PRQIB9gpOEUp31Ob1Fhtp85kkoG0kHhl6zHxJ9Id/pi38g0/rRAC48g+UD+7/18GMeVX7jW2YMw8umq27FPsTpXTNAkL5mkVPV/tAAuDyJs+v9Qhlp25VcXMMbCHU=',
             'val': 'eyJ0aW1lc3RhbXAiOjE1MDkzMjI1NDE3NzQsInByb2ZpbGVJZCI6IjRiZDIyNTQyZmM0MDQyZGViOTRjMjAzOWI0MjYyNTliIiwicHJvZmlsZU5hbWUiOiJzdGFybG9yZDIwMTYiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdjZWY0MWUxNWE0ZmMzOWRjYThjOWY1YTgwZWI5ZmIyNjNhNWFmNTlmZWU1NGJjNGViZDVkNjYxMzI1OWUzMCJ9fX0=',
             'trail': '',
             'op': 'false',
             'speech':"I will make a new world of only peace.",
             'powers': array(
                 "/buff",
                 "/jump 0-2",
                 "/run 0-2", 
                 "/haste 0-2"
              ),
              'buffs': array(
                  "/effect ". @plr ." 5 9999 5 true", 
                  "/give ". @plr ." minecraft:diamond_hoe 1 16:10 name:&1M&4a&1d&4a&1r&1a&4s_&1D&4e&1a&4t&1h_&4S&1i&4c&1k&4l&1e"
              )
         )
