@plr = player()

@hero = associative_array(
            'name': '§4M§5a§4g§5n§4e§5t§4o',
            'class': 'magneto',
            'sig': 'uK6yrjF6fTCe/AWAI9Vnmh0U0ng2RewCb9OA9g+SQITHYkew4/wpO/Frvtb1sWnszBEAfHrXrl/vXtV3pTwOzzMN3YB7M34Qo2Z/KS9TassekOoAGGZTaJDK4JpOCdOOGnemJI1YI8X5Eh4ROPdR6DyvfnuK4MfMgJr/I8sCX1tReyv1JvuPVkeprsdGUSUmETdHLYL31fvOM/Zp97FkCiTB3AuKMawZWCE4s/dGBN+qqI6Iw8Qw+lhzT4OGssBUXET5gZ9eVV0HzPbko6P+R9kNYY9e1PRZVI4ZkkkCo13x5Sos8iic4Ei2D7rmDqg16dM9jYP/sHH/+n2kUavR6NieyRgb5dgYDSiQvgJR+F1iWsZ312ThnwVydgVFp+S/tBd4OjXJmGNFWtNAg2SU6XsRw5lQ9MZKwhihgp/MND9B4tRT/Iz2O83Qz5Iq92xRlBUHNdA4aJVA1Ndxo4RFn3w7bnTPzZgcG2xpxwS7Gg7MqvucDbqfRPd3hxckC5zsZGiR+Ju9zAi+gGe05Sn0uCxDHCbRnRyDqFnGAW18EXpSdRfJouN8NTm8LxB7V84EJrWjJU2UzdzDJgC7Vb4pXfIEZRpDtZiryI5zk56/C5i3U/En9sbsbASRbbCihhM2b7QS3uhlf/8s/w7TPYiazwlgZZ0PpENDZo82RBmrweo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjgzNzYxNDk4ODQsInByb2ZpbGVJZCI6IjAxMzAyOTlhNDQ4OTQyOWRiNGViNjg2NDNhNGM2YWM4IiwicHJvZmlsZU5hbWUiOiJHT1RlYW1MZW9HTyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTU2OTk5ZWFkYTliODgzYTkyOWZhZDdmMmU5NDcxZDQ1OGQ4OWM3ZmRjYjg0OTVjZmZhY2RlNjliMzYxZSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Well let's just say I'm Frankenstein's monster...",
            'powers': array(
                "/buff",
                "/ma (this is his iron attack!)",
                "/jump 0-1",
                "/run 0-1",
                "/haste 0-1",
                "/iron",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 4 true"                
            )
        )
