@plr = player()


@hero = associative_array(
            'name': '§5M§2a§8l',
            'class': 'mal',
            'sig': 'Ywo1y4dlC7Le3HdoOwCdBGtKYyJidNjWj6uSbJNcxqaGYJ4tJeD0OA9UhBRtqIqcdcXeFDAJltVAf/9Mx80BIvLE0/xy6RuvcQXjafsDmOBpaDL7nU79Hcf5mivnBGxyyVb1GHeBMra6VJnVckiKpqy2u69S8E6a14Hv5iT+CGTzuUOBVekZrer2g10aCWyYOkeoXR7/Th7Vyp7ODusQqSmePpUjxFd3IY69VEXOytMpUGvWJLkDdmsYnIT2NP5FNsCzWBNIf0ei9DsYaJAzmIEBgNs48dhdFTi/+XtYjbk+eEjJWEnkqWf/AQiPWlxgB2fW+CQNIK5Uw1i6kMcoW72YjWwkkrTn1SgzEpf7QHDGyG5Go6P6vI9nIaz9XwcJ81uhRGmyQyjbmgnGcvbhKBltRStfQY5k1JhCZw2ey5iPd7YvUCIcxSR/G+DetLMLDYZdLhKGjd/wy8uoZUDjkgDKpWR/+stDbPvPi+1Wu41XROPNUN52YEFEDjwrSXnqTySVHMsuISeK4sfz5/san7QTQojNefkzRgrNPDl8gpc6XtKUUZ/llsKo6d9//bpW8H8tyZO5VgkOvlXFJw/58UHkdHdZjk34kK7awAC/PhLlCBfWd4hYN76yiJmOWRn4RMvy/Dw25Unae2KUP3YBn5anxYs7Xycx2CI0cGo901Q=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTM3OTE4OTA4MzIsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJUaGVfUmVkX0NhbmFyeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjBjZDYzYzdhZTQ4NzNkMzQ4ODVhNmRkZDRmYTY3MmM2ODczNjEwNmMzOGRhM2Q4YmU5ZTViNGQ3YzcifX19',
            'trail': '',
            'op': 'false',
            'speech': "I'm rotten to the core!",
            'powers': array(
                "/buff"
                "/jump 0-3",
                "/run 0-4",
                "/haste 0-68,
                "/flyspeed <number>",
                "/fly",
                "/disguise",
                "/speak <player> <message>",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/invis",
                "/vis",
                "/confuse <player>",
                "/disguiseviewself",
                "/undisguise",
                "/cast time"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:book 1 name:&5M&2a&8l&5's_&5S&2p&5e&8l&2l_&5B&2o&0o&5k",
                "/shot give ". @plr ." magicblast",
                /effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"
            )
        )
