@plr = player()


@hero = associative_array(
            'name': '§l§0Ma§4ndra§0kk',
            'class': 'Mandrakk',
            'sig': 'Ag8ZZkm0ZErlBJUlVOq0xqq0v8XxBiBjKho5XqTmArWq0J83cqbmjwvNJQCcKjyVCJz7+ULm2m234OINi2lD9S2K8szgXCCETvFmFpVhv9kaVS2xDktq/98QARJsAvYHwLYEDVM97ynTASjqWOsFJbD0MILWfXhhJVLPeIcND/Sce8yHhVOpYSwj+F9WHB3mOZtYmyzRvczN60IHBMC7XouhM27puhyd7E00xE/f2ywGLvX1s6PQJSvRSi0un8hqyh58tPhARE1J2IHU1+TrquKuPjg614egN0irB0nmVkVQ9MI0FYo9Edqpx51mrvD6Ry2GBEzlTjeyBSHduFmn/J+vP0UByUHJtNqLeuTA3UdIJ2C2a6AmL3CUtNdPfLANooyDW2jqPE/LDmdursl7F9lykoTvUSCg+EarxBS0RCFp+k08a0PPnsbMQjrCVqPQCrjtY7X0RWnNscK8ADwMZ6DFNuIN5uZR17uDpTTFjHYLnHiQKjZ1JYrTDFigQj+m2wTPbB5DDV213/BVoxZDU4DH0BPwR7iySJ8tp9Yj3Svw6zKKhwWr6CdSJ49aXrYK66UP5/xvlcHM8x1GjO1I3j7TF4NEQk8jFWU/yH+BrFl2OUCzsWldIwkzYg0mRwcYMlDx8ZzWX7S/h6AmmwHZtlGDwSvYBj05pYaD9euWJa0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODM3NDE0NTk0MzQsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmJmNDU1N2FkNDc3MjdlNTRhMmZhNjQ4MjQ1ZmU1MWQ5ZmM1N2E4Y2RkMjA0NGZhNmNiZmEwZDA3NTk2MTMifX19',
            'trail': '',
            'op': 'false',
            'speech': "I will consume everything!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-9",
                "/run 0-9",
                "/back",
                "/tppos <x> <y> <z>",
                "/tp",
                "Access to all warps",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 25 true",
                "/effect ". @plr ." 11 9999 5 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." energybeam",
                "/shot give ". @plr ." dimensionalbeam" 
            )
        )
