@plr = player()


@hero = associative_array(
            'name': '§cMandrakk',
            'class': 'mandrakk',
            'sig': 'GZcPjMZbE2z/8yhBLJ2TspHuq2HRpiUPIdzbu6GU9/g/LheGs0RkHEHmNhOZahQwYgTR+JipBoG1IwZCqMG4TAu1GcV2ZyqgaOBAfrBMc5s4LgtCYSIPp6gC5hhfSEHGFvl+mbEjHBS475XNZJXRybCQ7t8wCoZy/QmgguAf9qVaUDLZ6bkJpwuMGKgQXvLtG4ZMrZML0XkCvOLHXv0fNH6ffdR6FLLXQ0FSdpGiWStCsEbfsBT3GNY2PhQHKL4oymUCkpUqnq5XigxrCBO38FLo1OMUEOZO2qx6QT3eBvGkn04fKscPUw8Y89xiglPsH3PxD4cLx7/E7nUi9H9iUQlQIqQBbFl7rc50sh49gKM5VwgzM3n+D4GQw/ACgPGw7weVSucm8l61yXD2eQ3uAxgGLTmIo5PozaagNs55xRV8m3VE+xCX7SGuawxleOdR4cM6v/4PATIR6u8/J0jT4gMB6V4kguzsqU1CpxrlOcvqR3mtHLpaBOMw+ZV+BIqOQKkGVfPlPRqSTwALWxPIuJyejIYordfVb94VtBulQfkPtXvhDlqq4Rw323lRzhbi/2M1eGEy4Nl6rIi+UsQTJxXEHD4rboHafr0fekOBWoPzafLJQeTmM+mHy0lT91nWPRxKWsIm0Pd6yvbfSRd8fjnYxvAWJKEOY9xWd7+ijGk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE2MzY5Njg4MTEsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjIxZTM5M2M5N2Q5YTk2Mzc0OWZiMDQzMzlkZDY2NzFhNTJiYWExYzViOGM2NGRhNWE1YzlhMjExNDIxOTYifX19',
            'trail': '',
            'op': 'true',
            'speech': "I am Mandrakk the Dark Monitor!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/fly", 
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 254 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true"
            )
        )
