@plr = player()


@hero = associative_array(
            'name': '§6M§4a§6ndr§4a§6kk',
            'class': 'mandrakk',
            'sig': 'kWp9/ouTUu2kpdH/IdC2XaYsyhdxpI+F23wBJzJrmhGNnpuADnAk3DfYs/Nd2O1QKP/mNd0dgCvp9kNXGMdX1LMVi4jrt8/whJR9/HaJUF6IBq2KOZ31CAeKIm9L8rUrXxjjaDHg7Os15SAeOz6VOOD+jM/vq3rTHoKGRM5D0GIScno+dX4UuDO84s0fxBJ6Ap7E1Sb16C+xQUkFGeZTijYZKomyyDB2/fIONyK7lGhEwq2hM5SDEVjYhd7W+gsLHxaGnD99/njmZBvkOg6Yb1HjarZiFbmkFU+s5iN/pjp2HbV9hJO4ZTbwhY5lYPrh3Mooet8aTlhYK+VIapRnJx/U4hqLGsLcp/Db9H0XRA8l+7/JsvB73LWX76BSr47uEydUNDw/VbyXK7Uep5LsjsZcTw3mMl363U7ZJoHQVASfOSc3NI4VBTKMbz4lf8BYgjQshmsJhgeBphBZjku0/kBiO7YiEvOMNJ5emTLQ7StB1jS94q9jwn+1fMDVIKmGq5x0EWXVs+SMBp4IwtolkWagK/3jGuOLOImCy3vmmxnxbxaC2fq3QBOF44YiNNG9e6N7DGhHcsny87DJ7fF7MQDjmK2TPOd9N6hJg6cVYk+8SHkaI0h83vY39wf8luREgPv5bp4sDJxhthAo/ZKC4zxvvXcF1raUOibvTjLcjuM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk1MzA3ODU5ODMsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJHb2RfRG9lc250X0V4aXN0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xZTRlZjk5ZTZiMzUwMjc0NTNjNDRmZTFlZTIxN2RjZGNhMDVhY2FmMDcyMDFlYjQ0NjcxNzE4OTUwMTE2NyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I will consume everything!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-9",
                "/run 0-9",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 254 true",
                "/effect ". @plr ." 11 9999 5 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." energybeam",
                "/shot give ". @plr ." dimensionalbeam" 
            )
        )
