@plr = player()



@hero = associative_array(
            'name': '§3M§fa§6u§9i',
            'class': 'maui',
            'sig': 'Bp2Q3CSUcg+Xng7hcYMQZSV+2w8C4OIL1rCpREslMhJMfK5SorOI5f/M+3r/ZlOsrJcHEJYXtr3o5biZ4zaWgN7OUgCsbNBI7/jYeNsKAQGd3qew9Cj80eP9ULtsPgMAdg9MgYwPg4XpWK/4T9iYaGYr7BfiKqr3DCzLrpaJvKtiHzubN9XZw7ncJPMtVLoI5RjokS6pf/t9XxyEpfHcqYvlBJY6DNKtwN+AvsxRhcIRVAzQod3HugKKaKyjPNq0ktVg7/U6KJM19xlO1CHupGVCJHup00Z7+zUUDa4jG7CR8jyl2Fg7n98I4PynxReoeYGji4iURYfxKphndZJz1vunn3Y0+qVAZ7923ZsIcXjT0Gi/YsZdFvKjZY6SS2Z790c7pFyYlRp8ONoIqrPUv+Z9ulA1qUut2ZYv4JcdqSJzWfFDDVGCm2zcMKWyINbaP7E1FPIghGOHZq8dM/D4gk4tSHIIGPwVLKNzAt7gbAasHu20bfZipnWISaOjiWPpsISQfw9k6qHc7CrQShmu+zSM6vVyJboJxYAV7t1kN0eEfdljdxjvvgMtWXPidZIMjm5zzL+ZU6RS5zbTCMuCYReFoGxliZNcLxlUFjQg5uPw+FIvtXtAeM40otD6MGrl3/klbZ44MW9/e3uWcb1a86DXrEyDXHRDQmhWnm03gxY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE5NTA1MTM5OTcsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJhZGFtYmFzaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2Q4Mjg3Zjk0NmM5YmU5NDhhYjQ1ZTRkNTM1OTNkNmM4ZTcxOGUwZjJjYmU5N2M2NDA4NGQ4MjdjNzc1NDUifX19',
            'trail': '',
            'op': 'false',
            'speech': "Maui, Demigod of the Wind and Sea! ",
            'powers': array(
                "/buff",
                "/fly",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-2",
                "/jump 0-9",
                "/haste 0-9",
                "/disguise",
                "/disguiseviewself"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:fishing_rod 1 16:15 name:&3Maui's_&1Fishing_&4Rod"
            )
        )
          
