@plr = player()


@hero = associative_array(
            'name': '§fMax §9Steel',
            'class': 'maxsteel',
            'sig': 'EwKyyRF3etCTEvxg76Mz1vuPt07mlfSR/hDrGyWKvnepqQegzxvdFeh5RfhCBigkR6O/XNcHT24L1cpTA8FWuZMfY3FFNEfxjG6vZ+69/Go5KiACJc75pXvejOPIcTXL8JtPN38aAGMjGQPqzYC6pKowVPTYLZC0lI/YjJGlCthBQdo/KObZrMFnHQmk6Bba6smKNGAyRFMQqrkV2jlXLlMDlrYnDpNspeoUm2ouZqeOt7k2nvWV58J+zzV4LMG6+JiupLUKEsGqcbvtUBOfxiWuaaTLMf0hkTcQjPJ2RoETklBiA6n9VbCZonxpm5kCB8Tkd7w1LG9M1ggyTbKuS5gp4j7pa6kLj6TtkBrdBp4YvWW3KjnY/CSdgI45BECLsSXlYKRgxlQZnVNOzbV8se7snI5UbFlyP6XBPz4RrjKWhW2U1UDlKliIGammtOjfOsRNkXBUi7iKjokow3J0oXr+fH5KigoIWzTXRCIdP3J28WCE0JbpnYT5QaWUqv4d+KExb3HvlB4K/ztOrPkM8EltcYXkD+hhUYhd4kyPl6SzJMQ/sm8wunO70JjabNK6SIz6cyJ0HondfkYAWzzzgxvtE+rKYWbIypcyGDMlFxkNQAvbQ9riwIrZLM7OM+8irKbDfqpouwmPF0P9nTYMsP1qs/0s13wTw13LS89+5dk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTY5OTM1NTk2NDAsInByb2ZpbGVJZCI6IjkwYjJiYTZkNDNlNjRlNWM4Zjc3OTEyNmI2OTY5YTljIiwicHJvZmlsZU5hbWUiOiJXaW5nQXJtb3IiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2M1ZDJkZWU4ODQ5NDQ4YmYwNTdiOWE2ZDg0ZTBiOGFmNDBiY2I4NmI2YWZjNjg3YTQxZGU1NWY4OWIxZjcxIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Go Turbo?!?",
            'powers': array(
                "/buff",
                "/invis",
                "/vis",
                "/run <0-8>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:2 4:2 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts",
                 "/shot give ". @plr ." blueenergybeam"
            )
)
