@plr = player()



@hero = associative_array(
            'name': '§2M§6e§8r§aa',
            'class': 'mera',
            'sig': 'bNesDaPyN0JLDIy6129UoQVEAbVDnZxByfOFSBt0vGczdNByFD4WMZqdaaBfh2eFdEhKiv9in4BAQWrUlccXcZ8RuYW0yY/U7I8yflsMhVs3GUOnz6/Stu7ve9wmOYA1+MEyMI/2FVkCUDueXheHzuVgydEv6rYacZ6qMJcI5QbnLHERlMG+1dN62gkr5SiSgZ+MDUOw7VXslT9wGPzhBGj/mO8JrEZugW5KHb24TWDK7wEKFIwpzI22nO4o6lBCxwoTA9Mu6i90si9rBVnnPn12d8ExZ4dFLUrkK0SACOTC7wtpBSJMeNBXBkkzBH0kBTJ0Xok/jmdcwmY5xoScfS9LYesgTkyKfFw8Y3Ekx3jdc4egNJmzEywq9eCDF0OBI14ntRPYYg675RIZddOsNcgLp2M1i5BExOv7UXvGYFDt4xCeBJCJumghjv7GvCmHcyk1F2a4M0xTb3PXRWAQqK5Ewow5rFrvEBlCDkTsuGuDohVIPxqJEsno0sMY0JHt7scBu5dDkoeRfcfFQftIG1TyZKEoWQ/ac63odszacgECvzHNK07PsKoUdkWtCcVWvX/skuJQZ5u9tocx6mZW4VUhGoHusg142+oImLAo9I2qcMcLFVxFHdqWRBwLxU7OajIACLTXXW4lZzpbsBRtlcW5qKXOT80TVhy3ucGRtKE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDYyOTQ0Nzc0NjEsInByb2ZpbGVJZCI6ImM4Yjg4MTMxNTJkNDRhZjA5NTkzZGRjZGIzZDU2MDU4IiwicHJvZmlsZU5hbWUiOiJfSXRzTWVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzEzMTUzZmUyNDc5M2QyNTQ1MjIyZTMxZjcxN2IxNTQyMjFhZTUxOWY4YmFiNzhhNGY1ODk4MWQ5NGYzYmU2In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "The absence of water is not my weakness. It's all of yours.",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-1",
                "/cast waterspear",
                "OctopusForm: Left click a water source and then hold sneak",
                "Surge: Tap sneak at a water source and click in a direction to fire a surge of water",
                "WaterBubble: Hold sneak when in range of water to push the water back",
                "WaterSpout: Left click to activate a spout beneath you and hold spacebar to go higher. If you wish to go lower, simply hold sneak. To disable this ability, left click once again.",
                "WaterManipulation: Tap sneak on a water source and left click to send a water manipulationto the point that you clicked. Additionally, you can left click again to the point that you clicked."
                "Torrent: Left click at a water source and hold sneak to form the torrent."
            
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/shot give ". @plr ." watershot",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts" 
            )
        )
