@plr = player()


@hero = associative_array(
            'name': '§fM§ee§0r§fc§6y',
            'class': 'mercy',
            'sig': 'u1EdbDFMSBR59HpgLJE5I5hOaHkUv9iBv6frlIPKoo7ZT48twFYOnlB9thIFovWyg15lxGoRjiTR2jgPARdcXuFcMvMRy7TWzXCcEl0mUxsZbiJiYgMtMqVcJzbpxMUfZnryjWy/FX3EcY5VdtTJk8pI7jZyntv9si3Ie1AP9Ww8YBzg6Z3/34Hvt56DfC6KReyQPUrQw6Q1BkHl0fH/mqTFfjADfqFdAMdhPVocynscD96JaaX6yk90Fut3I5FcGQivjxUP/FhNNr89B9Wa2FGceGHnQBRdW7JV6wjowA+ftfGH/rUW41FRNvE5MA51YAmBJHzxW1KwAAxiLh1aOmRHjdH5xJCnjebchdlFgX++17lKSF07wPzxdDhnu0sTf4lYMNvnVyfMShBgUwiA27CF78PFezLlUxVZwhxzF+py5N1h7oiYwJCyQs0nWEbmlUic2E2isOizxbyhW+7HQe2GEJl1cMMC5kjrs+zdAF1hoTwdkZt2cQkKEhCPmBbgCRA3vjf1T7AGxJbjiV757fyZEFj50Hql7Xg0x3yslK77Q7DthLW8jzb+kNa1nmVzK+sh7BTFnQg9K2RuyIV3ZT4kUbuw93b5/YMZvD1WYfo/lNEPQyZ5S7tim24pYtJODzJFgngKXRAx0iRN/bz4FPyPES36QHv++HDk7yeKQsY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTQ4NTkzMDAyMDcsInByb2ZpbGVJZCI6ImE4ZTE1OWVhZGVlYjRmNzNhMjQ2NTkxYjU4OWFkY2Y0IiwicHJvZmlsZU5hbWUiOiJNckZsYW1lWVQiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81MjUwZGZhN2I5MzM5NTVlMjUyNmJjMTk2MWFhYjc5ZmIwYzFhZjY2ZjU0YTQyM2FjNDJlZjYyNmM1NTA5MWRkIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Heroes never die!",
            'powers': array(
                "/buff"
           ),
            'buffs': array(
                "/effect ". @plr ." 10 9999 2 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." mercyhealingwand",
                "/shot give ". @plr ." mercybuffingwand"
            )
        )
