@plr = player()


@hero = associative_array(
            'name': '§fM§ee§0r§fc§6y',
            'class': 'mercy',
            'sig': 'gm2Cd0mJwTMieykMYHdn7WDTX2d7BmoL+d3dGhCjAin/YZVDxXSZwYW7ws27k+xhmW7tx+Bee4mc2y9xvH7LPqdgs7Z/HlHFSmXJz9qgL5ykjPr6OUIkQ7DE2UDprccRUroOtXQSjNGXowwlXY/9a0rY+yXKhATE7T2Avzd4ezTFw7jikqUvSS+EK15QZFQnsILJr2Qhaf7+AUrBYKsWmAM/3cHKzxsBRJ/a3DHIuLhU6lfpz3FKDuuIFSiVjvnee4Jk77SokqNffhQoIgbV3B1YxOeSonGYQTaIZOLlPJEot1+629KJ5CtNb5SOmALy0MsYcKe6/tVUGiQP9ka72Teb6OFkiapDeYBmiKyIheP3m1JOsRLjajMScOUgGmR9KCkBX/vDwIP3ZbpyhLpNtda/24W0s5ItVMhWPvYSIfGEU4D4oZ6dHVs9cUHa8YeZ+E1nbwn31YdhwvS2y6s66ar5AKSQeRAMTrYCSdEaxzrjTmRVCSX7C8ZLKn/W+UVopxXmOBBi9CdqsMUHlhJB3783WmCxogNGlDvqbYJFj0spWupyXW/a/bI1DTBbMPSIEjizgFfsDlXxHazMY45MM0uKm0klym7nRmUSNOk3BOG6WAlOQI3+u/o2TEacXFscDofH+gvzUh5sWfhx2Z3+1FoFlIaXcdDTVphH1WIK6Sw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTY4NDAxNDc3OTAsInByb2ZpbGVJZCI6IjhjYjc5Y2QzMWU0ODQwODc5MTM3YTM3ZTE2NGYxNDk0IiwicHJvZmlsZU5hbWUiOiJNcXliZUl0ekJsdWVfIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zMGExMTdjNmZmMzhlODU1YzRiNjVjYTgxZmJmZmJjYWRjNjc0YmVkMDRkNDlhY2RlOTEzMzE3ODU1OGNiZTMifX19',
            'trail': '',
            'op': 'false',
            'speech': "Heroes Never Die!",
            'powers': array(
                "/buff",
                "/fly"
           ),
            'buffs': array(
                "/effect ". @plr ." 10 9999 2 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." mercyhealingwand",
                "/shot give ". @plr ." mercybuffingwand"
            )
        )
