@plr = player()



@hero = associative_array(
            'id': '152',
            'name': '§dMew',
            'class': 'mew',
            'sig': 'cQbEtt0p38EEFmyN/GFujhLB2D+0E6fea8PI5AzpKV/gVTVUKkGlK0c2CxWZxZKICaBQPN7IBVVyZHfPiLomVGpSuia2oVQgCkZXwYIDEnsNiMb+myuIlNroXeGfLrDT1JNTVvz4K7cTs0X5B0ye5L7IumRxUhDtqfif7H8KgxM1q8WpPsd8PBT34fWlyFM+//XXiBpMh6hFYew8ubUGmtAuolsIKcmyczXpJEH6traQUKjtW0vWP4Zy/efLNEEh8bPVWTswDl10Akn2FBc7TM5F5GU8p8EajqQYZ7+uZKPsdd7AqDC/Qfl3kRQ4sSXOrqGWK1fytw9y/eTzigVeGPbVq8aZAg1vks3KlhhuICiksZ/mhhLmyw1SwXBXFQFk18HbtZmX1wNWQEKOINX/pNdwJ422SSWYdwkyh5O5Zj/ga4yP8VW508782cHG+VkzEzXWGyyrYg67z8DJlVNHAKaHa5/QB98lL6nNiBsykbJpODIrWFBr6AU5ay9wa8XWqlVGeD+k8WO5LEZU8rYv7VUclMAsxwV0J5zacQ7l+WwllBkdK41Qb5rBaZdqcprsOJI0hpHeM8KTKaEnt6GOOdT0jeWhwCFO6fLad2sA8fHdKUASiwzcl/pXW1bPud1q1jf8qHTnbQdor7imrEQ/V/BvsIs/LjbSqW5b/N4vZ64=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg2MTkzODgzNDEsInByb2ZpbGVJZCI6IjRiZDYyYzJlNTZlMzRmZjQ4NDNmNGFmNTFlZGI4MzM5IiwicHJvZmlsZU5hbWUiOiJ0ZWFtR0JOaXNiZXRzIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zYTgzNGY5ZjU1YjRmOTIyM2Q1YjU2ZTYyZGI1ZGJlOTU0ZmY2YjA5MGJkNWQ2NjY0ZmJhZjdhMTdjMTg1YWQifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am the protector!",
            'powers': array(
                "/buff",
                "/flyspeed <number>",
                "/fly",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/tp",
                "/speak <playername>",
                "/jump 0-2",
                "/run 0-2",
                "/confuse <player>",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 4 true"               
            )
        )
