@plr = player()



@hero = associative_array(
            'name': '§fM§de§fwt§dw§fo',
            'class': 'mewtwo',
            'sig': 'nVc8zmGETj3kIGXQx3EojM6e1wc87NcvPGRS3ndx3xT1U7AAFt9wR5oQxcPogIzj1DenwEgEK81wfeVuPWEwFIcZFaGYnHogSq3lxcu1pKuXjTI8sg1P9cYx1y2Nkt8qK1f6A8H78ICcTQseox9DrFXn+WA4qNiGDZaT6FZ4bX7zae2NN9rsfyC4S+Dklq0KrAkUDh+Yzl1YoIUNL8Mes+fQ7aTm5zM9coBVKCIUr1DnHpyplIKGW7IGcyNXzd7JQkuY1w/Q5/3zhyFlm6Ua4XBl8IFqIJ2pdw13+4c5+yOLHxBeQWo85QgRJxFkZNv2ypPxsNOwskBHKWM25Iav+4uL+L/1cgSmevmRIUxzVKcVoGG22AmcQmv6cZRG4DJCChONYr0LDCjitaRSiUJYNNxSNayahY+BYZmX2jydIa74zbwqwYBbTtQ06Q3C4bhEFcG/4QowRPB8nXhklP5wtanYaNqEcVxcPA0A6Lq+VN2Pe7hblwRGQleJbAOuMAdEN2/fMCPyqiNeBhfn+/WoYnfXP1k9AEKWuNC2KD1+RPnvTkrCsPi0XaRVLEHf9vWVCA3Cg1Rwv0mEBmxW4viu+9rDenpKXvrEVCpIMi4Nd1XWFXwIGE1dOmiA8uSZMMOiaSP1+H6mBm0i2ju3HNh9ddbUPBY3vRPrG8VFEihArYE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg2MTEzODU1MzMsInByb2ZpbGVJZCI6IjRiZDYyYzJlNTZlMzRmZjQ4NDNmNGFmNTFlZGI4MzM5IiwicHJvZmlsZU5hbWUiOiJ0ZWFtR0JOaXNiZXRzIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kNmJiMmQ0NjQzNTk4MmZkNWZlYzExNmRiMjQ5ZmVkNGRjMThjZDE0NDQ2NmRiZDZkYmQ5OTU5NzRjZTYxOCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am the ALL POWERFUL!",
            'powers': array(
                "/buff",
                "/flyspeed <number>",
                "/fly",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/tp",
                "/speak <playername>",
                "/jump 0-2",
                "/run 0-2",
                "/confuse <player>",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true"              
            )
        )
