@plr = player()



@hero = associative_array(
            'name': '§2m§fi§7k§fa§2s§fa §7a§fc§2k§fe§7r§fm§2a§fn',
            'class': 'mikasa ackerman',
            'sig': 'jXPN9r14NucZOGzfg54uweSvbr+UwJwCtChBbqufk/uwS6pMraTYsUJTotBx+XAyON4pVddqPDdkhxPV2qQO4P8LG9/DmfcendfVR3SPEJyRESrKBVpWUAb3aWoaTyvf7L9o7UTV4ccMNjChYUYCuJMPQtEwEg5NA/NXPF4yd9bFNkr64tzdIabysPCI6ETSk/DuQkKcGx3O6gsnLIMF4PHFRZgIGgj81BqfkR/k+Nn00NsFwMqFKYiex+WTRo9vrqStNb3B5nfiRBf4UNxJFqIfuTqjwS3qZKMXzKGQKLebW37xuczF9jBsrpvViEm3MmYjgB/FpJUCP30IFKC8UCzJx4WGqyLdHqbebIZ8zkHpo1ZYFaPMJObKK4WTiwskcDw4v1BFHd1SGWClaph991Ol1pJM/z+2qCia9vFeu698R2ZWYFJVMpX/8CPqYUWCCYD6F6YtSgC9fG/GO+5cEtydYl3ZW1M3zXBCvHEWFvBi+0DdXIio+BhP1+gbsrkGuMXihoeygdWCvqqAIGa4tfTm2Vks+Fx/PKmUTA4t3b8nmaZuq699R52iL5lJNPehK44nczFaM2nzTMBaXDlWzCqmsKHoBsh4qRHufZ5LPRa9lhbwV69cSRQqt6XnV7HssSVJrjmHnXo1X1FgU84ilVz/O8TlUUCuSaqhOxHQ0LQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTQ4NDQ3NTA4NTksInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYV9SZWFwZXIiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzgzYzlkMjQ4NGEyMzM2MTg0MTIzYjY0MjJmNTc3MTU3OWY5YjcxZTJhYTI2ZGE0MTVkMzdlOWIxZmMyMSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "This world is merciless, and it's also very beautiful.",
            'powers': array(
                "/buff",
                "With an empty hand, right click the air and you will use your 3D maneuver gear. You can use it to swing around the city! Note: technically, you're sitting on an invisible chicken (lol), so if you wonder why you can't move it's because you have to press crouch button to get off the chicken first xD"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:§73D_maneuver_blade",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:§73D_maneuver_blade"
            )
        )
