@plr = player()


@hero = associative_array(
            'name': '§0M§8i§7k§0a§7b§8o§0s§8h§0i',
            'class': 'mikaboshi',
            'sig': 'MG0oPw6DaIuh2lFx2tonwv+5iZ7pY5A9HGBEYs1HrQQWrzgXoRabK+05SLOvXAQX0aM8VM29/GVc8YuQUjyIyJsaAHy+gqm8t/WmfldB/YQ4Asvu5na50Mt8zvzClBcBnUlcUI4aQt6vE/fJoOojyI2WoLZMubw8YhbwsXVJufNx1ZI6ffC1Jedrkr2DbSd9Qa6kmUF/VWKw1tfMhRw6AFU+mla5vK0qUWGy7Jv+h4QX9ZRMlg3FUyW4VbHy9HpWkALOK9jCXHwQae30ra0LSlOeIeDSnreyyQJROoLezAvav9aMjVZdNOvwifnKCq5zn10ihL7EOGTE7mCFevGsGqbxt5DW8qZoXQ2W+yG31kjPxN1jjqOph9C8nReNtgM6e5Dia2L6PRMihSmvpl2gnAEs7G4KDsdIP/qY7AWw3uLdStB+HRrsQQYSQ4VnoRA60VIu0+fp18pSh6fI2l03RI4vtbrN3LG0zBUtveiu8sgWyvdbBENGIja/Ayh0puPGTNJ7KTbtqdQMv9tauyp71M5JVazKSNU7YZXZLmOs8dg2H81zpU3v43ajE1LUXFL/g+WxvOPPFbTWbk7MYVhtaP36Rokh18z71A03qXKJM8O24I/swltx2ZNCc6VhRr5pu8ng4ZroTYIFa98vxEGrFTbRHfz9iBnOYLMqAz3JcMU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTY1NTM4MjI5NzYsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJ4TXF0aHkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzgyOGIxN2MyMmQzNjI4OGRiNDAxOGNiZGI5OTRhNGExOGU0OTgyOGQwZTNlM2JlOTVlYjViODhhZGQxYjQwIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I am the Chaos King!",
            'powers': array(
                "/buff",
                "/confuse <player>",
                "/grow",
                "/normalform",
                "/destroyworld",
                "/tp"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/give ". @plr ." minecraft:iron_bars 1 16:10 name:&0Finger_&8Spikes"               
            )
)
