@plr = player()




@hero = associative_array(
            'id': '2',
            'name': '§2M§fi§2ss M§4a§2rt§9i§2an',
            'class': 'missmartian',
            'sig': 'h1kqg/lT0LYScsEvNSzx1BbP9UP/uoVXsWmEapug+Dygeu/j5hYx8Y4VAY9dI6WxtMfpZzPsHHwLiCqfWEyNS3jP+kmcQZCTai9qfsp+taJdFJzLlaPQEP2QyEw2n/3tI5uNSA9oPs3jW1kFrR4LZ7Fj08ihNmHXDB6VKQ8UrhqLanbGX2ZKDeuxaPO3tvVjjGRhcfft9SIuA4nHUYYjrwHla3U1MfFztAbJskWOLDb5H1DOJ/65dfzwcC2Ai0dXM4tc7uSh7N2inf+81/+SxyvGjtLUmw9FIV1YGSyneMAsTjPLo9yQXSQFkau/mvi4dEgJtjqABzhLNm10Vn9sEGcn2MaN8uNh9az+CGgT7ecaV1JEwPIPgDXPxUz2cReu9jEPgEKGWg5e/CAvLbcigRy2PkqpSFBijSfOHvFfXEbCFOvYMGGcikb2h4hhK3Sku9MpE36BqwNH4hrxXrjs6MRFLp/KQQC3LP9krWFOYHmL0/8YWZlWclUxMGBrCnbN4lKwnHSy7BvTpLzxvvI9se9GjM/beJInDXb8WmHVzBB9ZdF+wex4q7z23EQCVmQ74cFIUYaUuPqzeyHfbf1MtBYo1qEvy1lYcox4FG4vziPUG4HIuWOPWDpe385tNqYt2yaLO6KHa0sZNKc4Tee+8W0qQHBcvBNimiuQHiWs4G4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY3MzIwMTI2MjcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xNzViYmUyNDI3Y2YxYWRhNjNkYTc4Yjc4ZmI1NGI1ZWEzY2RkM2Y1MTNkMzgxNmI4ZGQ2YmRjMmNhZGQ1ZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Miss Martain is here to save the day!",
            'powers': array(
                "/buff",
                "/jump 0-8",
                "/run 0-7",
                "/haste 0-6",
                "/fly",
                "/thru (intangible)",
                "/disguise",
                "/speak <player> <message>",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/invis",
                "/vis",
                "/disguiseviewself",
                "/undisguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." energybeam"                
            )
        )