@plr = player()


@hero = associative_array(
            'name': '§4Mi§9s§es§4M§4a§9rv§eel§0(§4K§9K§0)',
            'class': 'missmarvelkamalakhan',
            'sig': 'ttkvgAA0dVt8s1hDoQZiY9UrcFiqMSoSS4wGlxqPWSerbgLoCmManHpR9w0ktctPZGM9qn00X0GB01VJSsyG/m9nd9EEEl95AOqRwYwtB6Abjq9n44aBAZTfa+EkLTo0r1GfnmRJONxtGlenJjeq8oaHQap+FrENe8ZFkIJVsE8zOwna8D/ZygQKJZUzrAVlmXcNSzhGrah4AzazC6PclleituGyGW7yqgoKH/YFdC5TQCh+RQa0zPaVxGQA2jHizjDs+gVNnRjhDDFbm5ulavhmCnXZZktkT7NveCZ71PR6gQj5YqKBEr2u3ujL7LTPGJohWIS4uUYG1OHAXgHaRQJETm5yF//k+Ctg2n7Bmv0hKmdVQhaFtk5hFrg4RUCqqgkSxvWxqr66lK+dAptyhi73E9koYs0LHUg8ypV38eTvdINFjViV8rDiHcq2Pwpngzrdb8jdojb3Ag3an0wqGZmeDANGPOZ0hgs0lgu2ygayrhfbLnwd+O1KElTz5jxAyE5iKsXOwXTiut2iYUyCzTBcqluty4fWR+/mj6igadwRRMY8lvr9wPc6TJzVL0PYj+qqvdhQRyM0bIDkkSvWgEI3dJa18xZQ0dwunztE57s0yZc1+kBHTAeG2FWE2n3qLJVOoyTM1Ds1LAXQRJ8b+lY6puMYBdI+9nNmXr5GWQY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTM1Nzc2ODk2NjksInByb2ZpbGVJZCI6ImE4ZTE1OWVhZGVlYjRmNzNhMjQ2NTkxYjU4OWFkY2Y0IiwicHJvZmlsZU5hbWUiOiJNckZsYW1lWVQiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iNDNlNjdiN2ZkMWQ4MmE1MmI5NWFjOTQ5MTI0MWRiZThhYjMxYTNiMDM3ZmNiZjY4YzcxNmM4ZWY4OTIifX19',
            'trail': '',
            'op': 'false',
            'speech': "EMBIGGEN!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-1",
                "/cast embiggenpunch",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:fishing_rod 1 34:10 name:&1Ar&0m_&1St&&4A&9r&em&0_&4Str&9et&ech0re&1tch",
                "/give ". @plr ." minecraft:elytra 1 34:10 name:&Glide"
            )
)
