@plr = player()




@hero = associative_array(
            'name': '§2M§fi§2ss M§4a§2rt§9i§2an',
            'class': 'missmartian',
            'sig': 'vm1KGjEp08kyyCR+HweV1BIZ0em2KE0wG9pCOqnvVbAyDzH9InYPClFJbGj2FhZz/lq2G7PyaoPuaDnjw8qo3vSsgi8/Vvy0Q4PpunaSzfYU0ki5W2rmT1h9bNMapboY8pVEchJzqzEuwUyo1Sq0uiV58dIevmYDj1zfdSU1+pRxQslsU6l+KO7gtaee289L4/EQPDQFNTZ2+wqG6ZC0c0jb73tkzyLvAxMn+T2IR2hJyFpe0jI1quXmm+OLu2wRIwUDY/7m+vg88qIXb9YkzFI5EAtEVdZXHYUPbdyQk6iABIyFOgC80jdl14xuj9YBnKfmquNhsAQNwCP+aw9rhsBWECVP+kmDrvXk4NnNnL+Vo8hKkJIvHLbpO6FoA80wDt76ydUFjadrAMgL80qBRJg2HXZhJ9VU/ly5yo3zZcFSW6glppb4FY4uCnAkRv2D5jsHSIPkZoBFCQB9yWuOSWv/1rx8jmb0iSAjo6b314qbvr+mnus/lpqGOIQSY/KtCaye8Md/SpBByXThyV1gHyNpbRIN9HPVPyfkKVW1qrHbck3P1kvmqtIJ0ozeMzww1h2ZubuHku4oVX56RvsV1zcIU0PEJwvkQtZbJBmbfxTAM4keVNdeqR7LmN1sTpeVRQwQWJptQoWd5avooLD7eGbH2uKNPZ4yvYqkLbejZT8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODc4OTExNzM2NDIsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJTdWFubmFpaSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQwZGQyNDJmN2VhODgxMzk4NTJkM2I5ZTAzYzYzM2U2Nzg2OGM1YjM1ZjJiN2I4MThmZjU4NTNiNDUzOTA2YyJ9fX0=',
            'altskins': array(
            array(
            'sig':'cCRZbcj9Vjmcr/Vg15K+/XWfd65Nveqv6BhyjptBRO3X4AmXvfoLcZmWYbMojMXyCUtSaOY8iqypCQE+of/QB3oGo5cpQtLsQQ+/kEDrKJSIUXC2giy7kfi2bP03OXr8uJjJcunkigKsBp3tUzkQpNZcwKw5dfS7lzest4aH6e/e5JqhtuaAOxXjT9j17YfZ7yyuJrk9lSdajsiRL3pG1VWDCMpUcJ2rBLpdFJJC4MOJhFtlCB5n1UlhI4abjf4DNS4o5R6Jy3nK+9JL+tRWuJLisD5XtycIjoAm3wt7ZPUKHaZ/byCukRnlGP9a/j+86joxoB2FD6Ku0yvse5aUTgUNR8WYqWiLbMeanhmToHhL1j5u0dDA/26yBhmwzxlDhQzBwP1hkHF5w8qcXzJicu50/VkHfh3tVJ1o4njDdG9jmWBD+/v4hTP0Gth/VmTyuKLlEJHjgDggp84AkOrceDWVoJTB8EYMd5uuCvYy6SfL7IA1uL5/iEtDp5duBgd6BPI/FQqsds3quvYNm9yeQYBGAKFuRl9kdjlfNAKJXjGmdNC0Dv9+29HueuFZ7w0Y37SNjmMPGxS6XQAN7ORVy8MTKyU1AHalerpwaP2YgPfRHM7QTIdMOq8jgY6HXRWv7mwMVvC6KouE5vbczy25pkmfMo3x/Vs/X+/O2do0I6w=',
            'val':'eyJ0aW1lc3RhbXAiOjE0OTUzMzA4OTc2MjcsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJYX0Zvb2RNZWF0SGFya19YIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzE0ZGExYjM1NmY4ZWY2MjYzNDJlOWNiNzI0ZGM0ZWU1ZjdmYThmNTJmODRjMmI0ZjEwYzNhNzU1NGU2MTMzIn19fQ=='
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "Miss Martain is here to save the day!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-7",
                "/haste 0-6",
                "/flyspeed <number>",
                "/fly",
                "/intangible",
                "/tangible",
                "/disguise",
                "/speak <player> <message>",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/invis",
                "/vis",
                "/confuse <player>",
                "/disguiseviewself",
                "/undisguise",
                "/mindlock <playername>",
                "/msg <playername>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." energybeam"                
            )
        )
