@plr = player()


@hero = associative_array(
            'name': '§7M§foo§7n §7K§fni§7g§fh§7t',
            'class': 'moonknight',
            'sig': 'vLK5MRvDy5Gr0QpkD/elgoby4TPtNP6Xgypnt2JvwFPM2mAYPMb+aT8c40i47VAZYzJgNsj+aaux7uErCoCyuNBe1rR/utIo7FPGy2f+E/kptjuPFu0sdP2IvbsnFuJhjcSl2CaaZB/wNeKPv+Zvetv2BWBbGcbE+E6D+z+xIB9gFuf+MEdGi/Cse1EerZcl5KSu3lwpJZSgncryw+Qrp3Ss3GGrTH6/4UvNCdcU10YEPtXak0DBJaJwo2zr7307w9FiTS/vbE4O+Hlwp/6kVWaMGOILPwo7+dGr8byyuTWx94f3mG/pwlvfDDzEBqlqzl8hor5Ceqhx6lbQxumlMRPA9StBq4wcsXyNdO/EnbwCmNe+I54+Nd5DKq58LeyoFInxxT4AWEv4r/6I2eGT0k+i3esLsS/NEBtEcKg7dORBAgnBwMTVd5Jonl9lIJ4Ji2WOQytx6UkARbWYIlbfDrmy58pfZDAX7CpKbXvT7qhxgzK2Q8JsujEXV9Ym+EPYcMUB7jJ7bs4OKy1UwhcPpzZwF3kSmPyu3/MhyEjY5eXZ6zZO0aTWgTY5GJCMxjtbOGbdUw48wME84B+/zp42ixZz3p6fiZ/hMJN6bNrOgJGf5yDEIuSHPYTqWdfwOHNVSjy8BFgaEFHPe76T0G37Jke/49KwJxJonWjMWLfzVZE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDk3NDg3NTY4ODgsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmMyZTJjNTcxNTY2YmIzNDQ0MzY4MWY1YjU5NGFhNWIxMjY0ZWFhNmQxN2JkMDdmZDFmY2Y3M2UzZThlN2ZmNCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "May the moon guide me!",
            'powers': array(
                "/buff",
                "/cast crescentthrow"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:stick 1 16:10 name:&7M&foo&7n_&7St&faf&7f",
                "/give ". @plr ." minecraft:elytra 1 16:10 name:&7M&foo&7n_&7Gl&fid&7e" 
            )
)
