@plr = player()


@hero = associative_array(
            'name': '§fM§7o§fs§7q§fu§7i§ft§7o§fg§7i§fr§7l',
            'class': 'mosquitogirl',
            'sig': 'k8rP5yXpfmzSewSahWqUuabKGgv/ENCprqnV6O1NaLUYwSuZZhzALyXBfIkB/4WzaET7vKIv46Nh3z9pdd+OFYCf5dR8c0hbM/yJNZnoiIQ5RmWFqB4BfNm6DDlOOpkN/mk8qmoMukFeXFbIUuxVTyVOcPNngvDwEdh7wWYF8hoTGUPzaAgkSbazIhCbczptYuBljfIAqKwXG37KziPRsBIezfjfvG5+oFN+npwx/xz86I6Oa3V62yGpdgn1byIpcLpYnceArlEFOJLdaIbD+M83YhbeFFbPGvcjq3xGudnc5blr2zoaiM1Txx3HRG0DPhcnnHL/bSYgaPbXfFzaV0fQj56G7t5QDoBc10V8xGZ7p8IwJTYS+UOlscpQKITsuoHDbJbHCS+Xyn/9W3QhmYSG1Nvv/w0nKgYl8eL5CNRSsLWPx+MVQi+mTp6ui1eiPJZtUI5WPKQ5WcxXyY3+P08j2Y5JBTSvCpxx6K4nuJrIykipuCS3NeBi3/aTCeNA7Hfyij/dXmEZq/oviBpiT5msKzqKz4BTLNQXv5PUyi2uveRzDiewvgRoKYMtIInjmVr1CqaZNcpGiNqXpNgKOT/kMeU3vIwEHSfcQijrsGkIjo3xwofaHy29InxOBBvPP9FyM/RTnkypBqdBJFe9ckyNIWT63SDuXO65uBtoAsk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTA3NjMxOTUzNjQsInByb2ZpbGVJZCI6ImQzOWRkYzUyNWZkYjQ4NGU4ZTBjZjUzOGU3OTgyYmVlIiwicHJvZmlsZU5hbWUiOiJFeWVtYWtpZCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzY1YWIzMDFiNjRjNDE0ZjYzNjE0ZTAyM2ZiZGI1ZTk2NDE5Y2U5NTRlZWQxYzhiZDBiYTE3YmM5YWFjZTQifX19',
            'trail': '',
            'op': 'false',
            'speech': "All my little ones, come to me right now...inject the hot, sticky juices in your bellies into me!",
            'powers': array(
                "/buff",
                "/swarm <playername>",
                "/bloodregen",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 14 true"           
            )
        )
