@plr = player()


@hero = associative_array(
            'name': '§1M§Cr§7.§CS§1h§ci§ff§ct§1y',
            'class': 'mr.shifty'
            'sig': 'q0yGrJ5kjvi2GM/8D+JPQvowBkVP0mZnYPHmToMZZ0Or+McoFNiRhWtgYbcjefThjXIlBKzk3JWa2ISbSzcFW2DZjbIjsPzXuOPrMTIi5ZN+BmyvwkR9O0lEoi2uJxdXBgY0ImLevnOvlNtGc+6jb5pgIh+8LzPdRJqsSH1lE8Px8kxUkfvuF8j+j/2WMMfBHK4IjOymmYIugqMziulwWc82zar+SDmJWNWhmGBcRDudLeG1Bd5nieNelzDrzcm3+T2dRTXmF257SHJKQvv6A/Q2NoQSS3FWQxCQ0dr6VLfYXtRaFJyP800MesqT325VmvYufpAXoLfdnc59/30BHJDPUbCgSl5QLe8zhYzHM9BQ0g+4EKPCC3EYPtvd8D5iT9CHxXYjWPlSZ6HR+wqkmrUeshCbwVke1HCgmsD87kgmRyljdAEkhgkPa3WoMwBqoNbUDFDeYE1UrR5floDTBjj3Ng4Am1mXsYxeNPgVhouOF6CTaT6Ol8lvIWQCvNAOAOv/T79FIY6Gq1d/ZQn6ma+QXj9VqWa8iAU8yv5JrH0aPtN3X67Z13kReE43g2b59Mj4jOTVBShfdVZFP8XYZmbBZVp9wNKMtXkpRNSsE1url6HA7AiJpVHcedAjxYPPcQ7MIMbFCr7IsIJgulQEEl5Ao4MoM/pn3EC1t5Iy8gM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODc0NDM2Mzc5ODIsInByb2ZpbGVJZCI6ImJkNmY2MjIyMGI3NTQ2OTg4YzgzZmExY2EyYWZiMmU5IiwicHJvZmlsZU5hbWUiOiJDaDFja2VuIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81YTVhNmZiYjdjZGQ5ZmZjZWY4NjllMTRiNGNjMzM3ZjM0M2ZhY2UyNzY2Njg1ODQ4NTk5NzA2MTRlMCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Time to get Shwifty!"
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3,
                "/haste 0-5",
                "/pt jump (use on stick)",
                "/jump",
                "/thru"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 7 true",
                "/give ". @plr ." minecraft:stick 1 name:&1M&Cr&7.&CS&1h&ci&ff&ct&1y&7'&cs_&1S&ct&1i&cc&1k"                
            )
        )
@hero = associative_array(
            'name': '§7B§ea§0t§7m§8a§7n',
            'class': 'batman',
            'sig': 'SR15FEYOESBW570M+IKHpRjykgMd3ATxyh4S55Up0OUobbFPyhlZqh0i6lPm11Gba9v0+B8JT/dPeNxDQuaKgLJoA8jEFVeSdmN4hnd4X//1To1LrQV6LNehxQKHk0cs3l9DSsWR20iBgwN+oKD6Ylie8PnDF7nzXVbNsE1ZcV16DyEyiFp75vXl/CYYVsLWaU6WQP3ghCzupGfMPHFgg5xBzmpO1JTARrh5+awjcpMv3jXc9XSRYTEgDKpMgyqQVrNBlAtZa0r+s7s6HBgYPz3we9S54J3JtpG+gsbt0axwFgCOXoF0fsojLI3VIBVDJKD0ORpZw9t4zG3PaU30P5o7wwirEAwRqVhQDmamBtCYqYARuuvOfQtz/zSIrhaUuqpau/IFu05pro/IKBQzh6Yc99ARjOoscQQR8e200f9NWRCnaMaLEAfE5u944BOILjW4A5SPijQLd5VRZCp2HzN7CLeM2P1RLcNQF3eb3G+7PZN0wiPwlATU36KDhbwjHj+r3/y2FU4KJLvC7ulNBXdfO3f2C7cj387fQwm1l/HgVwUvRLVr70YxNefwXFWh5xekCMv/M82Qjr97vbQ9LY5HCKCAb/HgDz8gU7mxOiCrYE1Oc6yfvA2Oq8+Vw6E7EuDZLfv+v0Us383sS6LYU3lvwtFOkrcsDtlUfHY4ypI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NDgyNTE1NDMsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzc3NjZkZmM1Mjk4ODRlODk3MzRkNDI0ODRmNDFjZmZlOGU4ZGQ2NDMxMzc1NTQ0MjQxNTg2ODdkY2VhNGFiOCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Your mind becomes razor sharp!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&7B&ea&0t&7m&8a&7n's_&8Glide_Wings",
                "/give ". @plr ." minecraft:ender_pearl 5 name:&7B&ea&0t&7m&8a&7n's_&8Grappling_Hook"                
            )
)
