if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§1M§fr §1F§fa§0n§1t§0a§1s§0t§fi§1c',
            'class': 'mrfantastic',
            'sig': 'w2kbIAs4S1S8xSwQgszgG8qJyBRWugXo0AYnGglGSUKsiDNSMEBx1MP3Qedib2rmddBCG88zqlNijLCyVSfZUUnMHDjV7/OuE8tVyg7+oAtN1PrX2C5udwX10b/JDzEI4N4IDnjCJgd2ONqQ3XY2FKNgBZKFntIQ+utNgV51cWva3v8u3xBXTjTxx4UZa27I5kAI3Qlbvd9bgqMf5rukaF3DqUlla9uI0kmB8X9E/a6lOR432yIK+GAef0blikKMf/vEiggcCMggk2/p4eHsOBvKQdgNyafgLA4ELsQtZmdfHB3P+sfofa7Iou5FKmA3Y8rv2Yot+4HrTu0Bt2+w2L7vVC+DaEOXB48DI6x/EGfW1vrrZ1FJNgMte9oxRWYIGfugKIu/EPp7jzXBfMTtX+BE8Rn3KP7mrakb3iLycR8qV8ymrzQG8mcBKBx94Ua8Y0W5E1uAXUvU6PV8IG/JUhqK+BWJFg1KXIKR2ldDyI+oOR7mGGBjCvaaQ4uQR0eQ5WQOUneKpBxaVVvTTtACnuhmphdNCBXyemKMjiWkxhGLdHMkGKeDC81spqB1ggGhxNoyLliXXwKc4m094T8zesxdASpblahrApcWRQqdDC3ouBnYewF0DYWAUj9HKScpEyj43goPVmfulG4JCMh/rox37DcN6b+sSNCp8y/gXNQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTE1NDYwNDA3ODUsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjJjN2RkMWVjMzVhNThkMGM5MzQ2ZTYyNjZlYTNiZjA4OWFiYjdmMTExODU5N2I2YzQ1OWM0N2FiNjc5YjAifX19',
            'trail': '',
            'op': 'false',
            'speech': "",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-1",
                "/cast longpunch",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:fishing_rod 1 34:10 name:&1Ar&0m_&1St&0re&1tch",
                "/give ". @plr ." minecraft:elytra 1 34:10 name:&1Glide"
            )
)
