@plr = player()



@hero = associative_array(
            'name': '§6M§5r§6. §5M§6x§5y§6z§5p§6t§5l§6k',
            'class': 'mrmxyzptlk',
            'sig': 'ODnHaJAB4DkgeHZR0sbr44VwA5QwAIo+23Ov0jiPiA/NM5xm92Q9svGXBCH4DjX4wNrWdOiv9usP1vz8Pp12+pq5E9XkLddg0dVyWH7wobRQlSp+MFYGCGBJc5WIy5TrFNrhoCrQ/mX2eo/s1MTuGqFtaQbFK0DmLaOLAKivR5M/FSqTxVGcRNIWGNEiDU+Dfd+ONOPaT6YRDnhUlvdjjBTl4o3lWXtDfPWGB0SICzQ3uXccxPKTGEf7ElURjGV8H6vKh/lnT3bKqPMh9uNZ+/lJy1+A2kW2Be8rg45YSaO8x48n8KoEXXnPqbHnbFdhjaxnfZ7xVgIEKDrHZF+TyjWh2FRpCM9qqgiG2I+H03VspY5tCocV+n9Je1LfqvzXh/88JHy2xmOAtuYy8Dndi23Kx5SVMm8hDV1RgRwnt1+Ble/Y5M910r9DwgIaPu4cVChHs2yD9g4kdScPMrw4mmLoBcqNZQYQ9Ak2V8PrMeYEN9FIdaYyZ3U4ChvoItbhN35GbWhfxtAhgWrs3pFnnP1B5W3T1rkYPkv8zQOWhltWFFJx3LUwaPLaubjAk0q8ueBB1ybeIiVveJWf22WLIpSNS3drEKxmq5PCXoCuomqlMgVpm87Gu7P481aElXwy71eaYcp8PhSekEsNSf0F1h1Sk/XBsEm992SHIB3qJhQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTE0NjUyMjY2NDUsInByb2ZpbGVJZCI6ImU2ZGU4Y2YwYWY0NTQ0ZTQ4ODJmZDk4NDQ2ZjRiMzFiIiwicHJvZmlsZU5hbWUiOiJScW5kb21QcXJzb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2ZjMWQ5MzVjNDBiODJmMzgxZmViMWJkOTMyNTc0OTdiMTJmNjM5NGJlOTIxMWE4OTg2MjE3MzllYTQ2ZSJ9fX0=',
            'trail': '',
            'op': 'true',
            'speech': "Let's play a game.",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-3",
                "/fly",
                "/magicmrmxyzptlksmortal <playername>",
                "/disguise",
                "/gmc ($1/sec)",
                "/gms",
                "/undisguise",
                "/disguiseviewself",
                "/empower <playername>",
                "/back",
                "/tppos <x> <y> <z>",
                "/tp",
                "Access to all warps"
           ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 13 9999 1 true"
            )
        )
