@plr = player()


@hero = associative_array(
            'name': '§1M§Cr§7. §CS§1h§ci§ff§ct§1y',
            'class': 'mrshifty',
            'sig': 'q0yGrJ5kjvi2GM/8D+JPQvowBkVP0mZnYPHmToMZZ0Or+McoFNiRhWtgYbcjefThjXIlBKzk3JWa2ISbSzcFW2DZjbIjsPzXuOPrMTIi5ZN+BmyvwkR9O0lEoi2uJxdXBgY0ImLevnOvlNtGc+6jb5pgIh+8LzPdRJqsSH1lE8Px8kxUkfvuF8j+j/2WMMfBHK4IjOymmYIugqMziulwWc82zar+SDmJWNWhmGBcRDudLeG1Bd5nieNelzDrzcm3+T2dRTXmF257SHJKQvv6A/Q2NoQSS3FWQxCQ0dr6VLfYXtRaFJyP800MesqT325VmvYufpAXoLfdnc59/30BHJDPUbCgSl5QLe8zhYzHM9BQ0g+4EKPCC3EYPtvd8D5iT9CHxXYjWPlSZ6HR+wqkmrUeshCbwVke1HCgmsD87kgmRyljdAEkhgkPa3WoMwBqoNbUDFDeYE1UrR5floDTBjj3Ng4Am1mXsYxeNPgVhouOF6CTaT6Ol8lvIWQCvNAOAOv/T79FIY6Gq1d/ZQn6ma+QXj9VqWa8iAU8yv5JrH0aPtN3X67Z13kReE43g2b59Mj4jOTVBShfdVZFP8XYZmbBZVp9wNKMtXkpRNSsE1url6HA7AiJpVHcedAjxYPPcQ7MIMbFCr7IsIJgulQEEl5Ao4MoM/pn3EC1t5Iy8gM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODc0NDM2Mzc5ODIsInByb2ZpbGVJZCI6ImJkNmY2MjIyMGI3NTQ2OTg4YzgzZmExY2EyYWZiMmU5IiwicHJvZmlsZU5hbWUiOiJDaDFja2VuIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81YTVhNmZiYjdjZGQ5ZmZjZWY4NjllMTRiNGNjMzM3ZjM0M2ZhY2UyNzY2Njg1ODQ4NTk5NzA2MTRlMCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Time to get Shwifty!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-5",
                "/thru",
                "/mrshiftytp"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/give ". @plr ." minecraft:stick 1 name:&1M&Cr&7. &CS&1h&ci&ff&ct&1y&7'&cs_&1S&ct&1i&cc&1k"                
            )
        )
