@plr = player()


@hero = associative_array(
            'name': '§cM§es§8. §eM§8a§crv§8e§el§8(CD)',
            'class': 'msmarvelcaroldanvers',
            'sig': 'ZYlLWh7jLz/8GYRbj/7HnL/guvyEwTBSEibpgHZzY4esc7uYfe133Jk02eC64Y5W/k/LBcCaW4v9YrIdHlZe3HqR+iC9zC28N3w1q3LrCp5ktY6KRNNwFhQyAp+cVesvwNFC39AIvrjwMTS4s+zXwR4frOLR3KR8adAa8GWWafSotUFdMdkCtwWtvPuaGIr+TmbzskOe76wHWq4hWuv+ZjBk7RsP3tKBk1UrukvWa8KcuZZtzI04NSKoGkygcAmcSYeSLUil/hOswtWzwuoAQ4isS9NHHTdLT34TV4f0nCTr01XZSGsmwJxhd7L54mnD9oR2IvOGyX1Oc5kOWiGawr4p3rjEFJNTwoo2bx4jrshI0E39uPhDx4CrxNNTlzFe2cKCkiLRq3qezPeApII0rjrK1iZTllGAD7BbEYmuilgHLba9n6j/Drg4M5liVNKqWlikQBgl7x8Me7TFmUHiLqSJ9kYeVEuogBl316NWZgulEFS4U3EBtLD50NSre35ip9Ahg/dictJiU5tWFLrFwWsvc46Fa3EH9Jrt97BOshlLi1KGBVXiWi3ejM3r/DTHt1i+8Nh1Ljkw1d8wZB9w/ZqJyLcZShrHqxc2LCdPqSQL2piI2v1hdrpaZd7WROk9opTlXXCz01hA9Gg1a2Y2USmwQQQU1XGBnm8QyvyPAXk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzMyMDU4MjY5NTYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mNzk4YTRjZTMzMjViMDJhY2Y1NWVhNDljNzgxZDViZDRjNjZiOGI2MmM2YmQwOGM4MWMyMTY3NmRmZDQzOGI3In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "MISS MARVEL, FUCK YOU SHAZAM YOU RUINED ME!",
            'powers': array(
                "/buff",
                "/flyspeed <number>",
                "/fly",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/carryplayer <playername>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." yellowlightning"                
            )
        )
