@plr = player()


@hero = associative_array(
            'name': '§1Mystique',
            'class': 'mystique',
            'sig': 'bHtBLMcSBW4wMHK1lUjFlZVyKvgD0riOnp1lAZNG/9QmTJfqnNibwjYiYwvrt9aIvRzoQ5+AHB4S04VWHOXamTnoukKz0UfmzcEMaj4qgEZnXwrJPjpUq0HG5FwTMIp4+DhPOwxDjgVfLmpB38AA/MO6LZuAcK2xnLqkoWb/xHjIQyGZMXb+v3UegMFxQrn0jbmxY9JNpnKRdqYGa2lo60+u1lFJrVrSCBJkzjH2kTbUFJunGiimTe06CPerFAG9IBQlzJvFSxMbHKGrJiYScfeSCOYgGcuPin7Q7MkhGNLGTCJmNMQLPiiBIfpx8aMg5NCPGNIMw+doeJyXnAiYNFVB+IunIC/z9mJoz/D9KNh/go76NzaZxepihzyOFucO9KwUG7bD3FnOTH7NP8j24/1+bQMNZe44T3PiL9/vmnZPzLje7lJRnF65DiWa+xTIpkzPy3OqQluYE6aw7L2E8ZUb4ju3KGnsQ0UUxRBJIUX8Tif96r41fjT4dadXVh8UK9CMM94E9i3Z6I03mGTM7hEUiGprTx4cqBLUgBAJ6nTfv8f5n133nQObw3ytdMzKf/PKABLZIbQyrLUJ7ncs669NQAKZqWtVznFPeVE9t33QivzdT7yslqI/dlGAHfOHfglFTQ2nrABXBMZtXDfPXwm820NU6kC6f68D70pi1m8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTg1NzI4NzcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kZThmOTI3YzQ2MmIyYTYxNDI3YjU3MmY1NDY2M2ZlOWE4MmRlNjE0YzIxMmNhNTI4OWFjNmM0YTJhYTE2OTcifX19',
            'trail': '',
            'op': 'false',
            'speech': "I can be anyone!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-2",
                "/disguise",
                "/disguiseviewself"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"                
            )
        )