@plr = player() 
 
 
 
 
 @hero = associative_array( 
             'name': '§2My§5st§eer§2i§5o', 
             'class': 'mysterio', 
             'sig': 'MGtfcrWVikZinFNi0Prc/1dNksrcwnmNSY+aptx0lKpNPkGRRc/VNqVY450seLTBLBlxNFvSa9AhTISVefXsMej9SzUpfM/CLgPaU9gNE6d/jNo18fFUUlKWGY2gu9fyz1/shdb//dSRNZXIhuFNuaJ6KIpfRPSyFrlSVCNNzCAguGRr2ey0FwCVO8jhqbMDglDCk/qKH7hvafJpHwTo932mVuF/UOgwS699aOkWrD0GMw7xrfP0O0seyGatt6JuTfQQ+0r9HlTzR3uEDvUsZWq0afmzREGOCw59ufu0MY+SylE/p807W4vInp9WBflXxv+IOpkuna5rV6A39w7hXxICAUFZO24FDsI/dNILoT1iCzYZt/lrU1mrLz0SRIvbtXoexdh65TGEq/ZkM8Ez2C6072iSu+1hgkHN/TtNzRsN6Nal2DqnKIoDCLx2c91AMU1OLbR9QF9j4Pc0C6ofl31avIlrTSFg/XPEYwcIGKe2Wd4WXO340FRO6lGjW/wxAEN83Q9aguxHZlJLNX/ABR351Vk0UV5G2+n9BTOqe1hyaaoPqDv+Z1g/8TIou4S97zZLExVHciMqwkES7QGhwDqD9+FS/P4Ag1a6OXw0vXMf0gIYPHOp1ACAA5awDRgLau/QTZRh3DvbxP1IVXVq5G3AGwCGngsOPEoZiV2LFZ4=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE0OTg5MzM1NTE0MzgsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzM3Y2UyZmUyNGU0NDg0YjIxNmQ5NTk4ZWExMGJhNjQzNWE5MjNkYzkyYjhlNDQ3ZjJhMDRjMzBhNmM0ZDM0MSJ9fX0=', 
             'trail': '', 
             'op': 'false', 
             'speech': "Behold my power!", 
             'powers': array( 
                 "/buff", 
                 "/tppos", 
                 "/run 0-2",
                 "/invis",
                 "/vis",
                 "/cast telekinisis",
                 "/disguise",
                 "/undisguise"
             ), 
             'buffs': array( 
                 "/effect ". @plr ." 11 9999 2 true", 
                 "/effect ". @plr ." 21 9999 9 true", 
                 "/shot give ". @plr ." phantomblast"                 
             ) 
         ) 
