@plr = player()



@hero = associative_array(
            'name': '§6Na§0r§6uto Ri§0ku§6do Se§0nn§6in M§0o§6de',
            'class': 'narutorikudosenninmode',
            'sig': 'QKX8pO7weJKYaoj9Mkgj7Oru9elGXa+gstJfmCdhTLQZf3klD5akYMZaXbK8M0A0S5Sq+02ShfhMHdUCf80BqEoJtmn5zorp4uYHGG61DF5pD9P9R7GCaLvQmKQiDZxcMulqtP9Do2toXhybPtYYSBSd2n6Xyub1+3VIeGgWbV2i2vQ6bXelu1gwZr2DcrNHwq7YLqkw7L/V1fIe3f5ga5jRioGNDOdX/nz9wn/lMBYVCmJKQpC9DQNnN4xErRJA0ZqQUKUBx0NazS3O6zOipTCbxKGYExFDYYBb1/k43tRkGG5mAZIlqX/iukP9wUHEoqS3lkJW9/JVw7xlN/OUqb/ay58f2bHXrVhbvBTuC6Mh2o5f+TtiWYGM97xoMKY7FfeQJjgv4YK701jQjpqNLrvXS/XorUqcfqkbJ36mGAQYMqZws2tLgbfJ8MUZ3DL4aViiFjnjGLimp8NPmapaRQdH1M9NCDMymZKJmQ10xkYQuv5XlzQ+qOMmvhU7XfdXoAWcboxpYMPrrLF23pc/1smryj+c9V32C/PgGEoP915hzHHBRvjTeiIMDNgc8C/BwSoCnz6NwmBqzD71nrfx6WdXppQ8npwOnFe+dcoFZhJyZxgKLJKvKK9jXSIFNGT+t1U7MEBY/6t198bXMSiuNZLZXBmChlQDzdGtXWsuVmc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDQzOTE0Mzk5NDEsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJUaGU4dGhIb2thZ2VUcmV5Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jNzcwYzE1OTIyM2ZkOTNmZmM4ODFjM2FmZTlmZWMyNTNlNmI5NGIzYjNmNjE0ZjBmNmFlNWU0ZGFmNmRhYmUifX19',
            'trail': '',
            'op': 'false',
            'speech': "Here I come! Get ready!",
            'powers': array(
                "/buff",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer",
                "/dismountplayer",
                "/rasengan (very powerful punches for 10 seconds)",
                "/jump 0-8",
                "/run 0-9",
                "/haste 0-8",
                "/msg <playername>",
                "/tailedbeastballrasengan",
                "/ultrabigballrasenshuriken"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 50 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true"
            )
        )
