@plr = player()



@hero = associative_array(
            'name': '§0N§4eg§6ati§0ve §4Fl§6as§0h',
            'class': 'negativeflash',
            'sig': 'gpmoDRgkti6Cm2ypY0TMyeRdrxMOdke+O5BYp8NQhuG3as3v592XwlF7LWL/fTsmftn/xqtabaPufjpLVjsk/ht7NRKqTBEDz9tLf1ONWfSy5jQWHpV4D7HxovlITHAhw01tRfe8kKGKUHhFGwpxngS3zyj3FItyaAZt/3zbIgtAi4FV/jhSVFeJ4VI2a11dMY9OfNalntFLHknEOutdvYFjwyPiohLJhh9JZtyvRkm5mFjxhOrhdTcme3NmiWKvgqbsP9R4/dlYwNhqkd2+0m4aRvsvTOYTpEQknJ3xhP794okZHYUY8IQ49ZYhXIut0p18+UGncaKipESGNhumjebyDlBhF8GiM6ejw67V2ZuqC2g9iDmM6+jCMaTWIFqa3me0EnNPexCjHrhTa1y5oUXuPViidsk6BcNpcecx1/4J+vsL1RnpDRIQXT9AzDbKt6unfWdK9aRBhglvZvYzytCAx+WvgZ2uJKBTPNF3AF6dN/hIoG+09rldOWotzGsancyQAOgsBVXEdRsQ0kymgrJvMGnU0BbwQnIiL9c2iny9sRvEqNPH3kYt777sp3mcQLYvN9PVbIzi8vYMHu0S/Usfnm72Tz7ybGkcmJjz6kmLuy/D4MAcB7Amg/qvDlmSb6yRxGOMapyzIKlMbLKf7cdO0dtx2Bk3c1Z6o3/9Vjw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDc2NjI4MjA2OTQsInByb2ZpbGVJZCI6ImQ3NzU3ZTAxY2YzZjQzMDU5NTkwYzY4ODIxNGJmZjc4IiwicHJvZmlsZU5hbWUiOiJtaW5lY3JhZnQ4ODIwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2M2NDllN2M2NzU3OTk1YmZiZGNjZjQ2NmJlNGEzZjAzNGI3NzU1NmYyMTZmZDU0Nzk3OWZlOGNiZjJlOTY2In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Now the negative speedforce streams trough me, I doubt if I can stay the hero, but I will stay the fastest man alive!",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/haste 0-4",
                "/wallrun <on/off>",
                "Look Up+Jump+Crouch to perform a wallrun.",
                "/tppos <x y z world>",
                "/wallrun <on/off>",
                "Look Up+Jump+Crouch to perform a wallrun.",
                "/modifyspeed <playername> <number>"
                ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 13 true",
                "/effect ". @plr ." 10 9999 5 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
)
