@plr = player()



@hero = associative_array(
            'name': '§0N§4eg§6ati§0ve §4Fl§6as§0h',
            'class': 'negativeflash',
            'sig': '"gpmoDRgkti6Cm2ypY0TMyeRdrxMOdke+O5BYp8NQhuG3as3v592XwlF7LWL/fTsmftn/xqtabaPufjpLVjsk/ht7NRKqTBEDz9tLf1ONWfSy5jQWHpV4D7HxovlITHAhw01tRfe8kKGKUHhFGwpxngS3zyj3FItyaAZt/3zbIgtAi4FV/jhSVFeJ4VI2a11dMY9OfNalntFLHknEOutdvYFjwyPiohLJhh9JZtyvRkm5mFjxhOrhdTcme3NmiWKvgqbsP9R4/dlYwNhqkd2+0m4aRvsvTOYTpEQknJ3xhP794okZHYUY8IQ49ZYhXIut0p18+UGncaKipESGNhumjebyDlBhF8GiM6ejw67V2ZuqC2g9iDmM6+jCMaTWIFqa3me0EnNPexCjHrhTa1y5oUXuPViidsk6BcNpcecx1/4J+vsL1RnpDRIQXT9AzDbKt6unfWdK9aRBhglvZvYzytCAx+WvgZ2uJKBTPNF3AF6dN/hIoG+09rldOWotzGsancyQAOgsBVXEdRsQ0kymgrJvMGnU0BbwQnIiL9c2iny9sRvEqNPH3kYt777sp3mcQLYvN9PVbIzi8vYMHu0S/Usfnm72Tz7ybGkcmJjz6kmLuy/D4MAcB7Amg/qvDlmSb6yRxGOMapyzIKlMbLKf7cdO0dtx2Bk3c1Z6o3/9Vjw="',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDc2NjI4MjA2OTQsInByb2ZpbGVJZCI6ImQ3NzU3ZTAxY2YzZjQzMDU5NTkwYzY4ODIxNGJmZjc4IiwicHJvZmlsZU5hbWUiOiJtaW5lY3JhZnQ4ODIwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2M2NDllN2M2NzU3OTk1YmZiZGNjZjQ2NmJlNGEzZjAzNGI3NzU1NmYyMTZmZDU0Nzk3OWZlOGNiZjJlOTY2In19fQ==',
             'altskins': array(
              array(
              'sig':'ox038VGMXB2aiOPUTqlZLWwk5G/7KgRdjLomeDd+4X3Pxqvqj1+TBj+AsoKaBraenAmrPSUQ66CbAlc7J3chiVojexAK7lH2431jpwHzc1LF0E/ezmrIF73X75F0A4J1udfVZMuz/w22IxqyR6PVkwSs/znNOkEvuM+IytHhJkK1aefyOBvNjkL6z7890l++zf9mCzocBcBJgdG/LphzcMglXTCOA9Ix1m0PpdJKNlppjeuzPHEGxgKN256098W6gFpyCMzf4Z3gAvYULJu02nOHwYQOXK0vo1XUIL5HkzX54IzDNVG3oeOCvedCS9HeizxR8TAo8F/2IZ9it9cZ9j5NdKuqiIWgJkZSDCipdYQusAFBl8y80vKEQ7rB5EvryzQ4rjtemW4ovkywBdeV1uxN1823T6xuuELgFyHR4s4qcMkYQwxvQcvCmjKrSRnHFDgwiDaLwTu6keCWR5c/28tvTqncfjorL8urDjMZyE9fcyLBpVOAnyNr2XU5hVEUKjjOcGf/dhia7vDrpv+Pizht1n2dLjJYMnbf8RPp5Q1PxD1dLKGeL2sXePu5nCMHFxixWHAhwW6kOMOidB13NMyhWDJXHwN3i12r/Tz0XANEm9gSDczD6uXVDTFVTgkM323NLYfU+/eDXlFJcADlgEU0eqaz1LrpLQ03sM5Cykw=',
               'val':'eyJ0aW1lc3RhbXAiOjE0OTAyMjAzNDI2NjMsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJTdGFyYmVhcnp6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lYTg0ZTg5ZTQ5ZWU1YTczMjIyMDM3OTJlYjgzMTE0OThmMzljYjI4ZGYxYTQ4YmQ4Y2QwMjVkNTU2NTQifX19'
               )
               ),
            'trail': '',
            'op': 'false',
            'speech': "Now the negative speedforce streams trough me, I doubt if I can stay the hero, but I will stay the fastest man alive!",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/whirlwind",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/haste 0-4",
                "/thru (phases through walls)",
                "/wallrun <on/off>",
                "Look Up+Jump+Crouch to perform a wallrun.",
                "/vibrate",
                "/stopvibrating",
                "/lightning"),
                "/tppos <x y z world>",
                "/wallrun <on/off>",
                "Look Up+Jump+Crouch to perform a wallrun.",
                "/thru (phases through walls)",
                "/thrudestabilize",
                "/modifyspeed <playername> <number>"
                ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
)
