@plr = player()




@hero = associative_array(
            'name': '§8N§7e§0kr§8o§0n',
            'class': 'nekron',
            'sig': 'ffLTiWI8TkHBbac9KrnEZE0HA7jch63iLk4bp+3jzrfHdF90ibLJcaJfavIfvSvxPUAubRj5p4bsj6boib/VPy0gPxgN6cMYZCYEnNtgm6pOJOI9S74UwrHgArD82UxyXgEyShSUBL3gBqpc80ZN3uBRVEb5n72wYyq+35ipWx816gtWx3XiOEZBJMlNML+g9HaP9INkhcsztu5uQag+n3DePhkvh8tjqF/9iv4snj6LAI1vKkfzuaUYjs2B1fJFRqHSQ9OxdwpFntqNht+dHpZMjfaNpymYv7dgMfSrxb7HjqHZOSEa3EbbyGo2D357te6SntpKW62/QTmu1IjptxY0Tf1E3/HYW4hfZi+ZVoOhVyeFsMYegzr4lvPLrHQDmvoIy/KMflzdwMVemK7TxN4ccP9MSdPFeYOVCh94lhMGuch2mzZpx989mr8vDKcMdJI4lg+ivM2STg2aRsk4lOODRAMx0dIOEV96oYTZy8wP9jKbs92dyau5nR3zeYl4OUj0cva6jbDuannTYHebeVdfCapLnTL0zgIfwlg3omef8wy/RY5vQWgDmFEq4cY7mu2XU/HCluW7rWULNuHGTJX5+aDarJQdYyGwFPXp4NoS8j42reu5FpzGo0R9ZDAeCkvFIy6xf21ZHcwGlYjHG9Ml0CtQmAkDnrTBkN+faNU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY1ODE1MTE2MjQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2RiYzBjMTI1M2NkMjg4MjU0ZjVmNTYwZTk0ZjMwMzVmMGZiNWQyZWM0NWI2YThmZWJjYmEzZGIxZmZjNGJjNCJ9fX0=',
            'trail': '',
            'op': 'true',
            'speech': "You owe me your life ".@plr.", you all do!",
            'powers': array(
                "/buff",
                "/flyspeed <number>",
                "/fly",
                "/kill <playername>",
                "/empower (You empower a player with your Nekrotic energy",
                "Mobs won't attack you"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 254 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." nekronlaser",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/give ". @plr ." minecraft:golden_hoe 1 16:255 34:255 name:&8N&7e&0kr&8o&0n's&7_&8Sc&7y&0th&8e"
            )
        )
