@plr = player()



@hero = associative_array(
            'id': '152',
            'name': '§fNick Cage',
            'class': 'nickcage',
            'sig': 'Fyr9nrC6bt14h+QtXLi8zGXIWlt3KeSAgiIxniKt4699M4D+hATHbY7+Te59Z4zvUYtXyT4XLUmCO4ypUwd2NMa8oeyz3wwXK/DfAU3P2X8uuK/FTP5TVQAd5Q39gLg4HEE0qDMUUkuU20f8xNwAn8fJAROtZVu27yqWJkQtbs0L5ehPc75sLzvoq1KII8l8qHJhz2+CtpDTyPcmtX2WfRYet6D0gZNa8r38q09i2m/qhkzbXrS2m5G3Ib84eBps8TceoUp3aYfHfnz298kkCLOURbiMt8QYeBEKA6OmiUp/g4DhTI81ownsmDBn5hyzF0NZivFS53J1BGuJ5+9J+ritsVKEzOpAJDNpyVT/011YQdZFI17+WKV3qEI/+jxsNiGFa9u/Mwqd57oUWwvNq/9slwKRijLO7ES3cXQ7AfLT2t/5T2pulndljsYLQrll15RnsejDPfWI23t8jFCbcU9hYgIZflXAMdYRGbmes2YZ6AcxLBGC9AuS8f+jQ1MXukMwxLwnrXT+Iq8M9msRGs3qMaaz27kvsih+79x2QK8lhOv97+TJAWFdej/ybmJ5FV3Pmyd5TWoUTNX5OURkKK2m894vFRCOI/Xd9gEFDcnAGBJwfYUN2pXsayw2LPhMrJIXuZLkOGjGzdhew9FIIezXixwiZpz9ie6fZYP93bI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg2MzI2MTE1MzksInByb2ZpbGVJZCI6IjRiZDYyYzJlNTZlMzRmZjQ4NDNmNGFmNTFlZGI4MzM5IiwicHJvZmlsZU5hbWUiOiJ0ZWFtR0JOaXNiZXRzIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zYmNiN2Q1Y2U2OGI2YTRlNDUxNzc5NmM1YjNjNTU1MjJlNjE3MGYxMjc1ZjI4ZGViNThjYjNiYWU5YTk4MDE4In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I am the best actor!",
            'powers': array(),
            'buffs': array()
        )
