@plr = player()



    
@hero = associative_array(
            'name': '§8Nick Fury',
            'class': 'nickfury',
            'sig': 'nymD/M4zCIPgyWicEfJ+9bRU5eqmKpjixA8GAyN8sQPhu8/BWqkpjiwGC+NEEoRWbc6DwSiWD5X3ZXcH2r0YpdWbi+7cJifWeh7zBGVwn4LpQ75hMDE1OM+UcIKJ3jg2D96DOZU5OuFxrkpmGRqMXzV758fxsnB+kbWSIoKlqMqw0bodA6shrDXGi4h0NbnAVIaneVrDON7HgJZqUotzZHPDj198itSX/R4bomhUjVWYmb+Sg50zuzuVeD5A8a0bNfDKg4vIU+OuLKdtQPugGwY1bhNyxCt6l8bDEkwu64scjrISWlG7K2f073XWmEQcVZyPVKPWo3rf05KL2E7hdHVpoApy35qOCeRkPt8/fAmo6f1GpQ0tNa2kpRB20ejPU+KL6e/y4IE3K7n2uve6mN6xdtM/G/tC7I2MLGCVyZfDbjHZodiFQIZazslqbs1UyyR7iO5JztvJdixlZHZ8kFBBTsyr4+7xXXSmtf8tSvt3gyUMYRLx0fiOrV6zUooYELtKofF31c2KllRCrGAFOPaLtcNWym4vlalhNzFZIu464CR4nfhgkpuJjMVqnjUCwWnnl88pWTlS2AUICUaNyD0eQAaYtQ1bTim8pbkigdW27uS4pJ3nct4kI0CwaYx+C74Ag5hHhvQgBUbTs1FU4nHR8Ihp260cWXx7EQKDmes=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzUyMDg4NzMxNDYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2ZmN2YyMmEyZWFkNjQzNDk2Y2NmNjRmYjljM2ZmODZmZmI4ODJlNDE3MWMwOGE4ZmZlZDc4MDgwODRkNGZmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Director Of Sheild here.",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 8 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." AK-47",
                "/shot give ". @plr ." Hunting",
                "/shot give ". @plr ." Olympia",
                "/shot give ". @plr ." Python",
                "/shot give ". @plr ." Gauss",
                "/shot give ". @plr ." Putty",
                "/shot give ". @plr ." Grenade",
                "/shot give ". @plr ." C4"                
            )
        )
