@plr = player()


@hero = associative_array(
            'name': '§1Ni§4g§1htcr§4a§1wle§4r',
            'class': 'nightcrawler',
            'sig': 'E7dCEo343A47XbrMich7suPF3tPW6yrVWzL1oAmSW2nZD587PDC2yY5nQraN4TfTDy5cWEx+zqADUWg0ymWvs8U2EnqGZRIp8bXeoMnYwXn5gT1O3Amoc5d0zlF2UyqcPMMbgOKDguETl6Uffvry7YH/w07ZH53i8EhiIknvCweL2uzfver4bWpoAfh+QP1kavkEWoaVVkaZTvbMNv+yfUgXXlKHdYGxBCHo9Wz4TkGdJp5p70iOa4gyUa2+RvROPHMgy7VBZ+8lIRYwQ59Rcb4CG7G9nR+t7JzUlKAwIkPk/oA9LOd4a672sWX4DfMa9gQAlXLMkWsyfLZE2Y3FXrBqk0yR5sAHpJOLcRtWlbG0CDXUlh5TLUCfQ6LFz6bwwOe/dEqOtS+x749tiRUKMLH0CGuOm6HJtmmQGnvolpu+OK/ngsKfhmpvUXxh5BR9d21bn/xYI1vss8pORVxqKmP6yOWd0JJUdkmx+yUAA007dMSMmK+DfHVQo9RAXxNLFMD6+OW+EoicfkXjg1zRBUiGKhWhxyX6T60qIpX5zy5S5xPd5vQyhWfsanf89x49KgXgTE3IYxHYjYaybUz3SO/U6BWQPUwoPOELBLgkYT0Y4grEfEDhVB8OAnOlS2oNXE3pBY5sjvl2nE+fk6icTjdeAczegIUQeiW3toX7GsA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODc3MTQ4Nzk3MTksInByb2ZpbGVJZCI6ImJkNmY2MjIyMGI3NTQ2OTg4YzgzZmExY2EyYWZiMmU5IiwicHJvZmlsZU5hbWUiOiJDaDFja2VuIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS85MzM3M2I4MzVkOTZiZjc4NDU5YTYzNDJhZDI1YjYwNjNmNzBhYjM3NWUxMGIzZGZiMTk1NTg2MDhjMTcifX19',
            'trail': '',
            'op': 'false',
            'speech': "See-ya!",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-4",
                "/haste 0-2",
                "/vis",
                "/shadowhide",
                "/jump"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/give ". @plr ." minecraft:lever 1 name:&1Ni&4g&1ht&1cr&4a&1wle&4r_&7Claw"                
            )
)
