@plr = player()


@hero = associative_array(
            'name': '§1N§0igh§1tw§0in§1g',
            'class': 'nightwing',
            'sig': 'Dx75srg6fRc3fOdoKbEEo53hp3R7ypLwJgT5mqd+b2PjFscSiLMZYG3sd/mCgWNpGxx7PtEv0BB2lEwn84FyYswPDgze6Z+IgyX3zxQlm+doVH+8IIpTmfHHp1y4v5DIEstp+kPNuoT8wosfzPdrERs66BdSgdmp30BYNQz28rJ9rTeG4N6gvCjmRK8xKZxl+j4yYiI65mJNTNeC8wniznqhHtuqsuO4FoenRTX22FdcetdrrTKlT6kTBUgDfiok/U3FUm9Pv1IJjwnJni4X69mrMM7/GTtQvlsgYogEwOMX+MzWr/nDARhymMgf4NvADPi+y+4t0FYfvzppql5YgZi1ikOVUBmpodcOAZYBolW6i0HKzOcnxARnw2wKEY38F3lSx85zvbOwSY2c32SJCRoYc7rYwybZA0hv1ZKZkLAQaRL//McnrfpJtZ7gDI1rpZF8J0dNeCkHm+HRH9+o4MWTsRC+dPc2WiT//s+8P0x0BU65+2tG6NwVlivVQiZnsKsASy4br6KhE8m27Sh8TFQHhk6yLRp0i3G5DPIT6neAYRTJ9fg9MxFWZBLOSdrzLNH0lEvwFQNit0gas3ty+oElKbnrBW2ao4GDaaLdBx1+AeyqbCbdy6gpACLP6+h5uhQzGdzsaHboaq9wh1Os0tpOGO8igECug3cr+RP+jB4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjIwMTMyMDAsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Q2ZTRmNWU5M2QyNDk5MWY3OWE1ZWIxZGQ0MzFjMmU2NzllMDY3YjNjNzkzOTc5YmFkM2M3Yzg4NGVmNDNmYmQifX19',
            'trail': '',
            'op': 'false',
            'speech': "You'll never know if you can fly unless you take the risk of falling.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&1N&0igh&1tw&0in&1g's_Glide_Wings",
                "/give ". @plr ." minecraft:stick 1 70:1 34:3 name:&1N&0igh&1tw&0in&1g's_Electric_Stick",
                "/give ". @plr ." minecraft:stick 1 70:1 34:3 name:&1N&0igh&1tw&0in&1g's_Electric_Stick"                
            )
        )