@plr = player()


@hero = associative_array(
            'name': '§6Ninjago §4N§cy§ea',
            'class': 'ninjagonya',
            'sig': 'Bg64EAR92oJ4Iv7DOltaetUPOdyRb42fnqCtnP0jZqUvZz8kTC12vWbP5lUxpoBQvi0tS6p78BA5o/lulCbma418g36PdRcISnVVboM7fD+cerPg51BXvdyFZKHb0m+B6lFXvQ7QUWMYyAH9U7y7T3mlhLjTd4FZvaEaC0569u1p/XV/UY1AQ2ZEFKODdNeEWu+OUoGTqOI6dx0Z6ikZvx9STacA35N82Lv4oShtJcreAKdxgXnxKkxFBgKavY6yINMMcb4JOJE83lWFWXxUMNKR/5DtgnvqqmyO9iERYiSNFc+cuRYczVDb51H5b/MgWExFzOP+Gl3FSr7+Kkvk9eFNZ/BPYIVjEGzrBoLzPKUI4OHa3FQueoABi7N8kKIzvLro+XzS8T/2xeAcvcdqcLj4B5NW2dWy4n/bvk+eCJqheOHMmJ0KWrV2DzTw7wN5PIqcwgkwTDGA8ZvgAh9fYFD5CMOIhx6ud1TIGopYXsaCr4ZQaOif65T1XdRy1OrhjR9yieQ2xMCf29y/us7iS41IEUttGigXBIQIB+iS+QpxYVRtQIoJHkao3rge+SXG6glu+Gg9svFvz53QUrW0ZgX6QCWUAXkGrFcVUZufVO/ct0ZpD57rSiX79QiCFY5sKGM2GMwgO8jg2boithd0ttllVb0+u9et/kJvI0vB+QU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODUxNDcxODE4NDAsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJVbHRyYU93bERDIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80NmEyMmZlOTU4ODU3N2FlZmUwNWJlOTkyNDZjYjk3OTMxNDY4NGQ5ODk0NTJkMDM0M2ZmODE0OTRmZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "GirlPower!",
            'powers': array(
                "/buff",
                "/jump 0-1",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-2",
                "/spinjutsu (gives strength 5 for 10 seconds)"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:stone_sword 1 16:10"                
            )
)
