@plr = player()


@hero = associative_array(
            'name': '§6Ninjago §bZane',
            'class': 'ninjagozane',
            'sig': 'UXdh6i6/tkqRteZpHI5RBTytt/sDeyTUIfJ0F3u4Tq8iUoSmj7/7FtNzQ65UXeT2j2ouSNVexqn9mV7Vnc4WUR4U//rB6yAlfbobmSDxjW1nxtsxJVI6375m3dFNQuFFnB4StxlQN/kkMpRpLNGF85MlX9NQwEOUFh98oVPm0nI6XCi17Eb2NS5klk2bExU2IAXjISyL+9hSQPWBkpIuJ/1HEqlq9r9YBlhSQNIJEcN4CEXt2CxYkUPy6BIWEEmZ13uAY4EHQ+kwfWFXZNMtzbmPAdLWQQAUJ/Y5NaVCIgHbFAI42q6udj3avIT8PGIq5X5FAKVynkKZxFPm1MxvqxJlH2mFZqFSPT7QQMbiRyd4aQfoh0STex3Ns93AiAcOmV37MV9fmhxxxN8XW7T+5Qg/M5QNZWxnD0n10GaQIvX7c+JAUu6sByULB6FemKQTwM3TP/FEU+vd743HnVyHdZEP1ncv2ZApSkGCDxkuRoXdmyj0WFNYSnY+8ngVS+skEwJH6vA+gZdOk0yQ0hMnYiIqebLBgo+FFTyGu/juEQgPOhqDwQ25ekzH4ePZEuWqFiiL25va3sHB3rBeqMXTOPwoZ/gQ4S3lNIkX/6uZdMxMB1+63yDo5A78lHH3cFqyiZGxtSXu0cFzkoOAHAQBtzT4CM7ZWT5rGDGxkzAr1ps=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODU1NDA4NTUzOTcsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTVmNDNiN2ZhZmFkZGVmMjBiNjA0ZmMzNDJjMWE4NmVkMDdhZTQ2MTRhNGE1YzQ5NDcyNTEzNzI4ZmJmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I am the ice ninja!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-5",
                "/spinjutsu (gives strength 5 for 10 seconds)"
            ),
            'buffs': array(
                "/shot give ". @plr ." icebeam"
            )
        )
