@plr = player()


@hero = associative_array(
            'name': '§6Ninjago §4K§0a§4i',
            'class': 'ninjagokai',
            'sig': 'LOH9Tf47nOMQFh4m1stwV9EbafKboZBVyuU68sN3VmFycHzhhufCcrocYWCw0GMraQB+DhJzcKrmcgcjnANM4YcIXcoSm69B6/hk5ByO5h8Rp96N9OaMOmjpIlfN8k/u9DQVQDdjHbxO9+yI3xXAfPm+ccajk+fVWXiWvYHrj0tSi8JnqiceLZkLGXYL2sLQwvpSavsE2we8Rz76qOl9CSkalqbQUBrUdEuId+Ct3dgtqNZ2g2OgncP554XzB74OH2BFTtMx80qCSutmmh6LUio8kvlQkJ5GlznUVWxW/FDdM2LoZGxJfyPZ1ZxRpsaH0EDg/+WKxo6lQpKGAfLFtb+o2aIfNTZNZ685UKFFxDGAeDL5hvw1D7f0o3HcqmvrzxgiBn/2GJWE3NuEhc0PgDWftH7aMAK6/PHpXOn8qd4v9WtiWMU3FP9rp63FMQThxyxrA4291SAbKhLJtpD0J/LdgfCB9/zWI3N1gscSKNM6v31DrbJuXkhXHS5iSlrgSZ3Gdp1bCTij/HpXDdLEH3gewTFLOFMEskIUBrzp0nc5523v4xkkVI+J230/eXYuuzWVvKwU/Uu+mkMMeL+iiQcXBv6bIF2rkQRvqBdmha8mQysnAaiSSRBEgVYK4IsZvpU+sQyRWEtcQDAd4y+Aodolc8Pc4Txw15mkJpyWO/0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQzMzkyNzQyMzIsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjQxM2IwZDA4YzJiZTJmMTUxYjFhMzM2N2E4N2I4ZmY0YWU1MjIxMmIwYzU5MDNjMmE1YWFjMjVkN2FiNTVmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I am the fire ninja!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-5",
                "/spinjutsu (gives strength 5 for 10 seconds)"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:golden_sword 1 20:2 name:&6The_Sword_Of_Fire"                
            )
        )
