@plr = player()


@hero = associative_array(
            'name': '§6Ninjago §1Jay',
            'class': 'ninjagojay',
            'sig': 'thCo+tPN+4BErs5CgqM0XzPMhpmH4h4YB1VcvBb/pOvpxOkijKXfd4n9rSZE8BFJb/aE2X+RvvN5td9/A/f/d5jtImDrunUB3Tqh8VUhF3nJhG+ztQVnw8hQJyYPQuLex3f7agD3Ps+1+7SFCq183nYLcTeIfUqgVfYc1WHCcG6V9JDRlw6FfGMK4lgK8K38uCw/mH6RIzUvIzr31owo/vwpckdXm1oLIjmwxeeEgaWXbsVTIYd92MgoZuI1QGJdORhgGAvee0PC18CVgIRlm7O1rC5New17tvqVaG4nYSFyz9XDsxuMm5slmFA/iMWtvm7M5kzl1PilpkT60eUZu2FavYNmjJJrOh6QJktrFEJuGO8elIP0nQMbl/B69Tk6Dy9R/aSpX4AZrEgqgxXhGDqURLCy0naNlftVgQ5CyedP9T/FkAvOHO3tbshvXulYTSqRUe37DGohcxEnCSVAZiisbbK1Of9aPuQvMQ6pVStnkC2f8PhqpPmF1dYQng6KeP4KoAIKvzqbWrXi9V5HY86xFJvVVpacWI0INkIEZxf4Hg5C479vL8e+h+FZJz/ooojblqon5Z3z4pNA6wa51+E6pLN335wTTfHrvizVarvaugl5PAkxy+P157Pvkkj5W0m/kaQ3I7eDeXn+ROwcHYM2J1W7YTk6lUdAekauhuI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODU1MzY0NDk2MjksInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmNlZjU3MzQ3YzYzNzM3M2RkZmI2N2FhYTc5Y2NjMDQ0YzMyYmQ0MWY3MWY0NjlkZjgzYTdmN2UxMGFlIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I am the electric ninja!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-5",
                "/lightning",
                "/spinjutsu (gives strength 5 for 10 seconds)"
            ),
            'buffs': array(
                "/effect ".@plr." 5 9999 5 true"
            )
        )
