@plr = player()


@hero = associative_array(
            'name': '§6Ninjago §0Co§8le',
            'class': 'ninjagocole',
            'sig': 'dJVgojJLUZYYNjkTaZA3m1xvyuPjgg0uaGPgLahZRk4uhkz69S6PxFE2w6LNrXxP0ithL5I7sZa9pw/F1Pm1hzXUPFlWTxE67amp9X+4RpW4YwAGPj039pgHUQaQzv+zqhZd5zTsNY6IsvtIQafFLUnTOd3rJ2G2rZaUljmZlO9uT1vUZeG2bzHbUP1mEe7jZoID2gcC7aug+93b9n/ATdAFq0ImyWH5jnjStHDYUu564W1Uu0oNnRDKEPRFaxR1MK/K1EaNw9x5SyvpEpTP1M8Lnj7MenVYPi9w+BzxJPVrRQjApvySzTARu1yqzk7OwRnmdh+ft61rW2oawCPm9beb30tBoGY/mBU+sNGzy3sdE4WHXjZCutyNe+6LWfl+21CUndY5+gJyo/pe+L/atqeHhbns4HUEbFhKmVo6xlcKN0coGi0iVLwyr3m8uEUrIh+0dh2pvmWy0dQ+zQpYq+MxirkusY1H/UVCqTWhlaHiB0Sa+ou6etNI1BVUuhjOaH1WKzXeKjzUQ655Lj09Z+06UXb8K27NTa4eJzLGpjczAEwXAdN3JI6FfENs3qpnCbZjh5YBTgLDmSSQmWvSfj8h6oDiXQsVRWISRDc3qyc+2A6kOkgbo1SPIpW8F6I63DuvaEN5NN9jfZmJSi/rOkEtLnKQOVLpwwh+6QLKFUA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ1NDIwNDQwNTcsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJVbHRyYU93bERDIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lNTMzMWY3MTU0NDVlOTBhMzc2YjRjNWEwY2ZmZjNkNDNlZWMyZWJlNGNiODZhNjMyMjU1ODVkYjE0Y2UzIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I am the earth ninja!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-5",
                "/earth",
                "/spinjutsu (gives strength 5 for 10 seconds)"
            ),
            'buffs': array(
                "/effect ".@plr." 5 9999 5 true",
                "/give ". @plr ." minecraft:golden_hoe 1 16:10 name:&6Earth_Scythe"
            )
        )
