@plr = player()


@hero = associative_array(
            'name': '§6Ninjago §4N§cy§ea',
            'class': 'ninjagonya',
            'sig': 'R5dSD72liS/6IvnB7i1dKsprQqFeSKEx7+BNEHqXk/xE50kDei6JRC1saPFM8NWY48FbF9x4xkBsMv1PSsCyLtl8QwsxHiZVoPd9tnejNUz2eqpLZESSnjcTi/kLvRDccWdKpqYwOWmiia1Lzpf1cLHhZy2Ez/hLe9+pZqH/iSc9Q1guAtVfaGsfuNX6S/oBIYgxLYWsNwbc/61JsKQjP6X7sY8htSAj/yzR5+OO+LQ2u69a49sobWbOaHCTntx38BDH+ozFsI5LmwMebiqjUZ/wSPK4kUDRPNMuh84UwzseApBnCg2AKwWSqaMg9ER49ULwDpS1383KT1/x5rOtU3ohlw6fqOaByjpaEOApQLlM8twX03qAXY38xu9+4evqxkSh6Eou3sDZlxWNwybWyoQjYavlnE0mQ9AX3x93pvoUrTP+OjyvOLXLTjv/m4sHYky/xKGIIfBaUWca6jPpi/LHYCVB+qnpOG0Sna3cKFqYm+MMo6PC/mtANAYyGTs10NDZk+K39Yyq7pcHBqGWo+TQbMHJIKl+LKJ/IXN/PSOLCNkteplPqGPe+H1yw8ZwS4AwxPejNASyb5367THKyiqXhr+PUSndJzon4nMVWV0tynZRF7hNgaBhhb/gGFlcn2xDowruJDkpuIFo1jkcB9l0IxKxh0nPj/Lzpi8CoeY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODUwMTEyMDU5MTMsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kZmQxNTFjNDNkNGNiYWMwMDNhOGE5Zjg5ZTVlNWEyNmQxNzQ4MzY0YmJhMzliZmNkMzU0Y2U2YTMxZjcifX19',
            'trail': '',
            'op': 'false',
            'speech': "GirlPower!",
            'powers': array(
                "/buff",
                "/jump 0-1",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-2",
                "/spinjutsu (gives strength 5 for 10 seconds)"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:stone_sword 1 16:10 name:&4Sword"                
            )
)
