@plr = player()


@hero = associative_array(
            'name': '§8N§ci§8te O§7w§8l',
            'class': 'niteowl',
            'sig': 'Llfbzn2v2OtKF/garU9Ouod6EnMLQHamvHEv5l0YT4UFEXOB1wRddgxXFFNvpUqRhKeETPD47NRcqYwJ4QOvK3HGKOkV5n6oCY4V4m4z2lmodPh8EUvs0X+8l3CtCAHIU3rA9qdCfXNhnd9LGLCSF2NCB9Yk4RuSVqSbCXYFPn3leWtdctbLfy0X07/+mhE6ybWGELI8d4PQkBhEzCM70tH08KYLrTxp0CyS+pJ96A7Tu594VUoXcn8xjkXeObxC52RmgYkxKd8Ellvw26Ho27nxmP8FjzCJC+YB2/TgzMVYXvS3AGE43V5ISiq91w1I5Dus2fpKrt1CDxDfIfce1mhs1A58nGqbSJDJARwzwrpEn1uSZHh5yyI02M+EkHXMiVpZQ34m6DMX1Uo5WVLLbM+ElmiJFX+miEf4bfMKKHbsiOg4DCEWjhcTJyOu65pM1BmY4sch37XWxRBazuSxWK7T1EV8U7A8ptiSxsCM8JAEar3IyqXgiRqdzDNBixWdf+TFKsKx8scHcN8MUVU3WmCuJz5fmJ6Hb9/WIyQlV9lRfCIjqWmBC49krcVUQ2IetEg+Uw3ZMOKlgCiwAbGxteu7rz9nYZLXBecV4UflbbH0h5CvrBDFI79N9dmgTo00rJWZ5SwfsCl5QGFhb2Sm8HPpyRZZ+xcsB9hPijjiKJY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Njg4MDQxODQ4MTIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzU1Mzc0ZTFmNzI0ZGMxNmU1ZjJkMWIxNmZkZWJjNTY3ZDJiZjI2MTU5OWMwMzNlYjMxNWUyZDE0ODNhYjY3Y2IifX19',
            'trail': '',
            'op': 'false',
            'speech': "I seek the dark sky.",
            'powers': array(
                "/buff",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true"                
            )
        )