@plr = player()


@hero = associative_array(
            'name': '§8Nor§0ma §8Desmon§0d',
            'class': 'normadesmond',
            'sig': 'xItR7H21dD2PDeaFnVQNgs0oJHaB5ATosCgULQBmfclaAYcVTrwnnNSYJibQHsLRQkB1oDZfyCtwXqmALi28k6EneRpt8y2cNcULIR237lOWYUIKKyfEO9obZHmmCSDjhjogGEnCFk6Lp2eRO4nIhn8YYlZGrpMIQ7YKItqJVYkvKpe1SB4FwzuMEUJDuGyn3uPmgX7MUfwX/hv4GLo3g+Q4WgDYKCk2nKFS70jReeZJ19PhGGe3vmm9nC8ytYZ5VXS4M9FjToJTWIv9wskqrRfXIcbs3wb/7At93/Ajs4arPTkzch8g1ysnTdQYaFS0Lum8zyJlYbyrXq4Uhz+oz85NfSi2mvJ7rFuJd3zKtNOx43VWhpADaGhmZIJBaunjpym7Jap0NmdB9zaHGylQyFFoZJIF8LR/+0ukizr69liQGQzLLFHppM2slyPOQnX+urqspNShwL2x2i56oLVhJkrDSnLUI4QDBtb4ZC19HF1cFNRJ8g2ZFqz6YT2LwkSf46povwwjOKD9SPpTgxNppKslVtkfm6RLuHuwLW9UyrQ9wwWUOyAILa3w+lQt3+JTR1imdVNGN3+SukHCF/Fz4VJPATIPgP1MWXNHfxEu0k6VfxLXKnWPLzg0bBg26FemUfw8iZKt8jvmSl7MzVfDyWK6e0hoVYyraUYYI3yg9w4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDAxMzk1NjQzOTQsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJCYXNpY2FsbHlIYXJrIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGI2MWMxOTk2MzlkODU1YjFiM2MxNjkzN2MxOGZlZGE5MjM0YWZhMGFlNTE3MzU5Y2FkMTEyNWRhZDQ2NzEifX19',
            'trail': '',
            'op': 'false',
            'speech': "No One Ever Leaves a Star!",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/shot give ". @plr ." pistol"
            )
        )
