@plr = player()


@hero = associative_array(
            'name': '§1N§eo§4v§9a§e§8(§4S§9A§8)',
            'class': 'novasamalexander',
            'sig': 'OnL6VF1BrhsRIRqby7eZKubr0l5MiTmp0DodhUjHuIf3Ll2R3jWQwnLoaeVflxoS/0R9Q/e//u57RPu3SZ35GZ+ojDVP/qPiC4DuBnj5xUZPDMOWk/Ec6yzCsOEZRVbxU1h+NR+g2efRs+UfbY3TYJKd/SumYfsRPaIAz8ucmdkjzsHjRnCOEJK+M8lLUaT8SuT56oG2jge4k+GGNXYYTXUlCsNHKIJzmWTwIc4rXeeqo6fa2Nm8QgGwnktXxSWNpS4YIXI5pbaNK/21rO+gkCe+exJEVf24YTUQLNHSXnEMaZjS0QbbhCYSKVxn+b5C0s/UBpzrFTbRVjqZ6RK6/t1TCPnN+9X4xd9OAVSXbpAXTViAWfQG68kDjnAeKv7v8XeBTytEJrl9vEz33d3OWDcSH1MpWbvOJdzGm0CDbLORKECsOgaY+/XP1jqAnKGk8ZN8MUmDmIXIEjWda7b1wZ43oJtBk+tAWSB7t5AthNhUwORfc5YF3r+6ZQ8flp6QYadMde9yw06LBvP/6PQ6R1ttBNjUkN6tmjxec4qEBcxm4pB+vzqhxNbqtNwq7SLm38ipM2fFRpIW1KOfeFMvO1L/m1BUvUO67WBEuX0wBkYfWl5mkpEFP586lAjP7zpf9HnmPQTQzD1ssjDhlpztAc5imro+v7TUpc1b2eY4psQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg3Mzg0OTM1MTgsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJXaXR0bGVUaW1teSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODg5MWIyYWI5ZjZiM2I0ODQwNDgzZTc5ZjdkMDNmYmMxMmNmMWRkYTc3ODRhYzIxNDQyOWU4NzU5OWQ3ZDgyNSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Don't...call me...BUCKET-HEAD!!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/fly speed <number>",
                "/fly",
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." novablast",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
