@plr = player()


@hero = associative_array(
            'name': '§7O§bb§7i-§bW§7a§bn§7K§be§7n§bo§7b§bi',
            'class': 'obiwankenobi',
            'sig': 'XaaOOuE6g0tIWL2URJLw0tt33BCAR2DQI7382lbWgl3MW+OtL4IGUuBi7Wfob+EqqF15qRykzD+UDkVyhc1YTdAucll8ED2/+Gklbzi+y+Gda62D9cIRmxD7uxuJYwo/pkntkB1IXSilZoA3O9+E3P51jiH3Hi82Juq0oFe4ZBjMO4G0Y0i6H0vuIUgscYeoBgKgzXMAOoCdZm2MI6PCnHUifvRS/q9LKuzcFqS+CASA5tcXg257Bl9rR2o+elcM/pqnGwNVzlJ6dYmhv0uLNH2ZYk3m3up/w0jwU8v9/X4Utlqk0Su3K77IB2epoIq5rw2aaV9XN9D5OPUAImIboqMnr9MZVxUDnBcR26WLpKkq7K/Q4bzBWNgDOLJaJhmdjTWkgzT1mubDNZ35f1rPd1MWkSCWYpR37QmVLM6+3N02onl83TOnMgChaKc2Ntk1ioFO/NZ04nUCBjGamsgxi6j9WmWf+YIWRp3qVFYbIxxXlhenXyGNPt6+Jz9Ih0yd5uV98Wxe/8mpqYG1ZCpM7g7Id8AWLxERJ3mElR4OhCEm/BhpsfaBzsJCbOQDCV27sIHQrUdXohp8O0aYYm2URqZlDzf3JS/izygEV6vOBbMAj6g1tdx4MNL6arsIbKz0CfXsJbu46Jw9GFbnGvAr4K34qeRGpRIq265yJa667is=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDQ1MzQ0OTk3NjYsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJ4VG9ueURDeCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWJiNGE2Yzk4YTExOGU5ZmQyN2U1N2VhNTdjM2Q0MzdmZjU3MmYyM2IyYTRjNjllZDRhM2EwNjA1MDMxIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "May The Force Be With You.",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-1"
            ),    
            
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_sword 1 20:2 16:100 name:&7O&bb&7i-&bW&7a&bn&7K&be&7n&bo&7b&bi's_&7Lightsaber"               
            )
        )
