@plr = player()


@hero = associative_array(
            'name': '§6O§ed§bi§7n',
            'class': 'odin',
            'sig': 'q6VM8Kbw7/+HfK+WeYBj0alrKo1FFu+6X0HqV76szThB6DloWpZY8KIiC6yMGhG0jDYWaXSTLiOclpX57XYPXo4rJprMBlr8EokV6jZhv+JgA+dbBRzF4LEBXbP/DNnyhzWaPGW6yuOWmJiX+SJY/pZSgm9Hley2IAb1b6OQThHdGcPiv6D5oAwP9QtN6/QWsLVReacEcuqylNuuAc5Q3FPEWJdCLylD9jf7gdOt9bGUzqwtXN//yNycRAmSq+w/zRSWbvwvYjSXczXPT5otWvTBAkDQYtkOBC+/r+SHnzoGQLAjnlSjRP1QzQGEVl5oEMbzrPzsquApkveUBgrkM6pQzl4gU4dzbeiidPPvgNVRvdH6nrYkYme2WTFpZ3WptPRNY1fIqPbW4Mihndy+vv/03AJh8M4d2iRK7xWiiKfM4uHlEcSPBaB+JPzPkFetHGQNlF1PlSeMl73C3Vap5BCZKkkPBx+11qeDr5nYKJnE1BKk2ysP7b7UbYVyESBTpCehYIJTKa3YvQaaEm+hXtuu/7DZasKDSOCpfSsrXvd7D7ztky2hQxyhNwGZii8+cAIhGgV7RolHkFdtQdH6P5jFTyO5a0mrmXgDyS8148ntVtcYMdgOCnvWG4dQ4hMrlKuNo2M7LOdLoMT+AuXaTKfkmNQ6NUGYut/2b0sDLk0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTU5NDgwNjM1NDMsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJ4TXF0aHkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzkyN2ZlZmI0MzBhZWUzYjUyMGExZWQ2NjEzZDRkMTQxMWM2NjY3NzhlYWMyZTIxMjkxYWM0ZGE5NWQwNDIifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am the all father!",
            'powers': array(
                "/buff",
                "/cast freezetime",
                "/tp",
                "/cast cosmicbolt",
                "/grow",
                "/normalform",
                "/depower",
                "/enchant",
                "/create",
                "/cast odinlightning",
                "/yell",
                "/mindlock",
                "/cast meteorshower",
                "/fly",
                "/destroyworld"
                
            ),
            'buffs': array(
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/give ". @plr ." minecraft:iron_sword 1 20:2 16:150 name:&6O&ed&bi&7n's_&8S&7w&bo&7r&8d"                
            )
)
