@plr = player()


@hero = associative_array(
            'name': '§6One §fPunch §4Man',
            'class': 'onepunchman',
            'sig': 'YqEfqse4aHeaQYupLBrg85bAlPWQiWNyHoGBsO4D2uzxbfi6U/bUc2UeMNl3F83szuglKi21t8bgiUM6MT4KG/0vL5KAWKS/JeEm2sAWhTEJ8r5MPJ07sL7K0ShCwHOY/w1sDzwPI2wntdBRL3PF/fRUhH6yIUg64yvG7aBTBcrGv0z7Gz7k7WqAGUcu4iv4WW2WC3QRn7Qk6JhFVJ2YAeAkHZG3NDIgCtcUlUWruedeezwnZ8cEhIJm61SZ+06PooDC756CS8igtNQX5JDfOjNEmjPPoDjSGFExr0kQTUWDOuPOgwBY2NroyPhw/94vGmQos/qjCKLzZwLhX9ILGnecOCWIos0uTMmBZxMQ8HTfXv8Uw6xTQs/xJxqxt5cL3zddJB09cw7fy7y0WcTjcqw/itPvmxmOUqwGe+yDAbjV2A11yi8Ca1d3ptLFAN/qkDC8mxELwlZBMFdout7Dp6+6ovBXdv5PfUsqDzFgRpPH3UbDQeOf6cYG7MkVr2MUYJjr/ZnQPoaJ6hfpTA7GesLUjJTD23P867PoBzIJh09R48YdXc/A/C5okqi1t8LEgBiTI20yTFoMBH7TJ0bUdAu+Crc7vvbz1MHZZ0JRhtkvm/rue6THa+6jZ9x5NhAypXJx9vODCq2l3WEdJAoQjgCN9Y+JxE3fjRFD8MNQDE8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTQ0MTg4MzMsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzA0NTcxYWMxNjVjYmIyNjdlOTkxNzZmYzdlMjkzZDY4ZWEyYWQ4NzU0ZmFjNjI3MzlhZjFhODM3MTE3OCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Is there anyone I can't beat?",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 254 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
