@plr = player()




@hero = associative_array(
            'name': '§4Onsl§9aug§4ht Reb§9orn',
            'class': 'onslaughtreborn',
            'sig': 'Y8TfQJSFGDuN4ulFB7qPYT1D90+3iY3b7tyShGDe2yIrv7VI+i3nna13NbBbZXEdX5NZVJrLtcLMKkUq1jjV8ijHc+E/lIeLnf19PmHJ1ZSQXKc71KY6OFRIURc5NF+z5ShDbzoDdtv9JT5wLEUNVoD6qZKXim32zicgaj1s6AyhO7LpvnYvkUZ1kQDw+mV3SI3q9becc9Fzr6GZgNot7GLUjEiy5iIYnVTE6ZPKpjW2QYx29+WAUrMwpqIC+E5ogJUsT5BKt7dWlHcTZUGbxIFzedKwBxE+XFIVjuYmlb/59PPtrvBvGhy67clBh3DtpYAHG6vxwiR2g6BLuczbObOEicIuJuKalpEhMeDxD/JG5f0hsjkU+8z8ra9vhLyyld9Atuc1Qcy/yyqxR5HKGYQAuDri3QDtf691yvJSD4aI0Cgd4xPeZihT9iirdndxcBtvwCKRZTwadUDoQDbRySvLvy5ql0BZkOLJthLqd2j8NiVdX/1xLkNWlUN1kR9CaVymTEGPn0W8Lg/kCR5OREBvOmDVgb3mb+SHEcx/1BxsFZSxOrM2N5VR2HEKRf7+vYPQfgvmW79vHse1rJ9eJkoUZ1u0VBsrZJmnxxSW8ezTbYAKdlpJnLgZk4p3n52N/ri4xYdW0duV+OazKtz3eMQjthHUoxUI75a60qDY9OI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjgyMjA4MjQ2MDQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2UxMWRkNDczNjFmMjU5YzVkNDk5Zjk2NGM1NDVjN2E0MjhkNDE4MGNkYTA5MTQ3MmI5Mzg4MGZlYzMzYzE3In19fQ==',
            'trail': '',
            'op': 'true',
            'speech': "I was forgotten within the crucible of fear!",
            'powers': array(),
            'buffs': array()
        )
