@plr = player()

@hero = associative_array(
            'name': '§9O§4nsl§5aught',
            'class': 'onslaught',
            'sig': 'mhOZJl3AJBDNaGPHkpXmKq+weNfjPM5paCh1DzIpzX1bOpvjjUVV+MMMfxUWrWxECx/a7Qzaz0WIrqkkUhw62SjBJ/kvYPobfmEMohDpVtxUmDLMgZfyUJjcAWM2SajN1/skagcFQt2oqHn7oT3Qgd3deHSiNXgWvbTS7XtezpVvJ9kSAdPUr8JorujuY1pM1YcfyKEX8nhqL9Lqjs6qvAiYWr9vmDyv0TZ5bVWsRxRv/b7DyySm+/vLaFVHEjeDG5in1eg96BaT1IU9r5lR56dLVxlfa+LGY9nwNVw6nQKXhs0tnVjmHaVxbM0p8IXnx6k+JID42k55x5hUppE8FJlHI07wzvvJgxjjf3OI2gTfo7KqVE6WeuKcQwQXpRO8UKHU7cWjoyw3hur1TGYI0nHFCsWfxXW2xamN83I625sxyvaQjaBNaxp2PQhLLKst2AvHHSqRE9kCFZwKRhJ6teGXkt7fXsy7JVSqTz92iJ3t9AWb6HXecnSKTNXIjF6ty/FrBZiSWjDiQWkF1wureOGUwZsjRHtkmN0SaS21hCZAZ3eKChT6U/MAnCtxXWVZe9eXjND0Go14ohVXmhZ/WwJ48+qsZoMlzU1rgShS8huDt6EGROnfieiFHFwmrKtdYtp9iuicFtWxCWfXYPiI9vYEI/nofWyEvOfHOpzxwt4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTA4OTgwOTU0OTgsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJhZGFtYmFzaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmY3NmE4YzZlMGZmNzFkMjgxMzc2OWM4Yjg0NmRjYTZlYjNmNDcwMTBhZDUzNzJjNGRlODc5ZDA4NDcyNmYifX19',
            'trail': '',
            'op': 'false',
            'speech': "I'm unstoppable.",
            'powers': array(
                "/buff",
                "/fly",
                "/flyspeed <number>",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/disguise",
                "/undisguise",
                "/speak <playername>",
                "/confuse <player>",
                "/carryplayer",
                "/dismountplayer",
                "/msg",
                "/mindlock",
                "/tp <player>",
                "/jump 0-6",
                "/run 0-3",
                "/haste 0-4",
                "/lightning",
                "/grow",
                "/shrink",
                "/invis",
                "/vis"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_bars 1 16:155 name:&9O&4nsl&5aught's_&8Claws",
                "/shot give ". @plr ." energybeam"
            )
        )
