@plr = player()


@hero = associative_array(
            'name': '§5O§4nsl§5au§4g§5ht',
            'class': 'onslaught',
            'sig': 'P/+VTv3enCe+fnwpkpVQbNaz5frg3r1m2/HDeQJpbHPNosT1qnCdphThysZzI+ssOOuP0Ow/bCXUgGKO0Se0Q+zdSKQqhRhBCfFejWQ6qV9SN5cHsSt+rtjpv7KvqE4zkuCbo6DqUjC501nAT+7lKCaqbe0aOFlAIIOfw1ajRPilt5tPnHIRmHM09Zucc/lMKZ26rXciajYuy+PY24ntN5l8kvUpSnqGG50EE4PLl0DbNZ38AUVk0GXq6pM/tDXKGV6FkDqahwBQ2M9eZqbSMvaz+nW11kA+96iSixQhXFxG6ZW4Zah5vYr2ZXcBH2diqG+esZ8ywTtTQXj5qCQ8amOh84XiA26+NR1t4KH45p3w/ck/SyUE6ZpUaC1/XodPmAZWylswWLyj1irZE8kBxUyE1BaBH1+MEWu/+PNmNV2B3KNLHyThs9Nmkrwp81N26rHOFGWp7TYdpnvBtWBWlDMrSaZ94zdNCBJsVYKPvXKau5xHETeqp6jbsK0x8veEFS2dQWGfcgmVclorh0CI0h3pJ3teFnV+TdoDiCN4fPiRvuAwtQ5MjCKdgxAmhExHCNc2t6wLoy2G25/7md+q7ipbuSBQmDZVQxmrqftGY9tW0Iwvn+jqh4zaxGT80WVd1zA0MmermXEJS++iHnjvFSII4DckKvaI9ku9VcZx//w=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTE2ODczMzQwNTMsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJMb3N0SW5HYWxheGVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmQ0ZDc5OWQ5NzE3NjZlYTU5Y2IwZDVlNWRhODQyNWEyNTY3NmFlYzQ2ZjhjODdlOGE5NDQ3NWI1NzkxNSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "At last...FREEDOM! Now behold my mighty hand!",
            'powers': array(
                "/buff",
                "/fly",
                "/flyspeed <number>",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-3",,
                "/mindcontrol <player>",
                "/mindlock",
                "intangible",
                "/tangible",
                "/disguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 7 true"
            )
        )
