@plr = player()
@hero = associative_array(
            'name': '§1O§4pti§1mus §1Pr§4ime',
            'class': 'optimusprime',
            'sig': 'fGCK/MTI65DQCMwOZqmlP/uB9sqpcayzTCwheUywUXtbdCYtWD40coX1pSestZhLMNnDUYB8JIJmsgpMjuNpiF5wq2SalSB4jO40rx28PH2OR5LDUPBZZ0dEUc5savcPnjAXSQA8yuX7iZ/BCZd+xpdPFfp1ORF2PkCaAHs0VvY6A9eQ8dRg8qWm6NtPU+xFviTpR4QFx/52EQV8aNMpn+emyeok/e+kjk/uu0owAosCnPauuPM43DPn66WwGmzqv5bUip5dk8dQZxoJtSwaIGuXipxAGwdObrAozaN9DZ7Wc08fZt8rhBNfg0W0ioTGyqa5BvRpYf9oiOgWwQ4murCsryENsDbT03gND1MQnQ6c6f5DAAg/KA7lZg3hLv7SQHBRGc/ocAoTL0io4VVC9XkCCqWxCy/bcyeb8RCQW7vJiVs4ctrsrzHKg1EcH90919EESDWXIYXjcm3DXqyAaqLMI5dpzmtZ0vnwav5oJw1rT6wrMSqDNj6KW1gPfDmsHKrF2vFPYhgeNqk52uLrB4TCAWO8i7mNFirw2tUQFyYAQAoxIdJuuvlGRhVrqQt1eFweJEAw1uoMjNpUKmWZ1GQhD0Q9ptXvMs4fl1LF7PVapz6dW4zjVt11FDJSsKlrcQI5QM0s1W1VqD6wELiwqV0L+lALZaKXH1mlQy3hXw8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODUxNTM0NzY3NTIsInByb2ZpbGVJZCI6IjI1N2E0NWQ2N2RiMDQ5MmQ5NDVjYTAzMGY0OTg1OTMyIiwicHJvZmlsZU5hbWUiOiJCb29mdXJkIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jYzEwYmUxY2ZjMWI3OWY0NjE1NjI2NzU0M2E4MzFjMDhjM2JmZGZlMTcxNmYzMzNkMTJhNjQ3YzUxYzA3NGRlIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I will defeat Megatron and the Decepticons.",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-5",
                "/carryplayer <player>",
                "/dismountplayer",
                "/transform",
                "/untransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 14 true"
            )
        )
