@plr = player()


@hero = associative_array(
            'name': '§6Or§0a§6nge L§0a§6ntern§8(L)',
            'class': 'orangelanternlarfleeze',
            'sig': 'xVI8zFeIcbKbUG/jNp1G9xtLlaXqMCemBYSbO2o5AtQi6/s7JXwATRG+jjwxD2haO5tZMU0FAnwMpSsxW9z7+j1pdELbZM4hUyfaxMeEMqvdJt/cPY7HFWzTnBBtxXLM1oe4WjohlpdQkL0KM8svgVdEbMdXUyW9xXN+0gAkgF/YYfEs8GM5zIirVi2tAPrYJtmac5oReGbLekuki1mtrLbEvQDWa2Yw0Ip3eMjT0nCRBwDT9Ix6CswzGf9N5lD8zGLNIWYkNcUp3MNgXDxeSkrGit6u8leKogIl3m4X15BFAaj3gCnuMhelRQoXTSioRMPqBndLFDdaDubrObeWAZC5aRHdknqQwIlHcgj2KYCMdtx7IbGAs48hdV2UG2npbDCP/c0dYtWQp2StBozLtIp7WQuqJpt0y5BZcxyM5pTy61S4XpxCsSnnXpxiwJcfkGiEiFH5o/ssyZPDrjgS+mYQhPxAX5mZr84qq3XFO1wJF3LGWiidoIuyNOsCXi8d2XUJ8f/zLWiKd1ydURnTcFm8uVgyMRgL9LpQgutlWZFxOXqlSARhXph1y2a/niSiqKJ6e2eDTMy/VgYwLXu/noqytiurefJsoOjlL/YCWfPiDGCgobdalYSn9mCaWA+fgn+k/NVcFUNHah+CCCJvtquKJRqs9JugcHLzWkcsxTo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODA0Nzc0MDEwNTIsInByb2ZpbGVJZCI6IjEzZDRhMDk4Yzk4ZjQyMTNhMWNjMGU3MGFmYzMxMjRiIiwicHJvZmlsZU5hbWUiOiJEb2N0b3J3aG8xMV81Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hYmNkYmY2OGM4ZjQxMzc4MmQyNDUxODg0MDVlOTZjYmI3NjY5OWJhZDQ2NGUwZTJiYzQ3NDkzZThjYTAzZSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I take what I want.....",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-4",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." orangeenergybeam",
                "/give ". @plr ." 95:1 64",
                "/give ". @plr ." minecraft:dye:14 1 20:2 16:155 name:&6L&0a&6rfleeze's_Ring"                
            )
        )
