@plr = player()



@hero = associative_array(
            'name': '§7Ow§bl§8m§0a§8n',
            'class': 'owlman',
            'sig': 'd9h5nUNC0G0olsoa4GRw7dF1UOgADn94g6Qqhd9rLI/cPzRC9BC+kHYQ3kQwWqkfnwJUd7pSiBXe08keSjzu5LSX39BqjEj6nxVpGdzxck0UI6VXsSVQBTLhlgwvJ64kg9GIiDrAGqO9da3JOMAjZQY39n161AdcMaFgail4XMPnMiZ0fh8tlgpE8LAhILtA3Z6ekP/jcRxvIGQqbMPgo1Gb22JEf7qPE+iT51rrDvvq1+KWXXscD16eGRs5IA7a6AbqRZI7MJl7mCHcThqlJJIzS1Hsz7dkdBtylt4zDYcjKxJLMbXgGZRl599ohGi13GISY9XWJf6jTHQj86QhpmDl28rpIQM4cdViderqgUTwH/lbPnJcysQzY+8r1kjz9AVlGlLf+Vi9erQz7Wasxi98s7lrXPNC78m0tWlaXd08tc0iZo+7KC8PNYof6N3V7XEllW0u+bMHItCsCwj60Lt6b69sza33Ie6lrd/U8+HrHjfxOWvbv7oSwk0+y0f8d2WWo2pJbVOB3bH+iYiHzcJRzc76Pnd5/mud8tSSHb+z3vbEpL8zEU3cf+g73DrzLpgb5L0OMCV5/zlU+8JJSSwPNjkMgcm+ZeP9eBbfzVMfXLNf7JOOeTiM3wTOLyLXpzrYPMKBNVuzb3D7Uoy/1IeI73+R8KzGH2QyX4YgGD8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Njg3ODQ2MzQ2MDcsInByb2ZpbGVJZCI6IjZkYjcwMDc5OGFiNTRlN2VhYzQ3NzIwYjUzMjI4MTVhIiwicHJvZmlsZU5hbWUiOiJKb2JiZXJ6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mM2ZiNzhkMDliMjIyYjc2ZGFhYmEwZjE2MmNiYjUyZWZlMmU5MTgxOTBkM2U0Yzk2Y2I3NDJmODZkOWZjMzQifX19',
            'trail': '',
            'op': 'false',
            'speech': "Hey look I'm an owl. Neat.",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-2"               
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&7Ow&bl&8m&0a&8n's_&8Glide_Wings",
                "/give ". @plr ." minecraft:ender_pearl 5 name:&7Ow&bl&8m&0a&8n's_&8Grappling_Hook"                
            )
        )