if(@plr == null){@plr = player()} 
 
 
 
 
 @hero = associative_array( 
             'name': '§5P§4a§8i§5n §8(§5D§4V§8)', 
             'class': 'paindevapath', 
             'sig': 'g14wvu4qfzDokpEyQN47c32IbliC6sk33/plFisPMjvKnfyV8j5eAOpMoPx3gNNgaF0vEh4gZE4hxJZ5JyDkK/zTqVLbWRhApvsxBnNRVzEPmkK0j4bR8/guEeBnPQqQtAucL97hnCW8gVJ1bgCasw36TO0++f4LVbbKFwYaOIXF1TFhNBNfVj/1EygSsuSrd+7tiPJgX18o4vBHOuRdJKlhtuxNMMsBz9geAkkQ4XoGkTz2V3xl0yMcTC2MmLxlbZgF1RbNn9OPVDYAjqwQWWDRR/+nta5AWHO7zkno8BzY7OQf+gpcDVSd9/QA0rde9ZOmZ48bjEiQ30Rl55Ubi7YMusg89emFjzBPJt72jUcw7aCUQXcanFbxJJHkweCBo8qu7BGH3udoPCsWRqxXhsgKko7u5qRo3elOtVLYk+h1kitMO1RtKhTEz2EC/N1oFRpeF3U31bZkvEUSs/uxXTlq6x5hE7PriWdV8TaeVwJVupUd+6x3M755FrT4iWAFmxdM/THOgamMhuYNDFS9HAB1upB3ymaav29DtOV0rfxS7JptV8XamW5LTU37Ma/aNMMoJAa+T7fdaNBa9yFh+ihD9CTp95x0zDf50SN0AZo+0Mp9UfFPKwBshO/d3m6TJAqZfpJv6dFyDPMmbIm8r6nomJnTl0O8JU2Scw3/94Q=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE1MDQ2NzIwNDYxMDQsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJUaGU4dGhIb2thZ2VUcmV5Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kMmZiYmE0MDUyZTI3YjQ4MzJiNDQ2MzY4NTIwMzQ1ZDNiMzE1YmU0NTBhZmEwNWM0ZGMyYzNiYzYwYzQ0OSJ9fX0=', 
             'trail': '', 
             'op': 'false', 
             'speech': "Know Pain.", 
             'powers': array( 
                 "/buff", 
                 "/jump 0-7", 
                 "/run 0-8",
                 "/haste 0-9",
                 "/float <up/down/pause/unpause/stop>",
                 "/haste 0-9"
                 "/wallrun <on/off>",
                 "Look Up+Jump+Crouch to perform a wallrun.",
                 "/cast almightypush",
                 "/cast universalpull"
              ), 
             'buffs': array( 
                 "/effect ". @plr ." 5 9999 20 true",
                 "/effect ". @plr ." 21 9999 19 true",
                 "/give ". @plr ." minecraft:stick 1 name:&4C&8h&5a&8kra_&4D&8isr&5up&8tion_&4B&8l&5a&8de",
                 "/give ". @plr ." minecraft:stick 1 name:&4C&8h&5a&8kra_&4D&8isr&5up&8tion_&4B&8l&5a&8de"
             ) 
         ) 
