@plr = player()


@hero = associative_array(
            'name': '§4P§ce§fn§eny§4w§ei§fs§4e',
            'class': 'pennywise',
            'sig': 'PhSZH8AkuBk7WcIyOpo7JuEBRwY5wshze0ILSlvaktmS4hBzy9FTYpK+myvT+m17YrQT6QAY0uVJPQk6l1azwM2DUd6Br7w01OSO0wfOkMufrt6THudZxb284jjw++k+uGH4V5Qxd0muUaHpFaTT3Dd1Z6De+MqUAfy/jKezdRKhAknwDlSJ/OI5ddjLzONBBtDZgyWFdnyfw3KT5/miqSBbNof3UkCT7tr/Rj2mwp8xK3ecUgzcGI93XZitnHYEO4VfKxjPvWA7CrB8a2KyfiLfeUojtHl2kzongh6BREEyYU5lq/xv6QflnrWEsz4bdCVqd/FmQDzMPCpvapBtYFCXpchM+rrLKT5lwT5JTU78GVaLceh+tzlkMMVlvT4W2UMdQIuhHORZ+ON2Fqa4N878DOQsj4TsKqovWT3pnKoGq4ZEgmQNP/7x/GXl2SdMMvIMiNGJ4kvXHFpybUQFX1aKDdkXs3ZIGqMaiMiMp7Fkuq8ZrT+hPs+sCWUZJu7BcBraSUpz1MPotYZcIovFSujdm+74vajoDdOI8nGISAXctcPhuYhdSEpCHQkUDRY/h98lOGS0qanFxam0haWtn+BTKikKeps+Q2by8pLAo6mlriTCpshmqpOYsosqif1O2d3dUfOUE0WAeyvl+kT3mKkQ5W97MaWWDIDw3nWcfZw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDcyNDg0Nzg1MzAsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDU4NjRmMmU0MmE5YmNjZmQ1ZTlmZjU1ZjkyZGZiNTlmN2E0YTcwZmZkMWE0OGQ0ZmY3ODZkMmQzOTQ4In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "YOU'LL FLOAT TOO!",
            'powers': array(
                "/buff",
                "/disguise p <player>",
                "/disguise <mob>",
                "/jump 0-2",
                "/invis",
                "/vis",
                "/cast deadlights",
                "/illusionplayer <amount> <mob> <player>",
                "Spawns Mobs disguised as the player you specify"
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 4 true",
                "/give ". @plr ." minecraft:iron_bars 1 16:6 name:&4IT's_&cClaws"
            )
        )
