@plr = player()


@hero = associative_array(
            'name': '§3P§9e§3r§9c§3y§9 J§3a§9c§3k§9s§3o§9n',
            'class': 'percyjackson',
            'sig': 'DoUpIAZ9/aRGQh9WohlhTUaNi6xhytUXaQeLgaj/dJPn/vfDS/lWs2xfQWUPzsEU4/RP7xh5WPh/VZfzMPJ2KFz5QHp5pzOLoEhxuu7xXuJ5toXFgzyUcQjHTPhwqvvr+jFBav6RMGKlIo8qScYTvddXZffbb0VCf55etlJlJ+OJxQ5l99TiF+9cTxHA46H2cFW3XV7l/oD/FFgjQbhQNMs3mu7w/boAD+qTfn1S6cD7WZUqlYUNAtPJMmMr4wsoRytj20+3rR9xdz6tGG0cqBcJo4o/kk1fjqOhHPN+2c4Ns5pDATAnzsS11UKAPoB4c0dYEW0BkayzCKJT4KI96SG1xKZXfV5drt3E2uqlWRFIrPZ1wfzAI5DrTfclbCSDK9sFw+dD5vMJGJrxYpTW0IgafmGEaSkwQQT7eX/GXpDsB7Nks/XOIf+IA4JwbQTqaMUkfyrIWuSPAJ9zentHi69GYzY2+zroPxLLTFu65ZfMAUNM7ocKUQFbZk7HMEzU2+8P5QBW3FixOhON8OE0RyxAuVFlljar7Xf+ZkTeZfysbOWV1WtZ7P8EN/zofIUzTkH2/mfIUw1+9aztiMmIRfi1xktUlM9c6OvciHzERjcce4G0j3Aq7cmyNg6qBspQhlecWAeWDOHRZPk5a6iU5iQicTsgHE3LaXEnUXtQmjY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk4NTMxODY1MjIsInByb2ZpbGVJZCI6ImJmYzllNDRkNGU3MDQ1NDQ4NjI4ZGY5Y2U5YmUxYmZlIiwicHJvZmlsZU5hbWUiOiJTaXJSaWNhcmRvIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hNmM5ZjI5NDRjNjdkMjkwODYzNmRkZmY5ZTI0NTA2ZGE3NzJhOTVjNmVlMzQ0ZmMxZGFiOTNmZGU0NjgwNTAifX19',
            'trail': '',
            'op': 'false',
            'speech': "Son of the Sea!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-4",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-5"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 12 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." watershot",
                "/give ". @plr ." minecraft:diamond_sword 1 19:2 name:&3R&9i&3p&9t&3i&9d&e",
                "/give ". @plr ." minecraft:leather_helmet 1 5:50 6:1 8:3 name:&3P&9e&3r&9c&3y&9&3'&3s_&9Water_&3Helmet"
            )
        )
