@plr = player()


@hero = associative_array(
            'name': '§6Pe§erf§6ect §6Bi§edo§6oof',
            'class': 'perfectbidoof',
            'sig': 'hHYIyt5NWRqBeyoV3QLH0a00Svvl9Rt/FoYzCVkswBQfvXXHpMOUqTAmMHpX052BsqfCu8ipadmITlTyWiztgqkWl6cVx+5Etnn9rbrGAq9Ke78W0ax1HC/54xeFpFJegXd7LUNkMev+4qnNKUQ6JW40Cz9Go/kQYiFVp0HUzLBjya6HNrTwtZFkpjR1NC6Ilz8CfemaknV55knKvn218Rbz4mslmQ3h4UnBfHg/2MX5nddxl5EGJENJaJC3UboX0GlZZwRqRaduXN9RctmMsQL/w5m22sxK6ShCcTPQp8Yc62HzXQSDO5hIoeIo2eBP3SpVd+44h+P7TFuTcyLXp+2mcLb3dhntd6CdmiX6NamFkssSVPSWmuGUlNdrNWJcaC72rIw8Oh7p3qv55P/KG3aYGabl0N/pL+gbZzNIDYybOuMwLkqL4cwerYN9lUm/ivra4YGba4LuY5Jxvx/ToDSpklSEEwTcMb6asQW2XibAXtc8v8xj6rmlrlwxVejF1sfM2HSlLzzSthpz50Xa3yfaLqSSepf2J/5W+HsjoqkUOQkNLzUJGAVh6YKyCeQFgiZ+BLPqoYOLcR6biHcGJvgOUP+yZcxGdh96tIvtAv360M3Xu/dsXRJYaywCGfROVOpX+OAdCekqXAHFqXZ700XkLpddbu1lGVP8UzHMjMg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTQ2OTMwMzUzMjEsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYV9SZWFwZXIiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQxNWY0YTk4ODMyOGQ4Y2IyMzEwZDYyMjU2YWM3NWE0Y2FiMTM5YzBlMjgyZDA5MWYyMjgyNGNkZWJiYzIifX19',
            'trail': '',
            'op': 'true',
            'speech': "I would like to learn Thirst for Vengeance.",
            'powers': array(
                "/buff",
                "/explode",
                "/fly",
                "/tp"
            ), 
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 11 9999 4 true"
            )
        ) 
