@plr = player()


@hero = associative_array(
            'name': '§4P§6h§eo§6e§en§4i§ex',
            'class': 'phoenix',
            'sig': 'p/NNKlWbnlK7zYuBSDHfZesGWUP/Z1TnGPzc18ZOVNS0m16HMxZXzpIUX7SAoMzsGfIyTuupyeVxg/kesollHhSET+sxM6ELC8OO5nHYwXBRkY6bCLNBo40+u09mf4c2bqMG3j/yHraoOSUrEXH09S9g3Lpq/PQC4Dw8S/yWjzPzQSoRmXgsSDrRT4vyclIyOqx+1GTObtMjEP3NtudJ2820zRDGkMTQ5nNRJaJ7JyPBEjj1GCkLWMdYXir4RE39pDGByQQjEJjkhQxz/KEwnFE0p4KSDEJdyOv37lLkOLkOWtgLnlYLUvN26lU2q/e99UDygvCtkrQeXuCxLRn3Podz4+TPCYmSF6+qNEO+kT74o2gmF9JqRQq0GiR9Pfy3J6P08CgcO0qPzsGKYeqQgxRTkeOMk132JzhHv1dFoSYsfVPmTPMJMnrZVVOKi45oJBq24aZe56Gokrq53lZQEJZSeJ67fdddq8x4utNFxuuigm13r5fKWR8kDPtczWGN8JLXF9g3lSwFOF09UKTkrn9cM3dz3kmKFhtSE0ZCK06g+GjZZBnc21pXQGaxyZ89ASoIb6frH19oZTwP6QqLiBTZuRvy6jaPadjZyyr820lchE+NGk3Tqc9OHFeYD2BS2yyWsA80f4Tlpq1hfosGDODFKKqB+JecPLllOvFwHww=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTM3MzAzMTM4MDEsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJScW5kb21NeXRoIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmUyMDc0MWU0NWU5MzFmZGE0ZGY0MWQ1MjgxY2U1MzMzZTYzY2Y4MDY0ZDE0YTVlZjU2YjMwNDU3MDc0YmQifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am at full power feel the inferno!",
            'powers': array(
                "/buff",
                "/tppos",
                "/cast healingfield",
                "/cast firebolt",
                "/cast telekinisis",
                "/cast forcefield",
                "/cast phoenixforce",
                "/jump 0-2",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true"              
            )
)
