@plr = player()



@hero = associative_array(
            'name': '§2Pi§5cc§folo',
            'class': 'piccolo',
            'sig': 'QuA2BR+ofNq7u9QeldNAuCK63CTQe9YL1sn9gaA4bD07EUp8tHmyfDBddq26820Dh0t+aE4ybc7TlZJQD6isnNb5WIzUmnUrruLil0kVl9y00WFLIaHx4Ypl+yibwZAu7sYZ7ocLibzjDhR2bCxigUTjB0j0xB/KuZcSMJ2HNztI5WbYcDI5ui+SmBqnQJAlEceowYSmKDOQOOVU0+m8q7GAYJQEEap2b0c35vbN3N4VfQFAZVQh0YWU3lBa6mcXE3NJyNv7O4Op8HunjXvC9mZDuYF2gFDMaOO3OSOyarKqrbVbHILcHveLIElVb2hOMCbyTYgelh0tY5qrq/N1F4dDF1Z+vfg3gI5v/O1P4ov0Fj+DeTIpQ4EHm0OgrEJEw8MRcUJJH/b2SUHQNE3GxR6etLfLeE1X9a3oyrG8qyuypyxrtMksVX4vBA+ZPGrvqb2girkOeBWXAbMIsbFSQ31VAePe42OtSyr7DOYTF9bZlwAkfs8zv1osCFn3Tydt24I31utQBKAOPgLHUePCo/l0FxNow3TIOeD10j7EnlD6wFhK6d+48NE/d9QPJ9FUvoflUdMSVp9pIrgvgTGKoPWR77FM2rRUt23TtS3SsW7Yd72Dgj0hroh/9/F40lQnOowEj+DWmMVEnbu5f9VykPjGPfLliD97U/0mQJ6fe6k=',            
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTE1MTA5MzQ4ODYsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJUaGF0Q3JhZnRMaWZlIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lM2UwYzc1ZTgwMmMxZjhlYmJmMWFjNDBmZWYxZWEzZGI1MTkxMDIyMjBjNzg3YjZhOWRkNjMyZWRhMTI4M2FlIn19fQ==',
            'altskins': array(            
                array(  
                    'sig': 'jArbqvt2Qsgh1GS2s70PQKhKQChtPK2zTY12K0w4ePJxBZPvkJD+mg1Mv7hI0DCkwaQ+mu/iSKMtCswlzLUDdw6hrJn39wGFbdwp7sSZzF2HibLRoijsfIoHAYVCczg43bs0Q8VLNr5Cm5Kz6smtwklhPLsc5zr45/sYA35PUA1RS28ceqYBMThxBeWYzDcC8vjk7pDcDiApQNaoImF8HhJN2dKVP5uApiqVtZgPL6vK9Kcl/8X5925T9excN3NHegoC4XbpzSC1Ep5flUzcOxal9vhzl4gIMp+2JrwPifTXwrKZ2Uo6Us/BZLTBnIYIoy7LMVidQpFBh3m4AvyxHCNYq/jPAe3SqIbDHRDMxpWVAT4AlgIBKVi491q3kfKmaKzsipaQDOXu2q/jQcUgods8phmPqcRPKYCqX5H3bGgiQbEsk4E9emCLx3s0sc4Cr4qzsSYXOWYcEEPlBIfDMdX1tjooxNW+M3Ntdmuvj0+1peBSSC5iM9Xpi0Y0nEFAaWyJ5cNnyrov7F9bxA98ucMyRTqRa8p0qwSXfwbPvxQvGppNThxLSudQ+wMzRrMR4wfSXblak8ya1ybpC659Kz7DvUGkrxS/qwskaet1qxUQVTi1hfWtnxqvAvIxFO+NxJXijWlUAJpEQU2v8nLLg4DrEicMwHG11xdEWJrj2UQ=',                    
                    'val': 'eyJ0aW1lc3RhbXAiOjE0OTE1MjgzNzEzODYsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJUaGF0Q3JhZnRMaWZlIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83YWEwMmZkZWQ5MTNmZjRlZjFlYmI4MTdjOTgzZjM0OTNmMmZkZWMyMWMzNzM2NDI0ZDQ0ZDQyZTU3YWYyOTYifX19'              
               )
            ),            'trail': '',
            'op': 'false',
            'speech': "I'm Piccolo!!",
            'powers': array(
                "/buff",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/fly",
                "/carryplayer <player>",
                "/dismountplayer',
                "/flyspeed"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 18 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 5 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kiblast",
                "/shot give ". @plr ." specialbeamcannon"            
            )
        )
