@plr = player()



@hero = associative_array(
            'name': '§eP§ci§ek§0a§echu',
            'class': 'pikachu',
            'sig': 'P6UXefjzmMSm6dChSDvqlVxdUFRMzSOR6NdZx1tCK7paDZRQHkKdD6RxITePQ5vIuCbU+9G92RcQ5eGy7NsW5gl4vSB6SS4MrpCg9L/0Vx8Yj/LGOJP1ZbiBxwQFH5vhgfBGPx1m1oS0sntCR0MwMm/FOGZFfkEp9KWfEeUmwZzDGn+fxRAgqhk+f87WvEhr8QiDo9e3WflaceRbKdvvu4IGZnvvFiP15x2cA9F/TIXY4CRTfwDf/PD/r6TU2IqFwn07kfPwNODq7qkyHp5/1QsrOaHRR8xggblJDIZO1L5+yGmtDRqXT4oIbKHU9FJt1CL8fNisKzH4m/S8fo30BqF+ru4spn+2XIhTFNVpvylEDLwZcnuSvqMtUBEQFF2LaTOrQpexGfXXNq04ywSjoQDyROKu8pjTQ9jK/5ehYx225uOz5kC05I1Q/OURYyV02FNgz8hJlJG/yEjBGjAXAzftLI3pUVYbmvE2k1TAXP/PfIcXWf+ryGJvv2L7EONPD6ZNg3v8v2EForAo673SPpuyFcrUXT5wEKdN4ut18eTByEEXsYl7RJuFj+AS4Daac9KesZll4toUMvBSGdWUwpMS6yqZI8t/0So5hE30BMIQXK2N3kqpsATVA6uLbNoC215/5Z44aYWbAnDiCLZ1qrbWmQud5iAkqBmKCnCjYWs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzczNjQ5OTkzMzcsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJXaXR0bGVUaW1teSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODkyNDZjYmYzZjI4NzVjODVjYjZjNTE5YjQyNGVkZjllMjhlY2JlMzcyNTY0OWNmNDAxZGU5MTQzOWZiNWYifX19',
            'trail': '',
            'op': 'false',
            'speech': "Pika Pika PIKACHU!",
            'powers': array(
                "/buff",
                "/jump 0-4"                
            ),
            'buffs': array(
                "/shot give ". @plr ." pikachuthunderwave",
                "/shot give ". @plr ." pikachuthunderbolt"                
            )
        )