if(@plr == null){@plr = player()}



@hero = associative_array(
            'name': '§dP§ei§7n§dk §dRa§8n§7g§de§er',
            'class': 'pinkranger',
            'sig': 'V6qzAEzKNkUsbvFQESG19hFSZGrCWglpVPxVxqkU4xSLHjirED99DzhPGQZmxz9MjKbiyvCT0udwvCv5oPkBsp8xoWjDjOQnH2ONeW/TWB8vcSWPY0rUFRwgWIHDAL/BRvsFS9piEUeGf1Q/sq3752vNNgEDUgsN6SWFL1wtznpd1qyF1rbafHs/29nk4LtOGVDmW63jvXLYWagDdKTFl4+6Je8UAM/MV9PTbbpi1JNawraRfS+agvtFRNIqcdnx8oaIO8BSFOtmY/yZ6To4+g/tjFKsPyZGnXiIukOu9QX3/e0QOc35mCNieR79Wgl2AT1ZMBFsvpuCRvcB2I6h2EPlFQ1L4veWjE2AMemGMQIogc7iZomBdB8ArSm6O2/j3ZSWeL5GOplZQg99zlqp9vow8TOkWzdyoc9OHGveppvT9cvB51rLrQJYFQIytFdUbJGqrzWDxspHtEOBVUl6I88mglWyIChZtl3M/IUoTabRxHgrZKRDchNKVz4wsKSfscMU6HBxRmjeVj+q22OQ10InBUZS3ATeyy+rbNr/xRBw1PbGJapvA7IeaZ85vzpxTB7YbJi5WlpelJJNGKwdX3l61FqykiNgcVibZ7nd4YiDsFpbf3s106xUk11nrpVaEXJ7HaFENIN7wbj0yxFezd3ESvxgX86+3I3jykKngKA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTE0OTA1MDc3MDcsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJ4VG9ueV9EQyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzQyNmMxZDIyMzQzODlmMzRiZDk3MzQ3MjFkNDhkNDQyZWM2NDZhNmRlNjhlYzQ3ZTczZTQ3Y2E3ZWY5OTQzIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "It's Morphin' Time!",
            'powers': array(
                "/buff",
                "/run 0-2",
                "/zord",
                "/unzord"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:iron_sword 1 name:&dP&ei&7n&dk_&dRa&8n&7g&de&er&d's_&eD&7i&8n&do_&dS&8a&7b&ee&dr"
            )
        )
