@plr = player()




@hero = associative_array(
            'name': '§aP§2o§ai§2s§ao§2n §aI§2vy',
            'class': 'poisonivy',
            'sig': 'Q6a5ROvFpH2yLZVqg3fYbKiOZACW3GURLEvDEbNXSW01qb9z/ayCizLsCY0NisUcsqqO2MYrH87vOobmpe3vLfWvPDBQOi1IEyFfoBB2y4Bp+tlwzG1jzBm4vFsxfFFrJn683F7VPaJwoKoHFNSBgLBhTSSIA05CHMHNKDu5uFUn9tNzV/bVL6EOj/vrbMun5P/kTvJ89A/JYC6+Vj7vx4Upch8LsjJ59cMISgzgOSz9Kna07CZKKPn1+OYVtI5mu50A2vZT7DMosyVE+u+4nvM4w7taBMV5/+Sk+g/AL+TFDWAKovwMvfr/AGwcQ/qlABcXJhQA336t3bftFHUUDAqGh4xsyM9SRs47ndpmNeUL4Nrx88VyabU9m/jmAFQQ6gI1L7U2pN3t+dYgI77v0D6bFhrZpxcCrAehQsb/s6jhhOwc0P0dfMrj5P6Yo1uwC8H3RuvDFGfwiaVmZjz+n3S/6zF/WpQGv3hALkHDwDtgbv0/IIfq7K0vc6LljI2D67fujV8LePXpu5LQCaWuVZTXuW+4vPyr6yqQGO1QAOlMUVNHdNM1fovKyRUVjThx4jQpLlz6y446FNFvCyOKA4i6NjVoCXU+33Vsr4WBbTBo+7gn9EIXlHivFBsZH7I0OGFrHYxUudPr5pOkwnusprFK78S8yB7DnDUuvaxuRuI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NDM2MDQ0NjEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS85OWI0N2RjNmI2MmZiYmMyOTRkZDk3NTQ5ZTkwMzYzZDc3NzdiZjZlZjc1MTc5ODNkZDM5MTM5M2QzOTU1MCJ9fX0=',
            'altskins': array(
            array(
            'sig':'r/1jBy1N3+2bwm8LrVhkiSQN+nvFt8O/Lv9ZWKuEm2bizbMNUYBXAY5d1wLKUtmzlewA88KQfdq2j6P+QQM5bae1ZzoIMu9UsYWl6cl5XUyoLB/ghCntggqHLG3cRSGCpvcq+v4to3cPvv+IZzhWsMPmSCx2eaK8ySAlAqAmzisCLVwAvLSzz6Y0Y0KdxWf3G8B0lcXxCKlRhauoyNVlCtWATUsjy6CqA7/+4ugGD9syHciDBFEGzXprpcEBmMY1aGX05MavqUIiaF/ZyMudJ2uPgnun8nQ7Gwp0M9fafubISLNw3hcicms1NGwvJDPTZlgoUOhPjcdzQdNb2mZ4PD27GcCPvBiNQ27PuY+xKntCEbPwZ/8xg4pSNKh+/AZsf+A2HxU0YNNaUsWf5Fcl13anXLudBqjt5pXS0DNrWInFH5xaPd9KL0S5gwzUO/vYAasCCqlwvkJvJ44QZGi6t41/99DSvxXET3GOa9ArV2hFDl96dpn94ONuhGQagB5C5WTOOW7w5V7Hj9o3dHiBYcxLfd3gBMuWS7S7b+Yjm7Uxpysngp31yHQg3XGqAMmbza0O5R5CJNWc1FYEQrpElYDVBZJtieZSMLCdGdwQoSpmK3TOf5XF0WrPbzlUY3z12aNnqt/qOMan4jueS4dNlsW8s+9riY1QQfU443ux70M=',
            'val':'eyJ0aW1lc3RhbXAiOjE0OTI3OTI1NjM5NTYsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJMb3N0SW5HYWxheGVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzZkOGU1N2Y2ZTY1MGNmZjYzNDM4OGEyODg3ODk3OGQ4NWU0MzRjODQ1ODYzMjVmZGEzNDJlZTYzOGUxNGRmOGUifX19'
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "I am one with the plants",
            'powers': array(
                "/buff",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/haste 0-4",
                "/jump 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ".@plr." ivywhip",
                "/give ". @plr ." minecraft:beetroot 1 name:&aI&2vy_&aS&2eed"
            )
        )
