@plr = player()

@hero = associative_array(
            'name': '§2P§ao§2l§aa§2r§ai§2s',
            'class': 'polaris',
            'sig': 'q/obJ/81RGKM0bc2ArHfKOF827ku+M73B2l3MyGFqHfA+bRNJ/BmwAWNYgmnA/lzctqzFGSNHNrhd3LAQM0n/O4uIPORhpn/ptw8wxhnI3MWVQGgHix9FStMpGfS9E0FaK77I3qH5EXU3Kn8hOd1n8pDjy9+y5YBctEXfTLOZ5xiweMX/6G2N3fhGjE4Pi4GaZJJYDHwaagvCpipYCJl0yFuGm1nPoDE/6X9xRKFx/c1nFhmx8Cf8MT9+DCMGt9EjqQHzfMygmfSP+nbZyKtk6JVrVVeieE7ncJ78lzbYEiHyTlohyu4AxPzXKfNON0kQoFT/ncT4ePUd8Z3OCPPVvo3rv6DSqCe3ncpc5YOJ/6fUvCBZTcx4BmF8OamyqXxw9jprMkW4xyCX1KWlXSw4Im5RbVqGHQHuJ/o6BAV3pBX0zEWwP9hKgT1gK5Ypuw7CBuHGHcclbmCWBQUPa1ON+yoh7xvcAOsHz+R9Y9aoozYoxZdKo9Cxrbxe91JuROP1RGjwwBEaqek7f0FWRxxsTx03UW45nHc4NW5uawxDLr8ZwW8TCER8xqk2LHCzeCcxyqH2cec11krTh0v+ywNPgNpKj1IJ+gIoGHIzjoIbpd2guFBL70cY3/2nPJC7ZGp8T+VisVg9WkvQLh6TT/vY/fDdT4HCR1wlKGX19LbfWQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDk1NTU0Mzk4MjQsInByb2ZpbGVJZCI6ImE4ZTE1OWVhZGVlYjRmNzNhMjQ2NTkxYjU4OWFkY2Y0IiwicHJvZmlsZU5hbWUiOiJNckZsYW1lWVQiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jZmRjZGNmNzk4OTQzNzViZWNhY2E3MzhmMTZjZGMwMzg2OWU5NzM4NmQ2ZGVhOWNjOGYxOGY5YWFhYzdiOCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "You will pay for what you did!",
            'powers': array(
                "/buff",
                "/ma (this is his iron attack!)",
                "/psypush <playername>"
            ),
            'buffs': array(
            )
        )
