@plr = player()


@hero = associative_array(
            'name': '§3P§9o§3s§9e§3i§9d§3o§9n',
            'class': 'poseidon',
            'sig': 'tszjiRuFykWGDmesqHb9EKEpIB0PSglX5Rz8d4wjaUEMgL7910r2dqD2whLygkbvYlfmWbh+pgNy4Hg/C/+kSFPVGhy2CFkUAwMLf/xXgAbafiASPy9doBxZQmwXQBTpsKisxYF55Uz+XC9G4ALZ/WUnzi+yfMuVWGocZRJnw4W6uf0lkyaJPPWHuGWJroNQkgpmlkAqOkxFhnX3ThLkfutie339X2D1YfyAWU6/pCjKtFcGrLWsNmgcXeB+wAQYwqtuvGUNMRr7IjMgTy2/G6Pr1qrnu8vd4YNS5mpEsqmqZFf6PEdsrrRsGKTrgmYABmd2OozvwgjmI5XqSscOEmbdxG0FzPXORyujuVuAEfQQreMlo9XQrQL0PXQscexrC6yQr9XR0RK9KL2XgyRhVH3VIwrFcNACpFXqbprcERd8HUJIDDRleEs7qGcaduqkdpwXqqxAqBtFG4WFavH4RPjtibqxj5hM8TreAmVJU9cG9YRboMBOrqbK9+Grwh4Y63jzaOwGerT33z+YSgJtfLV8kJkSibkxb7veFUJgSpxFEt8ahF669Cv0yNIm4Ai0vTjAeCJqYZZkTKMsPKl7dKUHj624Ay13KsyfnRZ/aWRMHvbduvZPatP9y3iBvJ6Sxch+lfR51TtJjUKfVogZJAchl37P+Oh7Owc9FK6hBMs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjYzNTQ2MDksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzllNGRhYTZkZDRiMjhiYzRkOTI3YzE4OWRiODQ4NDBiM2I0NjU3YTcyYmFmM2VkZDViMmZmZTc1NzJlNDMifX19',
            'trail': '',
            'op': 'false',
            'speech': "God of the Sea!",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-5",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-5"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 12 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." watershot",
                "/give ". @plr ." minecraft:fishing_rod 1 61:32767 62:5 name:&3Pos&beid&3on's_Fishing_Rod",
                "/give ". @plr ." minecraft:leather_helmet 1 5:50 6:1 8:3 name:&3Pos&beid&3on's_&9Water_&3Helmet",
                "/give ". @plr ." minecraft:diamond_hoe 1 16:10 name:&3Po&bseid&3on's&9_&3Tri&bdent"
            )
        )
        
        
