@plr = player()


@hero = associative_array(
            'name': '§3P§9o§3s§9e§3i§9d§3o§9n',
            'class': 'poseidon',
            'sig': 'tszjiRuFykWGDmesqHb9EKEpIB0PSglX5Rz8d4wjaUEMgL7910r2dqD2whLygkbvYlfmWbh+pgNy4Hg/C/+kSFPVGhy2CFkUAwMLf/xXgAbafiASPy9doBxZQmwXQBTpsKisxYF55Uz+XC9G4ALZ/WUnzi+yfMuVWGocZRJnw4W6uf0lkyaJPPWHuGWJroNQkgpmlkAqOkxFhnX3ThLkfutie339X2D1YfyAWU6/pCjKtFcGrLWsNmgcXeB+wAQYwqtuvGUNMRr7IjMgTy2/G6Pr1qrnu8vd4YNS5mpEsqmqZFf6PEdsrrRsGKTrgmYABmd2OozvwgjmI5XqSscOEmbdxG0FzPXORyujuVuAEfQQreMlo9XQrQL0PXQscexrC6yQr9XR0RK9KL2XgyRhVH3VIwrFcNACpFXqbprcERd8HUJIDDRleEs7qGcaduqkdpwXqqxAqBtFG4WFavH4RPjtibqxj5hM8TreAmVJU9cG9YRboMBOrqbK9+Grwh4Y63jzaOwGerT33z+YSgJtfLV8kJkSibkxb7veFUJgSpxFEt8ahF669Cv0yNIm4Ai0vTjAeCJqYZZkTKMsPKl7dKUHj624Ay13KsyfnRZ/aWRMHvbduvZPatP9y3iBvJ6Sxch+lfR51TtJjUKfVogZJAchl37P+Oh7Owc9FK6hBMs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjYzNTQ2MDksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzllNGRhYTZkZDRiMjhiYzRkOTI3YzE4OWRiODQ4NDBiM2I0NjU3YTcyYmFmM2VkZDViMmZmZTc1NzJlNDMifX19',
            'trail': '',
            'op': 'true',
            'speech': "God of the Sea!",
            'powers': array(),
            'buffs': array()
        )
