@plr = player()


@hero = associative_array(
            'name': '§fPo§cw§1e§fr G§ci§1r§fl',
            'class': 'powergirl',
            'sig': 'X32PYb+SAguFnY6jjq2f6ZROr3Z/1I9pkf3bNYuzhew3ZpwzulUEFySZtC29a6KOYU4vm877ZBMVv2/vDR5kbZrxhO4+ub0NmkwO7Suyg57rvdh9R7kn7O1i0xeTGiUIjJ79bhgcuut2yWRYXThnCqBHw7gFiBccN0uLKC4NMNnOYRCakYBDiirG4tlV4MDyhCachKtfyqRthggo2YM2BJ92FmtwCDHMP5wzBtniXrxHWe+VTa8ZQ2LCpyejoGHsXQGddlVUduje3KSp4PLo3I3EGPKNHl3LN1CAKOo+QWMjuDQvIwnplLHc9Y2vKdTsNRT1BLJ5IqgOR+8RONQZoBUGj3+LPdgTpG+xqC7ag5aDdVjK3sM7EgpLw0ktOlefPjo8VAIenEpUO+r6g0mD24JwZWQYUBtVq1xi7HFJajW1JS7LVAq8ITHX8If0OLlMQMnPJPuM3Q8QdP9vICgLyCBj9YulQGXP8DcLNzVp++M1l5XuISeZB2Ah939mqGJNQ4D5B7PoHMj0DoLhvyD4gNUrmx+NaXTrRbvqXA3dxtp4j6ASDQJquT6t+rNyVpA6uzEQth4j5rHo5w+EOZ4evTn18+3Mn5zKNxo46XhszD40q7QKXvmRVQO/b6+wMZwPzbd/FcNIFc8mc33rfwZdA+ui0R+qWWJKYSfDyvfI1o8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIyNjMyMjg1NzksInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJUcmV5Q29kaW5nIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hODYzMTNlNmFiNWMyMWM3ZmEzZTZmNzY1ZjA5MTRjZDYyZjg5ZTU0MDFlOGE4NjI3Y2U2N2Q0YmNkOGYwZjkifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am Power Girl! Kara Zor-L!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
