@plr = player()


@hero = associative_array(
            'name': '§8P§9r§8e §9V§8iz§9s§8la',
            'class': 'previzsla',
            'sig': 'VVBdN+jT9XEcvwpJUYM9ImlTYLNebJUWuVR2ZA6v1AjX5IQExjnrDgsmCrekoGySfNgJWjbo5XiohZ8YvOxM6dGe8UCXzB62/P09MIalS9nNjd0J79eu++4NHDGJlMFZbyC6WnkNJEgCkjOcPryAAwHmtc2tILCtkYhV1XCpTWyiPl2vW/c+1AFLs4B7LD4U7g9T1AqZ+QtSB5YyX7g5xVaW9e3VObrf3Atqp/a5uYDcaNe4jLIxl/HE8a9R+NSvE0EcZecTr36AjSBUtJj69b6pGi4pr1TrE4xnINnFQT8DGQ2yC8YpVxNYbQF0MvXHEYS/KJCAYgw51L1xaBk1EOfTwuclsnpV6g32Ta4IN+bOQ8XU7ReDxnAvjvRlfTZUv1X+nhjkfFU3NQJML+AlAghGBywdngA9PjFHriVkS2hBCzABAARJCMk4524bHQtvczXLPaefztNABM9Wj5DFaZdSyX0ukF3NtvOluIeuP4SecZkCQ4XO2OCmGYxYx1Arqa6DNtpnj2PbzqUC13OT6Z/GCxS5IPwnWAAK4JV5zDf5bXcZVw/0WRKjiJQvIBQ8EWun3g3XN9fJdP29HOjTeRB+82rLmQaZ77ACp276KdpzaAmo4ktQqcBe4dznrCvNqv8ZHac9vRDkf6OHw0c9fLlbtNnz2Rm0AMysNQAClDM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ1MDYxNzU0ODcsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWU5MDVjMmEyZjE0ODQ1MWRhZjEzNDM2NzQ0YTI4MWIxNTllZTgzNTRjOTcyNzJkMjhiYzhmMWQ1ZThhN2YyZCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': " Mandalore will be mine!",
            'powers': array(
                "/buff",
                 "/carryplayer",
                "/dismountplayer"
            ),
            'buffs': array(
                "/shot give ". @plr ." blasterrifle"
            )
        )
