@plr = player()


@hero = associative_array(
            'name': '§dPr§bin§7ces§5s §dZ§5e§bl§dd§5a',
            'class': 'princesszelda',
            'sig': 'SpYr59YF9bwhP6377zL8mk5fnY/679vKEeUJYtdirMoXmHW3JSxcfTaUQE2dU0O8gYTgxMHDmFRKd2njl16aKU5rlgnxRCHrbMKJeXXfWnFRiQlDy5h6TGoa5dmtEPMvaNuxQ7nS8jVgOW49l/5KQHZaHShI6mxVVfSzzcX4MtelNI0GnZxhQ2q/vJY+Vm8mofVuBipxnaxQnOFmNBDFSH4QhYHD+L+tQOXBqIlXRJZE3QES6c9CAIG9oMs9SSqLxjCwkv27OU3i/OC4h26VHINQqBxD8pWykkM145MFsuYESCfDeGH1x2rLa6ItaOOZnvGrb5DlF/h/GRjE46Z+HZym0DZsy/vDsDrPu+8Y++wCR/+gol1rsVGKPwd/uEKoRGtQVhyuCQny6VJi+TE2kO7UlplND2G906WKejJ2jJG/73DXZU6SaAMvppDms/W1V005b5VkIqOHL3kAlBiSDQJX9/fs6mWUvn2G/fjwdzQR6TMy+OXmiTXrX9if4EfqAtd4bXovGfHVVypxODnJRcevF4nOLgsRBw4Hchi03qlmZUCRQsZpIfljCW0McRq+g69GrX0R0MvGyDXUUwDNJ653txlPtQkojYcNPJyFtfNhQXixp+93BWDstckxx9tHH7fsULw6On2QdWzkVdVUmkgYRCJzWLwXZ89fwSkn1dc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTE1NDkwODc1MTAsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJ4VG9ueV9EQyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWVmZWEyMmYwZWNiOWVhNTg2MjNlZWU1NTg5NDBlMTZkNGY4NzE1ODQ4NDFiMzU2Mjk1MmQxOTVjZDk0NGQifX19',
            'trail': '',
            'op': 'false',
            'speech': "It seems I'm the only one with a mind of my own.",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:arrow 64",
                "/give ". @plr ." minecraft:bow 1 name:&dPr&bin&7ces&5s_&dZ&5e&bl&dd&5a's_&bLi&7g&3h&bt_&bB&7o&bw",
                "/give ". @plr ." minecraft:iron_sword 1 16:2 name:&dPr&bin&7ces&5s_&dZ&5e&bl&dd&5a's_&dSw&5o&3r&bd"               
            )
        )
