@plr = player()



@hero = associative_array(
            'name': '§4P§fr§7in§fce§8ss §fMo§8no§fn§4o§7ke',
            'class': 'princessmononoke',
            'sig': 'Jr4e6+Fard35REHhdud/U8C8HEUm1yaTUyQPrbHMs/K9qrKEMzwCBvywQ4YTapiqDZ/0qnaEi2jks2D7tcPTaxvzYbUH0mj6ex5wjjy1/VkuAOUW1XpJ0EydVIssw1h04mdDV7F79XFfUaMMMeK1Zj0LhV11G9mhUKrUVl2UmCi9B3zDrAYT8xwNUt/YqS9pkTwGO2sWzogm6BMbrDu/zAcNwZeZEWp5XI4VVwkISCNvaOb/HFeaoXyslqvlNkZD+q2MgIKa/fMvvx/bWVoA8knB7X0kE7zJ9hVX8CK58qGG/9KAamkPZUeVaJLVIC00UOXZjBUfIxYb8DyDkLi5GH2e2L2bpBQwUCWRnROnjxObSrihWKOJv0E/ov91Sbim2MoPMXLDVgS2vVxxVg6wGx9zM5rcJ8G3kPNLkLaFGNI3/AUYV8bkzr9WX4D906OPKeajvNnYZl8iIHXFoo1ATvc9zqpjh4IxQBnr5IHg3HGlD+7HPnJUz5JdK0Pi5Spy+4+HD28+BXHxwwtGLX+GF6sbBk4T4cDuV03u2E/L/VGZGoUvRB5aK8icf8sOAqv8DWSKRT2vmF0glS/U3F+eI2obefcms1CO0pJtK63ZAnbcJeXdADdUJnZmvxKFjTv85q94s2jUioi8rcjQGXYQfqgz99kdPxY0Bx7D/CFKgt4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzczNTYwOTM4MDIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zZjRiMjRiNjJkM2M4YjE1YTk3N2FiNTI1ZTE3OWQ4NmY5NDZiZDU2MzQxYjAzYmY4OTc3MTRhYzMyMjE2NjMifX19',
            'trail': '',
            'op': 'false',
            'speech': "I was raised by wolves!",
            'powers': array(
                "/buff",
                "/run 0-1",
                "/jump 0-1"                
            ),
            'buffs': array()
        )
