@plr = player()
 
 @hero = associative_array(
             'name': '§5Psy§8loc§0k§9e',
             'class': 'psylocke',
             'sig': 'Yi7w0s4b8+F9HSGU9YxIYoV1EtCJNBPty9Xi9pFtTdZhQy6SfD2J0/NK7eq7Z9eL/B0lKU+24vhKHK7wrGH9yv4OnLxdbX92o0MZAkUiBfuLtB0BX8s6mfDJn8ZfLUnIa9Sbl4Os7/0fHb/mmdhJU/33EBuBujufq8VS4UK9eqXuzkMF65bVuv9O/NYhC1488yLUoM3/p+daQ6vuV5LkM0HYN86y0YmiUpExgL6y5RubAMjXYOz3xcKZERVQdGXA4nTgePclcR6B1Ira8DTbmRlQ2tmDZGnzQwPcB7gHCgiH4pkB7Xj4reBEyK1VQmXUQxH6ij8fkgtXR5fdVmsSZTG8DOee73avKJKR332qzOilG3hpWwwXlQPT0AYGXHfz/7PGmFh2C2ltVa1DF+P/NkpVnf7bWYEvK8hzbDzyrZCMq4pc1dDFXBULR9JXNLVJX8jxrjBW+TM2Bb4MlwzKZXHwhIPRD0ui38P/MnULaScTjUDRdxLEGbJJ4J4Hk6gGk+uiKCWjzqy6YB9k5suks5jaJ4LN1OBWU5oGYpHbHxt2CYx48K2/Fk3DlBRBHgkKjdvDWKJ5oJQk3HfqAuJl1/My+EwEK9WYlvz9RrUX4JvU/i8xr6rqbvhmviwk9Di3ercTHQ9Of/xqkMRUeVmoZ7Wy0u5Eekc0u+jmrVlJkmc=',
             'val': 'eyJ0aW1lc3RhbXAiOjE0OTAwNDc1MzIwMzgsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJTdGFyYmVhcnp6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDI2MGUyNzNhOWE4M2M1Mjc4ZTQ1MWE3MWMzMWIyZGI5MThmMmQ3NzI5MTcyMmU2MjQ3OTJiY2I0NjhjNGI5ZiJ9fX0=',
             'trail': '',
             'op': 'false',
             'speech': "I can see, into your mind",
             'powers': array(
                "/jump 0-3",
                "/run 0-4",
                "/haste 0-2",
                "/psypush <playername>",
                "/confuse <playername>",
                "/unconfuse <playername",
                "/msg <playername>",
                "/mindcontrol <playername>",
                "/stopmindcontrol"
            ),
            'buffs': array(
                "/shot give ". @plr ." psybeam",
                "/give ". @plr ." minecraft:iron_sword 1 16:20 name:&dPsy_Sword",
                "/give ". @plr ." minecraft:bow 1 51:1 name:&dPsy_Bow",
                "/give ". @plr ." minecraft:arrow 1 name:&dPsy_Arrow",
                "/give ". @plr ." minecraft:lead 1 16:5 name:&dPsy_Whip"
            )
        )
