@plr = player()
 
 @hero = associative_array(
             'name': '§5Psy§5locke',
             'class': 'sylocke',
             'sig': 'JIUpvUvHW79Zxd9owz+0OY7KqnTik5Pf4RCTtFX/ZFb16a12Lm+IEKC4tygS6gDe/XMqBjN+/bQa0UAKlkq08JZgE5Vffw5cxhd0eygeVbBHd8CUgC9tEABtNs+lYlHWtKRjArVVjgDr7fMde6fco96hoPjBYd/2Ncozwi8ztYOPn93z8P7dUFihR32TNQDwwy4uf04zcwh64qeFBmWdecabUWbF2x3LiBLwJ3YsHQAfNffnwZUKZuIXuV2LUuYlM2dbP/xx294k7qiNGusbUNr6e6GWkSKvBZi1MbFW7hmcXYcgajlbmZwMMw/tIWzn+Zj6ZpY7zoXd9Zcft0lSlSeSTPTGgdFl1y6bZLMT0zU0edXR6DvHmkscTglPKC8TKeyO7GlDJIK7/QH1no/m7LPGywGvIVf4ESPWIxP3Qh51RknSIFRZrbYz+xfr3pyIeFo7dHM/4m4f/99RypkJctMAb+W3ZnikfrnXHk3IvNeiIUIMuS0PwxH8Ewc41TzThXuM+PxIoe3w9vYRRPDlcNFnNvJbQ5KpLBlx01ArxjfmS+bbP60Mze2TMQ3UwzkL24Bt/tOfnIfq4d/LbjePguAFk6h49XBYZD33wqSpQICscTE6Ui5K++NMNJSjEHov1k30AxBIZsZiiD4J5F7tzMETLgFXvtI3sLuY2Swdr3s=',
             'val': 'eyJ0aW1lc3RhbXAiOjE0ODQzMzYxNTE2NDYsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWIzODM4MzlhYWZiM2UxMTJlNDNmMWMzMjFiYzk4ZjYzODMwN2VkNDZmODI5MWM5NDQzZjE1OTcyZGRmNTg1In19fQ==',
             'trail': '',
             'op': 'false',
             'speech': "I can see, into your mind",
             'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-3",
                "/haste 0-2",
                 "/speak <player> <message>",
                 "/mindcontrol <playername>",
                 "/stopmindcontrol",
                 "/confuse <player>",
                  "/flyspeed <number>",
                  "/fly" 
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/give ". @plr ." minecraft:gold_sword 1 20:30 16:20"
            )
        )
