@plr = player()


@hero = associative_array(
            'name': '§3Q§1u§3i§1c§3k §1S§3i§1l§3v§1e§3r (§6X-§8M§6e§8n)',
            'class': 'quicksilver(x-men)',
            'sig': 'diScE1aLuZrue/P/m4maVFw23PqlG3phOqgY4SpHjy5BmF/yqx9BCChhzIXRwxn1UM6DBMxg4NwPBin+NR7Pysk60dxcHxBUoQxBn6v8KbuLPh/NK+IajWONStExuSGXdo3lN6os+W6QP3Xh9cJy0GxPTkIvRPdpfJ4amguDBKbiqIFBrwqtOC63F8yQkXK5WdNLpSM6lto5yyWJuwaAmclNH2tFUE0CD20cPasmeLX0ATAuksY/c5rbAsZXBB8iZ8ZkXicb3FhEpWwMbjDChpJbz2Ps72zl/HhT0iPgA4+flu5SB9ONzdvLzjpVUVr2pyWE3DstPt+w1V3ykEO+2dTKIzAcGNEYca0F3OFb3XcjTt/40YCpTYbJX5QguVixN5CCEE4VfHQXK952WHF4IwQMCkk7wssgTYoadqc6zffPX3LLoemMiEA2hDvhyZRSOdTupT0pRsJOPwMCtM93nGn9NgGkMN0UVgrdJaEeNZnENxQ2R35o2NwIcdRwWOHdawvq1lFo35LlIzKN8HjksRTiCnVDOO7i8Doj9nA9kbSnJk0AQDGACppFs/eS2Cg9byKoFvbgGiPZa1SZXX4hSOGjuTfVlVBmJ2wolDLOL6CDwSWN6HEdgOpmXYySSf9FXsASsHjdt9c6TPbbzp8naebgAWSV++d8YMc2lsn8uus=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDAwMTIxNDI2NjIsInByb2ZpbGVJZCI6IjllOGNiMmQ4ZjQ0ZjQ2ZjI5Y2E2YWZjMGExNzU3M2YwIiwicHJvZmlsZU5hbWUiOiJEb2N0b3JXYWZmbGV6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iMTZhODczMmQ2MWZlNWQxNjQ5NDhiZjBhMzE1NDIyY2E5YjNlMWY0NDY1OTY2OGNjYzc4ZDc3ZWQ5NmE0NTY1In19fQ',
            'trail': '',
            'op': 'false',
            'speech': "Prison break? Thats illegal, you know.",
            'powers': array(
                "/buff",
                "/jump 0-6",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/haste 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 12 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
        )
