@plr = player()


@hero = associative_array(
            'name': '§bQ§1u§9i§7c§3k§7s§8i§7l§8v§7e§8r',
            'class': 'quicksilver',
            'sig': 's8+SwI5GaD6E3427AmVm2l4Q5KnAotJ7j/h8jlRMLK5+7xHUZBYFa6dxT++jzyM4sLrrGtV0/JeulbUvFf1au4PH34MdXrsOHJqBcuK9kT0q6QS1tdIz6c49PaNbJTaX5y3o9b5wXeMh038H4T5RNqW10jQEBf6eVItG5MznUVdCgAmUhfVl3ZMbTklSVQ50Spp3xofvjGmOo8jdtAX7FaoOEVbKz1UxMY4DdssOvihDLG3Vt0IebV3u9GAquATQuRk6NQdtUR1ijIqttV9VljuL2FUuI+8C/mTr3JgLyZke9EKt2XA1cfYwcm6rMYY59OUU66rviOmTRojh+t11OLhgsvc7DuLzCMEK+I9hYOHBk/7CxEvguwBoSt2Pzu8GZnRMGo+P9IpoPAhe+6pQPlTfJBBaqS/uixDEcPkPmO7nUOzRCUQBoESdrJarGswOiYQxgAQXvemDPo2HDvV1j97TONaf1GyGXwodIpvx4Qjk4nBpWh+zM22Tki7dRhWca4ttNMboJnnggardogp0fRhEeePxGjxc2ZnJeGBIio+avihy1fs7RcfT6FCn7Rz4E3H/M9WyGm/6ym7t6P2jwUSADojjO0mrwUZKIGZvW3vA4awLZDfLwU50KupUhUUJhhaUsATVC1LtiupvljE2O/0UWH/dGb51JHRyhQZQ3q0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ0MzUwNjgwNDEsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJhZGFtYmFzaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmNhYzhmNTViODQzOGU0ZjI2ZGI4Y2UwNTJhZDFiMmU4OWZkZTNjYmU1ZGFhOTY1YWQ0ZGI2ZDYxZGE5NWUifX19',
            'altskins': array(
                array(  
                    'sig': 'Tf/fHgsv0QUxT9rj0GOYP1Y67K5Q6npHeBSmfo8HLk2V/L5mIXWRhK8GmVWKSCs/d56ZRP6QBh5hlaLd9b8Eg32FvUJCc2/zF2uRFOMsEoTL1VZgmJKYC1B+yxUa8cixE9TZ9uZdR3NhfrSDXImhuWsXKOqDxgqULxngWfFM4/XRdMOWIBc/+6i9fH5OFfV0GvQ6ZW3tzNOXdErcnE0KdaKg1/F8ZGJQIjDWYFawYzSEA0DKmIk+55Kxz8zdx5Y36axbmi1kpUPDexYJXvIl5XgJTuf3F5WF9kREqsR6/oZVHsUIKexz3T28b+DmFy/2iNBsL/bnSaJ17EAGf9XTdAcGIwsJWtmt2nh1SHrZ9u6Fsw08TqwwWYL3tmbJqJ8otjhKseCpdXbCEZPwPAFvt5qGldLztNzywV+CAUs4C+fmbnYWjaAP6jmRW+qasw8lS2pmSNCpLyTZrgj59XvZO/9rJgOoFehSYOJg38TMVCpoASfjKutaPXdjNrnvpLHInXAYJaNZqDzxMdOr910NyAUcXK/+lVkcb2BC3f+Pt/A4+tOKEspIIoPmydTEDUEhkbujgzgz7O84DMm3RO1O5TDDgbjWr63mVzPi/MbAW5m4LuclYD4hXfsdGsQGPvfdWg8TW3SVsn4QdSRLvueFpMXbqPmn1CS9Tut+2gI5Xck=',                    
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ0MzUwNjgwNDEsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJhZGFtYmFzaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmNhYzhmNTViODQzOGU0ZjI2ZGI4Y2UwNTJhZDFiMmU4OWZkZTNjYmU1ZGFhOTY1YWQ0ZGI2ZDYxZGE5NWUifX19'              
                )
            ),                
            'trail': '',
            'op': 'false',
            'speech': "I Am Not Ze Fastest Man Alive!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/haste 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
