@plr = player()


@hero = associative_array(
            'name': '§bQ§1u§9i§7c§3k§7s§8i§7l§8v§7e§8r',
            'class': 'quicksilver',
            'sig': 's8+SwI5GaD6E3427AmVm2l4Q5KnAotJ7j/h8jlRMLK5+7xHUZBYFa6dxT++jzyM4sLrrGtV0/JeulbUvFf1au4PH34MdXrsOHJqBcuK9kT0q6QS1tdIz6c49PaNbJTaX5y3o9b5wXeMh038H4T5RNqW10jQEBf6eVItG5MznUVdCgAmUhfVl3ZMbTklSVQ50Spp3xofvjGmOo8jdtAX7FaoOEVbKz1UxMY4DdssOvihDLG3Vt0IebV3u9GAquATQuRk6NQdtUR1ijIqttV9VljuL2FUuI+8C/mTr3JgLyZke9EKt2XA1cfYwcm6rMYY59OUU66rviOmTRojh+t11OLhgsvc7DuLzCMEK+I9hYOHBk/7CxEvguwBoSt2Pzu8GZnRMGo+P9IpoPAhe+6pQPlTfJBBaqS/uixDEcPkPmO7nUOzRCUQBoESdrJarGswOiYQxgAQXvemDPo2HDvV1j97TONaf1GyGXwodIpvx4Qjk4nBpWh+zM22Tki7dRhWca4ttNMboJnnggardogp0fRhEeePxGjxc2ZnJeGBIio+avihy1fs7RcfT6FCn7Rz4E3H/M9WyGm/6ym7t6P2jwUSADojjO0mrwUZKIGZvW3vA4awLZDfLwU50KupUhUUJhhaUsATVC1LtiupvljE2O/0UWH/dGb51JHRyhQZQ3q0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ0MzUwNjgwNDEsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJhZGFtYmFzaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmNhYzhmNTViODQzOGU0ZjI2ZGI4Y2UwNTJhZDFiMmU4OWZkZTNjYmU1ZGFhOTY1YWQ0ZGI2ZDYxZGE5NWUifX19',
            'altskins': array(
                array(  
                    'sig': 'Ukz9sawdaRJjMqnsHT9TiGUWkUZEd/0heImH8lkPhmVMxf7Z3UT2DVL1/qCxYsuTbIs9xadz8JNELiwayEjxuNcffgmjbhA1wsARs84sMThPCs1Y1lLkoXNDKEcM9SbvKsrmOEMqrsN6S/O4lvNMT5bHEHAO8ZEns9YWjA2G8yPJDxEyqd/LApy621eYUwx3mXr6hvql8bMD5Nf9n7R6C4agcPUNbFot6KRaY8oJug+IPWvjacNogWv2TPHaFxgB24HZK9PBrsMtW6uASxhwrGk5XP2CoUxl+IB42Ubg4A1Qz0kcsrZqZ17e/3Y5CC9Et9tc69d8SLprSmZT4It5kNwI0h8ntl1EXQ8Lw5Uc2YRJNN6jGo0Q4IE8dao2zjs+MZDpK0YkThlhga+EI4uN9BpXtQ1MEqKDIW0RGJ0rowvh1R9cPURDNmf8yVb0tktNC31HRwneJoP3qyk5RTOb51cr5LyNEqoCne6NwaR/t7N4yWc4LC3VDIGJOpswu1yiC5M1H5NnTTlFa4I3MnwMXKYeNQmPz5B3LkfcUMJM+8fMK/iuBW8q580ZK9RLVCmXf3Yl/uJ82JvotPlMROhS7jvrDRpn7w38EHLXLUrrOSDDbyOuYB0EI5V++tvTNt/YckF4CJKuesRq4rtjS0mPPMtlaDAEdi82j3E/qX5WKts=',                    
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODc5MDM2MDQ0MjksInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJNckNyYWZ0ODg4Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82ZDk1ODNhMGY3M2QxZjEyYjg2ZDIyNGZhOTdiYWNkMjAxOWJiMjhlNjI4NThkYWU2MWYzM2NjNTEzN2ZmOTcifX19'              
                )
            ),                
            'trail': '',
            'op': 'false',
            'speech': "I Am Not Ze Fastest Man Alive!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/haste 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
