@plr = player()



@hero = associative_array(
            'name': '§7Qu§8ic§7k§1s§7il§8ver§f(§cX§6me§cn§f)',
            'class': 'quicksilver(xmen)',
            'sig': 'fW541sF3qqAstvuTjd6OOa8EaFiLTP1fZ42uIQrNCIb7mmKca6OQCScXxcPARx1Rx7IFEZCt9heg2xjMrjv3dScRIxdP3AU9tumz806u83m+v/1tsfAQXfXogjrl+exv8tA92jLe3T8Y+u25Dzgwlrd3y++hWxZcEhburyNBi8fFyB2K2JKUOafrpzV89oeBb9L5lvMl6lZqteI3iyu54E1nQVvJ0abvoVDuEdA0SsdkBjFd08CuDbxP9NsrJzlReFPt4FjtoB2Q6TNdqK7SDgaGFE9Pbd5wulzl5GhHLu9jyb38DOATmcKrlfzLx+2v6gEM/Ayu5hhba4DkzAWUK3QWHNyxaAHzvM/0FhaiZFc5knw1/hkho3zAgzHsTUFQ2TdtHAGCoUTxCY3fIlVQ1fvXAdAGq4E6vJCmH+iOBrJ0RLQ3qSP3ePY17+Pwe/Q5gbYHkh7VYdNYJsV2jRKmaSySpJDa15qhLEZX5yWUzBMwFvaY5fMGMlVdZpLH7PUtq6A6xDZDmGhoJDzuX7h0MdehINKiBJxzGVmAziY46Oi66p5q0G3lYjkUufO+xzcw/xcDsSRHqpdURpNzTrwKfV+OyZ7g2KO7o8+cp1IzJf2Eefvo65tk+ohYSQqvfFhLPqX1aeGZuJBGv4r0Dt1eivnSar6I/cydBlixOJqBJ08=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODc4MTQ1ODAyMjQsInByb2ZpbGVJZCI6ImJkNmY2MjIyMGI3NTQ2OTg4YzgzZmExY2EyYWZiMmU5IiwicHJvZmlsZU5hbWUiOiJDaDFja2VuIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xY2IzZGYyYThjODcyZjdhNzk5YWE2Zjk5ZjI4NThiMWExYmQ5YzgyZWI5NjVlNjllYjU5MTM3YzNmYzY0M2UifX19',
            'trail': '',
            'op': 'false',
            'speech': "Try and keep up!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/haste 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
)
