if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§7Q§au§7i-§7G§ao§7n §7J§ai§7nn',
            'class': 'quigonjinn',
            'sig': 't/aF2dCh7LAlK1ATVX1FPMoESwO1D23ycLc/dDhl7PNwNSSDjy5XePJZZY/dRNKOuXZP9Pi2u5a/gkf9JwBv4GqnWLVfuyeqjOQvbA2ts185GCRuTRrFLoB0v8qaY5hdiDplJcBlpJ/ad6xM0tq/lIaUpAZMgJaks77rw2nJr1n0OM1BCXE/YAtnKkpeDLQ6R8t5Snvg+sSJjI9D3ZKW8++nO+FJFaKhHDZ8qWdtfSUqNAv5Q7ZohO3DCm6nUj0tHLXddEP/LM9JLR8ckxPut1MgDevrwxB+GXW6QFHvbeh/5W8NXvHOCYT7AUFNecX5sqcVXPK9Bhp/wJp/+Tuy3IjnvsA1OoOF29l4Q2uw1EgC7J/5qm7ZXWLrElWqim60HehH4ZNoxvwGrBvZkYgyp4PB2uTU/M7HEB7i/+2JcznIlaTeZ2stCeiwfZuLJZXhkjbR+csl0jcxf5A92edr6J4ngjC20keAErSWceU4V6PhnpE+FNCbnECGlv6+b3w9QEr+eE7GvmCKemmrciFVnyE6LG2AeYRhS9C4j9zXUpdrm0A1r+qDqZR597upaWr6XOjXFTLs1xsL+vTzG4ygjtNnbsxRlCel4IBBmRtv3ujIRqznsMLFwkfIqcEeEMuuhoW1xZZ9lBhY4wU0tEge1g85QW12nnEe5dhzHChAJqU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDczODg0OTQ5ODYsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJIZXlJdHpUb255Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80OWY5ZGExOGMyZjJmOTU0YmI1NTU1NGJlZDJhMjQ0Y2YyN2ZmYzNmZjRmZTJjMTM4MWQ2YTJmYjg3NmViIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "May The Force Be With You.",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_sword 1 20:2 16:100 name:&7Q&au&7i-&7G&ao&7n_&7J&ai&7nn's_&aLightsaber"               
            )
        )
