@plr = player()





@hero = associative_array(

            'name': '§6R. M§9i§6k§9a',

            'class': 'r.mika',

            'sig': 'fP9AByF6nafDm6tfBSe1UNNYQSSN4UCOe7RaaJ+7czB6emiu5b7+vl5jqSEIHY2HzDlz7Xzid6tS4qPjmon+6t/iW4/AFIbzrFbCnPrygeoiGSm9/7MZBh/xX9d7FRradSPHRwy1FL22c3/YnzMYjMNJYpcpzYfEKttlkVEPPlp4bCRbdC2uFeTtECAoJQQ7BozAH7Y10cjKri0MOuj34Kes6Fgk07N+zA/caV9/5OOnEuYPj/xCJ3WhIofBdGHGYDYPQ+sMdHmNxTbyK36GibOsTReT4dLgJ/PfCw0vyuHsiRju0aSlhtDEr/KPkjvphkG/D9T1pOf9wYtjAlD986MSopxS7fkWkUziWtjqunRwpkcXesEyjCoo0zUPHDZ7C/Nr4DeLe+hYjhUqfqKFSOH54/BwZAZsJFNeO15AZeM7qgwITLgyfDdtzxYqw0nHwcRdSMXs5vSwX9Agh7PdEAbUVKobkPG6IX6An/p+yfcjFlEyTZjYvB/7s1F6IqGUOSgzWpa0cWLXbTWZScG0ul611sPd/xc4SqCJnFQ08syMuQuQy+9Nr53kWy3QgKm2L/2qqsVL7RPIKOTgaA103FwTbQF4Lz6FKeNp3p/nhwXDYZrnynCuNHPNGUmhaVv8aCWc0RoZyCL4CFC9Mk7Sy/j8P+ckpUfkd3X/kTKZ2nw="
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk1MjYwNTc4MjcsInByb2ZpbGVJZCI6ImRiYjQ3ODg3YmZiZDQwZTZiZmVjM2QxMDUzZWEzYWZmIiwicHJvZmlsZU5hbWUiOiJEX1RlcnJhX0MiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81NDE0ODc0OTEzZTZiYzU5MjM3YjQ4Njg3NjQ5Y2U0OTVhNzNhNzM5YTE0NmYzOTBmN2JhNDQzZjhmMmNkOTFhIn19fQ=="',

            'trail': '',

            'op': 'false',

            'speech': "The Superstar of the Ring, That's What I Wanna Be!",

            'powers': array(

                "/buff",

                "/jump 0-2",

                "/run 0-2",

                "/carryplayer",

                "/dismountplayer",

            ),

            'buffs': array(

                "/effect ". @plr ." 5 9999 3 true",

                "/effect ". @plr ." 13 9999 1 true",

                "/effect ". @plr ." 21 9999 4 true",

            )

        )
