@plr = player()


@hero = associative_array(
            'name': '§dR§5a§ep§dun§6z§5e§dl',
            'class': 'rapunzel',
            'sig': 'gvi4KYklnTPjyF3EocOexEZGu099vqpRUofbX/axFUKh5WzIvRG9u621pkPNmgy7nyjtBCTu91Hd0OBTjuTVozGjaGaHZ2uLOz8uWlYzNfFXZRKBpkNVQu8zPuw+FsoTWQVGcAa3JEiHUVnEU+Cb2m3Q5uKneCFJvVwKYoGxkPW+7R/jvs+oBITkny3R9oNe9/b/9bxL1G26VXUaRna2jb62b09ncLX2oPWRTo1Zeb8yGpN/NbH3AqOPTxekVowcPCX0GyUq9gpl/rEY/Y2J8gIrP4Kjy3RFBj56x80FRxyMlkpSLk3Frt0NWFcPYwbDmjB96qoAqxteQ/Xipr/wj0mEm18LQtd2VYkdGQvPnmcA77tsNMr7qo1VRw5bzix8/qDUBkB5uOFIDpwIeQrM8rgTMQQOb8LHs052r3v0oOiAP/CozEhYUev9UGYij94FdLYX8NZOStCY6ZXFWorAAn5XxrP7whJoUMHCh1/4zi9ihpwPvzy2STpgO3KxyfQXqNTkdujbKpfJaEtRoaSpLf1sNTrI2sEJErSMIDCoDnDo5AV6x7By966RlcYEihORZGGpLeu3QnV2sAj0fb/9ps9nvmFuHdPboEhjuhAbKjKMsV/1rvjqlUsESg11J7SAM6vxXGAYRtTMTEyTDwPT/qc+zVzTL8xduW9S6oYKpKo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDQ3MjkwMDI0NzEsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJpaVNpbXFseVN0cXIiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iZTYzYzBkNjU0ZmFjOWFmNGJjNGE1ZDBkOWNhYTU0YzcxYTgzOWQ5MjIxNGZlN2YyOTNhYzI2M2FmYWRhYzcifX19',
            'altskins': array(
            array(
            'sig':'lp24Do4psW/xc4GGKUokBqp+AFClB8wAuZeYFRywZIIJrXYHCjVXbI+pO2BohB7Ga5EurEfGBvZuzoRE7eA7KjEdePPbspVhl9hKMUEiH6IaukgTfexNVCOMEEmBFASWYMNqv2cOHt0Y0Hw7ZFZUOw8FHz2UkMoDC682j12SYTCi1TvDnXLr4l8VCzv6K+qmqiHtRirL7RPVI4A3Z5AgQCz5kil9622LOUv9cnh1fBfL47Xvh58V4n9YJP3QYTbTCVuGcCumjUsyJFKU4LB/DYLysj3Lre+fONh/DGxCl6VqQ2M/ccTZTEQZMZ85etBZn5hx3Wm0ExVHQePlWcEuF8VcVlgLJ/IxMnRqE5CV6KYQV0KTigmpEEv+1ok/cpoXGVQMYpixsAht4Erwl3x2enUnWI0xOGYUced+LmzK4KLBZDOdyKMMgXJLbQGYLtvxvUHbhsDZYrCefz42m4fjmSOgSBmZlUdZFQIV4t8RpomHMtNoMd/1WRpX6xyp8WHObSmReRJcSAYDfwc4NcW2qYjE6x2Vr+PnQYRKTA6Gfq4lmDraKPxiIgieF5pjmBredT+uwjJXcCnbZ/feXOBtQrgCstvUksZY9F7zGaj3ta1MUJbAXUSK1KswAUSRRBUEwjw+ddF72U76xrGWoHpjw/OrekhM8mfa+JKRGoC6BMw=',
            'val':'eyJ0aW1lc3RhbXAiOjE1MTcwNzQwNDI4NTYsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJ4U3RxciIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTg5MWRhZDlmZjMzYWEyMGQzOWMwMjFhMDllZjZhZWY4ZGI2YWRiNjBkNTMzZWUxZWMxOWFmNmUxZmFmMDk3IiwibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn19fX0='
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "Flower, gleam and glow let your powers shine heal what has been hurt bring back what once was mine.",
            'powers': array(
                "/buff",
                "/jump 0-6",
                "/regen",
                "/regen <playername>",
                "/carryplayer <playername>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 16 9999 1 true",             
                "/give ". @plr ." minecraft:iron_shovel 1 16:2 name:&dR&5a&ep&dun&6z&5e&dl's_&8Pan"
            )
        )
