@plr = player()


@hero = associative_array(
            'name': '§dR§5a§ep§dun§6z§5e§dl',
            'class': 'rapunzel',
            'sig': 'fMOihZ213uryd2Q9uVWHCOg9twezqW4gQYnjMHaZ/c3pvZyrhZtTLJ9UR249P8DHzzmd+ApS/ilIS9w9K3yNI/R+U34K+H6Qodmp67oPF4zCGfI6xq7bySXjb8qcXXkCvQEI56O8vjVxpHb5Ig7VmnhOJP+LXFdf0DEi2nG5gXmRRe39ENvKPOdRSKQxhCGfnPURd/n7k/waVeFJRH+q/xs0TVbvi2BfMa49hd2h/RBg2Utz+PcSQ4Bj9+ElTVFofwHACjvTegxOQbaS34+Kd/4VjHI+MT5oseYveBuOFHRh1fQQZusc1v4EMLMG4psuJ8mk5yn7bze26MECcYr14UHYzaLzKUU9MsImBkUGFoeTDBzaE0f42fLhpsjtE/dUTPj/TgSMMSZKhT/PJCfiVpW5xAfahtQjjn2+xCVJCX5DztFOwHOCbu0aTKFG/GOjfY+988hjqIDaX/AyHMIRsVGSeGiwlOPh0A92a5aBmlx7sCo80JGzX7nN16YvA/h9Q4+dLlBQRIJVjfDrIgBBTTayvsfKvayG3b0dfh1MI4YRPmDPzZ0vw5Mhhd+8TJLE+4SeFhmmah3AUdVdA4HKCNyK/i3+9rXcp52LwBakfQFNXe+uKZZekdUescbz7yKihJT+CMtnOhdsOsYuNVEB4hZmHqpJQbRuvlyMUBZ5Oj4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDQ0MDg1MDk5MzUsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJpaVNpbXFseVN0cXIiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xOTZmMmQ0NGIzZGMyNGFkNDI3YmFmNWUwZmM5NjdiYzllODg4NzRlMDg5MzM3OGYyN2NkMWQxOTJlODYifX19',
            'trail': '',
            'op': 'false',
            'speech': "Flower, gleam and glow let your powers shine heal what has been hurt bring back what once was mine.",
            'powers': array(
                "/buff",
                "/jump 0-6",
                "/regen",
                "/regen <playername>"
            ),
            'buffs': array(
                "/effect ". @plr ." 16 9999 1 true",             
                "/give ". @plr ." minecraft:iron_shovel 1 name:&dR&5a&ep&dun&6z&5e&dl's_&8Pan"
            )
        )
