@plr = player()


@hero = associative_array(
            'name': '§dR§5a§ep§dun§6z§5e§dl',
            'class': 'rapunzel',
            'sig': 'gvi4KYklnTPjyF3EocOexEZGu099vqpRUofbX/axFUKh5WzIvRG9u621pkPNmgy7nyjtBCTu91Hd0OBTjuTVozGjaGaHZ2uLOz8uWlYzNfFXZRKBpkNVQu8zPuw+FsoTWQVGcAa3JEiHUVnEU+Cb2m3Q5uKneCFJvVwKYoGxkPW+7R/jvs+oBITkny3R9oNe9/b/9bxL1G26VXUaRna2jb62b09ncLX2oPWRTo1Zeb8yGpN/NbH3AqOPTxekVowcPCX0GyUq9gpl/rEY/Y2J8gIrP4Kjy3RFBj56x80FRxyMlkpSLk3Frt0NWFcPYwbDmjB96qoAqxteQ/Xipr/wj0mEm18LQtd2VYkdGQvPnmcA77tsNMr7qo1VRw5bzix8/qDUBkB5uOFIDpwIeQrM8rgTMQQOb8LHs052r3v0oOiAP/CozEhYUev9UGYij94FdLYX8NZOStCY6ZXFWorAAn5XxrP7whJoUMHCh1/4zi9ihpwPvzy2STpgO3KxyfQXqNTkdujbKpfJaEtRoaSpLf1sNTrI2sEJErSMIDCoDnDo5AV6x7By966RlcYEihORZGGpLeu3QnV2sAj0fb/9ps9nvmFuHdPboEhjuhAbKjKMsV/1rvjqlUsESg11J7SAM6vxXGAYRtTMTEyTDwPT/qc+zVzTL8xduW9S6oYKpKo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDQ3MjkwMDI0NzEsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJpaVNpbXFseVN0cXIiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iZTYzYzBkNjU0ZmFjOWFmNGJjNGE1ZDBkOWNhYTU0YzcxYTgzOWQ5MjIxNGZlN2YyOTNhYzI2M2FmYWRhYzcifX19',
            'trail': '',
            'op': 'false',
            'speech': "Flower, gleam and glow let your powers shine heal what has been hurt bring back what once was mine.",
            'powers': array(
                "/buff",
                "/jump 0-6",
                "/regen",
                "/regen <playername>",
                "/carryplayer <playername>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 16 9999 1 true",             
                "/give ". @plr ." minecraft:iron_shovel 1 16:2 name:&dR&5a&ep&dun&6z&5e&dl's_&8Pan"
            )
        )
