@plr = player()


@hero = associative_array(
            'name': '§5R§0a§5v§0e§5n',
            'class': 'raven',
            'sig': 'oxyw1FYbZ7DIn1KW6ew67Pqq5PiD//ITNSOHEJWZHv4c2XaotFdKrat2s8osBKTXWF0dcROvS+cvCWM5xVwA8YIFcNZ1biLHu0M15lv8gzVkKPTCIoKC9n19U3fhPz3Mg2cV3YBryqLZCaeQQGZX2wlorpqE2BHj4LtmjTPGzBymoVBLGO6RpZ4u/IbOP2+S4FDXDfkH8H8ytlCVkOHUNc42hSpb95HbqByUcdz2++/gyQKVhVIKnuzl8bi241BRGIWmqlglQvELU/+GGKSrkzOe/uEy4Hpv2fJS/ftWTJRSbQ6s30V3Y3mcn9D3ItQLRPW3WHb59G2lThNuR9cDuJvxfL4S2vOLOw7gy5WPL0lufFZUJ8mGzs0LI0q+tcj3sijtxos6wpfXc6alubJB1HdGEUHLpGd/CJZjIyZVGKuS51A4LpPLgyjZlBHjsvdCmXJuofku75S19f2oz4WUfUytmWrW4Vie/DbuXqFFZfEdvtc3bVnz7qD+k1pdVSq0ohSL1dEhIxVU2OAPktAnlsHtlKTMiKB6F2zPm5i1NuqlYCgroX8J15EiYbHh49kR31cz10/BkRnelT2Ul88+gUmkMz9qtpaqrg64l5Q5IP/+my7vVwZ1MC/Wry5ZNGLRyyzFJH2z/jUXXokCsznGES+Jl6r7eubOd76U2asuYZs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjEzMzgzNjksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zNzQzYjY5M2ZhZjEyMjM3YmU5NTY2ODg5N2JjNTM3NGQwMTM1ZDM3OTgxNGY3OWYyMmI2YzViMTliNDAzN2I2In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I'm not creepy, I'm just different...",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-2",
                "/haste 0-2",
                "/fly speed <number>",
                "/fly"                
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." darkmagic"                
            )
        )
