@plr = player()



@hero = associative_array(
            'name': '§4R§8e§4d H§8oo§4d',
            'class': 'redhood',
            'sig': 'P0PRODVDuiPXCSouTUgLfL92DbKbNrhYiXD8yyuQPwUDgvAbU/z7wwMk481JWqiWhbNQpzXQE1O5F0mIaTcW+pqKSE4tXtBWda+yIPCtyh9pIf3RYFB2KeM1SRGM7s74//zc3tEDIPf2tpvg95O0BqM/1nKsu8AnP8nTYpjDPH6QfVwB2W76i+YIMYYIRmGhmK2W68s3b0RNPpyGHO78yzNgpPkGGB4vqhz/RTGq62jX66SubR0m3Eix40jJ2cEF9ua9gowZv5x7XhM3Qz9gxF4muEpRdlirPRMB+vyWZp2io3TzSJAZPhTU4ssRRVkbpyiYXd1YvIyYaCrlM33RcVrsQOc4ReVPuAbK7aLkryK9AshqH4QF2kSl7FXQlGMTutEvIYFI8YGYNsS1AKA/Gr982IkbjLp8KwmUsDUbMciz/IXmewcjJP3PbLQrk7cvwAaBNiOz6J5wuRFZSEMfvqUtS1KWCZGErL0PynVGc6CCy2tICuEn/Vil2eDrS8dwzsMWGYh/2XwLWF3der8LTf8ng7m7m3zQd6v/vzOqhTiRzEdw8xGkK22ueGDXZ3mm00nt/tXXThM3/S7greuMqpwnukZpQo4IttaG9dIf7dVfAtFFTpmDsSPyVrdOcvj0ipbU+yd1XNehJO2Uim5vDVHdjeLlFS90nbC1lphWwPs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzczNTY3MDIzMjcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzg0YmRhZDVhMzk1ZjY4NDBhYzM2MTExYzI1NWM3ZDg2NGQxOTAxNzVhZmJjYmVhYTNmYjIxYjhjZGYifX19',
            'trail': '',
            'op': 'false',
            'speech': "The old Jason is dead.",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-3",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&4R&8e&4d_H&8oo&4d's_Glide_Wings",
                "/give ". @plr ." minecraft:ender_pearl 10 name:&4R&8e&4d_H&8oo&4d's_Grappling_Hook",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." AK-47",
                "/shot give ". @plr ." Hunting",
                "/shot give ". @plr ." Python",
                "/shot give ". @plr ." Putty",
                "/shot give ". @plr ." Grenade",
                "/shot give ". @plr ." C4"                
            )
        )
