@plr = player()




@hero = associative_array(
            'name': '§4Red §lH§c§lU§4§lLK',
            'class': 'redhulk',
            'sig': 'TpIUngTSIlT1asLG+hApoJxoy52+KjcguxXLpqSZV9RI8kec91nc2dp+teIBblrRh1rtgunERLAga9rsPUGl3g9t1Q77XlHXzIhuwm3flHvA+P695BM2OVcYSUoUG5b23UOwNXdlRSEJnpmfVc3teeAodOZ8K6pEKnXE65idVsxVKLC4k7yBFmdcov41ahgdmfULineQnoQ7sICUZdMLY2cjsbbSTKXlj3jcAWxq+6Q8I70Fcjyw1X4zHOffID6iJN6QPKv7Dz4b9/t5b/I/HQrRXzI/hF1Byl8UdjO3Os39LYwyGflD+wvzdIneV/MQl4DANyuhN7UeVJUmfajAoo3kWw+9NsAqHkaZZB22olPK+ze2kcJEd2UdRmjbZxTf0nM6krDRMeiRSaGzfj/7i0Km2FUgkWLWFpgESstue3MnP29i+Fx7y9Ect4DA0it+bOw9QNYv1jJIzRqC8kV6rOkrdvGVfCOURNTDnqCJm4PvAEbJxFmcwUEiJ/3qUh12m8M4bu1VOjEdY0YG4u2E8jb4oqIf7l4wDz0NBJvQShxcfjpR6K6+GRuAFWmLgWVQjwn1rRlzLXjxEvnYLTAxkmrtWUaKq+YcFULOeyFXhtQZG4u8/FHPQBvITqj+OUCysjLb4WaqIFh+uktAqZpTrI8Vh6DzuGXIK79cAlicqoQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzUxOTE1MDAzNjEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFjNTg5OWI5YTkwNzZkNmRmYmZkOTZlNzYyYmIyOWE1NjVkYzVkYzg1ZGIxMzAzZmI4NDZhNDZmZGU1NSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Only the best hulk.",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-1",
                "/haste 0-9",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&4Red_&lH&c&lU&4&lLK's_&4Glide_Wings"                
            )
        )
