@plr = player()


@hero = associative_array(
            'name': '§4R§0e§4d L§ca§4nt§0e§4rn§c§8(§4B§8)',
            'class': 'redlanternbleez',
            'sig': 'Kzi9P0Ysf0ivgHMFJOmc8doY0YukN6JZeRD/NemaAOEM2YDirOZgKg9c7CgTbb6yZv7U+HhFfXmgH3Cdue3JyHdEnzthSj6u4AXUOLlXGENMnXGB+xKQ4XsnJt6h3AMqgPIGfUQ1ls09FW93SQlg18F9kxj7AYPKzR32AxflgUoH+RBxrd7RgNemQHPQPGV/3dvfdjxsiZ68ljcTBWs0IC/9QwmVH+9m/ZBgGF3Jm+VEmcEtrk719vtaljWX9oN5GfBcoiKzmeUulErM+D0Omxd8hKTB1fwnjV3Ga6PnuyhmpsUkebRT0NEdt8Fpya3/g8W01cDTWwKfhsPUGUIdZxUD+vti4Vv9mjkgK5l7rpk4jpAagD6rf3DJ7LxixWxd5pkufG5VeJJEsnVE3nUelUwfQc6MTcgzY+UuBgfwGNpo0ABHBG8ygmo8+0zLrDCKfRXJTWWAFsRuW6GwqkzymQTGO6X3Bem+0uNIY1OeqLaUnzZW6SpsZIdQPwfK0zpH2UgHhiD+j6qlUdt13zVS7VWxeUZartW9nQTg8i1ZTX0W9xeTPohhigDLe9Asz6L//Q6BApjr9KWIaN6Ja673zxB/3nIJiSRZh6bJGiG7EVV56hhzC81lWPw4uWm2vAgbvoDqJh7U7Jp0uMu/rnyY0iabHXlxmxv3SJtKbCsWHvk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTExNjQ0MTE0NTksInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJCcjBrZW5TMHVscyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Q5YTM0NDVjN2FiNDljZWQwMTIyMTFiZWFhYTgyM2E5ZTc2Yjg2Yzg2Zjg5ZjdkNDUzMTJhNzJkMzBhNzg0In19fQ==',
            'trail':'',
            'op': 'false',
            'speech': "Rage.",
            'powers': array(
                "/buff",
                "/fly"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:red_flower 1 20:2 16:155 name:&4R&0e&4d_L&ca&4nt&0e&4rn_Ring"
            )
        )
