@plr = player()




@hero = associative_array(
            'name': '§4R§0e§4d L§ca§4nt§0e§4rn§8(A)',
            'class': 'redlanternatrocitus',
            'sig': 'xcFBetoiqWz26eZLmFHRfEi/QlRcf9cN+RLtIDJ3uWyIYTcH/+diX6/KwIBMb7dMUMFd5Ytc2imm9qxYGmuPFop0UDhQzutBCz41YA7lAHEBYVNnnw0MGj11MMUnqOxLwjj5cawJFs7kLNNLMKeL0BiupatSLjXOwdir7NYY8+QjUkI3JcYXIIx4FmfefsRlR/GA8zoWfmqLj9W8cEcagk5O4MJfycp4kT3qFeMXxYKqQZxecwSvUkLsdVYFbhB5j6Q0TvbuPZo/EjFZdvQizJRT/J6Tir6MUXJL9+Hg2CgQnGxscDlJDxH56iePOxlIUJcqD7Sm7z6CW64eMqNcMGio7V+YWiqQqOK9lWZ8ilzgJkYL8GcOdFnjgu5LenYBnk0dFbD8CSSNfRcB0hLfHLyJfzEFsmCCfhIPqODrDFfpMdF6PpSkX+AQTCt1AfOONSP2wDj94ozSwb8VYFFdiTOoi/P4vrnMHuDFOwPEevyhb1BLdUX4MVWcaQtIqQgseNx7ah+1wQYjK2hF9xLxsytOwFbNHss3mnL4Y69Tz+c5ky6c6svP234nySjf8jqk3XcswUkurPu3ckiyKxkmaAqfxmhV3TbK+UaCeNla2RQrKYoSue6AObqWEYzeKmjOI6MyRy28sZYHTa6Fk00PcGv0/ezNzau5iKn6Hi+a6hs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY1NzI1NDAxNTcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzllYzkxZjQ1MGFhOGZiOTRjM2Q5MGFiOTM2OGZmZTNlOTJiMzUzZTNlNTRmZWZkNTI1NTNmN2ZiNzNiNjQyIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Rage will Rule!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-4",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/shot give ". @plr ." redenergybeam",
                "/give ". @plr ." 95:14 64",
                "/give ". @plr ." minecraft:red_flower 1 20:2 16:155 name:&4R&0e&4d_L&ca&4nt&0e&4rn_Ring"                
            )
        )
