@plr = player()


@hero = associative_array(
            'name': '§4R§0e§4d L§ca§4nt§0e§4rn§c§8(§4S§8)',
            'class': 'redlanternsupergirl',
            'sig': 'Scu4J1lEWYFqxs1pdFU5LlxSz4UC8HbEX6lCYU6jmZ+Rqn1cAiW/8wy019YRIa4MCyVpu/KbjVxq3peYqSWI8QOc+K7dxNcqHcatowAfSMA6dRF4VKjpOWWyp4Dr7/y6zRTZ2PsuKVUQPS97XOuEiO/1fXNG9PcHhUeS0QqTYzwkaV5GZZIMTRrdoLNHofvK7mdB51tyAgyRHskVvJ+2OPvPM56YNPhtSZRxBR6oBqlLI/QYIB5bV1qscFqGA5xSgwm4gmS9B8PqCx+BV2B4j8XDYGkNTRH7Xf+Wy3VNchi6wDb0PAbdKTUbIEmiVKg8wvGj7aiuJXOQP2e1cA0cIDViHzDrkydWhaQbnjrj394q1be/Mtpys2pNUGeVX/+YuSOJSdeF7r4LUIcdXuejCyh39uGdHZf5PEXwojfAA3BeDrxdZr01B+vW/qAg2nOr3hJ9QSRD53uDVAQ4VGtxrQmJNQEchZ1E4YhlnZB4KIU/DPVcWX+pyQp5e+jjiHF7pcTJSgxlT4ClJKzFxCtILY0E4yeiAmH+kl7BS12ZjcBEFzFEvfpVQCynCeM1/WIzSuPRHrKiR2nWCAceUYOUH4RxNTtoJBLzqcW+pAO0YRzarkZfQ4zbcQrtbixK7dCSA9h16SxhLUFSH+SIP6zMGb4A+fwfQ4CRlnxZR56eJCY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk2MjI2NDExMzIsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJTdGFyYmVhcnp6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWVkY2YwZTJiZWU1NjdjN2Q1ZmE5ZDc3M2NjNTM4ZTE3NzY4ZDgzZjdmMWMyZjllMTIwNGMyODFlMzY3MjUxIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "GHAAAAA!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-8",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." redenergybeam",
                "/give ". @plr ." 95:14 64",
                "/give ". @plr ." minecraft:red_flower 1 20:2 16:155 name:&4R&0e&4d_L&ca&4nt&0e&4rn_Ring"
            )
        )
