@plr = player()


@hero = associative_array(
            'name': '§4R§0e§4d L§ca§4nt§0e§4rn§c§8(§4S§8)',
            'class': 'redlanternsupergirl',
            'sig': 'SFgaYyMrfnstoys4EJcKrGiqpcfbKBvMoDUOcNIHHINUQEkah4W0MqeCzXtmkG4zX5ixNRWFYOo7/M0iuMqoSn0nxuf/jOk8xdd5rLc8CHQewbtYfLWMUGmFL8OkOhhNTzVdLvhrvYj6IVcl+kefA64JCqS+xuDDth88PUV/OTU2M4fjXvuzDkG7ONL/C/QIXSiFKoymJ5h9RTMBhd0/8yLcjxjRRzaCheOmzub7NkrCXOBCM455lMcRsoU5V1Vpx5YrZybhqOjgg0Gjat66dJxqTDLYqNUWiS8QJdyeIuU0EK3ZvVS7VLSCkbRf8Z5CyZ4dLakyUHmcqUcyEhOVEZhYbmY6XGDcrsi4BA5N7Dm+NGNyv4e7x6nY5XlLv0Bqw24FYdvJol2QvpMk2RlMx4CBn0vDwOhEXQ6QneY6kAGeq60wkKLSFt7wzsxLv9FuXMyRzm/iKoNDtfugBtSNtkKMAhXScbPWjP3CoVfQKgHbWrtunNdXjXbjCGHOAywe6Z/r4oJhX7IR+0GTswLj8w9hCoelrr0xKUlqqIlijX/nIJz0c1LqF7xA1V/yLNkNQjaEkyEiLvE9DRITb+hlR73ns9X/sDrUazAeFp4iuLBWem4596dCOqUYMjMSPs2WCVkr06Bpg5q/b2M4YREoOMnRvR7cm6ELnY9V9JkR6sE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODA4OTYwNTEyMjksInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mZDgzNGE2MGY5NTFmNzQ0NmNiNWQ3ODQwNGRkYmE0YTQ4Y2I2MmE0NDNiZjk5YTAyZWVmYmVlYzc3N2NjNyJ9fX0=',
            'altskins': array(
                array(
                    'sig': 'irJLLu7nYh4099LTNbsEiFdxltmf5xgXkGWlDHjUztD6za0yGIPkKZ7AsfVqAqmISqHZpPXtgkbmqKQ78oTTtM5wSiRojQvitCvuWPJHWdXcg/5QIsp1XHGaFjFOlF2ghZeraANnzq9n8PtKN4zeuTOyX2OGgjJ15cUGPzX+vG2wNNkh8JoSerEB+xYUOhopQUyDKcORX5hMLRev3E+IZqazEjEzYLmOuo+YbrzODStAn4KCI73IhwXaZy2BpP7OthV0ZlkXZ4UBvMKfGc2SM7+bClD1bbASd1qYTE4bCAveq6PdlvX5FgoVNBIR6f7z2p32twoAeJHHNYry8nBmLukjj6z/oxU/VnkllvynPrr916M6jy8ysC9oV1VVo2Ndh1SHXBHtIy1SU9COI+dggHzPGlkSk/AWoO7euHf2vfnle/gaGFTx0m7Re2YDzDSfa48uLrUS1H6aKPUVttxlfrAv6kEJfFzAwhsMS8w5lAC5+uESqMfIBqX8+YgszhTUi+G6mwSnFW1gCRHR4RgFbiUU0T49vvCV1yHYLcZFwC7dp++Gu90ePjzB+y3Ko9bAq7Qc03RktciuJXkBIj8LKehKvxlo2thhfBfWfD96hr7wSyd3QOLf3ADvGVMg9SgG2fMy5EAvWdlxOs0ng7rVAot7iBWozDmuW7dO0ZHHIHQ=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODk2OTYwMTk2NjAsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJTdGFyYmVhcnp6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzNhNDNmMzVkMmY4YTNlYzc4YjBmODkyNWFkYzNiY2QyMWQwZmQzMGI1ZWFiNzMwN2I1ZWZmOGJlOWMxNyJ9fX0='
               )
           ),
            'trail': '',
            'op': 'false',
            'speech': "GHAAAAA!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-8",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." redenergybeam",
                "/give ". @plr ." 95:14 64",
                "/give ". @plr ." minecraft:red_flower 1 20:2 16:155 name:&4R&0e&4d_L&ca&4nt&0e&4rn_Ring"
            )
        )
