@plr = player()


@hero = associative_array(
            'name': '§4R§0e§4d L§ca§4nt§0e§4rn§c-§4S',
            'class': 'redlanternsupergirl',
            'sig': 'SFgaYyMrfnstoys4EJcKrGiqpcfbKBvMoDUOcNIHHINUQEkah4W0MqeCzXtmkG4zX5ixNRWFYOo7/M0iuMqoSn0nxuf/jOk8xdd5rLc8CHQewbtYfLWMUGmFL8OkOhhNTzVdLvhrvYj6IVcl+kefA64JCqS+xuDDth88PUV/OTU2M4fjXvuzDkG7ONL/C/QIXSiFKoymJ5h9RTMBhd0/8yLcjxjRRzaCheOmzub7NkrCXOBCM455lMcRsoU5V1Vpx5YrZybhqOjgg0Gjat66dJxqTDLYqNUWiS8QJdyeIuU0EK3ZvVS7VLSCkbRf8Z5CyZ4dLakyUHmcqUcyEhOVEZhYbmY6XGDcrsi4BA5N7Dm+NGNyv4e7x6nY5XlLv0Bqw24FYdvJol2QvpMk2RlMx4CBn0vDwOhEXQ6QneY6kAGeq60wkKLSFt7wzsxLv9FuXMyRzm/iKoNDtfugBtSNtkKMAhXScbPWjP3CoVfQKgHbWrtunNdXjXbjCGHOAywe6Z/r4oJhX7IR+0GTswLj8w9hCoelrr0xKUlqqIlijX/nIJz0c1LqF7xA1V/yLNkNQjaEkyEiLvE9DRITb+hlR73ns9X/sDrUazAeFp4iuLBWem4596dCOqUYMjMSPs2WCVkr06Bpg5q/b2M4YREoOMnRvR7cm6ELnY9V9JkR6sE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODA4OTYwNTEyMjksInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mZDgzNGE2MGY5NTFmNzQ0NmNiNWQ3ODQwNGRkYmE0YTQ4Y2I2MmE0NDNiZjk5YTAyZWVmYmVlYzc3N2NjNyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "GHAAAAA!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-8",
                "/haste 0-9",
                "/fly speed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." redbeam",
                "/give ". @plr ." 95:14 64",
                "/give ". @plr ." minecraft:red_flower 1 20:2 16:155 name:&4R&0e&4d_L&ca&4nt&0e&4rn_Ring"
            )
        )
