@plr = player()




@hero = associative_array(
            'name': '§4R§0e§4d L§3a§cn§4te§0rn§8(§3D§4S§8)',
            'class': 'redlanterndexstarr',
            #'sig': 'G9Q2dxMl6/4DQcjXGNnfHVgKhS3WDSIZEAfpcDRWcZ2nqDCZxbQO74Fb1MxATurbvxvqayr5XYscRC/Xq1EH/v36TQRkxDKHMQAN1m8FX2nuUU1395Lj9FLj0C30dKR8Sive91i43agiVrHOFZRh5TEHLWBIjrHoMnjdTLS+o/FQSC4X6e5FA4Cbiq7ybptQQWwJcKAQU9yQienUPwy11srFXyInkvak54aWcnwiOGhx1nLtt0kEkwN7N5TT/Ghub5hwVnErpkxxwgCJG5lf19wtAgcqJm2bsK/3eLHaa/VOXaBYBOn+d86mn69ZIYs6GUYIRE5Qu2fmFNrYlUtLRfL6SCNvXl7hHk1aCZFL6zVE2Mo73b+VXN5L4/W0jXf/5QXNoyVcY+vB4ysvX/xeIJOX+58557C+6/CP1rEEPm5P4Xur9iTRPPF+N29dPLALlAVA/IrFXEqIvfg+ymm4gnjBrUlb69o0IUgtIIT8AUeGzozJoQp/wXUrGXM4yNcIjPKSpQqVIMC0iGO6rspcAmZ2/RdWppZ5CqHkd7MShTU83X3YHt6K3bNqAem7GjzasZsase3C0ppcRYViRfd2MQOY1SIp2DFvD+AQK4lhK/LQCpYDuZJWgr6yLwHxWTdiM81AoUUghHRY1lmpgo3f+3kwP5T+KCXZwXp8Y2s8pw8=',
            #'val': 'eyJ0aW1lc3RhbXAiOjE0ODE4NjY5MTMzODEsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zNmQyMTU1YjljOTFmZWM2NzVhMmQ1OWNhZGFiMTIzNzY2YTVjYzllY2U2N2IwZjRkNTkxZmE1MmEwYjliZCJ9fX0=',
            'sig': 'ocelot',
            'val': '',
            'trail': '',
            'op': 'false',
            'speech': "MEEEEOWWWW!",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-4",
                "/haste 0-4",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/shot give ". @plr ." redenergybeam",
                "/give ". @plr ." 95:14 64",
                "/give ". @plr ." minecraft:red_flower 1 20:2 16:155 name:&4R&0e&4d_L&ca&4nt&0e&4rn_Ring"                
            )
        )
