@plr = player()




@hero = associative_array(
            'name': '§4R§0e§4d R§6o§4b§0i§4n',
            'class': 'redrobin',
            'sig': 'XDUm8U0qtQMnjSde0Jw/utlQjMssUGXFXfniOz0rsjEY90EVKJaJgYhlW61m9M8LQUxFLPTfcpncC6Wpzst9GEjlSf5Fyg1sWKFxMSW+gbUWKH2ZN1S/dubLDrhSTQtGUPwXMo7/aLmsqyzQF3MHR0EKKMmJ7juyPcaE2B2TeoaxsaCtTAcYCQew7dHK+X3MGUl9nC0Pd/lo8YtpPektljyecbY5ggZkrjfwzpxoeJtkIQFx3P3XxqEOCWzfs+kKbK+C2KthUzdP5mtLGYa2PC88M6jMbDFht7ehW+7A9W5rhCllwhyPPs3VTCXi/bU8XHDZlnb3BVhXj5R7CWEDGGHhFm3P5my80ADYddvhho2YXHn2mezVwD5js3mLSzHQ7Tk42x6apLVqGjE2/FooxluEXT5Rm8YvNmsV9ANx1ZlRT47GJ2IAvYQfznCpoVz20HdCL0xomf1gppiPKigQUBBPke0nBdePvDPf2uxZPvT5mZRdsZCHabfd2lqX7JdJxRkrs/fJdbDu8vPxAp2xAfwH3vJgIssKFsx4gTqCUPX6LPPEArS0LfEyr2uahYYymVfNXvfM6ic3Lrq3uN8i2QUTa7Hqufx+tYglOryEWcX5q+lujKLu0XZkDfI4va0yQNvbN9VO1kYvB60HkdVSarBqrOHbaNc9kDqyJcObSRw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NDgzODI4NjYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzEyYzljOTRkYWM3ZWMwM2RlNWYxZTBmMTZlZWRiY2MyYzc3ZjVlMjk3NzFmMGYzZWYzYzE4YmZmM2MzM2ZiOCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I'm no \"Boy Wonder\" anymore, but that old training never goes away, even at my age.",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&4R&0e&4d_R&6o&4b&0i&4n's_Glide_Wings",
                "/give ". @plr ." minecraft:ender_pearl 10 name:&4R&0e&4d_R&6o&4b&0i&4n's_Grappling_Hook",
                "/give ". @plr ." minecraft:stick 1 19:2 16:2 name:&4R&0e&4d_R&6o&4b&0i&4n's_Battle_Staff"                
            )
        )