@plr = player()



@hero = associative_array(
            'name': '§4R§ce§7d §4R§ca§7n§8g§4e§cr',
            'class': 'redranger',
            'sig': 'ZCGWM2kgog6C/bddygfuNPl1Kh8W/1JCVyDXXLSCGzKNOvDRtMHPuCNalDYfHDeFvt3IbUDm7T2vFlfHXs/IsVqVshtQ04XwMxfsNTC49NRGDF8NHRt7+IaRRecUyV4e1GKLcoNUATPPBLhIPZEMoriWBsYbRCttIg6rJLvCjWI1wlCqdT0glwVwZkqIaImTVyb+O8O5oEdHitkir53rj9fz1Kr/DqErT8KyYVViW+HGY71LPBw3biIiiHJa4eA0siSBPUAQQq5JgHyTDTSDqhjM1LC1VG8/HMtiY+by6x+W/mXUMiwFEz6OiNgFOaNHJnTzc5fv1ExI7EwAm6pnivktcHXErHhr1gXIOl2QbXmwTzrglC0yy9YPksAuJ4bJ8DOHCmYS8k4wwRFumpP4EdG/zgXSnPQlqjniMKufKTf/LRqztVCZ2a9HuYB9tmbHlMtEzYptyjFwRPKU9gqWaQ5uTtkZif9bIh1rNiRkBda6RC/UfZMdsic1IrCtxP6x5VjRBkOtg8ty4+f7vdXFYTI6TXb8aUlgX/oK0Bn+GOLFPdL5rsHsJjrHvGihnYtW0mGx3wUu8D1EHMFvGZDZWsmLj2wCDsGYRMUjuvUSCgy9+cP8ckEx/b1infMKYJEYZlYW+SUbgzMAmNkvwJfZeCQGjq0+806hIaCN6W6/GM4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTA3MjA4MTAwMDYsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJVbHRyYU93bERDIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82MTRiZDg5NmEzYWI0NDZjYjU5ZWIyZjk3MzE2MTQ4NzZhMTFkNjAzMDc4YjI5NTI0NTRhZmJkMDhmN2U2In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "It's Morphin' Time!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-2",
                "/jump 0-4",
                "/haste 0-5",
                "(Shoots fireballs with bare hands)"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:gold_sword 2 20:2 16:155 name:&4R&ce&7d_&4R&ca&7n&8g&4e&cr's_&4Sword"
            )
        )
