@plr = player()


@hero = associative_array(
            'name': '§4R§ce§4d §8S§7k§bu§8ll',
            'class': 'redskull',
            'sig': 'JCILVtSr2SauRLVaZKtWTlnSjoGLSh2GZOKg6EinmtCHBla9b2gRXAmuUoMYBQThDSz+U0Wmlbed5TPr0DWHrGeT1tc4BufrheEB3ZO0xeXfb94M6nvOQO73xe51gSr0age4qf0+c8uLD/cv3Md0jx4jKSWERTxQy5P4xyJjnsHYQynLejPrIafkBAr/esY/FW0KrQIgJ+uZ4h7VHvxqUQGkwYjwNDy4uADcbui7S3X3Qqbn9Wy5j8q7GAxv33h+SDMrOHMnIC5cSfraVL+vxnzOA26L6pBF1OpNgSZqA3RBrjd88VYe8ipJKMEAkIbppcwv9pFraEh12UsUjXvPssNa8smlJL4KrBVSucHSM6HrTlEc4uaUKlLK5WqeXu6+2/XKWZB/C4RAva/tTqLD5tghQKFqPrLuq81cBWf4Ne2pAIjunZVzHAvZTHy8EcdAPF+7c5s3q4DtJlBKHJYGdWZfTmsZzLy/P5SkECRIzQMb0d+8vQtcl4FPPKkX+p7zG7H0EQLW+S94BB607iEksnGOmO0jFd08LzieqRyTcbvu77T0eFgWH22U+GY4UDNtq4vKg0USl5joz9OWHdBRkDuJ2vqFama2Y88iUDswuJNYT6K0UP+hNDf/mJSHXbZZRlcdA0scxf+59TLC/sqlr86/jXfCIdQ9cAYQSvTlzIk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTM1MzA4Njg0MzYsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJScW5kb21NeXRoIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yNjMxMzYzNWI2OGY0YWQyMTQ2MWY3ZmM4NTY5NTgzN2QzYWEyZTdlNGZjNDViZWE1NDFmZDNjZWE2NmJmMiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "You could have the power of the gods!",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/shot give ". @plr ." energypistol"              
            )
)
