@plr = player()




@hero = associative_array(
            'name': '§4Red She-§4§lH§c§lU§4§4§lLK',
            'class': 'redshehulk',
            'sig': 'n8K0sAgDjl0MdC+tmmZIO1VW3vXtSMs78X7CiAKE+qCRo/nnQarGcd0y+GD8qxUTmryGAp8BY3B3MuWZa0//dSwEbGXyilBHQhQjc19eiXwGaeQMrHUeN5r+3ydCgFtmEylO12NVue+uQlsOJZVWyT37NlaOy9APv8/lyl236a3UlU/mLr3+AJr4PGIUTvL4DW9n8C71sdvtfR3Qpzwxp7mKqbAj8ZhXyj/Ai/l9ExYFIzoOuXTHCBmzXaukwVxhmFv5TmjjUMB5kKyWq0AkhgmLJQ+sUNlCCjksQbz5br7BzBnDCnsGLUkQNRCD+k81LHIwLefx8R6dLD0pwmqbqXtHSqk7YrwgTWD5cTZcYxUb44BK9AV6PJEE6i2NN6WgxFhWi5MN1sTS565YhGf2TygKihJbHogNQUgw89anVNidK1L6IQdu0pFazJJJ/xl57Aw8rxUmhJbF+wi486KUttXTbY7cXRq/Y8Ib6To34N1jUbo9wL7SZHJuLJ0Z40vE+n0jv186KsYjUILY1McpUjVGegf6nrrf+UiNwb3SJ8BLib9EOTdJWvuR8sZHOm/tKUXArHKD1vjVD9UxCjKjatx9lQXyoyjG0qG3bS20tx7R9zh42fsMreCZjE2ztu6kZtimj4s2e9WC4eFPnwd2D7L2b/EYwCFl+ytOr0svABM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NDY1MDU1NDQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hZDZkODA0ODkxZGM2ODBkYzQ5YWFkYzhlMmM5YjM2ZjQ3ZGY0ZWFjMzU4NTUxOTc1Y2Q0YTc0ZGYyYTcyYyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Red is a sexy color.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-1",
                "/haste 0-8"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true)",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&4Red_She-&4&lH&c&lU&4&4&lLK's_&aGlide_Wings"                
            )
        )
