@plr = player()


@hero = associative_array(
            'name': '§4R§0e§4d §4S§ck§0u§4ll',
            'class': 'redskull',
            'sig': 'CDiItkFFniYtaJhZHNaO0TuM0YSzlu0/kxCLeiYEQ4lpNVKLFIzjlQ70l7uNS1jatfkCx9Iv+FqpB8SQ4gEU5m+c+QbA62xqOYB4kYAdx0mFhGlj8apNTFGGmRUT9Ptb7zpz6+dJn8VxLDTRTCZYDwe3dLuayTtvTxsB+BR+T57wkuSqXiudN5cA4OBBjS1adQmFHTBJ9wsTWAcv+fmenajS8XmP3QaVcw3/m4c6dNMmn9MgnxyyZRTU8hdKBxYNYpS0+1Rm3e5YaSWXDDFtX5BuqZ5stAQpFiWG6Ftz1kI9ojnWef6P1d+VB8HD47pCvnMktOd9STYCMwHxqFxkB1m6d4sbaxeATb3sZJQLyPIJDto4K2khCGmx8joBGKqJD2MUkG7+i90jRp25CR8uHgla7JMJ4EBokk1uxDE11SpylYI225usA2BCtAjwxELX4MTaGd0PuzMBqpQC41A9Wjrdvmg7l87gWnL+F7fRXX4gHVYbABbwr0JO+LQFhCFc7zoWbBNWUeuHyDiGH5rls5UqAypOBlrsW7Mw4JjC8Mjm1S8b8TejIRNOx3VNIawmQgo8DoCzN7ZmA9VVXRNOnL9Gq89jTcaWvhUXGZDDM4txiaVb4pXbZaYIt3e5sYk0aLvcAKObZLmTvQtwSGaxlLZwA4CJRgX6sXkanI+Mv3A=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg5OTcyMzM1MzksInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJXaXR0bGVUaW1teSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODQ5NGRhMWZmOGFiNDc4MTU2ZWRhNTM3MWI4OTNiNTU3YzhmNzg3NzQ2ZGJlN2U4ODk5ZWE2YWQ1YjliOSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "For RUSSIA!!",
            'powers': array(
                "/buff",
                "/run 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." AK-47",
                "/shot give ". @plr ." Hunting",
                "/shot give ". @plr ." Olympia",
                "/shot give ". @plr ." Python",
                "/shot give ". @plr ." Putty",
                "/shot give ". @plr ." Grenade"
            )
        )
