@plr = player()



@hero = associative_array(
            'name': '§cRe§4d §6To§9r§1n§ea§6d§co',
            'class': 'redtornado',
            'sig': 'vZUiWXlqSH66i3jG38vZLEJC4O4XniOr5x5kc0PPAtZ8Ii3l2gmuRVIz5PlgsLCqiprauXPF/Fm4JSXL0BQaNdHFsIlj0kdeCJZ70wYtU4UAxWc9XsNqtuWMQUcTuMgLoN3bRWRoDRnIXTTU+fF5dcK1v7+1N2ObbjpwtUt1Q71TabVpxcONGyt7SWSBFFJTC7+V9OO6kRpwWIayB2eeq5JvRLmqj0JFkPgYKB3wqp7ZiyWp1oIPJTAxmjaB9kfU4Ap8MLrKN/0oTXyEJdQF9m1LLIw0qFUgxkdghfTPc1vzTKcbGrFcfbVTjp1DTLYXxx3W0vL8IZ9FHvbdDzQ5EV9ze5yj1fVkh/18+8udPrasFWIsak2NxdLy6EEstY6bxKdx8PPqn9R2JjPNGyWezVbEfbrzM96hNvsR02zNJbjmOcXWuFWRTPNPqTcwg6/gqo+WG6I7hO7EbKBrbRyobn3aN6xibGYDkNPmWN+AE8bbdycdCQPmAsk6FVY0+f2/KIY3AsnIV08h/3u3U6GBaqdD4tYempadXYxoxytE/fEFQcYavlzqgNu6s8bxg0w1qIohAe/umEh/cfsSSlOzH7KH8OIyj42Nu3l1cKHw7FqGFqWWDoZoLPj/9l57Q2Y790pNiVA+5RWmlUaAO0p6V4lgGry/YbHEOPQvBPgH7wA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTEzNjQ5NzUyODMsInByb2ZpbGVJZCI6IjVkYTI2MDkyYzgwNzRjOWI4ZDA4OTUyM2Y3NGRkYzk3IiwicHJvZmlsZU5hbWUiOiJTaXJNYXN0eU5hc3R5Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kYjNlMjJhN2RjYTQxNWNiYzIxOTM2YWI5ZmJmNjY0MWE2YzNjNzdlNWEyMTUzNDk1MjMyM2ZiMzVlMmY2N2EwIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Excuse Me A Second, Will You?",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/fly",
                "/cast redtornado",
                "/cast whirlwind",
                "/run 0-4",
                "/haste 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 5 true"
               )
)
