@plr = player()


@hero = associative_array(
            'name': '§4R§0e§4v§0e§4r§0s§4e §0F§4l§0a§4s§0h§0(§4D§0W§0)',
            'class': 'reverseflashdanielwest',
            'sig': 'g0rKw3obHF1zMJVUfEPc2WSd99aRk7Q8pAtmM7B3VOx6GXNQgIPDPMblI1+VfCPv+Lf4+Br35l8tJf4pmApJxASr53ZOgGK1mAc1XZpGcJ+IXtLPgA0bVFjR9GZKh0yIxZzHRAhyIDQQeTxuzvRSiVkhMOt5W7s3tmlEPoFvtSlzMb259PmDIa/b1wGE8eNKA4dy2uJrrDuQf3u1itBKABYb6I0TPzfRknLgfP4blcN3okmsD/9fFAc3E3EJFP1C9mZ8ecvLJ5PoeltjhSsAKPvacn1ZHvLKsVjkwcbq/90xeyPXWydzx997CjOBU3HqfAsbXeGSUm4rOnKnKkAFhU8o92Df7PFHmi6XL0fTlcCv4BURYFoWHKWmDZquaj2IIaTAdetnQvp4AKYDWZzuQg9rvP0gveta0KlQqJQ3TR98GvOFRG99E2dCxK816NoMTsJhTnKyJraqGqyUP9pbydFSciibKuTVlKtJ7TXlLFBKzUfwTXl+pRTlnA6gqMikPW60KR6wVf2VG8DpS1FVwfRT6X7eRKtXY8ZpVuodYcAijgmJW3z2HStZyQVZoMoau1B4EzcvcHhbnyU88EZGXn45+LE3FwSDw8rqjBGsdQ6nnExDwiGA3Jg/lNHXaqhqM765nujma4CnTuAg2TIxlIzHQ3LB4m0fN03B3tUZXKE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTYxMDg5NjI2NDgsInByb2ZpbGVJZCI6IjFjNTc1YmU4YTg3NDRiNzg4MzA3MzI1MjM1MWFkMjc2IiwicHJvZmlsZU5hbWUiOiJMZWVkbGVyMjY4Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80Y2VhYTY5MzljM2UwMTZmYjY0ZTU3N2Y1NTYyNGZlZmIzOWFmYTdjNjQwYzJkYmZlOTZkMmRmYzIxMTRjZCJ9fX0',
            'trail': '',
            'op': 'false',
            'speech': "I wasn't always this way.",
            'powers': array(
                "/buff",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/jump 0-3",
                "/haste 0-4"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
)
