@plr = player()


@hero = associative_array(
            'name': '§4R§0e§4v§0e§4r§0s§4e §0F§4l§0a§4s§0h§0(§4D§0W§0)',
            'class': 'reverseflashdanielwest',
            'sig': 'lcgOSol5bLKqM1JLUtXFBv74OQhlRT8wrOSct0aCMENe00vyWHraYXKzUVO+ZGhoABhkmDCEnIqeCI05wikZYTz2MkIy+aNx0YQfND2I05XynBeMHr1Bn+CExJyTAAd6nj23Q29YGnB4QLOoh9EW/byftN3Use+muOxp+7TLwSxs/FJxtHNwxkx3f9ol9MWuuH/hHj0OTUlS/pPpj2snpxVrBZuPMv8pTzzz4+nz1l50S2zeiLP3xx3iNn5TnBPz4i+FKbPKg1VmQUMLuEzKW1wN9YNjjOCSGbeSrMuThf2Uqot6ggcBzbVdvL6YGFQSwy6gN1eQULVgYknvkSnG3e82/nRSmLjE5ah0/Ggk8ak7shTLiInu2GQY84iDDahCOwxF9XKQ5sEhINBuj5a0r3rMXjYiLTUc9sQaZVLLuHzy5+OWJMB54KhKPEbVpBGzH/Tf5RXtBuHt3TJwbalT0D2y7lMmK7oVE/HZ3MbX/+GLIWI4+Z0xAUiVbJ5Sr4qnDsT9gGc9dy5ssMQpYjBsh3Gi+kxKy+bE+oL5D2ttJr5lG5PLPNutaYIMu8oJ4P7EQpN50qIp2obsYj750PLpGLati55Fnh3HBaZN2ujQ1QGeE9D7plwHOir4qMbhM5vN8q0hsPWvG09BAocPI/bKr/8m+ifH8L4AWG5dDoX6pvA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDY4MjEwNDYyNTksInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJpaVNpbXFseUhxcmsiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzM1OTA4YWMzOTAyZjMxOWFlMGQ0ZTU5MzgzMzZiYzE1NjBkMDFlNDE4ZWQ2ZDNmNWJjMzM3MjRjYmY4OGUwNGMifX19',
            'trail': '',
            'op': 'false',
            'speech': "I wasn't always this way.",
            'powers': array(
                "/buff",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/jump 0-3",
                "/haste 0-4",
                "Throw lightning with an empty hand",
                "/ma",
                "/thru"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
)
