@plr = player()
 
 
 
 @hero = associative_array(
             'id': '148',
             'name': '§4Rev§1erse§0-§0Fl§4a§0sh§8(§4E§1C§8)',
             'class': 'reverseflashedwardclariss',
             'sig': 'ilNVkzhaVgRd+2hKPDcLrJJH2iSJmeKQZa3XWMvmLD7XB8pcTwMCFHq3ONRNLMSRioGfDb6bICBWq5CJO+bHVKmj/WQ0YnULxAk6aWe1SNu8BjHrbGnU6Q6cyDQMlxdMBe2ew0h3GsPFKy75zPzcYyEY0wZAqik9VF3wRrpT8nenyQcc4sNzbusxncJTVWKPp3u77e2LyJezash2nZp9hazWl5R4Wzr2vjGzUqWsiTr3uTfLZngOcGkoiIHhLIBJCCqlrlY3F68gdMs9MnudqhxILbWxictvGvjFndzOyw/j0oYWABqgVbjQcGYuO0qU5CXqZhxYe9TM89Ej4HJ+4YowXlfk7zhBTIjBtsbfBJck5skdWIoKT7f/a/s9tyTsgjNZKUf9WW/x1OmFuhcIC7OzBQ/ea6lgWCrj9ypbZq//EBn61OFRKZOf083jprzgKnd4ZHlR3AiQ89LVgd06PMNjhLEP7uxeg+p8YYWWYKJhQXt+MclfbmRrb9/SXs1GQjSteJmhcrnRECkhCZ69e2N8MJPb9VYMTJudQhW0PR+bFfaAyqkwiDY51jNK0cQoBbhqa3u2aHyOQh7Kvm5m92wgt5rfCf7iZoQt+ewtk/oOMvx1gBHs6IpAjy8X7fzD4DkMDN+04TOYTZIMq4kYHoE8U4P5tNHMNr2ovnCm5S8=',
             'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg5MzUxMzU4MjEsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJXaXR0bGVUaW1teSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTQ5M2Q1NzFlYmZiODZiYWJiOGZmZDM4YzUzNWJmNmEzZWRkNzY5N2YyNDg3ZjY2MmYyY2UyYjNmZTQ0ODE2In19fQ==',
             'trail': '',
             'op': 'false',
             'speech': "I..am... The Rival!",
             'powers': array(
                 "/buff",
                 "/jump 0-3",
                 "/back (in the speedforce)",
                 "Access to all warps in the speedforce",
                 "/speedforceteleport <playername>",
                 "/speedforcebuffs",
                 "/whirlwind",
                 "/carryplayer",
                 "/dismountplayer",
                 "/run 0-9",
                 "/haste 0-4",
                 "/thru (phases through walls)",
                 "/vibrate",
                 "/stopvibrating"
             ),
            'buffs': array(
                 "/effect ". @plr ." 5 9999 10 true",
                 "/effect ". @plr ." 10 9999 1 true",
                 "/effect ". @plr ." 21 9999 4 true",
                 "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
             )
         )
