@plr = player()


@hero = associative_array(
            'name': '§4R§0e§4v§0e§4r§0s§4e §0F§4l§0a§4s§0h§0(§4D§0W§0)',
            'class': 'reverseflashdanielwest',
            'sig': 'H8zNPjVz41Mjt7RUFhDXQ88UndzjjA4JOzR6SaSBCfU6CVbbZwE0MlIQzbhp10o8Eu81gPL/6sB4aVq42VEVvUkOMOfEvUZFVQgJNkI+wHDnYn54ctitSM9L7r0H2TJ87pCEm0cDaVpzl5Ek6TnbuBihQD6Xs4bhSJgedkH2s8dda5LSSJFym+5/uFVWvz6e1hQ7TF+54SShY/S+ESBLpQuPk+3A+P1YFBrxyqvCWGfYENfK6TEVkNSwPROT+dx5yMWPXU0/p8VlAQL9NTv/E5GFEmcTl8AgwEI4MtiSTNwCBKHsqjJYXkT4d7DfEdFJxHjQY7ybW9PznYiU+sINRQD729IoFDG7AvYcNGVARBL5evRG9Esp9BsK7uuSyfx00QFbm8/M8/Gb6p0K8ygDHfjG30GSsZe+QPhgS/bTduhWsv3TxXU47JV1uGxZ9hNeCTF8LsQcvta19ndNp6QzQTt8SwnnvRzRFVYy2nRXNYnN4eH+46o/Ph03RdvihrbohDBhLZ5aPslZ79AM2AogCfYUH+kbS3a8Dgdjpd2Ny9e+LZltVT8gs3K4WiUoifnvKGEa3z1dHF6BPmZSolOom24hreh+F1Ro/V4B7N+cRJ4CF3ClzkCIuj0uqKCMrKJnJ5HXD8Qj88z6Oyq1MsWiyj1LQIOjtvJkhX0GaAIbl1k=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDQ0ODUyNjIxNjcsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJ4VG9ueURDeCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2Q2M2QyYzE0MDQ2OGI5MzI1Yzk2NzQwNmNhNGY2NTU2YzM2MzNmNDAzODQxYTViYTc0ODgzZWJkZDIxIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I wasn't always this way.",
            'powers': array(
                "/buff",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/jump 0-3",
                "/haste 0-4",
                "Throw lightning with an empty hand",
                "/ma",
                "/thru"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
)
