@plr = player()


@hero = associative_array(
            'name': '§eRe§4v§eerse Fl§4a§esh§8(§eE§4T§8)',
            'class': 'reverseflasheobardthawne',
            'sig': 'CVeuYW+3D//vRVzraEwgfgh4zAJORpJLvMb/yehGyBYAyWmN1c4M89ZYvYLhyhJfUsGFKTGKMAB/PI4lWqOVkJ0IQaDrV3+SBw0+1LdLyxfhBjM98bNqj36v5eCXeXeKGNF7k5h6iRR+uzMFmgzP8TvHnI813n28LBmh7dHcFl1kWVbmhZc2YbTGs3zXgQ6Psi6q61LuMjkIKeN0i3rMF7dkGgblpKwpV6D8kktgcy2eQJtRCyUUCrDfa/+Ntp3Hck52Enh3kyLgBcNipq8aYUqBH3BOfgZln58LvwkbCflTESvZm5NFfcQAK2qLltdKkKGrCSOowT6mADpTU1+Aakb9DoCD/Oke+wftM6FEu6qZ0rilewi3OAiGqojmPjbvAzy3aHDGQ0Pi144lcCPMf5hCTeQCDfPmE380XK60+S1jI74q6RIn1DStDZYbD2NpE4tmxUUKbHAewjqlr26/5VrNVWGAFxl5LynuGZu6Ryc7rItiTi48zwNBNRfgRsPpxaqby1Gc0XYBWweUgenoR1sSFzXSwnpWbcs18IJXcdAWwPh/KTy+9LursIcWjZP05NnPhbK2WCRelS0Y1xSCh8cBy11JGmZhLPmyV1BTFsT6nuc0j0GMP9N21EZjFftGNluKs5MRqjGaNopYm8IlYA/iWfqN4hs1XWVRd6pFGnM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Njg3MDA4NDI5OTMsInByb2ZpbGVJZCI6ImNjMmQyNzM0ZTc4NDQyNTA4ODZkNWM2YzcxNGJmYjA5IiwicHJvZmlsZU5hbWUiOiJEaWFtb25kTWFzdGVyMDMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzg0ZDlhOWUwOTQ5ZDI1ZGJmODU0ODA2NjNiZmJmMWVlZjdkYWFmZmQ1MmE4ZGY3YWY0YTM5N2Y0ZjY4YTI2In19fQ==',
            'altskins': array(
            array(
            'sig':'v+qIPPiu8odYU9LV8mOgcyriJg+4WuDhtSq7Zh4+i9q1cj0Y9z3pd5szqOIKoDu1y8mrmNxUSHs6etSdobXX7btvesFTWrz5Y4kVKKmqv7O8DdjNzXSfZ9DXHvEFg8fHAnJsPpLfpVe6qJ3vzCIVaRGNpSBDaKhtRSp6QJ9uIsl/CxYHt+9e0jPMkO/OXija0OjKIO6fIJJ432tfoPtDanJ/heMj3ShVa4QgA3CyefbwtgIDUhInSpxaZcCvYmtmWMTDUK/K6HK7wbWFdppL7lZ9SKpNfkWkf6vgB5D9CKjlRJnEpCkzr9nIVTAnxL8alOWR2uT8+dmWW3xAW8eolglsWH942bfT4FDrGaYw2CaFHpkn0nDBa83H8UMMR9Mz/xnhvwzVJiHbejM1ghZlKGhqf73KdODVAXBEI9Tfph1KEWDFVHuaJSxZqEBzV3TBIfJK90W+RNOR2RLUZWW8gqaiLiUbgxq20EFAJfL0goYXfgZdH2H4KE/ds4irPZhHK86YK15GgDufoaQVSWMVKXnHujF7k2kYqxT8fGVrh5lKMYjlk2+RcCfwx+cCwAf4YG94O2DAyYj4c++YN4MZVaWQ0YNSJQGkknrunj94uqFVhOWgu/vCYIgQs1K1aCC0vnLUkmzennclWvQrDrUfZiQ7LsP8SEkNjh/Z166Mnl8=',
            'val':'eyJ0aW1lc3RhbXAiOjE0OTQ0NTA1NTYwNTUsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJDYW11bGxsIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjU0NjkwMWUyMTkxOWEyYWRmYjg3MzNlOTk4ZjMwZmZiNTY1NmYxZWUwMzE5NDhmNjY1Y2Q0NzdhYjNhNTM2In19fQ=='
            )
            ),
           
            'trail': '',
            'op': 'false',
            'speech': "I like to run.",
            'powers': array(
                "/buff",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/whirlwind",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/jump 0-3",
                "/haste 0-4",
                "/thru (phases through walls)",
                "/vibrate",
                "/stopvibrating"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
