@plr = player() 
 
 
 
 
 @hero = associative_array( 
             'name': '§7R§be§7y', 
             'class': 'rey', 
             'sig': 'LsdNOeYhn7446Xpjlz0PqrEAG9vfpNw0m5iCdRgWQbCSjhZP42mi447DtihHp1xBXZqpz9j6H1g0/6UsNXZuiQiwgOSotTYGowjOr2wHIEciYy4ShUs9uxjd3G6gyJ2OFC4ofvbo8gqUs10Q2NW55xZU5AJ90r0sj0CgIHSrLRrRNVO/1U1lnnRspEiVsLjhe05IcKX2MiKK1EoVbjvdOrbbBsBarO0TE/oABVm/xkjiuNeVHd0LrHnQhajB7fj2IR2VTPPmwoXfF0VdMW/D6+ejPNZBvPDt+SNglsSofJaypygf7uWdS/2oiL0sXjbPMx5VKS5llSEBAgdUTvacI75iZn6ZWT29rGCyL9VasU/mv8I5G9hbfAd3aOoEe5/7JWga83GddqOPbcvlb1XdBGpx35raZ5/y9eOgYp7p0s5IUb6ByB/qT+hd/zg6m0mY6PTrHnYk53n9Gpk81UfHjRU1yoVzlrH8u6gvdj3lDJui8hABGH82/9wJLNWAmnV7JeEdIhEYBMmcn30v8huOdLye9aIGEW2ohf/bUh9Mglm4S2/4+FXvppu6jqDXeF0AsmhL4JgDMxp5ys13YdZEr3YirXw6wS6gYd4Arp1hYUniAYdLEnriRjRxxVqCAf/sX47/rp/CgSXL5w8pkkFZ0PpuFc9kTmGENVCj1PYHSXg=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE1MDc0NzkxNTI2MjksInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJIZXlJdHpUb255Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjAzMjEwYWYzNWViMWM0OWQwODlmNzU5MzBjOTY3OGI2ZTA1YTcwM2Y5MDZjNzI4YmYyZjQ0OGQ1OWMzMWMyIn19fQ==', 
             'trail': '', 
             'op': 'false', 
             'speech': "May the force be with you.", 
             'powers': array( 
                 "/buff", 
                 "/jump 0-4",
                 "/cast forcepull"
             ), 
             'buffs': array( 
                 "/give ". @plr ." minecraft:iron_sword 1 20:2 16:100 name:&7R&be&7y's_&bLightsaber"
             ) 
         ) 
