@plr = player()


@hero = associative_array(
            'name': '§8R§7h§8i§fn§8o',
            'class': 'rhino',
            'sig': 'V50aefcuB+DkP5dh/IJLgWte6RqsFTD9KgwomqL8NVTEsyBt1DdLyzSqBrmXkiy9mcfgeEtE0lNQOfIcvUOfqfE32X9MRozzpAgf44KTmvLdwbLdEnGKUuphV2idEGW7GNSNNbaTrSBEaCH31rjP/+hAzA20/rmZgTSuXhvSh7rUlFFbeeu3LLjYbgFF57yWI1ICPivPtyd1ecjGnSb5mhoDcVwWdgbCBFaPSvTz09nqj984Ts5/IJxiba53LgCKsTJLI8oi7wjo213nPaTlpXmQtiliZDyY9jOPB3mieiOzeY+emtRq6w1/FGAKBshTUDtt904XKr/Y9PaOiYJWBCL/JxSyydmh+KXvtZ4E220EsX4unl/94UPx/D1zRIvzRd1ppmU+hI+978GIJsxxyu+aZwTSBH8Dgn99Xr3XsIx4BSzNY/9UFFJfsXCKot690qAaeag9XTekjCKR/wsMcFjWC1IiltpVqjmRcyD/CW1tgyPuLKWAXwhnKhKWXtUb0HQ6heaAgT51mQVOYZVOkvbZ2wsvTu9TG31iCNkWdcCtDdc+qecUmaFlNRWgKOl/knxDb2YNjo9qiuDr8dxuhIFAjIY3p5qyH+Ej8ASjySYOHXkyv1dYMEpATt4B6/ULxLSmgop2OzBW3MxUDHutjFfpZp0GFlggYwcqnS/Bcno=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDAzMTI4NjQwOTEsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGFkZmVhOWRkYWJlNDJkYzJiYTc2NTNkOTFhM2MzNGMyYzlkNGQ3MWJmZDFlN2I5YWE1MGU3M2Q1Y2JlMTcifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am the Rhino!",
            'powers': array(
                "/buff",
                "/cast rhinodash"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 21 9999 9 true"                
            )
        )
