@plr = player()



@hero = associative_array(
            'id': '148',
            'name': '§4R§8i§0v§7a§8l',
            'class': 'rival',
            'sig': 'A5u57zeaPLNN9GHfAW0ezvtp8zHzVhmq0UkXpal9T19bpq/t5XM3c7hlR5tyhjZIrogxVDbx4sODYGf6wsqZt7OWUhS0sZvEH0qlrgBwY8XlFSNPH1U+Xvvl3hxqDURdLos+aLiyHR4BlKPZgDXVebugLAQHtV0V0lvJAYHKIgqnR2n0Z8VcUZU7H46MtNJG7wUk5EDXtbEglaRKmseZzvF4v7M4BLhndANvZ+5t7UgdcIQb77Zco1589/J2fc+zHkGwn3IJ7/uJ/+SBGCzH/XeZ8HAY3LQC1qw18DZvHLyb5sY9KGMJFQ5ngiJQ3OW2G2UxssuGuzOjBi7d+Nr7i80y89j3rSvDCRbMaz1zlvIXQmCSe2UijdIIz0LKaol4kBCBISMqVI72nX0bEzSpVWTBLIQ030HdrmS7sPNQ5AVSDRze9qa63z9wROuaSmRLcshNTIMGs9JOyRc0ftnerRXRcx1uPLSyodqFOzHL3G2sVv5rZHOAobRKpFhd0qrErpLj6yZ8mD2Fi9z+T2VBlAIgiua0BPyKr6zMXyGGOZ+ukWidMmt4BdEOiA0eyS1HqCDLEJC+uQnYnCmjmPYXzYcBBQBS68ljDHI9q+xgKeonmEudCpVKqQH/ecbmW0fFjXL0FEXj7QRzYXxgP2DHOyE0yEUSZ1pFkV7CXw71D+w=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzgxMTgyNTA2MDMsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJXaXR0bGVUaW1teSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2MwOGQ2YTFmM2JkYzQ5NGJlYzZmYWY4NTg0YjI2YmU5YmE2ZDhjZTFiYWUwY2VkNWMwNDE3NzRlZDE1ZSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I..am...Rival!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-9",
                "/haste 0-4",
                "/thru (phases through walls)"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
