,@plr = player()


@hero = associative_array(
            'name': '§6R. M§9i§6k§9a',
            'class': 'rmika',
            'sig': 'WfNwFhGYQ3lwwPjUxPkLNvl2o2WNZtpdGPIOdaxLaRSvbbDFnHbbisVFSMnFMU8g94VhRw0R18w4ByAo2BfWBS7Q5vLy8oplZhbkq2uR17ehrlPVYw1lQAKOH49SdLQ4vhlgHZLMbkM3VSSOrkZk6RkbmLmKE9dbATsGGgmVWN8QcrJ8QBCV1UKvr5LHnItGYNbgmohkRAgoD/z4v4i1MtT5ZeBGQGC7jhI7RlanPBtALn0agqOuvwh81SrP0+cxlRWPylq+VmtJSPajSBdWqSEElkhuJl3MEWSXTwc/qjpnG4OJs6zlVaAl7f9lBre9AB+50gU/oKD1FyfzBM5f78phcKaT//znzmUKhirSfXWh24rWuLyFrf+CKlmrjayue4VKIAcKekfuJbo2PZYAgqggs7xP8z0lvIXuYKpfSgb98GhOvF6tAN0jy+wnPV9aehaXjkkLZ2c9zh2yZsjv4AqMcxdQ6YgWlkarLoIgh3kysQ0aTu/tDw3xpPVQ6zfL0VoOueHOqsCy5pvbIIJUtyNPhD8EhcR0yCLcE2pXrY+48Xy/+Un4v29DMfgMmcp62+2D89FNO9N8BKwKJVpoEuIfLiu6kl4Q+Bg0vkpEF98gw0ozMSMVKt3SewSP7i6q6zHttADENgFB51jf40ECEvx+g0t1uBYPkv+tMGSS9dI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk1OTkzMjEwMTMsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJCcjBrZW5TMHVscyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzU0MTQ4NzQ5MTNlNmJjNTkyMzdiNDg2ODc2NDljZTQ5NWE3M2E3MzlhMTQ2ZjM5MGY3YmE0NDNmOGYyY2Q5MWEifX19',
            'trail': '',
            'op': 'false',
            'speech': "The Superstar of the Ring, That's What I Wanna Be!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/carryplayer",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 21 9999 4 true"
            )
        )
