,@plr = player()


@hero = associative_array(
            'name': '§6R. M§9i§6k§9a',
            'class': 'rmika',
            'sig': 'WfNwFhGYQ3lwwPjUxPkLNvl2o2WNZtpdGPIOdaxLaRSvbbDFnHbbisVFSMnFMU8g94VhRw0R18w4ByAo2BfWBS7Q5vLy8oplZhbkq2uR17ehrlPVYw1lQAKOH49SdLQ4vhlgHZLMbkM3VSSOrkZk6RkbmLmKE9dbATsGGgmVWN8QcrJ8QBCV1UKvr5LHnItGYNbgmohkRAgoD/z4v4i1MtT5ZeBGQGC7jhI7RlanPBtALn0agqOuvwh81SrP0+cxlRWPylq+VmtJSPajSBdWqSEElkhuJl3MEWSXTwc/qjpnG4OJs6zlVaAl7f9lBre9AB+50gU/oKD1FyfzBM5f78phcKaT//znzmUKhirSfXWh24rWuLyFrf+CKlmrjayue4VKIAcKekfuJbo2PZYAgqggs7xP8z0lvIXuYKpfSgb98GhOvF6tAN0jy+wnPV9aehaXjkkLZ2c9zh2yZsjv4AqMcxdQ6YgWlkarLoIgh3kysQ0aTu/tDw3xpPVQ6zfL0VoOueHOqsCy5pvbIIJUtyNPhD8EhcR0yCLcE2pXrY+48Xy/+Un4v29DMfgMmcp62+2D89FNO9N8BKwKJVpoEuIfLiu6kl4Q+Bg0vkpEF98gw0ozMSMVKt3SewSP7i6q6zHttADENgFB51jf40ECEvx+g0t1uBYPkv+tMGSS9dI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk1MjYwNTc4MjcsInByb2ZpbGVJZCI6ImRiYjQ3ODg3YmZiZDQwZTZiZmVjM2QxMDUzZWEzYWZmIiwicHJvZmlsZU5hbWUiOiJEX1RlcnJhX0MiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81NDE0ODc0OTEzZTZiYzU5MjM3YjQ4Njg3NjQ5Y2U0OTVhNzNhNzM5YTE0NmYzOTBmN2JhNDQzZjhmMmNkOTFhIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "The Superstar of the Ring, That's What I Wanna Be!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/carryplayer",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true"
            )
        )
