@plr = player()


@hero = associative_array(
            'name': '§cR§eo§cbi§2n',
            'class': 'robin',
            'sig': 'SQPn+JXx+ADd3+IAmIUYRRbyLnhO5/1RvhPPqnENUWG1PDJl8R5AoSI5t/oDSjwnV5nM7sc5/xp1bwgImlAqTYvhrAFiHxh+qtsAigL2nfgd0jkqesFje3c1tVIjBwduShcZnC+uEfIubJ1JqmeDVt39O27wtkLyhDWm73gXxZ0zdx5vgh/jJRYq96sMbUdSCb8DjrK/vXZCpSIN1KsAj5JYDml55jFTovujmaOLra6Cfe3qoUKVQPDj2h5MKv5B8+Sgl8L/NYFUFXzyy+BlZK7Q/roWihdYoUTj/LOk5PlGpMGzEEPgq8j8+/8PM9tm2yJVawEdasUbq6qGCy0jemQA+yvv+nzMU6z/7r84bscFRxCArQXRFneJwdx3s7aD1Z4FS4R+pzfPOEF0qV945Zw4jUh3coq456XSuq4P6gW+1Ff0CEmrnMP3qEZWG8XXvLwfX7EZhX2qyIlnvtpzsxnk11EIXjgBD5oBofzjwIwQm8SYRWSGNPPOR/QSzPYwMS5DiCAnWy7F6OToVtPIUzBhWwH0LV1lKJ74sWSSGqWi02xIgREXuZsEV6zyIXRwfYEdNXAQcNcJLPYF+KchkGsKW4Vy0vajouJrhlD5YfI0xNQNPK16Xjb51ejpZ2Z7tQCY8VuMVBjroG0AaLB+S4n5KpOacBS95QKopPhdRgw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjQxMzY1MjIsInByb2ZpbGVJZCI6IjhjNWYwZWZmZGRiMzQxM2Y5YmYyMGZiNzg0M2IyY2NlIiwicHJvZmlsZU5hbWUiOiJSb2JpbiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzJjNjY2YTNmN2E1MWZjYjI4ZWE3YjE1M2QzZGI3ODBhNzg2MjMyOGY3ZTZiMjFiODY5ZDliNzI4ZTY3MmYifX19',
            'trail': '',
            'op': 'false',
            'speech': "Holy strawberries Batman, we're in a jam!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 21 9999 2 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&cR&eo&cbi&2n's_&cGlide_Wings"                
            )
        )