@plr = player()


@hero = associative_array(
            'name': '§cR§eo§2bi§cn§8§cD§2W§8)',
            'class': 'robindamianwayne',
            'sig': 'H4zXv+kpHf3U825FpIrXH7SGb4BMeoTlobf/j39jz44n0AyfccT0N27qX/DXdf1VEvu32sdjYfPNGJzTXQOULVCQds9ChX5HgO7KMt9UYh4UZE7sY8wNiGZP3t1tKKpdTdC68AzTbgh9onEMiBGQwRfUGTqsKmcQTDq4jBIqXDcsInLu5rpBGBXp04BuipZw6DI9yxZke0yeZpa1t3PwwgFoq03OpUYuN8AfEOCaVndzDZfXMgJAw+xUoO9y/Yyzlb1pZKHN0XiX98a00cdrr+R5QGGm5uS1V32R35YldG/JOcCFU01Ic4k61/20vR3Gpc4yK/Qbx2zVQ5Ll5ZQz2F3X8sBZbAJ+v/Pk+yMOEQtrOGj7D9Ihm6sEFLnMgn85wGslp3fqF69IL6CgqjKwv31zz7ZH5Ip4fNJIA9C61IInoyTjkO7B5k6GmNKzNAFgiVHM7+QCiwi2gXMdiwDDupONYYRcd3H3477U5HCLxQ8gwH7t6iS/sZbS5Em+ZqQM9tiuhlDPYkXabZfaL6qDJ2zEvGZVkoEU+bTb6dFSC/SpqHbaW9BI5edZ/Z2miMbROoxn8aSPvH4/DIQgmDrb3PZMUVyi5E0PtobC5iPAAsXDxDx1y4zCAYhagY8PTZTf2FObnTTuReatI9OeOSmreXV3D1bq5H7Wqcnr8wCs6j8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODM0MDU5ODE1NzksInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2M2ZmU0MThmNWVhZTMzNDI5MDhhMDlkYWNjNjk4MGRjNTk3YzQ1NDFiZjE2ZjRlODg0ODBkNjZmNDM5In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "My name is Damian Wayne, i was trained in the LOA by my mother Talia and my grampz, Ra's Al Ghul!",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-7",
                "/haste 0-7",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:iron_sword 1 0 20:2 16:10 name:&cD&ea&2mi&can&e'&cs_&2Sw&eor&cd",
                "/give ". @plr ." minecraft:iron_sword 1 0 20:2 16:10 name:&cD&ea&2mi&can&e'&cs_&2Sw&eor&cd"
            )
        )
