@plr = player()



@hero = associative_array(
            'name': '§4R§7o§8b§0o§4c§7o§8p',
            'class': 'robocop',
            'sig': 'LWpTEEPXpVt9w80lHJu2vM/ucZ0nj95vLx2jhrtumhkRDHD5pkD+F8onn4lPDkasgBeHqKuN1tNAuhgsImY4XAq8P03Wl65rYfyACh96NDfeTXJMTtW9tNhW4VBRSGKZskWISlNHPVKpAWT3r8nkWtCjH9iAPvQhQytbNLLmMgJvy7aYieXeW31ThiM//dWznX4U3v2HmRj4EQth3QLMV1MQiWzSTp/aRv9VOTXdfcew/Y/Nz1B+tnjYD78dfjnrdD03jcyBWIBMHMWg+gSBBxKs7rDFWwGyMzRENA55fnagRAln9bigjK6Vh4oITVgeW/7ImF3pbKTUKATrnl+Yw0yIOveIy6kJi8Cn2+O+PdqBA9TdzB47BxMT/MR8M1Juff5zx/NMkWjgC2+0xjwFQaqg52uQu0Sq++PayaZoMyWDHm9bwfiRr3plLTDQTbPNYXCImOvtxSGQ5ff4wkX5YmeRyfE8Vjkf0luFM+Zh2yfXV6d4V8imptoXtsv5x+RSDDt62w+78uw6caXyCKYHJdhV4uNfDdaLd0bF0l95sVM4hXeqHS2o3tCyKKPIy4LWIlxLednakrQTOzisoqDZpFpa8T/yDX3JI1x8fyO4ZVfugwRV8kP+L3sugq7XIjNbMf+NHRObVFzVRoMx4Em4J+u5He7DEW3ElphD1rCep3Y=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ3MTI1MjEzNzksInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJVbHRyYU93bERDIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yZmYzYTBmY2VhMzVkNDVlMzI2ZWZmZDZkZWQ1NDViNmU1MjZlMWIxNjEwY2FkZjcwMjQxMjFiZjlhNmE1In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Crime has a new enemy.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-5",
                "/haste 0-5"
                   ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 9 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." AK-47",
                "/shot give ". @plr ." Hunting",
                "/shot give ". @plr ." Olympia",
                "/shot give ". @plr ." Python",
                "/shot give ". @plr ." Gauss",
                "/shot give ". @plr ." Putty",
                "/shot give ". @plr ." Grenade",
                "/shot give ". @plr ." C4"                  
            )
        )
