@plr = player()


@hero = associative_array(
            'name': '§8R§7o§6ck§8§7e§8t §6Ra§8c§7c§6oo§8n',
            'class': 'rocketraccoon',
            'sig': 'k1YHonwn+h4hM4SFOXZeoTGdaLbnuePBzFnUQx36KzNA0/yzaA0Lz7wvZIts5F6/fXjKVK7MsnRIY/ONaRuwbSuojDevl1W5GLC4/4gD+6zT/+Ttvr9HEQLquCxk7Z9qCSAUK2QtniEAQffGCVAzkROWA0gDJ856U7sW1+NP39LCtc3esfGpxyI4T+OL3mx2fmf3dPLcXYUBu3eG74565i7d4GcnLwqxCsr0E0puippOxabPU/PjZnag7MBlikjhNyxdtdAOZrbHAp2JgK4jBsk1K2hwbnNWyv6ZOccybmrVW998whBdqbUt/CtsUCELWlbLs3k9bsfYIagKkrxbz7tdFv9wlganOCXG4QHrXL5gCSLS8whaTIavAGCcasUFy6YTL4bEAsidN3I1t5R77JlBYuhTHm8ZzawtoJEsdbW3e+iHwRaOm8oFxnt0qBO20W22UxlhqrV6cpu65/+4vEmMowd36bpf9aO/fetXrx+vNAUnjJtQhuWe48+6fSj4GhMOoPGfawOhPQ3wVxvD/dN2N5dh3SVKh+NzSu62iw6kyX9xhBqj3nBKZRt2N+wiFEFg0CQuCo9Am5RFdolWNJXfI8vDA3Kzq6odsIPuRrxIlmoJVOhoXZvLC1ToFkRwQro95N4PN0X4UgyIiLL3xtLHsZK0n86TuCmBV0ISPew=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzk3NzQ3OTE1MTAsInByb2ZpbGVJZCI6IjAyZGM3ZDcyMTk3NzQ5NTA4MWVjYTUxNTMyNTBkY2FkIiwicHJvZmlsZU5hbWUiOiJSaWNoaW5hdG9yMzI0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83NjI5ODUyODNkMWY4OWZjZGM2NTQ3ZmY4MWJhZDU5NTYzMzliMWEyNGI1NGVhOTA0YzM0NDk0NjgxMmQxIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "That's it! You can attack me, you can call me names, but no one -- NO ONE -- touches my blaster!",
            'powers': array(
                "/buff",
                "/run 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 16 9999 1 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." AK-47",
                "/shot give ". @plr ." Type95",
                "/shot give ". @plr ." Olympia",
                "/shot give ". @plr ." Python",
                "/shot give ". @plr ." Gauss",
                "/shot give ". @plr ." Putty",
                "/shot give ". @plr ." Grenade",
                "/shot give ". @plr ." C4"                
            )
        )
