@plr = player()


@hero = associative_array(
            'name': '§6S§ea§fbe§6r§et§6oo§ft§eh',
            'class': 'sabertooth',
            'sig': 'DRn2Vk1IzBqMx3O60sMnNmkCsg5SGKiHCiHBgdmiKVvAepo0Rn3AAiVY827yWVGQKThlaD03uxFHJCTEKKqWmKAgFoxkRQ8OygyVW3Kf+T5xVeZC5ncAvaieh03jQsQqvfFeJDE8WjlHCaa5we4IJtp+Z+XNFoVyiK09D6DojaoVWvvUQYLR2G5S20OdOBFA8jhmKkFyqk+CtVrRfwWfuoHObNy4b7nihLGSfx/EISrZbd7ABrac8As/A3nsCvuGD1WnAMa308fIKlXWIZCL0AtqOBNLL9WcOUQeww41xh4nDrsR2X0rijkinm9cFuIGdv30+/b98IHGkD/N2kxM0C0sF64JafFBC7ZGQMbRqsXUNyciww7yvYXJ4jIboz77qUlBjviFVynPI9fPJRPsjx1vFw5JksqmFAKZhQlZGln6Y6xYseJ5xker3M81RAqa/pD2lGvAGxh6qJP97wlcy7tOf77Fa9wgX56SxOwD5QnaAhHrD2yv2OLf44+TZJV9W/v2WdTCNEEdkGdc5TcsgueZgWuyIdmalnIgUlZm09E03rvyo5QkZEzRSvI7jzi49brM/BkpGU/YTnK2Q5iAdU6KyMnZc5soxMrg8lnkv00s9GhA1r/M98QJWMmnf6IDhCG5n/oSrOmdZ9JAOFKs+s/CbzxdMKQLEoueTvDMkZs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDk5MDQzMTYxMTksInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWFjZGU4NTBhNTg2YWE4MDI5ZmY3YmIxN2Q2N2QxNDI3YTcyYWM3OTM4NDE5M2VlODFjMWI4MjkyMjZjNDEifX19',
            'trail': '',
            'op': 'false',
            'speech': "",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/give ". @plr ." minecraft:iron_bars 1 16:10 name:&6S&ea&fbe&6r&et&6oo&ft&eh's_&7Claws"                
            )
)
