@plr = player()
@hero = associative_array(
            'name': '§2S§fa§2iki §fK§2us§fu§2o',
            'class': 'saikikusuo',
            'sig': 'L4WRYIK44jShhd4sLrQt7x5dPB3HjhCspNzEUtnXQgmnvOy/WSpMdx5Gb2sEUnXdv+6AqAo3UbI1KdbL2vqpgx7M5dJto2HBSV7ymb/i105dcGcwbjnmfVqU1KE5OXvv1GI+sIJNMXohBY1GKPwj0zRdRx8oFfAKZ5bWeSkqlRWP8CwOsrq9Y7TuAogs7n4LjW2/pPX9UclvIsI2MCG2ov1bkjpiXltK0wMzTYOL48D+xQE+v8dv5mJM5hwz2jdljTjeWQmvNuXaRBtktwHxLw77xIP/rDMVAkN0kYI7ZPdrNI3dLonbcSTsdOHUpk1GZiEnflKaaeuHb6OusdPejWLLtxmbttlYiNR1DGX9YFM5Y8yIZ/q/x7U1XWfwVtSVEpnnPMGelilP6o4QtXoObFiYVvu0VqEgUEb4ViQnDRQbcUB6cvKQCgLUpwRa2r27lkdRrdWOmjs5w8CRwi2uCebp2AD4WL6/RQa3/b3y7gJUljRXtyBc+JQZVRNDiR3BdQGqliJfbUfh0fGRfNI04fTBHW6nUP38CXrSqc5MxIDcbXgvrGSMITG10iC2JL9qZ+lY2bas0ERgWYylc1mqqYf1x+y8sYo8Z16/R0BZbEU5zIOvRQtAnBuHac3Km/io2Xebqhqf6LJI+s2AzLv9zFqb65R/IL6fsC93SLfnMgk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDQ1NDM0NjQ0MjMsInByb2ZpbGVJZCI6IjRjY2JjZTFhYmM4ZjRiMGE5MDcyOTE4NWI3YjU0ZThkIiwicHJvZmlsZU5hbWUiOiJBbWluQloiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2MxNzM4OWI2ZDQ2MWY5ZjEyOGI4N2JiN2VlYzdjZjk2N2Y2ZDdkODczMDhhYmQ0ZGYxYjM0ODYxZDg0Y2ExNSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I can hear everyones thoughts, its annoying.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/levitate",
                "/jump 0-7",
                "/run 0-7",
                "/haste 0-9",
                "/fly",
                "/intangible",
                "/tangible",
                "/invis",
                "/vis",  
                "/tppos <x> <y> <z> <world>"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/shot give ". @plr ." pyrokenesisblast",               
            )
        )
