@plr = player()


@hero = associative_array(
            'name': '§eSa§6nd§2ma§7n',
            'class': 'sandman',
            'sig': 'rgb+b8kSEdoVUdYNsv8EL0Lwsn7Q0yXRggkuI5vU+/ilnU49DNSXw+pBC3s9IEjL61oylm9oWumP8u9oQy3gMcZB5Durx+ZX0VUDouJL+Ar0cY/5hTddVvWLPn6HYpex+xP733cAIO6esnQB1c9I1mxGYqnSp4WzVj84hqhgIif0OXnCfSpp/G5BIRf3y86chPF3Vd+B+38f56qs1t2Ftowho8XRnhDzI4gNmfxEio3+L/zOSITFfFQ3c0FPl3vOvb4LvW4M1HbJcVjjxN5FBqMNP7kQIF/M6w4Lgl6jkbCS8DFPWgyHWoPFCiL3dzS7LJEuDdJNCALN4jCf7Im2Ubj/sUdCOaPyDAFJfzzHsNlgz26neend5tdUXit9zSvPf9kwtX8rjEMlL7RX+6fW41VEHGW13xXvQYBHFns90CMcF8ldSzNC5dFXQ04nfbbpOHRWmVwoozOGfvFVJekMrkySDlHcOYYgR5/iwHb4d9p5Lpul+IbDzMX1/DyWD/Ko4uU7E2V3XBFIJavdlu2APxN10EIan4tYb055+76StkzfKFdU11FPFIS9eSdElWmKlHX4lSI6A2LfD5V4jPau+HRfp8MQI1H+StP78oyXS+s1SEmRNvfjqyosX/eTAeF62RYzcZB19zB3gTx3+wnAm8GUHAtFOq8TvGPvQK1t8jU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTk2MzcxMDEwMDIsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTQ3NDNjYmUxNmM0MjFlMjg3Njk5ZGM5NjBkOGE2NTlmNGM5YTFiYmQzZGM2ZDJmOTg4NGJmNDQ2YTdlZmU3OCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "",
            'powers': array(
                "/buff",
                "/normalsize",
                "/grow",
                "/cast sandwall",
                "/fly"
  
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/shot give ". @plr ." sandblast"               
            )
        )
