@plr = player()
2
​
3
​
4
@hero = associative_array(
5
            'name': '§6San§eji',
6
            'class': 'Sanji',
7
            'sig': 'fhOblx1jimTZghCZm+TvfbhTcgs7xHN8tntt/5ouD6E4p9EyZM9XiW0PJAtVTuVZeNnkgVpfiJyqsI0mRLHsPgyMAdjfMlaH/VGbZf4ftsM6eOTvziXIjuRNhqaRzkrU96cw+9PKCO7MUZHP9BMLy7QOkw/nTbIj0meGM7hBsAR/m/+pk0WEz9gEYlqGg9XfjRgs6BUthBVVwoNXQuUQimYhT6np6hrYZGlH7O4wllvYJpsuyAwb1Q/MMV0RHh/feEk0SnVyz2ApAGtAs8YKu8jRBulKgGbLPy1EUVxAhvhVnOPNuZNk6W2iIyLHIAT46TyrH4eNNcEhxAgHjzHQGm7JlAr20L9SQ6ubjJGRRJKu+4J9Ddr9jhhENikv0jB4GBmQ/geFoP7gSLQ8E8K1mrY4bn3zt1z6lAkVEsPr3mPR0G1Z0RRzXtJVcFciVdlcqj1aq4OsPODEulkeIRJKljY+/tDSN1qr+XBz960IIFLRjnjiDmTpx7Ywo9nJbWuc7feeNVzD+3p9Ox2vSzG7rNOvw+ZZbHf6OmckxI8QXU3s/h7t/YFDZfu0N4awLZ4u89au8BPssJA981KprRiVxGujP5xJr3K+OoGSl92fd3K3eRnqQvcqZUoffx0Ptw+7nG6Fkb82aqdi+sFyX7Sl1xAmlfcMHQteJOChkI7jbbE=',
8
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTg3NTE2MjY5MTMsInByb2ZpbGVJZCI6IjRjY2JjZTFhYmM4ZjRiMGE5MDcyOTE4NWI3YjU0ZThkIiwicHJvZmlsZU5hbWUiOiJBbWluQloiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzhjOGZkOWUzNWYyMjRhYWU4ZWUwYTkwYTUxMmFjNTBjZjQ5OTBmMmQzOTFlMDcyZTRjOTc4NTI2ODFiZSJ9fX0=',
9
            'trail': '',
10
            'op': 'false',
11
            'speech': "Diable Jambe!!",
12
            'powers': array(
13
                "/buff",
14
                "/carryplayer",
15
                "/dismountplayer",
16
                "/jump 0-8",
17
                "/run 0-9",
18
                "/haste 0-5",
19
                "Can jump on air using his skywalk."
20
            ),
21
            'buffs': array(
22
                "/effect ". @plr ." 12 9999 1 true",
23
                "/effect ". @plr ." 5 9999 50 true",
24
                "/effect ". @plr ." 11 9999 20 true",
25
                "/effect ". @plr ." 21 9999 10 true",
26
                "/effect ". @plr ." 10 9999 15 true",
27                
                "/effect ". @plr ." 23 9999 10 true" 
28
            )
29
)
30
