@plr = player()



@hero = associative_array(
            'name': '§0S§9a§fn§0s',
            'class': 'sans',
            'sig': 'TTuBROaUbt2PKEyFqp6s/uMFo9LN9wVnh9uGmk3jxmnLRuhV5/ucD9vpMdhiTgDRRaBnNZ3wSfrhS5FClz8G35ECzSRfl5zNUA3MHGRMWRKNiE4saAI3c6m/LGlNGvCbnMVu7F4cK/FVazVRgHe0DwLD9It4zAYHYm/m6TOgSeBSlxW2YZRb9zK2An3Ml44O6pbELJxOmlG68/N1JkP6aqCLuR5Qogg1+jImF8KOTgv+ejnpKdfqOGNDl+RY7+zgA/OLxfdtfeHnpQfR+Az7A1D7KCJWPQ4lpgfpEN4rdlAiVBoMmAheAmIV0Ws5x0feWmlf70069t+/RJMzfjWXDBC68gX2jIbDN523xaH8DMW+jBEQVGD57k8aSPLAAkClDB2qCXYRRIhVeTGqEFb/a7G7JTO4j0/z28QKlD3ESjo5JNXO7hCmqr0mwdVEGy9I8Udf08tc/fo9+a2sMSchlc3IfX9dZydjJWT6qXqelKOR2Px850Bk5z5Vvzw20j62AT9zJWIh6tEjK2f2dNQh0QrMdxomxMJUz6TMXaFaLO0o1809PfSzKBQ+UhOjBZVtMM/Irw1LFqZrrlMn/u7jdrfvBPzeAXQwqB0KSZmFlaVGDDrRWKovCwAsdpOn6pgy/H+/XymIrehkZ2jwKU234T0AOFGHjrr9u2eKI7Uuij8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTY4MzA5OTY0MzYsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJUb255Qm9uZ29zIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zZDlkMzUyOWQ2ZmNiZDMzMjk4NjBjMzM1Y2JkOTY5NTc2N2Y3NWUyN2Y5ZTBiZGNhNjUyNDc5YWM4ZWMyNjUiLCJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifX19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "You think im just going to stand here and take it?",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/shot give ". @plr ." sansboneblaster"                
            )
        )
