@plr = player()


@hero = associative_array(
            'name': '§4S§fa§0n§4t§0a §4C§0l§fa§4u§fs',
            'class': 'santaclaus',
            'sig': 'l1zQsGmWk+9hpPRNRZ+b1Y+XXpipeunk6Hbx5oG8ciUOObqL1XttnJVM48TdDfnHVaf25r6h8UZ2vdBUTpV62/mbtSqAP8/VPJ9MxfRv++SL6C7s7S8WHrt642adUbNHoGvOOpl3zAInUW88UNCPblWNiKjQDzu1xD8QsBRS3ZPnaqQnBkT4ONG0axUjvTEHeOFCQgSGvUmHkQ6oXL5khh/lFnezV6ZRuZwcPQ4BiQIqPQxxjYrEZg/ktWXyAH/0vAROclOrZne+ekRq/LRyeRWrk1awb1etYgAzRYpbuH7qdBJUFGkk6lJw3LGUxQgWIgXt+KsO6XDdJBXXJGIVtLV+4EbCUfxd5ejox7jFx1GBnbttIUFiop8DAVJRtW/r200tvyTGCV2FCiDxaJX2aZ1HyhnXTvWV0FimlhDCInf0os1UgGs3P0fJHcXgkHEWqA9F7Rx2tceOMg1fgivsvBcjQ83VP4Jkk3nGx5ZdQ8WXPGomD58efEinKkWERZxy4ye02g6W5YTxiPcfKYY1mq6GAhhHO53Gx4b2M0ZjX9sB9ov+dtKFDi3xW72ugDbNa1CIR32rXa70lrw1EMnZ27ia3EdqLx+2Aqy+9NIo7mQ56tv755neyjEzJYBNI16aHsBTrVR1VY6mbBIBEOJvtaaC/d1Y5+nyT5XfbR98udk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTM5MDQ1MzQwMjQsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJScW5kb21NeXRoIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83YTYyYmQ1ZWJmYjU3YzE0YmJhMmJiZGYyMGNjZWZhODU4ZDhmMWJjNmJiMTRkOWEyMjMzNWRkYmY2ZmMyN2EyIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "HO HO HO!",
            'powers': array(
                "/buff"            
            ),
            'buffs': array(
                "/effect ". @plr ." 2 9999 1 true"               
            )
)
