@plr = player()



@hero = associative_array(
            'name': '§eS§4a§9v§ei§9t§4a§er',
            'class': 'savitar',
            'sig': 'kPz1FipicEjkp/2IH62cGlHg6bIdWn2LI1Vr1ufMOZY+v/yTUR/5TwmxH9EbK+sqzosRHitcgthR2D/wUim0IgSp3hjV4ufjpE+ZIkVsm+MfVfXfrQA45ei9zxkHCkY9zofjbfFTZx54+Ab/mysrleYnp54UOcWm8DM5eg1PaV8s8/9gxhgIW+7kSmgJ2xRvO0ZMOs7E17PuxewX6pPqIClfLZS8wD3i9qYN9w0I0T23X0MSVKAR4QcARHepAv3VySfto6iR3n10I1wmqOzbedXn5kfR9jbK4JskE/xCJ5cw9w31zFHDG6nZyvkMYfE8x1G17UbFjGelq4beUL6aoAdoqHaDgJKlYsVRnCG5CuHnVVsH2hr2xhvjwUj4kpjOfi+9GNKDBd5CSxTiLAYm6ZP8Jtr/ZX+C5HkDuRMyujW2aq8vkkMd+A8CmFgtDsHfPK+Edbf8xFmv6bCjoZ2IcVKLMZCsIJ7eQwgwfYBjtA0UNBbOLn53C9xQWgsKAD4KS7m086/BbMikmNS90fpPfCqFtuN460H8Qcrg16ngPRkwXZjLRvJHRtC5zGRFv3i66Hy/0M7tBYqJrXX/RWyqrvc5PCtYrYzYv94RYk8lneBPOvF3gP+npsYpysKM2WdP7EmLF3SR3eSzp0xxLxjbnszsExwBOEdjCjuWq/H+O0o=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODAwMTQ5MTAwNDUsInByb2ZpbGVJZCI6IjgzNTRlZDBkMDljYjQ2ODJiZjYyNWRmM2YwZTJiNDEyIiwicHJvZmlsZU5hbWUiOiJMZWdlbmRfT2ZfSGVsaXgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFjMTgwZGM1MzUwZWUxMjQ2YmQ1ZGMyMjhkNDVhNGE5MjMzMmE2NjhhNzI0MWFlYzUxMjgxOWEwYjY4YjQifX19',
            'altskins': array(
                array(
                    'sig': 'fRdpLkSgBytngu44ld5UFfx6dkZIqJNrL7mxGL2C9c9Psg5HoYdAcGUfooN3yNgYTdIy76vWKiFN+FP5T4D6/F0a2v6l6zStJzBZio+pmg3hZQ/Zy9yu3wCejZtdAg8cCZvMTZBe77Wicl4tr4hGo5t6uwaf6HqYctY3HBfdmVUI0vlN+7qWW4nfunlQhIy7eCJNiGP0qASYtml5VXJs646wzzGzA3hV4wxraVCUkx4WoqZH8P8pJ3lIxDvlQrfjjO60vC15ICgeMAltDbiP2pjbaTfqGSBHs+TtRm4lsm0z2fjHKuy+6jRPbzcui6QkSP4c+09ODLfVW4PKLBtTLx3nPlPCPPqK7Nsp3joFvzBYYNKJPzlFYInM5kcl6TJvY/6/M1T4fxVPfkMEoX0wyiVt5oPRPdZ/ChUT5SxWHSFO9334s+YvC2T+MpeVBRDEAk5KULU8Q4lJKN2kq31X8S2lmpHGuWD8cgSSXXtQexBypc/CRTHH08rnKbJt5OriiXTlEJUldgTg3ohfFe4VHKsh2yGENkOM5TYarcMDu+DqvKSnKyX9e/h595Pmk3YD4pYtujAFlSqM1hvJK3EozmmPPf4g+vn/OtBBYUNG55+CFvNw63oiXXi7qPYyj96aSaLuof7jygwk7cfhUbIZLbm5HFg4UwBw/kqK9p5J09Y=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODU3NjE5MTg5NjQsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yZGM2MzdlMDNiZjRiMzg4ZWQzMWI4NGEyZmEyMWI3ZTIzNmZlODM1ZjBjNmY5ZWVjMjZlNWVhYzEyZDVlZTFiIn19fQ=='
                )
            ),
            'trail': '',
            'op': '',
            'speech': "I am the God of speed!",
            'powers': array(
                "/buff",
                "/carryplayer <Player>",
                "/back (in the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/whirlwind",
                "/run 0-9",
                "/haste 0-8",
                "/jump 0-3",
                "/thru (phases through walls)",
                "/tppos <X, Y, Z Coordinates>",
                "/invis (makes you invisible)",
                "/vis (makes you visible again)",
                "/vibrate",
                "/stopvibrating"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
