
@plr = player()


@hero = associative_array(
            'name': '§4S§ccar§4let §4W§citc§4h',
            'class': 'scarletwitch',
            'sig': 'NiPq0rA8jrjE/YceGQa2dPR2lKssu3nAhMsBVelrRn2sntssFGJuZ8OVhTB/JpJ992gIDj6QaB840IciauBFdQ1O/C0MebuuMxlXTEOQQjX32oS9MnlHM43aoFFPMh9tyl1wToKb/8l5Y4su/Bt8tiyTiFejgDn7ExmAXBPZL+mf95Ggfekv2KSlyVR7OtGlS3H5frVEjerKgLpH5kedqLnXxHTyxoPPdOqQrwSaZHIKmv50rR9puymvfttAD3i6io1pkJC/IrDMN3Gr+1ukXjADzYMSwGDGWMvP19MNTgfTMMXYrcQvUTAlO0rScrWAIX+ftByOoVuOlwLtbLfsQ2dKv0kH01Fh+7VASAHKm/oQtHxKp/qKQ0lC0AQDo6t4e+dbDxFn2+BXyVzrqjhhK+9aXR3oQ9QRdIikjhdSnrcB8VmCzEer1NVstT0b97js86O7GWDou0U8jNwxCTzmHEgd70w6VKL7IeQudd3JE8ZAAUtoDkr/XXTKVACyBX//B++lrHTSufGGMQo6YVgjGpy3ooCUu2VxPqVQj7JwANcVF13N0Svuz7HRUS25uUzp2ZdqN11qngMfL9pvAeFSH7eyCUq4Vz6lWMNxE5ISh71jJ3xuz6EiLY6Yv+ZAqwfJZHxs2n0hVfUe9mG5eR19qCd2bKHgHwT6Htm+39guJjU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDE0NDYzNjA2ODcsInByb2ZpbGVJZCI6IjRmZjg2N2Y1NmNhYjQxM2U5ZmFkZTRkNzdjYTQ4Nzc4IiwicHJvZmlsZU5hbWUiOiJIZXlJdHpTdWciLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mOGIwMmM0MzRmN2MxZjg5ZWFiZTMxN2M1YzhmMTUwZGRhNDg5MWE2OTQyZjIyODNmZWZmODJiN2QzM2EyZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I cant control your fear i can only control my own",
            'powers': array(
                "/buff",
                "/caste telekinisis",
                "/cast forcefeild",
                "/fly",
                "/confuse <player>",
                "/cast manipulate"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9  true",
               "/shot give ". @plr ." scarletblast"
                          
            ) 
