@plr = player()



@hero = associative_array(
            'name': '§4Sc§far§4let§4Sp§fi§4d§0e§4r§f(BR),
            'class': 'scarletspiderbenreilly',
            'sig': 'C3J78rGe9ZyfWIVxqQXHo/567WbexjfGCUzMX+QhWNy5F07Vov5oa/BBsS39uK+3bHvKj0aWk9JF/Wus5+Nt+jDm5sOU2ZUKOXE306fozqdGleutsKtGRAe2EIHYjxdwwnz+qQwOBE+kuHlWtHBFXU/JW7uN+zV1eOtbd3fDsLSe92qqINI/oYNEpv5pkmnPh5cMWa3kUytpkyUrx/7tvKyy14R40uiMUattcfNAunMBrQvrrRAcrkqjMecbcTuv/rlRd+dkwQqGbtvL+ZbgIGsfECykMIapZfcJNfTKlBFjl2jCVWl0CZSNHqFgTTxgjwalYJsaqh6X66BuoaXuahSFlcvHljt3NRiwmSJyIpQAVnQ229sWfMEE5axBC7Y9cL562SyRXhXLfF7LGMizeDPN8rSi1UA2/cLL+Zr2dW8agYG3+MQFsh7wPP1T+umexMCCTmfSzf2Z8iGP++g0jXkzg1F/3YBPN2QF2hxCWFUANy5ze5NkDCgJffkSOBPvqkHk9F3BPg8BWlgTyZvi15d2gyJg8tX8Li62VNzIWkvvPCTFtM7hypso9d6+NBwKbC4iNg4WFa8VJ8wb0DahNZEbooUuiA2T80R2wMobvE41E1TkaPMMry5ArV7Xu73ilMEl01f3mtnmPn51Z1jPTrThqlmte1wxiqmZjNtTN4Q=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODcwOTg5NjUxODQsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjAzYTc3NGU3MGIyYWY1NjkxYzRkM2IyNGNkNThlZWY1MmZjOTg2YjZkMjk0NmM4NjE5YWZhYzYwZWY2NWYxIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I'm not just a clone.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-3",
                "/web",
                "/websling"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:web 64",
                "/shot give ". @plr ." webshot"
            )
        )
