
@plr = player()


@hero = associative_array(
            'name': '§4S§ccar§4let §4W§citc§4h',
            'class': 'scarletwitch',
            'sig': 'knaSzBOfQtzrZFemn4TuovYGHFs4ta6ZI9V57bRtrnDPo26rVpXToEVS3oAprEjZhUk9Ka9yYy4vSsEmi9ElDIt8bLGaUH5DE6mNk+lEy4pkLpO/XnMuA7OFiRFTEmdRhlY2T4FU3DhlNa8opuCWtnYbVDdcrMoj2yk0zqq4yh3m0v98fltOOCmAaipHMePT8ZygeRJfogiyTWt2tEffyfvyT5xDMhmNKmF/NJyHMt2SioisL+XTMBqGkcwGZbnccgfgYQq8Gd6x7zR78Ht4tp2sFxp3vpKaOCF5w+QjiIX51D6pKf+TVkhK7oyF4ExhvjxaodLyVJyUhXiuVNmq8aspbhqsg6gyaEuFYYUzRlrHWfSWEvpkBtlY2xTppM/PmAtOFoDmnx/AngXrRnSxrseeTAxS1olax5PlJmeolmwIxtSiAm3UD3kWig1buLAXLn6/68idZo3EPdrVpP1t9y+hdfbOJsFOQXiUqhEnd/31Wzf4bCjkmpHfeKTKuTX/4MO3BW5pGLG0yGx2RtqA6HjNSyb6M/euPe4wy6qTRTz4sGfIGEIopBYBcWz6LNr0gb1RiNy3+sFiU3XajrSLUl6iYnv718Q1iUm+tR2kCLjlxvsgIGpCSvktzIGvODv7nr+A6pF9pyIaJtdV3i1EYY6l8yUUzdt0lx42hrotsSM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDE0NTA5MTM5NjIsInByb2ZpbGVJZCI6IjRmZjg2N2Y1NmNhYjQxM2U5ZmFkZTRkNzdjYTQ4Nzc4IiwicHJvZmlsZU5hbWUiOiJIZXlJdHpTdWciLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mOGIwMmM0MzRmN2MxZjg5ZWFiZTMxN2M1YzhmMTUwZGRhNDg5MWE2OTQyZjIyODNmZWZmODJiN2QzM2EyZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I cant control your fear i can only control my own",
            'powers': array(
                "/buff",
                "/caste telekinisis",
                "/cast forcefeild",
                "/fly",
                "/confuse <player>",
                "/cast manipulate"
            ),
            'buffs': array(
               "/effect ". @plr ." 21 9999 9  true",
               "/shot give ". @plr ." scarletblast"
                          
            ) 
