@plr = player()


@hero = associative_array(
            'name': '§2Sco§arp§2ion',
            'class': 'scorpion',
            'sig': 'ODzY0lVQsLg4+O+t6y+przsL+iGP0Xe9tPzu297BxPGgN61XTd+Okl8veR5ATEcJY1PFTbgC5XCkNgj2Rxix4vlx1nAIjObZsfynFURaK85gGg7ydA2DkatHha72YuzlaFOtJr6EWTyBnyFj3Bz1QMlbpoO5FNZjIhf9y3LUR8UGEletjyk0dXLkcSkdUFxidmWkUWsq4S5UgQ2v8WK/W9aqhBVldEFHqOO7L7VBX48JFZac9r7M9jq8nf7epKZGYwEBnIZODHAnTSunva8YElUaxJhTAF/z0hkqDuc5wwxT2KlzIL/93UgHOYMofudc5ezuHqQJHqoTMxczo4Vz6ULxaNjfAWu2wj26DJQYhwde3xdJ3qHKYkX8J5xGrVRLY0ITHfRfKxf69F3Jf7TRkVyMe83Pet478IWb+lo2tS2ImIyda/JHhlixmOiuMS7EW9p6K4/mb9YvzLIQhlV+C3LyJwWVKdInntHbtOJ7a0rXB61biQ4HQ8QCCwFeEg9rt65egXB1nN8bOD9X5Ww69o6Sdfl6Kf1WVQMlDDU1IxNCHzka31fotIKpYVOUSbv6JI/7xodzE7NgkZoAbEpqw9EdBUNi9rvyz0gG/+ip9bCfDWPX2UgECwAYMJaj0QaVdKAARBzY5Ufq4b0vsV1cq8AEfIl01U9yuTuLLCfUbU0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTk2Mjc5MjQ0NzcsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzFiOWVhNWM5NGJkYmZmODJmNjU5Y2M2Y2E3ZWQ0N2U2NDIwMjExNDY5Y2ZhY2Q4MzE3ZjEzYmRmNzdlOTEifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am now stronger and faster than you Spider-Man!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/cast acidshot"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:fishing_rod 1 16:50 name:&2T&aai&2l_&2Wh&7i&2p"                
            )
        )
