@plr = player()


@hero = associative_array(
            'name': '§eS§3e§en§3t§er§3y',
            'class': 'sentry',
            'sig': 'O7MEvtExXvBFZfhAzdk0I5XWChY/uSCbTthoTS0xVpiwk/zdW/XenFVQnxM+SWxytv7DFrl04Y+MJffnGBz6rie8PqQ0ardbIGkcA5ONUDo6Dwrq/KsHv9skX+MlWWfXvCkL1yaphQSQJLpZVHXaznw6M0Fcm/zTfNgXv8vmnfbr5S6ch3d94AQETha6AeFQR0kYxwP4E9N4g5d4VYrRnr4guQEn8cgvaISxp6BZosLqUqDIp8ezqTtRS3XL0QXUKgWt27wXFlnVSrMgze848AzDfJtFpAlp5TyWHa9kWMy1IP/PnW7VTwJ31pC+7kMpM2zfycLP6VwOcGY8EoD9TszlB76RkgUqw030YO2JOy2VhyEMYktA3OFgMaWu/hz2pxOpz0qiAaLtXCQ82vHE1gHsudRJGzxhbe7X9/ywIaRmL3Hj7voump0tv5W00VibRn3HxxyVF78LIEuzyqCAMK706TEO4sSbK8KyJ7mIzIwRV7yGdVAVFbnkcRgY+4Cq81X8WVOFQQ5svz63YgXopcKLlKmCLYoNiI9ft/hWiIwx8DVN5NmWuVEnEhOX5xWxwW/tidMUSPDXDXK/SM0q2/Vy9X8Pko5eUS/KlRS1oHuvIsqW0DqMX9tS7ms3SXy2P60/da5TpGG24ax89hA1UeJxoatb8Hqda9rmL3M9QSA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODUxNzg1NzM4ODcsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTU3ZTcxZWM4YjZkM2VmYTZmNmM2M2Q2M2U0MTYxN2NkMWYyNmQ3ZTQwMjE1ZDEzYmJkNzRlOTQxOTJlNzIifX19',
            'trail': '',
            'op': 'false',
            'speech': "I don't throw everything into the sun.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
            )
        ) 
