@plr = player()


@hero = associative_array(
            'name': '§fS§ch§ea§fz§ca§em',
            'class': 'shazam',
            'sig': 'Lg9yVIGpjBX3xBjArKU/R6Y3GJIgH2PgKDJ+kD/pIxWuCArpSuYwZ1C0aBsot69WuGd//HDhFD9BBeOX2ijSJynV3/bTCWB67pJxeCylekRgiwk9aRz2ePAWk2t30G5LtVOcnPYYMzqrvJmY0pioP+sDkdP8gNZyeA6+l9fU3KemO0Mm4BKY3gXZdXs5MtGqhjx1r+oSEZ6+q2+T5hFXsXAJJJyEjeFTQV/sYX3in2DkDbXA5reFAVE+R1UI8oKOL3mdjSBUQPxf2UJyD12uMvG9D+aV/phflmb19O13n4sMuJsp6DAHENeM1/1hsDjz9gqbgZkt1Qj0JaKYc808JgvbG2ZxEp/yCY+o/e7qoUaX1K4eHWjb9hchuT2F2mieVsdhCqOmVomkl37vX5C9KSbrXSPTwdjxJgqm+UVPL1Tp6dhMmFIQoyXT1HBQrkT30MNN2c0K0bpLeU3l+9cpCBbkEBEiMY4P3SKHVu5KkTdECz7koneOx2UHflO6CmkL7mzEs9wD3zzIq4K/lIi632wVrBDp02ZcPzTFDEy+JBlIOSwiNiBnhzot8fPgw85ur8qxe9HSPBLfrWRRtPyR9q5MWzUsIvlgToyc/xUuOkdZ6gw5FzeuD7o2qyOgq9ISbd+EMOxdZsWVqdwiFOywVJknTI8YBHsfcWYGZH0+gnI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Njg3OTIwNTg3MDksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2UwNDVhNTU5M2I3ZDcwM2E5ZmU2ZDAyZmNhMjZhNDlmYmYxMTg0ZjVhMjJkYWFiYzYyMzA1ZWNmNDlkM2ViNTgifX19',
            'trail': '',
            'op': 'false',
            'speech': "Shazam!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." yellowlightning"                
            )
        )
