@plr = player()


@hero = associative_array(
            'name': '§2She-§lH§a§lU§2§lLK',
            'class': 'shehulk',
            'sig': 'nwSCU496TCj5VruMFD6N4VFniWP6UwWx/Sa2r8bt0171kflB9ZUjv1sQvcirAOeSKUAtr5RZ2Il+9HYT13yZcqtSwL6xQzvL+R4Zp7w4X1F2n5n3YWNuHnz6UIDhsXoZYLtQUwf+c9sbtp3MFHNCOY4zQw6EchQirRLGd6PNl3MCuQQwq0t3XNEuVaMFfSYAovjAMeYXEYSftt19ZgJ5yPZklt56MasrOPo4hZ/GPbH00fJ1bWUfEbTGQCT1hzyg0UKblpMuBzQXs19IZzw1LTfePBjVbtg//xlo3FeEdStKT6a8y4aGd3YVeZ0+dF9cWD6lJbj0j2s71mFwJWUNEFsy+fiUkT/FNF/ohcZ2T4HvkrcxP8no6FyCzhdUqqNl8ltuWevNdSJgr64Ors1zQnMgKTNWwpwa/Xm1dtyCTEjjIPdPxcQzrEIINvB6lbohzdvPOKegamgGiEYiReT75DPkyFNGKT+njDPt9IJKIZ7HjKLA72bntnwtliwS3Ub7enQSoY/D0sI5eFueYl8adVL68qwj2/5SIApXCtByWXMKv9QLPsTrStWVkFMwE4/Cx34wdNfZhLICYZ4yChsj40mrl8yzDsXs+Dlm2JYgYNAxidGNazLqQb7BW9uhmunbqCqLRuEDCJjD6b0vtcRQZaHq3z57dtfkNNnp5iopUJI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzQ0OTg1NjYwNDcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jMGQ5YzUzY2U5N2UyOTQ4MmNkMmE2YWU0MjQyNDlmYTNkNmU2ZWQ5YzQ4MjIzNmU4M2YwM2Y3ODRhMGFiZDcifX19',
            'trail': '',
            'op': 'false',
            'speech': "SHE-HULK SMASH!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-1",
                "/haste 0-8"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&aShe-&lH&2&lULK's_&aGlide_Wings"                
            )
        )
