@plr = player()


@hero = associative_array(
            'name': '§eSh§8o§eck§4e§er',
            'class': 'shocker',
            'sig': 'x9zixnvTAcGf6AsXfcPGStigom16dykj+IUwPr/gk2wKXlL+78JUv89RI2fxPQ+lYsFrsFQtR9yxFwdV07odoAFA7dHB5+ZNh2ydjat1cMxEcLjgueKbHjmsk8/z0SDCkZr84dNJZKSWjJplOtyszAmmD+zxBxofEOxJbX8OFnwwunLValNIbHA6iuWmWE9k6QGFdCN1tSroNVV1+3G3jVhqz94blCgDQpZRlc0TmN8rCDVIbt/+XS/U9zVzS3dEVWEmRFF4xpZLU1TTDpQglYIvN+2/N0hbILVzplLkfTmQ6+NjI/L7EcuAEXYM+YRnys4X9W2SMs2y0iZSsFuUW3cfY8IER6ycuGBML7+OKtvh157tQep/6xU7+sn++TKp1RuPZp6XOhk15xu0NPpwOTdnfg73hHcxJM1wW0sE6mQm7sP0e1G+uStCrEzfWnjk0L6tQ78v4L2wMjbcaGgydCvfrXfIg0XGnxJTXBo3TORDV7+SopDmAkPwQMwRg5g7rQVk7QSi9QcO8EnELk8Ef41aWP/dtwFffXeaK9cyHz66OmBwtT9J9QniajVY8ADMcg17AJXjfpPUAbS27XdvXCzVZzDUCwHXZv1zC5oO+dV/BvHVuZvItdGAurSibcWkECWlCWw88Ny1+T5RXnELJxA4Hkuxk6MxHjDkA5GhbzI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDEwMzk0ODY2OTEsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2M5N2U5MWIyNGU1MDk0YjQxNzY3NDI5ZDdkNDY2NTA3NTIxZjhmNzJjY2JlYzViNjgzMDk0NGUxZmE0NTQifX19',
            'trail': '',
            'op': 'false',
            'speech': "Your in for a shock!",
            'powers': array(
                "/buff",
                "/run 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." shockblast"               
            )
        )
