@plr = player()


@hero = associative_array(
            'name': '§eSh§4o§ec§7k§4e§7r',
            'class': 'shocker',
            'sig': 'gXJHw9zcGsSj4DGpOWJbgateKKNElwovIg/1JekS1FzikqdIt4BElMsICUvQ/2RfjtU5b51rLhfgZFEvomjDZLvLNjGwAdJgH/3t1pPQhm7HbeQzPs1TmllTa4shEVgoTx5L4b9GDVLSSw7NbunxQ34T4Xe4nnb6Kh9Pj6lDdsYQP7eLaGnGfKPW+lDeKNbsgSlSvl0ODtVVZ5a6y4YEAA22NpZ1DsTU0XjwmaXq5VcjhKMAy8vuwplba96GxC672w/5lNjWcu5qwnQk5Vd2un8kuskmQU6I2ng0OhHeGLtBXe3Yt43mHe+s/iG0VmBw94sgzVKGbAZE9W4iM9pT59FgE9k/djWLqE1ozsTKdIr6FbdKwmjlj44M2IJBvwfJLwU3R9astRoISyhGJ9XS9atTXRcCDBubN2ppNuGFiZN2OcHYpNn1C72jOGH7Qti/27/yvnMGE/Xwb9ENAf1P+2pctcDT/VZrVDavB4T85dPJcp/E4jvJz7qBGFAVYQbHJBQU1beTKIqkxW6riKrOk72hKGfSiu/Jp+MK+eVZI998CXvTv0dfgsI9p4mAUbLinDUmvmjquhuVhEo4f1yNHzw2N9+p7JdcW3ZEhLNbXEJcUT/I8L9qhAXQB40fMqM1DMMs/XhilxYYVmJPL75NDKdOUNhY9dzuVOPcALcRbew=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDg1Mjk0OTc5NzMsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGE4ZTRiNTQ4YThkNGIwZmZjNzNkZDBlYTQyODhjOGNhODExZDNhYzM2ZGE0M2RjMzZiZDA5NjUzODM4ODg4In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Your in for a real SHOCK!",
            'powers': array(
                "/buff",
                "/run 0-2",
                "/jump 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." shockblast"              
            )
)
