@plr = player()


@hero = associative_array(
            'name': '§7Si§fl§7ver §7Su§fr§7fer',
            'class': 'silversurfer',
            'sig': 'wbkkOO8pMKcgtfqvzY+ZCXSJZ0y6AVS5OVNXpa2kSGV9BZLUIJjCdB9t9aIUx5d4T/SHx4VIkhXlVTAEUw3w1+3qiqog7Yf3GKfjfiLAkfT9rojTVxokeH7m/F7i5iMyIyJuoSQLeykVpgncrI2j3QLHAc3pk0fy047KXquWAQ4JSg4IuvOibQ7qDzOa6k/4j77turK5TxCzKuMX/z02j60CpCvgPkGbSVcXMvRa1pwDmJD/3hys7EXYixJ7VM+hOgihu7pRrB42mZGrBLQfnxBgjV45L79jITC2P1gx/dMvsEZXUcMKpd8NoqcYCudQ8mmKEK3KrAXzXxLuZCiXZMjsr/WCdjuQkVhWGXkeGnsXlPsKpRhxjBg9v6/9yzeRqytjK3aaPxRjOAPc+YQt5ZV5gu8cmxqrn/QRI4/SZLkxBtLa+hlunDfTzkELDPUyYC38bCOV1vXHw+I+ykEAURJ4zcgECIty82R4xhuTEzQ7AK7wqB/xKlBofQJ3Xg3vFUKSVHGl7jscOqaNhQhZT1NCSxQmXB9tZBzp/4qeQAwIFS6p88ONmGwMzBUObtJLxvXvvlcxhn6PdtcYpmysrVvY46B+wvGxJ3LT4Qfu0ltD6oeBbFrUo79BnwiQ7YPq9+YZoqUpHCKCYBlIyQOt7t2S14suok+A3n4i4feZJZI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg4NzUxMTk5NTgsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJXaXR0bGVUaW1teSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDYyMzgxM2Q1M2UzMjVkMzkyZjRjNGY0NjI0YjU5YmEwMWQ5OGJmYjgyNDNkZTY2NTdhYzJkZWEyNDE2NGMifX19',
            'trail': '',
            'op': 'false',
            'speech': "Surf's up, dude!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/disguise",
                "/undisguise",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-5",
                "/fly",
                "/tppos <x> <y> <z> <world>",
                "/tangible",
                "/intangible",
                "/thru",
                "/mindcontrol",
                "/stopmindcontrol",
                "/confuse",
                "/unconfuse",
                "/disguiseviewself",
                "/heal",
                "/heal <playername>"
           ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
            )
        )
