@plr = player()


@hero = associative_array(
            'name': '§2Sk§6aa§2r',
            'class': 'skaar',
            'sig': 'mK6yUgRTb7Kq6c0fZL1yqIizOhre/W2SitYU6KcseJHSzaXP8tESKeKvYhzinKJOTZA9v4DJHDby6/udMBBGeUEy0PbqQjsjn2mAAGgge+GEBU40u2KkLR5yBxihwlV7wNjc5YDxtXR0fVIc5bm0s7cnQS4Vl7TyHR4zIqJQfJN49onifzykP4zu1+P/ntND9JOjfArr+0sLsOJucA1WgvxzxIGANyJvXsHw53mRDxyB0qPDJQbEHo4ttuRQMCIMrQ26Ue5ygtmSvZxhTDXzNbzegAWZz26kBz24ViBNeEYc/aY3LrVsXUpnIuX7Q1BhLnMXZSCXZIRQojN5gan+iF5YhkUAL0mFUPcgrZ9a2DtfEPVnBpDdo+1jECq9x1poGXFCi2D18eOe5KVW1ZS3TufLzesTEaPw+EYDuSBFzZWnW1rmb+j5nmzCAdl/R6n5FUTP8bpylOFuYqtNVRGXvr1jv3cUBQ6JsrF7/ujwOAT4nfAgNm+6Z7xSK4Y5VsSDkzkPyKqmPMzB1ISEwDFfeMGd/JzcwelCF+5DAyH2CRXYpZ/RD9EbmPdOjPa1v9uHdAjbhxrOx3ViQkRg+mikhKr8xng5Mh7M0D+CDup+OUXtBaVvMPeqjs76Ll3QhWyQPCqvRwzbTSUjXREOOMCUBakEU3UjQfRDE0/Ct2Eauv0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg3MjExNzYwMzcsInByb2ZpbGVJZCI6IjdkZmY5MWRkOTZlNjRiNzM5ZGZhMTc5OTJlMDU1Njk0IiwicHJvZmlsZU5hbWUiOiJXaXR0bGVUaW1teSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDdiY2FhMzNjYWZhNjlmMWEyN2RiMzVmZGNkYjY4OGNiOWJhYmI1NDkzNWQ2ZmU1OWEzNTUyZTE5NzU2MWYifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am Skaar! Champion of my planet!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-3",
                "/haste 0-9"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_axe 1 0 20:2 16:30 name:&2Sk&6aa&2r&6's_&4War_&6Axe"
            )
        )
