@plr = player()


@hero = associative_array(
            'name': '§2Sk§6aa§2r',
            'class': 'skaar',
            'sig': 'Dpbjp6vSjJiVwKxFEyfyuWSLYSP5H2BBE+hweNIQLPlxlJOy4r3lcK54aKa03aq/i+N/UuFVnZrx8H7DvkzRamZ5SM1644h23S30BF2f6a0UHIcsW+TrAheqeM4++Fp0qNjO7LCkGQ4otVg03QOhtYLy61FnHUungExD/wv0nc8KdxhT31AjD6fG5Fz5fnWRHWa1qMvqM0DjLoRZHyfOqB5RyziB4RgbCJ/I+Hk0mjyuACmqdTtTkmvW3WOMzSirlSeuvyXihnyeGd3fTW9ENPY27+2G0WvpCcTScBjh2rBTXsa0s8cceIdWpM2SYoabgoh9ByiABp7FxSUYpLa80hRiCi2o6jI3oFkH0DlPLLrTMKkLlIGISOhP+YNIWjwcUu2JE14Reu1rWEsx30GCt30g17eV0Fd6ylBVIAlTawEDF96tgIZPJ5r4oFD8qV9CO9aCSYSYPlWUDgCe7judBfEkFEuJSmC5++PllMjLDuMN9so8YGWBziRE8IJ11cnmhr9QPZrE7tE3gK9iHd2sYgv3bt+RmhkV8BcTnsdaNxqoI3DLi2JGDi7Ub12RclIHKaWKRWK36Gu3GhbXmoTdqZGuL7oXB7Tah+/zyceWNU2b2FMlGM00EvpYUk/3ZWoR8pWyDqSo34Cx+i8ffPBf/JwnxWgKWh04XwJ6wBF0HLk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE0Njk1ODIyODIsInByb2ZpbGVJZCI6IjI3NWFhNTQxMTg5NzQ1YzRiYWRiNzk1NTNmNjU0NTE5IiwicHJvZmlsZU5hbWUiOiJmbGFtaW5nd2FycmlvcjEwIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80N2JjYWEzM2NhZmE2OWYxYTI3ZGIzNWZkY2RiNjg4Y2I5YmFiYjU0OTM1ZDZmZTU5YTM1NTJlMTk3NTYxZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am Skaar! Champion of my planet!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-3",
                "/haste 0-9"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_axe 1 0 20:2 16:30 name:&2Sk&6aa&2r&6's_&4War_&6Axe"
            )
        )
