@plr = player()


@hero = associative_array(
            'name': '§fSl§ce§0nd§fer§0man',
            'class': 'nightcrawler',
            'sig': 'MhJLdpH3LwX/KbejKk6IX5B7gHlyfELXglD5BbjnfOLcj35paXL1QqaKFjkDZuSKKFbwqc4fYcNx7WQQLdMKyOWsDjmSSz4riAgJL6tY5LRmLo2QO/EmzyjA1+V9uQ14FyrDFaGBB/FSGvV4bAEOPvwy+PnXjyx32cNDfpzuMbTNbM4I7S/de2hzQXQKCJ+GvadFpmioZ7/OkA5jPbo8y0ZifjhDqubdUUm+5cRFpqaArnKSAgZl6C95kx/xv+sO6slNOMXb1SCPf4qM6x0ZW++9mbw8dGCV3lISNkdlYTSjwXrkZes48rLl4BDPfnSNeIOxsya49lTMouvvlR5jvfR8/Lk9Y5XWY0a0RuJXXkiuV4IvXWAV5vvpf0KegYvzra54LztyciAIMko4wGC9kuTLcUkaquXFUFAH7QXC+51QmsiWmvuwNlDaI8jWPKnCXwIjxgaxji6EJlP0e9zJzju96MNuXC0i8/6bHPxW/gyAN5RrawLICxPYVK95Pnuu7DNiMpTj3Wvn8hI0o1u45SOxnAF3m04yu57dmTidisNKMbTRtzjA9EnNDUFWtvfrrI2pmSAFhj/gWNCff70QtwsnM8YBKIJnHJRqraX3ZFP3N2/Ul27MJf07L7bXNOMTh6NOc00y9DcOwXmoJjfc7jIYU7GSDqMInkExm3iEtJ8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODc4NTMyOTI5ODgsInByb2ZpbGVJZCI6ImJkNmY2MjIyMGI3NTQ2OTg4YzgzZmExY2EyYWZiMmU5IiwicHJvZmlsZU5hbWUiOiJDaDFja2VuIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xY2IzZGYyYThjODcyZjdhNzk5YWE2Zjk5ZjI4NThiMWExYmQ5YzgyZWI5NjVlNjllYjU5MTM3YzNmYzY0M2UifX19',
            'trail': '',
            'op': 'false',
            'speech': "Give back my PAGES!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/pt jumpto",
                "/jumpto"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 7 true",
                "/give ". @plr ." minecraft:paper 1 name:1"   
                "/give ". @plr ." minecraft:paper 1 name:2"
                "/give ". @plr ." minecraft:paper 1 name:3"
                "/give ". @plr ." minecraft:paper 1 name:4"
                "/give ". @plr ." minecraft:paper 1 name:5" 
            )
)
