@plr = player()


@hero = associative_array(
            'name': '§fSnoop Dogg',
            'class': 'snoopdogg',
            'sig': 'iZEE3GUCM8/jDCuOQ+2YPhMOt5caR82nfdTdnPmquJL7ipxbP1IKBFKcMR3TQWCfk5rghRqYyUdNtp2sjLeFX29FWCoiuRld/rs/73tJnU6V9RY9aDjpgMHMJxEOqbGbb5HAE/wA3tT3ds8AGlKVhjAK5NfEn0ktklvvpYh8lEgkJnbuNFQPTer8CauTZszpzk7dVZBigEwGYm7gpvwm16e+pe9cMXsfS4XX4b2wTk/4h8C+XJRwBVPyP7XZ1xDOwbUt+hTt4FJkOokF7hWkXyS2abUIJ3txsmALUa5VQZh+R0wuUgOSkKSUl6+HkButgllwbt+xkVK4XEvVmkGTUuoRRLhNpw14+FbniMNOvVJWVbHFhEX8WwlHZoX1Vusy4dON7M3n4VG66QjLG5vG9+mNQxRlX6+xKdKK9x6lAnC3rBTwBkCfaquSaXiJDRXmJzcj+LhpKviKvneqdNijaakzdtBM3eaSr8Dp4kmmteNLEe14gF2hXdbSWgiCJaabGAZUYcDHLhncVZ1HxEfi4AUM4fxPdbI+FeXsM2M0xRHd4/dQm0V4pPvqaILw59TmuPnFU6Nqv6eEngsffeohbYuvzta7wdl6yPXBB6eefNv+ep1F7qptZnFuXlymFzKxt70D2rYQJmd9OqMpzTluMAh943iyh5bk+qpHl1p0mBU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE4OTg0OTM1NTYsInByb2ZpbGVJZCI6IjdkODVhODNlYWVmZTQyNGFiOGJkZjdmZmNiYTAyNzg4IiwicHJvZmlsZU5hbWUiOiJFYXRUaGVUYWNvWFAiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQ0ZWFiYThkMWIzMzYxZjEzMDM2ZTUyYTQyZmFiYTEyNzFiYTU2ZmNjMDYxZDA0YzU4NjliNzRkNTU0ZGVhIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "SMOKE WEED EVERY DAY!",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/effect ". @plr ." 18 9999 1 true",
                "/effect ". @plr ." 2 9999 2 true"
            )
        )
