@plr = player()


@hero = associative_array(
            'name': '§9S§fo§9n§4i§9c t§fh§9e H§fe§9dge§4h§fo§4g',
            'class': 'sonicthehedgehog',
            'sig': 'sYlPmlarR5eHUbNT+jf4lWl2NqW6ylErZ6+0VoLG2xrTvtnTQSMaNDL+cmryxWk85BpXHBVXaeB42qAseqwNSDG1Ex7SmgtGElaPS1zYHuvcpw7hWNI5YTJuY7Mq621al/dsZcxSo8nVitNsUIKc5v8qIlQTRyBwL1llgMLy7SQBJiP9jVSgj8ZWD0bicX3FHsNVr3PlO+MQOp8Qqi2zAiaKRMgMOfmBGGW8H86lT9lMlIECpMAvwrOTdExj4SD1A6kilOQJMgAsclpDp1mCnfGv4Pvi4iO7S1hr055bQn0qF34SpJ8od66OJiu3BVvOknu+SoXhyrN/oOASi1O/Zvm8hfwU0cbiKuco8PxGL8tw9Mx2sEFaem0m1sBuAasOLB1Cwgwnah0Lx5Lf+NkOBFs0jCF2otgjDsvytDXOELkkBghBqrpvwsCJOp/FKwd0giF0mwdNN+G3d/2Dii67M3TYuHWj7qNTZpeV5ZhnCrN5YnDu79p26nuKcwLq1SUDUtE/ud4cEKdKdwJIrdSkpu1idnmeGPgc4x9u2oE3rXt4p22xaQLkQwI2zjZdNRn1HY6f20zZWkR4+GatgqMJgjYUdCp0MlC+VQl9bzCod/wNCuJ9vckTzwxtLgpWSgxmic/k1HXZIVqs5TE3F4Kbnk/Rlsvey0QyDDWRMCIRGYg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzAxNTQ5NjQwNzQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2M2ZWU1Yjg1NzVlMzhiMGJhNWU2ZjM0OThlYzVkY2I0ODFjNDM2YmUzYzA3MDE0NTlkNzIxY2E0OGQ1NDA4MiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Gotta Go Fast!",
            'powers': array(
                "/buff",
                "/run 0-8",
                "/jump 0-6"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." sonicthehedgehogshomingattack"                
            )
        )