@plr = player()


@hero = associative_array(

            'name': '§2S§0p§7e§ac§0t§7r§2e',
            'class': 'spectre',
            'sig': 'BUh/1kUYGKa9AgJi2o9s4zKC/ZTAqiguAM4ta2UHpVV7RlxOjdIB+biheAfLAZaMf5VlRSkKM3O3AzS8tOb1e9RCbc5CCNG5XB+NpuQUiValXdqqk61wb+8skMCM0w8DmhMVykMVtYUJkcxpo8oL3OnGktzKyI+HCepz5goULDh0GxRWlKDpRqWhqFN5VUGu8iFsJ6Viv6h0yYfcZch7kSbt7uOHne/LSdpiaWp6Cnh5ul/FY3gpBwBM6LCQFnl05vHyybfI33YBYO+2Ad6vG2SztGtNsuEvn0Fzh7o4wWrp5Q81SDn5R+w06gSMzxj3BYtUDL4YItAWMGQEwHzcg40EZrOWFSJBUdMBzViJYfHGABpJ0rQgDpGPqZtqCZD6rpOg2J8qDyL6iFf+oIbagK9OVRHkuhz2/CbDbRDmdoGDLgTvkUITnfIxvYWZgyhOgZRk5zTTCX+tbmh4jdIHACIBNp16JdcA4bKxOpkW0gD6X0DSDnCh1/DNxXnsLFGHMaoNuP5cXn932SHedU4lUrqI7LM5xmsQmuRgFCZVm3g8Q5FfjFAKdhNRS9vOzCXPhpIpnh5saEo9RN07N4ypbscYNEYEt0IMxgmQ1XmaoqWD2y5NemzOwjua4eKnFLB+OSrd4GngCeGCm9rOrf8hPavlsfxUKlKutdp+WZc0b0I=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODUyMzE1MzEzNTMsInByb2ZpbGVJZCI6IjI1N2E0NWQ2N2RiMDQ5MmQ5NDVjYTAzMGY0OTg1OTMyIiwicHJvZmlsZU5hbWUiOiJCb29mdXJkIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mNjFiNjMxNjk5M2IwZWM5MzVjN2ZlN2MyMTMwNzU1M2Q5NjNkYzg0YzRhYTQzOGJmMjk3NjI5ZGI2YzkifX19',
            'trail': '',
            'op': 'true',
            'speech': "All will be put to justice.",
            'powers': array(
                "/buff",
                "/fly",
                "/grow", 
                "/shrink",
                "/touchkill",
                "/gmc",
                "/gms",
                "/vis",
                "/invis"
           ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 13 9999 1 true"
            )
        )
