@plr = player() 
 
 
 
 
 
 
 @hero = associative_array( 
             'name': '§6S§4pee§6d §6D§1emo§6n', 
             'class': 'speeddemon', 
             'sig': 'K4hUYe+vyA02hglN6nhcUYgAtLcSIjE1L/Rze/gwLx5b6Q/i5krxePtYSuA4c0KAZz1dJUMFdyUkp5i4pCyRa22pLyu51pnXCcIvc3pk8Rtj0FFiV7uK3fk1WodCV99obBZqN9q4XxOsorathXnonu6gYDHScVn6dNFlj2REUqkm46eaga9seQPIOzrKNLxNMLp9t66bn0DcEa+a2hS+5KEx+PiUYdcX20z/gTw8W7TsdSsLZ7fy3n5d1MLirseSsqIt5BkuG7jf/LJC0b5+9dS4w6P2QipB2+7x67E8WzBfYhdjtqwffG+Di3v5desMEO8NUj1ajLXGhVPQ4ZxgZwqhJB1sex8+zUKYPmWWPqCPX/mJSf3M8vGqBMVqShJ01abygj9coujTBs0SJ+vW7YOcZqbsf0N4nktZjIOljF/Vc/KPSYbiaEe+xG5rR5M5zx+4H6eNxze9XcBzyudt6vFKsVHtf3uScjkaHK91H358mp9oviqo4xi9YY/xJkUWD8QOHrXX22SNFyVVSb7uW2nCF9cyFo22vMgOABGHpFuNr8RcCwrdAkC9mU1cpIxSUUa/ge84XCEw0Ndnqw8XHrPELJuu/+JUa91MFou7ccPNhiAQM7F9z3cLlyzwXbSK5V4m//Wx834yLgmVTtcmDBDnATkI7FR9EEUBQ22PBUM=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE0OTYxODczNzg1NjEsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWI5NWI4NDZjNmM4NjhkZDVhMmM2NzVlYTI0MGZiNWU2YzI4MjU3NTY0YTFjZjk5NzMwZTk1YjEwNTY4MDdmIn19fQ==',  
             'trail': '', 
             'op': 'false', 
             'speech': "Run Fast!", 
             'powers': array( 
                 "/buff", 
                 "/run 0-9", 
             ), 
             'buffs': array(                  
             ) 
         ) 
