@plr = player()


@hero = associative_array(
            'name': '§4Sp§eee§4dy',
            'class': 'speedy',
            'sig': 'ICoDMsdRP+AarW6+gyzbD/9SDyQ1emqKZbFLQjHBTDADT53eHqZRNq2NuKB4UPFnq30Wf8sxK/gc1LKQNVc5fhWPkFZw6evmmBEebGtSzyXXK/QLWj2Mqnsvs9MF9QqontIkMUvCHq8SObC7HsTHpwvw9ZqgFJCrGEc94mQBrcV/3KQg+l/dvzcTUNnMTS9tpMUOMFekTkjjCjpmOYkjgmbYdNhPpBQV1rRLxTml+0P/bHKg2KjN2GMpfbwfFF5vqCqbOt6i8Uxe7gkV6bAhCrrkU85YFVmCyHVM78WnatggoFn72Kcj6tf+WBphW9pnY+l6/UsqQh6gx7YLv4h+n1hn4vPcRnEpFfC/1UtZg+tdrfcREfAAyXi0ZOu7Qn9ZJ3xEYyuWQR+XK4/3b9PAR33ViqyyQDRpAR5wqYxeETUL7yWycVpmOmkYmROzUJFMC7H/KQ9TwMfmRbKlZ3vdMo933DKdh606BEcNgCrwEJtgICPg8FqELy4+km+U4R4tm4YpgqLrXlcnhlWPiCiDYG3XyYyCQAN2JqjAY5pwsxK6bcNL+KJDzqajA9o6X3qDCA/7KfpvWVL02HkIBOA47Xnk/TTmcssxqBUa9dwRhjMdG4Rk7Bod0nL8kKfn9TbJ+QbybrTjFp/kdtnyj7nBRyvnq08G90x3ON2HOgwDf1Q=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjEwMzE5NjcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82MDI4ZmFhNWJhNmNmN2QyMmFmNTg2N2RkZDllYzljZmM1OWQwM2UyYmRlMzBjNzk5ZmJiODdkZjAzMmJkYyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I guess I'm kinda like the Red Arrow!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-3",
                "/haste 0-1",
                "/arrow",
                "/arrow regen",
                "/arrow regen long",
                "/arrow swiftness",
                "/arrow swiftness long",
                "/arrow fireresist",
                "/arrow healing",
                "/arrow nightvision",
                "/arrow strength",
                "/arrow strength long",
                "/arrow leaping",
                "/arrow leaping long",
                "/arrow invisibility",
                "/arrow poison",
                "/arrow poison long",
                "/arrow weakness",
                "/arrow slowness",
                "/arrow harming",
                "/arrow waterbreathing",
                "/arrow luck"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:bow 1 51:1 name:&4Sp&eee&4dy's_Bow",
                "/effect ". @plr ." 5 9999 1 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true"                
            )
        )
