@plr = player()



@hero = associative_array(
            'name': '§5S§0p§fid§0e§fr-§5W§f§8o§fm§ba§fn§8(§fG§7S§8)',
            'class': 'spiderwomangwenstacy',
            'sig': 'B5z6osyxnuz11tgxKUeR8RCQ/ard0ZUcb4El2KQaeedVgnyafazJq3yQWWbolo+DVl6pvfc3ivHb1XgI92ZIGo+3xX1rZESPxuoTUGEVOsz3aYriET/VbrDB/RsWd6pqGENgCbqeV8E6+E+AVhg7twnNmW2i044jB3vLV79nVGDa81eDrZXMATjI5yH+LEqAZtEbro8am09mI5WEfB7YqBBohiYfQLpPX0XwQTNIOqIjwf46UeGp/nLEKVmZUAIFNM27iT+PZnVpPv707/7eMNtM1y5/k3kLAHt4XPy/yg8QHY1mrm+DhxAwP+BkZpwV4EAxzZZPdeAVtHsMqvD8V0fVkg9Q/ji20ieTnTUvIPqK6Yoioitb4bxsorOWvQCbLnRwKztx2RBHRbVufUlfwFsPuCTP7/sAhBvpvjBgw8KmWwR/KQV0vg3zd0H7rZpBnBd/7XqRssDrWAu13UNx/M7yFggv7YvfNkg/OpoYOTngUsxsImt5cU8S/d+LJhR9OubRXOV+k/DrnHDpkGcyrYpwvo92wpO0xny5v8HFPtmzRIGYFPuikNZ7m/XdwIbDp66shSy0LCaA2But5RmYv+x2hY4TETYWv75BMOKij4/GzMSzsaVsbKBfgw2JgQlfkQ1ejS6+EeDkJKLJ3MHbyLEVDO476xEw07PoSc97j/s=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDY5ODM0NDU3MDEsInByb2ZpbGVJZCI6ImE4ZTE1OWVhZGVlYjRmNzNhMjQ2NTkxYjU4OWFkY2Y0IiwicHJvZmlsZU5hbWUiOiJNckZsYW1lWVQiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jMzhlZjM1OWM5M2RkMWIyZWE4NGE2MjVjNmM3M2VhMjczY2JhOTBhZmZkZDgyOWNiMWRlMmUxNzc5NjRjNTMifX19',
            'trail': '',
            'op': 'false',
            'speech': "Damn I look good!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-3",
                "Wall climb by standing next to a wall and pressing crouch and vines will appear. The vines are only visible to you, not to other people, so it looks like you're really climbing the wall! You can sto
p climbing but continue to press crouch to stick to the wall in place and look around.",
                "With an empty hand, right click the air and you will sling web out from your hand. You can use it to swing around the city! If you cannot move, press shift to dismount the invisible mob."
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/give ". @plr ." minecraft:web 64",
                "/shot give ". @plr ." webshot"
            )
        )
