@plr = player()



@hero = associative_array(
            'name': '§5S§0p§fid§0e§fr-§5W§f§8o§fm§ba§fn§8(§fG§7S§8)',
            'class': 'spiderwomangwenstacy',
            'sig': 'Pa995mO81YY6e7N7FwyEoUjAwyRrtNwhLArTI/Jb1wS7ylfTNlEJ87VbX3zIzOe5NQr3uCyxPnqBsv8zPMWw/3qrZlBDo9YW9h4kR4ghdVE78ipyBvPeLMNhuCqq/cQzl3Nd+nAanL8AMSfVlwSpUaRDH07NC5OWwyCihaxViqBJ31feldc1N+WpfrL78pzU1O4vQwnm7Kk45kqA2C7GOcIHtuq9FooTViiZGMDw5froSuwueZ7VnfVJbBVVrUZXfWr3+bIWX9P/W6LQ99BHMQMe8FzRp+EnngCZr1Lfn+sPO3UZumMjrLhs+Bwn2nhB2sqcDnLupZHq18rXzwa+32BF5omM983h4SpbYXC7xBMVmFfZkHawanYQob078fGEgJJt/mix5EYXeKbfC0RjBPPH3lySRRcZBAEyITlK9Jtc9JAin8VSERdvTBERE2tlZgdHrWl3OxVBBaPWPbQSF4ot9OsAaSYRsTRLAA5v1bP5gOugmt4Ej7DIU+0ucztCHvMzsA3Mz6Cst4zkThnX5aqGoi0utYMEpUPuEnK0+O/EHbMp8sz3Sv0kycCsIUHIJIdRVRT2DCVEpYJUOQgK9kCDJh4w5Hrr8Bb2CEE+28C3Hv63h4RHo7HPF+EqboRkUdMsmX317+JD8hVi8oSDYq/Wi833Mv5sCFXJoIjNCSY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NDM5ODI4NjUsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81ZWQ2ZDA4NTNmYjVjYzY1YmYyM2YwOTdhOWM4NmJhNzExMWUxMWQyZDc3MDY1MzE5ZWQzNWVlODk2ZGQ1YyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Damn I look good!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-3",
                "/web",
                "/websling",
                "/invis",
                "/vis"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/give ". @plr ." minecraft:web 64",
                "/shot give ". @plr ." webshot"
            )
        )
