@plr = player()



@hero = associative_array(
            'name': '§4Sp§fi§4d§0e§4r-m§0a§4n 2099',
            'class': 'spiderman2099',
            'sig': 'PgbiaiR5ECzObP+EM6uPwImUdWcoUSCY/N3+ZvSG/tZyEsVrCTvvxFmhra99C2sOPLbkRxLJh4YvJXpTRWe49Ow3NhoQnYaHJn5PI/iqx2ksvdIkJJ+UEB4zCrtMK2MUd0s9CjWwcnZof3gdXy/uUabALCujtH1QhH4CYAWqnk+WXaHJ1W1U2khGUDtGxMZGce5dTJnUxlPCH/oqHOeMFPZbb2rE41fsrqB2MoSa03LRwUz48D7i9s/6S4iCHYGedId9BGuOuLDnzqIrO1HH6vtM16+xshMoxxeJqu3azRG6V6fxmfTuPRyK/o08czBdVorBCiDDHCYZSuyleNlqh+QV2Rq84O4QKEdbn02mMgPHh/UrZ3EaVn1lLyLpPC7lOKCwWosQg3aAKZA/6QKvL+2/+pRlNeYII3F5TXwYb7UPmDPnvvy4HQ01ZiWxakOFFxRhctrdoMxyb4S5c2BwQ3f5RfnxkPPKvxjdL7LU5migNRxduIIAFgTiGlBxVkEyG7/eh3M4Q2XWefhLHzspaspUqwSWwo1l3AMACHhgO3tk+e0F4Rc4x4iTRP45C/x1PLGDxlPz1lIeGxIMdqCXyghY3AdyYfU2nd3/Cbgq7dahsQqYCJ076AMuj+AkaXV6j+sF0BCUvOQtKrmggFv7qKnZRLUl4TINtA8WXNF8HjM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODU3MTM0NTA4NTcsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWFkZjIzM2U0MTI2ZTU4NjZmZmUyYzZlNmRkMGUxNjU0NmM5OWY1NTdjZDM4YjY0MWNiNTgwM2M1OWFlMTYxYSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I must save the past to save the future!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-3",
                "/web",
                "/websling"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/give ". @plr ." minecraft:web 64",
                "/shot give ". @plr ." webshot"
            )
        )
