@plr = player()



@hero = associative_array(
            'name': '§4Sp§fi§4d§0e§4rm§0a§4n§4-PP',
            'class': 'spidermanpeterparker',
            'sig': 'LZpw7NEzmKO3Lr8sOImohBwK6cstWrUP4fZ3AhnvBBCT2C10l5YIU3dusgzqDWFGf/Dx+PZkVRT6DUOt+f+uj1YwIC45OLjDKrhNDdD/lPIFp/1QloZR8+WcDOtuWclJWbIlvExt/b+HCvkW0/q/h+Uq6kzfGQ0M9zUxM+CQhS1jk1fDq3BTzkpZN6JWvKKphTfPPCSSsdYSe4NA1EM6TbFRecbb7RK8Iv5ZuUaBOCYbI5fi9rI2I3DpOTVfapGBipiIPvOjPcfK2otpuhFbsCsm+EeCbOGsBrgIOrx2hTWkUpWoFPGpjXNJAolOojJniskOMuIXM85y6ucbBtf0AHplVNMmnD92MioG7M/F/mwgA9pOPI4E2Ev0a5GBfZDt53SlOsxdAET7jrfFs40RP+llEwZf88UCvHNs4mhp7WPTutrES59oTzJyI/h8SYNR4+psU0EsYJ1GSvtxiq7Q+CXewFh+WAs0c6T6jhCo3/j9TYT2jp4D7pVQcgW6RVx/fAcZJxYu72t/W+zt+2m349NnYXCxpkoifaClE42whKFu0XJPbWYanaHE0dVSUqGihlLWEfEdLzV8tr1twk3fHBVK2Dtchw29GWrkQKgcRGVCuoor3ixEZglv2AMvlhMhJ7Yu2bl1iVfcY3s/F/kmuBls6OfdCRNgutPsie0728Y=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NDkzMDM5MjgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzg0NGNkMWRjOTI5NmM5NTIzZTljNzJiNmI1ZmEwOTc1YWVkNTVkMzE1NTA4OTczYjQ0Nzg2Y2RjMjZiYzg5In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "With great power comes great responsibility.",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-3",
                "/web",
                "/websling"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:web 64",
                "/shot give ". @plr ." webshot"
            )
        )
