@plr = player()



@hero = associative_array(
            'name': '§4Sp§fi§4d§0e§4rm§0a§4n§8(MM§8)',
            'class': 'spidermanmilesmorales',
            'sig': 'YHjcu6XGP0tUXxv0CG2oWW24GZJpyZZ/+L/zRHmrz/xnWR9uZnQ3gxnDSwtvBbkN8qeUdwRJ+ad6VsIn9sGqEAe/rp/uXfpKExXRAShXWeknFSZzgNPc4zCoUBAiyZW+BrMOjLL+13s4krDXp8vKkaoXuoKM6X1aAEE75uKQbjHyVw4THk9zTNbR65vhQJVBOtcqtcFSqwL6RFPY9RL6YzxEy/bYhxMwHi7/eRU7Y8nRdl9FvfGoyujOU8wBwqGkovetKh8wgVRwxWltHprjt4ta7+PW+IYHk8pmHSwEzjBzDQK+0UPqTpwvIpgZqjii257G4c10LUdnfSy3oTHr1mlSELQ0wk2TiryS+q9jLuuZ3uruqeWNdZ/AuoQTCggFhSCMu1ax/UjfEYe//Xtijq7MPgsoeL+jQtRzSIFpeINAIzH7AQf3k8EPjnMF85LVHCq/AzQw6IzsYiywLfJPjxGfTojCGrx8hJ/KTPZSUVLgPmziWZN5AqBUsYWaXRZ6DXomX/7x2Eo9Z+qNOHqcuzo6Yqx9VnMNNPEe8g7abuxVGSRW1nnRhTuiBH/aMmh1n3tkym0oRUrAXYpuc9BE5HqH2+u6U5MDko70pqpddnjVi1xmeZ4MnhsY0oQKNMOGxtpLK+A4SBK6TR0WyN1tRo4sqswC6r2n+hU0ERXI42E=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODgwNTY2NDE2ODAsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJNaWxlc01vcmFsZXM4ODgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzY2NTNjNmExYjFiM2U2ZTdhZjE0YTBlNjdlYzU3NmJkMTY0ZWI0ZmRhMjNkZDRhOWU0NmYxN2QzMDVkZDViNSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Just a kid from Brooklyn!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-3",
                "/web",
                "/websling",
                "/invis",
                "/vis"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/give ". @plr ." minecraft:web 64",
                "/shot give ". @plr ." webshot"
            )
        )
