@plr = player()



@hero = associative_array(
            'name': '§4Sp§fi§4d§0e§4rm§0a§4n§8(PP)',
            'class': 'spidermanpeterparker',
            'sig': 'LZpw7NEzmKO3Lr8sOImohBwK6cstWrUP4fZ3AhnvBBCT2C10l5YIU3dusgzqDWFGf/Dx+PZkVRT6DUOt+f+uj1YwIC45OLjDKrhNDdD/lPIFp/1QloZR8+WcDOtuWclJWbIlvExt/b+HCvkW0/q/h+Uq6kzfGQ0M9zUxM+CQhS1jk1fDq3BTzkpZN6JWvKKphTfPPCSSsdYSe4NA1EM6TbFRecbb7RK8Iv5ZuUaBOCYbI5fi9rI2I3DpOTVfapGBipiIPvOjPcfK2otpuhFbsCsm+EeCbOGsBrgIOrx2hTWkUpWoFPGpjXNJAolOojJniskOMuIXM85y6ucbBtf0AHplVNMmnD92MioG7M/F/mwgA9pOPI4E2Ev0a5GBfZDt53SlOsxdAET7jrfFs40RP+llEwZf88UCvHNs4mhp7WPTutrES59oTzJyI/h8SYNR4+psU0EsYJ1GSvtxiq7Q+CXewFh+WAs0c6T6jhCo3/j9TYT2jp4D7pVQcgW6RVx/fAcZJxYu72t/W+zt+2m349NnYXCxpkoifaClE42whKFu0XJPbWYanaHE0dVSUqGihlLWEfEdLzV8tr1twk3fHBVK2Dtchw29GWrkQKgcRGVCuoor3ixEZglv2AMvlhMhJ7Yu2bl1iVfcY3s/F/kmuBls6OfdCRNgutPsie0728Y=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NDkzMDM5MjgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzg0NGNkMWRjOTI5NmM5NTIzZTljNzJiNmI1ZmEwOTc1YWVkNTVkMzE1NTA4OTczYjQ0Nzg2Y2RjMjZiYzg5In19fQ==',
             'altskins': array(            
                 array(  
                     'sig': 'eUPshfh4fqfYsX40H0LoFO7e2F768Ek7lo9cPiSzIAEbVLPDXBQO7ig/yvartcv7tkH5HwzL5KM2bHmj7BW5rQQ79BJAELUij3J4xnZTieWf0ZtVhFTq1yvIkmlmHV8g+IYxQqedGv0hAJ3H+AeE7xBTVjJe8J0LXg1BuhfCH7buHYNTq2BJrzRMkAoIaaJTH6WuK1u7XAO/wHoMHYBmd/HONDW8y4GEQoOp3MGHRTyRrR6vFoSzrvsvd81YRYoTr61chxAwB/2OA75SVBw77+2kEesSiU8ekLWq2aZDk/byGybbd6ncDRvBlBiHm1YY/L0KlEmXsG8gC5zN0iPBTleg2ETfEZbyIcFeYrj+Wk7lhTDtVLTzk8Zd+Z2ftYaOV66UYgc55cZaYFIZc16CCzFLOV7/SP7ySrg87rQA6edW9IwFFs+IL4EUvbdMIsCLGJ+ER5uoppzaY8ONO6rPz7tNdx4GJu1LSmxt5byPICybfUCCr9N4UOBRx79EOBiCSqF8hGtF0QfIqAqpsPn6B4taaPWAztWjCjmkJgXXLkt0yXJF68/E5bAe37cVH3rbA2gwyWrTh1fiToR+fZmNWtmfHcoZmKYBHyeqVTJZ1kLsbRTa2dGPJa2nJ8Km6pViFfql2i4xPWt4MHJiLGR6J7/o2NBeF0StGYMDdTsqBJ4=',                    
                     'val': 'eyJ0aW1lc3RhbXAiOjE0ODc5MDUyOTU0NTUsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJNckNyYWZ0ODg4Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mYWUwYThkNzJkYzBlYWE1YWI0ZTQ5MzNhYWJjNDFkNTM2ZWEzOGU5MTgzMTE0ZGZhN2E4Y2I4NWQ2NTY2YyJ9fX0='              
                )
            ),
            'trail': '',
            'op': 'false',
            'speech': "With great power comes great responsibility.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-3",
                "/web",
                "/websling"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:web 64",
                "/shot give ". @plr ." webshot"
            )
        )
