@plr = player()



@hero = associative_array(
            'name': '§4Sp§fi§4d§0e§4rm§0a§4n§8(MM§8)',
            'class': 'spidermanmilesmorales',
            'sig': 'GjnufT3Z/FwMDlXIqQvd+qDxftbbSKQuidftdAL3rkj1qcMlmsxeR8AmYmDLa5B/nVbRM1o0FtJhwmQE0TK2lAmGCyVUFp1wOK0E9bf+wuYiI6GS80x02lAdZf6olqV5+SlIUCBTBwwVk8ljHqmqwKwPjw2b9ePR52qICqdrU9FqTuyGk4hJOnxYvJtwkvQajoJCYShRbvGTKSCg98f7h7VDRl2lHEp83wJs2q4278L/66C4uAIy0W2oErFfjiG/dEq32T6ujSGd0XYGur+lvB8n+JGV06xLo78dk0ItzJRXYDn7YvL3ib16rmSQAhR4+bRBGP5+rmPVZf2UotIJKnppm5Nb9xXTMx46M+H9BWrVVdHqe/fLDlDZHfAoVqwK7RMHoaqFfCeQ43glgXrNWmAgJiRetCLx02jTKb7bBM5bvPQoSwjKbiH3riOMsOESL9k1ATMZQD3qp7D3uaulHhRBZm3NAkFqQrWVaaonnJGQaFuMshZjbfddDBcFMf3gUA5hthaMQRr+K+TCTM1NFiPbE0ataPmRywSw+H4M+dQHN8d9lTdpqdKcKWPeGlh4neE7cUYzRBSa4fCv/is+yQ5zXWfYyEffJDKJnoTSkiFEwFAxq/kQHoi4uOOGyAkBHKpDG57dyyajR6eqg4fFnYGOL2yQ5a/vCPi8JoHX/Ug=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NDUyNjc5NjcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2RhZGUzNmFlOTllNzNhZDZmMWFjMmI3YWFiMmUzNGY0YjkyYjMxNjMzODY5YWM2Y2Q4MTAyYmZiOTRjOTEifX19',
            'trail': '',
            'op': 'false',
            'speech': "Just a kid from Brooklyn!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-3",
                "/web",
                "/websling",
                "/invis",
                "/vis"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/give ". @plr ." minecraft:web 64",
                "/shot give ". @plr ." webshot"
            )
        )
