@plr = player()



@hero = associative_array(
            'name': '§4Sp§fi§4d§0e§4rm§0a§4n§8(PP)',
            'class': 'spidermanpeterparker',
            'sig': 'LZpw7NEzmKO3Lr8sOImohBwK6cstWrUP4fZ3AhnvBBCT2C10l5YIU3dusgzqDWFGf/Dx+PZkVRT6DUOt+f+uj1YwIC45OLjDKrhNDdD/lPIFp/1QloZR8+WcDOtuWclJWbIlvExt/b+HCvkW0/q/h+Uq6kzfGQ0M9zUxM+CQhS1jk1fDq3BTzkpZN6JWvKKphTfPPCSSsdYSe4NA1EM6TbFRecbb7RK8Iv5ZuUaBOCYbI5fi9rI2I3DpOTVfapGBipiIPvOjPcfK2otpuhFbsCsm+EeCbOGsBrgIOrx2hTWkUpWoFPGpjXNJAolOojJniskOMuIXM85y6ucbBtf0AHplVNMmnD92MioG7M/F/mwgA9pOPI4E2Ev0a5GBfZDt53SlOsxdAET7jrfFs40RP+llEwZf88UCvHNs4mhp7WPTutrES59oTzJyI/h8SYNR4+psU0EsYJ1GSvtxiq7Q+CXewFh+WAs0c6T6jhCo3/j9TYT2jp4D7pVQcgW6RVx/fAcZJxYu72t/W+zt+2m349NnYXCxpkoifaClE42whKFu0XJPbWYanaHE0dVSUqGihlLWEfEdLzV8tr1twk3fHBVK2Dtchw29GWrkQKgcRGVCuoor3ixEZglv2AMvlhMhJ7Yu2bl1iVfcY3s/F/kmuBls6OfdCRNgutPsie0728Y=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NDkzMDM5MjgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzg0NGNkMWRjOTI5NmM5NTIzZTljNzJiNmI1ZmEwOTc1YWVkNTVkMzE1NTA4OTczYjQ0Nzg2Y2RjMjZiYzg5In19fQ==',
             'altskins': array(            
                 array(  
                     'sig': 'Co9u5Y9Ho5+VNhsJfesAhtKr62pD/uuYE5InP1ItQHQOppqPgWXK9g/aNN3GE1yasJH3PFaiuhyInUW69NtScOf2TFZ0sDBfXA/EWi4roMgWfoGl6tX2RHqR53fcvscKD/C9UTq3gm+nm5XnI5zdDKlpPeaSTNCB/x8HN41nw5WsgD/eXcjo+aqz4DVwQXIphkj65Kl6G1tWVNwi6CdvcAcvDj66vA0t846N+X1iIQiXalceRXJKm73sc8n1Lmw0IWz83UBUvSnE0o/21k632PcEV2bmp6upGnExAEeoCIyOPMrgSE75Y2f9fkqXA6I/uMy2HApBKvoeDQwKaoQmlfRA8LAjuA6vddCCVMcPaA+Yo+t+7/H+PYweW6OF907FlVZCM8tC+0v+BJx0w591G+MrdN+6/sPp6cbBbKBMDKeyLugB8NcAw3w1cHS6Llccv8bFhBnhCCO0aSz3ZQRNN/oBSLDtmPedXex5GMI27EFfgyaU+eqD+/JSkkMOQSLXFFfS9+O98RVBfgouGbNigHMMwKg7O6ORzF0/6CyU5K3LIWfMUqro8DKX8llVcJumRBRLa0rGZg+7GyMtcfAda5z3tvxvS7VpOMfzoqHpN4amLrgGtq8sIi7g0iurYiDl2G14k1OcZzco2kbKl4GAxxsXyGqMtpdFlz5SLZjBpuc=',
                     'val': 'eyJ0aW1lc3RhbXAiOjE0ODg3NjQ4OTU5ODYsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJNaWxlc01vcmFsZXM4ODgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2EzZWNkNjI0OGMzY2U2YmY4YTkxMmY0YzQ2NjkzNGFmYjMzMDlkMzgxM2VlODc5NzNmMjU1ZjNjYzUxNDFkIn19fQ=='              
                )
            ),
            'trail': '',
            'op': 'false',
            'speech': "With great power comes great responsibility.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-3",
                "/web",
                "/websling"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:web 64",
                "/shot give ". @plr ." webshot"
            )
        )
