@plr = player()




@hero = associative_array(
            'name': '§6Squ§7irr§6el §7Gi§6rl',
            'class': 'squirrelgirl',
            'sig': 'vZZaL/p4hjqQ1aDbutWC1njGpNzaOVMHTpbX1bl3nmLxsRF+jKvnDPf3Q9eUj2lgVbBuTXDqMdoNSLNaGMo0v/emyazyqpVeIcFoHhiSFosG4SJFz+NQEfYAqtT7L3rPbEr/9lVpYbU4GMXLeTfX+T7VmhCEM972IaiV0dTWpwJzEkwSmPG/8vj7nj3NqS3JFFBMtD1BdRDhKAftl3Q6Pl1ynRqfaeIwS7G1PRl/kMzyOXNnBxTyoYrceFeNqbFXxVIxXjTuM2+jeASEr6dE8eWkFAdVjK0j1xEn2JUKDfZGsgGdXOiTdxY5tg16SyemXwwCuiJlLAawgtTX6qy+IWGO1MRv+yv5lG0o6OUHWw0a1AJpt7ZW3S8CJF7TWV4OuP/8PnHT/Yk3axBOJjQo3F6fsp4P0NGc8oBfiDeEOyboC6erMTiCpynZ9ZToBaRB7kn7t8/bnYw2Rp2RUpLeyMvdGh1G2X8Drkus+2pwZH/YIjnMWh6OJpKEa1pZwL++lOXl+jh7B+hhU8IRtxgpM7JyCyzZ1cFJUaqbbMo6/KCFTQNQ0m4azHM3SnQ1vdJncVHZAB1ZLQxIGk1rzga/4HczKRWFKKX8blSi7VUcIe6QbmzHSRAm7B3gNpTl6MzVFlZ5gRTKnD94Wjc/Fn+y3lIS2OX8ETR1tMgcNLUm9xs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODAzNzIwMjI1NDUsInByb2ZpbGVJZCI6IjI3NWFhNTQxMTg5NzQ1YzRiYWRiNzk1NTNmNjU0NTE5IiwicHJvZmlsZU5hbWUiOiJmbGFtaW5nd2FycmlvcjEwIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hNTFiYzNhYmRjZjFkYjVlYTViMjNhZTRkMjRhMjVlNWI5NTA3OWM4ZWJhM2RiN2E4ODJhYWNiZmQ0OGE1MCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "It's Squirrel Time!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&6Glide",
                "/give ". @plr ." minecraft:ender_pearl 5 name:&6Squ&7irr&6el_&7Gi&6rl's_&6Tail"                
            )
        )
