@plr = player()




@hero = associative_array(
            'name': '§6Squ§7irr§6el §7Gi§6rl',
            'class': 'squirrelgirl',
            'sig': 'Qe0WGdpTJ6rgT0r8yHqK02+fq1qrT7eCMkYWZKcMUY91EuotGsWR70YI3PLIm5JpDV4YAafKBydAEPl67GQCIRuOi7Wymuz9kKQwRatUrBAzqMMUX6VwgZZ5grDev0nHcDcuSbyREfz/kT9vymPrhIApiJ/jv6ZuX1iHtYy/gAZ//2u07dtwsl++H+mwPgMG/nFMwdiQ/axKjOd/06r7MSxcEjbwRsz+u2I+Y2hzfh+WU9pLYClr0sEcfTqkPu+uufXtGpUqifaAWNVPL6pzvWDG8fNmhP9ziyOSqkPLVTn4qEBSXw/ddWX/6KaowgwOgNcY1cZozWRZnI6S9QJOedpCIDnG21Nuhd+4J+CPUtoB5lCMakZkOw/bPEb+DQTOP6SNPl55tIJCjSx5L+TZ889Pc97q2JXYFNOmbqOONrY56s9edWKClkH3E+LCsPtjTdDEb+gH7hiUgzl6ywBnUtuSjqA3gAQV3+mUeYru4G2lXUBjqsQiEpJaN4pCPbJH0nWiyv28FNSZBw4Ta+j+9eWFkbbNJn2MTjLGUbM/bCDQYFY2Q7r6yN8QecE4Jct7oDvvtGpA0AWXpZnmS51ed5jNf3ZEbc1Rh4imzkzTg4ziOufSTOTcQhv5ixiMZtNEKilYlpZXwP7HCFL8/CZ+BFLL2PPCWjDgJBS3/KLacUM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODEwNTgyNjk2NzMsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hNTFiYzNhYmRjZjFkYjVlYTViMjNhZTRkMjRhMjVlNWI5NTA3OWM4ZWJhM2RiN2E4ODJhYWNiZmQ0OGE1MCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "It's Squirrel Time!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." spawn_egg:101 64"
            )
        )              
                  
            
       
