@plr = player()



@hero = associative_array(
            'name': '§cSt§9ar§7-§9Lo§crd',
            'class': 'starlord',
            'sig': 'cp1HEw/Oi2bDRHGYNTzRjM2y1JSOjm+OH2A6bU4MqwDXj0JKZlzzAnAA5u+k554fY0w6J5hGGssNdwXoXwSS6jZ+XquGoeR/WK8klTjlV6mz9Psp2KR0k7vH/g5jCXJrCZ8aLAgvc/LlrqrUFTuaYWk0UJR4wCcDCh1N5rziC1cOw2OjVU+IjYFndEBoGnxgxbBPkPiZvDAYObH35RCVEcaD+w2Up/4vqRLNxnoPrWAKUhW67OQ/Lj5+tuLRG+8ScHzaYcAb+OuDZGSVIk9+bZGbgl43Jd6t8en/qcFUYmoBiHKEMLf5YD47oD19wdC17oWAVSLn5Be60ZZtz3a5raARSs2/cG5rHMlNUx/AtogJyH3mDB0H5CcUuobvxFdcmDQUxBfqQ7l4tCFiuGo43mWZpEzdq1FGnc7RQbBIQtKtp0OjOjBbVwD3/exwOqFBeoyKzhmgKXynA6uPxPYF/cPGWubcuix4KhFoFlStlwbrHtT2EAeyRkMMsewtE4TZSepqDdTjfzf/pIpXdNFwyazDtNI/+9/K1JoPoZb1BI1fibBieo0WStO+vssTrRw1R6lk0lgvA7NsbzHksaTgsbwIE0XDoSQboqtAJafjeqPv+yIR7qx6iRx+A6vAZK8GZdbJogMfm6xdCxTncfX2Tw7zlX8ncuC9Hu/dOC6ReqQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzk3NzEwNzM2NDgsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJWaWNlVE9QIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS85ZTE3NjNiZjY0ODY1YzNmZGYxOTU0ODRjZWNkM2MzNWUzZDQ5OTE5YzFlMjdhZGY3NzY4ODMyZGM5YjVjMjEwIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Star-Lord, man... legendary outlaw?",
            'powers': array(
                "/buff",
                "/jump 0-6",
                "/run 0-2",
                "/haste 0-2"
                
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." blasterrifle",
                "/give ". @plr ." minecraft:leather_helmet 1 5:50 6:1 8:3 name:&cSt&9ar&7-&cLo&9rd's_&cHel&9met",
                "/give ". @plr ." minecraft:elytra 1 70:1 34:3 name:&cSt&9ar&7-&cLo&9rd's_&cR&4o&ccket_B&4oo&cts"
        )
)
