@plr = player()


@hero = associative_array(
            'name': '§&0S§&5t§0a§0r§5f§0i§5r§0e§2The§0T§5e§0r§5r§0i§5b§0l§5e',
            'class': 'starfiretheterrible',
            'sig': 'gvVQ95IhOVRTmTXljfJI8++xT6p0xRCy88BaZwFuq+ajUrSLmZt/5x0bnCKvzub3WWlHGDuDskXVx+hWQwedozKvEojlbwM6g+oKTYX7iRUdQKBzjCiKuzkbWVBB8Ho1e2ZpchCN1JdM4Xc37m9FqVg/QXd2LYeXKOms4SuO05PbHdG7In2Dl08ywlzW0LS9q6uJVweyG+RHnaOVTZfdc747LpHnvIUQPyWjnRI35n6+lnXK/8ufF7S4o7AwWlT4ttoBWuCSw5H55hP18Ehp1u/b0gFoI41jrxCCNE2pJUd0DfwRmoNde3E/i+23u3fIPWqMYxwsekgTWKX0EHJR9Q3FdBcnzkzzIjR83F29pZCtzD1cr+D/wWYQi40ECgslvwa31usVL9x5qPY//Ia4Cljkp0UsHPm5lQmEIZmmMMa/xzkDXsQi60+lyHrncRx+q/F91d3n5PWXqI7iupVHZjHBRCFUeCEO3yBrWJn5DAym0COfSQ/b2AdXi8JNNBLrZ+c+CCklnmDTKniuTlLHfQ9DEfmlR+ZHZrlSMKl3DZBWafp4Yfn/Yfh51Bw/afharXupmuONYdBDVEJV1ceO2/cVDJjN0vai30DL4XPFns7t7/jHW6jOY/+DIn4eBbPOk77fmb+jdMHShFhAhpdGzPW+EsKGTh9Bq1fZVLqK3p8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODEzNzc1MTc0NzMsInByb2ZpbGVJZCI6IjI3NWFhNTQxMTg5NzQ1YzRiYWRiNzk1NTNmNjU0NTE5IiwicHJvZmlsZU5hbWUiOiJmbGFtaW5nd2FycmlvcjEwIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDVmM2Y2ZWE3YjY4YzliODk1Y2NiYWNiZTI5MmY0MmZlOTdiZGNjZTQ4NmRlZTU5YjVhMDE5ZGI3ZjIxZWMifX19',
            'trail': '',
            'op': 'false',
            'speech': "It is is Starfire The TERRIBLE!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-3",
                "/fly",
                "Shoots fireballs with bare hand"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." starbolt"                
            )
        )
