@plr = player()



@hero = associative_array(
            'name': '§dSta§5r§7 §dS§5a§dpp§5hir§de§8(§dC§5F§8)',
            'class': 'starsapphirecarolferris',
            'sig': 'k/yCE4m6ekKX4bKSAQpPPY/QbmsjqZqwdA+FigNcLXZMt6antxbvPawN96yYJ0afBnPWx3ohXrQWm4EAOGgO0FlyzZvVm7SQupz3dMgv07xKnbHAdKAPG2biPR56tOegiiPWAXdQxoP/Qly/J7bhlKbbXH//36YDLYWcafOsfm39SYUjQpGYoF4yVL6ToifWp5iQMHToiEwLRketedQLpDZzW/qGgJWzT/PLdSPDPQeckVsGIt+E6ob2lZmCmGpMJl4kYYTI8ub3G4Uel8olB1sulhTwaHEiGpj3/2oKeMdl+Rr2ruHYFOqDU449oBNtBMGakwsrD5gtt4DLKmaB/nJ/Z8TJI1xTA5ZP6vihHjj8XEue2S3kB3NTYX+M5NkbUEj9CYjhipdrFPpdWnBKFXbkihDK2dtH6SE9IJqqVGk0OJgg4+97t1MsR9sRn+dwQVVVRFQXRw5w+ip/TrINmkyccRbvgTvdrrFLkBRMFW548SwdM4q9R0kKfUVjg1UyHwIoIdM2YZDXu5jbO1gyjdSphG+UsHW6c2GKRk0CANz50Nx5pAruW51krAn/Uam10GbPxo9gvzapAezgEF+Wc3j3k2y0cAhOe12/qKfCO1DlqKrIBXeiyw9AmSbkKwobRmu4r+SlGWZXnbRzCo5I6I5iVUayUCG5B0EAK6/fBQE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIwMjYwMjg4ODYsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jNjMyNWJhZGRmZTRhZGJjYjI3OTFmOTdhYzczMDI5ZGFlNzg5Y2RjYTU0OWM4MGYxYTcxMTM2OTk0NDEzZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "For hearts long lost and full of fright, For those alone in the Blackest Night.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-4",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." starsapphireenergybeam",
                "/give ". @plr ." 95:2 64",
                "/give ". @plr ." minecraft:dye:13 1 20:2 16:155 name:&dSta&5r&7_&dS&5a&dpp&5hir&de&7_&dRin&5g"                
            )
        )
