@plr = player()


@hero = associative_array(
            'name': '§6St§da§3r §3Butte§5rfly',
            'class': 'starbutterfly',
            'sig': 'nmuA51rsqyRqrEFbou6BRd/wVK9Moe4P5d5jGg2Ax9fy3urgbySsFZPpx3BhH7HBQqweeg5TepqP+aUDUPVYcVRKob1iXvucAuAPAE5AvrmI+gEUuvf7srU5Zt4chOZm1ijG+hP5f1Ke+gBkX77iXHMz3sN7xsGBOxISqbVnEsZnDomGP15q6VT4CNDSCco7lppYqnehULLir5q2UAxZYrYgFdZRRc7bPchg54pWAWOlFPpeZJ+YiVTdzoSdcPcVR6PH33PJCIKy0DhHAUoSGZe60ByfJRIy7ACPjfy+9zgogaivaZZ2L50E8u5V28NKlYgcvO1G1q1vNjdGz2ZhKuB85Av1YMAudQFLIXZv9uXsCxpMsLi42M0+TPZUPd6b4gl2jjTKWt162fYj9vTKkxn8E37lGaTXYS7709W9gRsdqxVVYGrsHeq6d8Q8o+oaJyO77anEgPJQsF0gRsI/NywFQg1FVtu+42rOH/2kZPQ4RSejgLQaD5Mgocv7eBzRKz5sPCAKJg4wisA63KXXhzKX0bvSXZRAEM0xE9bcGiNVCSEz1LAUd3MdgipWSedSCqMtZ5aWyzvNJHtPzl0TsdQDZObC7bug5vouwMRNZnUUAUMuuvLmBcV6VfhdFZYpkzlkwBupDiPXqq9gauiRSvDJgsipPpW8ds7/kPJbP98=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODc5MDE1ODY2OTcsInByb2ZpbGVJZCI6ImJkNmY2MjIyMGI3NTQ2OTg4YzgzZmExY2EyYWZiMmU5IiwicHJvZmlsZU5hbWUiOiJDaDFja2VuIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjZhMWRiM2E5M2JkMDNmNTY3YjM5NmRhMmU0NjgyMTc5NGM0ZWQ3NWFmZWRkYmRkNGRkOTRhYzc4ZTk5YWUifX19',
            'trail': '',
            'op': 'true',
            'speech': "Super, rainbow, narwhail BLAST!",
            'powers': array(
                "/buff",
                "/gmc",
                "/gms",
                "/mutate <playername>",
                "Access to all warps",
                "/tp",
                "/tppos"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:stick 1 name:&6S&3t&5ar's_&5Wa&en&5d",
                "/give ". @plr ." minecraft:shears 1 name:&6S&3t&5ar's_&5Scissors",
                "/shot give ". @plr ." redenergybeam",
                "/shot give ". @plr ." whiteenergybeam",
                "/shot give ". @plr ." yellowenergybeam",
                "/shot give ". @plr ." orangeenergybeam",
                "/shot give ". @plr ." indigoenergybeam",
                "/shot give ". @plr ." greenenergybeam",
                "/shot give ". @plr ." blueenergybeam",
                "/shot give ". @plr ." blackenergybeam"
            )
)
