@plr = player()


@hero = associative_array(
            'name': '§dS§5t§4a§drf§5i§4r§de',
            'class': 'starfire',
            'sig': 'TpCyjMn7TkiMtY3Zpw0mFE1JvviBS08aKc9pbFGLEilFmaJrViprYxa2K8wGW5cR4MMLXLXiTV70kQvZTNZJbwEUHdYpoko5im90Y3kNMVqOLr0VENfZfT5z/6cFDMhRnLYT16h/tqWMVXbdeq3HKCT2Tvjhc9rKVVWegTiUd/LXEyJEICRmWhIpRLiQM0cUQuTn4va5t7IKtwjCyzH1FLBMXBn3+W0xzX2kdjtydG6tPVa66md+AnFM4qsug+Kz7MHP0kJFb8mEgVwA50NaS9WdBepuSimdHkO140DdUrT+tv7MpXB8Ty7jc4guKH/Jpprnp6g4TkIzZUW9hoT4ftEJuxM+b4e0Ga8O6+QMkCv9DkCjqR5Ufg6l8XYx4+k199LfTjxqHBCXj1sUDZANMMcpNgsnsX0oqZTp2p/ia0o/gDMhzaOihRdiOYNr4Jkv+wM+KlA+zmlYbg7198nyYEURGubD/IzmC6rs+mE+rREYe+yLMSJKaZOdcrFMmZaKpYrclR7+SL9fwIvVq5eEvXob7u6VDKWjuaKaLMz2b+BMHlZGjFl7Dui7kcc8tZYsGje813AiUFW1p2wadueHAmcRLoOAIAn4/+hbP00d/q4Qr52vLC/g+dfXvnzWpmcc2D584ln4iA7uMDEVI9G8Ov6NTgLM4jrhDC3x8ENof04=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTU3MTQ3Nzg0ODUsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJ4U3RxciIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFhMzNlOGRiMmQ0MDFmZjllNDFjNWIwNTE1MmQ3NWM4NzY0NmM2ZDY0NzNjZGY3NDI5YTQ0MzliNGZjMDg4In19fQ==',
            'altskins': array(
                array(
                    'sig': 'E88ui1ZPDkw6NrB4eKFuUsTNg0fVLJmncuoX7Txw15Mk62H1yRc+nu5aSjFA4XSUgvG+fdFiunjrgY1xSgNVdEt0cM0G2U36ySDq80dLIl7p8QydT0k6jyXluBZseKhlJecfz6prHyn9vbyVdf/NfzPqt1sdVC1Jd3CJYxAh98ukciRKKocEjnYx17cxpINeKgep43E6+mboH2sXQsbUgttow2hNeTGlpY3GHrGdyz63b59X1e6Pw9xG2rCs/DboW7KZWqoY6Q5pRvMYu3Ye3i5xlmZc9DpYfYvwJffz7PCfTn+rqSYYW5fqlJNwmdDezBEW62MRohf10igvBUUoWOLhGCgyroe1AKN8kyRVqIdn6hmK5+V53wCE78Exaq8fc1J9crkvbcvuBeSTAMCZ7wt3TrireitxeEV3ZyXkMpLacFqAR0+5p5ssO1k2H4mqVa+wY5tXjfSimfMnsIUoKFlYB1aLQCXiebfZznbjgtf36ha8EQjzpnNukBfWQl0tJ14eov93ouVe8TVnoNTFSNdA5UwzKH5eeUYAZda5P67y8+Q07TRJE4l1jMHlbH1sY0k5G+x9Ly/Esf10iGerpBwiZqzo0IV+4KnKYAmrvaYVwl8wGCk3l+2ZMAlNburgDlI3iMM4EpFiinUobuxqfWpGogmUouEnGjwojD8BUZI=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODE0NzI0ODMwMjIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJSb2JvQ29kZSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2QzOWEzODE1NjMyMjYyZDQzNmQ0ZDlmZmI0NjdiZGZjMGQ0OGFiODQyN2M3MzQyMDUwZjc0MDZhY2QzNjZhIn19fQ=='
                ),
                array(
                    'sig': 'EV76mVO0cLDvdeNWmaqLEc2g9lQJY843oh4ZpU6zP3z7w28kd/G3nE9y3K90wUgprtzQQGHRT0zJ4gog4eyeXIvnqmiITLlxI9RU4d5VLsd1yPhh8kYB+cH9DcAKXx3D78JxURTMPzl2jVOfpESmEZ6MQzU+ZbnlLvb1QEYhoDmjxCK9SCdiDsYc26zD8ySgiDaw3S7vb29PneZImKCHdCdcDmtcoDFGn3AuZp5CKV/aEH2vG/xXHpzDt3eDxSbkQeg2BkaxEycsOR5vLHfR9Z79AopCdSlVOD8mN8HjTKEbsD2W7ictKoFx6dsWVj9LZL+PUqCajvddARR0+NNjE87gsEmXskmEKkC4CuVjjfHkEsCLkGIU2Pu9mnxUreg5kfGSmKduYa4GxR3uEsTROdQ2lLT8+NyQidhJuBQDir6c33CvrL72cNf8AXgKoxMjsUN20Yqe/PTVg/fzNPlprKHOXVlUCGdF6exAaO5ceEBaAaFm3Xs6NKgsSGIIYmhS1qyDSBR6HXfpRNiy27DAZSVzJoXd2qQAEi8qC6RQCmcUzjrvQ5ddLh4RZllHdCdTsGUvt2xXl+ixFar0zCkFAyfNvzuLsTmCr65qIn3SF4oNlZLvBuhgbxZRGrdPKE4j/xJAbrxmK7hhKJ/+LKfpwMrxdDpY2K9yrlnCUR58Xpk=',
                    'val': 'eyJ0aW1lc3RhbXAiOjE0ODk4MDA4ODIwMjEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJHb2RfRG9lc250X0V4aXN0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOThlMWM5MmMzYjJmYmViZGNjZTVhZTQyYzM3NTc5ZTI4N2E5NjhkNzc4ZWQ4MzExMjFmM2Q5MWJjOWIzZDQifX19'
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "There will always be people who say mean words because you are different.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-3",
                "/flyspeed <number>",
                "/fly",
                "Shoots fireballs with bare hand"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." starbolt"                
            )
        )
