@plr = player()


@hero = associative_array(
            'name': '§3S§et§ca§5r §5B§3u§ctt§ee§3r§cf§3l§5y',
            'class': 'starbutterfly',
            'sig': 'ZeVEQeOd8UouZ9/mk7RGKcaGHMQZDNeZAXzVQM2X6jaSG7P2jTl/aztoIddHaVLUmiIDBayhnofYS7BJjkGC2rVWQoB18knWMsgsBaGffbVaAHrtedEnE4T55BkhvAgFCAKfirh5XYCL3EhNbGtZe8XRStaDuB+irJDCEkcwD5JxJXO0U1aFKx2CvMK6WYggo+hWTMYGAvKmTFeVCOUXl4fYHYzwT+mXcamvzMQoK2kvWc8X2N2UTq++U4ulmM6kzrxTx0ZR2uOcKKIHcvUcL943jFSnPNp8ncm0BuLR4KbtSORuNe7IoRQXcGvZSqJRWApOes0xnkxJMzVN9wZjDW5ugqYa49S1KblousN9p8/DL3bha8XyRdFi75H9TBJiYkbmqbnl4MhzgavDTsEq+XmQIfZmjsIl6YbT7Kd7KZDB9YQEroexGVWbztZt3R4excsqq2NproUBiFQmc0DFVP3ziImueSOn/Uq6/sKKrisX/YgC7z/wI/j3y8X7l7Q0EQL15KwTc0LXfYPz7lcd77sODE0gTvQiO57DyULpVHilel4kTiH/1y3DOqHw9Co9wqnl5CcbfdKg3txGFpB6M0tipAyK6tzUmwZUNAcU1eRU9VNIMUvMbyzh+dCcaLWQPw2KKPYcd8Z8nWLA5MnImd1yg4Z8Sj3kmKrO/kuUtuE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDk2NTA0MDUwMDksInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJpaVNpbXFseVN0cXIiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mYzFmNDA5ZDlmY2NmNDJhY2FjMTc2Y2ZkYTg3NWZiZWFhYjFmMjdjOWMyNWMwNzViZjQxMjQxYTcwYWNiZDNiIn19fQ==',
            'trail': '',
            'op': 'true',
            'speech': "Super, rainbow, narwhal BLAST!",
            'powers': array(
                "/buff",
                "/gmc",
                "/gms",
                "/mutate <playername>",
                "Access to all warps",
                "/tp",
                "/tppos"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:stick 1 name:&3S&et&ca&5r's_&3W&ea&en&5d",
                "/give ". @plr ." minecraft:shears 1 name:&3S&et&ca&5r's_&3Sc&eis&cso&5rs",
                "/shot give ". @plr ." redenergybeam",
                "/shot give ". @plr ." whiteenergybeam",
                "/shot give ". @plr ." yellowenergybeam",
                "/shot give ". @plr ." orangeenergybeam",
                "/shot give ". @plr ." indigoenergybeam",
                "/shot give ". @plr ." greenenergybeam",
                "/shot give ". @plr ." blueenergybeam",
                "/shot give ". @plr ." blackenergybeam"
            )
)
