@plr = player()


@hero = associative_array(
            'name': '§9S§4t§fa§7r §4G§7i§9r§fl',
            'class': 'stargirl',
            'sig': 'KXRHlBflFIeIFZMNVelatsCTDO6i3v974svEqQslj3QbRjBdEuDnH3cLH8rn9l1EUH9SoOy83bDLUoCEAbedUxkhgB6wrnMqXz75RryhSN9NUtGff8j5NUp0r2+ZQswgkt9G74I9P0LkMpwOwPX2dpAqVlNuuCy3QwNchcijRSY0ad0sKgLYpzUB8nS786tUpeMukEo1hkRW3ZP+qBXp4l0uKjLxCCAPJJ5XXhAvQaDhkZUi7N2H77KekDN9C9yPszEvT/zT76c+xVvtlk+n/uU/mP5mvjRpemZjCHlyBM5+aNeDBkqrFYO6NvMGwFCnk3BEHU2TbvZP1SaNb55be5gQJ+cs2d9EXxI1IwQDRfR/PenJH54vmJV/xm3AJ359W81zU1uyqvpBRnMx+uXHuv7Q5iMSjsHx+atT7FHJHhF421728ZHCB5yMQ3gZ/buOAi0MFi+s4kzpYmnNjbAXPzrdOLKdDZ+Qq0j8Xyww3+SOHRlPfVfVGa9WBqtlzsVGT1+q1Gqf5QuWqPUQoyrcXDQq0ZV7LASeifvPAW6H/Lac4TDQ3CQQTuDQvHxoJeevy8d0WHfz+Miwv6UvNPbhTubqPXhyAR+rjGe7+NAeLGoRXvuMxsNZXOxhlPbGBsc2sygBKjtzmzjQEdn8i4AHLU0Vq1i65fJpF0B8kUC+568=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTE1Mjk4MjczMDgsInByb2ZpbGVJZCI6ImU2ZGU4Y2YwYWY0NTQ0ZTQ4ODJmZDk4NDQ2ZjRiMzFiIiwicHJvZmlsZU5hbWUiOiJScW5kb21QcXJzb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iYmMyNDFiNThkM2Q4MWJjMzE2MzlhNjVjNmZjNTQ5YWU2YmM1ZGExODc0YmQ2MjhmY2Y1NGQyZTg5NWNmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "For the record, I don't have powers, it's the staff!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/give ". @plr ." minecraft:iron_hoe 1 20:1 16:5 name:&9S&4t&fa&7r_&4G&7i&9r&fl's_&7S&9t&4a&fff",
                "/shot give ". @plr ." whitenergybeam"              
            )
        )
