@plr = player()


@hero = associative_array(
            'name': '§fSte§7el',
            'class': 'steel',
            'sig': 'e7+IdAkiHWV3NB4xCKyDjzEuzgTItdfJejL9RdjKe0ZcltP2MiutAw8e9lEiE4JC3CUKAyk3TD213kkiqIihAbmWkksJj1xFjKO4ndT2/HJ4uSZ1sdefptLcMSVy/5OJ/D2JVLITRETy9Z95Sr2V1Q4urlQ89O4ZMTpyWI13uvDdsLlrkTy0WqAbbll9MsaA94x60x0UPiRAPHHKJR9Bv+BUIEL5OZqmT8ZnZ+hhZhwmECzoXMCtQh0pYd9kPQb5Kg902bmti/llW4cTZuJvyI03s5mwm8KX2S4O/wHKXtgARcC8To+15W9xIUHHSkH4d762fQCZjHTrcbIqZa1Q2l9I4IeQ5x8kx44yjPQ8cHycO3tSKi+nlUV1GaRL1VRojdKnjUnd8EnBrm/N+yIY/ZfjHgmJPUsWHMi7FiyDxod4FJC7xgiR5YEltsS0ES/vaAYckDLGgMPu3SdeF/++o088q5zXyHBnBEDh6VChCgnQflPIVw2CeSZbZsEJqTdOeRR6JxympXAzhJHA0oZ75+y4+/n7/VI2qqPrMR/zgnUN9yqYMc40kcuvv0MTzN93+mwT59oztX36Z7PV7bSMdpwYhnbdd3nCpR2VHItbQQ2RCY3I7+UxGVjdzKgZ3u7jsd7N5pPTaJWnMCjPkHjZC/c71XMs/wmtpLF7JNZrs60=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODYyMzczNzY3OTgsInByb2ZpbGVJZCI6IjU1MGIwM2NkZDllOTRjODliNGVhNDRlYWQ0ODljZTBlIiwicHJvZmlsZU5hbWUiOiJBbmltZWxHaXJsIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80NDg5ZDY1NjVjYTE0MDY0NzRkZGI3YzlmNjE0NGQ2ZTM0NTI5MmRjODMxNzVjMjNjZThkMzc0YjgxNTAyZCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "My grand grand grand father was a hero in the past!",
            'powers': array(
                "/buff',
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-5",
                "/carryplayer <player>",
                "/disguiseviewself"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 14 true",
                "/effect ". @plr ." 1 9999 1 true"
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 3 9999 3 true",
                "/effect ". @plr ." 10 9999 3 true"
            )
        )
