@plr = player()


@hero = associative_array(
            'name': '§fSte§7el',
            'class': 'steel',
            'sig': 'Pa4YphVxmC2VseeeqOKmsyuUQTGF9ctd2lXayzEprNSJ6pv5D+aizO3HUSJ7t4hnYn+f3hzbMHGNY0U8xXq5dJd9dawFtWD+AoaCLvr9fKjwL5Wzy+H0qbN5Pjl7z1KvU/6UFbOirPKfVDSQMJqfKeNWvw0X+Y+CCOaLsV9zsjHj6lzENpdq6+ts58C9Eu13LbpVmLyyNThW/qbOOm5yxpH4cTGyiyopOOd35TEDGryJYx6bD8jkY8SKxDKsgdvU8TFWBjnj4xDs0Iho2G/CZKSVkJhgnZEUzm4XrJc8kkvk4ZwPLD3AAxiWTsQaYmPumrW+ZXf9Wl8xbXzFRXM1Wmtcj14XNjdBjL+WnBshQwol6cDBW3TB9D2/NKX0YCDChvkIE03eeJ2XOVJvTyMIDKR6r9841qCVVaywipVEE2xayNguD1u0oUW/ueAMIjv1/oIESs3F69+LXsVQoi8ydThX18Vu84ekBKLWLA9rJ151Cq5/tPR0FNnPsQ6pORAqF3rqeCEvwLkm3WZfA8OlYOKyDxpERvkxdXZYzNY3XxQXnmIAe0L7FvUMUqRN67+zxkoQ1axZfCHbxLBuCp3v+EQ6j4c0ByLmoZZGM94vXDM3BbRiftb8fYYN+eSV2MSLWlMVxOe6rYmlavIVbRj1c+3Z9HRe8QefChK3Y9HCo2Q=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODU5NzIxODM4MTEsInByb2ZpbGVJZCI6IjU1MGIwM2NkZDllOTRjODliNGVhNDRlYWQ0ODljZTBlIiwicHJvZmlsZU5hbWUiOiJBbmltZWxHaXJsIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81M2Q4N2JjMDhlNGM4MDE2NDI3OGViNmRkOWQ0YzVkNGM2ZWRiZjJiYmQ4MWY0MzRmZDk4Y2I2MmRkNjE2MzE5In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "My grand grand grand father was a hero in the past!",
            'powers': array(
                "/buff",
                "/jump "0-3",
                "/run "0-3",
                "/haste "0-5",
                "/carryplayer <player>",
                "/disguiseviewself"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 18 true",
                "/effect ". @plr ." 1 9999 1 true"
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 3 9999 3 true",
                "/effect ". @plr ." 10 9999 10 true"
            )
        )
