@plr = player()


@hero = associative_array(
            'name': '§fSte§7el',
            'class': 'steel',
            'sig': 'kpbQHBQk0okZt+uSFc+38hfR4JMAQt+6fCdHozmFX7M0LUW2bT7EZywad5qy+Jst6SzcdcZmtnL62JL8UZhiDSFGyX4jizkPYd53LQiGreFJ0Dm03CCXKY/TkxAgJlLkN07mFzr2qTMHHvL32Ox8TCZ/UQcMkibwKIXmZLTWkPE2Bn7Xw4rbAu1pySZwbK4bHVld26Qhpfw2dgkLWrZOcGhPm9TJ6sL3WcM1pZJX2091c854kWGG3jb2c0GWh2nqxOqoNRSrsbodmQN3SwBpEenHNQwLlZe7Y2xXp6hPj7E/TkERhHxHGic3qGXIsz8+X39uAA1COy/5JVApV2a3HxVQE9B1DP2BUkgGNtQyDwxqZX+tCN0i/Ot/I+JYdhpQGC5ORRUe7S4YSXoiPF5EuCd1GqnmIjEnYPlTGnN/Se4N5OGBeR0HjLe8DnFjhOyVqzIwpONgjg5NXpsEHGAM55O9dPbUJDYN8eH1BzW4ZFqm08ayG/QRhSKillmsj2I2D7sqy4ggJrH5wYR8MtDN5r6yGtxfX3quW7ako+jWIRZY/bS9b+3ABlRPs+K70to2QoMo+SzJ1ZjWFVK9UdBCqLETG7YBNH2WAgRt8AKzeiB0Fuz/aBwh7drPtj0A4DhwLsELbwqIhXJ9ooulzWBfLVKcytXmjUwtK+isGyhEwwM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODY0MDIxMzIwMzAsInByb2ZpbGVJZCI6IjU1MGIwM2NkZDllOTRjODliNGVhNDRlYWQ0ODljZTBlIiwicHJvZmlsZU5hbWUiOiJBbmltZWxHaXJsIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80NDg5ZDY1NjVjYTE0MDY0NzRkZGI3YzlmNjE0NGQ2ZTM0NTI5MmRjODMxNzVjMjNjZThkMzc0YjgxNTAyZCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "My grand grand grand father was a hero in the past!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-5",
                "/carryplayer <player>",
                "/disguiseviewself"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 14 true",
                "/effect ". @plr ." 1 9999 1 true"
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 3 9999 3 true",
                "/effect ". @plr ." 10 9999 5 true"
            )
        )
