@plr = player()




@hero = associative_array(
            'name': '§eS§1te§eph§1e§en §1C§furr§1y',
            'class': 'stephencurry',
            'sig': 'L+IiMBg7xfiPNyHyg7cv1ZRaSUMQ3Hp03wdm00Jr69wMIkmZbhrg0xhwdwM09TjOIhZBWdI3o6on/AvMVdSmoH7GJm+LHvA3rVCK99dkDOY4J/lKAQEqHSzeZw8dBzyFosD/LtKovsapK7ICfMFFTxcR4GKqUt0VkT4j4KaLnErqqSdYXHvBTv9r+p2URPxCep1JClYvbcFTgDYgR+MY6wZAr5dB6CM2aemmNJQAzN2K0KIPwj1KgMIMk8Lved/F72yAZdrV474rqwS8bMBgj4Jkbt1mUznXJfER2uu0c0HFefWG45gMA50MbOdGXfDbcdZ64yFw1cTolW0zYcKiphGlHznwrbSRe3EaELZcHnpH8nJ9Xa/yPpQ92xW4oiR5odHdhNPKxnMqOfZy2Q0R/T1WHnPzJjv2EU1G5CEhizG0OgRYxaCAHKgPS/FzrAPGc8/5inN98g2J+FkvO20UPqJtUbHfy6qBg53/kumUgkIftb2VNn1YYp9VAERB734FvBbkj0XySCVu17yDHdTyib7K0/5xs23dV54uaAF0i/GxBoPeHsqoep3xPz45NkGzDQhEM9vbn994P/zZQrmupXtwLCOJQJjL6iZ70CNi8tbfGvLQR702X7Ub7SAKDzUOrjTDRonfI4TZwfAP6PB+nUv+bqj/AVIZ021cY30u18c=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NTIyODM5MjQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdlY2ViOTczOGI1YWExYmVjMzQ1MjJiMGE4ZGNmNDE4N2M3OWNlYTI5N2RjN2E0ZDI4Y2Y2MTJmNjM0In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "What the hell am I doing here?",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-1",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true"                
            )
        )