@plr = player()


@hero = associative_array(
            'name': '§fSt§0o§frm Troop§0e§fr',
            'class': 'stormtrooper',
            'sig': 'MbrP929kjMyPnpR7RcuSN2iFVwypykQmhC3xtxflkTiHVimxQPhyGBkg5a7Kwi9QXYXt5hNOsmJEqRVzFs9yjs/wgRd7XQlC+hIGGi2oRJT2pecLYJa/8N+jLZmOu4GOKj24BjG18S4BB4Wisk3dR297bW1006vSlRDRDXPQlBFUb9TU9O3iDFcsbjkdLnJbtE6O2drHTbBmZ6IgYm3uoxtRTDJ78M5Sv7ckm7DevICwGN3o8+FXZ9zgzLnRNfc9y8IB/9RA9SuoUQD5LAM8FTwjcOIHTF3WWLuCpKSvP9W+Kiu/CUYTSdIC0N1jljyXalMYdq7pUXblzQkjgfsUlF69bfeaA/FOG4N5lIHONUTL45H57Nsp1WsjPC+0Dzdl23ufAtMrJSIiCLdTube6rbtcRE/uWWfJJAiuB+zqERb7GRYkxPi0OupQsh02x3xvARIUwTLL6HPCEmmeAnd1DCzv0XVmT31hnn5HUraTkgICp9QKxt9ODpiV5Wmpxn4+BpsKPeuwnBgR6en5Mj4FoRemi3x2tmfjpa7FLbkz/Vi9ksFA1RCbdNPjNkmhkpJYYUZtldLb8otesIqYmaVdvmXIuirDzZdFj/FmoV+bfiOmCap4unFr5JefHpED7TcKxfjyYdS/rUZDUXOBizMNUczRAQPkaec2knCmD1txwoA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTA3NTcyMDIzODYsInByb2ZpbGVJZCI6IjVkY2Y0NTcyNmNiYTQ3N2U5MjgxN2JkZGQ3ZWM1Njc2IiwicHJvZmlsZU5hbWUiOiJXeW5kZmFsbF8iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83ZDJkNzRmNGI3YjIxZWY5N2Q4MDVhM2E0ZGQyN2I0YTZjN2IzMTEzMjU2ZmI2MWI4MjYxN2ZjY2VhYzRhNiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Blast 'em!",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/shot give ". @plr ." Grenade",
                "/shot give ". @plr ." blasterrifle"
            )
        )

