@plr = player()


@hero = associative_array(
            'name': '§8Storm',
            'class': 'storm',
            'sig': 'O8tTjrilmyrr6SY8bgVxrV1NWQRz/QPe6qaKBvEaOyBmEg61QVQko9QKK8WxWd3ylcAhsm8jQ0MqV+9+BEly221o0SG8CnmPQAk12m6LPsSTygcEzaCqyyLstfO1yQP6SDo2QnJNHuMzqcrRKstOYkbwDBFbRRdUu9rOfO+Lcj6rflVfVQCyvyEKroPNHqSvHPg3c4UB4l9XiVIIgZ/qEBM1GdckjpdsYX/iW7w98OajGNk4t96eE8jCZNQqMcDuRA4NGz3YcoJ1PPKOnumo638zMsA/Cu1bfjPjHItUlzj7aaRAx5lvAiLG4MeOL/7o61ZexsZbjqRrZ+x25TfhSw45syP7ZJs/m8iigEFDh4H9M/StPDceKDzuBS3SpADLlAbYmtqN+/JowFN0FMXEn8IAA/Y2Xruxniqts4Ox7hqXxdWu6KgeJ5vtlx4CunEF17JZ819JRW0Q2vgbkELgyn6Pd7J6lCWvXHUw5megooA/skwYxBmfZO42giv+dB6wHeXnS1igA7DV3trD5V5NKH30xiQRV+wjh9rjeKQb15bqzYfDi1/LK7Gu+7O74FcZOZ1xGFf6TyWP0Zw88EyFDVwQUsbail7Ohq69up4yLKuRKk0+TwyqQ6G2rAHBIUdDW8PUOaUcz/vh+xPNaZ3epEwR1T1wC9ftevnliEGy8CM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjY0ODI1MzIzMTksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iNGVjNTMzYTUzYTU0ZDYxZjkzZjQwN2U1YjQzM2RhYTE1YWYyOWUzNGE5NmU2ODVkZGUyN2U4MzYwNmNiMWEwIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "We all have dark sides to our souls.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-4",
                "/run 0-3",
                "/haste 0-2",
                "/flyspeed <number>",
                "/fly",
                "/lightning",
                "/weather"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"                
            )
        )
