@plr = player()


@hero = associative_array(
            'name': '§cS§9u§ep§9e§9rg§cirl',
            'class': 'supergirl',
            'sig': 'ccxWzGt+poCGs/lNieBUMytCK2cQz0PYAbXz4i/xxIH9VSm/KOyJlsnXQLaCqMNPUCvEnLZKfz8L3wgGgZi3MmgddiQ1+8CGzYPEdfpTaSCSO4cbkG5FEp7eh6RRXHLzh3RdebYr9CNyPsn+ROufUFwJmKeIOE9TA1eAnc7iRZ5c++yk6+lyq90kCbk0yW9O5kNKgdvOTmQw3i6WbncGx4vX8FMIiZJgB0KMGKEbcllcaxUumJLD43FZVlkYl3iAb0T87XsifpuLpGqcsnZrjT0Lz/jdEEq9pzF4LgFTcNMUOlMhaIv1DsCyHNe0Re5c2Oo+ryZqoZQE/vxQ6t9RziiO+cX9SDSp2MKZTV67T3XNDIEcMOO4TpevK4jAZxul1g5/2AnVBHEtDkw5WVqFrl/Hjas70cHhL2kJpej1CsSaSnbLTalc5hrMOIruHlmR0Qe5Vc413jlA5gTcW8S2s3VIFhZEoVOgfYEfkYF9KVBZR+iNRXtQV65EAhsTiY1FkjGASYQWDkB+UXbgcx+bdfELmkHGZh+/3Wb0MohXT2Z8UXxmauWPGAG6/MsH1obWcSjszV6nfYi/ijZzyzcKCtyLzBKmujC4nQlrRrQnwUv0QlFf0mJJMrKGVynG00V4AyUikwH46zG6yDy2QDtRowgsr1K8+r2YpWkXXBYfgKk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzIwNjU4Nzk2NDAsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iYWRiN2IzNWUyZWU3MGRhMDQwODA2OTNlZGE3YjY0Njc3YTg0NTQzZDZlZTcxMDgzMzEyMjE2YTNkNmViNjEifX19',
            'altskins': array(
            array(
            'sig': 'j9Pmx9vylYGX1s0JoaOpC94iSVSqEu7LVtsHtW3zBxH3wycRI/nFnsLkjWDkns6hgsmu60w9MKxSqvHOlqtgNlS/3z8FLfpWCmsv8v1R7IVkqcXvZTgaH9AWT11bFkB1HgvST1BEiLqbO1yFE+cfzKThGc0nNaNwr0/ph3MMp8cr50BZle6bLu3ChK0TzuPKUVQFBGXnTFvI29fdL0YbJFga/akEmQtEJurSqq7Rix+vPrLbJGoyYmhOkd/3weIDbQU8/YtRez7xwnXC/RXcuIEUCVNml4WDhXZ0jTeTw0TcWtebeEBVsah1pmJ1AdeFon4tkpsQeA81vMLmOw2iqKCVS/CMUri6elZsj9yfufRqJcj2kAjTuCdEzgWNineC9PwojHiti+/xkdFJan+V9ha/syjkF39XckEvqA1K6Kjp4I+zOIlORphXNuIHf8ou3vzE25yvaE1nEywXPXRKTeFt/UCVcJtLLHyEIBtas7rYEHN8hWbJBq2AvQZcmOywW3jxfxzKa69oi+lgtAMnOe3T5A6r/8W7HvosgzGVnD0e+E5zFsGvrgN/TpwaGkJ3g2JHhzkZ2abkVRHzSjeM6gD5RWQ09Khy6ya4ckPJIhMtvJmvRhjh0X60ddPp0UhQwzJZZ7uUc5OYndPHmKVClSnwPTcJU3Zo7F4fax0AmGg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTUxNDkxMjAyMTMsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJSYWlyYWt1dSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzc5MmExZDFiNTU0M2ZiYjdkYmFmMjRmZjI4ZjkxMzgyYjM1MjhkZTkwZWEzODlkZDkxMGQ3ZWUyNDNlOWY0MiJ9fX0='
            ),
            array(
            'sig': 'MNgVC8BkaqDMhOMeVE7LvruW1prbeoBdqzzVKYbAi2xgdpm0gFRQwnKfHKyTOFH8Zzycbk/ZI16UZ1ZeWQhvNiKkoXfkoKApFfVYhcvkBEXM2oYltjU+Y5Jm3nA2mKz6v/XWs1u0uqrIkQmzOeK4sEzdzNTUHyxPIqhnm/46HdoEJJp9OiJguIIU3ewmURwSsEfoX49dkrN42sre/0XfyPbasa16hjI91dlDB+lXXOUqQXXhHFOtAR3iSbSaetRs+nKmtyGzqzm6Wbqo4M4RkGHaLPeDt01hqPYmNk/EiY1lmLXMI5GZfuRdoa0DDfwJrJo5fapnGN2fnkUBR2fnMm1qhU6ohkF7JEOb2+i0pMEeAUjH5PEDnqaLBsSw+UyKxGzu9hL9cbLBsVsX3/0kZ6MXmg8DftpywN8v4zhHpbin8i+FsZoX6CAnLNFF2HcnoyMWzYD2y1J0KNPcO7lgq5GAK/OZEfD+P1G+HOGxkw4Z1Oz+FKA7jpMfM2F0JizfeIltSvimy+aifBaEkR0bqMB5oP5daCnGni4RKXCTwplWomz6LW1o3DlzEVvNqbwJqIk6y+Fajad0LCjp8ub9qgdKgFGWvXRdXwCIF1LfX+zcXheRGgCmR7UE6NFoUpU4z/26foZXC7tga4osvXnnU1VL1icIYSJAmjNhDmToRpU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTUxNTEzMzk5MDYsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJSYWlyYWt1dSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzczZjhlOGI0ZWE0OTNhMmUyOTVjYzdjNzk0MTE0YjUxOGRmM2UzODRlNTMzYWFkOTFkNmJlZGI3ODZiOTczZCJ9fX0='
            ),
            array(
            'sig': 'dgzVE/RinH4XbtUojnIqRoqjrSplob3IPDVTo71WH8G+CTkih/AFhO6FA6ogJPujrtnfXih9Wj1r6h9YAeQLuTswwY+s79Y4QGsE73IiTDf14oiUJzaD31vk3k7ktYzdW4RB/lI/WOUNiBPUXostDM3IdY/sqlVMta01U7v7/2B2HUe870qxJdXRJw4Mwe1GDFAfnad0NXsHVrvhL7ibpG6qNF5XZH2QRqftfbOSHcTG8RUv9OBwrN8wzIr2p9RUgdYBpkTxwuPGun1L1doxuGMrWmwrDhZouIWSsa8TaFLK/aax7asuAVoMq7IHdIhOjypFkXRLE4CjN3djpVxTy3V4xcrt3gYEAUBFdRcQaGTG/oJNw75br/YInYyybph5vBOOxmSHuTmdDtKp5mMqdX6yOMj7MzVY3Q2SXvlIBxWXhJb6wkFQBLyYUujKgePSDVnAGq79IEaoN4ZLvyPkZq3pPkgmgn/OxQHKRBGkCX5xCM882/Pdu+HqqomvxcVrg5LpQ7HmgezZUoqRrdpVpgrLVtDPnThXhVT2hi/s4KS9omNwnooddT4WQ22Mz8DK5QoWYeIIrmBNmHqLvsspf8wSmQv8NxqiknjJeYYthZezx5QJ16edawqcmeaosE5FMle5BXGZWcMvGY/f6dpu0GC4y7QMv5fsIccQstVGBC8=',
            'val':'eyJ0aW1lc3RhbXAiOjE0OTUxNTE2NjQ5NzYsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJSYWlyYWt1dSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdjYWVmMTEwZDhiZGNkYTgxYTg5NWQ1MTA1Y2I2ZWQ3ZjU4M2YyMjY1ZWRlNGYzMTA0ZjYxMjhmN2YzMjJiZiJ9fX0='
            ),
            array(
            'sig':'ivzyef0yrHZ3ZN6nxPxXVSRSvy0EEpiU1gFhBvGJ6BNeS2JKibmk1MiONHH58TdPicpf/LgndFMzbsM3rf/2gyRPRzeQkbnOqcNaVtRupDIkk6+0NV3fMqIVKbRdqoDLIwWwIGVQSH3eoPXoERbTf3krAWRZKuT0sttPCKla7oFks5ghQiFFQOsirJhAgB4+whi00HByXWqLtCbW04cg+EuCWfgy2aP/7wbPRkSrniWb6jWMlEOz309ObV2eOeKMAFnychcokqmvs303tHkU8OEmZh27b2i7LSfU6yRIfWVuF9798ud6qv0H474O5Z13R9lgj6TUWuMNiDqnNzD5vc22ORNUf20qq1a2VjEyBuVQoujqnRQ0ByEjiA1r+9dIp3pzZ5u5AuPI91PXFEQjqjb7gBJZ/ZV5Tu1pr5muCCjCmG78aNeAaLl+UF7HPoY1N+2IHc8quwSWlX9+3ZxF0FyIYAI6bTWA3YWBWItoY+auEX9YPARcZoUP4+QIzaAq9Le+lvMa6JiDLnug4mfBqzhb290WrriOyrdMZbF+YWsIlRXhkPr7qYdE5RJ2RnjjZZ8oshAYxnUePKXgli9flqlUpnMRk6KrN94vQB14Hm5AiAxgWzJsfeBtyYQ5HWgD0i/B9m5DDJ3stGHCNQfiJWBSgAzg2wbw4IrkBpjfX3A='
            'val':'eyJ0aW1lc3RhbXAiOjE0OTUxNTM3NzIwNTgsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJSYWlyYWt1dSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2RlNzk3NzNjNDQ5NDI0ZGE5NjZkNDUzNDRkOWQzNzllODkzYzUwY2M1ZGI1ODQ0MzU3MzU4ZDYxZjAzMmFjIn19fQ=='
            )
            ),
           
            'trail': '',
            'op': 'false',
            'speech': "Time to save the world once again!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
