@plr = player() 
 
 
 
 
 @hero = associative_array( 
             'name': '§5Su§0pe§5r§0-§5S§0k§aru§5l§0l', 
             'class': 'superskrull', 
             'sig': 'T/Qxu489PDNNK/iq+7xBX4SsU6KukUzIfUUYst7KVcaruUOsveTpKJhfYntpxvzwVBo7cTc6ixWLQVq/1w/tovpRX+tq89t37+yVQcuEoW2YbtXG9HjGDIanIuiGSkX7wBNuZDhjbeYzCcm2sF4e5+PtFyC/Jh9RM3oCqvDxp0Fz8vk2NL3Gsd11ReFTJUCtLUxcO19RKX0JaHJQuCqUhhGgDutS5LDoPWKyl1ozHHm0ILpr+zTvOMCU+7XgtFdYX+35QNUjuaV4W8u71ph8WwWeZxaQvNIg8OhAdUN/BGI+M+nschdZX0mXol0NK5USVAftoI+Ooz61JuJYQs+8NZxnfbUSyIOsbd/t2p6bls/nZXuAOuT0e5FXL31ruHCMG2btybktchGCFEIhRFiUgaSwF9L02LcIWao7JgxH4Z0l2UYxZlZNsu/tM0SJVWtDvr2shTkHOSyXQ4g4FcrGNhTCOm666dBAMxcc50TdIgGYM6+8quXTREDPGLITY6moVDWWkaBHhl9AenXmenhA6zEufh3kpejl1g3i5jOKCTybF6r9C/oJi988jY2X6PRrdiHHx7TqKBMBSJQz63wMCRdvgfjEV0U9kAd2BCvTeTzVWBIimjoAzQUOerKg2t52Llbs+10nWBVS43N4fKFA0wVmQgILRDQvUt81CLHbkEs=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE0OTg2OTc4NTgyMzksInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNThiZDllZTRkNzJmMTFmMzJmNzllZjUyMTU1YjA1NDVlM2FmMzI3ZWJmM2YyNWVkYmQ0MDNjMTI5YWJjIn19fQ==', 
             'trail': '', 
             'op': 'false', 
             'speech': "I am as strong as all of the Fantastic Four combined!", 
             'powers': array( 
                 "/buff", 
                 "/fly",
                 "/invis",
                 "/vis",
                 "/run 0-2"              
             ), 
             'buffs': array( 
                 "/effect ". @plr ." 5 9999 15 true",  
                 "/effect ". @plr ." 21 9999 9 true", 
                 "/shot give ". @plr ." firelaser"                
             ) 
         ) 
