@plr = player()


@hero = associative_array(
            'name': '§0S§4u§0p§4e§0r§4b§0o§4y§0(N52)',
            'class': 'superboynew52',
            'sig': 'RK+nd9UW50d0PJEcVhaFgE9UqoDmneBdMdqArrRJNWDgxzcaY97dg5mm+PSiw4PCP8pSRwq8lx5qB/JpBSQyN/aQC2YIPYsCk1IhLxCMdpfuybKyr/corn8zCh2t9m6gXszxECSgHnz68HIGF6pVNOIdjHxpeNCy2b2RwFovqn4V3Oi09LLMV4VrfYH/99fNef1Kd2c9Y/PC3Sgp0J1GXG+sk02PWZQJAI3WZCHIl8oZmJiznuEhvLH6Ev1vWfKHUJchRiIFK6LToyuFWztUAob84yo74DZI3AttjXtiyRVCmPhorQnI3OAXBxCHY2XVQL8sQ3I7qOni6kPeNz1ypdSYKljwJtmrLEkPuuFY5GTRQLfA1kTUUMQ6mfajgsQVHX8m5pZZ70ZyC9r7MDbDE2NAnLSi/ShZQmaADbVPRRI47VfCtKfSf6SfyFlr+30+kxA6rdJaTTUvu3NtpbHj4cYqZeplVZer3qmqgnpymbmgrIqu6F9oitGrJtIlCcvt/g9QX9ZoCBeBvB1KixyYVKxO4JAnJDj13itMqi4mW8KOyTfWj2v6Rm/QWBDfqyLERVvi1En1BsHf+kOhk59GVFsCCHF8mAS1QvjE8fU+r6VE+U/D0wFo6AKvpjpcgrgin3Y921LZQDMJ7lPg9eRVkPt0ZktL+p6pbWjBEPmI4iU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTc3MDIwNTM2NjcsInByb2ZpbGVJZCI6IjhjYTdmYzU2NjE0YjQ4MmE5MWRmYmY4NTgwYmEyNzNkIiwicHJvZmlsZU5hbWUiOiJUaGVMaWdodFNoYWRvd18iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFjZDRlZGRjMTg2MTRhZGY2NjVmM2UyNGIyOTVhYmExYjI1ZTg0Mjc5MzdjNTc3NzQzOTFmZTZhOTE2YjFhMyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am the cloned son of the son of Krypton!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-8",
                "/haste 0-6",
                "/fly",
                "/flyspeed <number>"
               
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
        )
