@plr = player()


@hero = associative_array(
            'name': '§0S§4u§0p§4e§0r§4b§0o§4y§0(N52)',
            'class': 'superboynew52',
            'sig': 'MjNSqGE3uihQzvN4NNVvSHkObuY77syZN0dPa7uuQwORc3nFAsI08rP08MHG6fuHvn9Tm2lVbpQtDqwsX6WN4nUgki0cqLOU36cEoLe3AUDXRoxuQlx7fTcWC2DOCm4J4Be5t2tLcRMr/pizMgxHWukcjjGwK+EdMkZGFKanS07V61mLjwSAT2NS9AhWtSkvS9zvUL/7M3RTvD6mO0JvEz0IK8WtzP2XHhYCpWE/oBaSXTVqS/zoBslXs+Pepo9MOjlJmOmQ0RVo6mF9yc9IQt714pb0xRpySa1L3P8TF8LM91P5ERG7dEroWLd4daRAb9kH4c1YZ9dDpWb4hpOKAETRWpE1ZwnQML3aE305l064fYhO9my6+jcUqqlJZui7Fy1gmmaBn4+7MACEIqZnwy10QMjqu8zum+VMVh68mnjD9EWwFjcc0KKWkn2S1FHPv6jmTdkeAR9mksnYMvLDAawm30RmiCLSmX6jRleL9FnPLhhRblhUa7Lkx80rGM03IM+CKr7vOznnB052S0EhSsiXkbuMIw7IagPjHIEnwFKqa8pCWwx+mbP49rGyyoMCvzNdBlm4UVl/UM2HOCfC1GKxHjzw9L7ZrPru4IkUaVH2sBtJXvFvjoxNtaUEVFXPPItPPaQyGZF1ylV/F7kXicgxq+H0abi4uVqqkuDXANE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTc2MzUxMzEyNDMsInByb2ZpbGVJZCI6IjhjYTdmYzU2NjE0YjQ4MmE5MWRmYmY4NTgwYmEyNzNkIiwicHJvZmlsZU5hbWUiOiJUaGVMaWdodFNoYWRvd18iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2FhZDcyNTJmMWY2ZThlYjU0YTY3Y2JiNTYyYmU5ZmI5YmZlMGM4OGY0OWY1ZDJhMTYwNzczN2YwZTg5NDc0YjkifX19=',
            'trail': '',
            'op': 'false',
            'speech': "I am the cloned son of the son of Krypton!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-8",
                "/haste 0-8",
                "/fly"
               
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
        )
