@plr = player()


@hero = associative_array(
            'name': '§cS§9u§ep§9e§9rm§can',
            'class': 'superman',
            'sig': 'n12HtxORVEoDI6+HUojhNLkvmU/XtC5V/P20SCOhynxgBgqi3xcHu5UY4touepldXZsU1L0SwLcUpDIAaV3EasdmK5onympPU4TDORS9J6j1BC4xivbBkZ9vD4q5f9h48C67b5nDtwUC/xcs4mVfVdaUtSWRzMlIywWQIiwj1TlXhb6C7qe5CRuaiMdGMIRL3xbL9MXM8w2mV3NBtDki8Tbxspj6pW9HhToWA6KW1E7n1HRxmUnf8svzaJ0NQDZ4WspQTyrf2pWDnCJ2CWK9DNH66VEfPtipxCnf4YiuS8JHKtBXOZMxAimyDOdV5RI9c9gMGbxcWCJxAmh3KL5qALL1ptsu2BfMY4cyI4TvB7pBMSzi+sgc9hbHCXYTmpFF8WYnvcDEpcdYmFD5KpD+WZjUbBUeRr/6PZGJB6oMbk1Pn3y3qCSbFzzrOoLMEAnlEOHYpolHymSLj6e0z7aCp8K0xW2PjisApyRVlEGMdeYAZsBtgRoXbpCXU6rS+sHGGkakClSd+TKegyaF5E3MJzdDbONAqBt6i+wcB012W941uqgSLwRQoKYeyfKPmRFaZwmMP1hqYSTevqGT3CJ5DkTHSd1CCCufC9RfpX7ou9VPrZ2oCNdreagn3H1d45NovMaknPqBUmAx//v3autSokR0IV/Z2tIe32ROX+4CH84=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NDcwNTQ1NjgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzYwMTNmMTkxZGM4ZjAwYzE2NDRhYjUzZmNmZWIzNWZiN2VmYmQ3MGEyMTRiYjljMWNjZjJlOTEzODlhMSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Time to save the world once again!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
