@plr = player()


@hero = associative_array(
            'name': '§4S§0u§8p§0er§1bo§0y§8(§1KalEl§8)',
            'class': 'superboykalel',
            'sig': 'Sfwmm5vdUAM8P3ab/OClhbSVdlGyh1uwQjhQLBZ0bNgOZrLnEyxuxaqKf5baX2MRI4yACJWTZVamL5Cf0hVBHRz9XHFnoSRe/T55mZtHWUVv4awGsPT+2aWp6DWzYfnWXvECOE2NWW/87yW73Qw5wmBNorZTXUrz/V4/2ahBIYbJrkE2lKXaqDZ5Rjz4I6+1jAxXofME3DYhHqo3rnoy9XE5DAC9Qu+gpgqXE4v5KfSRulXMUWv5K3YR+cAqd7pXr/Qei/N2Qtlkjagzh+qCVVWeIS6Kw6UIWyGHm7q/LnQF7QkqieJiVfE/01HSvyl6YVBX6oWyAv1WsdTZfDRI7K7fFiefYTHWDD81P5qqwT7BiKi79sFrxEkrrHFV2LSp6iPIdElLsAV21hvUeOwaCsSGM86x1+4MmQQZyCzoWcZSuW/EsnMX3sbxO7PayaNlV1rdXY4LwagYi/ewavoZDgJzD6NZlbVKXz7HobkZ2VFlb1wWqWsqRV2TpoU4LDJTfrmq061sp/dZO+Z9jaikkDgzB9bh/YO1lKRhMHFO2ShkixhFFpvUcRGgxzdghDXZKpFEMGfWXr876bLFMoss1sRWN2ZD8pEcAWQzazdkJCWkSM7RXIpG9jggZLUnvRvOy3cCKLPmeTwnJGFth7ELFznIaOYS4Vg16XvznfK5TOs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAzODc3OTM2NDMsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJCcjBrZW5TMHVscyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWQ0ZDg3ZWZmYzRmNjcyOTQzNjFlZTQyMTQyZWM4MTdkNGIyMjhjYTk2NTIxNGViMjFiYWM1NDlmYmZjOTIzIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Don't ever call me Superboy!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/fly",
                "/flyspeed"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
)
