@plr = player()


@hero = associative_array(
            'name': '§4S§0u§8p§0er§1bo§0y§8(ConnerK)',
            'class': 'superboyconnerkent',
            'sig': 'nfxiH7BJd6nkZwnalSdK6iUlAWXjiQaHhzHhNTrllxkmmJCre1fqDmhZgGE1czEMYrIFNFdOw7x+ZZwPCr549aaL2NHA55zJiaWZT2LiSX5qJMwJJg7MjR4EzqyyLjEPQGqRlXy7TSvSNF0WL2PslkhIA37lNU3JFgSZvwQBZN6UVju0MhcY7ginb5F37LRIGhfkPd16EkMDQMdzQ9iZTJK1ebk4WpmtK18CexhX92zWHQeIr51A/OSx2ziwf4GL8goKqLm8Xnee0j0OJ5TjlDRxKxkiW3DfQv1+GjZs8z3mW7qtohh5Omzxyy5sQd7NxMs1PfhOTL54PSz1cCB9V6tTVP7BFbsvzqBKzd0Z4+uxcHY1brQ3L/Kj+/HflcmeuW/jnXyGL3tCABAxevQ+Pu+PxItt1bMjcniC/mkw5v85WTGSEm8g7jALrQrT5fNdrX8k9wtUJVyhXN4yO2mFbQsowsKoxIh1RH28DKQaokCFYu6jG6s+wAo+kGx8SBYcSl2Kgl7UH6YbGfsCDMnvoZ+bXL7JfTgxNnpQeBOvQ8zhJUKzWN6SUaEO9hRv1SCsYCfUEhVXQ0fG8zaHQk1XKQE0sXvGXVU0NVv4rLyBkX3rQXTQABg7The1/A4cydBAUIes7etN1HauoSrLJPC8DEw3k4oDoOsuK6oSFq8nEws=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzU2OTUyMzMxNDcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzNhNjZhNGI2N2NmOTc1N2E4OGUxMmJmZjVmYWY1ZWY5NzQ1ZDlhNzdiOWVlZDA4MDM5NzU4YWM2M2ViIn19fQ==',
           'altskins': array(
                 array(  
                        'sig': 'mPkZcOoOfK0TcRM96JEBJ3YHcKSawVV7A5LcUVKOXGCOPqLg9VOEtXxYmipP16v0YAGrl0wlXggJRSh0NLK6WgH8oXEop+MNRPkkRfVCa9wsYUcm52JLrkHxN2Xl3EPi6U3el78s6p0T10/CLCDKAeJddPQA9R+tdowQbZI0LVwhb3ElYFnZWAP2fsM9G//TBeryFFad6AGIQXCSoAUv44Destb0J4EBbAs9sgV0kky6/JF+/aEyV9PLKeabcIUAqQrMOWw6TaG3ynTp9wTz/BBjeRcgfXsLDtztseCQTmjq0KpsPn0Kv5JGo1mXtS5GoAoaBfbuQdtOeVw1tbMec1LJtEkqfYc08q/YUE8Y6IcmdkZJuDMQGn++YxRu6bpxgzAnW/MRM03McJrItdDMLmMtiIqX95nxmktI0VD85R5aorGCiwaHFrlOpcZQdJl6TGr2XD5UNZLA9WA5Y/xPR6bsx9ZMqRSYMnwS/oAwYhJ/skGiNCxPaVTh41/ksKii2Ak7YLog6xjehNto0nQii12q2zHN4AuCNEf9vDCfoaF0X+OQOQFDHHiS8GAHRKkDJ1fGKbxkTHKE0uMk6jcT7MGpiCZKSbUbIPqJXP1qFOv5C9p1hyA9Um8YKRSRfmYKCw8KrNGgNNTe3fwcds1Ls8VrcTMDi2sjDRrZuKYwF/k=',                    
                        'val': 'eyJ0aW1lc3RhbXAiOjE0ODg1OTA4NzI0MTMsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJNaWxlc01vcmFsZXM4ODgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzJlNDliMmMwMjJhNmFjZjg3MGU3MzM3NmE1MTg5ZDIyZTU4ODcwZTNmYjcwM2Q0ZTg1YzhiY2RkNjQzNmQyM2QifX19'                
                 )
              ),                                       
            'trail': '',
            'op': 'false',
            'speech': "Call me Superboy. I'm not a sidekick.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
)
