@plr = player()


@hero = associative_array(
            'name': '§cS§9u§ep§9e§9rg§cirl',
            'class': 'supergirl',
            'sig': 'ccxWzGt+poCGs/lNieBUMytCK2cQz0PYAbXz4i/xxIH9VSm/KOyJlsnXQLaCqMNPUCvEnLZKfz8L3wgGgZi3MmgddiQ1+8CGzYPEdfpTaSCSO4cbkG5FEp7eh6RRXHLzh3RdebYr9CNyPsn+ROufUFwJmKeIOE9TA1eAnc7iRZ5c++yk6+lyq90kCbk0yW9O5kNKgdvOTmQw3i6WbncGx4vX8FMIiZJgB0KMGKEbcllcaxUumJLD43FZVlkYl3iAb0T87XsifpuLpGqcsnZrjT0Lz/jdEEq9pzF4LgFTcNMUOlMhaIv1DsCyHNe0Re5c2Oo+ryZqoZQE/vxQ6t9RziiO+cX9SDSp2MKZTV67T3XNDIEcMOO4TpevK4jAZxul1g5/2AnVBHEtDkw5WVqFrl/Hjas70cHhL2kJpej1CsSaSnbLTalc5hrMOIruHlmR0Qe5Vc413jlA5gTcW8S2s3VIFhZEoVOgfYEfkYF9KVBZR+iNRXtQV65EAhsTiY1FkjGASYQWDkB+UXbgcx+bdfELmkHGZh+/3Wb0MohXT2Z8UXxmauWPGAG6/MsH1obWcSjszV6nfYi/ijZzyzcKCtyLzBKmujC4nQlrRrQnwUv0QlFf0mJJMrKGVynG00V4AyUikwH46zG6yDy2QDtRowgsr1K8+r2YpWkXXBYfgKk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzIwNjU4Nzk2NDAsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iYWRiN2IzNWUyZWU3MGRhMDQwODA2OTNlZGE3YjY0Njc3YTg0NTQzZDZlZTcxMDgzMzEyMjE2YTNkNmViNjEifX19',
            'altskins': array(
            array(
            'sig':'IKx3KSwJBmT6ndVxzH5lRB8VGi7bsLCO01Rmg2RSpef2rt1oGy5B2rYuozw7PxAYnLRIxO1ii2jY17riTebZhxxJDlkmcVCuBorwa27ApmEudEuas+dJJvzhypc3Dg6kTVuywm8SfcGmUvwvh2YZp0LZJS2Gbb+a5Tb7zSM4J16csRtRSfL+3cWNRk8cuFkZl1RRQrue9qUwH8tuiUVZ/p2mvR3qUN1QMlGK6MgRlWqrqPwFd1GNVV85rZYWUA1dHM6MuJMLZkJv0TksPLmeXKrPMmWCsfv5UCB8HHPAbh+2BO5qLCpsEbkpn88AGNsB3Wf0Pia6lrYpseiB11B5bVhKepoTEiSoY2cvn98x2ukC4CgJv/ZwuFOYCofmnJbZxQX3sClDDS4sXJBZsp9+Bnpq7d3tznZJzqGFMeYB0ydjxvavB6KVUqz2Z5lUzjBqVHS2TqUb69ULkmSmq7XF93bmcWpo9gQeLT3XhzpDpm6OUGrEflPQPV21AQIxGDinOIofgNU9f8vBNB/5y56mcmE7eyzxQm/xHoJIvOyyLoeM7kWupfeB0uKoXEtbAz3X+A3OoVafLBfvLKaBTyc56ZWq8D65zyRNKBBUMwwDNknDbWChpnSqqf5xzJHS2yGU1BLjww+s0yWPaye5mV4OLu+kQGLNpBI2ze8bTWRZipk=',
            'val':'eyJ0aW1lc3RhbXAiOjE1MTMwMzcyNzA3MDAsInByb2ZpbGVJZCI6ImI4NzhmNDg0NDczYjQ0YjM4NzZhYTYyMGFjZWNjYzY3IiwicHJvZmlsZU5hbWUiOiJZbm5la19EYWVkIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjBiM2M3YzJiOGY5ODczZmUxZWQ1ZGEwZmZjMmMzOGFlY2RhMDdmMjNiZmQwZGMzODcxZjc3MDg3ZTY1NyJ9fX0='
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "Time to save the world once again!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/wallrun <on/off>",
                "Look Up+Jump+Crouch to perform a wallrun.",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
        )
