@plr = player()


@hero = associative_array(
            'name': '§cS§9u§ep§9erb§coy§8(§4Kal§9E§el§8)',
            'class': 'superboykalel',
            'sig': 'Ld9uF92ZZm4RNConcK0VKwst4BL7TWmoPOfRQE5uLXtNtv0noAvtTvrcmjNMcN9EkxjNkQhft45c2TKd7UmSN/AKEalF3XDea8cugXUogkga58B8BUEyaTCPbhjLeyCdE2900s9cdRMqlRR/NVeldMsgSnM2I9K51K0m6j+lXheh3vBX464P4XtJ8thOR2HdeDtFHuTar/GrxsjlWDkAvxS7OLpuBbMsQTTM9D0OiO+JNlDkR6fjutpqHFWAHbDr5eA0tYeb9Sn69pinKA+gDn++moYOcirwoS4MlE2+GdslXD0/yzp90R+pdK0DMItKlfx7rpJQM++oG6DBHZHe/uZg7+uWtZ6kuOk6LiwCCLzgvqFq4zY9g1x4bsAXzhlTlG36mbhqawCMZQ+dQW+zk6mWEHeNSWTh5OujRSdablUda2gfG/cFQzazFPIqF8OOO/uXuMV3DzxgRLgrJGcrdvuY9p2c0iPcJpxnoRsS8rVbL5eiSrONu401oldUnPVoT6HNY8DLfudq/tnqZAx0WIo9ZizY0mZ/jL1FHjylrVnM7FXeRCc9bRaw7Aqo2zO7DSNps2PqCO9ykGzTZmZ7ZvaMn3PYAGlTsA2N2SLwRRRbju2Zyatg3I3ha09R23Os+3ZyTU4MhHi91KfMIbhY9YIVgC1icVjgLUKO3ZW9Njo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAzOTI1MTE1NjMsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJCcjBrZW5TMHVscyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTgyYmIyYTVkODhmNzc0ODY0NTdiNjQ4ZmZlMzZhZWY1YjUzNDdkNTM1NWNjNGQzNmMxNDFiOGY5ZTlmZDJiIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Don't ever call me Superboy!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/fly",
                "/flyspeed",
                "/run 0-8",
                "/haste 0-8",
                "/jump 0-8"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"
            )
)
