@plr = player()


@hero = associative_array(
            'name': '§eSuperman Prime One Million',
            'class': 'supermanprimeonemillion',
            'sig': 'qdSI/BggbHIAvGerU4VxJL5sAY0ecv9tkO1bRP8CNTwGp17BXsYvKK8Hff5Kyiz/tav+H3ISoFJFt5LAtMsZtYP92ypAw/yia4Gu71Ug+I0Usz2bDny4l/pqP008lmYtdLZTaJNm5ZgOcdlO2xL/PHqoj6t7qG6ELL1HSQXPr8qmWlOOq4cVoaA0nU3ada9OBSRjrZZYpsDES1vh/6dyrV7A/DZlQBiQmGy3GX6sFgtHWYHyzUnjpjaukwFYHS/g9hyJ/KHug9AnIrgMoyBOtM4Jx2bxVSgZbi+IW//t6oG3O/8uCnPIxPP9ppeqrmJNASRxKcq3S1GqCsjsRr81i2DgAHt915JdCvsOxiqxG7GmWMMs4ppPwwV6zuwkN56TLIKusxE0zSOvAA+LXdcbkYB6okue/y7uTqkcxcNQ+uC0DwY1ikKWhbHnncw+Sax+23oyAHXtCch8TIuBTk7sHhfiGeW6Cn696lpPgLGnHSpg5rNey9aLKTw7M0CacedzwaMCJOySilfpiEuQyGRsKsOYFtYE0B557MNvvyWpJqH2nKVbtS35DY4nUxUAs+2NHD1pR5zfC2HMmXogrCm+G+uTRQNtRuyEJBFq2+KUNcMf3Agxi0GVR9EWzSyoAimlmQHKiIKUAKvb/xB8eKIYhoapb5OEuxGyAO5q9Xxxsh4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzQ1ODIyMDI2MzQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzAxMDM4YjYxNWRlZjBjMmVhOWNiZGQ3YzNjNTViYTMxOTJjOTZmNGVmNmY5MmNmNGRmZDA4MmZjMWEzY2EifX19',
            'trail': '',
            'op': 'false',
            'speech': "Welcome to MY Universe.",
            'powers': array(
                "/buff",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true"               
            )
        )
