@plr = player()


@hero = associative_array(
            'name': "§2Talia §8al §7Ghul",
            'class': 'taliaalghul',
            'sig': 'U3BcEyA3OaldfkSnODOnyIX7dTjgjmy5QeY+5R3iBvD1e5oiK77RC+rJDhik2X4eoXhIvS2NMfs1KjH+aX/4RwtCR84IUYrJ2QruToGstEdeYyELAZeMdrKQI0xTQuA7w2Mo74LmPZCTGfmmccLSZAfsmJiyy6sI6C6CUL6KNDM37ejKH0lymU5LU8fL80eFpZS4AQkSTHE6EQKZNKp664QWnm9ciTOn9Y2BVuI67aFgPWW3LactdvHtbWOgxkkr2+0rkRwvk01SDmTKaugEr/O1Zn0I2+h2TDgI3VvKbgrrgkRng0Vy/ITWphVgLpswB3WBsStFVJ0SgZOTQs1SN0qGhlA2xTJz/TPYYOXGcyeaa0Fs4jfq40AylNFq+kma9yyzRuqU6qOjUBWPK0DoH3N4QLAu2XufvY1rEUGeffaJm06HgPXfCGNhshmcf8xPVYzn65VXy2pvaWzu8bO5eIo9x+rcwHmx2TVORGsYxSEz7YtT5LFNTr6E45Z3WVIo6dmI9IyCH0F8tF0RPRFtUsXEJVP4Zn3NkYDSL5JZR+2BSSMG8cfig41J77P0+R7S4FaCsEUf2znpK5CYAV6g1IqPsYyHNByHF1Rq4sc48fp2M9LHzZMtbH7nA3G0A84GNG4Xbmvk5o3ctY1id335fwv3RG1JahUwcszXto0yZgU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTY0NzMyMzcwMTUsInByb2ZpbGVJZCI6ImU2ZGU4Y2YwYWY0NTQ0ZTQ4ODJmZDk4NDQ2ZjRiMzFiIiwicHJvZmlsZU5hbWUiOiJ4VGhxc2V5Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDYxZWRlYmYyOTk3M2Y5MTFjNWJiZjU2ODZkMzg4MmE3ZmNkMmExYWY4MjUwZjJmMmY1NDI5MjUxZTYifX19',
            'trail': '',
            'op': 'false',
            'speech': @plr.", I am the daughter of Ra's Al Ghul!",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2"
            ),
            'buffs': array(
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&2Talia's_&8Sword",
                "/give ". @plr ." minecraft:bow 1 49:1 name:&2Talia's_&8Bow",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." AK-47"
            )
)
