@plr = player()


@hero = associative_array(
            'name': '§7T§1a§8sk§7M§1a§8s§7t§1e§7r',
            'class': 'taskmaster',
            'sig': 'A/v+41l5cjgExm56xMc0lBL+c7ng0/eyizXmCUI0ZuH1MvLt62OZ4g4h2q4iuevUAzAWO8bKbzxeRxjJtecqAKjvKJ1B+Db+IDubt6g9DfBEoUXqmJ/1IQI2k5MVQsHtVe7EEhHIbkfEH975G33QgPNIqV9URv1eVkZtzRkMp9UiU+Y7AWU6zQ7ShSkFGJ4b8PEtXLlsI7OKPaErwC9hDcK8D6MGnxjDmsAEOYQf5htGlJ2szbdxoVFcouyHc028mwTZYqg6NL/LbHhk31segzM0fMSxosjPfDZnl6xfr7NF6jQZU0zDdb9KGUL23qSL1ASIiBqHdaWPkN0DygD7pFyDnkpTej5u2vasAijR2TpjGUEHKzxzPuYunkOt/fo7eVzJryqF1+KJeYEe2CXLZEfj81gKUHLkFDilW6Y2LV1j6cWGq0a44mSGDjNlrXqVwlQDWMqPyMVQ+mEx/L38CafmCKyuE36zxPSwQX5d6GMBHQtsUlAxB1NTEPZG/s4ZQb668T2gJOGgNyTkDgELJrs43hS9rnjgysXRLyJ7J5QP9rH09zdZMEvxCMqRE/8T4/t66FkFC53xSfoIzxfZZTQcgotXS16KcCG5BeK8VtRBSpzciNEENnLTSJcQJVRuFMr7EGcztLwB/CsANKw8MIdkGocGtYOlaX8OEvdsqYs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTkxNzk4MzYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzk0MTVmZWMxY2MxZWMzZTY1MTE3NWYyMGZjZWM1ZGE0Y2RmOWU2MjZkMzQyYTkzMmIzNWM3OGRhZTM3MjJhZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I know your moves, and I can do them.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 2 true",
                "/shot give ". @plr ." webshot",
                "/shot give ". @plr ." pistol",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&4D&0ea&4dP&0oo&4l's_Katana"
                "/give ". @plr ." minecraft:iron_bars 1 16:10 name:&eW&0o&elv&9er&eine's_Claws""/give ". @plr ." minecraft:shield 1 durability:3 mending:1 basecolor:14188339 HALF_HORIZONTAL:10040115 HALF_HORIZONTAL_MIRROR:10040115 CROSS:3361970 STRIPE_CENTER:3361970 STRIPE_MIDDLE:3361970 FLOWER:16777215 name:&4C&9apt&fain_&4A&9mer&4ica's_&9Shield"                
            )
        )
