@plr = player()


@hero = associative_array(
            'name': '§3T§1e§0m§3p§1e§0s§3t',
            'class': 'tempest',
            'sig': 'iaSWFib+49cbEb45XNUDr23SblKcHJKGj7MENvtByDxbJavyeH+5zSuweJBS37iUpf8smEgDYNnBMkEERg2sfDZBRGGJhzzVX+rv38a5yUd+d04I8J5BMiRLGK7Fb8LyTjnGDuffXzImOpjVXkmsdfpxRNhBWLlZH2cidVB47XXC4Hn/Unp8Fkqz4oDcdGIQnigDkPel/PVKrN7946Kil2CkGNkqv4ZzT4GyuLtDaDXF3K27UL+ROAMdH96mqPtu/LVtU9FILbHBTxlofOmvObId2nCraD4rbERF9Nc50NE3whliIgBXCe7ZzZ2OOcyWpSfSKPZ0LnUE0WV9Kp3m1/QoA/sTF58GQBJ4bBGXuRQhRAYZ2E6zZPTqB1wbcpm/w00hAypCB8TiVLkVA/oAuZm/L78w7ZqDwURj8xKDTjkKMHMlYOK//yVDQjVMwZHk7gu67AzROVzvzOlsh6jn6ZY7iK4h9SJVghiRSgnktevJc8dbL0UGAt97XqGzHD40n5Hzalg/otFTld4qJaeMr98JRKZJFNTp7y5Tbc+bnDdUtQnnyISJCjIdywlIQiMNQVeZooXRd/rLRleZGUuL2x3ewaqvOu0AOH66gcKVeDCKfZmpjg0G8m6aFM62OFBVjWOvvO20tORFkiFlJO/7YJIJcRA0VmSV+ZT/W/38kC0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTc4MTc1MjQ4NDksInByb2ZpbGVJZCI6IjhjYTdmYzU2NjE0YjQ4MmE5MWRmYmY4NTgwYmEyNzNkIiwicHJvZmlsZU5hbWUiOiJUaGVMaWdodFNoYWRvd18iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzE0NzNkNWNmODk3OWQyZmMzMDE4ZDA0YWYxYTI0ZDZkZWU5MzMzODRkOWQyZGY1OGM3MzI1ZjY3YzZiMWNhMSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am The Tempest!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-2",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 4 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." watershot",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&3T&1e&0m&3p&1e&0s&3t's_&bWater_Bound_Sword",
                "/give ". @plr ." minecraft:iron_sword 1 16:10 name:&3T&1e&0m&3p&1e&0s&3t's_&bWater_Bound_Sword"
            )
        )
