@plr = player()



@hero = associative_array(
            'name': '§8T§7er§7m§8i§7n§4a§8t§7o§8r(§4T§8-8§700§8)',
            'class': 'terminatort800',
            'sig': 'RbPU93ghdHejFbWCg1xG/zlNl7pEUwcuc6tlzvPpqteyg7y/ZFmuU2kYu2PgDn5cLZN20DvYiuBYqEfnjGtyycQK/anwC3f/YSgXnA/sfkZgLmIk+mYsRy/spa9WNMSelHUPhzuOedwdPuyMHOiGzestAeZ1de/sOHOvcB3/n8H5Hh6CcTf51rU9EWuDaZ+Q/SYgwiUsizDtGhT58iF9pBSpM9uzM+07dvHbPE26FYSfAsx7HqEIntDRI8066NT1X2ifJ7yHoghOv1ClsrHxXoCkeS9xsvVKCs0FCk+w2c0cQMLFvJvPtc30l00iEtxQgWRRALUGMrDyjr/4UkIHlrMV+QkE+n/3q/ovSfOsK8M7gZfhI26ARL3PKtXt1S4EETvrYJGcLy+MAC0q4VFBqnz8fBKGmwbY3RMynqd7PQLBP0+zqpcbLJ01GwLiKFJ/s0prec1tdjMAhN9xE7SbLE7VVb2/l1McfvJx9FitR+aETXTUEq0n81vr/aL1MC2i7EvzWCmqzraw16C4j7qEERN84rHCmRx2oLXFG4fTPn2ZwH2+uGqTnxDiQvjIcg1d/L1yyNj1+7gWivm/xGWaLSqYaQg3wzTW5HzSIiStd5J/EyrIPQawtx/FOkCTgbUJhj+MSTQMRzIAEAQGAtov4ioXNUWOCIDrEYwqyOWgpAw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIxNzI5NzUxGMjMsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJhZGFtYmFzaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjZmNzY0Zjg2YjUzNjVlMTcwYTJhNDhkMTYxYjVhNDdlODQ0NjRkM2ZkMTA0ZDViN2Y1ZmQ1M2U4ZGFjNzFlZCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Hasta La Vista, Baby.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-5"
                   ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 9 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." pistol",
                "/shot give ". @plr ." AK-47",
                "/shot give ". @plr ." Hunting",
                "/shot give ". @plr ." Olympia",
                "/shot give ". @plr ." Python",
                "/shot give ". @plr ." Gauss",
                "/shot give ". @plr ." Putty",
                "/shot give ". @plr ." Grenade",
                "/shot give ". @plr ." C4"                  
            )
        )
