@plr = player()


@hero = associative_array(
            'name': '§eT§8e§6r§8r§7a',
            'class': 'terra',
            'sig': 'Pg79Kjy3JYLPBbi8+wjqpm8XWw/hThhj7YfvDnCPGKhgKbbwYzUSRpVTEoEGRzkFMK9XPzurU/szfPOgBwScx56b3DxJ/pQSU6/LpQeQP2B9ZJ2rc3NGWxYbBy+/hcUGZCmROpoTVKPnQ/irtTQ7TY8GlvWU1a6WeRuSy6DjwI5Yx4YoccBPUpOJDnouW1GbRoFoWWNnHLBw7Z3pN/POLd4bP05rbSTByH/zPiXrJpedu4jMihVhAghQp+oNk2QylFcBOjZ+Nn0Klky054oE7RpB82GHjS58nPNwcUb2gqWmsluLq6p3XuGTl7IOSyYc+E/ojobPEgYLgZBaeOcjvlLi9G5PoRDW+phtVpLvi0ufTUl1KrFDXsfzEpWclAlHRQffMPeEJDUreWHzdGjSAvAC90VOFKQqhLlm5V253RDQkrYeA6r4Z4viQcoEEIgO7PoWMCVGSR+83t92plp+jhyuErEUaydsceerot4aAzrXB6PRkwFAXVVNQM8iGm9VwCFH/YI4AJtw6k1aFF1+olP0RyzriGHvoJUtWtMuWtzyF9UCAPjkN5L+LXBqyRPAoQaH91PYgopcukXn8WDIq0kj7woY76eRe3YLj6eHNa3jjzoY5MDgPELgL/JekIl1NExpNFmJ5Fd6NCKRyOCZR2PhQwOeTHFuH1Xabwdy8lc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzUyMDc5NDIyODUsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zNzIxZTM2ODExYTIwYzQ2OTMwYzJkYWUzYTE5YmM5NDdiNWExZDE1NmM4YjIzYzllZjFkZDFhYmNkN2UzNzUifX19',
            'trail': '',
            'op': 'false',
            'speech': "My name is Terra... And I have done horrible things.",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-1",
                "/haste 0-2",
                "/earth (launches an dirt shot)",
                "/fly (uses telekinetic powers to fly)",
                "/carryplayer <playername>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 5 9999 3 true"                
            )
        )
