@plr = player()


@hero = associative_array(
            'name': '§7Th§fe §7B§fe§ey§7o§en§fd§7er',
            'class': 'thebeyonder',
            'sig': 'oMF7G4P4+/J5+AKZyeo+jL13HdsqO6glsXsHTSaicfZ3w+2S+d44FxHNvR7gY+dvuKaMkXBRX7uqCVZQl2VLnIIVSVr96ZXQz6P2iODkK8NF0bvIoUp5ZKH6fI9Tf3q0YGtmtiY3DDnfkvlOojvtFdLcfPvpqp7rLHPNyXmvVMP5sfWoZpbAHcrztiJpXqwfU1zJU2fTFP+I4p9ChCbl4Co3Yg/LNn8NEQtNYa4sMSsHofRNaGITzRj4mi3+VMoE/rCGR7QKpkV0Zkql6QFykQoCRyRsdGyrKi8rjVZ8ET/X7Cjsdr/dbP0oDkyGq/HpqVyzR1CfAs6luGtCq5HorUDgsF7LmRB9Oykz2Zfk5InN9p5bVZ4+oVJ8AQBNhZUz8QKoeGZacpBq49ZaEscwsSrztEoAHlX9jBbdCr0xvF6F3pDvi8myFyMKaLc1rCsZCuSnl0rj5UMCA1kPdmXV1IqCubOQx/LY7XXbpvYyvCR3/7DwKuJPCaX7TVWildlLB1xyWZQF3oZHKoHmpQEObiqBWvFk5zoAgUK4d9KM9AxJzBAJG/tAM8dmOFIQqG+bt0JiE1zrg1MmPygHtl8NLTrdkyc/tG/MoLHuxCeWT6xSlw7h+LMaqwnnUn1xtDblQP0s5Y1V5QgOYxxBaeKNq1s0E70Id04w7kL3p8ygWf8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTE2NDc4NzM0NzYsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWRhZjQ0NTk0MGUxNDYxODExOGE2Nzk1NTZjOWFkOTNkODEyY2ExNTdjZTY3OTljYjE5ZGZhYTlhNmQ5YWEifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am one from beyond... you can call me The Beyonder!",
            'powers': array(
                "/buff",
                "/disguise",
                "/intangible",
                "/tangible",
                "/cast telekinesis",
                "/tp",
                "/cast acceleratetime",
                "/create <item>",
                "/mindcontrol <player>",
                "/fly",
                "/cast cosmicbolt",
                "/destroyworld <world>",
                "/depower <player>"
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 13 9999 1 true"
            )
)
