@plr = player()



@hero = associative_array(
            'name': '§1T§1h§1e §1D§1o§1c§1t§1o§1r',
            'class': 'thedoctor',
            'sig': 'swO/rhFZJD71LaUCf4RUcHdiDeopkff2mP/n+MZQuSFRrzy3XaqH7n85m+OTyIg+6KapHzOEb47pK1iIKO7nAaUEYGpF+MZmLZ7wrhjVC0gCcYe//on0Dgsm9K5qPBdI6+jVA6V8hQOUcnWmsOt8KZog3qglMVjEfd9PbYV8dVDuEwKPc+XptA1OGK/y4QyetGj2oUi417u81uFgk8VYy/p/kz/9bTqEzboRc5i82JkZj7xFoxASF9TuLWdIHZ7I3xG99+hsyewYXXWjW0Cl6RLeYOBglhypCw4MBjPB47Jqy5BQZgIG7kGo0afW8zoX+drAj6xRfkGKrvMqaAEvS0suN89P+XVjPN0ZzR0Y3sl6cJwqpIjLeFL6s8ri3T7V3Cl+fS1u2Y8k349HcB2UOw1gB5HdA6SGhY/LIEbWw43d6zjXYYgQQvmDy2Z7s8DzJSbHUJcd+rRiQu/ca4Ect+tDWkNtscGpXHM8HfbG4D1VqW1Hm5mrk3TSexKiqbe0DGh/hYA8tclUa9/Yx3CDsmeWDi1IqbT0HzRfIKwSsOu9VPWtWqRRjFd6iPb9zfoCK8p1BDy8mCDtV54xVhR4X1mQLgC8GIgAzwgOmaWR9iudXCl9wTHheIWScCa7WzJfKFveMGkvzFSnFBo9KQYwxE2rA+70zJ25N7XjHDYWD1c=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODA3NjYzMjE4MjksInByb2ZpbGVJZCI6ImUxN2Q4ZGU0OWZhODQ3NGFhNmMxNTRkMjhjOWE1NTkxIiwicHJvZmlsZU5hbWUiOiJuZXZzZmFtIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zYmVlNjdjNDE3ZDI3ZDY3NWFmNzY0ODRlOTI3ZWQ0OTlhMjQ3MDlhOTg2MDUwNDc4MzQxYThlNTM1MzEyNyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Run, you clever boy",
            'powers': array(
                "/buff",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/tp",
                "/speak <playername>",
                "/jump 0-2",
                "/run 0-4",
                "/confuse <player>",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 10 9999 40 true",
                "/effect ". @plr ." 16 9999 2 true",
                "/effect ". @plr ." 26 9999 4 true",
                "/give ". @plr ." redstone_torch 1 0 {display:{Name:"Sonic Screwdriver",Lore:["\"It doesn't do wood!\""]},AttributeModifiers:[{AttributeName:"generic.followRange",Name:"generic.followRange",Amount:16,Operation:0,UUIDMost:31999,UUIDLeast:340404},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Amount:10,Operation:0,UUIDMost:82864,UUIDLeast:467292}],HideFlags:6,Unbreakable:1}"                
            )
        )
