@plr = player()
 @hero = associative_array(
 'name': '§5The §4Doc§5tor§8(§f11th§8)',
             'class': 'theeleventhdoctor',
             'sig': 'RUggnhFknT3dRxoVybO43TaknV1MJf+HBK4T8VubjQq+Jj9Z+yoXa+1DB3WtO8LOG2aK0lsmSpL9Ui6eSt20VVGW7pWeD0//upD3h7SjwJj7fpm6Fo7njtBPKKJOClAfJCUIDRpOiYioMQpfsvSXE0M6sPMUspIvGWQ2JsLdRYOVyjBeTTTu+Ndcg0be3DwywZlM9C5Q2mOqCSsJypHlioWDZdStdcpOH9aSiQjWshsae2Zh5TppeRbknFPnjG8BtYV9xAKElxtY47fOfGO3Y2jtTLjCpN5I8Gyc089Rcd0wdsKba1owW8doLPfD9zsg6pG5IkIEaBkDqxu/k5u2J9/3ywhKzB8wk4JR8ctC/BWZiyGbpQzZbsylV7bVG5M+TjNNEraoCw3oVZJz6VbFJ7gUXDez+ktFDjdXyln14ILyb4Juni6BkAvpHsjionLQOPT77UrmSAPSCfsO+ckpCKqVfe00uLJJiRw4LyCyIpu7DdSDbu45DtOkuXa46FAPBeRsyZC88/sBncQgGARMB9GN+Q//3J+cFwVFIz3BBEtceRIWeJpmaYZdEF7/UkAA3vLXoJ55LFpkwkjNKYlhDWu3m/FgDcSWpoLPMXPzOPxJnyHl7QumVfWOziCffTMlz5NuSEDNNk45gJ4BqEAd8FRCkmAMjzzHPwQrBMh2cc8=',
             'val': 'eyJ0aW1lc3RhbXAiOjE1MTg1ODk1NDg3MzAsInByb2ZpbGVJZCI6ImM2Y2I0YjgxZjFlNzQ0NmRiOTY2ZTRlZDdiNDU5MDlkIiwicHJvZmlsZU5hbWUiOiJMb3JkT2ZHYWxsaWZyZXkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFlMTljYTJhYWE3MjZkYWUzMTI3MGQ5NzA3OTMzNWQzNWQ3ZjMzYmE0ZTY2NjM0MTNmMzI3N2Q5YjgyMzQifX19',
             'trail': '',
             'op': 'false',
             'speech': "Geronimo!",
             'powers': array(
                 "/buff",
                 "/mindcontrol <playername>",
                 "/stopmindcontrol",
                 "/confuse <playername>",
                 "/mindlock <playername>",
                 "/msg <playername> [message]",
                 "/herotransform",
                 "Right click with your sonic screwdriver to place it and open iron doors."
             ),
             'buffs': array(
                 "/give ". @plr. " minecraft:redstone_torch 1 name:§aS§7oni§6c Scr§0ewd§friv§6er",
                 "/mgive ". @plr ." timestone",
                 "/effect ". @plr ." 13 9999 1 true",
                 "/effect ". @plr ." 21 9999 4 true",
                 "/effect ". @plr . " 10 9999 2 true",
                 "/effect ". @plr ." 11 9999 2 true",
                 "/effect ". @plr ." 5 9999 2 true"
             ),
             'alts': array(
                 'thetwlefthdoctor'
             )
         )
