@plr = player()



@hero = associative_array(
            'name': '§7T§1h§7e §0Do§7ct§0or §8(§f1st§8)',
            'class': 'thefirstdoctor',
            'sig': 'BGS5SkNYgLumEuPowmYou+gsSFadLz+vHtAqI6S42M4XakDrtL0RHfBNBqcZ3IjwS5cyXzIwywl4bCpbZ2kbCzQPhTPZuj1YBowiCNLCTOGDeDIYDLWD0ZDo+P7VrUeQmzaMA2bpnvcrGixxFRutUVpHekfEJyg/Z36jPD2rboH7p/Ov4CvrYhZTcfN9qTJ8kwUoSJu7THErTKHNFldUnUou9znl/E6wUnUtWJA+lvdXNAYP1jBqfDeGG5kc7lggJkYQc5qevkYhpMtkVoo7BNMO0cxJJB2pUmXhHWw/BEK28OUACUFqdnZz9fwvRYSbaWYODGIOg9Tm+pBHdqEMcG+QF8u3UstTriD3hVf0r/HEKn/slPb3CWqroHEld9UoxVsgV0ICLIfZ2WmO+g5b8tyRqIZXLG0VWR+u3jg3KqYjV5t+VRDWp3YFtfaVzYpZpsGf71jC9K1MLRof2Q/uM1sFjRYnkwgLSY7Dix4ipgo8EUnRX5YCzsXr9IIFF+2X0nlr7Xr/VQDkmJ5Uk3yHulPeFi8zw8S4xM7SXDO31zfNvSnu2TZ5pUyFoh7UHSRzeIAJ9uXvMvYW8IHYvbfo1w5XAzYFfnV84wjGdozUCcZ5txe7K6Qb1YN0qEa69atUdTWeQs2z89+UBE2fNQ+p4v/NY1VsdJedl6JYsWX3XDk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTEwNTE0NDk1OTEsInByb2ZpbGVJZCI6ImM2Y2I0YjgxZjFlNzQ0NmRiOTY2ZTRlZDdiNDU5MDlkIiwicHJvZmlsZU5hbWUiOiJMb3JkT2ZHYWxsaWZyZXkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzEyODFlMDg2NTg5YWJiMjMwZGRhNzgxNjdiNGY4ZTQ5Nzk4MmYxN2Q4ZDJkMmVmMGRmZjE0YjgwYTIzMzVmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "One day I shall come back.",
            'powers': array(
                "/buff",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/confuse <playername>",
                "/mindlock <playername>",
                "/msg <playername> [message]",
                "You have access to all warps with your TARDIS"
            ),
            'buffs': array(
                "/give ".@plr." minecraft:cyan_dye 1 name:&1S&9ignet_&1R&9ing"
            )
        )
