@plr = player()



@hero = associative_array(
            'name': '§6The §7D§co§ec§7t§7§5o§6r§8(§f4th§8)',
            'class': 'thefourthdoctor',
            'sig': 'swO/rhFZJD71LaUCf4RUcHdiDeopkff2mP/n+MZQuSFRrzy3XaqH7n85m+OTyIg+6KapHzOEb47pK1iIKO7nAaUEYGpF+MZmLZ7wrhjVC0gCcYe//on0Dgsm9K5qPBdI6+jVA6V8hQOUcnWmsOt8KZog3qglMVjEfd9PbYV8dVDuEwKPc+XptA1OGK/y4QyetGj2oUi417u81uFgk8VYy/p/kz/9bTqEzboRc5i82JkZj7xFoxASF9TuLWdIHZ7I3xG99+hsyewYXXWjW0Cl6RLeYOBglhypCw4MBjPB47Jqy5BQZgIG7kGo0afW8zoX+drAj6xRfkGKrvMqaAEvS0suN89P+XVjPN0ZzR0Y3sl6cJwqpIjLeFL6s8ri3T7V3Cl+fS1u2Y8k349HcB2UOw1gB5HdA6SGhY/LIEbWw43d6zjXYYgQQvmDy2Z7s8DzJSbHUJcd+rRiQu/ca4Ect+tDWkNtscGpXHM8HfbG4D1VqW1Hm5mrk3TSexKiqbe0DGh/hYA8tclUa9/Yx3CDsmeWDi1IqbT0HzRfIKwSsOu9VPWtWqRRjFd6iPb9zfoCK8p1BDy8mCDtV54xVhR4X1mQLgC8GIgAzwgOmaWR9iudXCl9wTHheIWScCa7WzJfKFveMGkvzFSnFBo9KQYwxE2rA+70zJ25N7XjHDYWD1c=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODA3NjYzMjE4MjksInByb2ZpbGVJZCI6ImUxN2Q4ZGU0OWZhODQ3NGFhNmMxNTRkMjhjOWE1NTkxIiwicHJvZmlsZU5hbWUiOiJuZXZzZmFtIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zYmVlNjdjNDE3ZDI3ZDY3NWFmNzY0ODRlOTI3ZWQ0OTlhMjQ3MDlhOTg2MDUwNDc4MzQxYThlNTM1MzEyNyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Run, you clever boy",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/give ".@plr." minecraft:redstone_torch 1 name:&4S&7onic_&0S&7crewdr&8i&7ver"
            )
        )
