@plr = player()



@hero = associative_array(
            'name': '§6The §7D§co§ec§7t§7§5o§6r§8(§f4th§8)',
            'class': 'thefourthdoctor',
            'sig': 'oCXdQutbTLgkNl0FU4oKwdA7Q5ucMeT06yJKvr0U48AnfUWncWQq1SILoVYoEPqbt9SirKvzav0gA1K+wzo1P7rXqw9RsZKw1jkzY4UKXbxjUmZLQMlC8O03CREHXMsBmKzqCzmLr5Z1mvvZERC1sZO7ddjOU7ISxy+yExAqkI/bhJr0fKDYKPgL7870luFBUh7hk88w/I7cJQ5E1I4dVq8qBxxXVOIBmIKFvJ4YkOfTSYJAka7dLfWyIqO93Vw3fO6SksEItqSlGRbvxabOBXcZO7Q8zFo5mWfnocuhiBFOhKXhNvTUTqg8sqBoD/BSlG7Qzzfav2GolquZ2BG3jDRJaEGXIFk1TCpWH+AE8+WCrSwCWR/dlm/47Qh8kaTrqijcJFEW59y4p9uW9gtu3WJpfkMonkPdHZNhfe4j856nFCz4gVets5ezlUH/w7dC2cJBpoajDiQBL+25VKt2XCsipJsOZmi8/ZQ+cmdXvKF6aj16o/+oyPySxDgJKdXnz/oOeL4LEBDsbOWt1WjSPcHBMj5IRmy12avylV5/mUiER1PIQ/DzlWGdfP9rqDpgkEqda8BWrRa97KOT0ifF7tZRG5+o9BapUaXMs4hs+2vFOeTriyTRMKFk7v2KfzUSoYWW8NHA6xBeJy0wNCrhXGcPhbtpMd4IQw7VRM1tTqs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTEwMTY4ODI0NTAsInByb2ZpbGVJZCI6ImM2Y2I0YjgxZjFlNzQ0NmRiOTY2ZTRlZDdiNDU5MDlkIiwicHJvZmlsZU5hbWUiOiJMb3JkT2ZHYWxsaWZyZXkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2M4MWIyYTFjOTI2NjNlZGEwNDhjYWFkNjllYjUyNDI0OWJhYmNiNWZmZjJhZmIzMjhhMWRlZTBkMzk4NmRlYyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Would you like a jelly baby?",
            'powers': array(
                "/buff",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/confuse <playername>",
                "/mindlock <playername>",
                "/msg <playername> [message]",
                "You have access to all warps with your TARDIS"
            ),
            'buffs': array(
                "/give ".@plr." minecraft:redstone_torch 1 name:&4S&7onic_&0S&7crewdr&8i&7ver"
            )
        )
