@plr = player()



@hero = associative_array(
            'name': '§fThe §eHum§6an §cTor§4ch',
            'class': 'thehumantorch',
            'sig': 'MxlHmRdMhusNaLMUfbZW0Q96XV/jw804bTSxtLiIYMfbBo45miH7UE+gqRXP0x2sF0IBWEfSXifvdV6gmKTMftRc7wLmc1pNtPfAMotH0AKaDVSxnFI7Ea4KCysspCxkIpPBWRfDLyIQQ0MzA9ZlqGp3ClqRnSUiCWN02yr2uWhjYnYkHuJ6a7tAIK6UP0/KnqKmGnMfnU4StZqozoaCaJFJR0150Dlw5sBi8nwULHGL0e4pE8S/gC34qLZ6e0Kf7pfONev6PG5gpQOmZoqwp+3OCJ4+kcGbCPZ3lg0fR9CfRZk28i7dhnM2+9wT+FtrwjHCAQSRSTsRNIgVPdxIvRYIe9S282S4EcsX9WqctrlZ94kMD9evGUvzMXsclf7MazLgNqnO8MvQ0s6jyFMezsDIB+o4sFoEL/FzQr5HfyC4R3UbGGO0OAIOKFSAL/j1iZbPhE6yPeTsuEhbJ7tbCv6Vo2HPdSTMamSDRBngnswwpXS67cO9MzCpxPfYLE7C2AhTzBiT3onjQajEMu0XJGi4jPqJV5X1vs/c3YU/Oo/PYOl1DywInR6yde4xaZobGOyhejWDaQmcTyvETKNI3ZyCtcC6nt9J3SzzAcI41A9B8i9DR3LYAAjP6yMg51+XhJ5IzCH3VBOunKnAfXLi8ASKS923B0n9SEpr2qY9gF8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTk4MzY4OTksInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzg3OTlkZDZmNjI3YWVhMTVmNjMxNmRiYjdmZTBjYTQyODQzODM0NjVmODgxMWMxZDc4NWJlZGE5ZDY3N2FkIn19fQ==',
            'trail': 'pop',
            'op': 'false',
            'speech': "Burn baby, burn!",
            'powers': array(
                "/buff",
                "Can throw fireballs by punching with an empty hand",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-3",
                "/flame <playername>",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true"                
            )
        )
