@plr = player()




@hero = associative_array(
            'name': '§7The Invisible Boy',
            'class': 'theinvisibleboy',
            'sig': 'xhCiDibchX+2RbJ+jT5ybN2DroKQhe3OWhXMR0wlVI/agO0CwS/AUeoqnuL7KaG6ZO/AaepOrwh6qk5pJ4/u4M6KFE0DhAjxxxBPyMBpMmKc4k0dmdrgO0vYqo8ggNEJDYJYCB4nH3GzhaJBWjDWX9B2Se8+80qevqopX+6he/S77DkHKssZMfkQCaBWW6ws5upMcrdSjxb9U1mWa8JhfIsorwHZSU+EwsbTSwrpY8ZOs35Q8dZ/2Q46R/X1KipOygiFuCA/3713MqATw/uhw/Fd8PA7rLmirVGrnVyPT1YmCZSrpTKX1MwFxa/B6ZkY5nBCUvMkLb5zL6KIDPIyLY/c1IyaoDNO/X3L8hLFTzEOlzrCnxIS+mn4RHfCrqal5gCNoNBLVDuVnIHZMGL2z1sB8nhgvDx6qWhZGtptH2pPF/1zlTzj8OIjoQ1GXs52Yz9uubkAOw2fJjeGnve47PoFDtHz2fEENNlZpBoy0IxuWeRka5K3q/hwhYdUATJRQKxcUnBU+A/KzD7nTDuyf63RXF0Mtb+dQ2C5DkqfclzoColjATc+VOEFNt7XQkB5sSKtxsE0gf4UBt+MaclnS44Oyqb/1deyTLLHhCB5lcSqrpwm8PuO95mwpl1HCwo/dUAYOHpGGBPmP8iAbQzW25ZcCo8HSERzm8oEgc2DqNc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NDcyMDY5MzIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xZGNhNjA4MWQyMGY5ZWU2MmFhMDY0NWJkMTNlZmQzNWE2N2UzZWE0YzdiMGJlZGU1MzFiMjZmYWI0OTMyIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "You really can't see me.",
            'powers': array(
                "/buff",
                "/invis",
                "/vis"
            ),
            'buffs': array()
        )