@plr = player()


@hero = associative_array(
            'name': '§eThe §6L§ei§7v§9i§bn§6g §eT§9r§bi§9b§7u§ena§6l',
            'class': 'thelivingtribunal',
            'sig': 'IdM8sCwAl3xMNR1tr6VQW5X6Rx0Q7mGIQ5CDkmvqNPW8lvj95vihUtoELDl8aNS+49gyJ69q4g9XeE3g8f9uMAEyguvL1D2o69vC4DOD4J6zASr7cRzIB17vhWgXw1zzfQHdz3Cd3VLTsbv9yb+QTAZjUV3TSFu/naPg1k8mg/DoxDxxQkF6kPJLFWSz46NBXetX2f355AN7f0vBiZzc6lzB6i5i1J6poMWZUmTiGSHzyEj4iFHHcB641Z2qoMV0kQOyGqJd8MxDkX+W+bKJk8m4A5iFAS4YU72LSMl8+RweyCI36cZnMpAu0sUatiNExh0UA4PyZkU4E3OB+KuNkzEZBcUnrB6+dghUuHVQV+T6JCFgRNxF1tOYfWjvQSXykx3gaOtcrlhKvq2XZNMrUocVUbQA/3JYA2UM5Q9H9Jatj+5EYML8THzAT5Lhh5eRvns2P6ltASooHIE327KCd+/ftnBm30h60m44OKzv52f6dg8wkmkWqeuwJJmD+gN8/bhigVrR7Xskc6FjX1ykOe+k0i4t5ckZgZTs5UGyE/a1fpquCDsXHXJfBZLi7z1PBmTY4BqnlkZTKv2NIyTQsJGOIZKlCjeGZGEbEIrA4yW/ErTxMqR0X8mYb1oofYLCvhHNNMKvP2eGALxeJ+mqe6sbLbIvb2deAIBmf5uA4iQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTExMTcwNjY5NjQsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODUxMjcyNmY1NzNlZjQ0MTU4ZjgxZWQ4NmMzZTMwYjc4MmFjZDZhN2NkMTIyOWYyZTMyYTI4NzZiYjhjIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I am Equity, Necessity, and Vengeance!",
            'powers': array(
                "/buff",
                "/cast cosmicbolt",
                "/mindlock <player>",
                "/tp",
                "/destroyworld <world>",
                "/grow",
                "/normalform",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 4 true",
                "/effect ". @plr ." 12 9999 1 true" 
            )
)
