@plr = player()



@hero = associative_array(
            'name': '§7The §7Presence',
            'class': 'thepresence',
            'sig': 'tp6G0i5CDvycB0AoK5GBLNMuTPy2BMLOvaVtsaIxgiKhkg/wA4j8648nYd5WOkUINp5FHPUZLf5/VF3MVFnb4ZI0qI/SXFlGvy1MCChTGW86FqC2w1IwmB1TsaF1GX1eTKIF8AxUh9f00EzVXmMCDgmrvawnB1iaGETXPSrcV4LlM04n1o+YCdP9OTcZvjwu9q51yIsAohHBuPSSPjBU59uM2bEUGT5ZQX4izC81y/xxLPZexvLfWk2IWVstp6A62ZQq45R9iO5gk2k2BCOHw/HmSt7GenCRn21xOWgMoqOL1HpUlrj5TIDyiWB5nDFbgP1xwWPowOzz0aAoA7NJBRknbhi+iVyhOvQnXtY6vUzSFQhz+j+F1kJ9ytVl1DU3Y9wo/BL98PCOwBJOedK8qAPEjzqDa6hcI/8Qf/3soCdU3Sq01P9WIvuZC6dGneGzad2BuG0RYC7G745vQ4DiOQtX8t2ruVgRXdORfzt0wsTOUmg/feaOMTXjrPM4iLd+cTilKjIVf6CWu1nhN5c89YBhYveoLUNWj1UsguMZ0iGYtGRsic79iSl1vZYGyrlGUuPGsi3udqqzPP+TgLFycEAUaFg2Ok1SUmXSlNxoZKpKH8bIrKTeJKnraR4QKvkLN7vYlcjfB6IqoU6dkPynYiMUAb9mnfIHnFa0N79wo5U=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE3MjMxODY0MTYsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmQyYzYxMzc5MDEyZmI4MDVlNDQxZGM4ZDI2NjY3ODQ2MWM4MjcxY2E2MGEzM2QyNzI2ZjU4M2MwODJlOCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I hope you are capable of controlling these powers ".@plr.", you have Infinity in your hands",
            'powers': array(),
            'buffs': array()
        )
