@plr = player()


@hero = associative_array(
            'name': '§cT§6h§ee §eR§ca§6y§8(§cR§6T§8)',
            'class': 'theray',
            'sig': 'YahsZNrlaZi/ApcmBYQu79e/rUSpwibNcVyclsGDVio3+bCjH3ODWG8VgEp7J/BgkRNdsc86MSkkhuJa0CxUd+zmy8Y2eVZLba+KL1MsnC+kodPX7POE0ksTOhYL8pY3oO+7rFKQbtvFEmyZSIh6KC4mr30gIgoSGw3Pi/u4QM3wtNaSWIC7a3ryL9skLcgVAnLZ50hPxMO2vyWm3VjR19KERMOkhFLveyKsOgsKa+vkH60yLJIH3cO3ndsSFq8Dg/bAy1usEX1q+ZO6Af9D4B2ThH1YMcLg0BwPTomQHMri9GXrgcKLUsy99/kInfPHCn3z5GjHSu/fC+cZba68A0FSNDmZwCXiinQGa2UMGJyYAHOMMUKI3SUWDZOgbBnf+fpFd7DgdGfPdfdfzEuadJu1jVzc8livYzNaz1ZDEJETiw70fv3oGCA+l/ac+Gu04XGCa7KpyOxbjtTqp4jhFsvYLth3LHYAECeRSHYwZl4czcdplftjHomXigz/J9LLB7lfRIcztSZ3DkW1lMcvMSnCxwHvNZxqv5dg1X2rZYgEuCLFRF5p+FpnzIoQR6PL58c/NT9aHeVcz3rgr1B6DmhW/4HZp2jIWVEzf52fv+SEp4WUwpKnIe0HCkWNoH4DqpzIyOFbaQEeFk5vkLxO2Puc1HYfo/VFqmcuwyx+v18=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDY3MjMxODA0MjgsInByb2ZpbGVJZCI6IjVkYTI2MDkyYzgwNzRjOWI4ZDA4OTUyM2Y3NGRkYzk3IiwicHJvZmlsZU5hbWUiOiJVbmNsZU1hc3R5Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xZWM2NWEzOTQ4MTBjNzdlOTRkNDViNDI3YmU3MWNkMmI0YjVhMDNmODM5ZTY3YWNmZWU3MTBiNGY3Mjk3YzRlIn19fQ==',
            'trail': 'flame',
            'op': 'false',
            'speech': "Its time to come out into the light...",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-9",
                "/haste 0-5",
                "/flyspeed <number>",
                "/fly",
                "/transmute <number>",
                "/thru (phases through objects)",
                "Shoots nuclear blasts with bare hand",
                "/invis",
                "/vis",
                "/intangible",
                "/tangible",
		"/cast lightray",
                "Shoots Light Ray At People!"
            ),
            'buffs': array(
                "/effect ". @plr ." 12 9999 3 true",
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 10 9999 4 true"
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts", 
                "/give ". @plr ." minecraft:gold_helmet 1 0:6 1:6 3:3 4:2 name:&cT&6h&ee &eR&ca&6y&c'&es &7Helmet",				
            )
)
