@plr = player()
   @hero = associative_array(
   'name': '§0T§fh§0e §8D§6o§8c§6t§8o§6r§8(§f2nd§8)',
               'class': 'theseconddoctor',
               'sig': 'jJ58sBvC1byTuCcUCLn12vFsWNbeT3p9Enl2nJ2qMFMJStbUTx1tZA94exJNXABvndC/Ir9JC07VtgBXtyB5jL0gT/MFa4ewX/NwpnEETSFSrq/KpbDymkW1wsF/XSORrS3l6eWmP22lgrgjpnDyhi3wPZVU9yLOT5wck+jimOiZu8W+wJqVXNLMam+0fjJw+gdAtyeNJpg47s8L9tNfLPlhVqymcEcCnH2hlsE3QbiOD1Bn8c6RYfm7YalTqLF8Qi8ywxUtmA6oR9x62RYEDouZrbDgpqOZEb7D6tnwseFhyBbFfBz9AT2a/bsbyHTCS/d+dKUyrTg2TcDx10vs6QPiRT76jMuro8JeH2lGNrqkfiUfEONZN/NqIwNAs5wSPAIKP1BoN8Bvh/E98RkSiBKwYeDaYPjZk5mDajxjswPUrgmeRKKU66p/7CWoYM9h/Rl4dNeLhhiNqGtmyAQU8y8+f3vsD6KmtMqaLogU7BQfSNdkZcqdQQUYPPd8SdvqfmeDPafI4XoF8KffOU98TtrT8HoQK5///W5p2AqCRjTc+aACH+j0FntienyNXQEpYTv0QqGHV312cy6zLDayLDbNgAnBcxZOp66nF7qzr1tjDG7/aqLcVfGzZQMgUrYaCh2i/LpPSrhZAA67KUi1wcSiKkUs4OONHboZG3h57po=',
               'val': 'eyJ0aW1lc3RhbXAiOjE1MTg2NTg2MzM5MTAsInByb2ZpbGVJZCI6ImM2Y2I0YjgxZjFlNzQ0NmRiOTY2ZTRlZDdiNDU5MDlkIiwicHJvZmlsZU5hbWUiOiJMb3JkT2ZHYWxsaWZyZXkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzNhZjE5YmNmMGU4NGM1ZWU3NzFhZmJjMzViZDc0MWNhODk0MTFkYjhmZTRkODlkMzAyYTg1NjI3NjRkYzIzNiJ9fX0=',
               'trail': '',
               'op': 'false',
               'speech': "Oh, my giddy aunt!",
               'powers': array(
                   "/buff",
                   "/mindcontrol <playername>",
                   "/stopmindcontrol",
                   "/confuse <playername>",
                   "/mindlock <playername>",
                   "/msg <playername> [message]",
                   "/herotransform",
                   "Right click with your sonic screwdriver to place it and open iron doors."
               ),
               'buffs': array(
                   "/give ". @plr. " minecraft:redstone_torch 1 name:§eSo§7nic Screwdriver",
                   "/mgive ". @plr ." timestone",
                   "/effect ". @plr ." 13 9999 1 true",
                   "/effect ". @plr ." 21 9999 4 true",
                   "/effect ". @plr . " 10 9999 2 true",
                   "/effect ". @plr ." 11 9999 2 true",
                   "/effect ". @plr ." 5 9999 2 true"
               ),
               'alts': array(
                   'thethirddoctor'
               )
           )
