@plr = player()
    @hero = associative_array(
    'name': '§2The Doc§0tor§8(§f3rd§8)',
                'class': 'thethirddoctor',
                'sig': 'E0xwA1q5QjvbQ9Ji2tassmdhk8j/lEGjU5ZFm0CHbmMCNPSIki/9TiEjNwyDtYnLji9zqIUPWbuFnRhyQ3an/ahz8hjEHGo/3ilWi3mC9SlQ75D7JOZBfTxcsY1hgN6T4Be2GM4nI6Q8MmpFNyDQ9DV+NBAB4ifhGrEQWbU6pz+ifhwdTa8dXeyrtw7MB4/Qunzg/QIP5RkiCrHrHXGeafHELUQtRDvJkGKv3dSBj+ASF4rcz139jBaEZBIxUJbnORP1eiLl5PzhY0HywOCBbjlKQcyF3YMl0lNMwz4blhcjpcWbBsS635bBU6R1Xx/msrE5ycMLGULvyQt/vgscsi53U4xzQwlEWqDN0QdECdvrF13gX/IlZWtgtUFxHmTWavxBhPOaIlhIxjzZr+VPRLKZ33QA50EgKD8aKWERrTOuz+Q0YmYrRCG9GcseBZc796JZ9BR6ihTMqsbqCiY1U3I6oBXY8hxQae1uTZeXB6mD+Y2h7vrSV0ARqAE5b2cSjV11bM40HiDFWk4eserHiTgtq8AA30R10hQUfl15MLLSS7xElJDru+GPYijs8XdXjuHUYEKUE03GxyhOswvVsa+XgAjaUOoGlTZbuN0HX/V4x5ZLrv7D+waniXPReBgD7DkCop4lOXiQWsRyPrQqeyc2AlGRnoxfu5AtSU8huxc=',
                'val': 'eyJ0aW1lc3RhbXAiOjE1MTg2NTg2MzM5MTAsInByb2ZpbGVJZCI6ImM2Y2I0YjgxZjFlNzQ0NmRiOTY2ZTRlZDdiNDU5MDlkIiwicHJvZmlsZU5hbWUiOiJMb3JkT2ZHYWxsaWZyZXkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzNhZjE5YmNmMGU4NGM1ZWU3NzFhZmJjMzViZDc0MWNhODk0MTFkYjhmZTRkODlkMzAyYTg1NjI3NjRkYzIzNiJ9fX0=',
                'trail': '',
                'op': 'false',
                'speech': "Reverse the polarity of the neutron flow!",
                'powers': array(
                    "/buff",
                    "/mindcontrol <playername>",
                    "/stopmindcontrol",
                    "/confuse <playername>",
                    "/mindlock <playername>",
                    "/msg <playername> [message]",
                    "/herotransform",
                    "Right click with your sonic screwdriver to place it and open iron doors."
                ),
                'buffs': array(
                    "/give ". @plr. " minecraft:redstone_torch 1 name:&4S&7o&4n&7ic &eS&0c&er&0e&ew&7dri&0ve&7r",
                    "/mgive ". @plr ." timestone",
                    "/effect ". @plr ." 13 9999 1 true",
                    "/effect ". @plr ." 21 9999 4 true",
                    "/effect ". @plr . " 10 9999 2 true",
                    "/effect ". @plr ." 11 9999 2 true",
                    "/effect ". @plr ." 5 9999 2 true"
                ),
                'alts': array(
                    'thefourthdoctor'
                )
            )
