@plr = player()
@hero = associative_array(
'name': '§9The Doct§4o§fr§7(§f10th§7)',
            'class': 'thetenthdoctor',
            'sig': 'x5unnANM81LFVb/bXy5+bfnCG2URDuN5b7iWGg3oZYiajadrVhErmlLCVDPjQSJ+gQT7qepu/oc/1pDefVb11XVfVfxmatxWonP6KB6gB3PQpupNtSPvK4SL3Q+7NkCkyeG05/DARAFJ/ZCFxxf8yXk22CUuDc6fKW2btFWwQ9qFi2FVN1OmtUxPudkb0gz9ij8ZGGtQmjc05Pb0mLfuaitjwhjHYMcrQL3r9olq8teI4qYnCPknaZfxJKVG6E9x6ihrhaFWrufsy9xm+a5m3enKB6XPfIC5Ztdh5zUfvrfQ7at3vMKg2TYqz1PhHlGZwoPullOQRw9HQn19Df0TpY2cRrbZofwSazC0+DwIDwTXtuK88qPBv78x5n8ZHvMAy/6mHc0zitcSSIlNhjSX+pNYap53KEd5LFCJthr7WCqIdZD0jLmdaJGZ1b7gQK3skcbhASoMHze0tPtU0Fvgr7I65+INqQr8ZMIh4HED/n0OH560fnEkljDh16zf5G/b5YhL5/lHLDrLqEFr3GlHM1wru8UN1COnZtROSDPwvCUqz83IKldAfPU60k42D2YXF3mfyEpCwiQOc8o+R/2NY0m1mzm6NjrjW2wN1hrSTdNYpBOZBFhvX2l5mazTkRorKfaN/fEebUR4H+PNHhV8+zHFO5qHrirKgDb+wiN12OM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTg1MDc2NDUyNTksInByb2ZpbGVJZCI6ImM2Y2I0YjgxZjFlNzQ0NmRiOTY2ZTRlZDdiNDU5MDlkIiwicHJvZmlsZU5hbWUiOiJMb3JkT2ZHYWxsaWZyZXkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2UzY2MyOTIxNTE4YWE2ZTY3YTIwZjYyMmE4MmNkMzg3ZTU3NWVjYTgyMmJlNTlhYjI0MTdmZGFmODk4MzQxNyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Allons-y!",
            'powers': array(
                "/buff",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/confuse <playername>",
                "/mindlock <playername>",
                "/msg <playername> [message]",
                "/herotransform",
                "Right click with your sonic screwdriver to place it and open iron doors."
            ),
            'buffs': array(
                "/give ". @plr. " minecraft:redstone_torch 1 name:§1So§7nic Screwdriv§0er",
                "/mgive ". @plr ." timestone",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr . " 10 9999 2 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 5 9999 2 true"
            ),
            'alts': array(
                'theeleventhdoctor'
            )
        )
