@plr = player()
  @hero = associative_array(
  'name': '§8T§fh§8e §4D§8o§4c§0tor§8(§f12th§8)',
              'class': 'thetwelfthdoctor',
              'sig': 'ZY/zE9nQVwVMZ5IZqnkfNxS2vOKHSAb23OvbgoaKd1fBhEMB7sDIY3HWgFJ/hFpwCvyvi0u5h50e9HNqf3JuLAexPqsDXMMu8E83vpGyRhOFaGAY/5mZIgLGkkLOTyLUrMe/Z0ErZtxh3T4OR1inmqE8QaysJw6WwR5u4bg5kNDtQw876KgHr6cHEMuSeHEsIWN4LI60WBV2q74eyPAhUpqd2+HoWy6mh0kY9Dh5nrr+haIt9bCz9DPrAzCQRGFAFYOCdKRej2IzDt5BjCNsE4r5F9lN76YenxD5um8A+3FaR/c8D2GCnfQ/DiYHlY0ao++IFAxjonWRiWm29KUg/813Ah4xqXUHPEo7n05jUa7Xu/5IuGDGToq8gN0kIJ6NtnpHvUFb4rzUeIyWQATxAsrA1iK6VUjJgfAd73irWvRHa1MiewEgRO43aVTTtaNSbleKApT8fy0HfqgZYyZLit5m80QXMxcd1O5f9qM/JGIG9uDJjizUdNm0UEXH4W3FSV4GZgPu+MvuhOpiqGMObwsoysXSbRwRHUylliLUkhhTwn8hDUBxH6PsAMcTNdj2quXuGAY+bju8hOHhMPM+C1Sn3LStx4eOW17+XFF01KKL3SE1GgO7zQUU0HM9b+qlMcpMCJtF8/fG6txt8u+voeS6D2gtoDEWbtHhF4a3mdo=',
              'val': 'eyJ0aW1lc3RhbXAiOjE1MTg2NTg2MzM5MTAsInByb2ZpbGVJZCI6ImM2Y2I0YjgxZjFlNzQ0NmRiOTY2ZTRlZDdiNDU5MDlkIiwicHJvZmlsZU5hbWUiOiJMb3JkT2ZHYWxsaWZyZXkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzNhZjE5YmNmMGU4NGM1ZWU3NzFhZmJjMzViZDc0MWNhODk0MTFkYjhmZTRkODlkMzAyYTg1NjI3NjRkYzIzNiJ9fX0=',
              'trail': '',
              'op': 'false',
              'speech': "Shut up!",
              'powers': array(
                  "/buff",
                  "/mindcontrol <playername>",
                  "/stopmindcontrol",
                  "/confuse <playername>",
                  "/mindlock <playername>",
                  "/msg <playername> [message]",
                  "/herotransform",
                  "Right click with your sonic screwdriver to place it and open iron doors."
              ),
              'buffs': array(
                  "/give ". @plr. " minecraft:redstone_torch 1 name:§9So§7ni§9c Scre§6wd§7river",
                  "/mgive ". @plr ." timestone",
                  "/effect ". @plr ." 13 9999 1 true",
                  "/effect ". @plr ." 21 9999 4 true",
                  "/effect ". @plr . " 10 9999 2 true",
                  "/effect ". @plr ." 11 9999 2 true",
                  "/effect ". @plr ." 5 9999 2 true"
              ),
              'alts': array(
                  'thethirteenthdoctor'
              )
          )
