@plr = player()


@hero = associative_array(
            'name': '§6T§eh§1i§fn§6g',
            'class': 'thing',
            'sig': 'm7iZ6Src5FHzH/g3ikaNc1+O9XJFA9ky9emr0a1ajEsB7MDC45/QaZcCsAT5iNqQ80TdLXTUYGQZ1jfRNBNLiFgWtjvJ4f/zXQDi6I8SFOR9rJ3MPm1svC0y6xa5pWFjSfgVxGq3f4rfke4g8F2xpoueIUnz3i8a2vGFbkOq8P1iSmmdxXPgfXJAm/xGunD/5iN6R0PJej2mX1iy24kdHx5vU630UeEXskJjIA7Y8m6ghNYmK/MGo1VrgcbM8t8UaJ16SKSN2PLDQUOVb6Cbglw259XmjnSyGl33D4u7dn44eHaqP0gSrjK8ZgdR0jVZ7Whk8Agp0Y8V/iz7bJrLVX5V7qe0p+QprVWoYbPcsLsfZEYBUaTvFLL5MPu6EDor3V6//kv+a63OKDf5DVyPmJNX2sB+f5XgJF2uYqSmgB7NRJEwgggowsHJNXYoFGLZiEEftA+e3x/wsZhPtAIsoQi6+yiGNJzM/ttIMYN1HXltfv4OPpa6CeZ/C63qp77Ospf2Lu5dBXlSEfAy3rowepqeo2HdNEFHOIqpCvjKtqV/lwo5aGHfphw3eXp1VAixWIBDBhkyiKo9mohdW8gSwWqk4El2TnhjDYxd1rUF2jCqdqIZWWECcGX6O7cVuSfBRm4S76Q13Xg0HEOb+XEFujCzJ77DUppMBztkLNOtWGk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTE1NDk4MTk0NDgsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmZkZmI0ODRjMTVhODdlOTU4NzQ3NzMwYTQzN2JlZWE2NjM2NGE4NmE4ZmUzN2UxYmRkNGQ2NmMxZThjZCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "It's Clobbering time!",
            'powers': array(
                "/buff",
                "/run 0-2",
                "/jump 0-1",
                "/cast groundpound"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 11 9999 1 true"
                
            )
        )
