@plr = player()


@hero = associative_array(
            'name': '§eT§4h§9o§fr',
            'class': 'thor',
            'sig': 'cVlGgL9zjSgmXeS+2S+Y4KS7R88XBb+nwjDZrxDLUEyM/BbJGrvpwml+VTr8UVJ7VQ9pC8hbRZ/XrYnj0Dge7SmvTup3TsvN7wTqMIYBF6TbFrt9JYEhjQgiOLUUjYK2JZfa4hnnZEz/8EAHXz1tpcwRdHNoQxpwe4AF+XS6hW/TmMjav1YPBvLSdU1Apouh7RzBrYokFAylysXExfmuBVVJanOAnVXNm0uOPkPE6/xHqe6NAoAADgQXoBl7bWUOuVBSSiFixJH0gJZeDERkKIGLmGOYzZeOn5doGj+t3frlKjZhcyqJ5CYDcG289L8HxU2OciFIFI20sSs6KFwqj8DHj76/Sq/9FixBNITmeJ7Tsd0JmbOPgPAdAWqwN+1WK1I3ImiexZp1xPn19L12eOMdE2RZLAkOeAFemKMSdCZnHQnW6yyOk5bH9uhkgYsFFB5rPKPUUl2Oprj9Dlit1FUuBqgL/Z7cW+LjPG2itYUnTp5+mZJtmiixoVKXG5ll7N+zXpY4n7AWzZzlki/yN20sbFgiFuW0oanO+R00B1UOjfjA9+osxUgAC0fU2khrAA3yLik785IzhUq9xaW0922vKviETwmVUAiBzjo0JM0Mh6REm/XM76th9hLaZfRvvKa8ahPF0yuXJwUMsBl5vRaVsaEIVrZwC/lunBOjHPI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3MzA0MTA1NzYsInByb2ZpbGVJZCI6ImZjNzE1MzI5NDI1YzQ1NDg5NzExY2MzMjAxMmY5YzhiIiwicHJvZmlsZU5hbWUiOiJUaG9yIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mOWU1OTk4NTliYjBiYWNhMmU2MTYwZjA1OWJlNDExNTNmMzBjMGZhMzVlNGFkY2E0MmQ2YzNjNGMxNGJmYzcifX19',
            'trail': '',
            'op': 'false',
            'speech': "The God of Thunder has arrived!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-8",
                "/haste 0-9",
                "/fly speed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." godblast",
                "/give ". @plr ." minecraft:iron_axe 1 20:2 16:150 name:&eT&4h&9o&fr's_&7Hammer",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
