@plr = player()


@hero = associative_array(
            'name': '§8T§7h§8o§7r§8(§7JF§8)',
            'class': 'thorjanefoster',
            'sig': 'VV1IWq/H6sP1GN/2g5NAbK87sLuMpYcTCh7YdaQNQbmiZANucbTpLLaD9ui1LngRjG2zuC9FemOLdUEYzYFMHNjsPgAPHEXk7OgZgVC2hOOhLwl+/HbEaGAVKftQ71JSBTdU0GbK0kRE2lqoS5hATz3fFGBbAXraZzojWXzUmKgz1zTEXhIMb6F3NMSK/lMhdD4UKXE+h6wnWAhqRc2TTF1vn5AetrWgAvZomGPQMxZwS130yp4q8BCGI6zMCeN4VezZF9EAlrMY9pE8e5vx7Qnm5OAHo/2hqiz+76yLXfdsWrX1ZfImqqsJKShPnltqHYsYevCQuiCAci3CS/Gtwn22cDc3KZne+S4aZo5h3rUpY34XnUgP4av7yHqfpHhO7VHQn+J9YdddcPXnan4cP3ubsfhebVBT+UXtASkovWLoPFupjYWBD4xu5UImJPOO57Cz2q3dVlsgQ0m4cToJmqrJARBryVAhd+vo3WWtsAkX+K8HXegesNDpLNs+9MfqiovwgdZAEBU1Siqficv6mUd7TQ0ywfY1jaFdTgZ/2BP9O9lLeYmZKY8qD6VGtD7Aij1rique2KnyOfOeJlRLLjO5gqqIhL+MvFOOYeF0F0Gops6CD3EVWw4HelEYXZTMQgPLqDP3Vg4hU84JPxoAcIo5MzXC7WmyRWfSH4fKNW0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDcyNzIyOTM1NzcsInByb2ZpbGVJZCI6ImE4ZTE1OWVhZGVlYjRmNzNhMjQ2NTkxYjU4OWFkY2Y0IiwicHJvZmlsZU5hbWUiOiJNckZsYW1lWVQiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80YzNhZjYyM2FmZDMyYjJjNDI2YWQyMzkxZWVlODk0NWNmMDI0NzhlOTJkNjRiOWJkNWQ0YzUxODY5NyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "The Female God of Thunder has arrived!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-8",
                "/haste 0-9",
                "/lightning",
                "/wallrun <on/off>",
                "Look Up+Jump+Crouch to perform a wallrun.",
                "/fly speed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." godblast",
                "/give ". @plr ." minecraft:iron_axe 1 20:2 16:150 name:&8T&7h&8o&7r's_&7Hammer",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
        )
