@plr = player()


@hero = associative_array(

            'name': '§2T§fi§dk§ci',
            'class': 'tiki',
            'sig': 'XBkoDci2zEbhtQjO7lawuPea9HtGcFw3FUoKvFQlVu2kXXT/WFYwRYPeZNz2o9X1iz5JUN3ol4b0+5xO/1aJlDxDskPVOmeEHdbzc7LcwteqSMsFzgfbAsfGwwZtxg2XmZp9SDFyuwpQQnOz96HBS0EiPmkKCJ0rBNUGOosU3xKaijuUqkV0YriqMMESf78h2lWWlrGNtx71fck7klxIzbhKLPWfjTh4iBbrK6ZqR8Vw41rNPHg2O5xrnJXk81QqpuytPr7nl2YpYytvOHgez8JYemhLdYaFF7kfipKdsGtrlmQ5rWQuAAcktSeBa9thvOF5RX+8DAi2BgZlnbEiylZoiYYZMSG9usHXVneyfRuiDWIsda0yEVjCDdwsvZG3v/OHb1mIpmhoyXj/ZDeujyVFpDpSrCOLYdESealilKwIA+xuvtejgooEVRJwC3DkQlqJ1HAz1lCPM2w3Ny95HKlSQTWulyR4LX0rVT8M5KPfLTTVvx9olPlRnVr6yomk3PdWu3pqdizZqdzem4/xhfq/hkw072KdsVZoAx0kukHUoEy3DikTaGcRUwlcOZbZIk2NdnPwHxBY9llLTius4bobW4VVUdKQGGEThTmW6k7coDEJOKX5rLIRIHI/JgLRGrkjpSqkJuZ69+MP5hwd6qpwhZcOLtnNESnH5eFyf8k=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk2OTQ5MTQ2NjQsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJCcjBrZW5TMHVscyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2EwZTdhMmM1ZjRiM2RmNTg5MzkxZDI5MTRmNzJmNWMyOGMyMWRhMzRiODk3NTBiNGE2ZjFhN2EwOTNjZWZmYyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "So far away, beyond my reach... I wonder if they ever look down at me.",
            'powers': array(
                "/buff",
                "/run 0-3",
                "/disguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 11 9999 1 true"
            )
)
