@plr = player()



@hero = associative_array(
            'name': '§8Time §0Wraith',
            'class': 'timewraith',
            'sig': 'qP2HimAetM528CpTLLseIB6TaP4pG/Pe8DI/F8PWqx6WGl5Lzsbu/WGmS7GjZ+fSrX/+p2I1wxxr2nchhTTmwatfK22RVdyS5vBwCnKouvq61VbmyAny5Gop1LnnpcHTV/5z3kCaX/o+Ez7uRLXfEafP7m6nSzEO3w9MmUNVRZAEtInnVL+pHysPlPOThsEyObUcWKKE5QW3QnKs8b1DiimbkIqhEuejRszamzgJv3jiWmtXYP91m6xjzohxehSfq5EuIQ+2ooSA9cxeZp8lPo3K6uhrBs0z9ui6EMgrj+NfttUDjKFwfumjFX91/qcTwx/VfOxwbaAg7bg/kMNcRRk3CfSJAaja0NMcGXBhnl8SFPvcul43tV1NAkD7TdejIH19K5SI+vzoXdHIWIGIAZpqY1Lk+bjypR/klgdpWOOcYbddGLvn9z0ygj9ANQRHHhVblr+vg0hD6fXJMfRnee29QRbM2uidjW5N2vvaQMFHUGI5de+I/VF78rSIV8P3J4y/x2f0Yi1cIVXA1CTbnk0F1ClarvZefcCUs3IJPaopuEckQN9SNYGa4IpyCeWXSoLrWLiW0ewmsjLdC8r4orNjar4b34EC0C2oRwR6YahuyrBaP2617Ox6UfcI0WHa9Bfe6zkbt2a4NUzLQ2YQXZ/RPTMQ6PzFVFzNckO5IvA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODU3ODc2NjY1OTYsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82MmM3MTc2NmZjYTFjNWEyZjI0ZGRjNGEzNTFiNGRkNDM2YjIxYjQ5OWIyZDk0ZmE0N2Q2NWM5ZTA1NGE1YTEifX19',
            'trail': '',
            'op': 'false',
            'speech': '',
            'speech': "graaaaaaaaaaa!",
            'powers': array(
                "/buff",
                "/run 0-9",
                "/haste 0-2",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/run 0-1 (In the speedforce)",
                "/wither",
                "/fly",
                "/fly speed <number>",
                "/tangible",
                "/intangible"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"  
            )
)
