@plr = player()


@hero = associative_array(
            'name': '§0T§eoo§0th§8le§0ss',
            'class': 'toothless',
            'sig': 'JE4vckLk3l4i83Cb12sWYKEJTRJ7WTpDiQiagDnJHRrWsQlLS9/5iPQoVLD31vFWZKVJObbYJimMtDt/NcRfXgKPqvRVzfMAD80VwIgjuOYlX/fU1B/zF2PiYGAkV3Vq/Az8Nl9WqKtQ0ffVAkIET6ehQUjni13g8uSPmyhEwHh4EmIXCxavfqQUTJM/P7aC4KpW5fILxaD4ZL4B6320eY0yYAT8Zkj+khzDQJrwEt6KDNLxJVS1grD+aoWj9U4I76ZacuMLQjjQABY6NsbGDsPPryahqgtO45FFxRyihFAwC1fERHt7fZot3JdsbDHjDqYmXN1Cc4egXWV+D+JcZsOh4EIIRrpAGHZJ5SXj4Hn51Z5WvpQjeYhjrvTAuHEwsE3ENxgdkYK5iqqpATaQHSf4QFgEfnfb4BM/ErcsImzdZWc4Ugy+UXmPOqlA9Tw3gp7Cfad1I9KfLJ0hTsLpPwEq85KdaCjyQU4sd4pdpowEVBE5nY6OovM7GOYGaMSJuvgmYyUNrjWuQGVsJnep7OZe2YWuEus1JjmvtJRiv0A6Q+SQ7UPy18j4Q91rL6lo2rM7IWOFxusCkJX+H2kfG7idIGms2QgR6YV6knfbCsLhDThKNZFInfrFDM2z/26uGoI9guEIfS+yj6x+wxC6MPUL1EKMbUFNV0EIVGuhC20=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTM3NjEyNzUyNDQsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJMb3N0SW5HYWxheGVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2RkZGQxN2Q0Mzc3YmFhZTEwNTU3YjI3ZTVkNzg0OGUxOWVhYzE5MzZiODYzODlmNTk5YzkyNTg2YzNlMTk4MiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Roarrrrrrrr!",
            'powers': array(
                "/fly",
                "/carryplayer",
                "/dismountplayer"
            ),
            'buffs': array(      
            )
        )
