@plr = player()




@hero = associative_array(
            'name': '§2T§aot§7or§fo',
            'class': 'totoro',
            'sig': 'cWDdIDCDr8qpNezEYVmYXGnshRY7ny6FqCl8nMpGyi8fbYHQvbkPZbPQvOvmv78QsRZZzoI2SNRXE+RCHZ+Q4/aYNp9953e0mkycyyUASYDU37dSEjGvks8UhsHBeZp9toWqJvT+/XWCxLHRg3LzuHrrWS16mOMEoWmJ8/+yrC+J8X9pXJ8S9Dxlauk3TrlBOQhp1Qx0p/pTI0IeSyC+zSPOiMoxmQu5/9Tjv3sVMHvfRrPi10evTu9THCBzNu8dYwkiL+QnbcVobUmLomqbA+ECl8Q5AP2aRSZ+Mh5c03v/C1/TyMokTGmBsyM+7KVn+Z8leay0efqkqljQyNzvSuU//F3B4VsbKUHkJX0YkNJ2FrAOA8PRdU1Cp/A9d/kdf/NajzdJjKLgDuPcQInz8wuV0C0+25Sx/KVqZSN1qI+/kABy8JRD0SDXYfcJNVk6n4nonEaYCpUpyZWRmBCYwPJlchcZC2AV+Pa5z/bPgOnY/eG/L1aJrjbQ3n3rBLsmDdqXfnT82c3G3M0hXD+PTLMbI43KEGJ+unAbJQxIorBza5OCSaIc20W6wqAj1jetOIK/aNOPYdkJhOIiHkmbfoWD6n24eu2LIsTvD1JfFNRSI7Wx6f8Ht2px0AOytGzZGyIYPdfVdphkqdy4gpNbUOCesO1+ApvuRU4zRO5iSCw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAzMDYwMDM0NDYsInByb2ZpbGVJZCI6IjVkY2Y0NTcyNmNiYTQ3N2U5MjgxN2JkZGQ3ZWM1Njc2IiwicHJvZmlsZU5hbWUiOiJXeW5kZmFsbF8iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS85ZmE2OGZhN2RlM2Y5MTZlZTNiYzU0YzdhNDU4YTkwMGRkNmFlYzJlNjc3MzY4NzY0ZWQ0NTJjMDNmNGMifX19',
            'trail': '',
            'op': 'false',
            'speech': "*Yawns*",
            'powers': array(
                "/buff",
                "/carryplayer <playername>",
                "/dismountplayer",
                "/jump 0-6",
                "/run 0-3",
                "/haste 0-3",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 7 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 9 true"                
            )
