@plr = player()




@hero = associative_array(
            'name': '§4T§co§4x§8i§0n',
            'class': 'toxin',
            'sig': 'jzMIXJJ6F0QOOizUyGrIIgg9gEGdhzhCl+G67tVLQGjQdlpAjLcAJpwpqD+AbGBkjcIDd3Ea0HfJ7aMhjHFx1y6LgMnf+7dZB1wT3gNrD/aWqjcAL91H38B5bKEb1SLENffV134Ahlv9Kyl0n1lwC023qajUCZ0Zrvy39aAUZjQTsHlB2S3hZHKtKOjiwkUoAjgXOm31aVgYbUH/PM39a4NrOXttxJNGqN4byOi6EEX9cyD+dz9wktVzmsDKxrwMLt+GwtOi8OWHmgPCMxc4/SvFAEOhIeNhZ37a36aiIpvq2I/96xGyY7JksFe2JID6QspIxQYf6ckrPBZ9wWiONo4bqNpVKCfEXRoDprYwCguGffgSTihuxstjOUA3o32qIIMZ0oT8+JF7I2aE4YuqgkpUJuDd1PzbDS9EhFhqnf7n3WK0jwsSz1JiWwfFQPM1AOFON4d6RXJRYhHosS2AQ8HbaqxMoLGCbkq2yvi0rHLos3ue5NsjVMmAYM9tkIzhL/bQ6vEp4AXZUvfF80Bn5U/Xx1/bW/QsVdcqozJVdiZCQ55zXVHUqKRSIhDu4Sc76juBRyQnMavtlDOTZRX2uqnwZmEYKeF+vwZJPx+NFQtYmsKl88j70ehInJkamCuIioJ2v/w+XaTiG1kBW8oNsmPVFdx2x/Hxko3CGOuYYYE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTU4NzEwODUwOTUsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJ4TXF0aHkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzkwNTUyZGRkZjJiNTY5ZjE4OTNlYTlmNDRjYTIzMzcxMWQzODQxZDc0NzgwZWZlMTM2ZGVmY2NmNzVlY2IwIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "WE ARE TOXIN!",
            'powers': array(
                "/buff",
                "/carryplayer <player>",
                "/dismountplayer <player>",
                "/wallclimb <on/off>",
                "/websling <on/off>",
                "/cast symbiotetendril",
                "/cast symbiotestretch"
                
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/give ". @plr ." minecraft:iron_bars 1 16:10 name:&4T&co&4x&8i&0n's_&4C&claw&4s"
            )
)
