@plr = player()



@hero = associative_array(
            'name': '§6T§7r§fa§bc§ee§6r',
            'class': 'tracer',
            'sig': 'BFpOcZxdIJt/bmsMWf4cr1BFTgs2UuHCJQS2r/9CmomyV4pRamDQKBu8eUfHRpL80+SwyEa0wqEohzafnnZTxGkn6OaCrL9GNHEdVXycw4HxYvXx5xSMvJbsOVAH0j/xLBIDsiwRvssONTEUCn1n4T5NCBiJQTN4V/eMvjS+p+8/6ukPKZxRm2XlZimB+sfSYtBj7oPTxx+daPJYNLi7XEcqduDWwE/ah20DwwPxsDTwNzxeZk7oiIR29XprV/ylzZ9idLfAusJpApYNhXL5sOWgirpxaZcAPrimmKB5zF1jkWGWW+YyF3pdWsZ1QeQn0x22WKohIUjEIq1g/Q5dvSrZBQGD49tVRbU4LJ41i0V4pNXfphJnT0jtqSpI3X/50TMzkaCtrwxwpvQI4cfvnd4o5uSRuHt3/zzr78yJXARb2HyrkkaEG8iZMr4CJ0G2QFX2h2lySZTh0J2tm/To0d0nxBF1Gb9zbXbLwynvtUtLvII5GRa6ynSo/TzIQdO6RZEKv90WxHthUGU1tgESVseaL+VzgThpq0zLC95gV20DJ52WxiFOUjiZeGfJDsOyMdxcvj+3pwYfk19KRJVgM5aK14hQnPSi/cTV9GZsjyB6a0J4JU8RXz7tpQsiCbB6IU/r6ncgJn8lRrxCoPG/J9smaZLJFwzCQ5wEu97VGuU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTUxOTg0NDQzNjQsInByb2ZpbGVJZCI6IjkwMjVlOTZhZDI4NjQ3YjBhNzA5OThkMmE0ZWU0MmRiIiwicHJvZmlsZU5hbWUiOiJUaGVfUmVkX0NhbmFyeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2QyZTk4MDI3YWI5ZGU4YWE5YzU4YzNjYWY4ZGZkZTI0ZDRiYWQ3NDJiNDRhMzNlNWY4MzU3YzAxYmU5MzYifX19',
            'trail': '',
            'op': 'false',
            'speech': "Cheers love the calvery's here!",
            'powers': array(
                "/back",
                "/run 0-5"
            ),
            'buffs': array(
        )
     )
