@plr = player()


@hero = associative_array(
            'name': '§4T§cri§4gon',
            'class': 'trigon',
            'sig': 'JYRTQCDKEE26vFNI75eDiBtEsEAKZBU+KJMVEiSfn0DL1TTEu8ezvjr+jv4qlEfGsTQpqoXqeVDaZZP7SkYevZ2CZGyUE4r5+Vr3rYOHBIjQdGj/OZwScXptysZ1SKnCkJWk3C2zxOB/fieTisnQF9zWO5Md78W+xImEqlq3qWDa8XhpCf8ctV36kwtO32im7Rx2eMHsAHDTPya6WcfWie3weJ0dlq6emU6zpEm2vQY0rPJ2i+qLKewElnxxSV9WnpTTz+wl0bHv/MHkb3zZ8RpMzS5fDjwOYO+6pHifSzb0gthNah8ZS5SkPMuavfJd4LbAmkuj5ZJBFV9Rf+75LMyrIFoC2RrstHKH0ANxpXDt1qxLSBhEXgSXq7wezlBGePzlq+FA6XQ4fpXaxgEwbsWl5XJon9Tu1wjO/wFLCAORYLEJ0mM2rJYq0gdREWapOplcvih+G/N8g7V4ZixgB2TrTYF97+cuYhQsQHLLDXM2tkQwczd4wBtQmsFoBT7tHp0JZ5VsL1SmoMN6tvQ75ywNdPUKsz0GUzgqiz2mao/yMPL1QBj2UA3t8n+Ze0PRWXvU44W2wy3XtFfokf5SuXyomPIuy/muMd6wq4ufjllcDW/uAoiai5zv/GI+PL8o04XqcHxpOYqPwuGzkLBga/iA68CJuk7GYbqIcFpdqxI=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODUyNDkzOTgyNjIsInByb2ZpbGVJZCI6IjI1N2E0NWQ2N2RiMDQ5MmQ5NDVjYTAzMGY0OTg1OTMyIiwicHJvZmlsZU5hbWUiOiJCb29mdXJkIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jNmZjMzYyMThjNTUyMGI0NmI4NGQ2YTM0ZWI4ZDhkMjU0N2FhMDk0OTVmZDcwNmU3NWM2ODFjZWI3MjMzZSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I will rule the Earth.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-5",
                "/fly",
                "/mindcontrol",
                "/stopmindcontrol",
                "/confuse",
                "/unconfuse"
           ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 24 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true"
            )
        )
