@plr = player()


@hero = associative_array(
            'name': '§fTwo§0Face',
            'class': 'twoface',
            'sig': 'l5chKkxzc8cx0Hfqnqem02u6/LdyeaIKglJo8Vvh6B/TiW24786qVB6+UWZwwN/bexE7jvKsM1d/AZzC1GjMYXyMAeT+hyErNxuznb90fhuTQ9NehzHoN01Ztj/K8VGdq3c53gpPli7W828L4oq6mryh3CuAL0ThpsRH9n7XBrfBUi3osOWudjRkSYx+b8CE9otFTZvej9kRmlQLbcKnklZ+c3gtidNY4jEiMSUtVtXQYcu/mzEv4T0OIaqL1S/Bb1KXYZ9zpm6w1NvgyACXOyhtvhmtfPp6ocYerHG6VCzZpSYaWTx5GyfW6CUB5et9i27qsWZUQfIKmWoPIq9dow25g5fUAL1KnUenpOuwQsVxu5+5tdE48mY5809ErF0KB4j3RiZsF79xrOg4RQmD82SgTUWYIhJwX2dM9HnAlE3GhERxryrl8R8XmYT2flRkbBPCu4oytRzPCMi9mJtV1Kq+iB6MC/Jpl2Hb+mlmPQPU9kdob94Xnd2SsVwdxvK+vy66FNZP+flCAm5bIYmEWaBti2ptyZei0TB9HxB9Ep0z5a/HlL1KPAHA4NtrhO2DEw/ph1ujh4FNWbDVcie8sy8ixdmW6xaQr+Q1rxboHmfIP3W3O7DbMNl7dmHR/bIVvOWgzBOeHtuyHKeDAAQoecPWZ3StCCt2cwvo3+sAw0g=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ5MTkxODI1NTMsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lOGY3ZGIxMmE1MzdlODA3NGQ4MTk0MmNhZGZhMjlhNGU2Yzc2YTE0OThmMzFkZGEzMGFjZmUzYWM5YTdmMCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Let the coins decide",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/shot give ". @plr ." pistol"
            )
)
