@plr = player()


@hero = associative_array(
            'name': '§eU§1l§et§1r§ea§1m§ea§1n§0C§8S',
            'class': 'ultramancrimesyndicate',
            'sig': 'moFUnLRyAxJZ713izhF+lcmDxng5GsQHkG3+wdXKns08uvvMMp98cztbOZb2bAJmeeDZDP7BGHcF0/PyBsfNk2tc3N1EgJcG2qGz8Ec7ojgdJVrOspTX1Rnxh/Dyb7ZjQMpK1FuyyVOgWvwauJs5uo3RM5HvEhoiarQXf5cSz948wdtSmIX+BfccPcMJKzmtaBa5FeBNtIiKQ/ZUPTD2a0Gs4LoeIqGbR/nxORkVQx+YFUUXnNdQVqJfpP5vtxJnDOhLEBPgoPBjYNfiPG+u8NztKve7TCqAHPxyBqKGgLOIhbE4Cc6hUYTb+NEZSAvUPmTqoLMK9kw6GdFRzK0LvRbzOvCkvdGR3ILMqvLy0ms+vdGYOvRSJVsrteByJncJRO/JNCNKcVR5i+wIa6nAeVZRhlw2ZvHt0ayByMLUE6YgXnvBLxuUVygv5sbqQQ1goUmduZuewDc8irag/ZUrjft0JBGBcmogcT2FfkgvU4i7gUJ43jN2pteNzKzv4vvKilwve3EjaiW4p2wp26Wnsw2G0o7s/7m73i9XGK3EM0813G413lCYSrevOuPomkWJ3HJMN8eVcBOkPbSWGO7YaRy3MqaHmjMdCWlYVxHzZCdNH3/psH0wRig9Y+H19+gF7w3/sbbwZwOFdmYMWalKtoMHX0O5/7yerjz7OYfnnDk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIxMzU4NTA2MDgsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJhZGFtYmFzaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWZmOWQ0NjkxNmQ2OGM5MjdiZDZiNDZjMjRlZTFkNzRiMWFjNTc0MzFhY2U5N2UxMTMxZGQ0NTJhZjI2ODI5NiJ9fX0=',
            'trail': '',
            'op': 'true',
            'speech': "I Am Strongest With My Team!",
            'powers': array(),
            'buffs': array()
        )
