@plr = player()


@hero = associative_array(
            'name': '§4U§4l§4t§4r§4a§1man§3(E3)',
            'class': 'ultramanearththree',
            'sig': 'QYL8id9g8zs/w1/iWZKv46oD5nPN3n1htPRN7KCDqshLBFJQqfl+LJSI+izg05GgqAKMEE6tUnJC/7MXUitopDRoWrVU7XZyQA1vfiNhsijlIUhJgJ3f0qs142qdDB7AQRHWL2Hcv0BuOhncRrWjyc1++zbctMidhN44ykgRSe+uUjldmh1iYkRqQ8RdJoNWi7Ki2xmFq167Y29bMxWL4i1l9NLfgPPKy/YGzUx4a4EO+fdpRzjhzc2In2L3OujgHlcj17efilOMFDlkcUNXQgtlyVh764wT5Wy7f5gLFVj8AL9PteZX0lZSkoB/0xCCv1tpvVqYdUSxFSUx0DkhtVD2fpxWLNNd6B6DKPXzCXR22WMCcgTZ3tOLHQnnoW7t/RThol+/aGyzQK1l+hsIA94+a6KTaNpCE1GYaRmVIjm0C3Jl2NgW+yP2ouXP8vCfAeddsKiVkoLv+Hzw4KKxR/KMbq/V1643jxLKAR38675lNi7pULOvzNdCKvbJlrYATrOGFW3+OZcWoQNhfNRu+5QgGsHJ3RTcSGYXZnqsms86ELKQxiUz43IHGZxaKfeBDXtrKdS+WeoPd7SCf8X4u7A2+Sc36qv3u6+CZuAcUipLXWWzE9BYaFQt6Z46v3GRzBYx+czGb2idwbe9nerM9c193FfI97TnzhrzIcdouVU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAxNTYzMDkxMjEsInByb2ZpbGVJZCI6Ijc0OWNiNTc2MDIwYTQzNTA4NTJjOTllODE4NTg3NGY5IiwicHJvZmlsZU5hbWUiOiJkaWJzMTIwNSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGY2MTU1YjRjNWJiODkyMWVmZDA1NGFiZjE2MWQ2OGI2Y2JiZmVmZGU5OGZhM2Y5Y2YzNzI2NGJlNjYxZmIifX19',
            'trail': '',
            'op': 'false',
            'speech': "This World Belongs To Me!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
