@plr = player()
@hero = associative_array(
            'name': '§4U§2l§4t§2r§4a §4B§0o§2y',
            'class': 'ultraboy',
            'sig': 'NeemKzdTzZgEmCkrw/IMgKjIRJ2O2R2Rs7Ccf4QQnpbgIdDvUi7mNVSWyuYSCvDymRg0mgmrw+j9Ala+mlqwfvVGDl8Fy9Tppz8eMU2LhWqLlRm3E83abV5hZl5kcbzPp6nEnwPUR6NEEUHuYaFq/r8Vq+V/m4/+20JYQowYEf+MJrGUU/a7YhPM9XAfIJmZmDB6jV6OhlixMlLoFN9UK29djIVRManjZWAqbzLPF/24dHjCXrU9vSbfd48P51Dy1l5kI5RtYM7P5cZUaXsDecbOxSQGBQjdilWLQ0WTebbAV+aUO4DmlqBhxpq4+BYaynzirfyTJlKbVuKeV7OM6SBQrhzIqkALyu6KnHc/eqUCW0PSBr3R5j8QSkR2kMaNIgalUKtlzRaSwLHhapPX0HarC/jXmaBywdJYhhSstKM8urAK/6oZn4PyauM/RcKQ10BQeta6q6zBeQwShQGh3oZTEuxxDjMubycOT7RuSJ8ADEAAaxADX5fbU8qLdTUrCZdLNNMTyLHa1pTiSPeae6IGKEvwXlEXqWL25dj9OeD4RH2aofFTWAY8sZ+6naNuqr8FrMVD8TgoPMXMiQoRgoMOMxaY+Et2pONJi8NDYtyqj5tDFFLcTgwZTtlDVGFovxw7eiJM5gBzQnligKxGjqySX9J61oI5VAbzBkkkqOw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzk4NjgyNDUwNjAsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2EzZWYyNDM4MGYxMDgxNDZkNjY1MDZhYjY4ZDJkMTQ5YjZhMmVhMTQ2YzBlNGViZGMxMWI5MmViY2QwYjMifX19',
            'trail': '',
            'op': 'false',
            'speech': "I lead the Legions of Super-Heros twice..damn I'm great.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." flashvision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
