@plr = player()
@hero = associative_array(
            'name': '§4U§2l§4t§2r§4a §4B§0o§2y',
            'class': 'ultraboy',
            'sig': 'IPLtNogNaig04Om9991SvYRsp2/9jgwbCI4TDZviJOqqAIgo/FwJwEqsoDxW1dqSI+mp1z0mML7HajbPilISOax+8Bzc6cluaOrBKQwRWmKLuxoOUZukem+GCZcDXNGPQjI44V4rTPWHIS0WA2uk8nRy9s5HjyOyJQPyR5mO1PwpTOuqKtx20KqBtcLIvxfN4VCvyWHsBJHSZwXYPCPYNLnk65aeH3SY+4uTfaWXOrDgz93hMrRBuRKo5n4ahteWtovaUQgJIW73Y0ynV5JiVy678l41u7370Jgj3iJaEEzGlZOLhznlfea10U3/tBt4J1JxD61FWZCHLkbOvt3+i4VcrzoQdJcVXZLuOIbUZZ4GVNOR0PiwVo2nP4ZVPxBhRSG+fsqQQj0XYz7CqsNuRKWaaao6KTUwF/TqSvmDPNwnW+4QUlrZpFzF5FC+bRy6b6rnZpDAnG78rhPgN5QEEc21/7U5Qy4ONmhffrnLklQDKxYA5WcduEceGJde/ldXKXVNQcYUuLcA0X9mq9HyH+n2A1lKYyY5wmFo1eyluyXsSWxy8YZMwoT/sNkcvbkXxvnuHzxW7VMF3f4QDUK04CAgUjaVxPRWOUb7gP7JgAjPOWDxwR2/TRpWYkyby9R16W0BAMmE4rya5bmJzSlFuuCHlveT2Lp3Hd8Eog1HD5I=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzczNDczMzY1NjEsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2U3MWMxNzQ4N2E0MmU4MDdhYzJiNWY5MTE0MjdiOGQyN2VlZWUzNTYzNTU0MjRhMWIxNGM4ODAxMWRlMTMifX19',
            'trail': '',
            'op': 'false',
            'speech': "I lead the Legions of Super-Heros twice..damn I'm great.",
            'powers': array(
                "/buff",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." flashvision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )