@plr = player()


@hero = associative_array(
            'name': '§4U§4l§4t§4r§4a§1man§3(E3)',
            'class': 'ultramanearththree',
            'sig': 'NmhtrMKe+tRb8/EN5FSlZ2dBD2jpgG42H7aq0qz4x4AutxVTBbNMqbBm6A7eHwiuyRBf/iLBV1+59HB5p82/gEPuFYsZkl/whJ2I0WiuerGV3YVC1+Jzwsk5v7xBk/vCemLZT7o0qxDbuyOVxnXhl09gnNG6JTvkIAxrHawe+w0jiafqCyD92yKlnVAb13oHpbiGa8vZbOPMRXrJyHxR6HpDK7kesSZEgyp1LiLg2JN8IgfX6z4hJQETGaiHJkxJyF5YkH/o04Zo+ZDqE0FnlkJdfXFWTkYnC6I96i4SiejXae0kRanRkLlAapb/ralqJsDvgDdkidPI7beKSIe9h1oY014J6z4I6snlbUpiCM642aEdMzXsVu0JKLrs4C644yW3aH3rpiJ+8Bg9j9M4ev4y7QnyenJNXBpkftIEdg7IRmeY+6ayL1Ux3vfpmfhBsyn+iAMeshoCLVyBlDci3gKspb3roMUwkiUpCHWc5U1z0HRWuOZTWwSf5w1cB6z+Ci5pWbP6ScNLSwkPyCGPuBwOt22G0ug5MUznn9F0QvnS4xKY7hRgcCR6ebOztd4SGV0sslOYjSNN4K8hv5HxOazVF0q2HZbL/66B1+rLVcukCGs4YzZZyYdMC4Sw7Tyy+C3cAXer6HgsmR38JOkxgCJlseesARYhtIeMwJcJx6g=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE0OTg3MjI4MzYsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJhZGFtYmFzaCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjZiN2FkYTRlZTRiZDhjZTU4NWRhZTMzZTkxOTI1ZjlkNmRkNGY2OWE1ZjUyNDFkOWI1MTE4NzUzNGU5OCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "This World Belongs To Me!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." kryptonianicevision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
