@plr = player()
@hero = associative_array(
            'name': '§4U§2l§4t§2r§4a §4B§0o§2y',
            'class': 'ultraboy',
            'sig': 'ezUqImt8VXBEWQi4gtx3zPnSrrybcdAfUEXi7A2JO+BrC5er7qNvrwRaPHuuIRVLDRZCdSvx2grK4xmH3MSuZnvUWyQoO4yDQqiJDfQSn5Wwtdg6QVipmfXPnNuU9BQxLaj3YQ7k7J7m0huFI3FS4Y3xBF1SjN7J3RH4SWf3amF2RMZS+zc4YRdEpaqD29jw46ZgAqS/+xZFNyG/ghw5N4ov1pxqN8XNha4T+DF7+EnvlAOCWSI6a/+G+fXgt/z5bRPehCCKWCDmYjDgqp+ABk8aS4Zje76TBVfbmWtU7Ka8OLflCzNh+LdJ2D/0HYuGapYqoP+xcBzW+GWjE0+fqlI8gTpMphWdlgH5XgeKaIsFbZrCWWCouiQLX9o+TcXsmcU8JLKKSexfrir/JPnN9x0pkpnsSoxsn597+OCrLScBP5FLvQSWjHbhzWEwngRPaD+MC0ziKkjv08JgVZ6+EMk4VUBRX4EIovgMV94QfjLsa0NOrMxnBqL+745/pA4OXX3LvgXFPGUYozKJuuvysbp0OJVIf3SfzkHnl5RnMRVpqB7LdxJytuNg5ni3q13496YNRJOIvUYmwNYunmOOSGsj6sWQyIgSMnzKrGBy59wFl9SETIMFc8wNkeLy1vZJB+m0v3L80IcKMlyCkZSuA/N6DB5mTxlGfiiPIZQB53M=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzg5MTM5MjUwNzcsInByb2ZpbGVJZCI6ImQ3ZGI1NTcyYTUxZDRlNDQ5NTM4YjlkNjVmMmY2MDE2IiwicHJvZmlsZU5hbWUiOiJHaW9fREJaIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS85MzE4NTJmNjhlMWY1NWU1NzA5ZGJmZDRjOGE1MTFjMDJlNmZjMzQyNWVjMGVkNzI4ZTI0NDJiNDVkNjNhZjU4In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I lead the Legions of Super-Heros twice..damn I'm great.",
            'powers': array(
                "/buff",
                "/jump 0-8",
                "/run 0-8",
                "/haste 0-8",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." flashvision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )