@plr = player()


@hero = associative_array(
            'name': '§7Ul§8tr§4o§7n',
            'class': 'ultron',
            'sig': 'vMMmjwhJlsXKfnqw8Kp04RY9gEF8w6OQr1wxmg67Ga6McFTnt1V+LPGRDqEVpGk+KLfJynb/HdljCKMOD5+Tq8YgdII0lgnU10MHMXiI+HWe+ryfxCT5R20QmHhkkPzzArgJuMOktZKxPx5e5yfIPhJwI+xNwNSnrVHDaPu8Tbze9yraPEaSwjHBnTsfn1xHCmB5OSZoWNIst0Te2NfT2sCll/gjLW6BMKDkfEfmKSwDpFk+MhdCrdYwiWUjtlVokum/QYx/GsOD+vxUMpqVnI66hqoMncfT1Y4eENxjJ1tmgAxsAOP6GPhJkSMnRyO4s3sSR/kEF8xPga5v+VGEd+X8FuHQ7fOM0zhhK6pieP3tyxAka5RbpqEUzGiFH/hBOKS8PwJ4ux0OhfAuP4p70ABnI4e6tL6+nZUpdn3rcmwlb5CG8dkWeUCzRAum3YaD78Qzs4h8zNg7eghODX79j/cEoH7ue08pNVvi6sS1PCxHqXJ8xeqhzRRcxavCr8ho/44JrsHiHPOfVVuH3j5EnhVGGvUpiEbUQ2vlA0S+Or6zsXlrv/wSrK5UL0liL3PoaGwuyZshjuFFkmc+4h4bmW2AOwm2Jz9ZP2UHush43SH/L5/YaH7R61K0Lviws6JnWAXj/kuyKy1M7bQVm6wHOOmDu14OavNMSd7vuaiPGlY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjA4MjIxMDQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzU1NzM3YjkxMzU4NzdiN2Q0MGRiNzQ5M2QxMDljYTcyYmNmMzIzOWFhZDg4Mjg1YWRhMzkxODlmODNiMWEyMSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "You're all puppets, tangled in strings",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-6",
                "/run 0-4",
                "/haste 0-7",
                "/fly speed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." petawattlaser"                
            )
        )
