@plr = player()




@hero = associative_array(
            'name': '§4U§9n§fd§0y§fn§0e',
            'class': 'undyne',
            'sig': 'mHd4IsZrCsd/Ub/kDKw78d2Wgo7y89sNwzZAHRf0TmMIJ8scwkiS/ATHWHJ3vcZZXHudCZSwTIMa8Q5caHAQUR3N5mlqNYbHYvLp2S5guYOsxmnIMrvcl0/lMWswtutOjlpRvGfOiZ9xDg5aV4BKu2Jr6j8LDIEqYcUQ8ahwi+PMUsDE7NFiQOPf0cba02xrOceYpKBoArsGchQ+SaQdh15mYOkStW12fciH4/cQR4pBzTlzCRyRSLlAmVVoi5E2AfTfbTUMtmES2P8NWzYhNvi36bhrOYGIcDEB1d67vkDOOd3QM55G1WaYjcGD4xiE7lYJBtRZ2e8xMGSfIz6lMFYB41rL8AW+Uoojw4u2Lp8CAd8Yv1ePCg5b2bAEDtgV1Ar9ybooc5cA66BMjQljicC65kVtZIrfilwbmVJbsMNMHkMRbliEteknuo155lxlm7wQd/4lfPn2PiL4xqs90zeNDcTSm0GvSDDjhMQT4DvQ1k4R/mk6uw16xrZQccFiia0QSps/svHi2LEOY0oYghZaX1RtGXDEJexsIaJrZf2QOzKmYeCM+C7wAONalBaxhMYDYQkFSmPf5LloF1QQq0FG+svtAlN3mdvokbhw9xcRDmrVxtcynC3ALHTXsokZC/Db4bYRu7WTJ4635rJ4ywiQ3cfASPnLuVb3YdbROZo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzUyMTAzODU2NDMsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS84NjUxN2E5ODQ2MjFiMGNjMTRmOGMyYWE4ZmM5Y2ViMDgwNTMzN2IxNTgzZjk4Y2E0ZDgzYzU3OTNjNTRkNGEifX19',
            'trail': '',
            'op': 'false',
            'speech': "I am Undyne, I will bring justice!",
            'powers': array(
                "/buff"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 3 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:diamond_shovel 1 0 16:10 name:&4U&9n&0d&fy&0n&fe's_Spear",
                "/give ". @plr ." minecraft:iron_helmet 1 0 name:&4U&9n&0d&fy&0n&fe's_Helmet",
                "/give ". @plr ." minecraft:iron_chestplate 1 0 name:&4U&9n&0d&fy&0n&fe's_Chestplate",
                "/give ". @plr ." minecraft:iron_leggings 1 0 name:&4U&9n&0d&fy&0n&fe's_Leggings",
                "/give ". @plr ." minecraft:iron_boots 1 0 name:&4U&9n&0d&fy&0n&fe's_Boots"                
            )
        )
