@plr = player()


@hero = associative_array(
            'name': '§0S§4u§0p§4e§0r§4b§0o§4y§0(N52)',
            'class': 'superboynew52',
            'sig': 'noIzlevKo/66pNdVPkcyJkkAGtbJmZAF7maCvSByx0GOQ1htCEypghgEjLgjgkN7KksnCw0r4mfaVJHhKvJHX1rNczIJWfHCgN4kSUwsQJeTwgZPcbfoJ+G3/Hk8ypl9Uf6okESBpBsNVE2Ybp1ry8JPen6lepiAha1BWOeKyk1+4gADtGpCmYV596rUcxVKAcmDS7MJ/Svqu+yRPH5ge125ckxlKaqCHG5+JGRQFDeMCe6tI/IDJItOSiLYH2KmmnS61EgH5PSl7kiFEpeEgzlm9zc5L0d2ET864rHleRMcFGo1SH2DzelnRhLjNgNwFVII+PrLUMLiSoA6jSxmJrYDgZvxvFPSfuKKxwO5/EMWDMBaGSscoC4S+eN7TE1xNoEe7Ifs7qNbQUUqATZFe7z0GfTnpHEA8dv52ThOFpA+492ravUSIT8+g5VJfkUeQomtZpUhci2gizl9YpN+1pusCLKWUUSuD0xuH4FYrTigzNZc3IInB+VMZy6WWoVlmIPATi2lUrtz4pnada9kpkm66f8EAEOWUgePzEG/fKNk10XvEB2BRmmVl/H1LWC4tX5cBrNARnHtrzu/3Bd+GIUk8l0darEcTGXcol4nz/Er1jgXrli+B6tpZr5kr+qgy94bhD/Kh0+tcphbmicV5rPinMPtvJvkGI9DR/mvFZQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTc3MDEzNTI3ODYsInByb2ZpbGVJZCI6IjhjYTdmYzU2NjE0YjQ4MmE5MWRmYmY4NTgwYmEyNzNkIiwicHJvZmlsZU5hbWUiOiJUaGVMaWdodFNoYWRvd18iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFjZDRlZGRjMTg2MTRhZGY2NjVmM2UyNGIyOTVhYmExYjI1ZTg0Mjc5MzdjNTc3NzQzOTFmZTZhOTE2YjFhMyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am the cloned son of the son of Krypton!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-8",
                "/haste 0-8",
                "/fly"
               
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
        )
