@plr = player()



@hero = associative_array(
            'name': '§8U§2p§fgra§2d§8e',
            'class': 'upgrade',
            'sig': 'OjeJyuJeY6zMSkX7B1wWE3lXQ3pdeqPeAhnHrRgBvlFsEVGVEsOrEprYKvpQ8hLa4xTu6GsnUMpppyVRv5ICGKwYK8hOYdsHaOhoj5l7/DJBfTe2JbW1sbHWMEiyUpgIy9Fa2m3vKWOUyvyvur84FfkbxqFq+4iyBR4+vNZ2592TWoMUkl7pwrV6tiPkKkd4qycpU0MtM6cAmREJI2OfDZTiUViIyIPQ/tTVjrwl78HFb3f70jdgc74zbDSmqUC0Q+WYDxuShoMomLWqH+u7UsVxo6gGyAMwKFeFgEm1Rp6CaUWysNdlJT958qt626y6ev7kNcZf4tocCazdCeaFzSnOphv0uxRIAcflqafZDST8NjlRe1AeD52dUK6MF2lQBbjF9BoiIHtbdlWkmEmv7SWQfLPFn+GpTgRh1y9YmyWTxnsBxQlei0fsHGrgvO64o8xGto17SKDPcMEIFDQg5r8+082yapB0RTDCPyV/yvXQFYUGF8OEbHKm2pujGq6RxoCz5KSfDkJ5CfsrE8ksN2fADUJzJPA1NFDKsZbxlThUzELF8BEnfLgyfPg3HbKby/WBdkbVP4fMY4+IGvcm181PnFxHDS/kJTALqT7VHujAmcauStfPEDskEA1x86UMLHa+ZyIEx/5brJUMunmdxSY9yvJJeji564SsktBeuiE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTg5MDYxMzk2NDMsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzY5YzQ4MjQ5OTE4MmYyMjc0MmQ3ZmZhOGI4ZTMyZmZjNTY2M2Q4NWU5Njk1NDExNTUzNjUxNjdlMGVlZWUyIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "How about an upgrade",
            'powers': array(
                "/buff",
                "/herotransform",
                "/run 0-2",
                "/wallrun <on/off>"
            ),
            'buffs': array( 
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 11 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:flint 1 16:6 name:&8S&2p&8i&2k&8e&2d_&8F&2i&8s&2t",
                "/give ". @plr ." minecraft:obsidian 1 16:6 name:&8H&2a&8m&2m&8e&2r_&8F&2i&8s&2t",
                "/shot give ". @plr ." opticbeam"
            ),
            'alts': array(
                'ben10',
                'bigchill',
                'alienx',
                'lodestar',
                'heatblast',
                'fourarms',
                'xlr8',
                'diamondhead',
                'ghostfreak',
                'goop'
            )
        )
