@plr = player()


@hero = associative_array(
            'name': '§8M§bar§4sha§bl§8l §9Le§ce',
            'class': 'marshalllee',
            'sig': 'SJoF2IGgYmGZUEgEgMBdICOlsftIX2bPhulGxAxfaO+VP+JdWPzsyzfeTL8NrIJlGQgkac8O37/qPMyryvo2f3PN0DYTwSe4713XSgbolI6EXzgreU2d5q3O96R3ri0G/1YdSZlsH6GeKJ04uOloj26/s9G2opZDpyddNPhq1puDw6efo/S28c0z/RvF/ApgaZVm4GghU+hpFZ7+HUM4SY5c3pLnuiLKRYbS2jo3LlPs+uSGNikW5jiydxjL9ls5XR+KtM/AsX39wqLNlVWaGL40G/mqxCGmEPxm989k4+rJGTRzFLs9NKg5qHhcBVvrepkleUoqFnxbWp/ojoy7VSFlo5/smjsi0G9uJzb7LWgE5caX8pC0qqOQc9dc9Syj0HIfDJzlN1ApvMwQxAWnyq0kVFgk/mrZ0iPc+crPPaf2hBVSyEdVnrd2e/g8Xrw4UxdeeODbvx75ffCnFK1yMVpWnK9qZCG6PRJ+Hq1EeaC1lVBb/tJg1TDySk0pX0QvZk5BRdd5vINVh46LHqg+67as7s0DDgQ3K0E7UDpz4yDZjggyi1e/TUPomSiyznvKvzrw5m/wXEidzd0NgnX0cH3cnPnZJUP+lE1kJRh2v0MpLB7jfOp0X2qqtL+36GO/i1CaG44c2wymQnLjbYX8bcqUQ1eLD4Nyu3BDxLXatsw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDYxOTEwMTU1MDksInByb2ZpbGVJZCI6IjM5MTc2MmViMjRmNjRkOTU4NGQ2YmZhYzY4MmQ1NzVhIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hYWM1NGFjOGNlMmU4NjhmNjU5ZjE2NGUzNmUxNjRjY2M5OWUzMWE4OWY4YWQ4YWRlYzNiYmIyOTI3NTM0MWVmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I....am Marshall Lee!",
            'powers': array(
                "/carryplayer",
                "/dismountplayer",
                "/float",
                "/stopfloat",
                "You burn in sunglight!"
            ),
            'buffs': array(
            )
        )
