@plr = player()


@hero = associative_array(
            'name': '§eV§fe§1ge§fta',
            'class': 'vegeta',
            'sig': 'o0uUtV11lIT2N2GA8/Vs9vjzCmmcaHvfe/5ZG96esYiDm17thIaXafKsZgWTsYAlkWtCalDdmfQvthCufFpbV4Ep87X6u5dHAtXjwlkv21Ic1JOU27xU+Dxi3IQKg70GRo7a1qKVRcw/GVhyBHRtoEa5/Yc0Rw+HuXewHvou6Ouw9EfyMhgoOP7HZRMtx2OskCZj0TmBwZAQHuiCvLCLmUGSTbfOhNUKgvSGhnx48QCiTpqrriuLQetzZ/+JR230GZ2hSdxxlxMSfs5dxBWXCUltBAzEgNyoA/Hey/URzNcBowYjnFdOeqiZAfO1lJxtCIARelaC5GAyfehUkptom/ic44l0JvKVK/iyxN6soZZjwPAn/ZNm0qTuR4gM/v6PcJm9VJCoQXO9zyn9D+dQ9MInievr2jdbRTjLTcKTs9CF+RB3cBC7dGHcICBPycVXOgNZfRz9htTdCOtW0GgVkzhN5PPRTYv6Ao1K5XE9UCaXLcS0vhwOLyICox7X2ddRUjs1VV9Uu3ThEFK2fZnezysJNmWDx4SFdcIqDQUH0E0SQxespTJSmYRjAsR3OE7ifkbkpS/mYdrOsMOmuOWCH0YcyMif6HtQLlfstamY/Vvtm051GOX55+F9Fya9zRGBt6PvdGnG4sgVsG4Q8YHtM0R9YsIK5SeGKxP54Nqi6dc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTE2NTQyMDIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQ0MjRjZGNkZGMyOGI2M2MzNDFjYzA3NGJmYzdmMzBiZTY3NDZiOTEzNDFjOTk0YWFkMjU3MmQzOGFmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I WILL BE THE STRONGEST SAIYAN!",
            'powers': array(
                "/buff",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true)",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots",
                "/shot give ". @plr ." finalflash",
                "/shot give ". @plr ." kiblast"
            )
        )
