@plr = player()


@hero = associative_array(
            'name': '§eV§fe§1ge§fta§8(§eSS§8)',
            'class': 'vegetasupersaiyan',
            'sig': 'DKH3OlSGkwxVy3oyg3GJOO9qXeHac0ZHRyqoiPsd6GpN16VzWmMWHqlAwIcln/G+p1Q/T9ml5oHNtej6Gn6UEhhbMPKDN+CwR2N71rqZe48dWHg8uXNdb1ianw4sZdKluwXiXkfIu9K9YoP19/tSIwOw0aalkTeVSGRg3DvnEAxqgvHU1jwFaikMwhpjpCzb8ZY3G6fXtJzEPPuJ1QVyBVS63wQu2tyWDLRenLyd2//z7Cuvss4FBPg1bD58EsNMsSlZvO3b7FIKtSYqagEY9oGeE4Z6SXhSqr8CT+t/Mglc6uArUQAD9L7TONUZbwsyS1dJkE68LIkTbOwOycrKSE1PWQF//aPJBjb4pdtlpe1h4/Gq/38Ny9Zq5M8UCWy/FPxBffmzVOa2y1muw86Mhmwtpyv7vcJreQdEM5KiKMHK0lToTkZWlMnk849sGUhNWB92VG99dh12/dF2AdWxBOBGTtGcvNM9SQLs+j/dJQB4STM9STa64iffXYY2zamUHHzDyBA5l+EwuBZCg9VveJFZeVt44wqFh59sM/rdwP/Ivm7LnjxuHs8BC4SaTmZqShem975UF1jidiLWn3yOW42GYzvyqOCW52WkgoNyaY0iZe7UYMe6xjPYJTpaG+kTQmmICRH3vm00Xv5TuzUuvmr5D7RjY0ygv9iqzrEdM4c=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTg4OTQ5MTQzNTIsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2QwYjRlN2Y2ZDNmN2IwOTZiMDEyMzNmZmVmY2M4MmI3OTQ1N2E3OWM0NzFlMzQ1ODVhY2Q1ZDk2NWFhZDI4In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I WILL BE THE STRONGEST SAIYAN!",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-5",
                "/haste 0-5",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 14 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." kiblast"
                "/shot give ". @plr ." finalflash",
            ),
            'alts': array(
                'vegeta',
                'vegetasupersaiyan2',
                'vegetassb'
            )
        )
