@plr = player()


@hero = associative_array(
            'name': '§8V§fe§1ge§fta&8(§eSS§8)',
            'class': 'vegetasupersaiyan',
            'sig': 'o2UzxUHCshUmPixx/n6LYjb6oRIecJUqw3o1/MT04h6xlKFyXgdm8+moEZmTdNpWAKOMhisRg8rJ0aUYrf3+ivh4u6/62loKXjWQl6MfQLq7fYniSNbUM3riHxA6wIWXFeFA76DD4q3UylZIZdNCZEYS5VmJDmV09kKdlqoo/Dtc3rMZLt2d0ZYKifSIFadaMDkdfBobOh3h6gYjX5gGRw/0Lsl7xjx3amS3z2EAdZ7MPtuf/CEnI4k4nk5WufIwx1xI8ZCCejPsnSC70bANbhmIlzkqas8pbsrEmW4SNB24H+C4iyDGexStAQ9eWFszjhldg6uLUE7g080KbkDLJ1eX0J51/LWzIcWwY8vG9fnuyce+uqtL+ViQiUQpxTPPF1TGsxSF9C8z0Di2G+2ViRFSzxocDCdZ5nClCBtIQd4NFN2GFLYXK+/y6COnRgGc8m2VbIy+tOvaKv0cBzUbF7AVtjbJWxhIG2CotWGi83ByC1Vl2Kyk6JN+nJjA4dxTcx0UpC0sK1dgJ/MHyEQdDUzQXGLRgGBCNjA648PD2dR45WtoN+UUnZhNkHFgItXWg2rE8WiBabkrbZiBsEWHJvJWXrga6OL1Mv4Hof1CVPLCEoZbpxCu5FrJFxaXAuOROb3vXidea6CzWiCs5nwBTgt8Q3kGsj9yu++Zy90EWe8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTg0NzI5MTM0NDEsInByb2ZpbGVJZCI6IjA4ODBlY2NjZmVlZDRhMmY5ZTIyZDhmNzIxZjM5MTNlIiwicHJvZmlsZU5hbWUiOiJaZUVuZm9yY2VyIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zY2M1ODEzZGMwYjMxM2YxODhkZmNmZTM3ZTVkNzA3MDc5Zjc3YTVkNzlmNjIxN2FiZDRiNDdhNTc2ZWIxNCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "This is the power of the SAIYANS!!",
            'powers': array(
                "/buff",
                "/jump <0-7>",
                "/run <0-7>",
                "/haste <0-7>",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer <player>",
                "/dismountplayer",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 16 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." finalflash",
                "/shot give ". @plr ." kiblast"
            ),
            'alts': array(
                'vegeta',
                'vegetasupersaiyan',
                'vegetassb'
            )
        )
