@plr = player()


@hero = associative_array(
            'name': '§8V§fe§1ge§fta',
            'class': 'vegeta',
            'sig': 'MSflhJ+jY86qLZTUErWGQ1/Jv+aJ5Q73ZYGRH6VQH6YEKtAELtmXPNhjeU/RpxGvv9Xubk49EcxV9QYjqWo8SKXgzYj0HVRRF6HAcItp76mfdcYALZoCNhbyWXoVswcJoWADWPquZAyw9nhOhVppNCmo68dQqg9LN6KK3fRvouY7/zccsWm7/9U9S1RLtqFYm5r1Le+DsnJKHZlhHFZl+grqtRFp1TVQD6JLzf7rX4pA7q4O9tDjc1m2eRek45/noG7TMKFjdX/S3B5cO5bnPDh22WUskfBI6AjFhszXkGk6MDzg5BRntaZuoMg8/JOQUY9BWNgEl+8Xm6wDGAUZUfLCTJWn7rwMoShML1wWk0JZXvjhWjVi1Y6+/Yxa2tdqIRDa9O4DRVLP27vNMVWK2fJQcJwsnR4RiwFNXsqTfFOKH7qnS5te1we+iqyYr31IdgPoSeesdSXUWnxVk6E7slo5Rvvsnl1kqeu09VHrD0ZfyxyCXMoTNKzeYbYSgc2lgzXHIOct/LLBluEQXDCrrwTxBUKybuVBa9kUxJgE+3SJdFqmtLaTKd5tSGMdyZ9xiinhM5QHqZ0aZ0sH2PR5RHrl+iY7AevZLQW2AL0eSefl8SDrwHZl1wRk6ovWOM8gYqGGNvzeP8STSpwTWrHFIQKkuNqgrRYcqAXGcRdsbg0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTYxNTE3NjI1NTUsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Q4ZGZjNWU3ZDgyODgxOGQyMTU4MzVmOWU4YjA2YjJhZTE1NThmYmVkZTRmNGQzMTI2MTkzMDUxZWViNCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-3",
                "/flyspeed <number>",
                "/fly",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." kiblast"
                "/shot give ". @plr ." finalflash",
            ),
            'alts': array(
                'vegetassb'
            )
        )
