@plr = player()



@hero = associative_array(
            'name': '§eV§ci§eb§ce',
            'class': 'vibe',
            'sig': 'XeP0f1FiahNTzSuEyvaE1XI7yvKlS3o/tqvnwunwMtp0pj8/yV8Z8cZYCEndz2IAavFUf9AQd22A3kUJN7aYfz99cvBt0qKXfcB39SAnEiaRi2ppz1iuM8Et/NEam5u9lqsUauhxN99YGpLcBh+OGzoIhkaMikbsAlpyIP5BmFVX362mSVtmts1e4oMYg1jUAQ1lhrRNsDJ0FqeHA3cW4U7l9VLL6gi2oqlpNeA7JjDsUuV4TR1UgudAIGP5xMbtoD5xar2NYOmQ0ZlaaRnBF9GeNtVrOKmuWC9vCbAp8/fBtdVx4eDNMxEdAxc1AroB/Lg6vJH98xm98AdQSlEsgx3d+ogSYqPnVaYXQZCHFJFSi57MFk7fbUTaVJ8fCCQF0ubtkRHtYLuqTyC0dEGKtzp+xDW+E2dJ3Z8fqwD39y/ITODq2qnJ94lfqT/KVPh49Gj95LZ8NWemrnHnJPmSAH+l5eGL4cZ/2pO+1bw6iIaaXBpxacCywFwhcIPeOBHuV/IEFYUNwSlIR80ccgJEwGsKAF2kqu22HNc38tC7s28BlSbIEhx4M4RnpeO928119KEhyyq/dGx/SE7AdHcYGCb2yZ+1YIeMrFHAQIeQsM833ksXKhElgaNwY53g/VXsr54R6n2ccq/SFOyGhK4MeGchNzPuhAY0BfbDVSBTlzo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE5MDEzNTEyNDYsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTA1M2NkNTEyZjIxYWZiMWEyNTg4MTE5MGM0OTU3Y2NjZGMyMTYzMjEyMDM5YjVkYzRiNTgyZTZiMzNjIn19fQ==',
            'altskins': array(
            array(
            'sig':'dc1/fpcuIv2M8QngvjTzgjIzeL41kGKzeP9J9YM3UW1I5e8D6SWVUxe1v6djUYnnnahhSiKJu09zV+eKI3bRPbdVSz8fne7UJjEuoDO3ZOyDlnwkgxCDHWgStE3FjlDpUsZOVmxXIJk/h85qawWgRht8uEOvIVETwLbZhqsGBqFh2WMl32mfELxoosiCkASduaMkAEJqvUZmOYtiuQCs88lmc5aZtXSWPfwPbhaehRUGSsByAR1gBv07uDb48j24t5oPLkAzyVNjpS+HLlSa+IHEq8fLLpjVn0ISbS3D/5/feaNFqOdsKOS5A5z6zuHPnMidabPeSq4joG9l78eeMvq2YjbBQSvC4HvO83MMcbbQid0QdF4DNq5sIPrnUUTOk1jyMoecwo6nwUWqebuQcvSvz1hQdAlbE8PHN+QKvkpKKtTF564kfzACDBmQUlhHhWRLsc4b/n2m3Wcme0mxDYdEzLKUDNMm9eUUK1GV6tHwov+APtO8O81d/ziSPCpwkvwEEQR+qs/jGr6/GUCBSccCXBiKjfWtGNVjeOZiOs/MyV5y9gArH7S/nPONS3tFOxQAKn3sq2qL+7qOgvxFDZr/CdlP4I4JzAsJWwXFkLl1Fj1gHmPxO6VsBxR3fT5cbd67epbr7F8KZEq/cUJkBbrFElNXYQZzJ+DcXu0RC3s=',
            'val':'eyJ0aW1lc3RhbXAiOjE0OTUxNTQwMDMxMTYsInByb2ZpbGVJZCI6IjkwNjhlNjU4YTE0ZjQzYTNhZDY1MDRkYmFjMTJhNWUwIiwicHJvZmlsZU5hbWUiOiJNYXVyZWtTYXJleWUiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdjZGIxYTUzZDc3NzY1ZDVjZGMzMmZmYWNkYWY4ODkzMmNmMGRmZmZjMjE0YzE4MjY4NjMyNzEwYjJmNGMwIn19fQ=='
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "I got some good vibes coming your way",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2",
                "/carryplayer",
                "/dismountplayer",
                "/tppos <x y z world>"
            ),
            'buffs': array(
            "/shot give ". @plr ." dimensionalbeam"
        )
     )
