@plr = player()



@hero = associative_array(
            'name': '§eV§ci§eb§ce',
            'class': 'vibe',
            'sig': 'XeP0f1FiahNTzSuEyvaE1XI7yvKlS3o/tqvnwunwMtp0pj8/yV8Z8cZYCEndz2IAavFUf9AQd22A3kUJN7aYfz99cvBt0qKXfcB39SAnEiaRi2ppz1iuM8Et/NEam5u9lqsUauhxN99YGpLcBh+OGzoIhkaMikbsAlpyIP5BmFVX362mSVtmts1e4oMYg1jUAQ1lhrRNsDJ0FqeHA3cW4U7l9VLL6gi2oqlpNeA7JjDsUuV4TR1UgudAIGP5xMbtoD5xar2NYOmQ0ZlaaRnBF9GeNtVrOKmuWC9vCbAp8/fBtdVx4eDNMxEdAxc1AroB/Lg6vJH98xm98AdQSlEsgx3d+ogSYqPnVaYXQZCHFJFSi57MFk7fbUTaVJ8fCCQF0ubtkRHtYLuqTyC0dEGKtzp+xDW+E2dJ3Z8fqwD39y/ITODq2qnJ94lfqT/KVPh49Gj95LZ8NWemrnHnJPmSAH+l5eGL4cZ/2pO+1bw6iIaaXBpxacCywFwhcIPeOBHuV/IEFYUNwSlIR80ccgJEwGsKAF2kqu22HNc38tC7s28BlSbIEhx4M4RnpeO928119KEhyyq/dGx/SE7AdHcYGCb2yZ+1YIeMrFHAQIeQsM833ksXKhElgaNwY53g/VXsr54R6n2ccq/SFOyGhK4MeGchNzPuhAY0BfbDVSBTlzo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODE5MDEzNTEyNDYsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTA1M2NkNTEyZjIxYWZiMWEyNTg4MTE5MGM0OTU3Y2NjZGMyMTYzMjEyMDM5YjVkYzRiNTgyZTZiMzNjIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I got some good vibes coming your way",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-2",
                "/carryplayer",
                "/dismountplayer",
                "/tppos <x y z world>"
            ),
            'buffs': array(
            "/shot give ". @plr ." dimensionalbeam"
        )
     )
