@plr = player()


@hero = associative_array(
            'name': '§4V§ei§4c§et§4i§en§4i',
            'class': 'victini',
            'sig': 'kSWeyQTF86uf4GfQsR/8nCBHfc41k84DHHQiEoHMKRQkgG9GOqY/WmDTMtz3lt7AMq7rlGaSvYw9lBLec+JqMRg3Aqm4FONxSyJauSK52LLYXEuaRalg3mptQJ4qC4uY/2iw9zPb8bTtd9iVRo83r4sHxO158elYtBJSgaqbq1sNQzJgIWdPOYo6h3vN7v2gfHhwg3twEcx5V0V2xEDEk0LWo0spUCKpNacwAWgjCthGpgWavcqTyuBCMUU+L6swpFRL9L+Vnhi4JK0/LbhiL1RQH6EpIdoO2oBwC2Ed7SL9NnBz5ZhouH7buwtncTmxA1UAVtgTDJUz75ph7XhCxYOzFmyasGZ79coO9GbCQBFkHKGXBBqjqjqeY+Bd2w8GwLslONlgAynCnlld2BbNm5ho2Ac4mHqvXhRcS5DsW96k2TPlLdQG3NczYPI/+GpI8JGqmmqPNvus4rqkc4qPaA1Bp7E1jkQy6Qvc2uwvCRe3Mt4KCnssZSlYnHnfWjtLPePz8nk7VQQ2ThzvC55iwN3/DR9j4T7YTr4fL4uxNyqEWeIDBsoLZhDDWOh/fvlFQbmoxFkuYKEh4M+8DENzc9xWFrgRhcGY+fE+YuSg3KkwsbNjaCEeTiAOOiQqaD+jX5l7HClIEwLX71U9kA9I6uY5uCzGp4XzRK9nXW3KK50=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODYwNTY4MTc4ODYsInByb2ZpbGVJZCI6IjU1MGIwM2NkZDllOTRjODliNGVhNDRlYWQ0ODljZTBlIiwicHJvZmlsZU5hbWUiOiJBbmltZWxHaXJsIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS84ZmI1YTA4MjRmOTZiMjE2ZWI3ZmY5MjBjYzE4N2E5ZmEzZjhkNDZmYzM1MDZiZDI4NWQ1MzY0ODUzZmZkZjgyIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Tini! Tini!",
            'powers': array(
                "/buff",
                "/heal <player>",
                "/fly",
                "/empower <player>",
                "/invis",
                "/vis"
                  ),
            'buffs': array(
                   )
        )
