@plr = player()



@hero = associative_array(
            'id': '152',
            'name': '§oV§fi§cc§et§fi§on§ei',
            'class': 'victini',
            'sig': 'RRexyJUdJGpAKds2TH26i+QHHCLK5Z8d4bPnL6TfFVmLWKOro2Y7LPop5xIPjO3w239NG5zLj7swd3wySfbREPjwjyDuGE3ohBiyGGH05qi18RwXQE9UTi9efR9nUbJKSwCqu/5Er+M2b0qNzoEwAFRgp4Zm8e67QomKIy0fu0Xz/74QPAzOIR6RKWe3h/84UfOA6y3EtSzQJlqCZPaE709PrXv2IthlmtSyfQ6sr90ebKtUYSzzFxeYlCglHYIE9BvqMQYGC/VD51Ynw0jSz1m+8Hfm1HCXr/se2Zq+PcrJ4H3cjP2aan/C2G+4yK96TqzJfrdbMAWKIhumpDNmucAL8V250JXwM6HQL5xAGFlIqMsoaUDsQaM/umzau88gNqRJjQQMRccTin1NWJVQWSpejkL5iexQgopyLyYadOGdzN55lB9xI7YwalqiP5cWdx8281oOAUSWrthvwETqOl36V+ZU7o/HQOy1D0uN7Kjsj2FY2E8MN7LEGbfO0AzfdnedkelZmVZ9Lj6td5h9WevyCCOm8gUS7R48JXz/VphzX+Df9zDUeBonlyLvSaTpx7QgstihtyyIe0GUW39NsmrVCRuOjQWTNT5n6MkrinqzSG6iB9DQa172+GhzZYLGLHOWWX5LcK2i45vmZxVHGlVolHRPXdNOSniinT2OUvk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ3Nzk0ODQxNzEsInByb2ZpbGVJZCI6ImJkNmY2MjIyMGI3NTQ2OTg4YzgzZmExY2EyYWZiMmU5IiwicHJvZmlsZU5hbWUiOiJDaDFja2VuIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jMzI2OWQ2MzQ0M2ZiZGYwMjk5MjM4MjU4N2ZhYmY0ZDk4ZTNhMzEzNjI1MTVhNjc0YmY1M2Q3ZjQ1NGQ0In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Victory!",
            'powers': array(
                "/buff",
                "/flyspeed <number>",
                "/fly",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/tp",
                "/speak <playername>",
                "/jump 0-7",
                "/run 0-5",
                "/confuse <player>",
                "/haste 0-4",
                "/vis           
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 2 true"               
)
