 @plr = player()


@hero = associative_array(
            'name': '§4Vi§esi§2on',
            'class': 'vision',
            'sig': 'Uy3eMcts0oAfBICunPNbXdG87SGPKrwpdO9WmA2er8F+I/yFN/izuHetfbTjFoCj3NrGAsY1RfE3syY5IpzdhGrXrLW9Ola79gKjMxrgp6ZjnZoLSbqHMwb/sVTMJ4XzCNrrhMadD5eX0Y/ankqSgUXqf7sknRZOqwoRLMXuq2NEMn+0BhnfgHgCHU7PV21XIrlU9JV26jca7tbVLWzazHHEyWcWMLjw/lmuNmPhpENZuPOswtnduxLksBJ1bVvFFJVCpIunjY318evv1ZBvoDPCx1iQL5u+qraNFDka5RrxthqGT4U+vJFSQPFJnWvjR7R2GAzMR+PQZ+wMf4bZ7ms2qQWGneNd+SD+otgGFLsCW9Jwtg5lYp4QsIvLE9iKz9tRSWY4SSBJw42D4cW8628GnHFD4G4Egt6KGwNOKaKHNIo1j3U/wYzw3C7TTDmY2rex2rMQFORii3aia7duJktu0oFX7XXWp1CJ0cUtuyOHs0qFCWEa2dgfukQmKoq9tE6IvGmgRC4Maf+du/Wj340qfnFw6DrAbmbjfdmQAdIfb021oo0NTLT0LccLq9y2aPJg2JFXAx2XpJiboZGs4sz5PwRe+/iogtJuSn5N0bTWuhfiGbHXwqqHznKQiyuLvLVwjgoyOVdVZDPMOEwMCXl00+EXwobn9rRELDBLlTE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODAzODUzODQ1NjAsInByb2ZpbGVJZCI6IjI3NWFhNTQxMTg5NzQ1YzRiYWRiNzk1NTNmNjU0NTE5IiwicHJvZmlsZU5hbWUiOiJmbGFtaW5nd2FycmlvcjEwIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zNmViODkyNmI2OTQwZGQ3NzI5NjBkYjZjYTkzYzJjZDQ3MjllZThiZTRiODYzMmRjNmUyNjk3ODI1Y2Y1OSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "that was... odd.",
            'powers': array(
                "/buff",
                "/jump 0-4",
                "/run 0-6",
                "/haste 0-5",
                "/fly",
                "/flyspeed <number>",
                "/thru (intangible)",
                "/disguise",
                "/speak <player> <message>",
                "/mindcontrol <playername>",
                "/stopmindcontrol",
                "/invis",
                "/vis",
                "/disguiseviewself",
                "/confuse <player>",
                "/undisguise"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ." solarenergybeam"                
            )
        )
          
