@plr = player()


@hero = associative_array(
            'name': '§6Vi§ex§6e§en',
            'class': 'vixen',
            'sig': 'I5i1mCC1BpAuX/2ZgoTbylvejhB1nCigMl/5whhWzRCgBGtUGoyu/uygaAoh3yFrrcomGQKhEVKQYXmMi/fC/WAmAu3X4xDtT6KFkf9QsJYfvD+vQ1HrVuwUeCBHsTA2A2LsR04EV3td1P177iVFJw4LhgYVXCMbFUekd60zZOIiPD/MbEjkQY529m8E3a3lGiq1ymSJk+7AZmh2p6LDUMqtWq/HMANXBM47Px9xEcJJJFuZIszJVypcMRVQfUPJDwj3Z+Xi/VlwYni9TaGiDaPKpREbZkaHNljajdsL2dHywj/uVZvd6H9dxCU2lnNQM7/MXyKy0u9PQHm9ASEjSqo5lChF18FrrP+1FlzE11KNCG1HpheiBJsOaa4fulWEc54Z9XxKg6nnb04KUE/8tNbkOYhTYqN7c1b1TLw1YJwEPT8Y3ERLzUw+KEzNfhNUOW61J45DppS9Noe26yAQrpXuAR5Zng0SdP2drWlb2PvkfVW1svKxSwTk8jU6SmW3fGgps3G9/kxTjTqSp/OYez1njm6q38ji72Z90cLzOW1K9GsVSNUN9LtE+5q0UCkg/IP9t1duCfHwU8hlK5L3nZCOxENDK73roneCwAnY/9wlRCVVdEdJluErzEFOshoeLjjPToePZIMzVHyfZn7beaG9UpBugP+uA5i9SaM5KFw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODY4ODU0MzcyMjIsInByb2ZpbGVJZCI6IjU1MGIwM2NkZDllOTRjODliNGVhNDRlYWQ0ODljZTBlIiwicHJvZmlsZU5hbWUiOiJBbmltZWxHaXJsIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zNTFiN2U2N2U3ZWU1Y2Y4YTgzNWNiMzlhYzMyNDI5ODFkNzc3YTExM2UzZjcxM2JjMmM5OWE2ZDFiNCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "The power of animals in my chain is a tradition in my family.",
            'powers': array(
                "/buff",
                "/jump 0-6",
                "/run 0-6",
                "/haste 0-3",
                "/fly",
                "/carryplayer",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true"        
            )
        )
