@plr = player()


@hero = associative_array(
            'name': '§2Vu§al§ft§au§2re',
            'class': 'vulture',
            'sig': 'wynAS2S5JstIFH9RPt+HOdzS/yWVDa9/MOfLxBVkgoSMYi9SjeZBSLSt6Dg69TE3Tk/KoZRLq9N/Txyi+Pu6X2WtVeAQtjcTukRokVsm1QqOP4Vc5zVW5U7En38TSvXLNtTSFDQBfWwrD/2MRz/wTZf9xVmg7E4KsHE5krbKHx6V57igNjrT1EpldNWj3g7D9ctLdwN4D9EtWFxvzk8KYo6u03YMuwomjAvU8D3ik7vg6qHVJfllg29yM+b/oxdEiX3158xXWPUT64hchsgu7KQtnkOJ63tVwnsLh2BgpbAwu5pW7Dy3twgFrqAUCUrC3VWXUXiBIre/27WDQYr4ygUXnetTLimcLXCUX+Wqq/naV7h/uuCTAWr9gydR3umK6u36KKMTNW8m+HybwZoBa4skKONVIhTB3VVAmwhK8k87vaZleNnHv9D/uF+YtR0B7pERdKi8zzO1mm/YUshfJxE0mIO1qPi6vXULopN9Q9wkqFlVCVHhsc5j6lujL0M7HOjNUZlBta3NDpCjPXRTUgF39a5yjbOL//5od9K8rj/v8JVPH65tkGd7MbBeMMid7uRn0P/ckIqyK0OHev5/MmUlyFVUjx2PqkEJkzcyXoSIRdgHScD/4lyH9CnYQrRHs17Q8pU7Mbp8HYGJ6H0cdJrLrgTlPRGwZdq4iscX0DY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTk1MzE0MTcxODgsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTlkNmU0ZWJkMmM0YjFjMzNhNjE1NzQzZWRlZjQ1YWU4OGFiMWZiYThkOTdiYWJmYWY4Mzg5YmEzZGUwMjZlMCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am the one who will finally destroy Spider-Man!",
            'powers': array(
                "/buff",
                "/fly",
                "/carryplayer",
                "/dismountplayer"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." pistol",
                "/give ". @plr ." minecraft:iron_hoe 1 16:40 name:&2Vu&altu&2re's_&7Ta&8l&7ons"               
            )
        )
