@plr = player()


@hero = associative_array(
            'name': '§0W§ea§0s§ep',
            'class': 'wasp',
            'sig': 'QGK6zarGSNI3B3R+wyvG17o8ycgXBKMDpRCEFXXeFN3J1mgoocidVPVMT2Bk8ItG3GNomhb9YCfvBjEonc1Fi69tHn75KH8+qAcK4JOQGbyrn81jutbieEdHLR40BKBDDJdF5BBDKz5NupDnYyoXDFiI2szrIcz1p/zZdby7t4aYvvaMHDxm+iFL3qROQMqO8haIKAGXAmZwo/6h8YjMs1GKOOZS2q49G22wT0PFW3V54cLEGtNGNOe9APPp7GMJ03ACT9tiATRqenpBdRa6RahrFnuRUCjVfNTNnAcVKTl6Ok0SPKxj47P9FVXllJyn/ncM2/0FCEyrjyNMD2I95yv+2944qJW6+hTVeS1UMI+/F4PggC9EkJNFnWJbJ3KvUHQNACtiO9IxwADMjHh7/iVNR/Pk2bum+pEIGU3wu76bhCuJvFbscmxJrt0VYBQTIWeQYS52pthiqhcxaqnx5UspGtIbJvOVpdKbq1/nsz3LiM5PB1GrHp6BwJR3CPo8zMVP+9Hdoeh75+4gq7OO8HH1X7JKaB9w/GNSN+yVTna/oUQBog2w8SzulwKTOXXzqyxTiwEHYlP7+LVdUrQwa7ng7PTS50rkSvSZhlRBI5S8gYP9jCgK7tcO+7taz9RwcHg20M/SWV5yRrJqW0ahWq70JIUG9e1cz+RvOuNmlsM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ3NTY3MzQyNzAsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWNhODZlMzAxOTJhODQzZjVjZjdjNGRjNTE4YjdhOTY0YmFjNGVhNWEyODhmMzhlY2NlMjcwOGZlOWZjOWMifX19',
            'trail': '',
            'op': 'false',
            'speech': "Feel my sting!",
            'powers': array(
                "/buff",
                "/fly",
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 4 true",
                "/disguiseplayer ". @plr ." villager baby"                
            )
)
