@plr = player()


@hero = associative_array(
            'name': '§0We§7at§8her §bWi§8za§7r§0d',
            'class': 'weatherwizard',
            'sig': 'NFGeCHsA9HUXJIQL0IHVyOPnqvnDaEjGs+o/caMEYEgxNaBLDhK4aHXXNjgYKp6Uvz4LkdmTSpwfQAGC8jZuFooI+GBvbPEKKC9WS9fcdD5rvEuQcNnxof+b7CH2RFQYJ819kMvE5VlRKMOI/SgDsqSaoTW7JYfr+WYsF/apHoLec4nT0L27kb/wLopOjAvWWifNnWn9U955X5rLzCvWn7sKi3FcYHuS7TpfbfiPT1Zd44WmaL676X0TvYilWfpmgvML9o3wkLM3lLkwNJoRFZv/sQnFxmG1bgKTv+0kgaaOsRqQh5JUqjgYptajWqo+2copCPmDYAOVJivojYYEQbLwVLFr71KqztExQK00jN20M9UqKk90CmqonJ6U3p0FmLGt2LExp/a8U4xEzJAcSLDOis5cg9hzECjZY47WER7pA1R1vFREfV7x2NHU5/mCbGkeO/PTjv9cQwlBVfs6sE88oXe7bKWYNL08f1TRwndGLt2K0MSqFyzwF2pxrbOA7EqOMGCNkZKXt6B/V8G6+TGFPZ4Qfoahjq+o8Xj6XFw92HOuYZQy8kj3PxibezN9baxtDZoh/lPsoHrJ9Pm2UloFcJ/BgXl8IxRt384ci3L0SgbfR4GOZcwXgpZKgp4cJILBtqQzxCnwmAtrbE/LyyXZazBZv0GiCTyN+Z5J4W0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTc1Nzk2MzE2NTUsInByb2ZpbGVJZCI6IjkwYjJiYTZkNDNlNjRlNWM4Zjc3OTEyNmI2OTY5YTljIiwicHJvZmlsZU5hbWUiOiJXaW5nQXJtb3IiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E4MTRmNmQ0OTc3NWQ2MTg1ZWI5MzVmYTU5ZjdjMjg1NTAzOGYxMWNhODQ2OWNiMjJmY2Y5Y2M0NWUifX19',
            'trail': '',
            'op': 'false',
            'speech': "It will rain blood today,Flash",
            'powers': array(
                "/buff",
                "/fly",
                "/weather",
                "/cast tsunami",
                "Throw lightning with an empty hand.",
                "/lightningpunch <on/off>",
                "/wind <player>",
                "/cast whirlwind"
            ),
            'buffs': array(
                "/shot give ". @plr ." icespike",
                "/give ". @plr ." minecraft:ghast_tear 1 19:50 name:&fWindblast"
            )
        )
