@plr = player()





@hero = associative_array(
            'name': '§fWh§7it§fe §fLan§7te§frn§8(§fT§7U§8)',
            'class': 'whitelanterntelosusr',
            'sig': 'fYksthl3n9zpACn9r23aHFzUk86g5SbQUgi1OTp7wyrTsRSGd5azFf8VfmcSuVZYHqrAUjr22AolLpYmRcP8yiLOXPZFj0fcC67E9REzQSPyLr7tex+OVAMpAlNXIi7ZmBcm0sOnOjGj0WASGII7uHUcmsO/X5G6qRGtys2hYRDjjCSK29TEJaszePdHKnTeajNn5gQdqoFtKtiURT6iMKq7c51+IxO7JcMNDiIKDdQSNjPynavdW8nEcWXKohr7QQ359Y0VMy9D75iq33rPiptgpTcE8eBQUn0itxGC0fOnPrbwvptb3bNgCSHGtiiKCar00oNJeS0V4eVK8J+fuOwfHy45CdtV3ypz7hUPNizcz+MLNkK5b7G8WByS7UYuCL0ii7UYYRC1JmtozhgLAU6g2zujdYG2pc/qXP37eRDTMDJrS4sze32snIFnDwr05XDB6AKozDuc+yAQ5g+cJlMyCE4/s+jMBDLx+233fPR9w93sTPXctS/8Nv0dbGBVeQ12x4apnaT+6sfe4e+wdLSavP8rO+19ZZO25xZ/jCjcaxEt2NImTaEGOhCb4pXwWxXz9dmZnGHeR8zHcOOJruSBcD1WjDts82jRZjutCJF9EARuAar2FFs+uOi7k+eyuV8FOiv6Ou0MLleDAuRprHAkW9ZeIdbrUTqUwgNEV+Q=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODUwNjcwNTQwMjAsInByb2ZpbGVJZCI6IjI1N2E0NWQ2N2RiMDQ5MmQ5NDVjYTAzMGY0OTg1OTMyIiwicHJvZmlsZU5hbWUiOiJCb29mdXJkIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9hZmY3YjVmOWRmZDU3ODkwODY0MGRlZGE5YTY5MjA0MmE2ZGVlNjRkZTE4NThjN2UwZjk3MTdlOWE2ZDY2In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "In the brightest day, in the blackest night, no evil shall escape my sight.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-5",
                "/haste 0-6",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." whiteenergybeam",
                "/give ". @plr ." 95 64",
                "/give ". @plr ." minecraft:quartz_block 1 20:2 16:155 name:&fWh&7it&fe&8_&fLan&7te&frn&8_&fRi&7ng"                
            )
        )
