@plr = player()


@hero = associative_array(
            'name': '§fWh§7it§fe §fLan§7te§frn§8-§fK§7R',
            'class': 'whitelanternkylerayner',
            'sig': 'HLH31nmF1NAIteayItAcWpqTGWLdNiZg9bT9WaqRxG4G98p3rAvfJHKuFsvJmhGO2wDhTZt/0TaRJrHZM9vNQ2rTzy/w7SWANv3JJjBUZ2Jr5HoUGHI7s7eEPOc1yViuzge6x6HjXNzd5F0OBdVxlmPqDGACgAyPzc6GH1zjFwsJWnbeupryd9dK9tuoV638K2RSZ6Ph/v7QH9hEAGyVeaFgV2h1dyYpqkHnv/M5g+6do+EktQ1SHr7Jj6nd7uF5IksGUn9AavpSYoUyZWPQ2UhiZij/kEr0e3dlSZs73cHwNhDbXBYf1nsqiETUhPaFyo9Cv4ZZpT2cuAD9yfy+nAXXkQVqzCI+ZZVEBbVsI3qWnQdxYLlNfBtZOD5+4RCi+V8KU9VAHeBUyOZPHE7lEbxz721ijaeTp75HEFiaEcdp8xouhjW4jzfl1S4lbLe1HR3jUMeLnwwSVv7w4GjnGFXUhiIzjm0VUCmhgLeh013tItlWJD35Llk6zFZYcZwGLb3YvCBc6QbU5RZyjxWol6GtF3UflQlLjXPJJY6DI+j4Ci8y/9oYdPLCcnBt0H+d2KpuzrsvvsNVGDyPRZ+ASD6dGIzhfPquX7eRdJEfF6b3jvOeoP/Rz8zOyHMqQnB191gMiToaisvV8jUPLZfXmrouyDz4CJEr3ubLkIsDraM=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIwNzU1NDA4MTMsInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzRjYzJmYjk4ZjFlOWJjZGQ4NDkxYjg3NjMyYzQyOTNiZmZjMjI3ZWU4OGI5YTc2ZTdmYjI4NmRlZmMzM2NkIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "In the brightest day, in the blackest night, no evil shall escape my sight.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-4",
                "/fly speed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." whiteenergybeam",
                "/give ". @plr ." 95 64",
                "/give ". @plr ." minecraft:quartz_block 1 20:2 16:155 name:&fWh&7it&fe&8_&fLan&7te&frn&8_&fRi&7ng"                
            )
        )
