@plr = player()


@hero = associative_array(
            'name': '§fWh§7it§0e §7Ma§frti§7a§0n',
            'class': 'whitemartian',
            'sig': 'V5Mj/8wG11cjYUq4L6m2fGtMQyQTrDol9NwoqBbMtJOqqBGkbHNiE4z/MNachf+0Hqq9Gbxwd1Zrkc0yS/GQMMSwPzR56tCB+KJBzBQXrmmqnoo/v8+bnRRqwAktNlyQIauQi/u8bnHxnRuKK98dFVRLdeV7R1oXhWbWWHmESsqy2G9swxHFwUQrPE06gCfqfJvmS9ep53M6HAATCTC5B3Qvou9FeA4aqFP1aDLCJpGbrW1OV27S7jH9Ov0d/rxgbE8tX33J2ORWoAkNKy+gQWhHfXYHT8/CYBv0VGzdg4/T6K+QfdXQHCEF3l1a0rzTMLypSJAntLy9JAN7FqKbYtSxmkWBQP2x3PEZpGJcsnEnniAOFLKZ2k/kfSP9w3HHDO4vJBGXw2DZQtovfGMPmFbMooPvKwTb1JtwPxikjrUNDQG1CJncbuVFkaaZu2Z50ubJmj11KKYxo0K2aJveXzeI93lnVYw52c7fsrSQ3+x6qMxh7sMb8DhtIH+vURXA5oZ4Kb8CpQzsLT6SLeHWo/rNsw17Lk4LVUtD1MfAVKVaJXR6Vly4V4hn96lXOPbqeVhTB8vybHoTDGdsotaoAyDROsKfCZo5tTUb92uur+7q8Of1Fsqyrvfn5S0mFza00qHq9WLIgE5LRtFSFTDmbb1DgoWuyQWeFH6JARCi2LQ=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAwNDYwODQzNDMsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJCcjBrZW5TMHVscyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWViZTgzNzYzZWFmNGJhOTJiYmI2ODk4NTU3MDhjMDFlNmM4OGI4NTRmNmYxMWM5ZGFlNDMyNDc0NWU4NjI1In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Some on my planet do not see the whites as equals.",
            'powers': array(
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-4",
                "/flyspeed <number>",
                "/fly",
                "/disguise",
                "/undisguise"
            ),
            'buffs': array(             
            )
        )
