@plr = player()




@hero = associative_array(
            'name': '§fWhite Canary',
            'class': 'whitecanary',
            'sig': 'D/AB5570jJQXEt3wAGXjD2pZr3in2wdI9NFDs2fkscdnXV+rF/KQpoo93YMxho44PTl4f4WlziLYj97fTHxsBBAqcPNeeIiWQtEqQG0vL+bb/jv8wKfP36X4w0mLnrXSmSzdbYZYWuRa5/W+iC4O90mUKLkuI9tdDPTaQAEjGPmh04HQBPmjZNzubWAOS5QmT8HUTEzyrODoc+/w+4t1gluE0TpixKxuVz07Kur5qCHcqdyeuCFwDlRn9lOzLCj2EXOcEoMaaDElPhBLQ4rGElBO5qCmsNadkWIZA9r3FF6Kp6Ta8w6Na3coqF7HU09oQpl5i6pDbY/YxN+ctL7hC0bhxIiPbqQvCuCZXsT1O5mToUjdeNXu76gQIdxhzaaPfMJnaOH0jAllRnpn7KbQVMpJ/3tUhIZ4YZf888hI+mp6GwLOK3ex7Go/I/1GS2o7hRhEhrV/jUQfUM9M280yASaCUI60ns0w7OFM7voylgvw0NnCsQvZSbuLWz+IhAP06/OTrNUKKamzdLIJdpxIOfDC8U1BTQsNScXmQcRqXpK3MVUfggIdzwed47RDbFgpFVu/2n/e0XiTfrB7d0+xKdDHLcI5bfu+Ja4ro2Ru9YWTeNoX4AfTlVElUC+ufNob0LRdHj72CmES2gXZ1iB0qElgb8xn78M3ir0m7L+HxzA=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzUyNTEwNjAwMjMsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83YjI4NmFmYjljYTViODE2MTkxODMzMTE5OWNlYjlkOWU1OWU0NTJmNTUyNTVlOTVjMGIyNjE1Nzg0YzIwIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I think at some point, you just learn to live with a sword over your head.",
            'powers': array(
                "/buff",
                "/jump 0-2",
                "/run 0-2",
                "/haste 0-1"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 21 9999 4 true"                
            )
        )