@plr = player()


@hero = associative_array(
            'name': '§fWh§7it§fe §fLan§7te§frn§8(§fK§7R§8)',
            'class': 'whitelanternkylerayner',
            'sig': 'eFabjTBe2S+AUYb5x/Qqw2FeBzyjjCGGDs1ybIXLPxUEdyZYjVjPxd+ERgmU1iDt5POZTqaNuO3n+gDlNDsEF240GxQxbMb4lo8BsYjCoXq4Glm6BJX2kMIsuOWGwHY5nclKx4UAJsZn51aawgpX6bmxe2UqnuIsFvbhRNFEMTwxz7ZTI/o9zaKwB2IOHoDOE11yG7a9Vz3k1+X1DYZF5lI5frJodIwu+9KavL4SJqxl2x2LvrZkhWwfyzswThMEqSBoxZlfKLBVKvLfSD+9obwGaUe+5QyCi+6EuxkqnPICkhsD8dl72p3S9z2KJ1pkL/aHoihJ38rAMJZZ5OuFELyTVk4zKuPagdmlBUAwMX54BagGgvW0rwW01kh4YWRm8ItgsQ2zKMcYBJYujvEQHgAUF2APuN79wqTtWRZK0MHwMwBtAjR1MuVQiYaSvqPEVF7CEiofSzRbx/R3ZoOIAo7cydxANG2iGENCbrbWWEv1Ba2p6Uow2CLB5ShefUiky3UalnwOvqRACbdzwznonfOz6Amh/p2OeHhe4WehEn++DOdiZE+ANhQIaGNyBI8eXI1L+NIXyEXg/LThSdc+QYTAMeAXvxWRrVx223SpT7ExvPz53maYmPQUnGJKu25I5MEw4ubIiEoQWdvxbDiObd5j0VOyeF7k9DIcT7l1RcY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIxMTE3MDU3NTksInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzRjYzJmYjk4ZjFlOWJjZGQ4NDkxYjg3NjMyYzQyOTNiZmZjMjI3ZWU4OGI5YTc2ZTdmYjI4NmRlZmMzM2NkIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "In the brightest day, in the blackest night, no evil shall escape my sight.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-4",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." whiteenergybeam",
                "/give ". @plr ." 95 64",
                "/give ". @plr ." minecraft:quartz_block 1 20:2 16:155 name:&fWh&7it&fe&8_&fLan&7te&frn&8_&fRi&7ng"                
            )
        )
