@plr = player()


@hero = associative_array(
            'name': '§eW§0o§elv§9er§eine',
            'class': 'wolverine',
            'sig': 'A/v+41l5cjgExm56xMc0lBL+c7ng0/eyizXmCUI0ZuH1MvLt62OZ4g4h2q4iuevUAzAWO8bKbzxeRxjJtecqAKjvKJ1B+Db+IDubt6g9DfBEoUXqmJ/1IQI2k5MVQsHtVe7EEhHIbkfEH975G33QgPNIqV9URv1eVkZtzRkMp9UiU+Y7AWU6zQ7ShSkFGJ4b8PEtXLlsI7OKPaErwC9hDcK8D6MGnxjDmsAEOYQf5htGlJ2szbdxoVFcouyHc028mwTZYqg6NL/LbHhk31segzM0fMSxosjPfDZnl6xfr7NF6jQZU0zDdb9KGUL23qSL1ASIiBqHdaWPkN0DygD7pFyDnkpTej5u2vasAijR2TpjGUEHKzxzPuYunkOt/fo7eVzJryqF1+KJeYEe2CXLZEfj81gKUHLkFDilW6Y2LV1j6cWGq0a44mSGDjNlrXqVwlQDWMqPyMVQ+mEx/L38CafmCKyuE36zxPSwQX5d6GMBHQtsUlAxB1NTEPZG/s4ZQb668T2gJOGgNyTkDgELJrs43hS9rnjgysXRLyJ7J5QP9rH09zdZMEvxCMqRE/8T4/t66FkFC53xSfoIzxfZZTQcgotXS16KcCG5BeK8VtRBSpzciNEENnLTSJcQJVRuFMr7EGcztLwB/CsANKw8MIdkGocGtYOlaX8OEvdsqYs=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTkxNzk4MzYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzk0MTVmZWMxY2MxZWMzZTY1MTE3NWYyMGZjZWM1ZGE0Y2RmOWU2MjZkMzQyYTkzMmIzNWM3OGRhZTM3MjJhZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I'm the best at what I do, but what I do isn't very nice.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_bars 1 16:10 name:&eW&0o&elv&9er&eine's_Claws"                
            )
        )
