@plr = player()


@hero = associative_array(
            'name': '§eW§0o§elv§9er§eine',
            'class': 'wolverine',
            'sig': 'NVfl+GujWXLWelKfCR+9+Co3AMfyY4BJBNEQLQb8emTAvkMuQNTzhisqY8Ayvo2id+C8IiTgLAoe3GskvgCgSK0Z2GM9YUck6gpRFq0GZhkNGDdj4Ob92WTVNqTS1wPdNiNmE56NqBVidjR74ttk16tiz2W9Olsd+MAcCAcAjet3srIKXSr368UPbGNW8Zo7CA2EVyEdJjsFmnWWpPcDUtRKLIY/emztHhdTybPaXXNsPtT/a9znNQWDTzg4wMERKz68LcmpGw8BxL6Dd8P5tw6K/OYw2Mgh98kJbrZGrUxElQb64a0CsO4A8DSySu494ueRsZCszqGqPef19TB1RMVbpV2lrGKgaSQyyy+IimzAt2J4rSD6hQwJcjONIL2yWG2sPR33RJw9jIPe6idVRRRWEHjV7Ctt0CIjN/7r5NHP5yNaQYDMJRwIQUwu1HEwOSwyF2jjZ88wylqczlJJ6sqPYxClbt8sFgElPKAGdl1IoZGCzXGgtD+uM6Nv60egP8A6nw0lCoe5TBeJlnd8Mlb+r5SjsNDrVp28NQImmobNTzKS2xRIB2ZKiv8vIVLVBLKcNcWWpNtbuqCZ8iUuW4ViWVt4JrIiD3nTuTw6MwErCeoxkzHXR+zbUTVLlwEYWYbCml5ll8XsSrnh9D4P0oi1MhZFKlCjHc61Pk5GoD0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODg3NDIxNjQ5MzYsInByb2ZpbGVJZCI6IjQ3NDcwN2Y3ZjhiNDQzZWE4OTc4OWNhZTE3OTE3ZTgyIiwicHJvZmlsZU5hbWUiOiJNaWxlc01vcmFsZXM4ODgiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Y2OTExYmE4YThiYTg4ZjZlOWZmZWVkYTA2MzZhZjhiZWE2YjMyODJmNTk4Mzc5NTVlOWNkOGI0OGNjYmFjIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I'm the best at what I do, but what I do isn't very nice.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_bars 1 16:10 name:&eW&0o&elv&9er&eine's_Claws"                
            )
        )
