@plr = player()


@hero = associative_array(
            'name': '§cW§4o§cn§4d§ce§4r §0M§8a§7n',
            'class': 'wonderman',
            'sig': 'DJp8oDD2nVydp94thJKGUCRSxpyB7aDjjF8JP8xQtTe7F+Yk/qkf16NBIVoKosjT+pNFoigKPQUAZniR0g4AG1Tzx+kKoEoJ1G1960O0MGQ0P04niQjQN3gJhSP/Ui7hbhSD7NwfMLKC8QUOeuVRtyvGUuzIz9DHVjioD3ggaSTJIFIfedjvdKz0aMqTtdxX10xuatikTPVWe/MIlM8ouVNM5m+kqmFthh9ZACJJv7XDY10pTPjb9g7aFy6bPUYsCXYjIfIzlGaLW1w70JjJ5/uSNs9svbSE+vPWWOI+11NnVICfYB3tprMyR6h9JglQZEWJ59qZ1lryPa028jdqauD0vCru6QYqozbkCN2lWVxMTRHcTDZtlTax0QkzeLqb4bneH666sWYOt+qBYTQBBWby7DFPg4nQDfsm+65pJHWI5+9PLVwiIF++HT2UYXdlE47XLTdPjotsZAJYXST1fhq386w2g7UCUNqkXdu7MWsockh/jCMhSk5L00M5nyYLLe7qvDl/Ga8Ayv8Ymhy0qiJ5UiN/aoS7Al3B1bRPHrQJGylTyk1sPJdrg7yH6oxeD8sfaSQl6nYWtIFsZof1n18TB8v/0xkg+hgjqX+dTfnwHZu5tIl1/3gjNVbCkHDha5AMaW41N2z+Efqm/gQs3jkt9JUbmjlFMBIBWA+mj7c=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODY0MDMyNTg5MTksInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS85NmQwMzM4YTViMjhkYjI5ODFhMTYyMjZiN2VlY2IyMjVlN2EzNWU5ZTYxNWJjZTQxZmQ4M2E2M2MzY2NmIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I am full of ionic power!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
