@plr = player()


@hero = associative_array(
            'name': '§4W§fon§eder §4W§fom§9an',
            'class': 'wonderwoman',
            'sig': 'Oc721gxv0yBzVHZq3lHWvxTWne1XFPIqpzu9hqDfS2xe+SvyGhyhAnMx96kY41pQ1TKlUjwC8AzUgd2m42TqQiBH1xsqA4E8yL+3nOJEjiLrZPGEynyU5nFn7dJvk/8keBYPF5pTt5P1VxzWGg/bswZsGlqI6POZoYgVsYwj7W0rpsmwPtsdbTuep5LkYDVa7GfIWIsHs3GIlZwtFXr4oigtsOCp1VESpF57hYc51bB36D0AKAtAXRIk8FnxuWTnN4Jn22OauFa8zmax/M4LwJz+q8B/GdIkme0Nz9hfDfk2ZHPdHwJdGeCpSRGgxEiE5yamCv4L2/3ICbp5fkLSqiS3lqesxN9+6cWCNHbFYdmFT81dLgBGls/eJ7riP3tiu0T/mjHPSwtqTGPdYKlj2gy4nNYYvQftuooi5K2uRTrvxxl5xW+ZdEaK0EH46V95DwMBEfiVaNrcsW0tlDz8I6W7EHzkHoi6uklTNAGqx0tm5bMVU3jzl1xjZ3sokUKftjWBtYrX2uknq3BWYh0DaRJ4N8ousQSIAcr50E+d5SbK36wO2rXL5S3yxx9bWYH5uxncwCM+YvkI15IAMY0TkKlZ7rOsudMcZb5S6lc+bUKM1E4HYWCgSdRbYpEli11LDctVlZ1jX4p5XjwZXIR9J9Vj6CKxn05gNHIf3yT0Dxc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTU5NTg5MTY3OTcsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJ4TXF0aHkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzVhMjUxZGFkNjk4ZmI4N2RkOThhZmNhYTFiZTM3YTYyODZjNGZhNGQ1ZGMzZjM4NjNmZWQ2YThiZTg5ZDVjIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Justice shall prevail!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-6",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly",
                "/back (In the speedforce)",
                "/tppos <x y z world>",
                "/tp <player> (In the speedforce)",
                "/speedforceteleport <playername>",
                "/lightningpunch <on/off>",
                "/cast forcefield",
                "/cast wwbracers",
                "/msg <playername>",
                "/mindlock <playername>",
                "/herotransform <id>",
                "/cast lassoregen",
                "/cast lassopull",
                "/cast mindcontrol",
                "/stopmindcontrol"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/give ". @plr ." 420 1 16:10 name:&4W&fon&eder_&4W&fom&9an&f's_&eLasso",
                "/give ". @plr ." minecraft:iron_sword 1 16:20 name:&4G&fo&ed_&4K&fi&el&9l&fe&er",
                "/give ". @plr ." minecraft:shield 1 durability:10 mending:1 basecolor:16351261 name:&4W&fon&eder&4W&fom&9an's_&4S&fh&ee&9i&4l&fd"
            ),
            'alts': array(
                'wonderwomangodmode'
            )
        )
