@plr = player()


@hero = associative_array(
            'name': '§4W§fon§eder §4W§fom§9an',
            'class': 'wonderwoman',
            'sig': 'DYdVLJxRlDYEQ5T8wkOLXpo2nGB2MeGR/hO1PQP6r31Z1Zc4ybJnBEtLNrWRCLRuTe55JeB5fQZQmDR4g2q4iLJV4tCDBlakRYwcpXptcaUwQpsiZrSNv8f1IoFi/5eP3/f9DKI24YehPpfIJjKBi8EKmXvo3GxScCGSQ3KK4cIjeNBZbSaHakiBEvCQni+9/l6BoEg3hxCEiDoZE/HbMQuZUkThH9aF87SVp7iPa9+AQSopBXqVEfah2Ylp7neXU2bi1lRP3M6HTNQ8aGCCC7Aja15gzJSPa3LLVG/8qi4jW4GsjTDgQOFTtPKfhaZ8Rp93zC4eT9PSVOFnxUNlzGXbWxXK4a/UuK3iWZFLVhpYPGxEEAqQv+DpnyTv1h2B/6Nz+h0CPnk1ZyrLY383oK1xbyN0YhN0QI97SY6wM8GbXmwkM1UIlLfaY2hm6nwwJhcP6w9LE900RPR1hClFdRaY37XwVxyKZHIoGQnq0Gy6s4E9BUmNhinxvL0jEz2f7FdtzqNuQ56YZYbXBgNio803XhotabOybQczeND/DLW5ysou0DY7j69z8FTDhrDr/UtZ4kkHviMrphIiJDBVe3/Db57RA+BH5SrWerJEi+NVRSF9U7ObIsJhp8CSqRuNW9vsLCYeQYDjVduXVH1/5bJwvBFeiIiwgWU2XQADBu8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDY3OTk0NDkzOTksInByb2ZpbGVJZCI6ImM4Yjg4MTMxNTJkNDRhZjA5NTkzZGRjZGIzZDU2MDU4IiwicHJvZmlsZU5hbWUiOiJfSXRzTWVoXyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2U4MWY5MTg4M2EzNmI1Njk3ODQ5YjZkNjkwYWE5Y2RjYTIzNDRiMWRjYWNiNGRkZDk3NDgzODJkZDQxYjQ5In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Justice shall prevail!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-6",
                "/run 0-8",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/give ". @plr ." 420 1 16:10 name:&4W&fon&eder_&4W&fom&9an&f's_&eLasso",
                "/give ". @plr ." minecraft:iron_sword 1 16:20 name:&4G&fo&ed_&4K&fi&el&9l&fe&er",
                "/give ". @plr ." minecraft:shield 1 durability:10 mending:1 basecolor:14188339 name:&4W&fon&eder&4W&fom&9an's_&4S&fh&ee&9i&4l&fd"
            )
        )
