@plr = player()



@hero = associative_array(
            'name': '§4W§fon§eder §4W§fom§9an§8(§bGM§8)',
            'class': 'wonderwomangodmode',
            'sig': 'DuVKNBqvEEipLaq4UEOmptdeRhTBqFeo79247eSVPirJeGKO0qKEOj9FsUDBNwBWDMHQQLCXCVacr9d37EYSYcBs6DZ8ZTZoUcU+/AKghSmYzoQKkDXYil4VAc4bdMSjMr3SeNdtoA6AVr3sT9IjtCJfsddF/U62xieomHBduWG7ck3G/LPiIYd7PEeVEdFKEZeIDG0/ux5SZHkpJ31zI+pL7ThB2XXDGoiY42l3rebJRY3DHos7CvtNOCf4qHG4bEs3wqHSa4dHHfFSL2Hg94d/MKoalAkii1euCGq15HJf9MyvrwQGyEQszaF2gV2V28TmIM2D7Ck6cnD9FWsVQwLIfAEX8tnPexdl2uiM5NfGSoRvEvktSME1493hcp5FuL2ic3AqPRjjoPmOe/CZT3dRumzLBiIvEuNVCfM0rVDxFLeqUtQuVi+z5HD2Obn+dzJ2nSKZBv98mq8Vsi02Pr5LQ/8dWBdnjd7qYbI4xSFWC0nchF9v+QNz6kG4fiai3f9p/Iux4ikUlPlLS6ptkMc3zylf0JU9emhgtQ4NHCbXyv6WBOBdvd/j2bRVKj5agQY0bBs0kThuH+Wg7wRjAg48UP4MpVD261EOBcCNp7wywJD/TUaVxD20aEY7FQI3qn5iQCWHIaH5McLVbPySBcwVMX2R8qKUxftERrkCLRo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIwNjU1NDA0MDMsInByb2ZpbGVJZCI6IjcxM2NhZTdhZWY2ZDRhMDY4OTIyNDc0MTQ1OWMxMmJjIiwicHJvZmlsZU5hbWUiOiJaYXJnb25fS2luZyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2E2MWY0NzU0Njc2OTg1NzY1MmY4MWExYzVkYWFhODFiNmQyNmJiODIwODRkMmY1Y2ViNDI0MmUzMTEzNmQifX19',
            'trail': '',
            'op': 'false',
            'speech': "My cuffs were YOURS!",
            'powers': array(
                "/buff",
                "/fly",
                "/flyspeed <number>",
                "/tp",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." 420 1 16:10 name:&4W&fon&eder_&4W&fom&9an&f's_&eLasso",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4H&ee&4r&cm&ee&8s's_&4Boots"                
            )
        )
