@plr = player()


@hero = associative_array(
            'name': '§4W§fon§eder §4G§fir§9l',
            'class': 'wondergirl',
            'sig': 'OMP66+C2D0Fu6/XYEjJIUwNW6HqGgqoPDsBXN+nnZcIWIk8C7NaWhZz552vXGfK64TjB/m7dfzkNb5MT/VzeJ3oYFLEE3LWXRxT3MFVLeKzgMfJZvnO8CeZi64tKtY3UK05ttNIdben/7RuVW0FMQWR4zO86sZVilRUhEWErQGobTV3FwdTFFeWFsAVwK+hHkGdT2Kzt3MKBgrq9VfigWEDwDnQQjC54wW5jGxIrO23KAtUQk6DNxY0xZ30mu3dIpU0t6zTuaTzIZDHJYB4ITBRUwQGgPZ6aGHu0BnftBXKBGETySKBQev1PiWw/bs/2PnWv7SU4DUCGW+AvsZCWweIT8g5Dd3UN8F7kW7GsLddWuro57iMozmuBV5w6UHcAxM9Dz/c9VPJODmJKJlZEK1DjTCfZtxJLcCIHz/stO1ECGVC1rMvJNFi91qsF5umoWWRpmdUwgy+74PQ5RgTsFlFFk7vIOAMk8s/QJd3/x2A6E2GgWuVpkmhX+7LE5ScYHvI5LnrZWAPNr6XcETK8C8ettzn0g09NsISUs/d1oBurSOQP5m03B2ynprF/JU62QMh+pC0OvDTUASjIC6CV5D30PLRWEa7yG+NPv+LHpLX0a+Q/UBvN41AuTO+PZXoj+UoEOLTP8aNI4SpbTwDklsZaV2ZQEyrDKW7sWWKVpRo=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAxNTAxMDY3MTMsInByb2ZpbGVJZCI6IjhhNGFhNTg4ZmIxYjQ3YTdhMWNmN2Y4NjZkY2M0YmY4IiwicHJvZmlsZU5hbWUiOiJEb25hbGRfSlRydW1wIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8xNTZhOTMxYWNiYjkyNjNmOWYxYmNlYzIxMzQ5MjcxMmU0MTg0NDQ0ZTcxNmE1MjY0NmMxNDhlNDlmMjRmYTMifX19',
             'altskins': array(
             array(
             'sig':'KVqLCsQmxmSnsgt+jgnMRZmmtQgg95hIM5tVHPQlu2SLHTNI3tGmgGU9mRpjYzzLqFlLWLRJHC4U35q/yfObyCfZl5p2VwTcg0X6ofnTmVU+mm2DOo+3+/xDFQ5Am311ISuvuTn4ZjcmCrWwir45tw5Csb5MZI1++F03thePaQzyc969pCsmx6FgfEJWZ0ocCdNgaExyyM8xT6UyxTPLiG0nvYJidY2cf9WugaeM/khe4PEYrANS1LyFgWISQXx+kVVDtipcRTmGe7jAimXYIi6O7m3PDlu1lW58c83kiJXVW3t1kH1VMd74m/wkZjurpG6FsNWM44tAVkaf7zKXZ8wmWfBTcHebPzdjh6XZU1KzGbEc23Pxj1lwUu04huunzkrTD12VApslUXvki74On+R8rmLd7bRWUwSK+Aq51+BgdfqAEZJnAzvkUn6Z+0CeABBOzwRBAWxh554XZUH3C1RwyTGHo8lo/8Fw7HeEo35w8SO68wzQoKEJWWJqtDQMRCSm0SlzsXncQVGEcDJr/piFfwF4Jofm7y4mf6vgtQ2AmP2Wppos5YLjRLlwuPLQYHsxCsU2SW2rRjGxwmFkzsGw9JLMtMxg/MTIgfbnWD5skQRn+unKLRIFVvG9yNJTdSaDn08dT6zTpUAJ8JgFDGjcmsEuMnKSFtTW2f7pias=',
             'val':'eyJ0aW1lc3RhbXAiOjE0OTAyMTAyMjM5MjIsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJTdGFyYmVhcnp6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjgzNWU2NDkyYmI0OWE1MTE3YTk2MTQ4NTA1ZmRkODVlYjg3Mjg3NTRiNjQzY2U2NGYzMzhiNjlhMjhjNjI2ZSJ9fX0=',
             )
             ),
            'trail': '',
            'op': 'false',
            'speech': "Justice will fall!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-6",
                "/haste 0-6",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 8 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." 420 1 16:10 name:&4W&fon&eder_&4G&fi&9r&fl's_&eLasso"                
            )
        )
