@plr = player()


@hero = associative_array(
            'name': '§4W§6on§4der §6G§4ir§6l',
            'class': 'wondergirl', 
            'sig': 'Dbt+I0KMNa4bsfty97d///jkKVGWfxL0nVbrhYJYP/KnUArQ0zfBZF7gzsM5XeoJ4jD8o1Vpcf/a8Ic1JECzkRHyex2Em8hqUjqEyKRLZOAnOzgoq/kD5b7c7dML8vc82FcgrAHxMVw6LS5BONFcuXZojynm4cFYr57TKcj1bpjyPG2Knvxgswil8CUO7j0dFLTLfzRiPIF7ID5H0qSNSP3oP6IHwfVBSw8LSlN2cMgVcVSqpEOzZfekgWU6cCPfVElsbnmOPtsFSPGR2fykE7crhYr4GYDvVGdhDw3H0vu4wEjNNzKOkr8W1CdkIB6Tr7Lf8SzS9hXvRx+z5A/qQNUG/GTk8SrYA5EuieHhqxhatgHnuOo+pF7coG2N38Ixe3DJfuyM3phpyoRV5uqNwTT90AIiJlJIbu+QvjN9vz+UiJP8x+301TtYIbnD6iisK+mRwGhnjHwY6kt4llMYftUgRG8cfMtTGjvjXRQdwVkkoyfgEIFhPT2sKWE2YoAB2UKhLppLqq1DeflUt3hno5YcmX8MMaWZPZ5TJd9ywWBBsCOHWAVTaQivNF+ULo4N6Zjw7WUxRlyKTjx/4hVfQ/xyqwi9ouOTW0FYZeYkO+s8C89vpA5GZ8muYTKS8XTkjE+lzsEgUREXOYRcHja0wu3xkfbp8OM5yk5hy8sH78Y=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODIxNzg3NzE0NDAsInByb2ZpbGVJZCI6ImU2ZGU4Y2YwYWY0NTQ0ZTQ4ODJmZDk4NDQ2ZjRiMzFiIiwicHJvZmlsZU5hbWUiOiJXaGF0QXJlVGhvc2UwNSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzE1NmE5MzFhY2JiOTI2M2Y5ZjFiY2VjMjEzNDkyNzEyZTQxODQ0NDRlNzE2YTUyNjQ2YzE0OGU0OWYyNGZhMyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I have to be a little less fan girl and a little more Wonder Girl!!!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-5",
                "/haste 0-6",
                "/fly speed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 7 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." 420 1 16:10 name:§4W§6on§4der §6G§4ir§6l's_&eLasso"                
            )
        )
