@plr = player()


@hero = associative_array(
            'name': '§4W§fon§eder §4W§fom§9an',
            'class': 'wonderwoman',
            'sig': 'aFYtShn0ssurOM3u+EYDdoa5VNl+4AntNAPXZ+Bc6Thkx4Br0NRaFRvh+jF6D7UBQGeP1gQ/CUVwewnb1GMQFl6CZ9CO9595tGUf28UzS8eCTr5Obt3Vla6CHykiQ5/l979akX/Hm0hFHBQ2cNVBNKIEWEm8XxUjow6JwrgfjhPGADiFITU+x/yMhXd3mD+Af0leHjiMmDZgmxEp0DxWgWM78XcN0vEwYo0vOR4RqBWgGgqrIphUjfxP0YmLzBibUGMOwIgRiI/uShv6eIuXahpoUv33PzovAuGJYVNCh2N6o1kp4vcE7izDtDuuyUDXnW6NyGhnG24wIFGncEwrsWnDEcGfoMdcarCxliYZ4mzdKXH6EPV0MmQBnHgBigO8T7nhXQy+cgXxwisXOqZUOy9zc7lD7vg/BkDqw0OGsqA6+1OfNaQFxtsajC9dafqjDwJtStkYImpm36mtYpJFLwzvOYS/kZ/mKWUX7Jxjjdh/keFR6zOwJMzK1RbnzkTH7VM1kJj9NyhKB+27bri3WUHw6HmS5WoQJLFbH1gm5CyGQzOCjclsoVxPlgUTiybcNYR8+3kWKE/tsx/q+eGuokZMVAN2ga+ohDVOLZQdTJj3htIteHKBTRX4GzYoMEJWrGMo7tG0QwKYvfuzsJt1zzNckygHluwpUT79yBLn7gg=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NTIzOTk5MDIsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81M2QzZjM4ODYwZGZiZjY2ZGQzYjdlMTJkOGJkNjgzNWViNzNkNDJkODk5ZDQ4ZTg4MTU1OTYzNDczMTY2MTkyIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Justice shall prevail!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-6",
                "/run 0-7",
                "/haste 0-7",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 8 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." 420 1 16:10 name:&4W&fon&eder_&4W&fom&9an&f's_&eLasso"                
            )
        )
