@plr = player()


@hero = associative_array(
            'name': '§cW§4o§cn§4d§ce§4r §0M§8a§7n',
            'class': 'wonderman',
            'sig': 'bgwp3t7GiSSYlq9h2ms/CQk9P4zIFiKTr8I69Av6QqMrJziUMNAls46dPSHB6RQFdQjY/it+qdd8Gy4AaDHuMfy8OTfpx4z04TBQ39IZWRjmnRHnV0HqrooBZpILI5pZdWFBkKyfUI6IlD/3BB61PsA+60bndaOOoR/cLmiGUMxoBr4p5rwahxo6UXfDcrMEycKyKKrTaNcTupRKL7ymSk2VtSrloEqZ5yIEkcBj4axpDfDWpWiScvKZEMP05a/VR7OcQYWdVuTtaIvVR1I/nw2ezsZ8T8JKemT8ob8DIjYAwnpUYWfhlVAG2vbx7tE0Itaa/spsgIbNTNPjmPyr0wWNBtMCZT9xL40CgOVAsmWPAPexMo8VnG76D9ZFQHkff1c9k1f8MfUZyo73A6lb/8tYElCrBgNa+i37NzN2OInKG2JogBIgH9XhKZUow2NxtOFUtL8Pla6d1lJ/CZSfc+110rM9I9QzQ+X9fqdUgftT/ZpwG3IreK8lBtwh4Bz1ig4aAPjvBEYJcq0dbZkfYPk8rBVuxpVM90fYjtYdoFSvGZ90TTt5ZuVWqqL6oibh8Atguvx/uWQyAX7gip1uS6QcIkvxaukDEfwUl9+XXLTMUZk9M83MWkG3gi+RNHAcfTLSco/V0N8ca5RlkLbQYnI02OiYYeIdg04uX3ydiTE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODczNTEwNzY1ODYsInByb2ZpbGVJZCI6IjQwODdiYzdmYzIxMzQ3ZGZiZjJkNDE2NTAwMzBiZTQ1IiwicHJvZmlsZU5hbWUiOiJVbHRyYU93bERDIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS84ZDdlYzMyNmIxZWQ2YWI0ZjIyOTk3MWZhZWE3MGZiZDhiOGE3YTJmYzUxN2NjMmQ1ODhhNGQ4ZWNiOGM5NyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am full of ionic power!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
