@plr = player()


@hero = associative_array(
            'name': '§0Wo§nder§8gi§7rl§8(D§7T§8)',
            'class': 'wondergirldonnatroy',
            'sig': 'id/Kcq3UzSEaAXepXNogaJOdD+XASrvrzZT2iwfN2vv8yTwnWQhEXMCiDu18DiWnHz/3HtNJGbrP1fCYtX8ku/SuUPSdeOKztlSWFjM9QfLqQvZIxHvSSi57GhfkQooNaJRj4YIhoYXZpveWGMGPMzHL6p0V7+blMsaV/L2zJhG7u8lFONIzgQLjklom06pSqVITA168qmahpZfhQnMrg43ka+xsXNY1jArllmlEGPn9XTkDTH7WjWcidyUQxMBYi6yPPEWxfQ/RcVlMoe5pSdUhI5tB8vPt6Q9BgpJotAUIrj+JGDlahFIo+Pv6DwXABBJaF67Klc7LAnD+uEqszE8vmzYOyVmMIU0NiYjnonwV/LUmfUKdK70htiMdk+90TLqopB5Zr/WKM+/j32DroPLhyhMKOzfhvYfMRUzj1EBaTqRlwnZfzVEgnOUSu16jOvPm/Nv+uYOy5MZU1BEwt05jwU1Kq4/iPmOFRqq7pq9/5i3lTpWz+4ocnlVp9rhl4ilt2GN6bR9IK+YpI82XQc/fffPT/10mLT470aU/i/Qx/bxiGqm9F3Bn2SVP/qT+GENE8E2DkqIUyB843FwfH38pxWopf0n6xyfBiOpGrZ659rSANziDiKneRk/1/pGG0HPez0MQex29O99yqfx/9iNCpgH1W5G2IegNWke7vAc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTE3MDQwNTQ4NjYsInByb2ZpbGVJZCI6ImM4Yjg4MTMxNTJkNDRhZjA5NTkzZGRjZGIzZDU2MDU4IiwicHJvZmlsZU5hbWUiOiJfV29uZGVyQmF0XyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzc2ZTU0ZDcwNTM4YjFjZWU2Yzg2N2JhZGQ4MzhkZGNjMjg1Mjc3YmVjYzA0Y2U4ZDE4ZGRjY2JkMWIzMzIifX19',
            'trail': '',
            'op': 'false',
            'speech': "Rhea, give me strength. More than never before, I need it now!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-6",
                "/haste 0-6",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 8 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." 420 1 16:10 name:&0Wo&7nder&8Gi&7rl&8(D&7T&8)'s_&eLasso"                
            )
        )
