@plr = player()


@hero = associative_array(
            'name': '§5W§3o§dn§5d§de§5r§3m§ba§9n',
            'class': 'wonderman',
            'sig': 'aHm8ZSlc/hJ+nJlwoY5N77suhAaWbIznsbAav6PIRxb9Ab60gjVoCadPZregB88amUgOiYkGLtccAuhs6hrtFoGLdLPkXTUaw75g0zw/skkl1QPh9qn9WqzBM7NXGkioFYj6HZqSg821vT0xfwnZ+iLuiTWIOo3KK4mVTMpjS+rIhMWdewQfsdpCRP30ZzrFA81GYZ2TL9lGXt9R4hOoDyUmLfF9gxdmvS1rdXUUOE2oKV7Bv9OtVPFRe5SQWwCVpB/OUIHOeWNcBHMu5HXC4wRc40S4FIt37USTnEFt0bC3xPW9vU1AwOXEpKX9sQCF0uc4XaKzMZQcylGR3xoGFGe65Jxgl/We17y7tj8SbCJl3qbBy5Rvnj/bmzv4Y3g6D4bjECOV/GN521ymC4cyxslv0qObejUzeNGFc4pdcK+Gac3OhMfU3P74mvRreyjxLnEpBtMZG3DVkPKdTAOhs9M7or6RoXlVxHhlQCIPWbAkE24XVao4woCPLaXlmeSr35HWzJvr7X+3IB35UO05a0I3EXbeXEL/BIwfucaQHxqxYJLeqASDDhUeO+m514IP3X1z+S3lh5z/mmKdaxPhaGTclHwA6p+1MfU0w3S8dzjkcCUAAAZ1eM10NSiXerqTUvp1B9flI5GxBM+CsEjCf3kJHiTfbOdIEwhLHqk6Wcc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODYyOTExMzY3MDksInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zNTc0MjJmN2FlMGM3NzdjZjYxYWNlYmE1YzI1NGJiZDFiZjM3OWI4MzM1NGRmMTQxNTNmZjY0YWI0YmVmZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am full of ionic energy!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
)
