@plr = player()


@hero = associative_array(
            'name': '§eW§4on§ed§4er §9Gi§8rl',
            'class': 'wondergirl',
            'sig': 'hbv6fkTfz9EwylBbDOgrf3nFlIPc9NeheZafShLbN4/+4aJGxXu9zdUV1fdCSoFMZ36+aSo/hsUFB0QO8TMdOA1bO76JuoDlZDrHx4X2nytxd5DuCHtL4erOAZ+hHzFV3KzhBzVtv+AY5mDAiyzgF9qHm0LMJ89yYcIuKOtqcHHmWVRlp0s0q/dk/1a3d2KzTrguk4OvUCUSxxqNoND3TDJS3j+5LlUK2e8o/3E0e1/xyz7TjomR45AVqkyu4enNlewuLJKfOkEkaPDGRNT2J5p8ljT3bKbxdxv5D1Dbe1l2X3Rwttugb7/B3rqIkciZuQpNtIw1nx7/f5ETBuNJncAFq5ZXq6wwUy1ua1Y9w8PEfbqVxB+oTH2JJSQxY9T53od69lkVm9g6AaTVMg2JXarOF4+Xwb8ZKvKdWxem00L6iiWthLGUKmuptSzF1Fh6XTEHnCfhWfD2CQ0PU98Wh9FsZ9H2VDFFJCtar5TsAv6lB6I+XNkaT3jRMX5jEQgCfmhG7alx0pgEidpFBAoYQk2j0eCCXS7cgKqpZZer/qVeBi+ZF/Z+ME2+2r1z7+DXEjctmx2+NjqZ0BNc2Jy9wBS41sY0WPNBFygpUx6ugjg2Ws0rXUH3N93wtouKH96Hj326qzm3oHCkZPjcJE+cSzWOQsvC3pYduKdcPjpvYuc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAyMTc3OTYxMTEsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJTdGFyYmVhcnp6Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzIzNDdlNzExMzc4NzliZDY5NzVlZDY0NzM5NjI3YTBkMDhiZjM2NjA5MTkxOWY1N2JjNjcyZTM4OGM5N2YifX19',
            'altskins': array(
            array(
            'sig':'oisyBcYRcj+D6szfAzxW5MU4qbPBiEMH95mH/W9ETOHM6kEIUuMX2nAaQ6Rpcx85xXTYYHNAsiTAXjx1iGdIekJA7gPt17srXIjJF8jhYGX37qoNSWt95aoUUjOa9kpSmD5wopXbmDTcB+KqZejzhlYe41gd2GcaZrZ5N/rZVOo9DjPV1kHqxIaPIT1EFZIwTkNqWFLKXRT85fQmQewQ/bg/T7YGfk1tU6wzxZs9SvD6E27ONZB9S9C/QZemCp0/73jFkL5AaIb6+t2cQLnBhBalz2X2Akl4to633pxECEXhFN85XnbKuWiP2Z9mtVRHnlPt0pWQwvqkuLXm+3FiS6wjio2oon+qAkZ69z8Kw6F6LFKpIR69x6bdmrtofDfJyH2yUjNcVKzTBIaVLBYV4AJDgHG6OqkZ5xVL8gBdXdvjl1XnQ70r49a+k6iXt5tSwaaSnilmKJKDfcIUAj0KsVUcGIU0umIsBMbnFKQQRo6OwA+ve1FytU5wz5Oeho5pRoXdmiKmTIV3/iRIGxhmHOGIXyvX0rBZFlNHdgG5Hg0iNPgtmo2p1KzcXpKcC/UIJgt9Md95cMACGO5o2ToKHu2O9sNXQyUI/bV2aZrMeZU+upd0ou416uDVwywpZs9NLYblNAfmdi9++s5H32qu7gDuzk9ukqkchA7+S82fBRQ=',
            'val':'eyJ0aW1lc3RhbXAiOjE0OTAyMTY0OTUxNTQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJHb2RfRG9lc250X0V4aXN0Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Y4ZjZjN2MyNDRhOGI3OWFkZDRmNzMyYzM3OWY1NmE0MTI0Njg5Nzk1N2UwMWFkOTI0ZmM4ZTU4YjU1ZDUyIn19fQ=='
           
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "Justice will fall!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-6",
                "/haste 0-6",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 8 true",
                "/effect ". @plr ." 10 9999 2 true",
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/give ". @plr ." 420 1 16:10 name:&4W&fon&eder_&4G&fi&9r&fl's_&eLasso"                
            )
        )
