@plr = player()


@hero = associative_array(
            'name': '§0Xe§8n§ao§8mor§0ph',
            'class': 'xenomorph',
            'sig': 'pjEQgIIb2RdcNaz4VPz58jsDOoMovlS0W58PfpC/aiQQCMei4obQMcTh09vybyohWu/HbEowkg8BV4Zn24ovNCPosemuPM8rk/KeIsBWeecMbhI29vS9RHcUpUPjiTgSnGv36c6/mVF8erf7nzxNWwEkdBTl0DbItIExJysOrsgv1PQrtspurKWSoo5/k+6MFH6jLe8Kk6tMPVg3agjudxMsMqZEr7EH0sslxta5YRfKclKl0MvQ+n6XrYiF1NtnNOmOWtkKsq7LhsoKOU9ZjhGZ8hy+0QM+cu2NciDoRmJnQObXM2d8HOKbCy+gQOUMj3b7EezbMB3qlX8RmLpzJKJRP8txf7+A09ccnMkYO5hxtPsbUaBnYjpLYk5pyRUNCM267qYHJE8rQoc4Muk1rqPO7q94baztQWVH7Dma1Vtu9Y4lIosiRzyyg1/s8E44FEvju93yZC8kjq0wg/zMIvdyn4h2SqLqlsAYUcbqTnMDczpjT2GcUUdmV3gzT7ntuPuhYREIJOoD7QXQW/Y4YB/6rGbJNTbgM94KpiySQEBTgwTFLasfrBo2+fxgI8OFk6UO2d5No0F0N/N8byTJdgNqHdXmBAHPt6ducrduqzS5yQwm+YMsLWfIOxttxGypG1rhfohq8uKTLyDj2uo69Ir78Ob9W0MBRM3DxmntKyw=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDEwODQxNjIyODAsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjA3YzViYjVkY2Y5MzBmZTVjNTI1YjAyODNjZjY0OGIyYWVjNzJkNDk3MWYzZmNlODE2MzQxZDgyNTM3ZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "HRAAAAAA",
            'powers': array(
                "/buff",
                "/cast acidshot",
                "/run 0-2"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/give ". @plr ." minecraft:iron_hoe 1 16:50 name:&0Ta&8i&0l_&0Sp&8ik&0e"                
            )
        )
