if(@plr == null){@plr = player()}


@hero = associative_array(
            'name': '§8X§0e§8n§ao§0m§ao§8r§0p§8h',
            'class': 'xenomorph',
            'sig': 'H72WbEa/qt3gQ6Q0/Er4rrHlgQmP6Mzheg9RayxJZw2vo0DxhXmnEHInxdEC6nAfpmw5kg1FaU7vZXIlBUZ9ZjJpalnoTAhOhJ9FTHuvDWXz4M+Ek61DDEO5tMBAXpB4GDZB3qtMJ/EXwTrhQhj/6cQj8FYHhaEvK1x8D8H8vqmaBIPILB/9GO2R2u4qRtKEjYapLmIhwLIN/bTiiobYNw3sMh23af1LaxVBuF52tOFjpwzpO5cmiDS04vavyE/WD2u3/dPS1O2iJloEB3/AI2yZRJJy/kU4NJQLvvMQMb3SM4FnuWlR7LcNZI6tYTsmA3NahbhiDHTlCu3s4JqwNZFe9k/yTnk0MP0d9Te/qIx0tPtARVr+dSlN4ZeXWc/zOlMCncXN+KLWfuY/3rfU8BRULNM3CyzVawzcD1bS4GSSIhpfc6iz+dmQxCiMtuU742IRzojjd4XwA4zgt9KZCeTe0PzaFxW7tBCSX+178Yl2KKfm/JUvMVg2ooiovUqnfe66N/TEbdr1GIkmYxtHepTOZPDOwk3TwiSk5f/SnlQFIKtwoAH3chF+BSpL+JVFtmWwjAO7kV0F4ENuwWzAEGMW7IrcFpnP8mH+24WJf+u/V12I2NvGjgS2YfaLrPxzkV+A3CoYGl6k3zT9ovodj9bRW6FqGStsCHd1UToD14E=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDczOTkxNDM3NjQsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJQcmVzaWRlbnRfTXl0aCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjA3YzViYjVkY2Y5MzBmZTVjNTI1YjAyODNjZjY0OGIyYWVjNzJkNDk3MWYzZmNlODE2MzQxZDgyNTM3ZiJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Hssssssss",
            'powers': array(
                "/buff",
                "/cast acidshot",
                "/run 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 11 9999 2 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/give ". @plr ." minecraft:iron_sword 1 16:4 name:&8Ta&7i&8l_&8Sp&7i&8ke"                
            )
        )
