@plr = player()


@hero = associative_array(
            'name': '§3X§fL§8R§28',
            'class': 'xlr8',
            'sig': 'qkOghjh2WW§s5uh93+EisMBRLJjzEIJHz3URxo5aoaBN6aGtoinNJTOSfXGvaBcFvB2VZBiKPyYJJflEHxFVvYBM/Ov3xy7lHCp6vTjkaiu/QoC7SBkDUJEGvR7/8cwXknqsdO28W0uHkfQCsN7iI7wtPiA7wKKG3ZFqRxIXwOg+Ar8DQGC0FuuCQ2cb57ySVNRQhbr+y6wjGIMQMHoYYjmVtapxFQlYCgjM2QaioSA05msvtFSNTIX4EbodyUqe5GtWeVecqe+8ri3D9CQEzvSDozWAalstPdp7RxuP3fly6bxwKavGNCb/xpq1vkksiylY9nugaK5/Gs0SzXNB1gdJOvT5DcgK10ee2gqaok+opBmCB3ujWUVOZRFa+pjusitMjTKuSElGDmgUOyJ2UPHBcXBJ1GE0bFgdEoclxT/I2jfL9nsqmZeOD3fnZJx7lcWDRpoX1DfJz7XedeyOAgBbjFpVNImHhEYliGj0OIu8qEzmaHIVBSug84OjHTflj2Vmu3tXU00NhoO4I6KSC/3WcfU4R57DrhFBgeJ7wNvovke3ehDdp6imlzBcJf3OlM3Y8kRJWiOOPqKG8IrQ/3CfRYKMFcqybTuJEMISwJRwsj6c82gEJVJdoVh9/H4OhgH3CVNjYVJdMQqpKxCp82szb7ylZJiSJcmNAocsPyxY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTc2OTExODE5MDgsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzE4YjFlMTczNWI4Y2QxZjBmNTRlMjM0MmE5OTllOTQyZjM0OWU5MTZjYTZiYWVlMDRiOWU3ZTMwNWFjMTkifX19',
            'trail': '',
            'op': 'false',
            'speech': "Pretty fast, huh?"
            'powers': array(
                "/buff",
                "/run 0-6",
                "/haste 0-2",
                "/herotransform"
            ),
            'buffs': array(
            "/give ". @plr ." minecraft:iron_bars 1 16:6 name:&4Xlr8's_&cClaws",
            "/effect ". @plr ." 5 9999 2 true"
            ),
            'alts': array(
                'ben10',
                'heatblast',
                'fourarms',
                'bigchill',
                'goop',
                'alienx',
                'lodestar'
            )
        )
