@plr = player()


@hero = associative_array(
            'name': '§bX§fL§8R§28',
            'class': 'xlr8',
            'sig': 'KgmlI3Pl7ptf3C17jtgxkEg5eMMAkUYENmfs2JI9JKFF4l/Z/+36gQYskL840/r42X65mVim5NuXhjiTRt9TlshjHyTmHn2Tgc2z9hIecIl38ogJCwZ8OuDJTpA/oL388MMoo9PT8Mya3C6y3Q76qo9EbWahnMqwZsDOgmrF6tobyny4zsRRdJjpMqLGC+fmWvNw9jKZ5BfRPHjKORnRDqpM/h+zZYQC6q3pChP7g3votjhKpxWEMBqjI36WmCWBOHTC6Wr7mP04YquWFEV/FKCT73WtzNUPLDIYo3TXUUcS4zYzOKtF0eGlkp5Vf8uD6yZxYdHIYvwjP71ztFAVuNrb3f8P3hJ1aQ294+cD5o9BL2t8SoE5U8d+FVvn4iynZai0/O+edCbJ2bNJIMO0tr814TkOLUZn1+hGjP4qvS70O75sU6+N3lIQyGf85PIoSw6fNe0JkDvPHfLDxOuV3oJHCmYk1SNXPTM2lhtTzFg0qjLt5+WRdTRmvRdRc3o1A2QIieM056S/Z5t+VMOunL/MEI4JWTNhdJ8k9W1RX/+oGH78AsRN6c/gSO0YvQ0wok/nN0R9t5nMaGw2AaKDHS0hS+cduYSZBTS3TvUIWhR19DVbrC5LjldDgNXVP2gyZMabD9ZYaryy/IHD/vZTJU+7eo9dXpx9XX5DdFRFBQ0=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTc3NjI3MzExNzEsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzE4YjFlMTczNWI4Y2QxZjBmNTRlMjM0MmE5OTllOTQyZjM0OWU5MTZjYTZiYWVlMDRiOWU3ZTMwNWFjMTkifX19',
            'trail': '',
            'op': 'false',
            'speech': "Pretty fast, huh?",
            'powers': array(
                "/buff",
                "/run 0-6",
                "/haste 0-2",
                "/herotransform"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/give ". @plr ." minecraft:iron_bars 1 16:6 name:&bXLR8's_&8Claws"
            ),
            'alts': array(
                'ben10',
                'alienx',
                'heatblast',
                'goop',
                'bigchill',
                'fourarms',
                'lodestar',
                'diamondhead'
            )
        )
