@plr = player()


@hero = associative_array(
            'name': '§fX§0-§f2§03',
            'class': 'xtwothree',
            'sig': 'Df1PCRItGcWNiANeEPgl7yZ9T0WotvWBG8NfboPSMuTclBk+TxK4vGmfmGlhl2DACSDvys9czkyuOoapIHpxK5+zPKiOXQVdMRVBHiEltcHo7EhQYWIR8z6MNnIoMGUB0iIpnimlZkJjNB8sA7n1W7kxGfe001G87iHzrFxvk5Ll8q4HcblazYM8RcOIC0PyUmmAJeSI7gzM2jShkqi3Xwbz/SE7VUgEExlYnX2IO+6K5BMYscvAmWc54HqAFDqHi8iPyFeefjzS4XP5LaFDDx5L8QNkzY1krhFjs3r4u8Oo6yx/JsKYTJbpuRR6ImBpdpguLWj8JaILWsGibExTnKpbT+d1AuI5+95FK6nLyvHfBKLWFDplf879uhqAx2E8IV3uOPQ4wY3+dOsoj1lkw0+1qbLW9rUNhj8C/fZAT9xQrOE/8pZFAJJ4LkkkzTaten1BF+qN1KTbvz9o6gj2NgsmDPFEKH39Z2x2aEEqizitMR4nHXQJjvtcmfuFT70kTAMLjFcvRRlHYlGjPqjmCnW2wSCfoSnwrCWOTqoHZgxC2mvp24E9ZHkWCilJkpntxNg/1dovnkPDj5kIxFpr2umL/dzb99zOP5iSWZniKmR/p3uMvflj8ZA0OuyZsDnmnnKpC8h/t8uay7XlWWn7Bdg5P/hxuUHFc+A/tOjXWBk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAyOTc1OTkyNzAsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJCcjBrZW5TMHVscyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E3ZGQ0ZjdiYmVkMzM0YTE3NWNmY2RjNzJjMmFhNGFjM2NmMTM0ZDFkMGU0MTliNDQ5N2E1ZWUwNzIzNjRmYzQifX19',
            'trail': '',
            'op': 'false',
            'speech': "This is your fault, everything I am is because of you!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_bars 1 16:10 name:&fX&0-&f2&03's_Claws"                
            )
        )
