@plr = player()


@hero = associative_array(
            'name': '§fX§0-§f2§03',
            'class': 'xtwothree',
            'sig': 'Df1PCRItGcWNiANeEPgl7yZ9T0WotvWBG8NfboPSMuTclBk+TxK4vGmfmGlhl2DACSDvys9czkyuOoapIHpxK5+zPKiOXQVdMRVBHiEltcHo7EhQYWIR8z6MNnIoMGUB0iIpnimlZkJjNB8sA7n1W7kxGfe001G87iHzrFxvk5Ll8q4HcblazYM8RcOIC0PyUmmAJeSI7gzM2jShkqi3Xwbz/SE7VUgEExlYnX2IO+6K5BMYscvAmWc54HqAFDqHi8iPyFeefjzS4XP5LaFDDx5L8QNkzY1krhFjs3r4u8Oo6yx/JsKYTJbpuRR6ImBpdpguLWj8JaILWsGibExTnKpbT+d1AuI5+95FK6nLyvHfBKLWFDplf879uhqAx2E8IV3uOPQ4wY3+dOsoj1lkw0+1qbLW9rUNhj8C/fZAT9xQrOE/8pZFAJJ4LkkkzTaten1BF+qN1KTbvz9o6gj2NgsmDPFEKH39Z2x2aEEqizitMR4nHXQJjvtcmfuFT70kTAMLjFcvRRlHYlGjPqjmCnW2wSCfoSnwrCWOTqoHZgxC2mvp24E9ZHkWCilJkpntxNg/1dovnkPDj5kIxFpr2umL/dzb99zOP5iSWZniKmR/p3uMvflj8ZA0OuyZsDnmnnKpC8h/t8uay7XlWWn7Bdg5P/hxuUHFc+A/tOjXWBk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTAyOTc1OTkyNzAsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJCcjBrZW5TMHVscyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2E3ZGQ0ZjdiYmVkMzM0YTE3NWNmY2RjNzJjMmFhNGFjM2NmMTM0ZDFkMGU0MTliNDQ5N2E1ZWUwNzIzNjRmYzQifX19',
            'altskins': array(
            array(
            'sig':'vSj47wiY+muSVWiTQwL4ruyG8OfTWDccm5CbGs2OJJr5ALjlqCuwY7oWpQhVCYdZy/hLLI6cQScJ5oBpkxUQVMkBPFYcukm+3U1nSwvvwyMCILp6zyhxcWYTcbKpSDUbDzm+KRdkr9oD7dEyt2owJ6kj+FJ4KO7iD43w6HFSxt2S9UYa2xHlaXTmqUZb2ZJmOEE1jDhEDqkQcuZyyGFJn4Q9J0AkUWSiUiRhM3JgNcnljCxpxACiHq59OChtnE/ywORnaYelgGGWxR/kC0tcY9+1YCuMnjBRWrjVztI/2V5Z65IqWqHwugIGaWx4kWFayP78fh0iMU2/2W9unxlin+XiFe5o11a6nxod7V+nt2lOtjtD5vnD+MH2djPmMu1UPDsfVPhux1HDKvsXZQtZ1VOn+0tbFeZWf8DjMQr1LPDW5nvV+Pl4Wxe4RMz5367SskmMsByFDpWnR2E+u3rateM8T43uE1ArQbPvQFGpumkGS4pBEuNu2sLiwWoaVJmvuYfHSkI37lDvOwjht5zZy3F8gGmrlIhqC00/8WRlo8fBp/Zk7Dg1xPHkRT1DOkc9BPQNrZNPgJwSP9QZMwhL2Rk5EV0Xw0kUSXlAviJBlMA6mERIV7QMyui8MlZrx9J4TnxXNoiP8DO/WZ0p2aSh0VVuCq+8Kf6T5FzyBIcPFBk=',
            'val':'eyJ0aW1lc3RhbXAiOjE0OTEyNDk1MTA0MDUsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJCcjBrZW5TMHVscyIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2VkMWU1N2Y3YWEzNWUxY2UxOTdkMTU1YTk4NDgyYzhlNGNhZjY1NTk2Nzk1ZWExMDUzNTA1OThmYjYzOWQ0ODcifX19'
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "This is your fault, everything I am is because of you!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-2",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 2 true",
                "/effect ". @plr ." 10 9999 4 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." minecraft:iron_bars 1 16:10 name:&fX&0-&f2&03's_Claws"                
            )
        )
