@plr = player()


@hero = associative_array(
            'name': '§Yan§0g Xi§6ao L§eong',
            'class': 'yangxiaolong',
            'sig': 'rn5IHx+kkRnKvTseIiK9rTJRGuDdMBfqfm3Gz2UT4WiSShdQSf7HwexzcWWUbGEicvOFR2X8+DXPheMDcqSQ+5S0/HusMltYnYerEN+x/4r3+idnDndBL3trkVp+8jmMyVtUnN6oewzmPwySG7GPJUF3o3C8tuX+USwymzsVveHartW+ILnLl0YJo/vNUbcV26CtXvCbRIRLNVy9ktEgihFWiTkARjE/jCR8ezaU7EkA8UcP5z+Pb/aRymgllugoNXsB2NC11njc99igyxjvBF26JqRJYDA+xz/nbj11PX0Z1cnXh16N80XOcUh84Wy2z3mzQJ4LihhWupfw2vJmhbFhAKvnOUS1xGVS1sAPzs96af0D1+ZWWx2FfaH8YcBVT4G6/Z/efR2f57V87fZAOL+jQWxE9qZpAerS6sHlD6pVEitKbpMTc2TGf6WywWGrp1QYf4jzoDwiP7M51CeN2o+4lkWma0LqRmagSyNLVkWlb6NF6AFvVTM42etKrupQr14Y6tSYs8bQ69zHSr2jC3DnHud5BAOHwJpSGaBneVd2RlDHTTP7ilFmV97uS4ZXvCR9vU9QWWjpcUKVzUMmXpX4Hb+pUtYyh3+nPXbkAlJLvOLPmzcZlPdx/owWZxfcLcPFA3G6hegO3Kp0kjauNVlc7dTujF53ezsKlGeQd5M=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTUxNzY1MjAxNTYsInByb2ZpbGVJZCI6ImRiYjQ3ODg3YmZiZDQwZTZiZmVjM2QxMDUzZWEzYWZmIiwicHJvZmlsZU5hbWUiOiJNZXJyeVF1aW5ubWFzIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzI0MzY4YWUzMWRmZjY4OWZhZTYxMTg1YmMxN2NiMTRhNDgyN2JhNWM5YTE4ODMyZThhY2ExYTQ1Y2RlYWEifX19',
            'trail': '',
            'op': 'false',
            'speech': "I can't take it anymore! Could everyone just chill out for two seconds before something CRAZY happens again?!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-4",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 20 true",
                "/effect ". @plr ." 5 9999 4 true",
                "/give ". @plr ." minecraft:gold_ingot 1 16:10 name:&eEm&0b&4e&er Ce&0li&eca"                
            )
        )
