@plr = player()


@hero = associative_array(
            'name': '§eYan§0g Xi§6ao L§eong',
            'class': 'yangxiaolong',
            'sig': 'NVmX0cc9CSSZHXVU1R9A73KDqDySzF+uXl3i/5fB040W82GWIUOF0MvWpBliOE4Wo5wY/w/W4SKuT2QuvjPccK6NOt/JUNu2pTp/hrjBg//52n5Tdz4dDvyvPsF584M7KktPgOd0xzwN3+jTT/5JE2+UJtSQA6APQBMcXIoVSSLuUt/VZc2EJs++nCMtA/cN48oLXoYpQ18HsxEx5sJ+7AOE1mQLjEkJNjmut8bTNtDFNJs433mC28eQKW94GGACk/iong2Fw/8BtGr+TyR9yT23YdIYybAkWgs9KyNF5hLwTFTx/qK6KvPJgc2N5IGpTuskKmL5I+moWnsyaCUMOZ52YWyCmW4kQLNxFWnvRx5CDPptS6JZaAq8JX5rgoUOdKT/D+4yFNP/MlDFHoicJu5t8PRS3cVxVpI4jLqa1CmQoecLa85sd88oB0JydAvcrLDWnXykuxst/nRDp0mDkerKgALjU0lgE4UqrffqJcYeKYea1qr+kN4MHaLxqY5jdY3CU1tRDYihZr11F7t6XGTInprs2vG1yd55LXaSarbyUnZ+ifYLXQHe9HGYTf6OsM7bshm7kkuFm9GyF6QEn5IBDwwVKIxWBts5N5of6RZKWqOFNn1rspSZEiMCtwNhGf2/jC+ep4GfERgmMh4OJ6kDVoqfnr/cJss7V4h6bh4=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTUyOTA4MTkyMjYsInByb2ZpbGVJZCI6IjI4NTU2ZGVhNjY3ZDQwOWZiMmZmZmI0MTc3YTIwZmYyIiwicHJvZmlsZU5hbWUiOiJ4SHFya2llIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzI0MzY4YWUzMWRmZjY4OWZhZTYxMTg1YmMxN2NiMTRhNDgyN2JhNWM5YTE4ODMyZThhY2ExYTQ1Y2RlYWEifX19',
            'trail': '',
            'op': 'false',
            'speech': "I can't take it anymore! Could everyone just chill out for two seconds before something CRAZY happens again?!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-5",
                "/run 0-4",
                "/haste 0-3"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 20 true",
                "/effect ". @plr ." 5 9999 4 true",
                "/give ". @plr ." minecraft:gold_ingot 1 16:10 name:&eEm&0b&4e&er_Ce&0li&eca"                
            )
        )
