@plr = player()


@hero = associative_array(
            'name': '§eY§ce§6l§0l§eow §eL§ca§en§0t§ee§6r§en§8(§eS§8)',
            'class': 'yellowlanternsinestro',
            'sig': 'v40IKnoSCU3xKnbUtq/2kX8dqEW2+08BXLlC5rA2PrlNVuTxj9v0m+dLDV0D/BTZQkS4DKb97e6B/rWw1cgpDBxuNYkeLMrMU7TvHqz+oPF/HV9cAfYOogHoF1GgNiOE8gcsW4KjAWmsIlEvTpWbNqOflhQ58MTgCgwNuNpWY4qAbWkGFa0czGX+ykY3MbAGBRIFYyL04BZN8N/nzoH4awNRTr5XJgkxwHA9oXPYODPmaetbhRi58Z+Qiqifa2jpANtAQ2p/rror9bizOlOM6YKqm8lO1Ebv6h4brTQudqD0xRJvzTyls25glmlhIkVx6aPZSat1i+KdsbOMoTHpSQxa/r+lEp6AC1thh7v3qggRs1DduSyfUGa0UGrFUar8TeV7W500vpD/P1yeo4rO6MzhhVOBSFj9HAM5m5u/9d/A2WFAc/k7RmabbIn0CQIYmw2CqYC02hOIvsrHkmBrRSuH5HccPNWSTnm8hTTp5Rc+klXxdc38XkKzpuJhMfsZHabw0Cg1iF+jkFH1SsMNek9Esd1TrLPs85O3XppIjcC2rwc3tLkdFTjO2L2v/VJAjX6iBPKm9j4cwimeqrUmKwLy1k4+uZBjwBRZObYoHvY+UpcQofgtK8B9YD4fT73BEZX9XucqkUIRxBi6d/WkAYUpZCQQaMaGQl8dY7hUXH8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0Nzk4Njc3OTE3MDgsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzZiOGFlMzI2NmNjNjk4YWM2NGZlYjM5OGNmYTY4YzE5NDQ4NDU5ZTg1ZTM1MTkyNjgzNzk4MWU0Y2M4N2FiNSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am Sinestro! I'm evil or some shit i dont fuckin know",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-3",
                "/run 0-3",
                "/haste 0-4",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 15 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." yellowenergybeam",
                "/give ". @plr ." 95:4 64",
                "/give ". @plr ." minecraft:gold_nugget 1 20:2 16:155 name:&eYe&ell&6o&ew_&eL&6a&ent&fe&ern_Ring"
            )
        )
