@plr = player()




@hero = associative_array(
            'name': '§eYe§ell§6o§ew §eL§6a§ent§fe§ern§8(§8B)',
            'class': 'yellowlanternbatman',
            'sig': 'aAFWMIifmX0dGNPG7Qu0dvW1w2g8oxs13dOnhkD/WgQJLtfD1PACfkOPzhroh/7aorztUOJTS/DqZOP2MDTcGneK1oxWMuGJzjCa6STrgaWWTlH5sXwaUNKkvkruovShBm5qgJQpYW7ZYYnQD6RyVWdgJXF0jqW5gkbI6wpsZvtU3F7T3iQgwiTY0/pLndj3ujk6rbagP4JDVfU08mk7A/wZkOjCSIH+nrPqjJ9/0NTkv8OF14EhaWXSvz1x4l5zycWXTS+ryItX95qyH5POeUZnYwu87Y1ikyxVLV8RjWSPzqI8vEgcU40LfpwoYY9XxYNHmg+TNbGyFnhzydd9z6pfrwebb7i+rg2BfzzMRBP2sKN/pc4m3WxLEG96GqmjA6aUIfrUOJyF5MC/31gegktN/HuWFyhLVuBMZ7NCs29YNRFzJcwkNDc6asE5V3pH8k3H5wV3zrnHxQ8mNFJgKzO+WQTet/thwm6nVjL7OdmntGY37t1XPS0mgK6HpBqNAx7RCllRBeTrsI/VBDsjiiXrbSMS19/8SlswWeku1Ia0KlO4eNozMUEvzS2N6iwVOvweTpkRlSHZ5BCuyKc9CzvlMkDq7lc0f6Gb6ETyiP8dzJXbxjR23JmCNgEC4dmbAKfHjRgRbRJhlm9uFotSvcC0DYJ0G0eNSARbc2iNKmY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzY2NDYwMDUyMDQsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2VhZTMxNDRiMWFhNDFiODU4NzU2N2I4ZGI3ZWYzMzE2ZDRmZTE0MWZmYWE2Yjg1MGQzNDQxMGQ2NWM1MmIifX19',
            'trail': '',
            'op': 'false',
            'speech': "Beware your power.... time to beware mine!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-8",
                "/run 0-7",
                "/haste 0-9"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/give ". @plr ." 95:4 64",
                "/shot give ". @plr ." yellowenergybeam",
                "/give ". @plr ." minecraft:gold_nugget 1 20:2 16:155 name:&eYe&ell&6o&ew_&eL&6a&ent&fe&ern_Ring"
            )
        )
