@plr = player() 
 
 
 
 
 @hero = associative_array( 
             'name': '§2Y§ao§2d§aa', 
             'class': 'yoda', 
             'sig': 'JTentysYSgzsFCeVNoyDJbleXQIcFbpoIfQPyLbBCiNiazVjhhwi1xPBiAIC/DfLM63MX5kskk2vsBJxnua7khl1NwvsX6N9uB1ebt07tjvTOBgM1zVaMnb9lkRQz5qCG6WytrEKQ14OSPYxFLix0NsfbtWscePAcMVGNBYxd/0zN2PTEAEaqXdTq51Q2SHXXHT1+JMQDwJSz10LFi3vdY0UCc4UeQ5RNBTRk4OPGpULfAkWHEWmkzR421b8Y4sXIO1uG6O1y+xCYuKDPgmOg3aUUOOYj0iTqwjuwHZyLMMmndl3G5oc60K7Ay8YTuGb4dtr6qLEs4dWzSbDxmJH60nGc83cg6t4XXiUX1OHi6Gfkv1WTFJt5JPjHIm63LrN9jxnvESk7K8dGHeqUpgKbX6HnlfDPKain6KPUcKJ3oirXqYCJysXQQyApkkp9lA59ibXkjLQTak8veEbsvWJwb0qH8Ff/YGx4ElN/HKDr+ctdby2TwIt7xrNRn2zA3W0VgyiCIl6k7ZlAUjq8QIVQv9L/2ySHFi513d3z7k/N6hrGhlBchRDVw5eYXyCh5jA+Bib3jDXcUbR4rBobMcJLlIQcirKJdZ203MyU0CUhu1msyTYbzr+Z6/Gq68n7mhRu1giHJsDD93ocqD8rg6F9+9BXL1VBZw1J40iTGK7rGE=', 
             'val': 'eyJ0aW1lc3RhbXAiOjE0OTIzODk2MDk5NDgsInByb2ZpbGVJZCI6ImY2MjE1ODZlOGVmODQ0OGQ5MjY0ODZiNjEzNzUwNTJlIiwicHJvZmlsZU5hbWUiOiJteXRoZ3V5MTIyNiIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjk0NWQzYWU3OTUyNmY1NDliOTVhNjhiNTc0YmU2YmNjNmNlZDA5MWY4MWQ0MGM5YTFiYTgxZTMwMjYzZCJ9fX0=', 
             'trail': '', 
             'op': 'false', 
             'speech': "Do or do not there is no try!", 
             'powers': array( 
                 "/buff", 
                 "/jump 0-4",
                 "/forcespeed"
             ), 
             'buffs': array( 
                 "/give ". @plr ." minecraft:iron_sword 1 20:2 16:100 name:&2Y&ao&2d&aa's_&2Lig&ahts&2aber",
                 "/mgive ". @plr ." yodaforce"
             ) 
         ) 
