@plr = player()


@hero = associative_array(
            'name': '§fZ§0a§ft§0a§fn§0n§fa',
            'class': 'zatanna',
            'sig': 'dh5cyv85pIxjJ7gWt4mtd+9qEK2Jh+i35cnylD9ySBihVnXZxJk14f3oCOau2O3iM7I5CeYtK7N7R2de16acisiLECDSZgBGtqVwCdlnj2tMXlGgXNV6EcOE0WUkckDFOm1rUzLO/zv4rKbuwtQ1jGrL6h4DDNVdmnSG99sJR9iJOoeB5ry6pLXznMwb1K53j/Ovf+VlHN+6M6YM5pgpOUoVLBa4xx3hLMc1T6zAwXiBgPj8cIxllCX/fzVSGSUEYvBKysak8qvAUHxRQvTWLyWm6FjtWNBNRAqROnxd52zpjHBM/VBher25BmPr3OIBUEUoKDJKCnkQ4z1eq0Z0qSzzElDFBC3ChU9c9cpOjsWuy6kHB1xCm3ouSPIw6GtFmu16dpaKUoQW/pcgQ4kxfrDl9igXsuAE3JQ62H08gkSLbZ5bep8WecVJgpnNpOGoZyCvlgdVjSxX/oEqTWPTf+HTFwVUs5T0g3w5k40RcdzeyFeoQ3pCsZH01B5jSqbUY3tgYQTgKsrkzaQJ8VPjS9/mDht4pqtazjvElNSrSAA+yCXKYl+QLFnjVxYR1OAj+0DzuBc7XmfUXh4dFxeIELPjq9qfSuWZzQEZdwleVTxxFDSzksFpxlPCsDKJL39bhmhTtevtLyeiaEOKcBkN8OJmBJJoVk1j7UTimzV532E=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzM4MDk3NDA0MjMsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80MTEyZjg1MGRjNGUyYWQzZTBhZGZiOGQxMGQ3NDJlY2ZhZWYxYWUyODNkMGQ1YTNlNTRmNjVjYjkyYTU1MWVlIn19fQ==',
            'altskins': array(
            array(
            'sig':'F71uiOquSv1IF7d0VBZnEVuyfgm6dAys6qRNfkdyJ3nmgRQRSf4MaUronLozQQDKM5UMZJ0FdMg4kciw83OoN1dKyHOdjjDzd6rexWWZ99baaXivv1dGRCw8OBbQPkc/1ySKg0NTp6Pbycn6eREkCAwIJ9EenTxqsgvzqG5ulOeyqjvDsY75qr4fd9lwYhubxj/N0nt9zY21G+20ZkSsh+7c9Ou7RtM7rKkVKHhzS5MDpYH4fVV36rPRCfjfEAVJr5/gn1jOHRY2MEFJzhv/sPRFmNB8QAhk5lxNuhO9ljoKQ6xEiivtIdYcbker4QO2vUBIG2vfpKkPkb++5hzqQZM2uULUwG2LjznoTJ4oz6859KW8auB1yIlRuaz5VteipERWMufhfqPQ1OjPzFpBz32eTDbAfffkCvCcRmahSg9ugHt7wH/IB+ImAiuYwgO/yXU+aqKlX0ovZR89QHHZo+oMG61mnoiRsSKpA9vhax11qDAf16YzQ06jA58lPiy+0/FAySI2KqDhQf9M4BVXHirH48RP61pzmV49bvqpjDcjxbEM18oXI8E55s0bHCy5AUBdyLWhixAQE3zQhspCiriuRHzi/qwd2GjdWM3DNLnhPSyU5NC4PYpfZuIhsd5NxJl5YjpJjTwl8zEyyG2o5Mt98ZMP6J9o5HjhOuz8rRc=',
            'val':'eyJ0aW1lc3RhbXAiOjE0OTQwNzc2NTU5ODQsInByb2ZpbGVJZCI6ImZiYjhjMDcyNGM0YjQ5Yzg5NDhiMjZlOGFkNzMwOTllIiwicHJvZmlsZU5hbWUiOiJDYW11bGxsIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTk3MWQ3MTRkN2Q5NzhjY2U5YTRhZTliZjI1ZmViZDM3ZjJmN2I1MjVhYTQyMmM3MTM5MTRhMWU0NmI2NCJ9fX0='
            )
            ),
            'trail': '',
            'op': 'false',
            'speech': "I like Zapata's!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-1",
                "/haste 0-1",
                "/fly",
                "/cast emoksemocebadlofdnilb",
                "/cast erifnrubnordlaucelbbub",
                "/cast dlocdniwwolb",
                "/cast etaercsnoisulli",
                "/cast tekcajtiarts",
                "/cast mrasid"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." magicblast"                
            )
        )
