@plr = player()


@hero = associative_array(
            'name': '§fZ§0a§ft§0a§fn§0n§fa',
            'class': 'zatanna',
            'sig': 'dh5cyv85pIxjJ7gWt4mtd+9qEK2Jh+i35cnylD9ySBihVnXZxJk14f3oCOau2O3iM7I5CeYtK7N7R2de16acisiLECDSZgBGtqVwCdlnj2tMXlGgXNV6EcOE0WUkckDFOm1rUzLO/zv4rKbuwtQ1jGrL6h4DDNVdmnSG99sJR9iJOoeB5ry6pLXznMwb1K53j/Ovf+VlHN+6M6YM5pgpOUoVLBa4xx3hLMc1T6zAwXiBgPj8cIxllCX/fzVSGSUEYvBKysak8qvAUHxRQvTWLyWm6FjtWNBNRAqROnxd52zpjHBM/VBher25BmPr3OIBUEUoKDJKCnkQ4z1eq0Z0qSzzElDFBC3ChU9c9cpOjsWuy6kHB1xCm3ouSPIw6GtFmu16dpaKUoQW/pcgQ4kxfrDl9igXsuAE3JQ62H08gkSLbZ5bep8WecVJgpnNpOGoZyCvlgdVjSxX/oEqTWPTf+HTFwVUs5T0g3w5k40RcdzeyFeoQ3pCsZH01B5jSqbUY3tgYQTgKsrkzaQJ8VPjS9/mDht4pqtazjvElNSrSAA+yCXKYl+QLFnjVxYR1OAj+0DzuBc7XmfUXh4dFxeIELPjq9qfSuWZzQEZdwleVTxxFDSzksFpxlPCsDKJL39bhmhTtevtLyeiaEOKcBkN8OJmBJJoVk1j7UTimzV532E=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NzM4MDk3NDA0MjMsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80MTEyZjg1MGRjNGUyYWQzZTBhZGZiOGQxMGQ3NDJlY2ZhZWYxYWUyODNkMGQ1YTNlNTRmNjVjYjkyYTU1MWVlIn19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "I like Zapata's!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-1",
                "/haste 0-1",
                "/hover on",
                "/hover off"
            ),
            'buffs': array(
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." magicblast"                
            )
        )