@plr = player()


@hero = associative_array(
            'name': '§fZ§eeu§fs',
            'class': 'zeus',
            'sig': 'RBSeUkE0yh4MALgfnwOeDzCzyaw37UsawF4rDwKziTO7fURV/NbmKtFPBW2dkn7dcgGswb0mQb+AEGB5YH3V30S0hgPLd6O6Bs4CiH6s58zxnUeqiVbdTLv/GD6dxQ/COV15hKR6yYADcTcvXd72bYhVJ+bLWiDZqtZpjJ+UZQiuQEfN7wGjgvBBQG/zxSs6Zbzk519ZBR9Gpq9B4zyYHxTLD3jemjrGaMJrUoS9XaljEj8cZydgZ15dckWMn78S/Jygt3Ync2BprP9rGdk2TFUcacx1pRynSP7EntBBIBRnrS+walaMbaxhDRZiV8CDqOhxHmVhnrFWd8j1YmydWxDUlRgxr7LzIXPYuyEljtkIKaEkXb31ytHnSAAYXcRoh4uakle8ItHTs/00TwYbYthJHJ3Pz9e6FaXmoO4us34yiBgE1iBLW1fyjPa25U2Oye4RNXBVsRP3rT3cX9V48+hyJT7MjfsfXyaaQq5iaeltpkyQXzYgG+dCtEzO9QNy7+xDT6h5dUS4cLR9qNyI8qhNujYF42bZnBrZ2urLtltuBiGJr2HnV63LdfnJGjTdkN63ZYT3JaVp2+faZncrKDS4W4ONF3D0Uho1XHTEijnR4AeX21TR4zEaKMS+NoltjUOriL0F0/Fh7tXXncUHszyRZbzQhmAExvb2da6VS5M=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjUxNDY4ODYsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzhjZjNmZjEyMTM0ZGQzYjNkY2QxY2UzNmY0OTI0ZWNhNGMxNjhlOTU3OWYzZWIzMjJiNjYzMmI2ODU4OTIwMjUifX19',
            'trail': '',
            'op': 'false',
            'speech': "Zeus Almighty.",
            'powers': array(
                "/buff",
                "/lightning",
                "/fly",
                "/run 0-6",
                "/jump 0-4",
                "/haste 0-5"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 21 9999 19 true"
            )
        )
       
