@plr = player()


@hero = associative_array(
            'name': '§bZ§0oo§bm',
            'class': 'zoom',
            'sig': 'RuP/oK2EqxOla6NrkgmCnPwXPF6C1f6xpegE8cUBM/hZsZzqztcRgupKiTFwcAKWcKbdan/C6iPiVzsv3pxRBXt1S3PjMVQcsF/KsG03UP43Au6SCge+vxvLuOpeCeYj8SdE7ZbzRTHsLdjnREdqnpt0ENSUHkww23bqI++uYqPXwiYV3S6a3KFrj1rDXzFOjC4FPEAfsyRogkAhImpeQpQxDlMT//HyYoIgEzZMIdSHyNEcORwJhoMdjzz99xD87FlDZ7HpkC6ovu6TRxQFtRrt6QLPERDJgXA/A+R1Zz76aLej5SuOIWmnUSH3joK1H5ykCaD1DLsLsBv9fuG4KYRfib6tutDux+se0CCMyrFl+m40hGXb1ssu7WkMcPjyR8gGERrkWCsaEA4+utvn0Vonys3t5hkjwDQJMg7foTWbgRH38pzBSghOXxvXGiOZtaA0QX+6hKjkRh5oJJISHbrAs2Tg35QrrSh+jJfiioOhyqNG+DBt7o7HPtg0ZGxfh7UWIR/h+DpN1tvqzV21+oi+nAa8aJAAZZ1T0VSVhfeMOXG1ies0zBMn0taaUL6jLGo4mCjnEnxDBZQbCL4iDtxUd2O0CoQP3Hwh0aeBytPE1WiDNBv7KleeoqSjzjHCH35oLngeeMnsItzRH5AY1fSP6zRjeEPbS2sL5rH941U=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0NjQ3NjY0NDE0MzcsInByb2ZpbGVJZCI6Ijg3ZmIzYzZjNWZmNjRiZjZiMzI2OTkyYzYxMzdlYTEyIiwicHJvZmlsZU5hbWUiOiJUZWt0cm9uaWMiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Y0YTE3YTUxNzA0NjZjNTRkZDY5MTU2NTFmNDViNzY4YjBhZGQ3NDJmNDExODlmMGIzMWI3MDdjYmJkMmQ5YSJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Zoom!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/back (In the speedforce)",
                "Access to all warps in the speedforce",
                "/speedforceteleport <playername>",
                "/speedforcebuffs",
                "/whirlwind",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-9",
                "/run 0-1 (In the speedforce)",
                "/haste 0-4",
                "/thru (phases through walls)"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/effect ". @plr ." 10 9999 3 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
        )
