NotifySilentChest: true
NotifyAnyChest: true
DisableSaving: false
config-version: 2
notify:
  any-chest: true
  silent-chest: true
items:
  open-inv: STICK
toggles:
  items:
    open-inv:
      87fb3c6c-5ff6-4bf6-b326-992c6137ea12: false
  silent-chest:
    87fb3c6c-5ff6-4bf6-b326-992c6137ea12: false
