Configuration_Reloaded_Message: "&7Configuration reloaded."
No_Permissions_Message: "&7Sorry, but you do not have permissions for this."
Check_For_Updates: true
Check_Pre_Reload: true
Generate_Resource_Pack: true
Shooting_Cooldown_On_Change_Held_Slot:
    Enable: false
    Cooldown: 60
    Message: "&7You can not shoot yet!"
Break_Blocks_Update_Interval: 40
No_Attachments_On_Lore_Update: "&7No attachments"
No_Skin_On_Lore_Update: "&7No skin"
No_Visual_Reload_On_Lore_Update: "&7No visual reload"
No_Trail_On_Lore_Update: "&7No trail"
Update_Lore_Cooldown_Milliseconds: 10000
Update_Lore_Stats_Bar:
    Left_Color: "&7"
    Right_Color: "&c"
    Symbol: "░"
    Symbol_Amount: 10