@plr = player()


@hero = associative_array(
            'name': '§4Ar§cse§4na§cl,
            'class': 'Arsenal',
            'sig': 'WV06sdT6KN7J3W/051ZWeanvY6T8GRcIwVt9PlzixUsbeokcwC/zOikaguSskc7b7fDCocK/zQ+oiFI510myh6CMxJbr/LM6bw0kz7mbqYYpow/BGEgXsWgKSV8bg9vjieD9hf11su3j8agzSUSi0+Z3mmEGtd6Qegly68j0wrzoYZQwl4NXrjiDbB81lpbRpsOo4Oc8qk5VoHHG6oHOAW6Ubwnz4gP4GAWKr+hoPgdXr/t1PMeX/zEYZCRFRh33TvfNs4NjQ2bjAyKaRXp3bd5zQIkfYblramON4lzFf/w6CUGRq69w/xoahuLFd4V0MNGOj5xhIuy+ePO/9gs/po6cUAWwQWLuTia4qPHE6X8vbSQZGI4YiDn/IIFvPKtAdV+HBO3cx9ramgIHNAukNNWe2FWzmaotopFoGNduXRkz7HX8KwmTtuhkzbq6huX15Gx/2tVxkF9GyJBw0TevIhNUTg3YXez8uqSMfvhe9Xle+8EiU9qk7RFpQ4VfC2BgzDab79dHqMtcyD4szQW4w9G8mKgz0iUuIAURn+jkN4vgxZ0fB4+gYl1Wq2zGK+KJfugcZyESgAkJo/JKY4XBUYRtBISHUvtPjwE5FRqGcl2fY2bkCKCw32959VdfGcVbTEMYSHLLNsjpv5McP6KMPuNKmIy802I6bFlpCoDiSOE=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODU3MTIzNzQ4MjYsInByb2ZpbGVJZCI6IjU1MGIwM2NkZDllOTRjODliNGVhNDRlYWQ0ODljZTBlIiwicHJvZmlsZU5hbWUiOiJBbmltZWxHaXJsIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zNmE4MTdhZmMxMjNhODhkYTQyN2YzMmIyZGEzYzdhNDU2ZDYxYzFkZWMwNDI3YmU1ZWI4ODcyZDAzOCJ9fX0',
             'trail': '',
            'op': 'false',
            'speech': "You have faild this City",
            'powers': array(
                "/buff",
                "/run 0-4",
                "/jump 0-3",
                "/haste 0-2",
                "Give's an Bow and Arrow",
            ),
            'buffs': array(
                "/effect ". @plr ." 1 9999 1 true",
                "/effect ". @plr ." 5 9999 5 true",
                "/effect ". @plr ." 8 9999 8 true",
                "/effect ". @plr ." 21 9999 14 true",
               "/give ". @plr ." minecraft:bow 1 20:2 16:100 name:&4Ar&cse&4na&cl's_&4Bow", 
               "/give ". @plr ." minecraft:bow 1 20:2 16:100 name:&4Ar&cse&4na&cl's_&4Arrow",
            
