@plr = player()
 
 
 @hero = associative_array(
             'name': '§5S§0a§5s§0u§5k§0e',
             'class': 'sasuke',
             'sig': 'M5X6oLQfQwmOwP9txP6IZUSGaIjCS/VlXsCJobBwwFSc+RvpaAmYgBImf5ofhHuEbI+iLjGqG5Q+mHTdIp6KpUUI4IIgcUM99pVi63x2Z7MO/oCt+4Dbmjn7w2xavW9Yx8HPKujuKlR/CAACTdRsPdaKngiNG00BEM3LNjxjsAliM/oZD3h4VSOdbKgAhZvIy8TXUaxPqIyLaUxJ/OofTCoJzaL6ylJzqVH8Io8PlKDIgXyPG64+sSJFkmSXWOC0LRR5wDUaYAkvYZHniHU2bVAe47B5BieUeIU3MQPgD3Dnq/NzSrIChz5ej3iDTcmjVjt9BuWyXrAPz2cTFPUXD+cR5SF2XBCJsu9BHw5BFblKsdo6LWSzl7H5ZDdFQaREdqPJ2wz2wYglKEcyHcylgE39Dn5LVfOTR8JVv60ox6twEjgNtcrwaAUjaPmlRJShy/k4KcZtzTPkqVN93xRTNKYAjqU5IkcAdPI54Azb/Ttr1rm4WhR/PT4NjrYlx0lTSatp2yFEsl8rfcsgNuEee+8umJh8thzVgKGUrcN688t4PyTMBGHh4LNB71Ubwyy5GLuuUo0nNb/G0LcKKuguKRRXrqk1jCZHK2AsVjQWouGKV2QnLphnR5xbpI1Rcx3FzHhiti4H/I9UtyLboqnMdnKPK+6BwQAphdA4fChzL/0=',
             'val': 'eyJ0aW1lc3RhbXAiOjE1MDkzMDgzNzg5NzksInByb2ZpbGVJZCI6IjRiZDIyNTQyZmM0MDQyZGViOTRjMjAzOWI0MjYyNTliIiwicHJvZmlsZU5hbWUiOiJzdGFybG9yZDIwMTYiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2YxMzY4Y2RkODI0NmM0ZjNjZDFjMWNjMGE5NGQ4YWZlNWY3ZmM3MjM4YjE2ZTQxNjIyM2IxNjg1NDNhNWZhOSJ9fX0=',
             'trail': '',
             'op': 'false',
             'speech':"I will kill my brother.",
             'powers': array(
                 "/buff",
                 "/jump 0-6",
                 "/run 0-7", 
                 "/haste 0-5",
                 "/mindcontrol <playername>"
                 "/forcechocke <playername>",
                 "/thru",
                 "when you punch a player empty handed, your victim is stuck by lightning (force lightning)"
              ),
              'buffs': array(
                  "/effect ". @plr ." 5 9999 15 true", 
                  "/effect ". @plr ." 10 9999 15 true",
                  "/give ". @plr ." minecraft:iron_sword 1 16:75 19:9 name:&5S&0a&5s&0u&5k&0e&5s_&5K&0a&5t&0a&5n&0a",
                  "/give ". @plr ." minecraft:iron_boots 1 9:2 name:§5S§0a§5s§0u§5k§0e&5s_&5S&0l&5i&0p&5p&0e&5r&0s
                  "/effect ". @plr ." 11 9999 10 true",
                  "/effect ". @plr ." 25 9999 5 true", 
                  "/effect ". @plr ." 21 9999 9 true",
              )
          )  
