@plr = player()
 
 
 @hero = associative_array(
             'name': '§5S§0a§5s§0u§5k§0e',
             'class': 'sasuke',
             'sig': 'yYYS3qlAtSiMkW4UpX/mVT0G7WPRX+J09uVbTXiSNWul2vEszoM7wVtfaS0OMZjeFh7f8nnF1KtlAxHZ57vEaPtNWWMo7Z+p/1AdeE2Z2xPOsOhSI5FqCRcVwAwfH4+LpgJRhCC0AVF5TjGjBEv9A2hExOEAQaG+OqaeIzhYJgEbNBH+JIFRgMWe3Idr5vS2De2wXBHYJFyp1Qs0gp/lJBkci6zXqCcxvMMFiygNQSFFBE7uqTAkDBM6zbEZ47774AXKpPR2k+4GaKYZfQ0mmVV8zYLTrTohRa9fth5mwQ74H80aywsb8dloTDBSbZ69YYUFmmK6M8vlfk71CRI81Jiy8JeH3Wl66Zro4iq8dLV40b7+w2zT4y6IKVnGNvHglt1UXymp98qX3t60Ndex8NspLWnUat0sYbPLWnJ5SOJUgZmcfTgQpnkI0EEo1O3QJdWhEUPOlNIM3os7QBKTW/W+OsuUTt90DJlLiBisdcqT8bxJxbtwU+IkOVSFrYvLpkiuEleMmBJHLxAgN8+yIQSkIZMUyWGu65BZI+NOtR/jCyF48+VKX75SrwbuWkW0/7OTzoQ0uIls+kcVtfb2+hjKVasAdqvFy7MJuSD72mKyCO+EHw0YRki/50bZBCrczA1kYZsDFSi/Rxhedrk7g1NJWhg9KOHWaAMQhqjC1VA=',
             'val': 'eyJ0aW1lc3RhbXAiOjE1MDkzMDQ0NTkwMzgsInByb2ZpbGVJZCI6IjRiZDIyNTQyZmM0MDQyZGViOTRjMjAzOWI0MjYyNTliIiwicHJvZmlsZU5hbWUiOiJzdGFybG9yZDIwMTYiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2YxMzY4Y2RkODI0NmM0ZjNjZDFjMWNjMGE5NGQ4YWZlNWY3ZmM3MjM4YjE2ZTQxNjIyM2IxNjg1NDNhNWZhOSJ9fX0=',
             'trail': '',
             'op': 'false',
             'speech':"I will kill my brother.",
             'powers': array(
                 "/buff",
                 "/jump 0-6",
                 "/run 0-7", 
                 "/haste 0-5",
                 "/mindcontrol <playername>"
                 "/forcechocke <playername>",
                 "/thru",
                 "when you punch a player empty handed, your victim is stuck by lightning (force lightning)"
              ),
              'buffs': array(
                  "/effect ". @plr ." 5 9999 15 true", 
                  "/effect ". @plr ." 10 9999 15 true",
                  "/give ". @plr ." minecraft:iron_sword 1 16:75 19:9 name:&5S&0a&5s&0u&5k&0e&5s_&5K&0a&5t&0a&5n&0a",
                  "/give ". @plr ." minecraft:iron_boots 1 9:2 name:§5S§0a§5s§0u§5k§0e&5s_&5S&0l&5i&0p&5p&0e&5r&0s
                  "/effect ". @plr ." 11 9999 10 true",
                  "/effect ". @plr ." 25 9999 5 true", 
                  "/effect ". @plr ." 21 9999 9 true",
              )
          )  
