@plr = player()


@hero = associative_array(
            'name': '§2Y§6a§m§6c§2ha',
            'class': 'yamcha',
            'sig': 'eyJ0aW1lc3RhbXAiOjE1MTgxMzMwNDQ4ODgsInByb2ZpbGVJZCI6IjA4ODBlY2NjZmVlZDRhMmY5ZTIyZDhmNzIxZjM5MTNlIiwicHJvZmlsZU5hbWUiOiJaZUVuZm9yY2VyIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mMWY2Y2ZiNDM2Njg2NGU1YmE1ODdmZTI1ZTRiNTE3ZTY3ODM3MTJkYWFmNWE2ZWVkYWE2OTMyOWYyNGE1ODAifX19
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTYxNDI3Mzc0MjMsInByb2ZpbGVJZCI6ImYzMDc3ZTY3OWNmODRiNDhiNDg4NGE1ZmQ4OTlkNjk3IiwicHJvZmlsZU5hbWUiOiJLYXJtYTAwMDEiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzMyNWFiNzBlNGExOGFjNGZhM2FlMzhmODdkMDg3YTliNjQ3NzY2YzNhNDZjYmQ1NDQ2MmUzMWJiZDgxM2FkYyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "No WAY!!",
            'powers': array(
                "/buff",
                "/jump <0-2>",
                "/run <0-2>",
                "/haste <0-2>",
                "/carryplayer <player>",
                "/dismountplayer"
            ),
            'buffs': array(
            )
        )
