Attachment_Remove_Message: "&7Successfully removed attachment."
Attachment_Add_Message: "&7Successfully added attachment #ATTACHMENT#."
Attachment_No_Gun_In_Hand_Message: "&7You have to be holding a gun to add attachments."
No_Attachments_For_Gun_Message: "&7This gun does not have any attachments."
No_More_Attachments_For_Gun_Message: "&7You can not add more attachments for this gun."
Not_This_Attachment_For_Gun_Anymore_Message: "&7You can not add this attachment since #ATTACHMENT# denies it."
Already_Has_This_Attachment_Message: "&7Weapon already has this attachment."
Attachment_Fill_Empty_Slots_Item:
    Item_Type: "160:7"
    Item_Name: "&c<&7-&c>"
Add_Attachment_Item:
    Item_Type: "291"
    Item_Name: "&c<-> &7Add attachment &c<->"
    Item_Lore:
    - "&7Click me to add attachment."
    Item_Durability: 65