debug: false
authkey: c573009468d57d0ba544003ad5aa9352fb4faaa649b449eb57
https: true
autoupdate: true
collectplayerstats: true
sendstatsinterval: 5
listenforbans: true
statscollected:
  player:
    travel: true
    blocksbroken: true
    blocksplaced: true
    kills: true
    deaths: true
    xp: true
  server:
    creeperexplosions: true
    playerkicks: true
buycommand: buy
usebuygui: true
loggingenabled: true
