@plr = player()





@hero = associative_array(

            'name': '§6Luffy',

            'class': 'Luffy',

            'sig': 'kM2xuJi8KuQzex2eXBJobzJo5jbskBI2E4rS19KJf1zCo3Y9T8ayiEVtSkOI/cKTYXxcXi/4SdhPWfNdmZ+Dn7tMaF9JVKez4LgbrxsYxDKzo5kC+ksL/Kqq+dJDzdyH0RopeOIV/frSBtY/tcpc+mbpSPWrtZkc05QDBIs62Ug8UX88OBMEdiu2gOo5t8ptxy/42syshJRvTMlM7tDV7wYIH81DSeIlEcOmF74UdCcl+yzH00YN6PTywlKwcGRBv0U3vSog3KHAJ+UbFJKmh6h4Ky9/4VWbhagLpqikv+KCm66g4VMyOHZG11UU7gw3DUZDxy8KNci4M2K6Ir8Jb2byAl1QXLLmJHcaPkQo1XIAuIZIjtV0V+pEGFXvIp61Yt4vQFqIN5fl5+MWvYXA6bkirLDS8leBxV3WiQj9CcP/z5Xjp0T7VPgPuj1jmhmJckBz0kfVBidwnPl6xE40JH6reaeVLZqDm572i3CcdYYZmhP1g4eNSOj86o4pDqgc04bEkUimEYY+IQfxq/2GTf0t8vNtYENvajGFocQNGn2lXW5QvzMWacw2kqDNpxBZBiucxNn6OPZ0OK7t/5F9K86Jg/MMmAk96TYmboZVHtR1CuyPryw5CqgbK+leyipSTDLfFt0r0QMvbTWnpMMdG2mQoES3ESnl/0AIRFCIroU=',

            'val': 'eyJ0aW1lc3RhbXAiOjE1MTMyMTY3MzU3NjYsInByb2ZpbGVJZCI6IjA4NWJlYjVjMzNiYzQ5MmJiOTZkNDRlZTVkOTBjNGMyIiwicHJvZmlsZU5hbWUiOiJTa3VsbHdhbGtlcjIxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83YzliMWVlZGZjNTFmZTQ2MzIyODlmZDE5NmNhOGE0NDU3YWM0NmE0ZGZkM2Q3NDNlNjUyNjBlOGFlMWIzYSJ9fX0=',

            'trail': '',

            'op': 'false',

            'speech': "I will become king of the pirates!",

            'powers': array(

                "/buff",

                "/jump 0-5",

                "/run 0-6",

                "/haste 0-5",

                "/wallrun <on/off>",

                "Look Up+Jump+Crouch to perform a wallrun."

               

            ),

            'buffs': array(

                "/effect ". @plr ." 5 9999 10 true",

                "/effect ". @plr ." 11 9999 4 true",

                "/effect ". @plr ." 21 9999 9 true",

                "/give ". @plr ." minecraft:gold_shovel 1 16:50 name:&6 Gum Gum Pistol", 
                "/give ". @plr ." minecraft:gold_axe 1 16:2 19:30 name:&6 Gum Gum Basooka",
                "/give ". @plr ." minecraft:sheild 1 34:25 name:&6 Gum Gum Finger Net"

            )

        )
