Skin_Remove_Message: "&7Successfully removed skin."
Skin_Change_Message: "&7Successfully changed skin to #SKIN#."
Skin_No_Gun_In_Hand_Message: "&7You have to be holding a gun to choose skin."
No_Skins_For_Gun_Message: "&7This gun does not have any skins."
Remove_Skin_Item:
    Item_Type: "291"
    Item_Name: "&c<-> &7Remove &c<->"
    Item_Lore:
    - "&7Click me to remove skin."
    Item_Durability: 66
Skin_Fill_Empty_Slots_Item:
    Item_Type: "160:7"
    Item_Name: "&c<&7-&c>"
Add_Skin_Item:
    Item_Type: "291"
    Item_Name: "&c<-> &7Add skin &c<->"
    Item_Lore:
    - "&7Click me to add skin."
    Item_Durability: 65