cfg-version: 11
message: '&cYou have reached the edge of this world.'
round-border: false
debug-mode: false
whoosh-effect: true
portal-redirection: true
knock-back-dist: 3.0
timer-delay-ticks: 5
remount-delay-ticks: 0
dynmap-border-enabled: true
dynmap-border-message: The border of the world.
player-killed-bad-spawn: false
deny-enderpearl: true
fill-autosave-frequency: 30
bypass-list-uuids: []
fill-memory-tolerance: 500
prevent-block-place: false
prevent-mob-spawn: false
worlds:
  survival:
    x: 4.976587380701862
    z: 3.287558850739302
    radiusX: 2500
    radiusZ: 2500
    wrapping: false
  survival_nether:
    x: 0.5
    z: 0.5
    radiusX: 1000
    radiusZ: 1000
    wrapping: false
  survival_the_end:
    x: 0.5
    z: 0.5
    radiusX: 1000
    radiusZ: 1000
    wrapping: false
  elytrapole:
    x: 20.404330547699875
    z: 20.47324582325889
    radiusX: 20
    radiusZ: 20
    wrapping: false
  alpha:
    x: -1383.5
    z: 1690.5
    radiusX: 600
    radiusZ: 600
    wrapping: false
