@plr = player()



@hero = associative_array(
            'name': '§6M§5s§6. §5G§6s§5p§6t§5l§6s§5n§6z',
            'class': 'msgsptlsnz',
            'sig': 'FVcEtTO0mGmFMQgCemVc1gfgIxLkYLeNI0c2vIX/+p9BVxuroPSEg8B5DIRDngisqXFUKxrU1C9cvlk9Yv7FrYCi3/N5CAzjM7+aXkDDMU5sLrXRBYzKNXXvPAD/hkRLcbzm+tp33H+pt0jWSbIPobdMdt8ZkapuKZZeqvbYjcpQf0u2ei22V76Uc/nX5x/37D+O6XZ/nKZFkrD4m3jIhqw0J9u6Odq6jMgKXXjPmN6WnawRR+tPZA2tL+d+hkw6BK37rxSN3gtbatrH94Xz6UOfHH3JAtGny7gUjS4WqUs+h58q4VAR5QwTLbvVzfpIXUgL0vVjW7qcFRBsPfbV8U7gTD5UFBAiIu/OnfXqVZdMLgcotqXXGf32Uh3/xuu6KLM/D25UKpq9OhTp3J6H9XWMfr22tJRePAYthLi7fw9XOug7KfwSvEKxuR1TQ6+qsggHiVneLn4MdB/yj4slhmVVIUDEMkzPWIxesWk1fZXZfq8CYkZ7KSPJ3659sOzIVRTccrhkNoHVB5p/SyAVItr/BitbWDEvKAaqek6KaYSIvWsrt0ythZd4ySHWRAN7a6jYUYgaf7/Uq2k1q2/ufqEs4hA4dg0FSUDqZbi8B3xB7orDqIgkDjbEUPoipJ3cDsJ7sj2RglYoIKmAqgx7Rvj8cHHKt4LYUVFXf+O6URU=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODEzMjUyMTI4NDksInByb2ZpbGVJZCI6ImQ2ZTI3NjI4NjE2NDQ2Njc5M2RmZGY3ZDllMWNhMmZlIiwicHJvZmlsZU5hbWUiOiJMZUhvb2RpbmkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zZDZmOWVhYmRjMmE0NWM3Mzk2ZThlNmY1YmI3NTgzYjg0OTY0YzU4OTliZjc5YjUyY2RiZTM5MjYzYWU2ZTQifX19',
            'trail': '',
            'op': 'true',
            'speech': "Ah... you're so boring.",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/gmc",
                "/fly",
                "/tp",
                "/confuse <player>",
                "/magicmsgsptlsnzmortal <playerName>"
            ),
            'buffs': array()
        )
