@questions = array(

'Why do you wish to become a coder?',
'Have you coded any heroes before? If so about how many?',
'Have you coded any powers for heroes to use on the server?',
'On a scale of 1-10 how much experience do you have with coding?',
'Where are the ms files for heroes located on github?',
'When making the name on a hero\'s ms file what symbol do you use & or §?',
'When putting powers and buffs into arrays should there be a comma on the last line?',
'Where should proof for powers be inserted for the owner to see?',
'Where can you find the sig and val to put in your ms file?',
'What is the purpose of the sig and val?',
'What is the difference between the powers array and the buffs array?',
'In the permissions file when making the prefix and suffix what symbol do you use & or §?',
'What is a permission node?',
'In the permissions file should all the groups be alligned and spaced the same?',
'What is the name of the plugin used for making lasers?',
'What is the name of the plugin used for making spells/powers?',
'What is the name of the plugin used for making the ms files?',
'What is the name of the plugin used for adding groups and permissions?'
)
