@plr = player()


@hero = associative_array(
            'name': '§dS§5t§4a§drf§5i§4r§de',
            'class': 'starfire',
            'sig': 'iMAMm26HmoPgL9LWAoM0I1tu7Gvf78DJQNsGS9Xiy+1fl75IZ99vGG6QXnbXXPvKlhOrTj24FIgQKRSj61ncEOgSDm2FtXk/WnsC7QAC0mfW0vTXZGdOqMM9x5TXWFMmgCWwx3HSPR5YSeYZWwP+uO4joHqlrFfcyP5GJjk2YbTUmanQdBMefdywmlIMp+kwd4QJSmnnwr9+ile5BIttPzahjtcjnldhx8prAbvILqcMNGUWpRK0x7GXUT2crglNGH9vPZO+gxJO8HyjQvFxps6wq6cQPBMJdKvZvCtGH7wSFU87LmnEpepzuoORloXBb20deCrq1UX27ogJSmsAM/76WekutXCYG4KOU4X6vW3Ki9peXjslEXG+OromtCWnjgui7Fn6oNekGxUKL6zzDN2aWoKwG0XP0KTvJU31wmE9SuojKdLU9TKoyzRMA3IHHzn1nBNr1edwE6B7eVpd3B96pVL3FSCrQ3fxO2Fz8Le0MBcL/OkIjZnxc7xhsEIlFSMSiIo4KZFfnSZG04uZ/W1ovZYn4uHlnBUqbmijULEdjsqGOGwN5c/DODXa+USaeNWNUwmPmMGksxTZLj0SRdkHbx/QByGM96ayKvezhzJEOBj+eDXN1Xbgmg9f4U+mktl8IuS0E3zYNGbfpw5r98l8LDieLwWtDnazPopL3Pk=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODA3MjcyODMwNDgsInByb2ZpbGVJZCI6IjI3NWFhNTQxMTg5NzQ1YzRiYWRiNzk1NTNmNjU0NTE5IiwicHJvZmlsZU5hbWUiOiJmbGFtaW5nd2FycmlvcjEwIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jYTJkZWVjMmY5NWE0YmQ3MzJmNzJmZDc5OTdmNmU3MDExYzEzODQ0MTc3MGNhYTY4ODhiMjMyMjc3OGU2In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Im bad luck... never had a choice for good.",
            'powers': array(
                "/buff",
                "/jump 0-5",
                "/run 0-3",
                "/haste 0-3",
                "Shoots fireballs with bare hand"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 11 9999 1 true",
                "/effect ". @plr ." 21 9999 9 true",
                "/shot give ". @plr ." starbolt"                
            )
        )
