MySQL:
  Enabled: false
  URI: mysql://host/database
  Username: username
  Password: password
  SyncDelay: 15minutes
OnJoinPrompt:
  MessageDelay: 20
Vote:
  Messages:
    Format:
    - ''
    - '&3&l» &f&l%QUESTION%'
    - ''
    - '&2- &a&l%CHOICES%'
    - ''
  Hover:
    Format:
    - '&c&oAre you sure?'
    - ''
    - '&c&lNOTE &7This poll does not'
    - '&7allow you to change votes!'
  Voted:
    Format:
    - '&3&l» &f&lThanks!'
    - ''
    - '&2- &7You voted for &a%CHOICE%'
    - '&2- &7You recieved &ea diamond &7for voting!'
    Reward:
      Enabled: true
      Commands:
      - /give %player% diamond 1
  RemindDelay: 5minutes
