@plr = player()


@hero = associative_array(
            'name': '§3P§9e§3r§9c§3y§9 J§3a§9c§3k§9s§3o§9n',
            'class': 'percyjackson',
            'sig': 'MUSarV636SAXrlbETAWlih5Slfm1t7FMuPsSOjWpF+Fk+TxMoBt8fEG0xws46+NpjdFq7t6wYShxvEYaPj/qm+GvHxNXuoj+6z5LSfn4T8RgsEDzISeQI7y6dXtl6Zj7YbR79wNVubB35hKInYpRhIpjrFlXn9M/AJC1EELKtUF+rbY2bIT9+WL1P9zk7EGyRAUw7DFiC+gYpZmJiUc+VrCcI6LFFD511BQU70Zxv8mf8UWiv8U5VruWYgskEPmD52m+S2iJVBc7+am89pFeEMXEmYVFcB6Jquc1Vt9Olqwu1XoZWPQHdf50vCtgAo4AftVeEbWxpp5+XbcXsTlQKCXzo9fCYGVTCi8ZV+olpGanhu5K/80aktpqfaD6+PhgjIeXIt9ciDA9FITz2mUlxrljTZjA3B071J6fgnqsYatt64up33BWpdnuvs3TUBUzWDzoOZygTXj8IDyZ7S+WM63sTOL05G9FgVXIgnZ20vBkpFpxlp9jqnkxtOSvMF7Q2iVsJKakddyDnSJNWmIO6M2FZQkr7VbID+6Td2qEnZhk2klfmaXGglKH0t8L1nXsB2a0s3p2NMl3m1FmoUZ7TrGN0h1M8NPjJwbDsIVKijOXqWnQP7FcoTXJKHAwwizR+rPGHzzGO5BvhxHh+AY111/1JlmfdQhzDG4hmMjvszc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODk4ODI3ODMyMDUsInByb2ZpbGVJZCI6IjAxMzAyOTlhNDQ4OTQyOWRiNGViNjg2NDNhNGM2YWM4IiwicHJvZmlsZU5hbWUiOiJ4RGNHYW1lciIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTI3NTg2ZTIzNDMxNmUyNzgxMjRhY2M5NmJiNmMzZWU2Yjg1M2I0YTk4NjZlNDc1MzVhNjliMzM5N2I4YzYifX19',
            'trail': '',
            'op': 'false',
            'speech': "Son of the Sea!",
            'powers': array(
                "/buff",
                "/jump 0-3",
                "/run 0-4",
                "/carryplayer",
                "/dismountplayer",
                "/haste 0-5"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 12 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/shot give ". @plr ." watershot",
                "/give ". @plr ." minecraft:diamond_sword 1 19:2 name:&3R&9i&3p&9t&3i&9d&e",
                "/give ". @plr ." minecraft:leather_helmet 1 5:50 6:1 8:3 name:&3P&9e&3r&9c&3y&9&3'&3s_&9Water_&3Helmet"
            )
        )
